### ISSUE TITLE
sloppy vendoring of "github.com/ugorji/go"

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad#4426] opened 2018-06-20 06:15 UTC
[github.com/ugorji/go](https://github.com/ugorji/go/releases) is a [semantically versioned](https://semver.org/) library.

It must be vendored by release tag instead of [random commit](https://github.com/hashicorp/nomad/blob/master/vendor/vendor.json#L296). 

Please update vendored `github.com/ugorji/go` to its latest _tagged_ release.

Thanks.

**Comment by preetapan** [comment] 2018-06-20 15:59
@onlyjob agree with your concern. However, note that we have been using this library long before they added semantic versioning, looking at https://github.com/ugorji/go/releases/tag/v.1.1-beta the first versioned release they had was in December 2017, and we haven't updated this library since July 2017. 

Now that they do have versioning, we will consider updating to 1.1.1 after regression testing it.

**Comment by onlyjob** [comment] 2018-06-20 16:16
Thank you. It is perfectly understandable how it was historically vendored by snapshot...

**Comment by onlyjob** [comment] 2019-11-07 03:27
Those who do not learn from mistakes are doomed to repeat them: #6537.
0.10.0 made this problem worse than ever...

**Comment by tgross** [comment] 2020-04-06 19:40
Closed by https://github.com/hashicorp/nomad/pull/7378

**Closed by tgross** 2020-04-06 19:40 UTC
Labels: enhancement, vendor-update
