### ISSUE TITLE
Error: Not Found Allocation of id: [object Object] was not found.

### ISSUE THREAD

**Issue by icyleaf** [hashicorp/nomad#16890] opened 2023-04-14 15:41 UTC
### Nomad version

Nomad v1.5.3
BuildDate 2023-04-04T20:09:50Z
Revision 434f7a1745c6304d607562daa9a4a635def7153f

### Operating system and Environment details

- Debian 12
- Ubuntu 12.04

### Issue

I ran nomad clusters with 4 nodes, one is metal-barel as main server node, the others is one server node and two client node created with ubuntu vm in proxmox.

Run a job with one service provide by nomad but it returns 3 services of Allocations 

### Reproduction steps

Run, change jobspec, repeat, and repeat 

#### Expected Result

One count = 1 service, then it will show one service url in traefik.

#### Actual Result

Three service of Allocations, and three url in traefik

### Job file (if appropriate)

```
resource "nomad_job" "jobs" {
      ~ allocation_ids          = [
          - "8d4ea305-5281-ab02-a8d6-a8cdcf195377",
        ] -> (known after apply)
        id                      = "media-radarr"
      ~ jobspec                 = <<-EOT
            job "media-radarr" {
              type        = "service"
              datacenters = ["bunker"]
              
          +   update {
          +     stagger      = "10s"
          +     max_parallel = 1
          +     auto_revert  = true
          +     auto_promote = true
          +     canary       = 1
          +   }
          + 
              group "radarr" {
          +     count = 1
          + 
                network {
                  port "web" {
                    to = 7878
                  }
                }
            
                service {
                  name = "radarr"
                  port = "web"
                  provider = "nomad"
            
                  tags = [
                    "traefik.enable=true",
                    "traefik.http.routers.radarr.entrypoints=web, websecure",
                    "traefik.http.routers.radarr.rule=Host(`radarr.example.com`)",
                  ]
                }
            
                task "radarr" {
                  driver = "docker"
                  config {
                    image = "lscr.io/linuxserver/radarr:latest"
                    ports = ["web"]
                    labels = {
                      "homepage.group"        = "Media"
                      "homepage.name"         = "radarr"
                      "homepage.icon"         = "radarr.png"
                      "homepage.href"         = "http://radarr.example.com"
                      "homepage.description"  = "电源资源刮削器"
                    }
                  }
            
                  env {
                    TZ      = "Asia/Shanghai"
                    PUID    = "1026"
                    PGID    = "100"
                  }
            
                  resources {
                    cpu = 200
                    memory = 256
                  }
            
                  volume_mount {
                    volume      = "radarr-config"
                    destination = "/config"
                    read_only   = false
                  }
                        
                  volume_mount {
                    volume      = "media-volume"
                    destination = "/video"
                    read_only   = false
                  }
                }
            
                volume "media-volume" {
                  type            = "csi"
                  read_only       = false
            
                  source          = "pve-media"
                  access_mode     = "multi-node-multi-writer"
                  attachment_mode = "file-system"
                }
            
                volume "radarr-config" {
                  type            = "csi"
                  read_only       = false
            
                  source          = "radarr-config"
                  access_mode     = "single-node-writer"
                  attachment_mode = "file-system"
                }
                      }
            }
        EOT
        name                    = "media-radarr"
    }
```

**Comment by lgfa29** [comment] 2023-04-18 02:08
Hi @icyleaf 👋 

Thanks for the report. Where do you see the error message you mentioned in the title?
> Error: Not Found Allocation of id: [object Object] was not found

Is this showing up in some log? And if so, which log is that? 

Any extra information that can provide would be great. Thanks!

**Comment by icyleaf** [comment] 2023-04-18 10:44
Thanks for reply, "[object Object] was not found" error wase raise by nomad ui, I think this is the result of my daily task "nomad gc".

Where can i to fetch the nomad logs? jourctl or node monistor form nomad ui?


This is another case:

I update postgres job, the previous was marked `COMPLETE` but it still publish the service.

**postgres services** return two services by 1babe023 and c6fe6b74, 1babe023 is running allocation, c6fe6b74 was killed by new update allocation.

```
ubuntu@nomad-bird-server-0:~$ nomad service info postgres
Job ID             Address              Tags                                                                                                                    Node ID   Alloc ID
database-postgres  192.168.16.125:5432  [traefik.enable=true,traefik.tcp.routers.postgres.rule=HostSNI(`*`),traefik.tcp.routers.postgres.entrypoints=postgres]  2fcffc42  1babe023
database-postgres  192.168.16.120:5432  [traefik.enable=true,traefik.tcp.routers.postgres.rule=HostSNI(`*`),traefik.tcp.routers.postgres.entrypoints=postgres]  76a8edbd  c6fe6b74


ubuntu@nomad-bird-server-0:~$ nomad alloc status 1babe023
ID                  = 1babe023-47d6-2710-6222-82a0b48e4e7c
Eval ID             = fc3dff73
Name                = database-postgres.postgres[0]
Node ID             = 2fcffc42
Node Name           = nomad-bird-client-0
Job ID              = database-postgres
Job Version         = 0
Client Status       = running
Client Description  = Tasks are running
Desired Status      = run
Desired Description = <none>
Created             = 2m44s ago
Modified            = 2m18s ago
Deployment ID       = 780c3a03
Deployment Health   = healthy

Allocation Addresses:
Label      Dynamic  Address
*postgres  yes      192.168.16.125:5432 -> 5432

Nomad Service Checks:
Service   Task     Name                       Mode         Status
postgres  (group)  service: "postgres" check  healthiness  success

Task "postgres" is "running"
Task Resources:
CPU        Memory          Disk     Addresses
0/512 MHz  18 MiB/500 MiB  300 MiB

CSI Volumes:
ID             Read Only
postgres-data  false

Task Events:
Started At     = 2023-04-18T10:34:03Z
Finished At    = N/A
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                       Type        Description
2023-04-18T18:34:03+08:00  Started     Task started by client
2023-04-18T18:34:01+08:00  Task Setup  Building Task Directory
2023-04-18T18:34:01+08:00  Received    Task received by client



ubuntu@nomad-bird-server-0:~$ nomad alloc status c6fe6b74
ID                   = c6fe6b74-a7bc-289c-1b9a-ca81585ba024
Eval ID              = f4304f50
Name                 = database-postgres.postgres[0]
Node ID              = 76a8edbd
Node Name            = nomad-bird-server-0
Job ID               = database-postgres
Job Version          = 1
Client Status        = complete
Client Description   = All tasks have completed
Desired Status       = stop
Desired Description  = alloc is being updated due to job update
Created              = 1d6h ago
Modified             = 28m45s ago
Deployment ID        = 9390140a
Deployment Health    = healthy
Replacement Alloc ID = 72983f88

Allocation Addresses:
Label      Dynamic  Address
*postgres  yes      192.168.16.120:5432 -> 5432

Task "postgres" is "dead"
Task Resources:
CPU        Memory          Disk     Addresses
0/512 MHz  21 MiB/200 MiB  300 MiB

CSI Volumes:
ID             Read Only
postgres-data  false

Task Events:
Started At     = 2023-04-18T10:00:12Z
Finished At    = 2023-04-18T10:08:03Z
Total Restarts = 1
Last Restart   = 2023-04-18T18:00:10+08:00

Recent Events:
Time                       Type              Description
2023-04-18T18:08:03+08:00  Killed            Task successfully killed
2023-04-18T18:08:03+08:00  Terminated        Exit Code: 137, Exit Message: "Docker container exited with non-zero exit code: 137"
2023-04-18T18:01:20+08:00  Killing           Sent interrupt. Waiting 5s before force killing
2023-04-18T18:00:12+08:00  Started           Task started by client
2023-04-18T18:00:10+08:00  Restarting        Task restarting in 0s
2023-04-18T18:00:10+08:00  Terminated        Exit Code: 137, Exit Message: "Docker container exited with non-zero exit code: 137"
2023-04-18T17:59:57+08:00  Restart Signaled  User requested running tasks to restart
2023-04-17T12:27:45+08:00  Started           Task started by client
2023-04-17T12:27:44+08:00  Task Setup        Building Task Directory
2023-04-17T12:26:09+08:00  Received          Task received by client
```

**Comment by lgfa29** [comment] 2023-04-18 20:44
Ahh I see it now, so the problem is that the service instance for allocations that are not running anymore are still being returned by Nomad service discovery, is that right?

If this is the case, then I think this is a duplicate of https://github.com/hashicorp/nomad/issues/16616 which is still being investigated. 

Those `error: service registration not found` messages may be a red herring and are also still being investigated (https://github.com/hashicorp/nomad/issues/16286).

I'm going to close this as a duplicate of #16616. Feel free to add any additional context you may have in that issue 🙂

**Closed by lgfa29** 2023-04-18 20:44 UTC
Labels: type/bug, theme/networking, stage/duplicate, theme/service-discovery/nomad

**Comment by icyleaf** [comment] 2023-04-19 02:47
I'll continue to discuss in that issue.

BTW, If you have time, would you follow up on the issues and PRs of 【[terraform-provider-nomad](https://github.com/hashicorp/terraform-provider-nomad), it's a bit out of step with the latest version of nomad, as you are also the maintainer there, thanks.

**Comment by icyleaf** [comment] 2023-07-30 07:24
For now, i written a script to clean all invalid services.

<img width="918" alt="iShot_2023-07-30_15 23 56" src="https://github.com/hashicorp/nomad/assets/17814/4b6d3505-8a94-4f28-8d2c-70b82eb5c704">
