### ISSUE TITLE
Nomad agent process is not exiting on fatal errors

### ISSUE THREAD

**Issue by rubenharutyunov** [hashicorp/nomad#10486] opened 2021-04-30 16:25 UTC
### Nomad version
Nomad v1.0.1 (c9c68aa55a7275f22d2338f2df53e67ebfcb9238)

### Operating system and Environment details
Servers - `ubuntu-focal-20.04-amd64-server-*` in AWS
Clients - `Windows_Server-2019-English-Full-ContainersLatest-*` in AWS

### Issue
We are running nomad clients in Windows using [NSSM](https://nssm.cc). Our Nomad jobs are consuming a big amount of memory that causes Nomad agents to crash with `fatal error: out of memory` message. In case of a crash, the service should be restarted, however, it doesn't happen sometimes. There are no new logs coming from Nomad, the client is reported as down, metrics endpoint is not working, but Windows service reports itself as `Running`. In such cases there's a Nomad process running (sometimes even two processes).
The manual fix is to kill the process(es) and restart the Nomad agent service. I think the cause of the issue can be that the agent sometimes not exiting in situations it can't recover from (like OOM, in this case).

### Reproduction steps
The issue is really hard to reproduce for us. We have ~3000 nodes in Nomad and this issue happens only 3-4 times per week. I tried to reproduce it by filling a memory and causing  `fatal error: out of memory` but the agent restarted itself successfully then.

#### Expected Result
Nomad agent always exits on unrecoverable errors

#### Actual Result
There are running Nomad processes after unrecoverable errors

**Comment by tgross** [comment] 2021-04-30 18:15
Hi @K-DOT! A couple things that come to mind from your issue.

Once Nomad has crashed, it's the responsibility of the service manager to restart it; there's not much Nomad can do at that point. Is the service in a crash-loop where it's restarting over and over again? I'd be particularly interested to see if you're seeing the "funlock" errors that we're seeing in https://github.com/hashicorp/nomad/issues/10086. If that's the case, unfortunately I don't have a good answer for you at the moment other than to let you know we're investigating still.

> In such cases there's a Nomad process running (sometimes even two processes).

Are these the Nomad agent process, or might they be the log shipper process (which is the same binary)?

**Comment by K-DOT** [comment] 2021-05-05 18:42
Hi @tgross. We have a couple of "funlock" errors but I don't think they actually cause this problem because the problem happens more often.
>Once Nomad has crashed, it's the responsibility of the service manager to restart it; there's not much Nomad can do at that point. Is the service in a crash-loop where it's restarting over and over again? 

Sure, the service manager is configured to restart the service on crash but the problem is that there's an active Nomad process after the crash and the service manager sees the service as running because of that. So my assumption is maybe the Nomad process doesn't exit in such cases.

**Comment by notnoop** [comment] 2021-06-02 12:38
@K-DOT  Sorry for the long delay. I'm investigating this issue further now. The following will be immensely helpful for debugging the issue for the next time it happens:

* The full logs of the agent after failed restart. To ensure you get all the logs, I'd suggest running the nomad agent CLI command directly, e.g. `nomad agent -config c:\...\config.hcl` and capturing the output.
  * In particular, I'd expect seeing a `Error starting agent:` lines that will provide some leads.

* The "corrupted" state.db file from the client data-dir directory, if it doesn't contain super sensitive info. You can send it to nomad-oss-debug@hashicorp.com or our Enterprise support.

Thank you so much for your patience.

**Comment by tgross** [comment] 2024-10-18 19:24
I'm doing some other Windows investigations and it looks like this issue has been waiting on more information for a long time. Going to close this out as unresolved.

**Closed by tgross** 2024-10-18 19:24 UTC
Labels: type/bug, stage/waiting-reply, theme/platform-windows
