### ISSUE TITLE
docker driver: doesn't accept 'digest' tags

### ISSUE THREAD

**Issue by justenwalker** [hashicorp/nomad#4290] opened 2018-05-11 21:36 UTC
### Nomad version

Nomad v0.7.1+ent (83ac1d7316a79aacb09d349298e14e23a0aa9853)

### Operating system and Environment details

Linux ... 4.13.0-1014-azure #17-Ubuntu SMP Fri Apr 6 02:37:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Issue

the nomad docker driver does not allow digest tags to be used when running an image.
It will fail to recognize the `@sha256:abcdef....` portion of the image and default to using `latest`

### Reproduction steps

Run any job using the `@sha256:...` digest instead of a tag

For example: `library/hello-world@sha256:f5233545e43561214ca4891fd1157e1c3c563316ed8e237750d59bde73361e77`

**Comment by jippi** [comment] 2018-05-14 14:59
isn't this duplicate of #4211 ? :)

**Comment by justenwalker** [comment] 2018-05-14 15:01
Yeah, looks like it - sorry; I thought I scanned the issues to check if it was already reported. I guess 'digest' didn't include your issue :D

**Closed** 2018-05-21 17:46 UTC
Labels: driver/docker, enhancement
