### ISSUE TITLE
Increase in "Vault: server failed to derive vault token: Allocation "xxx" does not exist" errors after 1.06 to 1.1.10 upgrade

### ISSUE THREAD

**Issue by dpn** [hashicorp/nomad#12261] opened 2022-03-10 23:47 UTC
### Nomad version
Output from `nomad version`

Previous: `Nomad v1.0.6 (592cd4565bf726408a03482da2c9fd8a3a1015cf)`
Current: `Nomad v1.1.10 (028cef251052e629db4321abc5dfd415f6045b78)`

### Operating system and Environment details

RHEL 7
Control plane (per region): 3x 32 Core, 128G RAM
Clients: On the order of hundreds of clients per region, c1_m2-sized hosts all the way up to c32_128. Mix of EC2 and colocated hardware.

### Issue

As we've been upgrading our clusters from `1.0.6` to `1.1.10`, we've been seeing a significant increase in the number of allocations failing to start with the following error:

```
ID                  = 0d4aaf0a-2c78-74cc-a39f-ead09ca53fdb
Eval ID             = 5681f411
Name                = a-nomad-job/dispatch-1646951139-93b8a50a.a-job[0]
Node ID             = 29ff4074
Node Name           = a-nomad-node.somewhere.someplace
Job ID              = a-nomad-job/dispatch-1646951139-93b8a50a
Job Version         = 19
Client Status       = failed
Client Description  = Failed tasks
Desired Status      = stop
Desired Description = alloc was rescheduled because it failed
Created             = 45s ago
Modified            = 22s ago

Task "a-nomad-job-task" is "dead"
Task Resources
CPU       Memory  Disk     Addresses
7200 MHz  16 GiB  300 MiB

Task Events:
Started At     = N/A
Finished At    = 2022-03-10T22:27:45Z
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                       Type        Description
2022-03-10T14:27:48-08:00  Template    Missing: vault.read(super/secret/secret), vault.read(a/different/super/secret/secret)
2022-03-10T14:27:45-08:00  Killing     Vault: server failed to derive vault token: Allocation "0d4aaf0a-2c78-74cc-a39f-ead09ca53fdb" does not exist
2022-03-10T14:27:45-08:00  Task Setup  Building Task Directory
2022-03-10T14:27:45-08:00  Received    Task received by client
```

For an idea as to the rate of increase of this error, in a different region with similar scale and workloads, we've received this error 211 times in the previous 13 days, or about 16 per day. In one of the recently upgraded regions, we've seen this error 687 times in the past 30 hours, something like 550 per day.

We've seen this increase in failures correlate with upgrades across 3 regions so far. We primarily see it affect batch jobs (likely due to the comparatively high rate of dispatches compared to other job types), but does also affect system and service jobs.

### Reproduction steps

Upgrade to 1.1.10 from 1.0.6

#### Expected Result

Allocations should come up healthy with a similar (or better!) failure rate to 1.0.6

#### Actual Result

Allocation failures are significantly higher.

### Job file (if appropriate)

We see this across jobs of all types, let me know if this would be valuable and I'll redact some specs.

### Nomad Server logs (if appropriate)

Just a snippet, happy to grab more if it's useful:
```
    2022-03-10T23:04:55.790Z [ERROR] nomad.client: DeriveVaultToken failed: recoverable=false error="Allocation "b761fc5f-b204-fed2-de3e-495f705e8f77" does not exist"
```

### Nomad Client logs (if appropriate)

```
Mar 10 16:25:06 a-nomad-host nomad[12284]: 2022-03-10T16:25:06.176-0700 [INFO]  client.alloc_runner.task_runner.task_hook.logmon.nomad: opening fifo: alloc_id=eeb4713b-d242-30c2-b8b7-7e86c8758232 task=a-nomad-task @module=logmon path=/var/lib/nomad/alloc/eeb4713b-d242-30c2-b8b7-7e86c8758232/alloc/logs/.a-nomad-task.stdout.fifo timestamp=2022-03-10T16:25:06.176-0700
Mar 10 16:25:06 a-nomad-host nomad[12284]: 2022-03-10T16:25:06.176-0700 [INFO]  client.alloc_runner.task_runner.task_hook.logmon.nomad: opening fifo: alloc_id=eeb4713b-d242-30c2-b8b7-7e86c8758232 task=a-nomad-task @module=logmon path=/var/lib/nomad/alloc/eeb4713b-d242-30c2-b8b7-7e86c8758232/alloc/logs/.a-nomad-task.stderr.fifo timestamp=2022-03-10T16:25:06.176-0700
Mar 10 16:25:06 a-nomad-host nomad[12284]: 2022-03-10T16:25:06.181-0700 [ERROR] client.vault: error deriving vault tokens: error="Allocation "eeb4713b-d242-30c2-b8b7-7e86c8758232" does not exist"
Mar 10 16:25:06 a-nomad-host nomad[12284]: 2022-03-10T16:25:06.181-0700 [ERROR] client.vault: error deriving token: error="Allocation "eeb4713b-d242-30c2-b8b7-7e86c8758232" does not exist" alloc_id=eeb4713b-d242-30c2-b8b7-7e86c8758232 task_names=[a-nomad-task]
Mar 10 16:25:06 a-nomad-host nomad[12284]: 2022-03-10T16:25:06.181-0700 [ERROR] client.alloc_runner.task_runner.task_hook.vault: failed to derive Vault token: alloc_id=eeb4713b-d242-30c2-b8b7-7e86c8758232 task=a-nomad-task error="Allocation "eeb4713b-d242-30c2-b8b7-7e86c8758232" does not exist" server_side=true
Mar 10 16:25:06 a-nomad-host nomad[12284]: 2022-03-10T16:25:06.182-0700 [INFO]  agent: 2022/03/10 16:25:06.182627 [DEBUG] (runner) final config: {redacted}
Mar 10 16:25:06 a-nomad-host nomad[12284]: 2022-03-10T16:25:06.184-0700 [INFO]  client.gc: marking allocation for GC: alloc_id=eeb4713b-d242-30c2-b8b7-7e86c8758232
Mar 10 16:25:10 a-nomad-host nomad[12284]: 2022-03-10T16:25:10.185-0700 [WARN]  client.alloc_runner.task_runner.task_hook.logmon.nomad: timed out waiting for read-side of process output pipe to close: alloc_id=eeb4713b-d242-30c2-b8b7-7e86c8758232 task=a-nomad-task @module=logmon timestamp=2022-03-10T16:25:10.185-0700
Mar 10 16:25:10 a-nomad-host nomad[12284]: 2022-03-10T16:25:10.185-0700 [WARN]  client.alloc_runner.task_runner.task_hook.logmon.nomad: timed out waiting for read-side of process output pipe to close: alloc_id=eeb4713b-d242-30c2-b8b7-7e86c8758232 task=a-nomad-task @module=logmon timestamp=2022-03-10T16:25:10.185-0700
Mar 10 16:27:03 a-nomad-host nomad[12284]: 2022-03-10T16:27:03.728-0700 [INFO]  client.gc: garbage collecting allocation: alloc_id=eeb4713b-d242-30c2-b8b7-7e86c8758232 reason="new allocations and over max (50)"
Mar 10 16:27:03 a-nomad-host nomad[12284]: 2022-03-10T16:27:03.729-0700 [INFO]  client.gc: marking allocation for GC: alloc_id=eeb4713b-d242-30c2-b8b7-7e86c8758232
```

**Comment by dpn** [comment] 2022-03-17 18:29
We've discovered that adding a patch to allow this specific failure to retry instead of immediately fail has "fixed" this issue for us- we just wrap these two checks https://github.com/hashicorp/nomad/blob/main/client/allocrunner/taskrunner/vault_hook.go#L307 with another that isolates this particular issue and allows it to retry a couple times before actually failing and our failure rates have dropped back to, or possibly even below our previous `1.0.6` values. Our logs indicate that one retry has been enough in every instance that we've managed to work around since applying this patch.

Of course realize this is just a band-aid for what is actually just a _symptom_ of the underlying root cause, which is that somehow the servers are able to schedule an allocation on a client without it being persisted in their state before the call back from the client to get Vault tokens executes. I'm a bit more gun shy about diving into those depths of the code base as I'm admittedly not terribly familiar with it and have some concerns about introducing unintended side effects, but it's something we're considering given this situation appears to be unique with our setup given I don't see any other similar issues reported. So, entirely possible we're holding something wrong here but it's still surprising to us that a version bump exacerbated this issue given our relatively low rate of reproduction on `1.0.6`.

**Comment by tgross** [comment] 2022-03-28 15:18
Hi @dpn! Your reasoning around retries seems clear, but after reviewing the code I didn't find any obvious changes between 1.0.6 and 1.1.0, so there may be some timing-related issue here that's causing the problem to appear more often. Even our Vault SDK versions didn't change between [1.0.6](https://github.com/hashicorp/nomad/blob/v1.0.6/go.mod#L85-L86) and [1.1.0](https://github.com/hashicorp/nomad/blob/v1.1.0/go.mod#L87-L88). Something that might be interesting is that there are two different error conditions here. One of the code paths will log `error=invalid response`. In Nomad 1.0.6 were the errors you were seeing that error or the same "allocation does not exist" error you're seeing now?

> Of course we realize this is just a band-aid for what is actually just a symptom of the underlying root cause, which is that somehow the servers are able to schedule an allocation on a client without it being persisted in their state before the call back from the client to get Vault tokens executes. 

Hm, that's _very_ interesting... the workflow is that the scheduler creates the allocation and the plan applier (on the leader) asserts that it's valid. The clients poll the leader for new allocations, and do so with `AllocStale = true`, which means they can get the list from the follower they're connected to and not forward to the leader. The leader replicates to a quorum of followers before it decides the raft entry has been committed. 

Meanwhile, the error message you're seeing is coming from [`node_endpoint.go#L1477-L1485`](https://github.com/hashicorp/nomad/blob/v1.1.0/nomad/node_endpoint.go#L1477-L1485). This is `AllowStale = false` so the RPC always gets forwarded to the leader. It seems implausible that the client could be getting an allocation _and_ sends the `Node.DeriveToken` RPC before the leader can commit. There's a couple things we can investigate here:

* Can you take a look at the `fsm.apply` times for your nodes? I suspect replication may be slow on one or more followers and this is causing the stale read to be more stale than usual.
* I'm going to double-check on my understanding of how stale queries are supposed to work, to make sure that I understand this case with possibly-ahead followers correctly. I didn't think this situation was possible but it's the only explanation I can think of given the evidence.
* If my theory is correct, we could set `AllowStale = false` on all the requests coming from `client/client.go`, which would assert they're all getting threaded through the leader. Alternately, we could set a wait index on the requests so that we know any request we make it has at least that index (so that the `Node.DeriveToken` is at least as fresh as the `Node.GetAllocs`).

**Comment by dpn** [comment] 2022-03-28 19:21
Hey @tgross! hope all is well with you!

>  ...but after reviewing the code I didn't find any obvious changes between [1.0.6](https://github.com/hashicorp/nomad/blob/v1.0.6/go.mod#L85-L86) and [1.1.0](https://github.com/hashicorp/nomad/blob/v1.1.0/go.mod#L87-L88), so there may be some timing-related issue here that's causing the problem to appear more often. Even our Vault SDK versions didn't change between 1.0.6 and 1.1.0.

Yeah we came to the same conclusion during our investigation- we considered that there may be some nuance here that we don't understand fully but it's sounding like that may not be the case.

> Something that might be interesting is that there are two different error conditions here. One of the code paths will log error=invalid response. In Nomad 1.0.6 were the errors you were seeing that error or the same "allocation does not exist" error you're seeing now?

We still have a few 1.0.6 clusters as the discovery of this issue halted our 1.1.10 rollout and from what I'm seeing we're seeing the same "allocation does not exist" error there:

```
    2022-03-28T17:44:54.560Z [ERROR] nomad.client: DeriveVaultToken failed: recoverable=false error="Allocation "7890e0ea-4b23-a49f-e198-1a6d2951ef15" does not exist"
```

> The clients poll the leader for new allocations, and do so with AllocStale = true, which means they can get the list from the follower they're connected to and not forward to the leader. The leader replicates to a quorum of followers before it decides the raft entry has been committed.

Thanks for this context, totally makes sense.

> It seems implausible that the client could be getting an allocation and sends the Node.DeriveToken RPC before the leader can commit.

Yeah totally. We're definitely scratching our heads at this one- my claim is based on the mental model I have of this which.. may not be entirely accurate given my very basic understanding of the codebase.

> Can you take a look at the fsm.apply times for your nodes? I suspect replication may be slow on one or more followers and this is causing the stale read to be more stale than usual.

Yes!

![Screen Shot 2022-03-28 at 11 35 25](https://user-images.githubusercontent.com/177607/160465348-e21ceae4-f8aa-4b2a-b111-36d0f412943c.png)

For extra context the large spikes in this screenshot are the leader nodes from two separate clusters. Deployments to these two DCs went out:

7 March: Blue
9 March: Green

> If my theory is correct, we could set AllowStale = false on all the requests coming from client/client.go, which would assert they're all getting threaded through the leader. Alternately, we could set a wait index on the requests so that we know any request we make it has at least that index (so that the Node.DeriveToken is at least as fresh as the Node.GetAllocs), like so:

Yeah this is an interesting idea- our understanding based on this: https://github.com/hashicorp/nomad/blob/v1.1.10/nomad/node_endpoint.go#L1474 was that these queries _should_ always go to the leader, but were definitely not aware that it may be possible for a follower to be ahead of the leader.

If it's helpful, we'd be happy to give this patch a try on some of our high-traffic nodes.

We've been keeping a close eye on this issue, so I do have some more information to share which may be relevant to this investigation. I'll follow up with another post this one's getting pretty long as it is.

**Comment by tgross** [comment] 2022-03-28 19:29
> but were definitely not aware that it may be possible for a follower to be ahead of the leader.

So I had a conversation with some of our raft gurus and there's some subtle details on that. No node _starts_ applying the log entry until a quorum of nodes has the log entry replicated. But if the leader stalls on applying the entry to its FSM it's possible a follower could complete applying the entry to its FSM before it finishes. So everyone has the same log entries but it's not reflected on the in-memory snapshot. And this could result in the behavior we're seeing here, but the consensus was this is implausible without very large spikes in the FSM apply times. But it looks like that may be what's happening to you. Are the leaders under an unusual amount of load? (Particularly CPU?)

**Comment by dpn** [comment] 2022-03-28 20:23
So one question that might arise from the metrics screenshot posted in the previous post: What changed on the 25th which seems to have "clamped" this slow apply rate down significantly in the one DC, while also appearing to eliminate this in the other DC. Story time:

We have a set of batch jobs that dispatch at a relatively high rate compared to the rest of our workloads in the cluster. These dispatches average out to approximately 4-5/s, although they are scheduled in larger bursts based on the polling interval of the team's scheduler. As we run OSS Nomad, we don't have resource limits so our strategy has been to have the the team implement WIP limits in their scheduling to avoid overloading the cluster. Obviously not ideal as we'd prefer to enforce this on our end, but once we ironed out the initial implementation issues it's been working generally well enough for us over the past 1.5-2 years or so.

We have alerting built around cluster metrics, and 6 months or so after this solution was put into production, we started receiving alarms indicating we were queuing up a large number of jobs in 'pending' state in the DCs that would later be impacted by the 1.1.10 upgrade. We tracked this large job queue back to these batch jobs and asked the team to investigate their scheduler to fix their high rate of dispatches. The clusters didn't seem to mind and we hadn't received any complaints from other teams regarding degraded service so we left the team to schedule this work. (Surprise, they never did- But anyways..).

During our continued investigation into this 1.1.10 upgrade issue, we finally discovered the root cause for this which was a combination of GH-10222 and their scheduler incorrectly handling a negative number of running jobs which led to it attempting to keep their desired number of jobs in flight PLUS the negative number of running jobs. The band-aid we put in on the 25th was to run a daily cron job to reconcile job summaries which has remediated this issue in our most heavily impacted DCs, although there is that one straggler DC evident in the above metrics which we're still actively investigating.

You can see the effect of this here:

![Screen Shot 2022-03-28 at 12 36 23](https://user-images.githubusercontent.com/177607/160476206-7abc0def-4dba-4625-8bfd-f8a90285ef3f.png)

We're thinking that this excessive number of jobs (and evaluations) stuck in pending was at least partially (if not totally) responsible for our struggles after upgrading to 1.1.10. There's still some unanswered questions as to _why_ it took the upgrade to reveal this issue given the lack of obvious changes which would lead to this behavior, so that's a bit of a mystery.

> And this could result in the behavior we're seeing here, but the consensus was this is implausible without very large spikes in the FSM apply times. But it looks like that may be what's happening to you.

Yep it definitely appears this is the issue- additionally the fact that it _is_ the leader experiencing this lag in these DCs seems to reinforce your theory around this.

>  Are the leaders under an unusual amount of load? (Particularly CPU?)

Yeah so we also keep a close eye on this- interestingly we _don't_ seem to be seeing an increase in CPU utilization or load correlating with the rollouts- in fact the CPU utilization appears to have gone down on the followers and stayed relatively consistent (possibly a slight down trend, even) on the leader:

![Screen Shot 2022-03-28 at 13 08 54](https://user-images.githubusercontent.com/177607/160479359-52b8b9ab-1033-4906-ae5a-567b8e091bb2.png)

The rollout on 9 March is fairly visible on this while the subsequent fail-overs on the 10th and 11th were related to our initial steps to diagnose this issue.

System load appears to be fairly consistent as well post-upgrade:

![Screen Shot 2022-03-28 at 13 17 11](https://user-images.githubusercontent.com/177607/160480020-d3fb8bb8-c91d-460d-a8a4-aefc2c621ea4.png)

I suppose if you squint hard enough you may be able to make the argument that 1.1.10 has less load spikes, but.. really I'd be more inclined to believe that's just an artifact of Prometheus and it's metrics collection.

**Comment by tgross** [comment] 2022-03-29 13:43
Thanks for all that context @dpn. Clearly we need to figure out what's going on with #10222 sooner rather than later. The FSM apply metric we're looking at here is when the node has a log on disk already and is applying its value to the in-memory state store, so if we're not seeing unusual CPU load (which I agree from your metrics we're not), then I suspect we've got some goroutine contention going where the leader is doing so much other work that it's spending a bunch of overhead swapping between goroutines instead of making forward progress.

If you were to enable debug mode (`enable_debug = true`) and then get a short trace of 10-15 seconds on a leader that's experiencing this issue, that might help us figure out where the contention is coming from. You can get that from `$NOMAD_ADDR/debug/pprof/trace?debug=1&seconds=15`

**Comment by tgross** [comment] 2022-03-29 13:45
Also, I've got https://github.com/hashicorp/nomad/pull/12396 open and I've at least smoke tested it to make sure it doesn't blow up in our face, if you want to give that a try. I'm going to do some additional testing here to see if I can artificially create a slowed-down FSM apply on a leader that exercises this idea.

**Comment by dpn** [comment] 2022-03-30 15:52
Thanks! I'll gather that debug info back to you shortly and we'll get that patch rolled out to one of our nodes and let you know how it looks.

**Comment by dpn** [comment] 2022-03-30 19:36
So we gave #12396 a shot on one of our nodes and it hasn't done the trick:

```
# End of the logs before bounce, you can see our band-aid successfully retrying prior to restart to pick up the new version:
Mar 30 13:18:12 a-nomad-client.some.tld nomad[33180]: 2022-03-30T13:18:12.436-0600 [ERROR] client.alloc_runner.task_runner.task_hook.vault: failed to derive Vault token: alloc_id=51394406-55b4-2b16-228f-59b9bf8fa8f1 task=some-nomad-task-job-task error="Allocation "51394406-55b4-2b16-228f-59b9bf8fa8f1" does not exist" recoverable=true backoff=5s
Mar 30 13:18:48 a-nomad-client.some.tld nomad[33180]: 2022-03-30T13:18:48.791-0600 [ERROR] client.alloc_runner.task_runner.task_hook.vault: failed to derive Vault token: alloc_id=766ca5fa-e09b-26cb-697e-2b673a4d951b task=some-nomad-task-job-task error="Allocation "766ca5fa-e09b-26cb-697e-2b673a4d951b" does not exist" recoverable=true backoff=5s

# Restart
Mar 30 13:23:35 a-nomad-client.some.tld systemd[1]: Unit nomad.service entered failed state.
Mar 30 13:23:35 a-nomad-client.some.tld systemd[1]: nomad.service failed.

# Not immediate, but of about 15 or 20 allocations on this node we did see two failures, after which we rolled this back
Mar 30 13:25:50 a-nomad-client.some.tld nomad[7984]: 2022-03-30T13:25:50.857-0600 [ERROR] client.alloc_runner.task_runner.task_hook.vault: failed to derive Vault token: alloc_id=97f94374-390c-415b-7834-43325425181a task=some-nomad-task-job-task error="Allocation "97f94374-390c-415b-7834-43325425181a" does not exist" server_side=true
Mar 30 13:26:23 a-nomad-client.some.tld nomad[7984]: 2022-03-30T13:26:23.249-0600 [ERROR] client.alloc_runner.task_runner.task_hook.vault: failed to derive Vault token: alloc_id=4ad4b5ae-991e-d2e7-e753-529c8a28368f task=some-nomad-task-job-task error="Allocation "4ad4b5ae-991e-d2e7-e753-529c8a28368f" does not exist" server_side=true
```

**Comment by tgross** [comment] 2022-03-31 13:39
> Email with the trace should be on its way to nomad-oss-debug@hashicorp.com.

Received, thanks! There's a lot to dig into here so it may take me a little bit to get back with an analysis. 

> We gave https://github.com/hashicorp/nomad/pull/12396 a shot on one of our nodes and it hasn't done the trick:

Sorry to hear that. That may throw a wrench into our theory about FSM Apply, or I may need to do some more testing about whether that patch could even properly fix the problem. I'll get back to y'all as soon as I can with more info.

**Comment by tgross** [comment] 2022-04-05 20:02
Cross-linking to https://github.com/hashicorp/nomad/issues/12465 because although it's not the same error message or symptoms, they smell potentially related.

**Comment by dpn** [comment] 2022-08-05 00:30
@tgross Thanks again for all of your help with this one. We gave the 1.3.2 client against our 1.1.10 servers a try today and didn't see any of these issues. So from our end we've got band-aids and an apparently an upgrade path that should work for us so I'm going to close this one out.

**Comment by hntrmrrs** [comment] 2022-09-02 11:07
I'd like to re-open this as it is still an issue with a cluster running with agents all running 1.3.5 (servers and clients). The cluster in question frequently (3-4 hours per day) experiences sustained high batch scheduler load. High batch scheduler load corresponds to higher raft commit times and a higher incidence of the "Vault: server failed to derive vault token: Allocation xxx-123-bbb does not exist" errors mentioned in the description. Here are some charts:

![image](https://user-images.githubusercontent.com/4218/188123941-3b06a75e-e687-429f-b999-4669cf2e8b3b.png)

"vault: x" are the quantiles for the `nomad_nomad_client_derive_vault_token` metric.
"plan: x" are the quantiles for the `nomad_nomad_worker_invoke_scheduler_batch` metric.

Unhelpfully I only just started capturing the logs indicating this particular failure in our metrics system so will post better correlated results later.

![image](https://user-images.githubusercontent.com/4218/188125816-969d886d-5a25-47e7-816b-b2babbe9d1aa.png)

`apply` is the 90th centile of the `nomad_raft_fsm_apply` metric
`plan_evaluate` is the 90th centile of the `nomad_nomad_plan_evaluate` metric

And the `nomad_nomad_plan_wait_for_index` 99th centile seems to very occasionally spike:

![image](https://user-images.githubusercontent.com/4218/188126145-044cb296-12b6-4a20-a075-1243ec54c023.png)

In these states the leader is at maximum CPU utilisation (dominated by user time, occasionally as much as 5% iowait). I don't have recent charts because I disabled the node exporter recently but will re-enable for a further post.

We are going to try increasing the CPU capacity of the leader as well as some other strategies for reducing batch scheduler load (rate limiting job register calls, etc).

**Are there other metrics we should be looking at?**
**What's the best way to trace the leader with 1.3.5 to look for contention during these periods?**

Thanks!

**Comment by hntrmrrs** [comment] 2022-09-02 11:20
So I am not super familiar with the state snapshot code, but I think the issue might be stemming from this line:

https://github.com/hashicorp/nomad/blob/main/nomad/node_endpoint.go#L1608

```go
snap, err := n.srv.fsm.State().Snapshot()
```

Based on the comments over here: https://github.com/hashicorp/nomad/blob/c9b6d0e71b36062805b9daaf80d7fc844b3f4684/nomad/state/state_store.go#L219

```go
// SnapshotMinIndex is used to create a state snapshot where the index is
// guaranteed to be greater than or equal to the index parameter.
//
// Some server operations (such as scheduling) exchange objects via RPC
// concurrent with Raft log application, so they must ensure the state store
// snapshot they are operating on is at or after the index the objects
// retrieved via RPC were applied to the Raft log at.
//
// Callers should maintain their own timer metric as the time this method
// blocks indicates Raft log application latency relative to scheduling.
```

Is it possible that the allocation's persistence in the state hasn't happened by the time the snapshot is taken by the node endpoint Vault client code? Should that node endpoint code somehow wait and backoff for the index to catch up? I'm speculating here so feel free to say "you don't get it dude!"

**Comment by tgross** [comment] 2022-09-16 20:05
Reopening as per https://github.com/hashicorp/nomad/pull/14521#pullrequestreview-1111161052

**Comment by tgross** [comment] 2022-09-16 20:13
@hntrmrrs I've raised this issue with my colleagues @DerekStrickland and @lgfa29 who've been working on a very similar problem over in https://github.com/hashicorp/nomad/pull/13279. I'm hoping that this issue might provide them with some more evidence around their diagnoses.

**Comment by tgross** [comment] 2023-12-01 18:35
A few different fixes have landed to the Vault integration that should resolve the remaining risks of this issue:
* Our vault client refresh behavior was greatly improved in https://github.com/hashicorp/nomad/pull/18985
* Our legacy workflow will be improved by https://github.com/hashicorp/nomad/pull/19268. Although that was specifically to fix poststop tasks, I'm fairly certain in retrospect that it'll help the legacy workflow in general.
* And most importantly, the new Workload Identity workflow is being driven by the client so for that workflow we simply don't derive tokens from the server anymore, which should eliminate the root cause.

**Closed by tgross** 2023-12-01 18:35 UTC
Labels: type/bug, theme/vault, theme/raft

**Comment by dpn** [comment] 2023-12-01 21:12
@tgross Oddly enough we were _just_ looking at this ticket yesterday. Crazy coincidence. Thanks!
