### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by kak-tus** [hashicorp/nomad#2169] opened 2017-01-09 17:42 UTC
### Nomad version
0.5.2

### Operating system and Environment details
Ububtu 16.04

### Issue

High CPU usage with nomad (before 15:00 at screenshots) and low - without nomad (after 15:00 at screenshots). Near 15:00 nomad was killed, but tasks continued to execution.
May be related to #1995.

LA
![image](https://cloud.githubusercontent.com/assets/3152421/21776381/35a4a50c-d6ab-11e6-8153-0fd2a0a107be.png)

CPU metrics
![image](https://cloud.githubusercontent.com/assets/3152421/21776431/759b1fb0-d6ab-11e6-8c34-81cf9de77074.png)

Other server

![image](https://cloud.githubusercontent.com/assets/3152421/21776445/91bc766c-d6ab-11e6-947d-98263425fed4.png)

![image](https://cloud.githubusercontent.com/assets/3152421/21776450/9f3a307c-d6ab-11e6-9e96-7a35e2656888.png)

### Reproduction steps
Runned about 20 tasks (more tasks per server - more load).

**Comment by dadgar** [comment] 2017-01-09 17:55
To be clear these are the clients?

**Comment by kak-tus** [comment] 2017-01-09 18:32
On the same nodes as servers-nodes (it's a small 3-nodes cluster).
I know it is not recommended in docs, but I have only 3 nodes for whole cluster.

**Comment by dadgar** [comment] 2017-01-09 18:42
@kak-tus And when you say you are stopping Nomad, are you stopping both server and client? Can you show the CPU per pid?

**Comment by kak-tus** [comment] 2017-01-09 18:53
@dadgar Yes, both client and server (they are running in same process).
Unfortunately, I don't have per process CPU graphs, but graphs at top: there was only only one change at 15:00 - nomad was killed and managed jobs (docker containers) were continue running.

**Comment by jtuthehien** [comment] 2017-01-13 06:45
Hi
I'm seeing similar problem
Nomad executor is taking too much CPU
<img width="397" alt="screen shot 2017-01-13 at 1 44 52 pm" src="https://cloud.githubusercontent.com/assets/4067846/21920885/96a924d4-d996-11e6-9d77-6e1d4e0ab8df.png">

<img width="1270" alt="screen shot 2017-01-13 at 1 42 52 pm" src="https://cloud.githubusercontent.com/assets/4067846/21920851/5d3846e4-d996-11e6-9200-04591eef5e04.png">

**Comment by diptanu** [comment] 2017-01-13 07:51
@jtuthehien Which driver are you using?

**Comment by dadgar** [comment] 2017-01-13 19:39
@jtuthehien What version of Nomad are you on? Can you run: `go tool pprof http://localhost:4646/debug/pprof/profile` it should output something like: 

```
Fetching profile from http://localhost:4646/debug/pprof/profile
Please wait... (30s)
Saved profile in /home/vagrant/pprof/pprof.nomad.localhost:4646.samples.cpu.002.pb.gz
Entering interactive mode (type "help" for commands)
```

Can you attach the profile

**Comment by jtuthehien** [comment] 2017-01-16 03:50
I'm on 0.4.6 . Docker driver. 
I'll send the pprof when I got it

**Comment by vietwow** [comment] 2017-01-20 03:19
Hi, I'm on 0.4.1 . Docker driver 1.11.2

This is my pprof debug [output](url
[pprof.nomad.10.50.10.20:4646.samples.cpu.001.pb.gz](https://github.com/hashicorp/nomad/files/718342/pprof.nomad.10.50.10.20.4646.samples.cpu.001.pb.gz)
)

**Comment by rejeep** [comment] 2017-01-22 09:14
I saw similar issues with the exec driver on Nomad 0.4.1. I haven't used Nomad since, but will hopefully spend some more time on it. If I have some useful debug information I get back to you.

**Comment by iconara** [comment] 2017-01-23 07:23
Sorry, @rejeep got the version wrong (my fault for confusing Chef recipes), we ran 0.5.1 when we saw the issues.

**Comment by danielbenzvi** [comment] 2017-02-15 15:11
seeing the same issue here with nomad 0.5.2

**Comment by dadgar** [comment] 2017-02-15 18:21
@danielbenzvi Are you seeing the 100% CPU usage as well? What are your nodes running?

**Comment by danielbenzvi** [comment] 2017-02-15 20:57
@dadgar It was one node out of two in a cluster we are POCíng - all the tasks were docker images. The machine is CentOS 7.2 running on AWS (kernel 3.10.0-514.2.2.el7.x86_64)
Docker driver version is 1.12.6.

During the time of the issue, the nomad client was taking 600% CPU, attempting to start and stop docker images all the time and was very slow to respond. Also over 249 tasks accumulated as "lost"  and the node health was flapping (we have 34 tasks running in the cluster normally).

Nothing in the logs suggested the cause of the issue and the docker daemon responded fine. 

Here are some graphs during this time:
![Load averages](https://cloud.githubusercontent.com/assets/612995/22994953/7994b3c2-f3d1-11e6-8cc3-60201933c5fd.png)

![CPU usage](https://cloud.githubusercontent.com/assets/612995/22995016/b3a8670c-f3d1-11e6-8e3d-c30d1269636a.png)

**Comment by dadgar** [comment] 2017-02-15 21:11
@danielbenzvi Hmm, did this just happen randomly or could you get it in this state reproducibly?

**Comment by danielbenzvi** [comment] 2017-02-15 21:50
@dadgar randomly. we've been playing with nomad for the past two weeks so I'm guessing this will happen again if we choose to take nomad further.

**Comment by kak-tus** [comment] 2017-02-15 22:05
I also have an issue with frequent container restart, but it is not that reason, that in the topic.
In topic I have high LA, but it is stable in time.

And frequent container restart happens, when nomad servers temporary looses connection to each other. They begin to restart tasks and then connection restores - tasks all started as normal.
In nomad 0.5-0.5.2 sometimes restart not succeded and I have used this workaround: some script that periodically do "nomad run" to all tasks.
In nomad 0.5.4 situation with restart is better.

**Comment by jippi** [comment] 2017-02-16 06:52
@danielbenzvi what is your file descriptors limit for the nomad client ? for me a too narrow number of FD have created a great deal of issues over the last year or so, having bumped it to 65536 have made all of it go away :)

**Comment by danielbenzvi** [comment] 2017-02-16 11:34
@jippi our limit is 131072 open files and we're far below it...

**Comment by danielbenzvi** [comment] 2017-03-13 15:20
Seeing this again.. this is crazy. Nomad starting and stopping images all the time with no clear explanation in the logs.

**Comment by OferE** [comment] 2017-04-27 11:38
look for the strace of the threads that are causing nomad to be in 100% cpu in issue #2590 
2590#issuecomment-297682053

**Comment by OferE** [comment] 2017-04-27 13:23
This issue can be easily reproduced by creating a batch job that requires more resources than the cluster can handle at the first moment. Once some jobs are queued - all cpu of the workers will be occupied by nomad. In version 0.5.3 - the cpu will remain occupied even if the batch job is stopped. However in version 0.5.6 - after stopping the job the cpu usgae goes to 0 (i am guessing this has something to do with the garbage collection - but i cannot be sure).

this is described in #2590

**Comment by dadgar** [comment] 2017-04-28 20:34
Hey all! Here is a build using PR #2598 cherry-picked onto 0.5.6. I believe it will help with the CPU usage on the client. Please let me know how it goes! 

Also for anyone who wants to provide feedback on that build please set `enable_debug = true` on the client and then run your workload and profile the client and share the `dump.proto` generated from:

```
$ go tool pprof -proto -output=dump.proto `which nomad` http://127.0.0.1:4646/debug/pprof/profile
```

[nomad.zip](https://github.com/hashicorp/nomad/files/965498/nomad.zip)

**Comment by burdandrei** [comment] 2017-06-29 18:44
![image](https://user-images.githubusercontent.com/2526486/27704605-d198136a-5d13-11e7-97ae-52b2c9b883bd.png)
received high CPU and memory usage of nomad client 0.5.6 when running ~ 90 service  groups on the machines.
All tasks are docker running the same image.

**Comment by burdandrei** [comment] 2017-07-04 14:07
@OferE https://github.com/hashicorp/nomad/pull/2771 this should help you run docker with docker driver and to make a workaround with exec

**Comment by OferE** [comment] 2017-07-04 14:32
@burdandrei - thanks for sharing.

I started using exec for this purpose and i am so happy that i chose to use exec.
U can add many adjustment to your infrastructure once u have the control of the docker launch.
I strongly recommend to stay with exec.

My exec script now handles timeouts for batch jobs. Pulling containers from ECR. startup dependencies.  logging into s3. destruction of containers in a clean way. reporting of nomad anomalies.

This has no price.

**Comment by burdandrei** [comment] 2017-07-04 14:55
strange, I like docker driver, cause i can stream logs with syslog to ELK, the only thing that i needed is to have soft and not memory limits.

**Comment by OferE** [comment] 2017-07-04 18:00
U'll need more once your things get complex. Also - soft memory is not enough there is also IO. For example, u spoke about elasticsearch - how r u stopping it without losing data? graceful shut down of services is a must...

**Comment by jzvelc** [comment] 2017-07-05 05:18
@OferE I use dumb-init for that which allows me to rewrite signals (e.g. SIGINT -> SIGQUIT).

**Comment by burdandrei** [comment] 2017-07-05 11:16
@jzvelc you can add STOPSIGNAL  to Dockerfile, and docker will honor it. Works like a charm together with kill_timeout.

**Comment by dadgar** [comment] 2017-07-28 20:13
@kak-tus Wanted to bump this issue as 0.6 is now out! Let me know if this has been resolved.

**Comment by burdandrei** [comment] 2017-07-28 20:47
I'll deploy 0.6 to our staging on sunday and will let you know how it's  running, as discribed in https://github.com/hashicorp/nomad/issues/2771 we got a machine with  ~ 80 tasks running, and i can see both high CPU and memory usage there, while running 0.5.6

**Comment by dadgar** [comment] 2017-07-28 20:48
@burdandrei Thank you! Would you mind setting `enable_debug = true` on the client so that we could do some perf inspection in the case we want to investigate cpu/mem usage.

https://www.nomadproject.io/docs/agent/configuration/index.html#enable_debug

**Comment by burdandrei** [comment] 2017-07-30 09:19
![image](https://user-images.githubusercontent.com/2526486/28752136-128292f4-7521-11e7-9d26-4bcaf6f49568.png)
It's 0.6 client running 117 jobs.
Virtual footprint is half of what we had in 0.5.6, nad RSS is 1/5 -less than 1 GB

**Comment by kak-tus** [comment] 2017-07-30 18:32
@dadgar Thank you. In 0.6 LA is better than in 0.5.2/0.5.4, but not as like as with nomad server/client killed and jobs running.
But may be, CPU usage is normal for nomad process.

**Comment by dadgar** [comment] 2017-08-01 20:02
@burdandrei Did CPU usage come down as well?

@kak-tus I apologize but I am having a hard time following your comment. Did CPU utilization go down?

**Comment by burdandrei** [comment] 2017-08-01 20:04
It looks like yes.

**Comment by dadgar** [comment] 2017-08-01 20:05
Nice! I am going to close this issue now! Thank you so much for testing!

**Closed by dadgar** 2017-08-01 20:05 UTC
Labels: client, performance

**Comment by kak-tus** [comment] 2017-08-01 20:07
@dadgar Same for me - yes.

**Comment by burdandrei** [comment] 2017-10-08 11:49
@dadgar  I got something to report:
Looks like high memory and CPU usage in my case was generated by the job that had 114 groups.
I had nomad client v0.6.3 consuming 8-12GB RSS.
In the last few days I've been working adding [Replicator](https://github.com/elsevier-core-engineering/replicator) to our stack, and he had problem with this particular job.
I split the job to 114 jobs, each one having 1 group, and magically nomad agent is now on Virtual ~8GB but RSS ~150 MB.

This should be stated in docs that huge job definition with lots of groups is not desirable for cluster, like consul-template is throwing warning if it's watching more than 100 keys, maybe it's worth warning on 10 or more groups.

**Comment by jippi** [comment] 2017-10-08 19:03
@burdandrei did it also fix your hashi-ui memory issues?

**Comment by burdandrei** [comment] 2017-10-08 19:14
@jippi, yes, when i open cluster tab with the tab of region without 100-group job, memory usage jumps from 100 to 300. When i switch to 100-group job it  jums to 2GB in 20 seconds

**Comment by jippi** [comment] 2017-10-08 19:19
Must be due to the Nomad structs or something in the SDK/server since 3rd parties like hashi-ui and replicator also see the same behaviour :)
