### ISSUE TITLE
Allow to select network interface to bind to per-port

### ISSUE THREAD

**Issue by sheerun** [hashicorp/nomad#2139] opened 2016-12-22 18:27 UTC
Use Case: I have few interfaces available in client, and I'd like to bind ports of one task to one interface and ports of another task to another interface. This is currently not possible as `network_interface` is configured inside client configuration, and cannot be set on [port](https://www.nomadproject.io/docs/job-specification/network.html#port-parameters) resource itself. I think a reasonable think would be to allow it:

```
port "public_port" {
  static = "80"
}

port "private_port" {
  static = "80"
  network_interface = "eth2"
}
```

Is it reasonable?

**Comment by sheerun** [comment] 2016-12-22 18:34
Alternative configuration:

```
port "public_port" {
  static = "80"
}

port "private_port" {
  static = "80"
  network = "private"
}
```

and in client configuration

```
network_interfaces {
  private = "eth2"
}
```

**Comment by dadgar** [comment] 2017-01-03 18:51
@sheerun Going to close as a duplicate of #646 but it is definitely something we are interested in tackling. You can add your thoughts on config there! Thank you!

**Closed by dadgar** 2017-01-03 18:51 UTC
