### ISSUE TITLE
Nomad job displayed as unhealthy even though job is running properly

### ISSUE THREAD

**Issue by raunak2004** [hashicorp/nomad#9282] opened 2020-11-05 20:15 UTC
Nomad UI and CLI showing a nomad orchestrated job as unhealthy even though the job is running properly. Also the job registered to consul shows the job as healthy. Only health check we have for the service is for tcp health check which is showing as healthy on consul.
![image (5)](https://user-images.githubusercontent.com/2456025/98292107-2ad4ea80-1f7a-11eb-8df2-57447cfd4d99.png)

Nomad Version: Nomad v0.12.3 (2db8abd9620dd41cb7bfe399551ba0f7824b3f61)

nomad job status -verbose xxx-rate-limiting
![Screen Shot 2020-11-05 at 3 09 00 PM](https://user-images.githubusercontent.com/2456025/98291834-c0bc4580-1f79-11eb-89cc-5952dddd0067.png)

ID            = xxx-rate-limiting
Name          = xxx-rate-limiting
Submit Date   = 2020-11-05T17:04:50Z
Type          = service
Priority      = 50
Datacenters   = us04pJ
Namespace     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group               Queued  Starting  Running  Failed  Complete  Lost
xxx-rate-limiting-group  0       0         1        1       6         0

Evaluations
ID                                    Priority  Triggered By  Status    Placement Failures
3e6e9f31-d41b-a65f-a237-f3b1e5d12de0  50        job-register  complete  false
279dcce0-9355-e2f0-d0c3-a059b371005a  50        job-register  complete  false
957cab7f-1f5d-ed41-dbbb-618930202529  50        job-register  complete  false

Latest Deployment
ID          = e5c0660a-eefa-6c1a-a5ea-a05d72ee1913
Status      = failed
Description = Failed due to progress deadline

Deployed
Task Group               Desired  Placed  Healthy  Unhealthy  Progress Deadline
xxx-rate-limiting-group  1        1       0        1          2020-11-05T17:14:50Z

Allocations
ID                                    Eval ID                               Node ID                               Node Name    Task Group               Version  Desired  Status   Created               Modified
38c2658c-afff-401b-9881-1f17613030a7  957cab7f-1f5d-ed41-dbbb-618930202529  a258cd58-52b3-cc78-6a36-8294c4171a46 xxx-rate-limiting-group  2        run      running  2020-11-03T17:55:24Z  2020-11-05T17:09:50Z

nomad job status
xxx-rate-limiting                         service         50        running  2020-11-05T17:04:50Z

**Comment by tgross** [comment] 2020-11-06 13:51
Hi @raunak2004! 

There's a few clues as to what's happening here. We've got this error message:

> Description = Failed due to progress deadline

That suggests that the workload didn't become healthy before the `update` block's progress deadline (10min by default, but if it were expecting manual promotion and it wasn't promoted that would fail too). I also see a bunch of "complete" allocations listed in the job summary, and 1 failed one.

```
Summary
Task Group               Queued  Starting  Running  Failed  Complete  Lost
xxx-rate-limiting-group  0       0         1        1       6         0
```

Can you share your job specification? That would help narrow down the expected behavior in this case.

**Comment by spuder** [comment] 2020-11-09 23:51
Possibly related? https://github.com/hashicorp/nomad/issues/7709

**Comment by tgross** [comment] 2021-02-26 20:48
Without a jobspec there's not much to go on here. I'm going to close this issue out, but if there's more that can be added we can re-open or start with a new issue.

**Closed by tgross** 2021-02-26 20:48 UTC
Labels: stage/waiting-reply, theme/deployments, type/question

**Comment by SunSparc** [comment] 2021-07-29 00:59
This looks like a problem that I am running into as well. I have a `job` with multiple `tasks`. The `init` task sets things up for the other tasks. The `init` task takes a long time and apparently hits a deadline:

```
2021-07-28T23:17:34.097Z [DEBUG] nomad.deployments_watcher: deadline hit: deployment_id=abc123 job="<ns: "default", id: "foo-bar-baz-api">" rollback=false
```

I am not setting a deadline. So the deadline must be hardcoded into Nomad. I do not see any parameter that allows me to adjust a deadline.

@tgross mentions an `update` block. I looked at the [`update` documentation page](https://www.nomadproject.io/docs/job-specification/update) and see that there are two deadline parameters: `healthy_deadline` and `progress_deadline`.

I am guessing that this is where I can specify that I would like the deadline (`progress_deadline`, I assume) to be longer.

After modifying my job file so that it has an `update` section with a `healthy_deadline` and `progress_deadline` both with significantly long durations, my job is still failing to move past the initial task. The only event listed is: "Terminated | Exit Code: 0"

I would not have thought to look at the "update stanza" of the `job` specification in order to fix a deployment problem. Thanks for the tip. I will keep messing with the job specifications and hopefully find a solution. Here is a sterilized version of my job specification.

```
job "foo-bar-baz-api" {
  region = var.facility
  datacenters = ["default"]

  update {
    healthy_deadline = "20m"
    progress_deadline ="25m"
  }

  group "primary" {
    count = local.config.instances
    constraint {
      distinct_hosts = true
    }

    update {
      healthy_deadline = "20m"
      progress_deadline ="25m"
    }

    network {
      mbits = 0
      port "http" {
        host_network = "private"
      }
      port "main" {
        host_network = "private"
      }
    }

    service {
      name = "foo-bar-baz"
      port = "http"
      check {
        type     = "http"
        path     = "/status"
        interval = "2s"
        timeout  = "2s"
      }

    }
    task "main" {
      driver = "exec"
      config {
        command = "${NOMAD_ALLOC_DIR}/foo/bar/baz"
        args = [
          "-config",
          "${NOMAD_SECRETS_DIR}/config.json"]
      }
      resources {
        memory = 1024
      }
      template {
        change_mode = "signal"
        change_signal = "SIGHUP"
        splay = "10m"
        destination = "${NOMAD_SECRETS_DIR}/config.json"
        data = <<-EOT
          {
            "foo" : "{{ env "NOMAD_IP_main" }}:{{ env "NOMAD_PORT_main" }}",
            "bar" : "{{with secret "bar/path/"}}{{.Data.key}}{{end}}",
            "baz" : "${local.config.baz}",
          }
        EOT
      }
      env {
        FACILITY = var.foo
        ENVIRONMENT = var.bar
        APP_NAME = "baz"
      }
      vault {
        policies = ["foo-bar-policy"]
      }
    }

    task "init" {
      driver = "exec"
      lifecycle {
        hook = "prestart"
      }
      config {
        command = "foo"
        args = [
          "-bar",
          "baz.json"]
      }
      vault {
        policies = [
          "foo-bar-policy"]
      }
      env {
        FOO = "bar-baz"
      }
      template {
        data = "{{- with secret \"foo/bar/baz\"}}{{ .Data.key | base64Decode }}{{ end -}}"
        destination = "baz.json"
      }
    }
  }
}

variable "environment" {
  type = string
}
variable "facility" {
  type = string
}
variable "foo_bar_baz" {
  type = map(object({
    instances = number
    version = string
    foo_version = string
    bar_version = string
    baz_version = string
  }))
}

locals {
  config = var.foo_bar_baz["${var.environment}:${var.facility}"]
}
```

**Comment by f3l1x** [comment] 2022-06-14 18:07
In my case tuning `update` stanza helps.

```
  update {
    max_parallel      = "1"
    min_healthy_time  = "10s"
    healthy_deadline  = "4m"
    progress_deadline = "5m"
    health_check      = "checks"
  }
```

`progress_deadline` is by default 10m, it's quite long time to see that it fails, so I decrease it to 5m and `healthy_deadline` set to 4m. As for I know, downloading docker image counts to `healthy_deadline`. So count with that.
