### ISSUE TITLE
UI is unresponsive, wont show Job-Detailpage when using hostname in network-block

### ISSUE THREAD

**Issue by SCORP111** [hashicorp/nomad#22197] opened 2024-05-22 13:02 UTC
### Nomad version
1.7.4

### Operating system and Environment details
Ubuntu 20

### Issue
UI unresponsive (can't click any tabs), wont show Job-Detailpage when using hostname in network-block when hostname (e.g. hostname=${node.unique.name}) is set in network block with bridge mode set.

### Reproduction steps
Set hostname (e.g. hostname = "${node.unique.name}") in network block and enable bridge mode:

#### Expected Result
Allocations get started or show an error.

#### Actual Result
![grafik](https://github.com/hashicorp/nomad/assets/49976585/e63f0c6b-52cf-4254-81b4-c5d23747692e)

### Job file (if appropriate)
  group "test" {
    # Number of Allocations to run.
    count = 2
    # All groups in this job should be scheduled on different hosts.
    constraint {
      operator  = "distinct_hosts"
      value     = "true"
    }
    network {
      mode = "bridge"
      hostname = "${node.unique.name}"
      port "http" {}
      port "port1" {
        to = 8082
      }
      port "port2" {
        to = 8083
      }
      port "port3" {
        to = 1344
      }
    }
	...
  }

**Comment by philrenaud** [comment] 2024-05-22 13:26
Hi @SCORP111 , thanks for reporting. This looks like a fatal javascript error to me. Would you mind checking your javascript/browser console for any JS errors and pasting them here?

**Comment by SCORP111** [comment] 2024-05-22 13:45
> Hi @SCORP111 , thanks for reporting. This looks like a fatal javascript error to me. Would you mind checking your javascript/browser console for any JS errors and pasting them here?

This is what I can see in the console using firefox. Im doing a rolling update of a job with two allocations, as far as i can see in consul, a new second allocation never gets started. Thank you for your help!

Content-Security-Policy: Die Einstellungen der Seite haben die Ausführung eines Inline-Skripts (script-src-elem) blockiert, da es gegen folgende Direktive verstößt: "script-src 'self'" 2 content.js:60:437
Stylesheet https://nomad.test.dev/ui/assets/~@hashicorp/design-system-tokens/dist/products/css/helpers/colors.css wurde nicht geladen, weil sein MIME-Typ, "text/html", nicht "text/css" ist. nomad-ui-4d2c3953d3ad29ec489f004e13ff90d6.css
InstallTrigger sollte nicht mehr verwendet werden und wird in Zukunft entfernt werden. vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:1210:25
TypeError: regex_list is undefined
content_script.js:7:25
Uncaught (in promise) TypeError: e.events is null
    get hasBeenRestarted/< https://nomad.test.dev/ui/assets/nomad-ui-a04e64d485b4efb841315ce1266627c2.js:2027
    map https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:2561
    forEach https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:2559
    map https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:2561
    get hasBeenRestarted https://nomad.test.dev/ui/assets/nomad-ui-a04e64d485b4efb841315ce1266627c2.js:2027
    get restartedAllocs/< https://nomad.test.dev/ui/assets/nomad-ui-a04e64d485b4efb841315ce1266627c2.js:877
    filter https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:2563
    forEach https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:2559
    filter https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:2563
    get restartedAllocs https://nomad.test.dev/ui/assets/nomad-ui-a04e64d485b4efb841315ce1266627c2.js:877
    Ee https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:1980
    o https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3672
    tag https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3667
    track https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4319
    m https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3667
    o https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3671
    tag https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3667
    track https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4319
    m https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3667
    <anonymous> https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3884
    tag https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3667
    track https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4319
    m https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3667
    <anonymous> https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3881
    evaluate https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3785
    evaluateSyscall https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4083
    evaluateInner https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4077
    evaluateOuter https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4077
    next https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4138
    _execute https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4137
    execute https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4136
    handleException https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4088
    handleException https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4103
    throw https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4086
    evaluate https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3886
    _execute https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4086
    execute https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4084
    rerender https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4104
    render https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:1716
    _renderRoots https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:1741
    It https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4073
    _renderRoots https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:1740
    _renderRootsTransaction https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:1745
    _revalidate https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:1745
    invoke https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4481
    flush https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4473
    flush https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4486
    _end https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4543
    _boundAutorunEnd https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4495
    promise callback*n/< https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4458
    flush https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3225
    _scheduleAutorun https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4557
    _end https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4544
    _boundAutorunEnd https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4495
    promise callback*n/< https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4458
    flush https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3225
    _scheduleAutorun https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4557
    _end https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4544
    _boundAutorunEnd https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4495
    promise callback*n/< https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4458
    flush https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3225
    _scheduleAutorun https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4557
    _end https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4544
    _boundAutorunEnd https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4495
    promise callback*n/< https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4458
    flush https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3225
    _scheduleAutorun https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4557
    _ensureInstance https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4555
    schedule https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4515
    <anonymous> https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:2512
    f https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4927
    h https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4925
    x https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4949
    onload https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:5003
    g https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:5003
    x https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4949
    x https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4949
    g https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:5003
    text https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:5015
    determineBodyPromise https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:5145
    ajax https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:5233
    v https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4931
    g https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4929
    invoke https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4481
    flush https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4473
    flush https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4486
    _end https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4543
    _boundAutorunEnd https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4495
    promise callback*n/< https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4458
    flush https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:3225
    _scheduleAutorun https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4557
    _ensureInstance https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4555
    schedule https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:4515
    <anonymous> https://nomad.test.dev/ui/assets/vendor-7b6788f72c262a8ca47ed42d574c0eb1.js:2512

**Comment by philrenaud** [comment] 2024-05-22 14:07
Got it, I know just what the problem is: we try to read task events to display here and I've been presumptive about them always existing. My guess is that in your failed allocation (red on screen), the events list comes back as null, possibly because things have been garbage collected.

In any event: I think I know how to fix this! Let me try to get something going soon.

**Comment by philrenaud** [comment] 2024-06-07 13:42
Hi @SCORP111 , thank you for your patience on this issue. I started trying to reproduce and wasn't able to on the latest (1.8.0), which reminded me that I'd pushed a fix to something related to this in April: https://github.com/hashicorp/nomad/pull/20383

This went out in [1.7.7](https://github.com/hashicorp/nomad/blob/main/CHANGELOG.md#177-april-16-2024) and should prevent the JS error from firing again.

If you run into this error again, please let us know and I'll keep trying for a reproduction.

**Closed by philrenaud** 2024-06-07 13:42 UTC
Labels: type/bug, theme/ui
