### ISSUE TITLE
[feature request] Task dependencies for batch jobs

### ISSUE THREAD

**Issue by dukeland9** [hashicorp/nomad#3363] opened 2017-10-12 04:45 UTC
I think it's a common case that a batch job is divided into several steps, and each step depends on some previous steps.
Could we have something like:

<pre>
job "batch_job" {
  type = "batch"
  group "g" {
    task "step1" {
    }
    task "step2" {
      depends_on = ["step1"]
    }
  }
}
</pre>

Google borg supports such configuration.

**Comment by dadgar** [comment] 2017-10-12 17:14
Hey @dukeland9,

Closing as a duplicate of https://github.com/hashicorp/nomad/issues/419

**Closed by dadgar** 2017-10-12 17:14 UTC
