### ISSUE TITLE
Please add NOMAD_GROUP_NAME environment variable

### ISSUE THREAD

**Issue by nugend** [hashicorp/nomad#2704] opened 2017-06-13 21:45 UTC
I found myself needing to reproduce the full "name" of the job. While I can currently manually type this out and pass it through meta, it's much nicer to have it be an environment variable already defined.

**Comment by jippi** [comment] 2017-06-13 23:08
Duplicate of https://github.com/hashicorp/nomad/issues/1943

**Comment by qkate** [comment] 2017-07-30 07:32
And #1943 is now closed, so closing this as well.  (Fixed in https://github.com/hashicorp/nomad/pull/2877)

**Closed by qkate** 2017-07-30 07:32 UTC
Labels: client, enhancement
