### ISSUE TITLE
Constraint "${attr.vault.version} version >= 0.6.1" filtered 1 nodes

### ISSUE THREAD

**Issue by karma0** [hashicorp/nomad#4276] opened 2018-05-10 02:23 UTC
### Nomad version
Nomad v0.8.3 (c85483da3471f4bd3a7c3de112e95f551071769f)
Vault v0.10.1 ('756fdc4587350daf1c65b93647b2cc31a6f119cd')

### Operating system and Environment details
Terraform modules in AWS:
[terraform-aws-vault](https://github.com/hashicorp/terraform-aws-vault/tree/master/modules/vault-cluster)
[terraform-aws-nomad](https://github.com/hashicorp/terraform-aws-nomad/tree/master/modules/nomad-cluster)

These modules both launch ASGs, totaling 3 EC2 clusters: vault, nomad servers, and nomad clients.

### Issue
Attempting to plan or execute a job that uses Vault results in a hidden constraint that filters nodes with Vault version `>= 0.6.1`.

### Reproduction steps
Executing `nomad job plan test.nomad` for my attempt at the given job reveals:
```
Scheduler dry-run:
- WARNING: Failed to place all allocations.
  Task Group "api" (failed to place 1 allocation):
    * No nodes are available in datacenter "us-east-1b"
    * No nodes are available in datacenter "us-east-1c"
    * Constraint "${attr.vault.version} version >= 0.6.1" filtered 1 nodes
```
### Nomad Server logs (if appropriate)
None.
### Nomad Client logs (if appropriate)
None.
### Job file (if appropriate)
```
job "test" {
  datacenters = ["us-east-1a", "us-east-1b", "us-east-1c"]
  type = "service"
  update {
    max_parallel = 1
    min_healthy_time = "10s"
    healthy_deadline = "3m"
    auto_revert = false
    canary = 0
  }
  group "api" {
    restart {
      attempts = 10
      interval = "5m"
      delay = "25s"
      mode = "delay"
    }
    ephemeral_disk {
      size = 300
    }
    task "testapi" {
      driver = "docker"
      config {
        image = "https://<REDACTED>"
        port_map {
          http = 8080
        }
      }
      resources {
        memory = 256 # 256MB
        network {
          mbits = 10
          port "http" {}
        }
      }
      service {
        name = "global-testapi-check"
        tags = ["global", "cache"]
        port = "http"
        check {
          name     = "alive"
          type     = "tcp"
          interval = "10s"
          timeout  = "2s"
        }
      }
      template {
        source      = "nomad-config.json.tpl"
        destination = "config.json"
        perms       = 640
      }
      vault {
        policies      = ["testapi"]
        change_mode   = "signal"
        change_signal = "SIGHUP"
      }
    }
  }
}
```

**Comment by angrycub** [comment] 2018-05-10 13:00
@karma0, This is the intended behavior.  If no client node meets this constraint, then the cluster is unable to run the vault-enabled job.  Is there an element to your issue report that I am missing?

**Comment by karma0** [comment] 2018-05-10 15:58
Where is this constraint coming from?  Is Nomad not compatible with Vault >= 0.6.1?

**Comment by angrycub** [comment] 2018-05-10 16:17
"Constraint "${attr.vault.version} version >= 0.6.1" filtered 1 nodes" indicates that Nomad believes that you _don't_ have Vault greater than or equal to v0.6.1.   The constraint text is the expectation.  More conversationally, this would be read as:  "One node was filtered from the eligibility because it does not meet the constraint that ${attr.vault.version} is greater than or equal to 0.6.1."

 This often indicates a misconfiguration in your Vault configuration for Nomad.

**Comment by dadgar** [comment] 2018-05-10 16:36
@karma0 Closing this as it is expected behavior and @angrycub's explanation is correct. Make sure you have set up your clients to be able to talk to the same Vault as the servers.

**Comment by angrycub** [comment] 2018-05-10 16:36
@karma0 I will say that I was just fighting this in my local lab cluster.  Turned out that I had accidentally set my the address in my vault stanza to **https**://active.vault.service.consul:8200  when I wasn't running TLS on my Vault server.

**Closed by dadgar** 2018-05-10 16:36 UTC

**Comment by karma0** [comment] 2018-05-10 18:53
@angrycub What is the difference between `active.vault.service.consul` and `vault.service.consul`?

**Comment by angrycub** [comment] 2018-05-10 19:15
I think I see your issue.  You have "https://vault.services.consul:8200" and I believe it should be "https://vault.service.consul:8200"—no trailing s on service.  

The only other thing I noticed in the configurations is that you don't supply `ca_path`, which is fine if the operating system's CA path contains your the CA certs used to generate your TLS certs. 

As to active.vault.service.consul.  A Vault in an HA configuration will tag the currently active node with `active` in Consul.  This enables you to select the active node specifically rather than the active and any standbys (which are all registered to provide the vault service).  This saves a little because the standbys will forward the request to the active node.

Hope this gets you unjammed!

**Comment by karma0** [comment] 2018-05-18 02:54
The issue turned out to be a bit more convoluted.  The certs weren't setup with the correct IP addresses and/or DNS names.  I was using `private-tls-cert` and the certs' IP addresses were set to `["127.0.0.1"]` while the DNS was set to `["*.vault.service.consul", "vault.service.consul"]`.  The issue was that the Vault clients weren't coming from localhost or an IP address that resolved to any of these DNS addresses.

Adding `"*.consul"` to the list of domains for the certs allowed the `nomad` systems to connect because the IP addresses resolved to `*.<region>.consul` in a reverse lookup.

Thanks for the help!

**Comment by angrycub** [comment] 2018-05-18 16:45
@karma0  Thanks for posting your solution!  That's a great note for future explorers.
