### ISSUE TITLE
nomad 0.2.2 crash when stopping job

### ISSUE THREAD

**Issue by bnordbo** [hashicorp/nomad#595] opened 2015-12-17 15:24 UTC
I was running through the quick start on Vagrant, and when I stopped (`nomad stop example`) the three node example job in the final section, the server agent promptly crashed because of an [invalid memory access](https://gist.github.com/bnordbo/83f262a6cc3631352aa1).

I started Vagrant using the vagrantfile that the quick start points to, but had upgraded to 0.2.2 changing it to pull nomad from `https://releases.hashicorp.com/nomad/0.2.2/nomad_0.2.2_linux_amd64.zip`.

Besides that, it was a nice ride. :-)

**Comment by diptanu** [comment] 2015-12-17 19:33
@bnordbo Can you please attach some logs related to te crash please? I can't reproduce the issue.

**Comment by bnordbo** [comment] 2015-12-17 19:38
@diptanu, I linked to the following gist above: https://gist.github.com/bnordbo/83f262a6cc3631352aa1. This is the output from `nomad stop`:

```
vagrant@nomad:~$ nomad stop example
==> Monitoring evaluation "74a70681-d4bd-adbb-e3d1-c58c76e5d581"
==> Error reading evaluation: Get http://127.0.0.1:4646/v1/evaluation/74a70681-d4bd-adbb-e3d1-c58c76e5d581: read tcp 127.0.0.1:44686->127.0.0.1:4646: read: connection reset by peer
```

I can't reproduce it either, but it happened on a clean instance after doing nothing else than starting the server agent, client agents and starting the example job. Let me know if there is any more information you need.

**Comment by cbednarski** [comment] 2015-12-17 19:57
Thanks for the report. I'm curious whether this is a race condition in the RPC layer. We fixed numerous similar issues in packer recently. They're very difficult to reproduce. (In packer the failure would happen <10% of the time in testing.)

**Comment by dadgar** [comment] 2015-12-23 23:06
This was caused by a bug in a underlying library fixed by this commit: https://github.com/hashicorp/go-immutable-radix/commit/dcb9407fddfee574a6816ccfc9ec0f9414a18410.

Should not be an issue on master anymore.

**Closed by dadgar** 2015-12-23 23:06 UTC
Labels: core, crash
