### ISSUE TITLE
Can't run a job that was retrieved through inspect.

### ISSUE THREAD

**Issue by james-masson** [hashicorp/nomad#10759] opened 2021-06-15 12:30 UTC
### Nomad version
v1.1.0

also tried v1.0.3

### Operating system and Environment details

Debian 10

### Issue

I expect that the job definitions retrieved through ` nomad job inspect` are valid for re-submission

In my use case, I want to stop/start jobs through the CLI

### Reproduction steps

```
nomad job stop foo
nomad job inspect foo > /tmp/new1
nomad job run /tmp/new1
```

#### Expected Result

Nomad successfully reschedules the job

#### Actual Result

```
Error getting job struct: Error parsing job file from /tmp/new1:
new1:2,5-10: Extraneous JSON object property; No argument or block type is named "Job". Did you mean "job"?
```

```
user$  head /tmp/new1
{
    "Job": {
        "Affinities": null,
        "AllAtOnce": false,
        "Constraints": null,
        "ConsulNamespace": null,
        "ConsulToken": "",
        "CreateIndex": 294,
        "Datacenters": [
            "local"
        ],
```

I took a look at how the UI is doing this, and it seems to submit the job as inspect retrieves it, so I suspect this is the CLI being overly picky about case.

**Comment by tgross** [comment] 2021-06-15 12:37
Hi @james-masson! This looks to be a duplicate of https://github.com/hashicorp/nomad/issues/6758.

For some more context (https://github.com/hashicorp/nomad/issues/6758#issuecomment-794116722):

> * HCL is currently parsed entirely in the CLI. This is required for HCL2's ability to get environment variables and local files from the CLI's environment.
> * The `nomad job run` command currently accepts only HCL. There's no particular documentation that says otherwise, but I've opened #10141 to make it explicit.
> * The output of `nomad job inspect :jobid` is the  [JSON jobs](https://www.nomadproject.io/api-docs/json-jobs) output. This is round-trippable to the [Create Job HTTP API](https://www.nomadproject.io/api-docs/jobs#create-job). (There's an integration test demonstrating this behavior as far back as e13f8680c6b4bc0243b63298e6707c035765cbb8 in 2017).
> * The output of the `nomad job inspect -json :jobid` command is the [Read Job HTTP API](https://www.nomadproject.io/api-docs/jobs#read-job) output. This is not round-trippable to the Create Job HTTP API. This flag was added back in https://github.com/hashicorp/nomad/pull/1503 but it's not super clear what this gets you over leaving it out.
> * The only difference between the two is the `Job` wrapper in the JSON. See the examples below for a very simple workaround which should be feasible for any context in which you're manipulating JSON anyways.

**Closed by tgross** 2021-06-15 12:37 UTC
Labels: type/bug
