### ISSUE TITLE
New tighter consul integration unclear

### ISSUE THREAD

**Issue by cavemandaveman** [hashicorp/nomad#1422] opened 2016-07-13 22:08 UTC
### Nomad version
Nomad v0.4.0

### Operating system and Environment details
Ubuntu 14.04

### Issue
According to your blog https://www.hashicorp.com/blog/nomad-0-4.html and Docs https://www.nomadproject.io/docs/cluster/bootstrapping.html bootstrapping a nomad cluster with an already existing consul cluster is easy. However, that documentation is unclear on how to go about it; it says it should be "automatic". The documentation you reference https://www.nomadproject.io/docs/agent/config.html#consul_options from the bootstrapping page doesn't even exist. 

### Reproduction steps
So what I assume is that with my consul setup, 
my **server.hcl** can look like this:
```shell
data_dir = "/var/lib/nomad"
server {
    enabled = true
    bootstrap_expect = 1
}
```
and my **client.hcl** can look like this:
```shell
data_dir = "/var/lib/nomad"
client {
    enabled = true
}
```
and consul would take care of bootstrapping, registering and joining for servers and clients.

My server actually gets registered to consul, but the 3 services (http, rpc, and serf) that it shows are on 127.0.0.1. 

### Nomad Client logs
My client fails to start with the following log:
```shell
    2016/07/13 16:26:26.469838 [INFO] client: using state directory /var/lib/nomad/client
    2016/07/13 16:26:26.470454 [INFO] client: using alloc directory /var/lib/nomad/alloc
    2016/07/13 16:26:26.471173 [INFO] fingerprint.cgroups: cgroups are available
    2016/07/13 16:26:26.475316 [INFO] fingerprint.consul: consul agent is available
    2016/07/13 16:26:30.488161 [WARN] fingerprint.network: Unable to parse Speed in output of '/sbin/ethtool eth0'
    2016/07/13 16:26:30.494593 [WARN] client.rpcproxy: No servers available
    2016/07/13 16:26:30.494622 [ERR] client: failed to query for node allocations: no known servers
    2016/07/13 16:26:30.495528 [WARN] client.rpcproxy: No servers available
    2016/07/13 16:26:47.215506 [WARN] client.rpcproxy: No servers available
    2016/07/13 16:26:47.215607 [ERR] client: failed to register node: no known servers
```
I used to have to provide ```servers``` in the client.hcl, but from what I understand I shouldn't have to anymore, right?

**Comment by dadgar** [comment] 2016-07-13 22:20
Hey,

When you say the documentation doesn't exist in the bootstrapping page can you elaborate? As far as I can see it does.

So the reason you are seeing `127.0.0.1` being advertised is because your server config does not advertise its address. Your configuration should be something like:

```
data_dir = "/var/lib/nomad"
server {
    enabled = true
    bootstrap_expect = 1
}

bind_addr = "0.0.0.0"
advertise {
  http = "<IP>:4646"
  rpc = "<IP>:4647"
  serf = "<IP>4648"
}

```

**Comment by diptanu** [comment] 2016-07-13 22:21
@cavemandaveman I can open the page https://www.nomadproject.io/docs/agent/config.html#consul_options Please look for the Consul section on that page. You will have to set the advertise addresses for `http`, `rpc` and `serf` services in your server configuration for the clients to discover the servers.

**Comment by cavemandaveman** [comment] 2016-07-13 23:21
That is how my configuration used to look before v0.40 and without consul in the picture; with ```bind_addr``` and ```advertise``` sections. 

In the latest version, the documentation makes it sound like consul will take care of everything. So I thought that once you launch a nomad server, consul will have it registered in its dns. That way, when you launch an additional server or client, it could just have consul feed it the information it needs instead of needing to hard code ips into the nomad config.

And that link opens, but doesn't forward to a consul_options section. A consul_options doesn't even exist, unless you are trying to say look at the Client Options Map section.

**Comment by diptanu** [comment] 2016-07-15 04:29
@cavemandaveman Nomad does registers and servers and the client with Consul and tries to auto-discover everything, but by default it binds to `127.0.0.1` and only when you explicitly use the `bind_addr` and `advertise` options it binds and registers an IP which is routable.

We have been meaning to change this behavior for a long time and make Nomad bind to a routable IP instead of a loopback but we haven't done it yet.

**Comment by cavemandaveman** [comment] 2016-07-15 14:49
Ok, I can get over manually setting `bind_addr` for now, but I am weary of harcoding ips in the `advertise` section.

If, once a nomad server is registered to consul with a good `bind_addr`, shouldn't any other servers/clients you launch be able to talk to their local consul instance and automatically grab the needed ips that the server is registered under (what I assume the docs mean by "auto-discover")? That would remove the need for an `advertise` section.

**Comment by dadgar** [comment] 2016-07-15 18:21
@cavemandaveman It is not quite that simple since `bind_addr: "0.0.0.0"` is valid bind addr but not something that can be registered with Consul.

We will be doing work to auto set the bind/advertise which will take care of this.

Closing this as feature is working as intended.

**Closed by dadgar** 2016-07-15 18:21 UTC
