### ISSUE TITLE
document GC decision-making (nodes and jobs, clients vs server GC)

### ISSUE THREAD

**Issue by glenjamin** [hashicorp/nomad#8130] opened 2020-06-07 09:23 UTC
Apologies for butchering the issue template, as far as I can tell, this is a reasonable place to post this sort of question / docs-bug, but the template headings were not relevant.

This isn't exactly a bug, but it's information I was expecting to find in the docs and failed to do so.

The config docs say:
> `node_gc_threshold` (string: "24h") - Specifies how long a node must be in a terminal state before it is garbage collected and purged from the system. This is specified using a label suffix like "30s" or "1h".

Is there anywhere which explains what terminal states make a node eligible for GC?

**Comment by glenjamin** [comment] 2020-06-07 09:29
To answer my own question, it appears to be "if the node is down":

https://github.com/hashicorp/nomad/blob/65937ffd21dc21e027313a511de8089a4e821918/nomad/structs/structs.go#L1863-L1872

I would say that intuitively "down" doesn't seem like it's always a terminal status (it could be temporary), so perhaps the documentation could say:

> Specifies how long a node must down before it is garbage collected and purged from the system

**Comment by tgross** [comment] 2020-06-22 15:53
Hi @glenjamin! Yup, that's it. I think you're right about the docs -- "terminal" isn't really a user-facing concept so the docs should be more clear about that. Would love to get a PR from you on it if you have time.

**Comment by tgross** [comment] 2020-12-17 16:15
Changing the title of this issue to reflect a broader documentation gap in how we document GC. See also the thread starting at https://github.com/hashicorp/nomad/issues/8345#issuecomment-669673001

**Comment by tgross** [comment] 2022-06-06 13:51
I'm going to close this issue as a duplicate of https://github.com/hashicorp/nomad/issues/13037. Technically #13037 is the dupe, but it has a broader problem description that'll be useful for whomever writes those docs. Thanks for your patience!

**Closed by tgross** 2022-06-06 13:51 UTC
Labels: theme/docs
