### ISSUE TITLE
resource stanza ignores memory

### ISSUE THREAD

**Issue by readmodifywrite** [hashicorp/nomad#9131] opened 2020-10-20 17:58 UTC
### Nomad version
Nomad v0.12.5 (514b0d667b57068badb43795103fb7dd3a9fbea7)

### Operating system and Environment details
Linux Mint 20

### Issue
Nomad ignores "memory" in the resource stanza and just uses the default of 300 MB.  The cpu setting works fine.

**Comment by nickethier** [comment] 2020-10-20 18:53
Hey @readmodifywrite a few questions to help reproduction:

Was this with a particular driver? How did you determine that Nomad ignored the `memory` field? Was this reflected in Nomad's API or by other means?

Thanks!

**Comment by readmodifywrite** [comment] 2020-10-21 20:57
Docker driver.

Nomad server page reports the correct CPU allocation, but the incorrect 300 MB memory allocation.

I have not checked the API itself yet.

**Comment by mikenomitch** [comment] 2021-09-20 21:29
Hi, since this hasn't had much activity and we aren't aware of bugs with this functionality otherwise, I'm going to close this out.

If this is still an issue, if you could provide screenshots or logging printouts with some more information, that would help us to debug it in the future. Thanks!

**Closed by mikenomitch** 2021-09-20 21:29 UTC
Labels: type/bug, stage/needs-verification
