### ISSUE TITLE
Auth error during node drain via Task API: rpc error: error looking up ACL token

### ISSUE THREAD

**Issue by scarbeau** [hashicorp/nomad#17471] opened 2023-06-09 14:44 UTC
### Nomad version
Nomad v1.5.6
BuildDate 2023-05-19T18:26:13Z
Revision 8af70885c02ab921dedbdf6bc406a1e886866f80

### Operating system and Environment details
Amazon Linux 2023 - 1 Server, 1 Client
ACLs Disabled

### Issue
Receive the following error when calling the node drain endpoint via the Task API: 
rpc error: error looking up ACL token: acl token lookup failed: index error: UUID must be 36 characters

Have confirmed the node id and token are valid (see job details below).

### Reproduction steps
Run the following job:
```hcl
job "al2023" {
    type = "batch"

    group "al2023" {
        count = 1

        task "al2023" {
            driver = "docker"

            env {
                NOMAD_NODE_ID = "${node.unique.id}"
            }

            identity {
                # Expose Workload Identity in NOMAD_TOKEN env var
                env = true
            }

            config {
                image        = "amazonlinux:latest"
                command      = "sh"
                args         = ["-c", "echo -n 'Test task started'; sleep 200000; echo -n 'Test task ending'"]
                network_mode = "host"
            }
        }
    }
}
```

Get a shell within the allocation:
```
$ nomad alloc exec -i -t -task al2023 aa399e9e /bin/bash
bash-5.2# curl --unix-socket /secrets/api.sock -X POST -H "Authorization: Bearer ${NOMAD_TOKEN}" -H "Content-Type: application/json" --data '{"DrainSpec": {"Deadline":3600000,"IgnoreSystemJobs": true},"Meta": {"message": "drain for maintenance"}}' "localhost/v1/node/${NOMAD_NODE_ID}/drain"
rpc error: error looking up ACL token: acl token lookup failed: index error: UUID must be 36 characters 
The connection has closed.
```

#### Expected Result
{
  "EvalCreateIndex": 0,
  "EvalIDs": null,
  "Index": 3742,
  "NodeModifyIndex": 3742
}

#### Actual Result
rpc error: error looking up ACL token: acl token lookup failed: index error: UUID must be 36 characters

### Job file (if appropriate)
see above

**Comment by jrasell** [comment] 2023-06-13 11:39
Hi @scarbeau and thanks for raising this issue. I have not been able to initially reproduce this locally and get an expected response when trying to perform a call which should work, such as listing service registrations within Nomad. Could you provide a little more detail about the ACL setup you have configured any any other relevant information?

Using your example jobspec:
```
$ curl --unix-socket /secrets/api.sock -H "Authorization: Bearer ${NOMAD_TOKEN}" -H "Content-Type: application/json" "localhost/v1/services"
[]
```

**Comment by scarbeau** [comment] 2023-06-13 19:57
Hi @jrasell, I have ACLs completely disabled right now. Other endpoints work (e.g. have tested toggling node eligibility successfully). The issue is just with the drain node operation. Following the error chain, it looks like the relevant code is here: https://github.com/hashicorp/nomad/blob/main/nomad/fsm.go#L479-L500
```go
accessorId := ""
if req.AuthToken != "" {
	token, err := n.state.ACLTokenBySecretID(nil, req.AuthToken)
	if err != nil {
		n.logger.Error("error looking up ACL token from drain update", "error", err)
		return fmt.Errorf("error looking up ACL token: %v", err)
	}
	if token == nil {
		node, err := n.state.NodeBySecretID(nil, req.AuthToken)
		if err != nil {
			n.logger.Error("error looking up node for drain update", "error", err)
			return fmt.Errorf("error looking up node for drain update: %v", err)
		}
		if node == nil {
			n.logger.Error("token did not exist during node drain update")
			return fmt.Errorf("token did not exist during node drain update")
		}
		accessorId = node.ID
	} else {
		accessorId = token.AccessorID
	}
}
```

From a quick review, it looks like drain node is the only operation doing this lookup in the hopes of setting a last drain accessor Id value on the node (see https://github.com/hashicorp/nomad/blob/main/nomad/state/state_store.go#L1193). When the AuthToken value is a Workload Identity token the JWT is well over 100 characters and a UUID check within `hashicorp/go-memdb` raises the error before parsing the provided token.

Happy to add more detail if needed.

**Comment by gs0510** [comment] 2024-04-03 14:48
I see the same error, this is my job spec:

```
job "agent" {
  datacenters = ["${NOMAD_DATACENTER}"]
  type        = "system"

  constraint {
    attribute = "$${node.class}"
    value     = "agent"
  }

  group "run" {
    task "agent" {
      driver = "raw_exec"

      config {
        command = "/opt/blah/box"
        args    = [
          "agent",
          "--instance-id=$${attr.unique.platform.aws.instance-id}",
        ]
      }

      env {
        AWS_REGION = "${AWS_REGION}"

        NOMAD_ADDR = "unix://$${NOMAD_SECRETS_DIR}/api.sock"
        NOMAD_REGION = "$${node.region}"
      }

      identity {
        env = true
      }
    }
  }
}

```

**Comment by gs0510** [comment] 2024-04-04 14:39
also, from the docs, only having the env should work since it gives access to the workload identity, so I am confused why there's a lookup for ACL token in the first place.

```
      identity {
        env = true
      }
```

**Comment by tgross** [comment] 2024-04-05 18:58
Hey folks, just wanted to follow-up on this one. I've been able to reproduce the specific problem at hand here and @scarbeau has it right as he described it n https://github.com/hashicorp/nomad/issues/17471#issuecomment-1589933052

I made a quick attempt at fixing this by turning that block into 

```diff
diff --git a/nomad/fsm.go b/nomad/fsm.go
index ff462036ec..f430a3cc25 100644
--- a/nomad/fsm.go
+++ b/nomad/fsm.go
@@ -480,29 +480,7 @@ func (n *nomadFSM) applyDrainUpdate(reqType structs.MessageType, buf []byte, ind
        if err := structs.Decode(buf, &req); err != nil {
                panic(fmt.Errorf("failed to decode request: %v", err))
        }
-
-       accessorId := ""
-       if req.AuthToken != "" {
-               token, err := n.state.ACLTokenBySecretID(nil, req.AuthToken)
-               if err != nil {
-                       n.logger.Error("error looking up ACL token from drain update", "error", err)
-                       return fmt.Errorf("error looking up ACL token: %v", err)
-               }
-               if token == nil {
-                       node, err := n.state.NodeBySecretID(nil, req.AuthToken)
-                       if err != nil {
-                               n.logger.Error("error looking up node for drain update", "error", err)
-                               return fmt.Errorf("error looking up node for drain update: %v", err)
-                       }
-                       if node == nil {
-                               n.logger.Error("token did not exist during node drain update")
-                               return fmt.Errorf("token did not exist during node drain update")
-                       }
-                       accessorId = node.ID
-               } else {
-                       accessorId = token.AccessorID
-               }
-       }
+       accessorId := req.GetIdentity().String()

        if err := n.state.UpdateNodeDrain(reqType, index, req.NodeID, req.DrainStrategy, req.MarkEligible, req.UpdatedAt,
                req.NodeEvent, req.Meta, accessorId); err != nil {
```

But unfortunately that results in all the `LastDrain.AccessorID` fields being set to `"unauthenticated"` rather than the identity string (ex. `token:1375bb36-f37e-11ee-be78-8b4601b6adf3`). The reason is that the identity is set in the RPC handler but isn't an exported field, so the resulting msgpack serialized log entry gets sent thru Raft and the FSM without it. Doing all this reauthentication in the FSM is kind of silly anyways, so I think I'm going to try to solve this by adding an `AccessorID` field to the `NodeUpdateDrainRequest` struct that we strip out in the handler if the caller tries to set it.

I'll pick that fix up next week.

**Comment by tgross** [comment] 2024-04-08 14:43
Fixed in https://github.com/hashicorp/nomad/pull/20317. In the process of working on that, I discovered this bug also potentially impacts server restarts! If the Raft logs haven't been compacted into a snapshot and you restart the server, the logs are applied via the FSM code path. But if you have an auth token used to drain a node that expired while the server was down, you can end up being unable to re-apply that FSM log. It's a very unlikely scenario and one we've never seen reported, but now that's fixed too!

**Comment by gs0510** [comment] 2024-04-08 16:13
Amazing! Thanks @tgross!

**Closed** 2024-04-09 13:28 UTC
Labels: type/bug, theme/drain, stage/accepted, hcc/cst
