### ISSUE TITLE
Varialble interpolation in service tags stanza. 

### ISSUE THREAD

**Issue by suikast42** [hashicorp/nomad#15868] opened 2023-01-25 15:29 UTC
I am using nomad 1.4.3 and wan't do some dynamic prometheus configuration. 

For some relabling issues I am to looking for a possibility to interpolate nomad variables in service tag staanza. But it seems not works as expected. 

```hcl
        tags = [
         "prometheus_minio",
         "frontend",
         "minio",
         "server=${TASKGROUP}-${TASK}",
         "test=${node.unique.id}",
         "traefik.enable=true",
         "traefik.consulcatalog.connect=false",
         "traefik.http.routers.minio.tls=true",
         "traefik.http.routers.minio.rule=Host(`minio.{{tls_san}}`)",
        ]
```
![image](https://user-images.githubusercontent.com/5046525/214604516-1d6ce9c9-2261-4e70-aa88-1822b4171928.png)

**Comment by lgfa29** [comment] 2023-01-26 01:06
Hi @suikast42 👋 

That's correct, I believe this is not currently possible. From our [documentation](https://developer.hashicorp.com/nomad/docs/runtime/interpolation):

> Node attributes are interpretable in constraints, task environment variables, and certain driver fields. Runtime environment variables are not interpretable in constraints because they are only defined once the scheduler has placed them on a particular node.

I think we may be able to do it in Consul tags since the information would be available at runtime. I have places this feature request for further roadmapping. Thanks for the submission!

**Comment by suikast42** [comment] 2023-01-26 10:19
> I think we may be able to do it in Consul tags since the information would be available at runtime. I have places this feature request for further roadmapping. Thanks for the submission!

you are right. over consul the tags are set as expected.  See server and test. 
Server is ${NOMAD_ALLOC_NAME}  and test ${node.unique.id}

```shell
zsh>  curl   -s  -N \
--cacert "${CONSUL_CACERT}" \
--cert "${CONSUL_CLIENT_CERT}" \
--key "${CONSUL_CLIENT_KEY}" \
https://"${CONSUL_HTTP_ADDR}"/v1/catalog/service/minio | jq .
```

```json
[
  {
    "ID": "556babca-437d-af04-af04-c8989f28dd32",
    "Node": "worker-01",
    "Address": "10.21.21.42",
    "Datacenter": "nomadder1",
    "TaggedAddresses": {
      "lan": "10.21.21.42",
      "lan_ipv4": "10.21.21.42",
      "wan": "10.21.21.42",
      "wan_ipv4": "10.21.21.42"
    },
    "NodeMeta": {
      "consul-network-segment": "",
      "node_type": "worker"
    },
    "ServiceKind": "",
    "ServiceID": "_nomad-task-86bf3ea0-042f-c6d2-ab80-9ed6cf5f8d4f-minio-minio-http",
    "ServiceName": "minio",
    "ServiceTags": [
      "prometheus_minio",
      "frontend",
      "minio",
      "server=minio.minio[0]",
      "test=1117a0ed-de14-25cc-0787-0d21dfa9d96e",
      "traefik.enable=true",
      "traefik.consulcatalog.connect=false",
      "traefik.http.routers.minio.tls=true",
      "traefik.http.routers.minio.rule=Host(`minio.cloud.private`)"
    ],
    "ServiceAddress": "10.21.21.42",
    "ServiceTaggedAddresses": {
      "lan_ipv4": {
        "Address": "10.21.21.42",
        "Port": 23999
      },
      "wan_ipv4": {
        "Address": "10.21.21.42",
        "Port": 23999
      }
    },
    "ServiceWeights": {
      "Passing": 1,
      "Warning": 1
    },
    "ServiceMeta": {
      "external-source": "nomad"
    },
    "ServicePort": 23999,
    "ServiceSocketPath": "",
    "ServiceEnableTagOverride": false,
    "ServiceProxy": {
      "Mode": "",
      "MeshGateway": {},
      "Expose": {}
    },
    "ServiceConnect": {},
    "CreateIndex": 20217,
    "ModifyIndex": 22029
  }
]
```

**Comment by lgfa29** [comment] 2023-01-27 00:06
Ah, so the problem is that the tags are not interpolated in the Nomad UI?

**Comment by suikast42** [comment] 2023-01-27 09:07
Right

**Comment by lgfa29** [comment] 2023-01-27 21:03
Cool, thanks for the clarification. I think the UI reads this information from the jobspec directly because that's the only source it has, otherwise it would need to query the Consul API, which it may not be able to.

Since this is about the UI it's a duplicate of #9835 so I'm going to close this one, but feel free to add more context there if you have anything else to add.

Thanks for the report!

**Closed by lgfa29** 2023-01-27 21:03 UTC
Labels: type/enhancement, stage/accepted, theme/service-discovery
