### ISSUE TITLE
Nomad Logs, Cat, ReadAt API calls timeout silently and appear unnecessarily slow as a result

### ISSUE THREAD

**Issue by robinovitch61** [hashicorp/nomad#13800] opened 2022-07-18 02:02 UTC
### Nomad version
v1.3.1

### Operating system and Environment details
MacOS local machine querying Nomad running on Ubuntu in AWS

### Issue
I am moving from directly crafting http queries to the nomad api to using the [provided nomad go api client](https://github.com/hashicorp/nomad/tree/cd047cdc03cdc61c7ebf1ea60615eff96509b606/api), which has all the configuration boilerplate I could want and I am very happy exists!

But, I ran into a hard to track down issue when porting my application to this client. There is an action taken in [fs.queryClientNode](https://github.com/hashicorp/nomad/blob/cd047cdc03cdc61c7ebf1ea60615eff96509b606/api/fs.go#L178-L210) that silently slows down the [Logs](https://github.com/hashicorp/nomad/blob/cd047cdc03cdc61c7ebf1ea60615eff96509b606/api/fs.go#L233), [Cat](https://github.com/hashicorp/nomad/blob/cd047cdc03cdc61c7ebf1ea60615eff96509b606/api/fs.go#L109), and [ReadAt](https://github.com/hashicorp/nomad/blob/cd047cdc03cdc61c7ebf1ea60615eff96509b606/api/fs.go#L97) api calls in some situations. It tries to query from the node first, with a default timeout of 1s. If that times out, it falls back to querying the server, which returns very quickly. In my case, it was timing out every time silently, then falling back to the server call and returning quickly, but it took awhile of looking at the code and realizing that's what was occurring before I was able to grok everything.

After realizing this was the case, I had to add the following in my application before my call to `Logs`
```
// This is currently very important and strange. The logs api attempts to go through the node directly
// by default. The default timeout for this is 1 second. If it fails, it falls silently to going through
// the server. Since it always fails, at least in my Nomad setup, make it timeout immediately by setting
// the timeout to something tiny.
api.ClientConnTimeout = 1 * time.Microsecond
```

### Reproduction steps
On a nomad server where node queries consistently fail/timeout, hit the logs API, and note that it could never be faster than 1s roundtrip time unless you manually set `api.ClientConnTimeout` to something very small before calling it.

#### Expected Result
Logs api is as fast as possible without a silent 1s timeout.

#### Actual Result
Logs, Cat, and ReadAt are at least 1s long unless you set `api.ClientConnTimeout` to something smaller or have a nomad setup where node queries return successfully and quickly.

The only "code" changes required here might be to document the `api.ClientConnTimeout` in the docstrings for `Logs`, `Cat`, and `ReadAt`, or there may be some better way to redesign these api calls so the default behavior is more transparent, expected, and performant.

**Comment by tgross** [comment] 2022-07-25 17:29
Hi @robinovitch61! This is going to be a bit of a long response because if you're using the Go API I want to do what I can to help your understanding of the whole system. But tl;dr yes, setting `api.ClientConnTimeout = 1 * time.Microsecond` is probably the right move _for your environment._

The behavior you're seeing here is by design and an optimization, but you're hitting a particularly painful edge case. From a high-level view, Nomad's RPC system is designed to allow an HTTP API call to hit any server or client on the cluster, get mapped to an RPC call, and then forward that RPC call to the appropriate server or client. There are a few quirks:

* We don't require that clients are reachable from each other.
* Most APIs need to get forwarded to the leader, but allocation APIs (like Alloc FS) need to get sent to the specific client node where the allocation is running.
* Each client node is connected to a _specific_ server at any one time.

For example, let's look at this cluster:

```mermaid
graph TD;

  serverA(Server A Leader);
  serverB(Server B);
  serverC(Server C);
  clientB(Client B);
  clientC(Client C);

  subgraph Servers
    serverA --- serverB;
    serverB --- serverC;
    serverC --- serverA;
  end

  serverB --> clientB;
  serverC --> clientC;
```

If I make an Alloc FS API call to Client B for an allocation running on Client C, the HTTP call will get translated to a RPC that goes from Client B to Server B, gets forwarded to Server A (the leader), and from there to Server C because it "owns" the connection to Client C, and finally to Client C. Forwarding to a client can mean bouncing around the cluster quite a bit!

So what does this have to do with your problem? Because if we _can_ talk directly with a client, we avoid all this bouncing around the network, which is good for latency and reliability, and reduces load on the already hard-working leader. This is by far the most common case in our experience. But if you _can't_ talk directly to the clients, you're hitting the timeout that you've got here first. So that's why you'll want to disable that timeout.

**Comment by robinovitch61** [comment] 2022-07-25 17:57
Thank you for your comprehensive reply @tgross !

> if we can talk directly with a client, we avoid all this bouncing around the network, which is good for latency and reliability, and reduces load on the already hard-working leader. This is by far the most common case in our experience. But if you can't talk directly to the clients, you're hitting the timeout that you've got here first. So that's why you'll want to disable that timeout.

Gotcha, this makes sense to me now that you've laid it out. So given that I'm building an [application that will use the Go API to hit a variety of differently configured nomad clusters](https://github.com/robinovitch61/wander), I may actually want to expose a boolean config value e.g. `"attempt_client_connection"`, defaulting to false, but if true, does not set the timeout to a tiny value such that client connection attempts happen. I'd slap a warning on it saying "if true, will decrease load on the leader, but will increase log retrieval times by at least 1 second if your cluster cannot access clients directly".

Is there something we could configure in our nomad cluster to allow client connections to pass, or am I misunderstanding why they fail within the 1s timeout in our cluster?

I do think the timeout could be documented better, as I did have to read through source code for a bit to find it. That might be the only "coding" task here, if any.

**Comment by tgross** [comment] 2022-07-25 19:04
> Is there something we could configure in our nomad cluster to allow client connections to pass, or am I misunderstanding why they fail within the 1s timeout in our cluster?

It should "just work" assuming you have direct "line of sight" from where you're running `wander` to the client node's advertised IP address. But for example, if the client nodes are on private IPs and you're using `wander` from your laptop, you might have a setup where the servers are reachable (ex. via a reverse proxy) but not the clients. It really depends on your network topology.

> I do think the timeout could be documented better, as I did have to read through source code for a bit to find it. That might be the only "coding" task here, if any.

Yeah it's documented at [Variables](https://pkg.go.dev/github.com/hashicorp/nomad/api#pkg-variables) but it's definitely not obvious. It might be nice to add this to [`api.Config`](https://pkg.go.dev/github.com/hashicorp/nomad/api#Config) as well. That'd make it so that you could configure clients with separate values, and it could fall back to the package global if unset for backwards compatibility. I'd be happy to review a PR for that if you were interested.

**Comment by robinovitch61** [comment] 2022-07-25 19:26
Ok gotcha, yes I believe our network topology is such that servers are reachable but not the clients. Thanks for clarifying that for me!

> Yeah it's documented at [Variables](https://pkg.go.dev/github.com/hashicorp/nomad/api#pkg-variables)

Nice, I should have read through this. 

> It might be nice to add this to [api.Config](https://pkg.go.dev/github.com/hashicorp/nomad/api#Config) as well.

Agreed, that would be cool! I'll likely put up a PR for this sometime this summer. Thanks!

**Comment by tgross** [comment] 2022-08-15 19:36
I've opened #14122 with the API docs update and that'll close this issue once merged. But if you do end up submitting a PR to add the field to `api.Config` I'd be happy to review it. Thanks!

**Closed** 2022-08-15 20:06 UTC
Labels: type/question, theme/api, theme/allocation API
