### ISSUE TITLE
Docker driver can't pull images when configured to use a Docker repo config file

### ISSUE THREAD

**Issue by tmichaud314** [hashicorp/nomad#2388] opened 2017-03-01 23:34 UTC
### Nomad version
Nomad v0.5.5-rc1

### Operating system and Environment details
Darwin/Linux.

### Issue
When nomad is configured to use a private Docker repository and get auth info from a docker-formatted config file, all image pulls fail.

The docker-driver does not use the docker-repository auth configuration specified as a driver option:
```
{
    "client": {
        "enabled": true,
        "options": {
            "docker.auth.config": "/Users/tom/.docker/config.json"
        }
    }
}
```
### Reproduction steps
```
#
# Replace repository name and <hashed password>.
#
$ cat > docker_config.json
{
  "auths": {
    "https://index.docker.io/v1/": {
      "auth": "<hashed password>"
    }
  }
}

$ cat>test_conf.hcl
{
    "client": {
        "enabled": true,
        "options": {
            "docker.auth.config": "./docker_config.json"
        }
    }
}
<EOF>
$ nomad agent -dev -config ./test_conf.hcl

#
# See job definition below
#
$ nomad run job.hcl

### Nomad Server logs (if appropriate)

### Nomad Client logs (if appropriate)
```
    2017/03/01 16:27:35.256533 [DEBUG] client: driver event for alloc "a3e2597a-4e3b-8065-6609-57712074e68b": Downloading image mycompany/myservice:latest
    2017/03/01 16:27:35.257204 [WARN] client: error from prestart: failed to initialize task "myservice" for alloc "a3e2597a-4e3b-8065-6609-57712074e68b": Failed to pull `mycompany/myservice`: API error (404): {"message":"repository mycompany/myservice not found: does not exist or no pull access"}
    2017/03/01 16:27:35.257637 [INFO] client: Restarting task "myservice" for alloc "a3e2597a-4e3b-8065-6609-57712074e68b" in 17.965784493s
    2017/03/01 16:27:35.392039 [DEBUG] client: updated allocations at index 17 (total 1) (pulled 0) (filtered 1)
```
### Job file (if appropriate)

job "test" {
  # Specify this job should run in the region named "us". Regions
  # are defined by the Nomad servers' configuration.
  region = "global"

  # Spread the tasks in this job between us-west-1 and us-east-1.
  datacenters = ["dc1"]

  # Run this job as a "service" type. Each job type has different
  # properties. See the documentation below for more examples.
  type = "service"

  # Specify this job to have rolling updates, two-at-a-time, with
  # 30 second intervals.
  update {
    stagger      = "30s"
    max_parallel = 1
  }

  # A group defines a series of tasks that should be co-located
  # on the same client (host). All tasks within a group will be
  # placed on the same host.
  group "services" {
    # Specify the number of these tasks we want.
    count = 1

    # Create an individual task (unit of work). This particular
    # task utilizes a Docker container to front a web application.
    task "myservice" {
      # Specify the driver to be "docker". Nomad supports
      # multiple drivers.
      driver = "docker"

      # Configuration is specific to each driver.
      config {
        image = "mycompany/myservice"
	force_pull = true
      }

      # The service block tells Nomad how to register this service
      # with Consul for service discovery and monitoring.
      service {
	name = "myservice"

        # This tells Consul to monitor the service on the port
        # labled "http". Since Nomad allocates high dynamic port
        # numbers, we use labels to refer to them.
        port = "http"

        check {
          type     = "http"
          path     = "/health"
          interval = "10s"
          timeout  = "2s"
        }
      }

      # It is possible to set environment variables which will be
      # available to the job when it runs.
      env {
	      "TEST"="123"
      }

      # Specify the maximum resources required to run the job,
      # include CPU, memory, and bandwidth.
      resources {
        cpu    = 500 # MHz
        memory = 128 # MB

        network {
          mbits = 100

          # This requests a dynamic port named "http". This will
          # be something like "46283", but we refer to it via the
          # label "http".
          port "http" {}

        }
      }
    }
  }
}

**Comment by dadgar** [comment] 2017-03-01 23:51
Fixed by https://github.com/hashicorp/nomad/pull/2389.
Just tested and verified locally.

**Comment by dadgar** [comment] 2017-03-01 23:52
Awesome issue description btw! 🔥

**Closed by dadgar** 2017-03-01 23:51 UTC

**Comment by tmichaud314** [comment] 2017-03-03 19:56
@dadgar Thanks.  BTW - I noticed 2388 isn't listed in the 0.5.5 CHANGELOG.

**Comment by dadgar** [comment] 2017-03-03 21:27
@tmichaud314 Hey that is because the regression was introduced only in 0.5.5 and never a released version
