### ISSUE TITLE
Vault address is ignored in nomad clients on v1.7.0

### ISSUE THREAD

**Issue by L-P** [hashicorp/nomad#19380] opened 2023-12-08 10:34 UTC
### Nomad version
```
# nomad version
Nomad v1.7.0
BuildDate 2023-12-07T08:28:54Z
Revision e4150e9703f3be6ee2339f0e45ff0801186e022b
```

### Operating system and Environment details
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
# uname -a
Linux worker-plane 6.1.0-13-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
```

Running on AWS EC2 t3.small.

### Issue
Nomad client attempts to reach local vault agent Vault using `127.0.0.1:8200`,
ignoring its configuration.

Downgrading the client to v1.6.4 fixes the issue.

### Reproduction steps
1. Follow what is now the "legacy" vault setup using a local vault agent
   configured to listen on a socket:
   ```
   vault {
     enabled = true
     address = "unix:///var/run/vault/agent.socket"
     create_from_role = "nomad-cluster"
   }
   ```

#### Expected Result
The value of `address` is used to connect to the vault agent.

#### Actual Result
Another value is used, thus failing to reach the agent.

### Job file (if appropriate)
Uses templates with `{{with secret "<path>"}}`.

### Nomad Server logs (if appropriate)
n/a

### Nomad Client logs (if appropriate)
```
2023-12-08T10:08:32.525Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=e3289405-b9fb-3498-290a-0d1a5a44b59a task=fabio type=Killing msg="Template failed: vault.write(pki_int/issue/consul -> 1656cb6c): vault.write(pki_int/issue/consul -> 1656cb6c): Put \"https://127.0.0.1:8200/v1/pki_int/issue/consul\": dial tcp 127.0.0.1:8200: connect: connection refused" failed=true
```

**Comment by tgross** [comment] 2023-12-08 15:17
Hi @L-P! Unfortunately I wasn't able to reproduce this. I used the following Vault listener config:

```hcl
listener "unix" {
  address = "/home/tim/tmp/vault.sock"
}
```

The following Nomad `vault` config block:

```hcl
vault {
  address = "unix:///home/tim/tmp/vault.sock"
  token = "<redacted>"
  enabled = true
}
```

And just for good measure, I ensured that no traffic could be getting to the TCP listener `sudo iptables -A INPUT -i lo -p tcp --dport 8200 -j DROP`. I can see a successful fingerprint via `nomad node status -self -verbose | grep vault` and a job I ran with a template seems to be working.

As an aside, I noticed that you don't have a `token` field in your configuration, which suggest to me that you might be using the `VAULT_TOKEN` environment variable. This was accidentally broken in 1.7.0 and fixed in https://github.com/hashicorp/nomad/pull/19349 which will go out shortly in Nomad 1.7.1.

**Comment by tgross** [comment] 2023-12-11 18:31
Thanks @L-P! @lgfa29 are still working on a reproduction. Just one question for clarity: your job has a `vault` block in the group or task, with the appropriate policies, right?

**Comment by tgross** [comment] 2023-12-11 20:35
Hi @L-P I think I've got a reproduction here and it's at the intersection of a missing `vault` block in the job and the peculiarities of how the Vault agent proxies access to Vault.

I ran Vault in dev mode with the following configuration:

```hcl
listener "tcp" {
  address = "127.0.0.1:8202"
  cluster_address = "127.0.0.1:8203"
  tls_disable = true
}
```

I ran a Vault Agent with the following configuration:

```hcl
pid_file = "/home/tim/tmp/.vault-agent-pidfile"

vault {
  address = "http://127.0.0.1:8202"
  retry {
    num_retries = 5
  }
}

auto_auth {
  method {
    type = "token_file"

    config = {
      token_file_path = "/home/tim/.vault-token"
    }
  }

}

cache {}

api_proxy {
  use_auto_auth_token = true
}

listener "unix" {
  address = "/home/tim/tmp/vault.sock"
  tls_disable = true

  agent_api {
    enable_quit = true
  }
}
```

My Nomad agent's `vault` config block is:

```hcl
vault {
  address = "unix:///home/tim/tmp/vault.sock"
  token = "hvs.<redacted>"
  create_from_role = "nomad-cluster"
  enabled = true
}
```

Last, I configured an iptables rule to ensure that it was impossible for traffic on the default port to work: `sudo iptables -A INPUT -i lo -p tcp --dport 8200 -j DROP`.

Then I ran through the [Vault integration and retrieving dynamic secrets tutorial](https://developer.hashicorp.com/nomad/tutorials/integrate-vault/vault-postgres):
* First I ran through with Nomad 1.6.4 to make sure I had a working setup
* Then I ran through with Nomad 1.7.0, and it works just fine.
* Then I ran through with Nomad 1.7.0 again, but this time I removed the `vault` block from the job that needs secrets. This time it failed! The Consul Template configuration in the logs shows an empty string for the address, rather than the unix domain socket. So CT picks up the default address which won't work.

I've got a preliminary patch that seems to fix the problem by not requiring the `vault` block to get a valid template runner configuration:

```diff
diff --git a/client/allocrunner/taskrunner/template_hook.go b/client/allocrunner/taskrunner/template_hook.go
index 3824dd02a8..4e00be2778 100644
--- a/client/allocrunner/taskrunner/template_hook.go
+++ b/client/allocrunner/taskrunner/template_hook.go
@@ -213,14 +213,8 @@ func (h *templateHook) newManager() (unblock chan struct{}, err error) {
        unblock = make(chan struct{})

        var vaultConfig *structsc.VaultConfig
-       if h.task.Vault != nil {
-               vaultCluster := h.task.GetVaultClusterName()
-               vaultConfig = h.config.clientConfig.GetVaultConfigs(h.logger)[vaultCluster]
-
-               if vaultConfig == nil {
-                       return nil, fmt.Errorf("Vault cluster %q is disabled or not configured", vaultCluster)
-               }
-       }
+       vaultCluster := h.task.GetVaultClusterName()
+       vaultConfig = h.config.clientConfig.GetVaultConfigs(h.logger)[vaultCluster]

        tg := h.config.alloc.Job.LookupTaskGroup(h.config.alloc.TaskGroup)
        consulCluster := h.task.GetConsulClusterName(tg)
```

Ordinarily leaving out the `vault` block won't work at all, but it works with the Vault agent because it passes the request through with its own token.

**Comment by L-P** [comment] 2023-12-12 07:46
I can confirm I don't have a `vault` block in the job.  

I tried adding one but it failed because `Task x has a Vault block with an empty list of policies`, which is odd because per the docs "it is deprecated" and I had the role set.  
If I set the policies instead, nothing happens. The job is created with 0 allocations. (Not unplaced allocations, no allocations at all.)

So I don't seem to have a workaround.

**Comment by tgross** [comment] 2023-12-12 14:03
Ah, the docs could definitely be much more clear on this. The new `vault.role` field only works with the new Workload Identity workflow. So if you have a `vault` block it'll be expecting `policies`.

> f I set the policies instead, nothing happens. The job is created with 0 allocations. (Not unplaced allocations, no allocations at all.)

It'd be worth taking a look at the eval status of the eval created when you submit the job, as well as the debug-level logs on the scheduler for that eval.

**Closed** 2023-12-12 19:06 UTC
Labels: type/bug, theme/config, theme/vault
