### ISSUE TITLE
failed to contact Windows Server

### ISSUE THREAD

**Issue by LukeMauldin** [hashicorp/nomad#10209] opened 2021-03-22 17:14 UTC
### Nomad version
Output from `nomad version`
Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)

### Operating system and Environment details
Redhat Linux 8.3 and Windows Server 2019

### Issue
Have Consul/Nomad with 3 master nodes. 2 of the nodes are on Redhat Linux 8.3 and 1 node is on Windows Server 2019.  The nodes are all running on VMs hosted on a hyper-converged system located in one physical data center with 10GB networking. In the nomad log files on Linux I see connection errors to the windows server like the errors below.  I never see any connection errors between the 2 linux master nodes.  I have tried running the Linux/Windows VMs on different underlying physical nodes and it is always the same result.  I never seen `failed to contact` errors between the Linux VMs but I always see the errors when connecting between the Linux <-> Windows VMs.  The errors only occur every few hours and as far as I can tell, the Nomad cluster is operating normally.  I see similar `failed to contact` errors in Consul as well between the Linux <-> Windows master VMs.  I do not think this is part of networking issues in our hyper-converged system because we have Mongo running on different VMs and the mongo replica set also has some Linux and some Windows nodes and there are no errors reported in its logs.  
I have seen this behavior in Nomad 0.12.5 and Nomad 1.0.4.

```
2021-03-22T06:00:02.622-0500 [INFO]  nomad.raft: snapshot complete up to: index=3422882
2021-03-22T09:48:54.672-0500 [WARN]  nomad.raft: failed to contact: server-id=9c67cf7b-ab71-e3ca-64a4-a4c6783deeac time=500.098112ms
2021-03-22T09:48:59.109-0500 [WARN]  nomad.raft: failed to contact: server-id=9c67cf7b-ab71-e3ca-64a4-a4c6783deeac time=500.043916ms
2021-03-22T09:49:00.261-0500 [WARN]  nomad.raft: failed to contact: server-id=9c67cf7b-ab71-e3ca-64a4-a4c6783deeac time=500.076867ms
2021-03-22T09:49:01.124-0500 [WARN]  nomad.raft: failed to contact: server-id=9c67cf7b-ab71-e3ca-64a4-a4c6783deeac time=500.095779ms
2021-03-22T09:49:01.701-0500 [WARN]  nomad.raft: failed to contact: server-id=9c67cf7b-ab71-e3ca-64a4-a4c6783deeac time=500.07739ms
2021-03-22T09:49:02.296-0500 [WARN]  nomad.raft: failed to contact: server-id=9c67cf7b-ab71-e3ca-64a4-a4c6783deeac time=500.130119ms
2021-03-22T09:49:02.746-0500 [WARN]  nomad.raft: failed to contact: server-id=9c67cf7b-ab71-e3ca-64a4-a4c6783deeac time=950.886433ms
2021-03-22T10:43:30.414-0500 [INFO]  nomad.raft: starting snapshot up to: index=3431191
2021-03-22T10:43:30.414-0500 [INFO]  snapshot: creating new snapshot: path=/opt/nomad/data/server/raft/snapshots/3389-3431191-1616427810414.tmp
2021-03-22T10:43:30.486-0500 [INFO]  snapshot: reaping snapshot: path=/opt/nomad/data/server/raft/snapshots/3389-3419728-1616384011983
2021-03-22T10:43:30.488-0500 [INFO]  nomad.raft: compacting logs: from=3412643 to=3420951
2021-03-22T10:43:30.512-0500 [INFO]  nomad.raft: snapshot complete up to: index=3431191
2021-03-22T11:27:53.214-0500 [WARN]  nomad.raft: failed to contact: server-id=9c67cf7b-ab71-e3ca-64a4-a4c6783deeac time=500.098098ms
2021-03-22T11:39:09.373-0500 [WARN]  nomad.raft: failed to contact: server-id=9c67cf7b-ab71-e3ca-64a4-a4c6783deeac time=500.088852ms
2021-03-22T11:48:06.384-0500 [WARN]  nomad.raft: failed to contact: server-id=9c67cf7b-ab71-e3ca-64a4-a4c6783deeac time=500.095903ms
2021-03-22T12:00:02.519-0500 [INFO]  nomad.raft: starting snapshot up to: index=3434120
```

**Comment by tgross** [comment] 2021-03-22 17:26
> I do not think this is part of networking issues in our hyper-converged system because we have Mongo running on different VMs and the mongo replica set also has some Linux and some Windows nodes and there are no errors reported in its logs.

I suspect Mongo replicas are asynchronous as far as I know, which doesn't have the hard latency requirements we do with raft. Can you verify that the latency between all nodes is <10ms and that it's consistent?

**Comment by LukeMauldin** [comment] 2021-03-22 18:05
See the ping times below.  These times are very consistent and there are no host or application firewalls between the VMs.


```
[root@usgvt1nomadp01 consul]# ping -c 10 linuxvm
PING linuxvm (XXX.XXX.XXX.215) 56(84) bytes of data.
64 bytes from linuxvm (XXX.XXX.XXX.215): icmp_seq=1 ttl=64 time=0.061 ms
64 bytes from linuxvm (XXX.XXX.XXX.215): icmp_seq=2 ttl=64 time=0.092 ms
64 bytes from linuxvm (XXX.XXX.XXX.215): icmp_seq=3 ttl=64 time=0.253 ms
64 bytes from linuxvm (XXX.XXX.XXX.215): icmp_seq=4 ttl=64 time=0.271 ms
64 bytes from linuxvm (XXX.XXX.XXX.215): icmp_seq=5 ttl=64 time=0.098 ms
64 bytes from linuxvm (XXX.XXX.XXX.215): icmp_seq=6 ttl=64 time=0.184 ms
64 bytes from linuxvm (XXX.XXX.XXX.215): icmp_seq=7 ttl=64 time=0.217 ms
64 bytes from linuxvm (XXX.XXX.XXX.215): icmp_seq=8 ttl=64 time=0.483 ms
64 bytes from linuxvm (XXX.XXX.XXX.215): icmp_seq=9 ttl=64 time=0.201 ms
64 bytes from linuxvm (XXX.XXX.XXX.215): icmp_seq=10 ttl=64 time=0.091 ms

--- linuxvm ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 241ms
rtt min/avg/max/mdev = 0.061/0.195/0.483/0.119 ms

[root@usgvt1nomadp01 consul]# ping -c 10 windowsvm
PING windowsvm (XXX.XXX.XXX.216) 56(84) bytes of data.
64 bytes from windowsvm (XXX.XXX.XXX.216): icmp_seq=1 ttl=128 time=0.211 ms
64 bytes from windowsvm (XXX.XXX.XXX.216): icmp_seq=2 ttl=128 time=0.433 ms
64 bytes from windowsvm (XXX.XXX.XXX.216): icmp_seq=3 ttl=128 time=0.235 ms
64 bytes from windowsvm (XXX.XXX.XXX.216): icmp_seq=4 ttl=128 time=0.277 ms
64 bytes from windowsvm (XXX.XXX.XXX.216): icmp_seq=5 ttl=128 time=0.313 ms
64 bytes from windowsvm (XXX.XXX.XXX.216): icmp_seq=6 ttl=128 time=0.346 ms
64 bytes from windowsvm (XXX.XXX.XXX.216): icmp_seq=7 ttl=128 time=0.408 ms
64 bytes from windowsvm (XXX.XXX.XXX.216): icmp_seq=8 ttl=128 time=0.295 ms
64 bytes from windowsvm (XXX.XXX.XXX.216): icmp_seq=9 ttl=128 time=0.373 ms
64 bytes from windowsvm (XXX.XXX.XXX.216): icmp_seq=10 ttl=128 time=0.162 ms

--- windowsvm ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 181ms
rtt min/avg/max/mdev = 0.162/0.305/0.433/0.083 ms
```

**Comment by tgross** [comment] 2021-03-23 13:45
> See the ping times below. These times are very consistent and there are no host or application firewalls between the VMs.

Ok, great. So that should confirm that network topology isn't the issue, but given that you're having the same issue on Consul I'm wondering if there's something in the Windows machine's configuration that's causing a problem for the applications. 

There are a couple places you can start looking:

* Are you running Nomad and Consul servers on the same VM? (Not just a Consul agent on the Nomad server node, but a full server.) That might be causing resource pressure, and it's possible the Windows machine is hitting limits before the Linux machines. Take a look at your infrastructure metrics around CPU and disk IO.
* Look at that server's [metrics](https://www.nomadproject.io/docs/operations/metrics) and compare them to the Linux machines. You'll especially want to look at things like `nomad.raft.commitTime` and `nomad.raft.fsm.apply`, which could indicate disk IO issues, or `nomad.runtime.*` which could indicate platform-specific memory usage issues.
* The issue is happening frequently but with some long gaps in between, which means that it's going to be tough to "catch" with [`nomad operator debug`](https://www.nomadproject.io/docs/commands/operator/debug). But with [`enable_debug=true`](https://www.nomadproject.io/docs/configuration#enable_debug) you could capture the output of `/v1/agent/pprof/profile` every, say, 60s until you get a failure and then send us a few of those profiles leading up to the failure, and we could try to see if there's anything unexpected there.

Just out of curiosity, why are you running different host OS's for the servers? I can't think of any reason why it shouldn't work, but it's uncommon enough of a configuration that it makes me wonder if there's some other information about your environment that I'm missing.

**Comment by LukeMauldin** [comment] 2021-03-23 15:11
Thank you for the response.  I am running Nomad and Consul servers on the same VM but our Nomad/Consul cluster is relatively small - about 20 agent nodes.  The Nomad/Consul servers have 8 GB of memory and I have monitoring setup on the servers.  They are averaging around 25% CPU utilization, 45% max CPU utilization, less than 50% memory utilization, under 2MB/s disk read/write and under 3.0 Mbps.  The Linux servers are sized to the exact same specifications as the Windows server and are seeing similar utilization stats.
I ran a metrics export from Nomad and `nomad.raft.commitTime` was not present in either Linux or Windows nomad metrics.  The `nomad.runtime.*` stats look pretty similar to me but I did see some differences in `nomad.raft.fsm.apply` which you can see below.  Since the Windows VM has such as higher max `nomad.raft.fsm.apply`, I wonder if it is related to how Go is flushing that data to disk?
Regarding "why different OS's for the servers", that is a longer story.  In short, we were bitten by the RHEL 8.3 bug: https://access.redhat.com/solutions/5542661 which resulted in OS level corruption of our servers and we had to rebuild 20+ production servers from scratch.  It was a bad day.  Moving forward, we decided we wanted our environment to be heterogeneous where possible to prevent one bad vendor patch from destroying our infrastructure.
Linux VM:
```
 {
            "Count": 9,
            "Labels": {
                "host": "linuxvm"
            },
            "Max": 0.4163540005683899,
            "Mean": 0.3596254454718696,
            "Min": 0.33657899498939514,
            "Name": "nomad.nomad.fsm.alloc_client_update",
            "Rate": 0.32366290092468264,
            "Stddev": 0.025047221380456612,
            "Sum": 3.236629009246826
        },
        {
            "Count": 9,
            "Labels": {
                "host": "linuxvm"
            },
            "Max": 0.42945799231529236,
            "Mean": 0.37441044714715743,
            "Min": 0.3507950007915497,
            "Name": "nomad.raft.fsm.apply",
            "Rate": 0.3369694024324417,
            "Stddev": 0.026111969664582,
            "Sum": 3.369694024324417
        },
		{
            "Labels": {
                "host": "linuxvm"
            },
            "Name": "nomad.runtime.alloc_bytes",
            "Value": 34375416.0
        },
        {
            "Labels": {
                "host": "linuxvm"
            },
            "Name": "nomad.runtime.free_count",
            "Value": 278037216.0
        },
        {
            "Labels": {
                "host": "linuxvm"
            },
            "Name": "nomad.runtime.heap_objects",
            "Value": 267415.0
        },
        {
            "Labels": {
                "host": "linuxvm"
            },
            "Name": "nomad.runtime.malloc_count",
            "Value": 278304640.0
        },
        {
            "Labels": {
                "host": "linuxvm"
            },
            "Name": "nomad.runtime.num_goroutines",
            "Value": 151.0
        },
        {
            "Labels": {
                "host": "linuxvm"
            },
            "Name": "nomad.runtime.sys_bytes",
            "Value": 217898000.0
        },
        {
            "Labels": {
                "host": "linuxvm"
            },
            "Name": "nomad.runtime.total_gc_pause_ns",
            "Value": 197990080.0
        },
        {
            "Labels": {
                "host": "linuxvm"
            },
            "Name": "nomad.runtime.total_gc_runs",
            "Value": 2114.0
        },
```


Windows VM:
```
        {
            "Count": 7,
            "Labels": {
                "host": "windowsvm"
            },
            "Max": 15.62339973449707,
            "Mean": 2.2319142477852956,
            "Min": 0.0,
            "Name": "nomad.nomad.fsm.alloc_client_update",
            "Rate": 1.562339973449707,
            "Stddev": 5.905090047261686,
            "Sum": 15.62339973449707
        },
        {
            "Count": 7,
            "Labels": {
                "host": "windowsvm"
            },
            "Max": 15.62339973449707,
            "Mean": 2.2319142477852956,
            "Min": 0.0,
            "Name": "nomad.raft.fsm.apply",
            "Rate": 1.562339973449707,
            "Stddev": 5.905090047261686,
            "Sum": 15.62339973449707
        },
		{
            "Labels": {
                "host": "windowsvm"
            },
            "Name": "nomad.runtime.alloc_bytes",
            "Value": 34016520.0
        },
        {
            "Labels": {
                "host": "windowsvm"
            },
            "Name": "nomad.runtime.free_count",
            "Value": 258607936.0
        },
        {
            "Labels": {
                "host": "windowsvm"
            },
            "Name": "nomad.runtime.heap_objects",
            "Value": 267194.0
        },
        {
            "Labels": {
                "host": "windowsvm"
            },
            "Name": "nomad.runtime.malloc_count",
            "Value": 258875120.0
        },
        {
            "Labels": {
                "host": "windowsvm"
            },
            "Name": "nomad.runtime.num_goroutines",
            "Value": 137.0
        },
        {
            "Labels": {
                "host": "windowsvm"
            },
            "Name": "nomad.runtime.sys_bytes",
            "Value": 147902720.0
        },
        {
            "Labels": {
                "host": "windowsvm"
            },
            "Name": "nomad.runtime.total_gc_pause_ns",
            "Value": 129478496.0
        },
        {
            "Labels": {
                "host": "windowsvm"
            },
            "Name": "nomad.runtime.total_gc_runs",
            "Value": 2020.0
        },
```

**Comment by tgross** [comment] 2021-03-23 17:59
Ok, now we're getting somewhere. These are small samples but it seems suspicious. The Linux machine is able to write to raft in well under 1ms, whereas we see the Windows machine on average takes more than 2ms and in this sample has taken as much as 15ms, which is a lot for fairly small writes. It'd be interesting to see whether over longer periods of time those stalls end up hitting the 500ms raft timeout.

```json
       {
            "Count": 9,
            "Labels": {
                "host": "linuxvm"
            },
            "Max": 0.42945799231529236,
            "Mean": 0.37441044714715743,
            "Min": 0.3507950007915497,
            "Name": "nomad.raft.fsm.apply",
            "Rate": 0.3369694024324417,
            "Stddev": 0.026111969664582,
            "Sum": 3.369694024324417
        },
```

```json
        {
            "Count": 7,
            "Labels": {
                "host": "windowsvm"
            },
            "Max": 15.62339973449707,
            "Mean": 2.2319142477852956,
            "Min": 0.0,
            "Name": "nomad.raft.fsm.apply",
            "Rate": 1.562339973449707,
            "Stddev": 5.905090047261686,
            "Sum": 15.62339973449707
        },
```


> In short, we were bitten by the RHEL 8.3 bug: https://access.redhat.com/solutions/5542661 which resulted in OS level corruption of our servers and we had to rebuild 20+ production servers from scratch. It was a bad day.

Ouch!

We've definitely had some odd boltdb issues on Windows: https://github.com/hashicorp/nomad/issues/10086, but this doesn't seem to be the problem here. We can do some experiments to see if we can reproduce Nomad-specific disk latency here with the Windows servers.

**Comment by LukeMauldin** [comment] 2021-03-23 18:14
How can I get sample runs over a longer amount of time to catch any specific higher latencies?

**Comment by LukeMauldin** [comment] 2021-03-23 18:27
Another piece of information: I have excluded the consul and nomad data directories from all anti virus products on Windows so that should not be an issue.

**Comment by LukeMauldin** [comment] 2021-03-23 22:05
I do have Prometheus available for metrics collection if that could be helpful in some way.

**Comment by tgross** [comment] 2021-03-24 13:11
Hi @LukeMauldin, yeah I was going to recommend using something like prometheus to track Nomad's metrics (and whatever metrics you're getting from the host). See [here](https://www.nomadproject.io/docs/configuration/telemetry#prometheus) for configuration details. That'll let you correlate connection failures with any other cluster- or host-level activity that might be give us a clue here.

**Comment by LukeMauldin** [comment] 2021-03-24 14:02
I followed the steps and Prometheus is logging both nomad and consul metrics on the 3 master nodes. What should I be looking for in the metrics? Do you want me to export them in some and upload them?

**Comment by tgross** [comment] 2021-03-24 18:47
Nomad servers will be doing the most raft writes when there's a large amount of change (like a bunch of new allocations being scheduled or new nodes being added). So I'd look at the raft apply time vs both the number of jobs that are being submitted, and vs host resources on the Windows machine. The [`windows_exporter`](https://github.com/prometheus-community/windows_exporter) for Prometheus should give you some kind of disk metric, I imagine?

**Comment by tgross** [comment] 2021-06-03 15:13
It's been a while since we've heard back on this one, so I'm going to close it out. If you have more information, please feel free to reopen.

**Closed by tgross** 2021-06-03 15:13 UTC
Labels: stage/needs-investigation, stage/waiting-reply, theme/platform-windows, type/question
