### ISSUE TITLE
0.10.0 fails to compile w/ custom vendor tree (Docker 19.03.4)

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad#6583] opened 2019-10-29 08:33 UTC
```
src/github.com/hashicorp/nomad/drivers/docker/utils.go:118:57: cannot use cfile.AuthConfigs (type map[string]"github.com/docker/cli/cli/config/types".AuthConfig] as type map[string]"github.com/docker/docker/api/types".AuthConfig] in argument to "github.com/docker/docker/registry".ResolveAuthConfig
```

**Comment by notnoop** [comment] 2019-10-29 15:12
Thanks @onlyjob.  To clarify, the issue is that Nomad 0.10.0 code fails to compile if you swap the currently vendored docker library tag set in vendor/vendor.json with that of 19.03.4?

Seeing the error message, it seems that such swapping made `types.AuthConfig` resolve to `github.com/docker/cli/cli/config/types.AuthConfig` instead of `github.com/docker/docker/api/types.AuthConfig`.  Didn't investigate this but my hunch is that we need to coordinate upgrading docker related libraries in lock step instead of changing individual libraries, but this might be a very naive assumption.

We plan to upgrade docker/docker library dependency after we can do some testing to ensure that upgrading library doesn't introduce functionally backward incompatible changes.

**Comment by onlyjob** [comment] 2019-10-29 22:43
> To clarify, the issue is that Nomad 0.10.0 code fails to compile if you swap the currently vendored docker library tag set in vendor/vendor.json with that of 19.03.4?

Somewhat. We don't use `vendor.json` in our build system but the only thing changed is the version of Docker from 18.09.9 to 19.03.4.

 There is an ongoing transition to Docker 19.03.4 in Debian and we are trying to re-build all depending packages with upgraded Docker.

Is there a straightforward patch to address this problem?

**Comment by elboulangero** [comment] 2019-10-30 09:36
Seems that the issue was introduced with this commit in `docker/cli`: https://github.com/docker/cli/commit/27b2797f7deb3ca5b7f80371d825113deb1faca1

After this commit, there is now a duplicate of `github.com/docker/docker/api/types".AuthConfig` at `github.com/docker/cli/cli/config/types".AuthConfig`. Hence the mismatch.

**Comment by onlyjob** [comment] 2019-11-01 07:18
Reference upstream bug: https://github.com/docker/cli/issues/2181

**Closed** 2020-03-30 18:45 UTC
Labels: driver/docker, vendor-update
