### ISSUE TITLE
auto-revert kills healthy tasks before last stable version of task is started

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#3836] opened 2018-02-06 11:08 UTC
When performing a breaking deployment using `auto-revert`, any healthy tasks within the deployment being reverted will be killed before the reverted tasks become healthy. I am not sure whether this is a bug or feature request to add logic that; when performing auto-revert, tasks in the failed deployment which reached a healthy, running status are not killed until their reverted replacements reach the same status.   

### Nomad version
`0.7.1`

### Operating system and Environment details
Tested on `Mac OSX` and `Debian 8/9` in both local dev setup and cloud prod.

### Reproduction steps
Deploy a job with 1 group and 2 tasks within the group with an update stanza which enables `auto-revert`. Then trigger a broken deployment of one of the task groups (use a docker tag that doesn't exist) and observe that the healthy task will be killed before the revert to the last stable task group has reached running status.

### Job file details
- 1 x group
- 2 tasks within group
- update stanza:
```
  update {
    auto_revert      = true
    healthy_deadline = "15m"
    max_parallel     = 1
    min_healthy_time = "10s"
    stagger          = "10s"
  }
```

**Comment by schmichael** [comment] 2018-02-07 01:44
I'm afraid this is operating as intended. For services to be highly available in Nomad they must have a group `count > 1` (future `node-drain` improvements will rely upon this as well).

I'm going to close this for now, but if you'd like us to consider making stronger availability efforts for services with `count = 1` as a new feature feel free to reopen. It would be fairly low priority I'm afraid as raising `count > 1` is always going to be the best way to make a service highly available.

Also please let me know if I'm missing something! Thanks for the thorough report!

**Closed by schmichael** 2018-02-07 01:44 UTC
Labels: deployments, thinking
