### ISSUE TITLE
allow controlling the task stop signal

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#1755] opened 2016-09-27 09:39 UTC
It would be nice to have a `kill_singal` config for tasks as not all programs react nicely to `SIGINT` :) 

Example `php-fpm` handle signals like this

```
* SIGINT, SIGTERM: immediate termination 
* SIGQUIT: graceful stop 
* SIGUSR1: re-open log file 
* SIGUSR2: graceful reload of all workers + reload of fpm conf/binary 
```

where SIGINT will cause the process to die right away (not cleaning up), dropping any ongoing requests and give downtime / errors to the user

**Comment by sethvargo** [comment] 2016-09-27 16:10
Looks like this is [currently hardcoded](https://github.com/hashicorp/nomad/blob/ec9e395b277c2969b48040f1ce8735cab7af3b49/client/driver/executor/executor.go#L496-L498), but I agree it should be configurable.

**Comment by jippi** [comment] 2016-11-05 13:49
This is more generic, docker driver got the same problem.

Redis for example uses `SIGTERM` to graceful shutdown, and completely ignores `SIGINT`

**Comment by jippi** [comment] 2017-01-17 13:47
Recent example(s) SIGINT is quick shutdown for nginx, where SIGQUIT will be graceful "let requests finish up" signal.

Very similar to PHP-FPM, Redis and ElasticSearch too :)

**Comment by nugend** [comment] 2017-02-07 18:19
A tool I work with only interprets SIGTERM as "graceful" termination. It dies without invoking its cleanup procedures when it catches SIGQUIT.

Given that the template stanza is actually implementing this functionality, what's blocking this?

**Comment by yellowmegaman** [comment] 2017-03-03 14:34
Were useful feature indeed. I'm using containerpilot, so i have preStop and postStop steps, totally depending on SIGTERM signal + graceful timeout for it to complete.

**Comment by nugend** [comment] 2017-03-22 18:57
Could this be added to 0.6?

**Comment by dadgar** [comment] 2017-03-22 19:46
@nugend Definitely will be in a 0.6.x release.

**Comment by TUIteamup** [comment] 2017-05-05 09:00
@dadgar Is it confirmed that this will be in 0.6.x release? Thanks

**Comment by dadgar** [comment] 2017-05-05 17:03
Still shooting for 0.6.X, not 0.6.0.

**Comment by nugend** [comment] 2017-09-12 20:22
I see that 0.7 is now in the works. Is this story going to be included in that release or is it still targeted for a 0.6.X release?

**Comment by jippi** [comment] 2017-10-06 10:15
@dadgar will this make it to 0.7 ? :)

**Comment by nugend** [comment] 2017-11-02 17:52
I know that this isn't like a platform priority for you guys, but this would let me throw out some very janky shell scripting.

**Comment by nugend** [comment] 2018-01-05 19:23
@jippi I think this can be closed now.

**Closed** 2018-01-05 19:25 UTC
Labels: client, enhancement
