### ISSUE TITLE
docker is not mapping dynamic ports

### ISSUE THREAD

**Issue by mmlb** [hashicorp/nomad#185] opened 2015-10-01 05:06 UTC
Following the getting started guide I expected to see the dynamic redis ports mapped, but `docker port` returns empty. Possibly related to fsouza/go-dockerclient#220

**Comment by markpollack** [comment] 2015-10-01 15:39
I was not able to connect to the redis server using the redis-cli (tried the obvious port numbers) when following the getting started guide - how can I determine the port?  netstat didn't help much.  (using ubuntu 14.04)

**Comment by purehyperbole** [comment] 2015-10-01 16:05
I'm also hitting this issue, netstat returns nothing on the docker host.

**Comment by purehyperbole** [comment] 2015-10-01 17:39
Just leaving this here for reference: 

It turns out the container port is accessible, it's just not mapped back to loopback on the docker host. You can find the correct IP by inspecting the docker container using this command (you have to run this on the host your container is running on).

```$ docker inspect CONTAINER_ID | grep IPAddress````

You should then be able to connect using that IP/Port combination

**Comment by rvm2015** [comment] 2015-10-01 17:54
+1 This option is not functioning properly, setting dynamic_ports["redis"] or dynamic_ports["6379"] would expect to map 6370 from the docker host through to the redis container however this is not happening on either localhost or the public ip of the docker/nomad host.

    [core@bastion ~]$ ansible 10.42.0.60 -m shell -a "netstat -pan | grep LISTEN | grep 6379"
    10.42.0.60 | FAILED | rc=1 >>


     [core@bastion ~]$ ansible 10.42.0.60 -m shell -a "docker ps"
    10.42.0.60 | success | rc=0 >>
    CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
    a7210ff4470a        redis:latest        "/entrypoint.sh redi   2 minutes ago       Up 2 minutes        6379/tcp            angry_pasteur

I would expect to see something like this in the port field:
    0.0.0.0:6379->6379/tcp

**Comment by markpollack** [comment] 2015-10-01 21:27
Thanks @purehyperbole !

**Comment by dadgar** [comment] 2015-10-02 16:23
I think there might be some confusion on what dynamic ports means. When the job asks for a dynamic ports, the scheduler will pick any available port on the host. So asking for dynamic port REDIS will pick a random port. That is why you can't ping redis on its default host. Nomad sets an environment variable for each port so you can determine which port you were assigned as you can see in docker inspect.

Please see: https://www.nomadproject.io/docs/jobspec/index.html#dynamic_ports

I am going to close this issue as it is working as intended.

**Comment by mmlb** [comment] 2015-10-02 17:06
@dadgar the problem I originally encountered was with the docker driver. Reading the `Manual Port Mapping` section of the docs seems to indicate that the driver will pickup on the env var, then map the randomly selected port 1:1 to the container, then pass the env var down to the container so that it can bind to said port and/or advertise the correct port to others.

I might have mis-read that (if so the docs could probably be a little more explicit IMO), but I think this is a scenario that makes a lot of sense and should be supported.

**Comment by mmlb** [comment] 2015-10-02 17:17
I'd like to expand on the possible mis-reading of the docker driver docs.

The docs states 
```
In this case, Nomad doesn't know which container port to map to, so it maps 1:1 with the host port.
For example, 1.2.3.4:22333 will map to 22333 inside the container.

dynamic_ports = ["http"]

Your process will need to read the NOMAD_PORT_HTTP environment variable to determine which port to bind to.
```

Where did `1.2.3.4:223333` come from? Is it the tuple randomly selected by higher layer? How do I map it to lower? I read further down and see `http`. Will that correspond to the `22333` from above?

Having the code block almost looks like the start of a new subsection since it does not seem to be introduced by the previous paragraph.

If the `223333` port does in fact map to the `http` config then `dynamic_ports` section should come before the `223333` section in the docs. And there should be wording like

In this case higher layers randomly picked port `223333` to satisfy the `dynamic_ports=["http"]` directive, the container will have it's port `223333` published as `223333` on the host. The selected port can be discovered by reading the value of the `NOMAD_PORT_HTTP` environment variable (and this is where the docker driver is not behaving as documented).

**Comment by dadgar** [comment] 2015-10-02 17:19
@mmlb sorry I totally misread this. I am opening it back up.

**Closed** 2015-10-02 17:52 UTC

**Comment by vtuson** [comment] 2015-12-10 17:46
I still have this issue. Whatever combination of IP/Port I select the binding does not take effect.

"HostConfig": {
  "PortBindings": {
   "80/tcp": [
    {
     "HostPort": "8001"
    }
   ]
  },
  "RestartPolicy": {},
  "LogConfig": {}
 }

**Comment by diptanu** [comment] 2015-12-10 18:03
@vtuson Can you post your entire job config and which version of Nomad you're using?

**Comment by vtuson** [comment] 2015-12-10 18:19
Sorry, I posted in the wrong thread. My problem is while using directly go-dockerclient lib
