### ISSUE TITLE
Dispatched Parameterized Jobs Do Not Respect Constraints

### ISSUE THREAD

**Issue by Miserlou** [hashicorp/nomad#4639] opened 2018-09-04 21:14 UTC
### Nomad version
`Nomad v0.8.3 (c85483da3471f4bd3a7c3de112e95f551071769f)`

### Operating system and Environment details
Ubuntu, 20x AWS `x16.xlarge`.

### Issue
I want to ensure that only one dispatched task runs on one node at a time. I have tried this using:

```
constraint {
    operator  = "distinct_hosts"
    value     = "true"
}
```

and 

```
constraint {
  operator  = "distinct_property"
  attribute = "${node.unique.id}"
  value     = "1"
}
```

in both the `job` and `group` sections (it is forbidden in `task`).

In all cases, this does not work. Once dispatching my jobs, I can see with `docker ps` that there are many, many instances of each job type running on many nodes. 

How can I ensure that only one instance of each type of dispatched job runs on a node at a time?

**Comment by Miserlou** [comment] 2018-09-05 21:46
Any ideas?

**Comment by Miserlou** [comment] 2018-09-06 15:50
@preetapan Anything I can do to help test ideas?

**Comment by Miserlou** [comment] 2018-09-14 20:04
Any updates?

**Comment by Miserlou** [comment] 2018-09-19 20:21
This is still completely unaddressed.

**Comment by Miserlou** [comment] 2018-09-19 20:30
@dadgar ?

**Comment by insanejudge** [comment] 2018-09-20 19:40
parameterized jobs are dispatched as separate jobs, and there is no scope for inter-job constraints/scheduling, so this sounds like a mismatched expectation/feature request for that?

**Comment by Miserlou** [comment] 2018-09-20 19:48
So it's completely impossible to constrain the number of dispatched jobs per node? That can't be right.

If that's the case, that should be warned against in the documentation, and it should warn that these constraints won't be respected for parameterized jobs when the job is registered. 

However, I think it's more likely that this is just a bug or non-fully-implemented feature rather than an impossible requested. This, again, seems like a fundamental requirement of what this software is claiming to do.

**Comment by Miserlou** [comment] 2018-09-21 18:42
@dadgar can you weigh in on this?

**Comment by Miserlou** [comment] 2018-09-21 19:56
We're not even convinced that it's properly respecting `priority` either.

**Comment by kurtwheeler** [comment] 2018-09-21 20:45
https://www.hashicorp.com/blog/replacing-queues-with-nomad-dispatch, which is a large part of why we chose Nomad for our project, claims:

__Instead of relying on a centralized queue, the scheduler can serve as the queue, and it has the ability to weigh even more complex strategies like prioritization and has built-in support for failure handing.__

Do parameterized jobs actually have the ability to weigh even more complex strategies or are they just a dumb queue which I should have used SQS for instead?

**Comment by Miserlou** [comment] 2018-09-21 20:53
Support for constraints is also explicitly mentioned in the [job dispatch documentation](https://www.nomadproject.io/docs/commands/job/dispatch.html#usage).

**Comment by insanejudge** [comment] 2018-09-23 00:47
> If that's the case, that should be warned against in the documentation, and it should warn that these constraints won't be respected for parameterized jobs when the job is registered.

Constraints are respected, we use dispatch jobs with multiple task groups and node meta constraints for scheduling _task groups within the job_ and it works fine. As the documentation for `distinct_property` and `distinct_host` states plainly, they are for scheduling groups and allocations within jobs. 

You are dispatching distinct jobs and expecting per-job constraints to somehow apply between them despite what is documented.

**Comment by Miserlou** [comment] 2018-09-28 15:50
They're not the distinct jobs though, they're the exact same job with the exact same specification and name, just with different parameters. The use case I'm talking about is described in the documentation and the blog post. It's an _absolutely critical requirement_ of a queue-replacing job scheduler.

There are so many ways that this could be solved, even with the current implementation - for instance, expose `Job.ParentID` as a constraint, etc. 

This, combined with Nomad's inability to any kind of priority-based capacity planning (ex. 10-priority-1GB jobs will always block 100-priority-10GB jobs) mean that Nomad job dispatching isn't as as useful as advertised for queue-replacement scenarios. Implementing this ability would change that, as we could put a ceiling on jobs per node and ensure capacity for larger, higher-priority jobs that are being blocked.

STILL waiting for an opinion from hashicorp staff on this, @dadgar.

**Comment by dadgar** [comment] 2018-10-01 17:14
@Miserlou @insanejudge's answer is correct. The dispatched job is a separate instance of the job and the distinct host constraint applies only to the scope of that job and not any other dispatched instance. I am sorry if this was confusing to you and we would be happy to take a PR for documentation to clarify that each dispatch job is treated separately. However this is not a bug in our perspective and I will be closing this.

**Closed by dadgar** 2018-10-01 17:14 UTC
Labels: needs_investigation, scheduling

**Comment by Miserlou** [comment] 2018-10-01 17:45
So it's impossible to apply constraints to dispatches of the same job spec? And there's also no way to do any kind of forward capacity planning to ensure placement for higher priority jobs? And there's no plan to implement these features?

I think the blog post and documentation should be updated to reflect these major limitations. I honestly feel deceived.
