### ISSUE TITLE
Bug in periodic job summaries: pending never decreases

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#9875] opened 2021-01-22 19:17 UTC
Periodic job summaries in status pending fail to decrease.

## To Reproduce

Steps to reproduce the behavior.

> Run attached periodic job.

## Expected behavior

Decremented pending status count.

## Environment:

Product Version: 1.0.0

## Repro

```hcl
job "j5" {
    datacenters = [ "dc1" ]
    type = "batch"

    periodic {
        cron = "*/1 * * * * *"
        prohibit_overlap = false
        time_zone = "UTC"
    }

    group "g5" {
        network {
          port "p5" {
            to = 6379
          }
        }
        task "t5" {
            driver = "docker"

            config {
                image = "redis:3.2"
                ports = ["p5"]
            }

        }
    }
}
```

**Comment by drewbailey** [comment] 2021-01-22 19:41
@schmichael mind reproducing on `main`, should be covered by https://github.com/hashicorp/nomad/pull/9768

**Comment by drewbailey** [comment] 2021-01-22 19:51
Looks like this is actually still an issue, we will at least have a failing e2e test for with #9768

**Comment by drewbailey** [comment] 2021-01-25 15:35
fixed in #9884

**Closed by drewbailey** 2021-01-25 15:35 UTC
Labels: stage/needs-investigation, theme/core, theme/scheduling, type/bug
