### ISSUE TITLE
add namesapce to telemetry for allocation

### ISSUE THREAD

**Issue by tantra35** [hashicorp/nomad#6361] opened 2019-09-21 00:32 UTC
In new versions of nomad really id of job consist from two parts namspace and Job name, but in telemetry this fact doesn't respected. And metric name looks like this:

```
nomad.client.allocs.<Job>.<TaskGroup>.<AllocID>....
```

but it must looks like this

```
nomad.client.allocs.<Namespace>.<Job>.<TaskGroup>.<AllocID>....
```

**Comment by notnoop** [comment] 2019-10-29 15:22
Thanks @tantra35; that's a good point.  I believe this was resolved in by https://github.com/hashicorp/nomad/pull/5847 and was release in 0.9.4.

We opted to use a label instead of a metric name component because of backward compatibility concerns.

Closing this ticket, but please reopen and let us know more details if you see any unexpected behavior.

**Closed by notnoop** 2019-10-29 15:22 UTC
Labels: enhancement, metrics
