### ISSUE TITLE
Service check not registered

### ISSUE THREAD

**Issue by oribaldi** [hashicorp/nomad#2229] opened 2017-01-23 17:04 UTC
Hello guys,

I am trying to write a health check for a service, which I register with a Nomad job. The service is registered in Consul, but the corresponding health check is not. The check is simply a curl to some URL. I don't use the HTTP check, because I am not trying to query the given service, but something else. 

The health check looks something like this:

check {
          name = "my-health-check"
          type = "script"
          command = "curl"
          args = ["-I", "https://example.com"]
          interval = "30s"
}

I also tried command = "/usr/bin/curl", but it does not work. I am sure there is something wrong in the commands or the args, but I haven't found any solution. I hope you guys can help me with this.

This is what I found on the logs:
driver.raw_exec: error registering services with consul for task: "my-task": 1 error(s) occurred:#012#012* couldn't create check for my-health-check

Is this the expected behavior?

### Nomad and Consul versions
Nomad: 0.5.0
Consul: 0.7.1

### Operating system and Environment details
Ubuntu 14.04.2 LTS

**Comment by oribaldi** [comment] 2017-01-24 10:26
Forgot to mention that the driver is "raw_exec".

**Comment by shantanugadgil** [comment] 2017-01-31 10:37
I too have been using a raw_exec and trying a service block with it.
What I have seen is that while the task is running, there is indeed a service registered, but when the raw_exec command exits, nomad deregisters the service :(

Could you post a more complete example of the job? Maybe that could help.

Regards,
Shantanu

**Comment by dadgar** [comment] 2017-01-31 17:05
@oribaldi Nomad registers service checks as TTL checks with Consul. The Nomad agent then runs the check itself and will inform Consul of the results.

The reason it works this way is that the script may be in a location that Consul does not have access to, for example a docker container or chroot. As such this is expected behavior.

I am going to close this issue but if you believe that the check itself is not working (reporting healthy when the script returns non-zero exit codes or vice versa we can reopen).

**Closed by dadgar** 2017-01-31 17:05 UTC

**Comment by dadgar** [comment] 2017-01-31 17:07
@shantanugadgil This is expected behavior as well. If Nomad did not clean up, there would be many inaccurate services/checks in Consul and routing via Consul would be broken.

**Comment by oribaldi** [comment] 2017-02-03 09:24
@dadgar Thanks for the explanation!
