### ISSUE TITLE
Indicate canary allocations with tags in Consul

### ISSUE THREAD

**Issue by flyhard** [hashicorp/nomad#3340] opened 2017-10-09 08:59 UTC
The new deployment / update features in Nomad seem to me a little incomplete as it does not allow the service discovery to detect which instances are the canary.

I would suggest that we add a new option to the update stanza to define a consul tag for canary allocations or add a canary tag option the the service stanza

This would allow for writing load balancer configs that could target the new or old allocations only.

We normally make the canary only available for internal testing and only when promoting it becomes available through the LB.

I would suggest that the tag be removed again as soon as the promote command has been issued. Another improvement would be if we could then tag the old instances so we can immediately remove them from LB while keeping them running long enough to gather all the logs before shutdown.

I believe making the Service discovery aware of which allocations are of the right version is important.

**Comment by jrasell** [comment] 2017-10-09 12:33
I believe this relates to #2920

**Comment by dadgar** [comment] 2017-10-09 17:17
Hey @flyhard I am closing as a duplicate of #2920! Thanks!

**Closed by dadgar** 2017-10-09 17:17 UTC
