### ISSUE TITLE
Cleaner output on not-applicable values for `node-status`

### ISSUE THREAD

**Issue by cleung2010** [hashicorp/nomad#616] opened 2015-12-21 22:26 UTC
`nomad nodes-status [node]` should return a better formatted output if values are not found or not-applicable.

For example, if the AWS instance running the client does not contain a public IP it currently returns:
```bash
$ nomad node-status [node]
ID         = 27b007ac-6271-f166-f2c1-9e16be923e6e
Name       = 0baca28c8653
...
Attributes = 
...
platform.aws.public-hostname:<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>, platform.aws.public-ipv4:<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>
...
```

The output could be much cleaner if it showed `platform.aws.public-hostname:n/a` and `platform.aws.public-ipv4:n/a` instead, and same for any applicable fields that can't fetch a valid value.

**Comment by dadgar** [comment] 2015-12-21 22:27
duplicate of #611

**Closed by dadgar** 2015-12-21 22:27 UTC

**Comment by cleung2010** [comment] 2015-12-21 22:28
@dadgar damn you're quick. I thought something was wrong with me/my browser when it didn't show under open issues.
