### ISSUE TITLE
client.rpc: error performing RPC to server: error="rpc error: failed to get conn: rpc error: lead thread didn't get connection" rpc=Node.GetClientAllocs server=<redacted>:4647

### ISSUE THREAD

**Issue by bfqrst** [hashicorp/nomad#16658] opened 2023-03-27 14:54 UTC
### Nomad version
Nomad v1.5.2
BuildDate 2023-03-21T22:54:38Z
Revision 9a2fdb5f53dce81edf2802f0b64962e07596fd03

### Operating system and Environment details
Linux prod-consul-yv5 5.15.0-1031-aws #35-Ubuntu SMP Fri Feb 10 02:12:38 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"

### Issue
After cycling the AWS ASGs for a rolling update from 1.5.1 to 1.5.2 the last Consul server (which is also a Nomad client), failed to show up in the Nomad clients pane and emits several RPC errors. It registers just fine in Consul as a Consul server though! What I initially thought to be a random glitch, happened on three distinct clusters. A reboot of said finicky last node fixes the situation. It comes back up and registers itself as a Nomad client.
### Reproduction steps
Not sure if reproducable or a bug per se but it's at least an observation I thought I let you guys know...

Update procedure:

- Packer builds an Consul image and Nomad image with updated Nomad binary
- Terraforms triggers to distinct AWS ASGs (Consul ASG / Nomad ASG) to begin EC2 instance cycling with three minutes of health_check_grace_period. So one Consul server and one Nomad server go in parallel...
- first pair is cycled -> all good
- second pair is cycled -> all good
- third pair is cycled -> Consul registrations are OK, last Consul server fails to register itself as a Nomad client.
#### Expected Result
The last Consul server (which is also a Nomad client) should register itself with the Nomad server and appear in the Nomad clients pane.
#### Actual Result
Two out of three cluster member register fine, the third emits RPC errors.
### Job file (if appropriate)
N/A

### Nomad Client logs (if appropriate)
Client log sent to nomad-oss-debug@hashicorp.com

**Comment by tgross** [comment] 2023-03-27 21:00
@bfqrst the logs you posted are right-truncated. The bit that's truncated will include the RPC method (one of `Node.Register` or `Node.GetClientAllocs`) and the server address, which will match the dial address. But they all appear to be of the same sort of thing:

> error performing RPC to server: error="rpc error: failed to get conn: dial tcp 10.x.y.z:4647: connect: no route to host"...

So the Nomad client is trying to reach its server at a particular address and can't. The first thing for you to check is whether that address is at all valid. But what's interesting to me is that you say it repeated for the last client that was hosting a Consul server. Are you using the Consul servers you're running _on_ the cluster to discover the servers? If so, I suspect the bad address is the address of the just-terminated Nomad server from stale Consul read.

In my experience, when you do a rolling termination like this with ASGs, the Raft leadership will _tend to_ remain on the older set of servers because the newer servers are still doing their snapshot restore when the elections happen. So when the last pair gets terminated, there's no leader for a bit. (You usually want to add a server before removing an old one. See the [Upgrade Process](https://developer.hashicorp.com/nomad/docs/upgrade#upgrade-process) docs.)

So what's happening here is that there's a brief moment without leader at the exact moment when you need it most -- when you've got a new client coming online with the Consul server you need to join the cluster. The client makes a discovery query to Consul, which it can serve because we've passed `AllowStale: true`, and then you end up with the old server.

There are two things you can do to avoid this brittleness:
* Add a server before removing an old one and don't terminate both a client and server at the same time.
* Don't use Consul discovery for Nomad servers and clients if you're going to have the Consul servers on the clients. Instead, use something like [EC2 autojoin](https://developer.hashicorp.com/nomad/docs/configuration/server_join#amazon-ec2).

**Comment by bfqrst** [comment] 2023-03-28 15:08
Thanks for the detailed answer @tgross! I uploaded a fresh set of logs to nomad-oss-debug@hashicorp.com and updated my Nomad config to use Cloud Auto-join. The Consul servers are using it already. I initially figured that Nomad agents would piggyback on the Consul discovery but hadn't accounted for race conditions...

So just to be safe, after implementing Cloud Auto-join one would set `client_auto_join` and `server_auto_join` to `false`, right?

**Comment by tgross** [comment] 2023-03-28 15:59
> Thanks for the detailed answer @tgross! I uploaded a fresh set of logs to [nomad-oss-debug@hashicorp.com](mailto:nomad-oss-debug@hashicorp.com) and updated my Nomad config to use Cloud Auto-join. The Consul servers are using it already. I initially figured that Nomad agents would piggyback on the Consul discovery but hadn't accounted for race conditions...

Great, it should be safe to close this one out. If you run into any more trouble, feel free to let us know.

> So just to be safe, after implementing Cloud Auto-join one would set client_auto_join and server_auto_join to false, right?

Right!

**Closed by tgross** 2023-03-28 15:59 UTC
Labels: type/bug, stage/waiting-reply, theme/discovery, theme/config

**Comment by bfqrst** [comment] 2023-03-29 12:12
@tgross, after spot checking the logs in three different stages, I have two observations on Nomad **client** nodes (which happen to be Consul servers in this instance):

1. Although Cloud Auto-join is in place the log informs me that it fingerprinted the Consul agent (but I suppose it is not used?!)
    - this differs from Nomad server output which only mentions Cloud Auto-join with nothing else Consul agent-wise
 2. Clients log the following line since transitioning from `1.5.0` to `1.5.1 `(still present in `1.5.2`)
    - `[ERROR] agent.plugin_loader.docker: failed to list pause containers: plugin_dir=/opt/hsy/nomad/plugins error=<nil>`

Thanks!

**Comment by tgross** [comment] 2023-03-29 12:52
> 1. Although Cloud Auto-join is in place the log informs me that it fingerprinted the Consul agent (but I suppose it is not used?!)

Yeah, that's expected. The client still fingerprints the local agent so that it can tell the server whether it can support tasks that need Consul for features like [Connect](https://developer.hashicorp.com/nomad/docs/job-specification/connect). That way we don't place allocations that need Consul on clients that don't have it.

> Clients log the following line ...

Hm, that's coming from [`driver.go#L770`](https://github.com/hashicorp/nomad/blob/v1.5.1/drivers/docker/driver.go#L770) which was introduced in 1.5.1. But I see a bug in the log message here that we're returning `err` instead of `listErr`, so we can't see what the problem is and you get `error=<nil>` in your log. Do you have Docker on these clients? If so, is there a chance that Docker isn't up yet when the client starts?

**Comment by bfqrst** [comment] 2023-03-29 14:13
> Do you have Docker on these clients? If so, is there a chance that Docker isn't up yet when the client starts?

Jepp, Docker is on those clients and I'm darn certain Docker is a go at that point. Fun fact, I've seen these lines skimming through other issues on the Nomad GH... In my case it's on every Nomad client ever since (Consul server or otherwise).
