### ISSUE TITLE
question/request: passing shell environment data into jobs

### ISSUE THREAD

**Issue by OferE** [hashicorp/nomad#2113] opened 2016-12-15 12:06 UTC
I need to pass environment variable from the shell that submits the job into a job.

The use case is as follows:
I have some dynamic data that i define in realtime (dir names, passwords etc) which i need to pass to the tasks in the jobs in a dynamic manner (i can't change the job defintion every time i run a job).

Currently I keep those in environment variables in the machine that is actually running the job.
Would be nice if there is a way to pass those variables to nomad without changing my many definition files..

clarification - something that is similar to env of docker-compose where if u define a variable without an assignment it takes it from the shell that runs the compose.

Edit - an alternative way of doing this is to provide an env file inside the nomad run command,

Edit2 - this is a big pain for people that comes from docker swarm and based some infra on it.

**Comment by OferE** [comment] 2016-12-21 19:47
I worked around this by passing the jobfile myself and generating a new jobfile with replaced environment variables. i write the new job into a file, then run it and then delete it.
This is ugly.
I'm hoping this can be supported in an official way.

**Comment by jippi** [comment] 2016-12-22 07:22
Could something like https://github.com/FRosner/cluster-broccoli work?

**Comment by dadgar** [comment] 2017-03-10 00:55
Duplicate of https://github.com/hashicorp/nomad/issues/1185

**Closed by dadgar** 2017-03-10 00:55 UTC
Labels: cli, duplicate, enhancement
