### ISSUE TITLE
Consul config merging regression

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#22214] opened 2024-05-22 19:48 UTC
While working on another issue, I noticed that my Consul configuration files weren't being merged as expected. My server had the following two files:

base.hcl

```hcl
consul {
  token                 = "<redacted>"
  allow_unauthenticated = true
}
```

server.hcl

```hcl
consul {
  service_identity {
    aud = ["consul.io"]
    ttl = "1h"
  }

  task_identity {
    aud = ["consul.io"]
    ttl = "1h"
  }
}
```

This resulted in the following agent configuration:

```
$ nomad operator api "/v1/agent/self" | jq '.config.Consuls'
[
  {
    "Addr": "127.0.0.1:8500",
    "AllowUnauthenticated": true,
    "Auth": "",
    "AutoAdvertise": true,
    "CAFile": "",
    "CertFile": "",
    "ChecksUseAdvertise": false,
    "ClientAutoJoin": true,
    "ClientFailuresBeforeCritical": 0,
    "ClientFailuresBeforeWarning": 0,
    "ClientHTTPCheckName": "Nomad Client HTTP Check",
    "ClientServiceName": "nomad-client",
    "EnableSSL": false,
    "GRPCAddr": "",
    "GRPCCAFile": "",
    "KeyFile": "",
    "Name": "default",
    "Namespace": "",
    "ServerAutoJoin": true,
    "ServerFailuresBeforeCritical": 0,
    "ServerFailuresBeforeWarning": 0,
    "ServerHTTPCheckName": "Nomad Server HTTP Check",
    "ServerRPCCheckName": "Nomad Server RPC Check",
    "ServerSerfCheckName": "Nomad Server Serf Check",
    "ServerServiceName": "nomad",
    "ServiceIdentity": null,
    "ServiceIdentityAuthMethod": "nomad-workloads",
    "ShareSSL": null,
    "Tags": null,
    "TaskIdentity": null,
    "TaskIdentityAuthMethod": "nomad-workloads",
    "Timeout": 5000000000,
    "Token": "<redacted>",
    "VerifySSL": true
  }
]
```

With the following combined agent config:

```hcl
consul {
  token                 = "<redacted>"
  allow_unauthenticated = true

  service_identity {
    aud = ["consul.io"]
    ttl = "1h"
  }

  task_identity {
    aud = ["consul.io"]
    ttl = "1h"
  }
}
```

I get the expected agent config:

```
$ nomad operator api "/v1/agent/self" | jq '.config.Consuls'
[
  {
    "Addr": "127.0.0.1:8500",
    "AllowUnauthenticated": true,
    "Auth": "",
    "AutoAdvertise": true,
    "CAFile": "",
    "CertFile": "",
    "ChecksUseAdvertise": false,
    "ClientAutoJoin": true,
    "ClientFailuresBeforeCritical": 0,
    "ClientFailuresBeforeWarning": 0,
    "ClientHTTPCheckName": "Nomad Client HTTP Check",
    "ClientServiceName": "nomad-client",
    "EnableSSL": false,
    "GRPCAddr": "",
    "GRPCCAFile": "",
    "KeyFile": "",
    "Name": "default",
    "Namespace": "",
    "ServerAutoJoin": true,
    "ServerFailuresBeforeCritical": 0,
    "ServerFailuresBeforeWarning": 0,
    "ServerHTTPCheckName": "Nomad Server HTTP Check",
    "ServerRPCCheckName": "Nomad Server RPC Check",
    "ServerSerfCheckName": "Nomad Server Serf Check",
    "ServerServiceName": "nomad",
    "ServiceIdentity": {
      "Audience": [
        "consul.io"
      ],
      "Env": null,
      "File": null,
      "TTL": 3600000000000
    },
    "ServiceIdentityAuthMethod": "nomad-workloads",
    "ShareSSL": null,
    "Tags": null,
    "TaskIdentity": {
      "Audience": [
        "consul.io"
      ],
      "Env": null,
      "File": null,
      "TTL": 3600000000000
    },
    "TaskIdentityAuthMethod": "nomad-workloads",
    "Timeout": 5000000000,
    "Token": "<redacted>",
    "VerifySSL": true
  }
]
```

**Comment by pkazmierczak** [comment] 2024-07-03 12:01
@tgross, I cannot reproduce

using your `base.hcl` and `server.hcl`:
```
$ ./bin/nomad agent -dev -log-level=ERROR -config=base.hcl -config=server.hcl
```
gives me:
```
$ nomad operator api "/v1/agent/self" | jq '.config.Consuls'
[
  {
    "Addr": "127.0.0.1:8500",
    "AllowUnauthenticated": true,
    "Auth": "",
    "AutoAdvertise": true,
    "CAFile": "",
    "CertFile": "",
    "ChecksUseAdvertise": false,
    "ClientAutoJoin": true,
    "ClientFailuresBeforeCritical": 0,
    "ClientFailuresBeforeWarning": 0,
    "ClientHTTPCheckName": "Nomad Client HTTP Check",
    "ClientServiceName": "nomad-client",
    "EnableSSL": false,
    "GRPCAddr": "",
    "GRPCCAFile": "",
    "KeyFile": "",
    "Name": "default",
    "Namespace": "",
    "ServerAutoJoin": true,
    "ServerFailuresBeforeCritical": 0,
    "ServerFailuresBeforeWarning": 0,
    "ServerHTTPCheckName": "Nomad Server HTTP Check",
    "ServerRPCCheckName": "Nomad Server RPC Check",
    "ServerSerfCheckName": "Nomad Server Serf Check",
    "ServerServiceName": "nomad",
    "ServiceIdentity": {
      "Audience": [
        "consul.io"
      ],
      "Env": null,
      "File": null,
      "TTL": 3600000000000
    },
    "ServiceIdentityAuthMethod": "nomad-workloads",
    "ShareSSL": null,
    "Tags": null,
    "TaskIdentity": {
      "Audience": [
        "consul.io"
      ],
      "Env": null,
      "File": null,
      "TTL": 3600000000000
    },
    "TaskIdentityAuthMethod": "nomad-workloads",
    "Timeout": 5000000000,
    "Token": "<redacted>",
    "VerifySSL": true
  }
]
$ nomad version
Nomad v1.8.2-dev
BuildDate 2024-07-03T09:28:49Z
Revision 3d2e1d9443a87309317acae66f34b8140b574fd2
```

**Comment by pkazmierczak** [comment] 2024-07-03 12:02
unit testing returns expected values as well: https://github.com/hashicorp/nomad/pull/23495/files

**Comment by tgross** [comment] 2024-07-03 13:30
Weird. I'm willing to accept that this was operator error here for sure. :grin: Let's ship your PR with the tests anyways, just to have ongoing assurance... unless there are tests that cover this already?

**Comment by tgross** [comment] 2024-07-03 13:55
I've checked this in my developement cluster and verified it works as expected. Not sure what I was doing wrong when I originally reported this... maybe my `-config` flag was just wrong?

**Comment by pkazmierczak** [comment] 2024-07-03 13:58
ok. I'll close this then. we can still merge https://github.com/hashicorp/nomad/pull/23495 to have an extra test.

**Closed by pkazmierczak** 2024-07-03 13:58 UTC
Labels: type/bug, theme/config, theme/consul, hcc/jira
