### ISSUE TITLE
Problem with Docker volume: Duplicate mount point

### ISSUE THREAD

**Issue by maxio89** [hashicorp/nomad#5617] opened 2019-04-25 21:31 UTC
### Nomad version
nomad version
Nomad v0.8.7 (21a2d93eecf018ad2209a5eab6aae6c359267933+CHANGES)

### Operating system and Environment details
Ubuntu 16.04

### Issue
I have a docker image with some volume declared, e.g.: VOLUME "/secrets", so I need to have a way to pass to docker info about host path. In Marathon it works somehow, but here when I'm trying something like this:
`"volumes": [
                "/usr/local/secrets:/secrets"
              ]`
or
`"mounts": [
                {
                  "type": "bind",
                  "source": "/usr/local/secrets",
                  "": "/secrets",
                  "readonly": true,
                  "bind_options": {
                    "propagation": "rprivate"
                  }
                }
              ]`
I've got an error:
`Failed to create container: API error (400): {"message":"Duplicate mount point: /secrets"}
`

**Comment by MorphBonehunter** [comment] 2019-04-26 14:15
Hey @maxio89,
nomad maintains 3 task directories (https://www.nomadproject.io/docs/runtime/environment.html#task-directories):
* alloc/
* local/
* secrets/

In case of the docker driver the `secrets/` dir is mounted into the container to `/secrets` so if you specify your own `/secrets` mount this is indeed duplicate.

**Comment by maxio89** [comment] 2019-04-26 14:23
It's not the case I think. I believe there would be the same problem if I declare volume like this in my Dockerfile:
`VOLUME ["/data"]`

and then I would try to add something like this in my job configuration:

`"volumes": [ "/usr/local/data:/data" ]`

**Comment by MorphBonehunter** [comment] 2019-04-26 14:32
Maybe i was unclear about this, it's nothing in the docker file, nomad maintains his own `/secrets` mount in the running container.
If you try to specify you own `/secrets` then you have 2 mounts which try to use the same path
maybe it's better to show an example of one of my jobs:
```
docker inspect grafana-task-ceb2e4dd-934a-a8bd-5682-d8f9b0bfbda1
...
            {
                "Type": "bind",
                "Source": "/var/lib/nomad/alloc/ceb2e4dd-934a-a8bd-5682-d8f9b0bfbda1/grafana-task/secrets",
                "Destination": "/secrets",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
...
```
This mount is maintained by nomad, if you try your own `"volumes": [ "/usr/local/secrets:/secrets" ]` mount with the same destination this is duplicate.

**Comment by preetapan** [comment] 2019-04-29 15:12
@maxio89 as @MorphBonehunter mentions above, `/secrets` is internal to Nomad ( like a reserved mount, so you can't use the same in your dockerfile. Closing this, since its not a bug

**Closed by preetapan** 2019-04-29 15:12 UTC
