### ISSUE TITLE
bug: missing complete AllocationUpdated events from Nomad event stream

### ISSUE THREAD

**Issue by Kamilcuk** [hashicorp/nomad#19834] opened 2024-01-27 22:22 UTC
### Nomad version
Nomad 1.7.3

### Operating system and Environment details
Archlinux Newest

### Issue
AllocationUpdated with ClientStatus=complete are no longer generated on Nomad 1.7.3.

The event is generated in Nomad 1.7.2, it is a change.

### Reproduction steps

Download Nomad and in one terminal run `nomad agent -dev`.

In a second terminal, observe the Nomad event stream Allocation topic with:

```
stdbuf -oL nomad operator api /v1/event/stream | grep --line-buffered -xFv '{}' | stdbuf -oL jq -c '.Events.[] | select(.Topic == "Allocation") | [.Topic, .Type, .Payload.Allocation.ID, .Payload.Allocation.ClientStatus]'
```

In a third terminal execute a job and then purge it.

```
nomad job run -detach ./missingcomplete.nomad.hcl && sleep 2 && nomad job stop -purge missingcomplete && nomad job status missingcomplete
```

The job can be anything.

```
# missingcomplete.nomad.hcl
job "missingcomplete" {
  group "g1" {
    reschedule { attempts = 0 }
    restart { attempts = 0 }
    task "t1" {
      driver = "docker"
      config {
        image = "busybox:stable"
        args = ["sleep", "infinity"]
      }
    }
  }
}
```

#### Expected Result
The expected result on the second terminal can be obtained by running nomad version 1.7.2 and looks like the following:

```
$ stdbuf -oL nomad operator api /v1/event/stream | grep --line-buffered -xFv '{}' | stdbuf -oL jq -c '.Events.[] | select(.Topic == "Allocation") | [.Topic, .Type, .Payload.Allocation.ID, .Payload.Allocation.ClientStatus]'
["Allocation","PlanResult","1ef87a91-f640-bb32-7a37-d0d82c478c1a","pending"]
["Allocation","AllocationUpdated","1ef87a91-f640-bb32-7a37-d0d82c478c1a","running"]
["Allocation","PlanResult","1ef87a91-f640-bb32-7a37-d0d82c478c1a","running"]
["Allocation","AllocationUpdated","1ef87a91-f640-bb32-7a37-d0d82c478c1a","running"]
["Allocation","AllocationUpdated","1ef87a91-f640-bb32-7a37-d0d82c478c1a","complete"]
```

As you can see, there is an `AllocationUpdated` event stating that the execution of `1ef87a91-f640-bb32-7a37-d0d82c478c1a` completed.

The third terminal looks like the following:

```
$ nomad job run -detach ./missingcomplete.nomad.hcl && sleep 2 && nomad job stop -purge missingcomplete && nomad job status missingcomplete
Job registration successful
Evaluation ID: eae401ac-29bf-554d-fdc4-754e67f8c5c6
==> 2024-01-27T23:17:04+01:00: Monitoring evaluation "e9416058"
    2024-01-27T23:17:04+01:00: Evaluation triggered by job "missingcomplete"
    2024-01-27T23:17:05+01:00: Evaluation within deployment: "d544f673"
    2024-01-27T23:17:05+01:00: Evaluation status changed: "pending" -> "complete"
==> 2024-01-27T23:17:05+01:00: Evaluation "e9416058" finished with status "complete"
==> 2024-01-27T23:17:05+01:00: Monitoring deployment "d544f673"
  ! Deployment "d544f673" cancelled
    
    2024-01-27T23:17:05+01:00
    ID          = d544f673
    Job ID      = missingcomplete
    Job Version = 0
    Status      = cancelled
    Description = Cancelled because job is stopped
    
    Deployed
    Task Group  Desired  Placed  Healthy  Unhealthy  Progress Deadline
    g1          1        1       0        0          2024-01-27T23:27:02+01:00
```

#### Actual Result

There is no "complete" event generated, no matter how long you want. Thus, it is impossible to wait for allocation completion using Nomad event stream.

```
$ stdbuf -oL nomad operator api /v1/event/stream | grep --line-buffered -xFv '{}' | stdbuf -oL jq -c '.Events.[] | select(.Topic == "Allocation") | [.Topic, .Type, .Payload.Allocation.ID, .Payload.Allocation.ClientStatus]'
["Allocation","PlanResult","3cb1ae74-f1bf-0b71-80f0-f89526bf6341","pending"]
["Allocation","AllocationUpdated","3cb1ae74-f1bf-0b71-80f0-f89526bf6341","running"]
```

No matter how long you wait there is never a "completed" event.

Additionally, on the third terminal the output is also different:

```
$ nomad job run -detach ./missingcomplete.nomad.hcl && sleep 2 && nomad job stop -purge missingcomplete && nomad job status missingcomplete
Job registration successful
Evaluation ID: 5b45c120-8357-714e-7d48-861e2f96006b
==> 2024-01-27T23:21:02+01:00: Monitoring evaluation "24d45dfb"
    2024-01-27T23:21:02+01:00: Evaluation triggered by job "missingcomplete"
    2024-01-27T23:21:02+01:00: Evaluation status changed: "pending" -> "complete"
==> 2024-01-27T23:21:02+01:00: Evaluation "24d45dfb" finished with status "complete"
No job(s) with prefix or ID "missingcomplete" found
```

It is relatively simple to reproduce.

Thanks!

**Comment by lgfa29** [comment] 2024-02-06 20:18
Hi @Kamilcuk 👋 

This is a consequence of previous versions of `nomad job stop -purge` leaving behind allocations, which caused several other issues. This was fixed in https://github.com/hashicorp/nomad/pull/19609 and release in Nomad 1.7.3.

When using `-purge` you're signaling Nomad to immediately delete the job and its related resources, instead of it being handled by the garbage collector.

Without `-purge` you will have the expected result.

```
$ stdbuf -oL nomad operator api /v1/event/stream | grep --line-buffered -xFv '{}' | stdbuf -oL jq -c '.Events.[] | select(.Topic == "Allocation") | [.Topic, .Type, .Payload.Allocation.ID, .Payload.Allocation.ClientStatus]'
["Allocation","PlanResult","4f8ed2bc-9c4c-078b-deb0-745662144287","pending"]
["Allocation","AllocationUpdated","4f8ed2bc-9c4c-078b-deb0-745662144287","running"]
["Allocation","PlanResult","4f8ed2bc-9c4c-078b-deb0-745662144287","running"]
["Allocation","AllocationUpdated","4f8ed2bc-9c4c-078b-deb0-745662144287","complete"]
```

**Comment by Kamilcuk** [comment] 2024-02-06 20:24
Hi. Thank you for the background. `Without -purge you will have the expected result`. Yes, I know that. Bottom line, is this the expected behavior? I would expect I would be able to get the allocation exit code irrelevant if stopping with purge or not.

If the job is intended to be manually cleaned up, to get all allocation exit statuses from nomad event stream, I _have to_ first stop the job, wait for the termination of all allocations, and _then_ purge the job after all allocations have terminated?

**Comment by lgfa29** [comment] 2024-02-07 21:04
> Bottom line, is this the expected behavior? I would expect I would be able to get the allocation exit code irrelevant if stopping with purge or not.

It's a bit strange, but yes, that's the expected behaviour. The `-purge` flag causes jobs and allocs to be deleted immediately, so, technically, there's not update, the data is removed from state and servers stop tracking them.

The allocations do eventually get stopped by clients once they refresh their allocation list from servers and notice that an allocation is gone. But this happens outside of the servers, so there's no event to emit.

While looking at this issue I did notice that `-purge` caused even the `JobDeregister` event to not be emitted, so I opened https://github.com/hashicorp/nomad/pull/19903 to fix that. I'm not sure if this helps you.

> When I am running a job with the intention to manually clean up after it and I want to get all allocation exit statuses from Nomad event stream, then: I have to first stop the job, wait for the termination of all allocations, and then purge the job after all allocations have terminated?

That sounds about right. That way you ensure servers can keep tracking the allocation to completion.

**Comment by Kamilcuk** [comment] 2024-02-07 21:20
> I'm not sure if this helps you.

How can I detect if a job was purged or stopped, only by observing the event stream? Both will generate `Job.JobDeregister` and `Evaluation.JobDeregister` followed by `evaluation.EvaluationUpdated`.

> so I opened https://github.com/hashicorp/nomad/pull/19903 to fix that

Could I get another `job.JobPurged` event so that I know definitely that a job is purged, not stopped?

Or could there be evaluation with `TriggeredBy=job-purged`?

> That sounds about right. That way you ensure servers can keep tracking the allocation to completion.

Great, thank you.

---

Example: On nomad1.7.3 the `missingcomplete` job above was started, and then stopped, so now the `missingcomplete` job is fully stopped, nothing is happening. I start listening on `events/stream` with all topics related to the job `Job:missingcomplete Deployment:missingcomplete Allocation:missingcomplete Evaluation:missingcomplete`.

`nomad job stop missingcomplete` generates the following events:

```
index=32 Job.JobDeregistered ID=missin Version=5 JobModifyIndex=32 ModifyIndex=32 Status=dead
index=32 Evaluation.JobDeregistered ID=dc5087 JobID=missingcomplete JobModifyIndex=32 ModifyIndex=32 Status=pending TriggeredBy=job-deregister
index=32 Job.JobDeregistered ID=missin Version=5 JobModifyIndex=32 ModifyIndex=32 Status=pending
index=33 Evaluation.EvaluationUpdated ID=dc5087 JobID=missingcomplete JobModifyIndex=32 ModifyIndex=33 Status=complete TriggeredBy=job-deregister
index=33 Job.EvaluationUpdated ID=missin Version=5 JobModifyIndex=32 ModifyIndex=33 Status=dead
```

`nomad job stop -purge missingcomplete` generates only the following events:

```
index=38 Evaluation.JobDeregistered ID=888709 JobID=missingcomplete JobModifyIndex=38 ModifyIndex=38 Status=pending TriggeredBy=job-deregister
index=39 Evaluation.EvaluationUpdated ID=888709 JobID=missingcomplete JobModifyIndex=38 ModifyIndex=39 Status=complete TriggeredBy=job-deregister
```

The "index" is the index as returned in the JSON from the event stream. Two events with the same index=value are received in the same JSON from Nomad.

Effectively, currently, I am checking if `Job.EvalutionUpdated` event is within the same events array as `Job.EvaluationUpdated` event. If there is `Evaluation.JobDeregistered` event without `Job.EvaluationUpdated` with the same event index, it means that the job was purged. Is this intended behavior? Is there a way to differentiate which evaluation results in job purging, and which in only job stopping?

**Comment by lgfa29** [comment] 2024-02-08 00:10
Internally a event type is mapped to a Raft log message type, and we don't have one for job deletion. I am checking with the team how to best handle this and I will let you know once I get an update.

**Comment by lgfa29** [comment] 2024-02-08 22:34
Hi @Kamilcuk, just another quick follow-up.

>  Is there a way to differentiate which evaluation results in job purging, and which in only job stopping?

Could you expand a little on why this difference is important for your use case?

**Comment by tgross** [comment] 2024-06-24 15:52
Looks like the initial problem has been solved here. Going to close this out.

**Closed by tgross** 2024-06-24 15:52 UTC
Labels: type/bug, theme/cli, stage/not-a-bug
