### ISSUE TITLE
CLI : "nomad job plan" exit codes 1 means Allocations created or destroyed. it's littel strange to shell

### ISSUE THREAD

**Issue by sfs77** [hashicorp/nomad#6867] opened 2019-12-17 08:18 UTC
refer to https://www.nomadproject.io/docs/commands/job/plan.html

> Plan will return one of the following exit codes:
     0: No allocations created or destroyed.
     1: Allocations created or destroyed.
     255: Error determining plan results.

when execute "nomad job plan" and it's result is positive ("Allocations created or destroyed") , but comand exit code is 1, which is customary to understand as abnormal status in shell. 

it's littel confusing and  strange,  I suggest switch exit code 0 and 1 's meaning

**Comment by jippi** [comment] 2019-12-17 08:24
Same, I had hoped it was a documentation bug, [but the code is doing what the docs say](https://github.com/hashicorp/nomad/blob/master/command/job_plan.go#L250-L262)

**Comment by Sea-Flying** [comment] 2019-12-18 11:06
Update:
 today when I plan a constraint filtered and resources exhausted allocation 
it's result messages is 

> Scheduler dry-run:
>- WARNING: Failed to place all allocations.
  Task Group "group" (failed to place 1 allocation):
    * Class "host80" filtered 1 nodes
    * Constraint "${meta.for} != gateway" filtered 1 nodes
    * Resources exhausted on 3 nodes
    * Class "host90" exhausted on 2 nodes
    * Class "host70" exhausted on 1 nodes
    * Dimension "network: bandwidth exceeded" exhausted on 3 nodes
>Job Modify Index: 28479
>To submit the job with version verification run:
>...

but than check its return code with `echo $?`  and find it is `1`

obviously this plan is unsuccessful,  but if I use it's exit code in shell scripts to control job submission, it is unreliable in procedure

**Comment by tgross** [comment] 2019-12-20 18:53
Hi @Sea-Flying! In that dry-run, were there some allocations successfully planned for place/destroy? The exit code 1 signifies that _some_ allocations were successfully placed/destroyed, not all of them. 

That being said, I think there's definitely some room for improvement here though where we could have more granularity in the exit codes. I'm going to mark this as an enhancement for further discussion.

**Comment by apollo13** [comment] 2021-09-10 08:57
I have a similar issue with that: In-Place updates keep the exit code at zero so I cannot reliably determine whether an update is needed or not :D

**Comment by gboddin** [comment] 2022-06-07 23:15
Returns codes are indeed useless in a CI pipeline.

0 = I'll do nothing
1 = I'll do something
255 = ???

It's funny because the tool is about automation.

What about (at least) :

0 = I'll do something and it'll be all right ( y a know so CI pipeline continues )
1 = I'll do nothing ( y a know so CI pipeline stops )
2 = I don't have enough space to do everything ( y a know because CI pipeline can then scale )
255 = ???

Again, it's funny because the tool is about automation.

Also it's funny because auto-scale is an enterprise feature.

I'll right, I'm done being funny.

**Comment by lgfa29** [comment] 2023-02-03 21:20
Closing this one as duplicate of #6589. I will add a comment there with the suggestions proposed here. Feel free to 👍 and post any additional comments there. 

Thank you so much for all the feedback!

**Closed by lgfa29** 2023-02-03 21:20 UTC
Labels: type/enhancement, theme/cli, stage/needs-discussion
