### ISSUE TITLE
Configurable delay after deregistering consul service, before killing task

### ISSUE THREAD

**Issue by jemc** [hashicorp/nomad#2607] opened 2017-05-02 17:49 UTC
As of #2596, nomad deregisters any consul services associated with a task just before "soft"-killing the task. The task is expected to terminate itself within the configured `kill_timeout` or face a "hard" kill from nomad.

However, some solutions may have other components in a distributed system depending on those consul service deregistrations for making decisions, such as a web load balancer (like [fabio](https://github.com/fabiolb/fabio), [traefik](https://github.com/containous/traefik), or HAProxy + consul-template) that forwards traffic to a pool of currently registered services. Being a distributed system, the changes do not propagate immediately, so the load balancer may end up sending some traffic to containers that have already disappeared (if their soft kill handling is faster than the time it takes the deregistration to propagate to the load balancer).

To facilitate this kind of use case, I want to propose adding a configurable delay between the time the consul services are deregistered and the time that nomad actually initiates the kill sequence for the task. This configurable delay would be zero by default, and thus would not affect existing solutions.

There has already been some discussion of this idea in #2596, but @schmichael has requested that we discuss the idea further in this ticket.

**Comment by schmichael** [comment] 2017-05-04 17:05
Just discovered this is a dupe of #2441 

Closing to focus discussion over there.

**Closed by schmichael** 2017-05-04 17:05 UTC
Labels: client, discovery, enhancement
