### ISSUE TITLE
Quota Limits - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shadowwalker** [hashicorp/nomad#10692] opened 2021-06-03 04:52 UTC
### Nomad version

`Nomad v1.1.0 (2678c3604bc9530014208bc167415e167fd440fc)`

### Operating system and Environment details

MacOS 10.15.7

### Issue

![image](https://user-images.githubusercontent.com/9603375/120588736-8c641700-c3ec-11eb-97fb-932f6394c2b4.png)

**Comment by jrasell** [comment] 2021-06-03 07:21
Hi @shadowwalker and sorry you ran into this. I believe this is a duplicate of #10619 which has been fixed within #10620 but not yet released. If possible, could you try building a Nomad binary from latest `main` and running the command you experienced the panic with?

**Comment by shadowwalker** [comment] 2021-06-07 22:06
@jrasell Thanks, I used build binary as suggested, currently issue is gone.

**Comment by jrasell** [comment] 2021-06-08 10:53
Hi @shadowwalker and I really appreciate you testing this out and getting back to us. I'll go ahead and close this issue. If you have any further problems or questions please feel free to reach out via a new issue.

**Closed by jrasell** 2021-06-08 10:53 UTC
Labels: stage/duplicate, stage/waiting-reply, type/bug
