### ISSUE TITLE
nomad: panic - after enabling prometheus_metrics on all nomad-servers

### ISSUE THREAD

**Issue by TheSpbra1n** [hashicorp/nomad#3516] opened 2017-11-07 12:17 UTC
### Nomad version
Nomad v0.7.0

### Operating system and Environment details
Codename:	xenial
Linux nomad-01  4.9.34-amd64

### Issue
We have 3 nomad-servers n the cluster. After enabling on two servers "prometheus_metrics: true" all works. But if turn on all servers - cluster is broken.  You can see the logs: [https://pastebin.com/p2aqZwpf](https://pastebin.com/p2aqZwpf)

```
Nov 07 14:23:53 nomad-01 nomad[15660]:     2017/11/07 14:23:53 [INFO] raft: Added peer [xxx]:4647, starting replication
Nov 07 14:23:53 nomad-01 nomad[15660]:     2017/11/07 14:23:53 [INFO] raft: Added peer [xxx]:4647, starting replication
Nov 07 14:23:53 nomad-01 nomad[15660]:     2017/11/07 14:23:53.518190 [INFO] nomad: cluster leadership acquired
Nov 07 14:23:53 nomad-01 nomad[15660]: panic: descriptor Desc{fqName: "nomad_raft_replication_appendEntries_rpc_[xxx]:4647
Nov 07 14:23:53 nomad-01 nomad[15660]: goroutine 13034 [running]:
Nov 07 14:23:53 nomad-01 nomad[15660]: github.com/hashicorp/nomad/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc4203a78
Nov 07 14:23:53 nomad-01 nomad[15660]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/prometheus/client_golang/prometheus/registry.go
Nov 07 14:23:53 nomad-01 nomad[15660]: github.com/hashicorp/nomad/vendor/github.com/prometheus/client_golang/prometheus.MustRegister(0xc427f27230, 0x1, 0x1
Nov 07 14:23:53 nomad-01 nomad[15660]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/prometheus/client_golang/prometheus/registry.go
Nov 07 14:23:53 nomad-01 nomad[15660]: github.com/hashicorp/nomad/vendor/github.com/armon/go-metrics/prometheus.(*PrometheusSink).AddSampleWithLabels(0xc42
Nov 07 14:23:53 nomad-01 nomad[15660]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/armon/go-metrics/prometheus/prometheus.go:90 +0
Nov 07 14:23:53 nomad-01 nomad[15660]: github.com/hashicorp/nomad/vendor/github.com/armon/go-metrics.FanoutSink.AddSampleWithLabels(0xc420410020, 0x2, 0x2,
Nov 07 14:23:53 nomad-01 nomad[15660]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/armon/go-metrics/sink.go:73 +0xa2
Nov 07 14:23:53 nomad-01 nomad[15660]: github.com/hashicorp/nomad/vendor/github.com/armon/go-metrics.(*FanoutSink).AddSampleWithLabels(0xc420410040, 0xc422
Nov 07 14:23:53 nomad-01 nomad[15660]:         <autogenerated>:1 +0xaa
Nov 07 14:23:53 nomad-01 nomad[15660]: github.com/hashicorp/nomad/vendor/github.com/armon/go-metrics.(*Metrics).MeasureSinceWithLabels(0xc420092370, 0xc421
Nov 07 14:23:53 nomad-01 nomad[15660]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/armon/go-metrics/metrics.go:129 +0x37f
Nov 07 14:23:53 nomad-01 nomad[15660]: github.com/hashicorp/nomad/vendor/github.com/armon/go-metrics.(*Metrics).MeasureSince(0xc420092370, 0xc421af0230, 0x
Nov 07 14:23:53 nomad-01 nomad[15660]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/armon/go-metrics/metrics.go:106 +0x8f
Nov 07 14:23:53 nomad-01 nomad[15660]: github.com/hashicorp/nomad/vendor/github.com/armon/go-metrics.MeasureSince(0xc421af0230, 0x5, 0x5, 0xbe7883d25ee4520
Nov 07 14:23:53 nomad-01 nomad[15660]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/armon/go-metrics/start.go:120 +0xb8
Nov 07 14:23:53 nomad-01 nomad[15660]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.appendStats(0xc4201b0360, 0x2b, 0xbe7883d25ee45201, 0x3d
Nov 07 14:23:53 nomad-01 nomad[15660]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/replication.go:537 +0xc5
Nov 07 14:23:53 nomad-01 nomad[15660]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).replicateTo(0xc42023e000, 0xc420f360c0, 0x205ebf
Nov 07 14:23:53 nomad-01 nomad[15660]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/replication.go:191 +0x1dd
Nov 07 14:23:53 nomad-01 nomad[15660]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).replicate(0xc42023e000, 0xc420f360c0)
Nov 07 14:23:53 nomad-01 nomad[15660]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/replication.go:132 +0x437
Nov 07 14:23:53 nomad-01 nomad[15660]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).startStopReplication.func1()
Nov 07 14:23:53 nomad-01 nomad[15660]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/raft.go:447 +0x33
Nov 07 14:23:53 nomad-01 nomad[15660]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc42023e000, 0xc421b22da0)
Nov 07 14:23:53 nomad-01 nomad[15660]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/state.go:146 +0x53
Nov 07 14:23:53 nomad-01 nomad[15660]: created by github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*raftState).goFunc
Nov 07 14:23:53 nomad-01 nomad[15660]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/state.go:144 +0x66
Nov 07 14:23:53 nomad-01 systemd[1]: nomad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 07 14:23:53 nomad-01 systemd[1]: nomad.service: Unit entered failed state.
Nov 07 14:23:53 nomad-01 systemd[1]: nomad.service: Failed with result 'exit-code'.
Nov 07 14:25:18 nomad-01 systemd[1]: Stopped Nomad.
```

**Comment by schmichael** [comment] 2017-11-07 22:12
We'll try to get this fixed in 0.7.1; thanks for the report @TheSpbra1n!

**Comment by dadgar** [comment] 2017-11-16 21:58
@TheSpbra1n Could you attach your server configs? Do you have any other reproduction steps? Does it happen to you every time?

I have 3 servers up right now on 0.7.0 exporting to Prometheus and am not having any problems. My config looks like: 

```
# Increase log verbosity
log_level = "DEBUG"

# Setup data dir
name = "server2"
data_dir = "/tmp/server2"

# Enable the server
server {
  enabled = true

  # Self-elect, should be 3 or 5 for production
  bootstrap_expect = 3

  retry_join = ["127.0.0.1:4648"]
}

telemetry {
  publish_allocation_metrics = true
  publish_node_metrics       = true
  prometheus_metrics = true
}
```

**Comment by dadgar** [comment] 2017-11-17 18:49
Also worth noting, the code path that caused the panic has changed in Nomad 0.7.1, so this shouldn't happen again but would be nice to be able to reproduce this. https://github.com/armon/go-metrics/pull/69/files

**Comment by TheSpbra1n** [comment] 2017-11-20 11:22
Hi, config:
```
# cat nomad.conf
{
 "bind_addr": "0.0.0.0",
 "datacenter": "DC1",
 "data_dir": "/var/lib/nomad",
 "name": "nomad-01",
 "disable_update_check": "true",
 "advertise": {
  "serf": "[xxx]:4648",
  "rpc": "[xxx]:4647",
  "http": "[xxx8]:4646"
 },
 "log_level": "DEBUG",
 "telemetry": {
  "publish_allocation_metrics": "true",
  "publish_node_metrics": "true",
  "prometheus_metrics": "true"
 },
 "consul": {
  "address": "localhost:8500"
 },
 "server": {
  "eval_gc_threshold": "48h",
  "encrypt": "xxx",
  "deployment_gc_threshold": "48h",
  "enabled": "true",
  "bootstrap_expect": "2",
  "job_gc_threshold": "48h"
 }
}
```

**Comment by dadgar** [comment] 2017-12-12 18:22
Hey I am going to close this out since 0.7.1 RC1 is out and it has the new code that prevents this! If it happens again in 0.7.1 lets reopen!

**Closed by dadgar** 2017-12-12 18:22 UTC
Labels: bug, crash, metrics

**Comment by TheSpbra1n** [comment] 2017-12-20 12:42
All works! Thanks!
