### ISSUE TITLE
Autoscaler changes count in the middle of a deployment

### ISSUE THREAD

**Issue by jorgemarey** [hashicorp/nomad#14669] opened 2022-09-22 20:24 UTC
### Nomad version
v1.3.4

### Issue

Autoscaler changes count in the middle of a deployment.

### Reproduction steps

1) Run the job
2) Make a change to the job (have a sufficiently large healthy_time so the autoscaler can perform scaling actions)
3) Launch request to make the autoscaler try to scale the job

#### Expected Result

I expected that the job wouldn't scale during the deployment, but in some cases it did (in some other only the count would change but the scaling is performed instantly after the deployment is complete).

Here you can see some snapshots of a deployment. When the first allocation is marked as healthy the job count would change and in this case more allocations were started.

![begin_deployment](https://user-images.githubusercontent.com/6938602/191842901-96cec942-b963-485a-9ccb-62ad23db3609.png)
![deployment_step](https://user-images.githubusercontent.com/6938602/191842936-06e3c51e-ab2c-4391-acb7-b69c84edc091.png)

In the autoscaler logs I expected to see some action, but actually everytime the log showed:
`policy_eval.worker: scaling action skipped: ...`
so I don't understand how this is happening.

I would expect nomad to wait until the deployment completition and maybe some more. In some cases when a scaling policy is using CPU as the check, usually when the application is starting it would consume a lot of CPU so maybe it could be useful to add an option to wait X amount of time after a deployment before making scaling decisions.

### Job file (if appropriate)

Any job file would do the trick. I'm able to reproduce the job with this file:

```
job "demo-api" {
  datacenters = ["dc1"]
  type        = "service"

  update {
    max_parallel      = 1
    auto_revert       = false
    auto_promote      = false
    canary            = 0
    min_healthy_time  = "2m30s"
    healthy_deadline  = "5m"
    progress_deadline = "30m"
  }

  meta {
    image_version = "v0.22.9"
  }

  group "fakeservice" {
    count = 2

    restart {
      interval = "2m"
      attempts = 5
      delay    = "15s"
      mode     = "delay"
    }

    network {
      mode = "bridge"
      port "api_expose_healthcheck" {
        to = -1
      }
    }

    service {
      name  = "demo-api"
      port  = "3000"

      meta {
        ingress_match = "demo-api/ connect" # this is how we expose the service on our gateway
        version       = "${NOMAD_META_image_version}"
      }

      check {
        name     = "demo-api-http-check"
        type     = "http"
        port     = "api_expose_healthcheck"
        path     = "/health"
        interval = "10s"
        timeout  = "2s"
      }

      connect {
        sidecar_service {
          proxy {
            expose {
              path {
                path            = "/health"
                protocol        = "http"
                local_path_port = 3000
                listener_port   = "api_expose_healthcheck"
              }
            }
          }
        }
      }
    }

    scaling {
      enabled = true
      min     = 2
      max     = 6

      policy {
        cooldown = "1m"

        check "requests_per_instance" {
          source = "prometheus"
          query  = "scalar(ceil(service:http_requests_per_instance:rate30s{local_cluster='demo-api'}))"
          strategy "target-value" {
            target = 4
          }
        }
      }
    }

    task "fakeservice" {
      driver = "docker"
      config {
        image   = "nicholasjackson/fake-service:${NOMAD_META_image_version}"
      }
      env {
        LISTEN_ADDR = "0.0.0.0:3000"
        LOG_LEVEL = "info"
      }

      template {
        data = <<EOH
NAME = "demo-api - {{ env "NOMAD_META_image_version" }} - [{{ env "node.datacenter" }}:{{ env "NOMAD_SHORT_ALLOC_ID" }}]"
MESSAGE = "Hello from demo-api. I am running on 'es/{{ env "node.datacenter" }}' with version '{{ env "NOMAD_META_image_version" }}'"
        EOH
        destination = "local/file.env"
        env         = true
      }

      resources {
        cpu = 500
        memory = 256
      }
    }
  }
}
```

**Comment by lgfa29** [comment] 2022-09-23 21:14
Hi @jorgemarey 👋 

That's definitely not expected since the Autoscaler [has a check to avoid scaling groups while a deployment is active](https://github.com/hashicorp/nomad-autoscaler/blob/v0.3.7/plugins/builtin/target/nomad/plugin/plugin.go#L148-L153). 

Do you see any scaling events for the job? You can use the [`nomad job scaling-events`](https://developer.hashicorp.com/nomad/docs/commands/job/scaling-events) to check them, and I think there would a task event as well.

**Comment by douglaje** [comment] 2022-10-06 17:25
We're running into what I believe is the same problem.

However, our issue is that scale-down events cause "unhealthy" allocations during a deployment, and can even stall a deployment to the point it has to roll back.

## Nomad version
`1.3.5`

## Reproduction setup

Setup: 5 nomad servers, 5 consul servers, 20+ nomad clients. Nomad clients and servers running version `1.3.5`, Consul version `1.13.2`. No cluster autoscaling during these tests. Autoscaler task running with ACL permissions to scale the `foo` namespace.

Job file:
```
job "scale-tester" {
  datacenters  = var.datacenters
  priority          = 50
  namespace   = "foo"
  type               = "service"
  region            = var.region

  group "scale-tester" {    
    update {
      max_parallel = 2
      auto_revert  = true
      auto_promote = true
      canary       = 3

      healthy_deadline = "5m"
      progress_deadline = "10m"
    }

    count = 10

    scaling {
      enabled = true
      min     = 1
      max     = 10

      policy {
        enabled             = true
        evaluation_interval = "5s"
        cooldown            = "10s"

        check "scale-down-cpu" {
          source = "nomad-apm"
          query  = "avg_cpu"

          strategy "threshold" {
            upper_bound = 90
            delta = -1
            within_bounds_trigger = 1  # Required if using nomad-apm as source
          }
        }
      }
    }

    network {
      port "http" {
        to = 7443
      }
    }

    task "scale-tester" {
      driver = "docker"

      env {
        RESTART_ME = "20"
      }

      config {
        # well-behaved container with immediate start, immediate shutdown
        image = var.container

        ports = ["http"]
      }

      service {
        name = "scale-tester"
        port = "http"

        check {
          type     = "http"
          path     = "/health"
          port     = "http"
          interval = "5s"
          timeout  = "4s"
        }
      }

      resources {
        cpu    = 200
        memory = 256
      }
    }
  }
}
```
^ Super basic container and job file for this. The important things are the rolling update (canaries seem to make it easier to replicate) and the autoscaling. This autoscaling will always be trying to scale down the job, to make the bug easier to replicate.

### Reproduction Steps:

1. Comment out the `scaling` block so we can establish how the deployment behaves without autoscaling
2. Submit the job a couple times, bumping the `env RESTART_ME` value to force an actual deployment rather than reusing the existing allocations.
3. Observe that the deployment behaves as expected:
```
    Description = Deployment completed successfully

    Deployed
    Task Group    Auto Revert  Promoted  Desired  Canaries  Placed  Healthy  Unhealthy  Progress Deadline
    scale-tester  true         true      10       3         10      10       0          2022-10-05T21:10:32Z
```
4. Un-comment the `scaling` block to enable scaling again. (We've run into a bug where setting `enabled = false` on the scaling or policy doesn't actually stop the autoscaler 😂 )
5. Submit the job, again bumping `env RESTART_ME`. Do _not_ use the `-preserve-counts` flag, as we need the `count = 10` to bring the task count back up since autoscaling will only ever scale down the task.
6. NOTE: replication can be tricky. We've found that this reproduces the issue ~60% of the time, so you might have to do several deployments to see the issue. It helps to do the deployment _immediately_ after the previous attempt completes, so there are running containers to cycle out. The super-aggressive autoscaling (every 5s/10s) means if you wait, the count will have scaled back down to 1 and you will only be replacing that single task rather than doing a true rolling deployment.
7. Observe that the deployment does not behave the same as the initial deployment.  The particular bad behavior we're looking for is "unhealthy" tasks.
```
    Description = Deployment completed successfully

    Deployed
    Task Group    Auto Revert  Promoted  Desired  Canaries  Placed  Healthy  Unhealthy  Progress Deadline
    scale-tester  true         true      10       3         11      10       1          2022-10-05T21:11:54Z
```

The "unhealthy" tasks seem to be ones that are killed almost immediately after starting
![image](https://user-images.githubusercontent.com/2522059/194357878-2095a428-7666-4cbb-a7b1-04a375d3a3ec.png)

I assume this is because the autoscaler tries to scale down, those tasks are stopped, but because they are part of the active deployment they are marked as "Unhealthy".

### Tips for replicating
If you're having trouble with the steps above, it can help to comment out the scaling, submit the job file to get a stable job with 10 running tasks, then uncomment the scaling which forces the scaling to kick in at the same time the deployment starts.

This further supports the idea that scaling is happening during deployments. Often times even if you immediately submit after one deployment has completed (and set the scale to 10), there will only be a few running tasks because during the minute the deployment takes, the autoscaler has reduced the desired count by ~6 and those 6 are immediately stopped as soon as the deployment completes. That's my theory at least, but it's hard to validate because scaling events do not show up in the log during the deployment.

### Stalled/rolled back deployments?
Yes, I mentioned at the beginning that this can lead to deployment failures.

We first found this issue with our legacy application which takes a long time to start up and an even longer time to shut down (often times not gracefully). The extremely generous timing settings in our job/task seemed to exacerbate the bug: sometimes it appeared that a task would be scaled down and marked "Unhealthy", and a new task would never be launched to replace that one, meaning the deployment would stall out and never complete:
```
    Status      = failed
    Description = Failed due to progress deadline - rolling back to job version 188

    Deployed
    Task Group    Auto Revert  Promoted  Desired  Canaries  Placed  Healthy  Unhealthy  Progress Deadline
    scale-tester  true         true      5        3         6       4        2          2022-10-05T19:07:22Z
```

However, this is very finicky to replicate. Instead I chose to submit the easier-to-replicate situation since I think the "Unhealthy" tasks are the root cause for the failed deployment. If you'd like me to submit that here or as a separate ticket, please let me know.

**Comment by douglaje** [comment] 2022-10-11 21:09
Well, I guess it's our lucky day. The 1.4.0 release happens to fix the issue we found, both for these replication steps and for our real-world issue.

I'm slightly confused since there's nothing in the changelog about it, but I'm not going to look a gift horse in the mouth.

**Comment by jorgemarey** [comment] 2022-10-26 07:20
I think I found out the problem here.

I changed the code in v1.3.4. Moved the group count change after the "in deployment" condition. With this change I wasn't able to reproduce the issue.

```
diff --git a/nomad/job_endpoint.go b/nomad/job_endpoint.go
index 331bb52387..dc43e5aa34 100644
--- a/nomad/job_endpoint.go
+++ b/nomad/job_endpoint.go
@@ -1075,9 +1075,6 @@ func (j *Job) Scale(args *structs.JobScaleRequest, reply *structs.JobRegisterRes
                        }
                }
 
-               // Update group count
-               group.Count = int(*args.Count)
-
                // Block scaling event if there's an active deployment
                deployment, err := snap.LatestDeploymentByJobID(ws, namespace, args.JobID)
                if err != nil {
@@ -1089,6 +1086,9 @@ func (j *Job) Scale(args *structs.JobScaleRequest, reply *structs.JobRegisterRes
                        return structs.NewErrRPCCoded(400, "job scaling blocked due to active deployment")
                }
 
+               // Update group count
+               group.Count = int(*args.Count)
+
                // Commit the job update
                _, jobModifyIndex, err := j.srv.raftApply(
                        structs.JobRegisterRequestType,
```

After this, looking at the code in v1.4.1, there's one change in the code: 
https://github.com/hashicorp/nomad/blob/2aa7e66bdb526e25f59883952d74dad7ea9a014e/nomad/job_endpoint.go#L1032

Could it be that previously the job was being mutated and the count changed even if the scale was not successful?

**Closed** 2022-11-08 16:05 UTC
Labels: type/bug, stage/needs-investigation, theme/autoscaling
