### ISSUE TITLE
Both tasks marked as unhealthy if only one fails.

### ISSUE THREAD

**Issue by erichulburd** [hashicorp/nomad#9254] opened 2020-11-02 23:00 UTC
# Nomad version

0.12.5

### Operating system and Environment details

MacOS Catalina 10.15.4, but I'm experiencing similar issues running through OpenStack.

### Issue

When a task group has 2+ tasks and _one_ fails, both tasks are marked unhealthy with `Task not running for min_healthy_time of 10s by deadline` in the UI (see reproduction steps below). Maybe this is intentional for some good reason, but the UX is confusing regardless.

<img width="1680" alt="nomad-both-tasks-fail" src="https://user-images.githubusercontent.com/3526083/97928534-15fb1b80-1d1c-11eb-87f4-3e221e4cb7aa.png">

### Reproduction steps

Please see source and instructions in [erichulburd/consul-nomad-issues](https://github.com/erichulburd/consul-nomad-issues).

### Job file (if appropriate)

[erichulburd/consul-nomad-issues/job.json](https://github.com/erichulburd/consul-nomad-issues/blob/master/job.json).

**Comment by tgross** [comment] 2020-12-16 21:17
Hi @erichulburd! So Nomad is behaving correctly here but the way it's being presented could probably be more clear.

Here's a more minimal reproduction for my colleagues on the UI team, so that they can see this for themselves:
* Run Nomad and Consul (dev mode is fine for both)
* Run the job below: `nomad job run ./example.nomad`


<details><summary>jobspec</summary>

```hcl
job "example" {
  datacenters = ["dc1"]

  update {
    health_check      = "checks"
    min_healthy_time  = "10s"
    healthy_deadline  = "1m"
    progress_deadline = "2m"
  }

  group "webservers" {
    network {
      port "www1" {
        to = 8080
      }

      port "www2" {
        to = 8081
      }
    }

    task "example-1" {
      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-v", "-f", "-p", "8080", "-h", "${NOMAD_TASK_DIR}"]
        ports   = ["www1"]
      }

      template {
        data        = "<html>ok</html>"
        destination = "local/index.html"
      }

      service {
        check {
          port     = "www1"
          type     = "http"
          path     = "/"
          interval = "2s"
          timeout  = "1s"
        }
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }


    task "example-2" {
      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-v", "-f", "-p", "8081", "-h", "${NOMAD_TASK_DIR}"]
        ports   = ["www2"]
      }

      template {
        data        = "<html>ok</html>"
        destination = "local/index.html"
      }

      # this health check will never pass
      service {
        check {
          port     = "www2"
          type     = "http"
          path     = "/does-not-exist"
          interval = "2s"
          timeout  = "1s"
        }
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }

  }
}
```

</details>


* Modify the job so that the allocation has to be updated (changing `cpu = 501` in the `resources` block will do the trick).
* Wait until the deployment fails (~2 min).

```
$ nomad deployment status d44
ID          = d4408e56
Job ID      = example
Job Version = 1
Status      = failed
Description = Failed due to progress deadline

Deployed
Task Group  Desired  Placed  Healthy  Unhealthy  Progress Deadline
webservers  1        1       0        1          2020-12-16T21:08:56Z
```

At this point the allocation status will look like this. Note that we have an `Alloc Unhealthy` event, with the description `"Task not running for min_healthy_time of 10s by deadline"`. If you take a look at the Nomad UI, you'll see the same thing shown there.

```
$ nomad alloc status 6cd
...

Task "example-1" is "running"
Task Resources
CPU        Memory          Disk     Addresses
0/500 MHz  36 KiB/256 MiB  300 MiB

Task Events:
Started At     = 2020-12-16T21:07:03Z
Finished At    = N/A
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                       Type             Description
2020-12-16T16:08:02-05:00  Alloc Unhealthy  Task not running for min_healthy_time of 10s by deadline
2020-12-16T16:07:03-05:00  Started          Task started by client
2020-12-16T16:07:02-05:00  Task Setup       Building Task Directory
2020-12-16T16:06:56-05:00  Received         Task received by client

Task "example-2" is "running"
Task Resources
CPU        Memory          Disk     Addresses
0/500 MHz  40 KiB/256 MiB  300 MiB

Task Events:
Started At     = 2020-12-16T21:07:03Z
Finished At    = N/A
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                       Type             Description
2020-12-16T16:08:02-05:00  Alloc Unhealthy  Task not running for min_healthy_time of 10s by deadline
2020-12-16T16:07:03-05:00  Started          Task started by client
2020-12-16T16:07:02-05:00  Task Setup       Building Task Directory
2020-12-16T16:06:56-05:00  Received         Task received by client
```

The Nomad client is doing the right thing here: the deployment was not unhealthy by the progress deadline, so the whole allocation is marked as unhealthy. The way this is presented in the CLI is a little weird but because we see the `Type` I feel like that makes it a bit more clear. But in the web UI we don't have the `Type` field and maybe that's why it looks misleading?

**Comment by DingoEatingFuzz** [comment] 2021-01-27 18:44
> The way this is presented in the CLI is a little weird but because we see the Type I feel like that makes it a bit more clear. 

It still seems weird to me that both tasks get the event? I suppose the event truly belongs to the alloc but there are no alloc events so this is the workaround?

>  But in the web UI we don't have the Type field and maybe that's why it looks misleading?

The type is shown if you drill into the task detail page, but we can probably make this clearer on the alloc detail page too.

**Comment by crestonbunch** [comment] 2021-12-22 04:07
I'm seeing this behavior when I have a task with 

```
lifecycle {
  hook    = "poststart"
  sidecar = false
}
```

Even when the task exits successfully with status code 0 and everything else is fine, the alloc is marked as unhealthy.

This seems like a bug to me, or at least something that needs to have a workaround. If I have a task that is meant to do some kind of initialization then immediately exit, that shouldn't block the other tasks from being considered healthy.

**Closed** 2022-02-02 21:29 UTC
Labels: type/bug, theme/ui, stage/needs-discussion
