### ISSUE TITLE
Nomad on AWS: nomad server members returns No cluster Leader

### ISSUE THREAD

**Issue by aashayshahh** [hashicorp/nomad#7173] opened 2020-02-18 05:32 UTC
I followed all the instructions provided in the Nomad on AWS deployment guide to launch nomad into a new VPC. The stack launched successfully. I ssh'ed into the linux bastion host. After I am in the bastion, I ssh'ed into one of the 3 nomad servers. Once I am on one of the nomad servers. I type in:
```
nomad server members
```
Thats when i get this error:
```
Error determining leaders: 1 error(s) occurred:

* Region "global": Unexpected response code: 500 (No cluster leader)
```

I would highly appreciate it if anyone can help me resolve this since I am pretty new to nomad. Thanks in advance.

**Comment by tgross** [comment] 2020-02-18 13:02
@aashayshahh that sounds like either (a) the Nomad servers weren't able to connect to each other because of security group rules, or (b) the IAM instance role for the EC2 instances that the servers were on didn't have access to the required AWS permissions for autodiscovery.

**Comment by aashayshahh** [comment] 2020-02-18 18:20
> @aashayshahh that sounds like either (a) the Nomad servers weren't able to connect to each other because of security group rules, or (b) the IAM instance role for the EC2 instances that the servers were on didn't have access to the required AWS permissions for autodiscovery.

Hey @tgross Thanks for the fast response. Highly appreciate it. Would you be able to lay down steps for how I can resolve this? I can try both the options that you mentioned for the solution but I don't know how to do that. Again, your help is much appreciated. Thanks in advance.

**Comment by tgross** [comment] 2020-02-18 19:18
@aashayshahh if you can link to the guide you're following I might be able to help you out (I'm not finding that title in our docs), but if the problem is in connectivity in AWS your infrastructure that's probably beyond the scope of what I can do for you.

**Comment by aashayshahh** [comment] 2020-02-18 19:23
> @aashayshahh if you can link to the guide you're following I might be able to help you out (I'm not finding that title in our docs), but if the problem is in connectivity in AWS your infrastructure that's probably beyond the scope of what I can do for you.

@tgross I have used this deployment guide:
https://aws-quickstart.s3.amazonaws.com/quickstart-hashicorp-nomad/doc/hashicorp-nomad-on-the-aws-cloud.pdf

I have followed it step by step for the option of "Deploying in new VPC". Thanks for the help.

**Comment by aashayshahh** [comment] 2020-02-18 23:21
@tgross - Just to explain it better in detail.
I followed this deployment guide:
https://aws-quickstart.s3.amazonaws.com/quickstart-hashicorp-nomad/doc/hashicorp-nomad-on-the-aws-cloud.pdf

To launch Nomad into a new VPC on my AWS.
After that I ssh into the bastion host. From there I ssh into the nomad server. Once I am on nomad server, I run this command:
```
nomad server members
```
This is what is displays to me:
![Screen Shot 2020-02-18 at 3 17 53 PM](https://user-images.githubusercontent.com/43300957/74786561-e1186880-5261-11ea-9e57-dfda9cd5b036.jpg)

I would expect it to display all 3 server members and not just one. Basically what this is doing is, instead of displaying 3 server members, it just displaying itself. And the Leader=false. I would expect it to display all 3 members with one of them being Leader=True. In a nutshell, it seems like all 3 nomad server members are not able to find/communicate with each other. Please note that my 3 nomad server members are in one region but 3 different AZs. Kindly help me out if I am missing some permissions or configurations.

**Comment by tgross** [comment] 2020-02-19 13:33
That quickstart guide is pretty old. I'd expect it to still work but you'll probably have to do some debugging here. The source for the quickstart appears to be https://github.com/aws-quickstart/quickstart-hashicorp-nomad, and that's running an older and less secure version of Nomad than I'd recommend (0.8.4). Also, it looks like that server config doesn't take advantage of the [cloud auto join](https://nomadproject.io/docs/configuration/server_join/#cloud-auto-join) feature added in 0.8.4, which I find is really nice on AWS.

There some more recent work done with Terraform at https://github.com/hashicorp/nomad/tree/master/terraform/aws that you might find a more up-to-date approach.

In the meantime I would check the following:

* does the consul cluster report that it's up with all members?
* have you verified that the [`install_server.sh`](https://github.com/aws-quickstart/quickstart-hashicorp-nomad/blob/develop/scripts/install_server.sh) script completed all steps successfully on all the servers?
* is the `nomad` process actually running on all 3 server instances?
* if so, do the `nomad` logs tell you anything about why they weren't able to join the cluster?
* does the security group assigned to the server instances permit port 4646/tcp between the servers?
* can you verify that 4646/tcp traffic can pass between servers?

**Comment by aashayshahh** [comment] 2020-02-19 18:28
> That quickstart guide is pretty old. I'd expect it to still work but you'll probably have to do some debugging here. The source for the quickstart appears to be https://github.com/aws-quickstart/quickstart-hashicorp-nomad, and that's running an older and less secure version of Nomad than I'd recommend (0.8.4). Also, it looks like that server config doesn't take advantage of the [cloud auto join](https://nomadproject.io/docs/configuration/server_join/#cloud-auto-join) feature added in 0.8.4, which I find is really nice on AWS.
> 
> There some more recent work done with Terraform at https://github.com/hashicorp/nomad/tree/master/terraform/aws that you might find a more up-to-date approach.
> 
> In the meantime I would check the following:
> 
> * does the consul cluster report that it's up with all members?
> * have you verified that the [`install_server.sh`](https://github.com/aws-quickstart/quickstart-hashicorp-nomad/blob/develop/scripts/install_server.sh) script completed all steps successfully on all the servers?
> * is the `nomad` process actually running on all 3 server instances?
> * if so, do the `nomad` logs tell you anything about why they weren't able to join the cluster?
> * does the security group assigned to the server instances permit port 4646/tcp between the servers?
> * can you verify that 4646/tcp traffic can pass between servers?

Hello @tgross  I started performing all the debugging steps you just mentioned.
1. When I type in consul members on each of the nomad servers, they do report that all the members are up and running.
2. install_server.sh is present on all the servers
3. All 3 nomad server instances seem to run because I am able to ssh into them and run the nomad server members command. Although for each of the nomad servers, whenever I run the nomad server members command, in the output, it just returns itself and not the other 2 members. I would expect that whenever I run nomad server members on any of the nomad servers, it should return me all 3 nomad servers with one of them being the cluster leader. 
4. Could you please tell me where can I check the logs. That is one thing that I haven't checked yet.
5. The security group has inbound rules:ports 0-65535 opened for tcp protocol with 10.0.0.0/16 has the source. outbound rules are open for all ports all protocols and 0.0.0.0/0 as the destination.
6. How do I verify whether the 4646/tcp traffic can pass between servers?

I really appreciate your help. Thanks for guiding me through with this since I am very new to nomad and I need to get this thing up and running as soon as possible. Much appreciated.

Just a side note: All 3 nomad servers have the same IAM role that has only 2 policies attached: EC2ReadOnly and ECR_readonly. My best guess at the moment is that it has something to do with the policies. The reason why I say this is that I had performed this same task once which was a year ago and at that time I had not faced any issues at all. This time I have recreated each and every step to the best of my memory. The only thing I don't remember is the policies that i had at the time and if there were some config changes that I made after launching the stack.

**Comment by tgross** [comment] 2020-02-19 18:41
> 2. install_server.sh is present on all the servers

My apologies, I probably could have asked that more clearly. You want to check that `install_server.sh` actually ran on the servers successfully. That is, walk thru the steps it does and make sure you see everything you'd expect to see. For example, do the `server.hcl` files it creates have the IPs configured are they still showing the templated values?

> 4. Could you please tell me where can I check the logs. 

The setup script is running Nomad as a systemd service, so `journalctl` should have them.

> 6. How do I verify whether the 4646/tcp traffic can pass between servers?

If you know Nomad is running and bound to the private IP address on port 4646 (check that with `netstat`), you could `curl` from one server to another.

> Just a side note: All 3 nomad servers have the same IAM role that has only 2 policies attached: EC2ReadOnly and ECR_readonly. My best guess at the moment is that it has something to do with the policies.

My question about the policies was assuming that you were using the cloud auto-join feature. It doesn't look like the config file does.

**Comment by aashayshahh** [comment] 2020-02-19 19:39
> > 1. install_server.sh is present on all the servers
> 
> My apologies, I probably could have asked that more clearly. You want to check that `install_server.sh` actually ran on the servers successfully. That is, walk thru the steps it does and make sure you see everything you'd expect to see. For example, do the `server.hcl` files it creates have the IPs configured are they still showing the templated values?
> 
> > 1. Could you please tell me where can I check the logs.
> 
> The setup script is running Nomad as a systemd service, so `journalctl` should have them.
> 
> > 1. How do I verify whether the 4646/tcp traffic can pass between servers?
> 
> If you know Nomad is running and bound to the private IP address on port 4646 (check that with `netstat`), you could `curl` from one server to another.
> 
> > Just a side note: All 3 nomad servers have the same IAM role that has only 2 policies attached: EC2ReadOnly and ECR_readonly. My best guess at the moment is that it has something to do with the policies.
> 
> My question about the policies was assuming that you were using the cloud auto-join feature. It doesn't look like the config file does.

2. I saw the install_server.sh and it seems like it ran because I see the server.hcl file which looks like this:
![Screen Shot 2020-02-19 at 11 37 45 AM](https://user-images.githubusercontent.com/43300957/74869168-5771a500-530c-11ea-8a31-22f6e95b12bf.jpg)


4. I tried to find the journalctl but could not find it. Could you please tell me it what path it might be present incase you know it off the top of your head. 

But I did run the ``` sudo service nomad status ``` command as soon as I ssh'ed into the nomad server as the very first step. It looks like this:

![Screen Shot 2020-02-19 at 11 11 03 AM](https://user-images.githubusercontent.com/43300957/74868355-fac1ba80-530a-11ea-992d-d29bce4f3b0c.jpg)

Seems like it has failed right here only.

6. I tried to check ``` netstat | grep <other nomad server IP> ``` output but it did not return anything. I also tried to run ``` curl <other nomad server ip> -I ``` but it returned this 
```
curl: (7) Failed to connect to 10.0.74.15 port 80: Connection refused
```
Also how do I check if the auto-join feature is being used or not? Which config file would tell me that.

**Comment by aashayshahh** [comment] 2020-02-19 19:45
@tgross I also tried the follow. ```netstat | grep <IP of the nomad server that I am on right now> ```
It returned me this:
![Screen Shot 2020-02-19 at 11 44 36 AM](https://user-images.githubusercontent.com/43300957/74869727-5b51f700-530d-11ea-834e-5732f725ebaf.jpg)

**Comment by tgross** [comment] 2020-02-19 19:50
> 2. I saw the install_server.sh and it seems like it ran because I see the server.hcl file which looks like this:

Ok, that config file looks good.

> 3. I tried to find the journalctl but could not find it. Could you please tell me it what path it might be present incase you know it off the top of your head.

`journalctl` is the command line tool shipped in Linux distributions that use systemd for viewing logs. You're looking for the logs from the `nomad` unit. There's a good tutorial on how that works at https://www.digitalocean.com/community/tutorials/how-to-use-journalctl-to-view-and-manipulate-systemd-logs (none of that is specific to DO).

> Seems like it has failed right here only.

When you do `systemctl status` that only shows you the handful most recent logs, not the ones from startup. You need to use `journalctl` to get the backlog.

> 6. I tried to check netstat | grep <other nomad server IP> output but it did not return anything. I also tried to run curl <other nomad server ip> -I 
> @tgross I also tried the follow. netstat | grep <IP of the nomad server that I am on right now>

`sudo netstat -antp | grep nomad` will filter specifically for the Nomad process on the host you run it from. You should see something like the following. We're looking to see that Nomad is `LISTEN`ing on ports 4646, 4647, and 4648:

```
$ sudo netstat -antp | grep nomad
tcp        0      0 10.0.2.15:4646          0.0.0.0:*               LISTEN      2426/nomad
tcp        0      0 10.0.2.15:4647          0.0.0.0:*               LISTEN      2426/nomad
tcp        0      0 10.0.2.15:4648          0.0.0.0:*               LISTEN      2426/nomad
tcp        0      1 10.0.2.15:47198         169.254.169.254:80      SYN_SENT    2426/nomad
tcp        0      0 10.0.2.15:4647          10.0.2.15:59846         ESTABLISHED 2426/nomad
tcp        0      0 10.0.2.15:59846         10.0.2.15:4647          ESTABLISHED 2426/nomad
tcp        0      1 10.0.2.15:47194         169.254.169.254:80      SYN_SENT    2426/nomad
tcp        0      1 10.0.2.15:47200         169.254.169.254:80      SYN_SENT    2426/nomad
```

For `curl`, you need to include the port. Using the IP you gave, `curl http://10.0.74.15:4646/v1/status/leader` should return something (it'll be empty because there's no leader yet but the request shouldn't fail).

**Comment by aashayshahh** [comment] 2020-02-19 20:11
@tgross Okay I tried ``` sudo netstat -antp | grep nomad ``` and it does return what we are expecting. It looks like the one in the screenshot you attached above.

And ``` curl http://10.0.74.15:4646/v1/status/leader ``` also does not fail. It returns No cluster leader though. 

And just to confirm - you said that the server.hcl file looks good right?

Is there anything you would suggest i specifically look into that might be the cause of the problem or do you have any suggestions for me to do something to resolve this?

**Comment by aashayshahh** [comment] 2020-02-19 20:14
@tgross  I also tried ``` journalctl | grep nomad ```
This is what it returned to me. Please look into this - I feel it might have some clues that I am not able to understand clearly.
![Screen Shot 2020-02-19 at 12 13 27 PM](https://user-images.githubusercontent.com/43300957/74872041-57c06f00-5311-11ea-83aa-9a6e172e6d7e.jpg)

**Comment by tgross** [comment] 2020-02-19 21:27
> And just to confirm - you said that the server.hcl file looks good right?

Yup.

From those logs I can see:

- The server hasn't been joined to any other server (which we'd expect from the install script), and that it's checking with Consul for its peers: `server.nomad: lost contact with Nomad quorum, falling back to Consul for server list`
- The Nomad node has registered itself with Consul: `consul.sync: registered 3 services, 3 checks`
- But it doesn't seem to be finding its peers in Consul: `raft: no known peers`

I would next check to make sure that all 3 nodes are registered in Consul and are showing as healthy in the Consul UI.

If you just want to get Nomad up to try it out, you can also manually join the servers to each other by running [`nomad server join`](https://nomadproject.io/docs/commands/server/join/).

**Comment by aashayshahh** [comment] 2020-02-20 00:00
> > And just to confirm - you said that the server.hcl file looks good right?
> 
> Yup.
> 
> From those logs I can see:
> 
> * The server hasn't been joined to any other server (which we'd expect from the install script), and that it's checking with Consul for its peers: `server.nomad: lost contact with Nomad quorum, falling back to Consul for server list`
> * The Nomad node has registered itself with Consul: `consul.sync: registered 3 services, 3 checks`
> * But it doesn't seem to be finding its peers in Consul: `raft: no known peers`
> 
> I would next check to make sure that all 3 nodes are registered in Consul and are showing as healthy in the Consul UI.
> 
> If you just want to get Nomad up to try it out, you can also manually join the servers to each other by running [`nomad server join`](https://nomadproject.io/docs/commands/server/join/).

@tgross I was successfully able to join in nomad servers manually and now when I run ``` nomad server members ``` it does return me all 3 nomad servers with one of them being the leader. When I run ``` consul members ``` it does return me all the members with status as Alive. But how do I make sure that this setup is complete? 
Note: I noticed a weird thing that when I run ``` nomad node-status ``` it does not return me anything. It's empty response. Is there a reason why this happens? I am still not sure if the nomad servers are able to communicate with each other. Please let me know if I am failing to check anything.

**Comment by aashayshahh** [comment] 2020-02-20 01:15
@tgross  to add to the problem, I also tried to ssh into one of the nomad client nodes. I tried to run ``` nomad node status ``` but it threw me this error:
```
Error querying node info: Unexpected response code: 500 (no servers)
```

It seems like consul is not doing the job of discovering servers and clients. Even for the servers, after I tried manually joining them, they popped up in nomad server members. Now here nomad node status is also empty, so probably the same issue that the nomad client node is not aware of the nomad server node.

Is there any config file that I am supposed to create after I launch the stack? or make some changes in some config file?

**Comment by tgross** [comment] 2020-02-20 13:30
> Is there any config file that I am supposed to create after I launch the stack? or make some changes in some config file?

I believe it's supposed to be using Consul to bootstrap the serf membership, but if you look at the submodule directory for the Consul cluster (ref https://github.com/aws-quickstart/quickstart-hashicorp-consul) you can see that AWS has been updating the scripts for the Consul guide but not the Nomad one. So it could just be that there's an incompatibility across versions.

But to be clear again, this is an unsupported version of Nomad so I'd recommend using a more recent guide to do this work for production. I would also recommend you update your server configurations to use the auto_join` stanza and set up the IAM roles you'd need for that.

**Comment by aashayshahh** [comment] 2020-02-20 18:05
> > Is there any config file that I am supposed to create after I launch the stack? or make some changes in some config file?
> 
> I believe it's supposed to be using Consul to bootstrap the serf membership, but if you look at the submodule directory for the Consul cluster (ref https://github.com/aws-quickstart/quickstart-hashicorp-consul) you can see that AWS has been updating the scripts for the Consul guide but not the Nomad one. So it could just be that there's an incompatibility across versions.
> 
> But to be clear again, this is an unsupported version of Nomad so I'd recommend using a more recent guide to do this work for production. I would also recommend you update your server configurations to use the auto_join` stanza and set up the IAM roles you'd need for that.

Okay thank you so much for your help in debugging this. I'll take a look into this and probably follow a more recent version. In case if I have any questions, I will post it as comments here, if that's fine. Thanks again @tgross

**Comment by wamonite** [comment] 2020-03-17 10:42
Hello,

Did either of you manage to debug this any further? I built a config from scratch and tested successfully on a local setup. I then moved the config to AWS and hit exactly the same problem,  whereby each Nomad server would fail to find each other via Consul and would never elect a leader (see log snippet below):-

```
    2020-03-17T10:01:17.448Z [DEBUG] nomad: lost contact with Nomad quorum, falling back to Consul for server list
    2020-03-17T10:01:17.491Z [DEBUG] consul.sync: sync complete: registered_services=3 deregistered_services=0 registered_checks=3 deregistered_checks=0
    2020-03-17T10:01:17.642Z [DEBUG] nomad: memberlist: Stream connection from=172.20.xx.xx:52542
    2020-03-17T10:01:19.373Z [WARN]  nomad: raft: no known peers, aborting election
```

I have confirmed it's not a security group issue, as the Consul cluster is bootstrapped using AWS tag inspection, so when I add the same 'retry_join' config to Nomad, the 'agent.joiner' successfully identifies the server hosts, connects to them and bootstraps the Nomad cluster.

I am concerned that as the Consul server discovery doesn't work, if the reason isn't discovered then I may have issues later related to Consul integration. Any further help in debugging would be appreciated.

Thanks,

Warren

**Comment by tgross** [comment] 2020-03-17 12:45
@wamonite can you confirm which Nomad servers' services are showing up in Consul? Also, can you provide the configuration files you're using (as well as the specific versions of Nomad and Consul)?

For what it's worth, bootstrapping the Nomad servers from Consul, which in turn bootstraps via the AWS autodiscovery is how we run our nightly end-to-end test cluster ([see configs here](https://github.com/hashicorp/nomad/tree/master/e2e/terraform/shared)) so this _should_ be a pretty well-tested path. But maybe there's a specific configuration that's odd here.

**Comment by wamonite** [comment] 2020-03-17 13:07
Hi @tgross, thanks for the quick response. Yes, all services and checks for each server were visible in Consul. Checks were reporting successfully, apart from API which was failing due to `error="{"server":{"ok":false,"message":"No cluster leader"}}" code=500`. All IPs and node references appeared as expected in Consul UI.

Nomad: 0.10.4
Consul: 1.6.1 (due an upgrade, but the same version used for local testing)

My `nomad.hcl`. `my-dc` matches Consul datacenter and `my-server-name` matches Consul agent name.
```
# region may contain multiple datacentres
region = "my-dc"
datacenter = "my-dc"
# name must be unique per region
name = "my-server-name"
data_dir = "/data/nomad/data"

enable_syslog = true
syslog_facility = "LOCAL0"
log_level = "DEBUG"

consul {
  address = "172.17.0.1:8500"
  token = "..."
  checks_use_advertise = true
}

server = {
  enabled = true
  bootstrap_expect = 3
  raft_protocol = 3
  authoritative_region = "my-dc"
  encrypt = "..."
}

tls {
  rpc = true

  ca_file = "/data/nomad/config/certs/ca.pem"
  cert_file = "/data/nomad/config/certs/cert.pem"
  key_file = "/data/nomad/config/certs/key.pem"

  verify_server_hostname = true
  verify_https_client = false
}

acl {
  enabled = true
}
```

**Closed** 2020-07-16 01:10 UTC
Labels: question, waiting-reply

**Comment by l-monninger** [comment] 2022-07-27 18:14
@tgross Seeing something very similar in GCP in 2022. All Consul members connected, but no cluster leader for Nomad.

`journalctl` output:
```
Jul 27 18:02:03 gcp-rpc-cluster-servers-5sp9 user-data[2338]: 2022-07-27 18:02:03 [INFO] [run-nomad] Reloading Supervisor config and starting Nomad
Jul 27 18:02:03 gcp-rpc-cluster-servers-5sp9 user-data[2338]: nomad: available
Jul 27 18:02:04 gcp-rpc-cluster-servers-5sp9 user-data[2338]: nomad: added process group
Jul 27 18:02:04 gcp-rpc-cluster-servers-5sp9 supervisord[1284]: 2022-07-27 18:02:04,072 INFO spawned: 'nomad' with pid 2884
Jul 27 18:02:05 gcp-rpc-cluster-servers-5sp9 supervisord[1284]: 2022-07-27 18:02:05,074 INFO success: nomad entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Jul 27 18:02:13 gcp-rpc-cluster-servers-5sp9 consul[2530]: 2022-07-27T18:02:13.409Z [INFO]  agent.http: Request cancelled: method=GET url=/v1/catalog/service/nomad?dc=us-west1&near=_agent&stale=&tag=serf&wait=2000ms from=127.0.0.1:54846 error="No cluster leader"
Jul 27 18:02:27 gcp-rpc-cluster-servers-5sp9 consul[2530]: 2022-07-27T18:02:27.572Z [INFO]  agent.http: Request cancelled: method=GET url=/v1/catalog/service/nomad?dc=us-west1&near=_agent&stale=&tag=serf&wait=2000ms from=127.0.0.1:54858 error="No cluster leader"
```
