### ISSUE TITLE
Tens of thousands of open file descriptors to a single nomad alloc logs directory 

### ISSUE THREAD

**Issue by sheldonkwok** [hashicorp/nomad#2024] opened 2016-11-23 02:31 UTC
### Nomad version
Nomad v0.4.1

### Operating system and Environment details
Linux ip-10-201-5-129 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Issue
Nomad has tens of thousands of open file descriptors to an alloc log directory.

nomad   2143 root *530r      DIR             202,80     4096    8454154 /var/lib/ssi/nomad/alloc/14e62a40-8598-2fed-405e-ca237bc940c6/alloc/logs

Something similar to that repeated ~60000 times.
`lsof -p 2143 | wc -l` returns ~60000

I stopped the alloc but the descriptors are still there. 

In addition, the nomad process is approaching 55 GB of memory used.

**Comment by dadgar** [comment] 2016-11-23 18:08
Hey could you post the open file descriptors in a gist? 

Two questions:
1) Can you grab the memory usage of all nomad processes (tree view would be great)
2) Do you have `enable_debug` set? If so can you grab a memory profile of the agent by hitting:

`go tool pprof -output=mem.profile http://127.0.0.1:4646/debug/pprof/heap``

**Comment by sheldonkwok** [comment] 2016-11-23 18:45
1) Not running raw_exec jobs.
2/3) Will do next time we run into the issue.

**Comment by sheldonkwok** [comment] 2016-11-23 21:50
![process](http://i.imgur.com/SSRWLF9.png)

Here's a glimpse of htop. The process just ran out of memory and rebooted.
The logs are filled with "dropping update to alloc"

Unfortunately, this agent did not have enable_debug set.

**Comment by sheldonkwok** [comment] 2016-11-23 21:54
![image](https://cloud.githubusercontent.com/assets/1491201/20579926/4d6c90ce-b184-11e6-88ce-2565799f02be.png)

Here's a graph of memory usage from our alerting system.

**Comment by dadgar** [comment] 2016-11-26 01:14
@sheldonwok can you attach the logs and the open file descriptors. 

Does this happen regularly? The memory profile will help a lot!

**Comment by dadgar** [comment] 2016-11-26 01:45
What drivers are you using btw?

**Comment by sheldonkwok** [comment] 2016-11-29 18:52
Using the docker driver. Debug is on now so I'll have to catch it when it's in the bad state before it reboots.

**Comment by sheldonkwok** [comment] 2016-11-30 08:14
Bad news. Getting `net/http: timeout awaiting response headers` when trying to run `go tool pprof`. Notably we were running the logging command before this and the 60000 open file descriptors are 

```
nomad   2113 root *012r      DIR  202,80     4096 8456000 /var/lib/ssi/nomad/alloc/ddf27f57-9179-2fbf-9c44-69f54a28f17b/alloc/logs
nomad   2113 root *013r      DIR  202,80     4096 8456000 /var/lib/ssi/nomad/alloc/ddf27f57-9179-2fbf-9c44-69f54a28f17b/alloc/logs
nomad   2113 root *014r      DIR  202,80     4096 8456000 /var/lib/ssi/nomad/alloc/ddf27f57-9179-2fbf-9c44-69f54a28f17b/alloc/logs
```

repeated many many times.

**Comment by jippi** [comment] 2016-11-30 08:19
got anything in the client or server logs relevant to the issue? e.g. repeated actions ?

**Comment by sheldonkwok** [comment] 2016-11-30 08:25
A lot of 
`client: alloc "00e0bb67-624c-5221-087b-ba31f5740b43" in terminal status, waiting for destroy`
but that seems more of a product of the client running out of memory

**Comment by sheldonkwok** [comment] 2016-12-01 22:19
We encountered this issue again after hitting the logging api for one of the services. It's crashing multiple production nomad clients.

**Comment by dadgar** [comment] 2016-12-01 22:20
@sheldonkwok Can you show `nomad fs` of that folder? What is the logging like of the task? What is the log config

**Comment by sheldonkwok** [comment] 2016-12-01 22:22
```
Mode        Size    Modified Time          Name
-rw-r--r--  31 KiB  12/01/16 21:25:59 UTC  service.stderr.0
-rw-r--r--  0 B     12/01/16 06:31:26 UTC  service.stdout.0
```
```
      LogConfig: {
        MaxFileSizeMB: 10,
        MaxFiles: 10,
      },
```
Nothing too crazy it seems.

**Comment by dadgar** [comment] 2016-12-01 22:35
Does this reproduce every time you log or just occasionally. What is the log command you are running?

**Comment by sheldonkwok** [comment] 2016-12-01 22:39
/v1/client/fs/logs/<Allocation-ID>
follow=true,origin=start,offset=0

We're not sure if it's every time or just occasionally. The descriptors are open on the client.

**Comment by dadgar** [comment] 2016-12-01 22:50
@sheldonkwok I can not reproduce this on either 0.4.1/0.5.0/master. It would be great if you could get a vagrant box or some reproductions steps so I can debug this. As of now it is a bit hard since you can't even attach a profiler

**Comment by sheldonkwok** [comment] 2016-12-01 22:54
We're still working on some reproduction steps because nothing we do immediately crashes the system and we're alerted of issues later.

**Comment by sheldonkwok** [comment] 2016-12-01 23:16
Managed to get the client into a state where the memory low but the number of file descriptors open is still high. Here's the mem profile.

http://pastebin.com/XbPH9qhw

**Comment by dadgar** [comment] 2016-12-02 00:39
Could you get the profile too and send both the heap and profile output


Thanks,
Alex

**Comment by justinwalz** [comment] 2016-12-02 01:56
Hi,

Tree: http://pastebin.com/Up3kLmvi
Top: http://pastebin.com/GxfDm6Hg
Dot: http://pastebin.com/iVLYVUY8

Does this help?

**Comment by sheldonkwok** [comment] 2016-12-06 01:52
We upgraded to Nomad 0.5 and we're still experiencing this issue when we make multiple requests to an allocation's log route simultaneously. Our use case is that many of our devs want to see logs for their service at the same time.

**Comment by dadgar** [comment] 2016-12-06 02:03
@sheldonkwok Can you get me this: `curl http://127.0.0.1:4646/debug/pprof/goroutine?debug=2`

How are retrieving the logs? Programatically?

**Comment by sheldonkwok** [comment] 2016-12-06 02:12
Will do next time it happens.
We are using the route `/v1/client/fs/logs/<Allocation-ID>` when one of the devs asks for logs.

**Comment by dadgar** [comment] 2016-12-06 02:13
My current thought is you may never be closing the connection which is causing this

**Comment by sheldonkwok** [comment] 2016-12-06 02:29
I was considering that but the number of file descriptors jumped from dozens to the tens of thousands pretty quickly when we only made a handful of simultaneous requests.

**Comment by leonoff** [comment] 2016-12-07 07:50
I reproduced this behavior with `nomad logs` command. When job contains more that one task and you trying to see logs from them e.g.:
`nomad logs -tail -f -stderr -job job_name`

**Comment by sheldonkwok** [comment] 2016-12-07 17:49
We unfortunately had to stop using the nomad logs/logs route because of this issue. We are instead ingesting the logs through Filebeat/Logstash/Elasticsearch. It doesn't handle streaming as well though.

**Comment by dadgar** [comment] 2016-12-07 19:16
@sheldonkwok Sorry to hear that! Hope to be able to resolve soon and get you using it again. Still haven't been able to reproduce unfortunately!

@leonoff When I do that I get a message telling me to pick which task? Is that not the behavior you see?

**Comment by leonoff** [comment] 2016-12-08 09:32
@dadgar I don't see any messages telling me to pick up task,
my job: https://gist.github.com/leonoff/1169e6337ba0ccc56c044a6a857207f1
step-by-step actions:
1. `nomad run -check-index 0 job.hcl`
2. wait until running
3. `nomad logs -tail -f -stderr -job hello`
4. see no logs(it's ok)
5. exit, ^C
6. CPU usage on nomad spikes up to 100% & count of opened file descriptors grown up to 2-3k

I'm running Nomad v0.5.0

**Comment by dadgar** [comment] 2016-12-08 19:35
@leonoff @sheldonkwok Got it to reproduce!!! Thanks for the instruction @leonoff. I have reproduced it. For me though the file descriptors close after a while and it is a few hundred not thousand. Still bad behavior though.

Will begin investigating!

**Comment by leonoff** [comment] 2016-12-08 19:52
@dadgar I suppose that number of opened file descriptors at a time limited by cpu resource :). And yes, in most cases file descriptors close after a while, but some times it didn't and only way to stop it is to stop the job. Also, I mentioned a strange "side effect": after an "incident" average CPU usage of nomad is increased. e.g. when job(specified above) running nomad uses 0.3-0.7% of cpu, after an incident(when file descriptors closed) 20-30%.

**Comment by dadgar** [comment] 2016-12-08 19:53
Yeah I noticed the jump in CPU too.

**Comment by jippi** [comment] 2016-12-09 16:38
I just found a bug in nomad-ui that would cause it to never ever stop tailing files 

if you use nomad-ui it could be part of the cause, maybe

**Comment by diptanu** [comment] 2016-12-10 03:15
@sheldonkwok @leonoff Can you please test the fix? We released new binaries https://releases.hashicorp.com/nomad/0.5.1-rc2/

**Comment by sheldonkwok** [comment] 2016-12-10 07:45
Will do. Thanks for the quick turnaround!

**Comment by leonoff** [comment] 2016-12-12 14:34
@diptanu @dadgar Tested new binaries, issue fixed for me.

**Comment by dadgar** [comment] 2016-12-12 17:36
@leonoff Awesome! Thank you!

**Comment by justinwalz** [comment] 2016-12-13 03:43
@dadgar @diptanu Please see https://github.com/hashicorp/nomad/issues/2089.

Had no issues today with logging, but did have many clients panic.

**Comment by sheldonkwok** [comment] 2017-01-11 03:54
The file descriptor issue just creeped back on to our system today running Nomad 0.5.2... Will try to reproduce. Just letting everyone know.

**Comment by justinwalz** [comment] 2017-01-23 17:55
This has still been happening a lot for us lately. Today there was an actual panic - I opened a separate ticket [here](https://github.com/hashicorp/nomad/issues/2230), but there was heavy utilization of logs during the time of the crash. I still have a feeling there's an edge case in here somewhere...

**Comment by dadgar** [comment] 2017-01-23 18:01
@justinwalz Do you have a list of the file descriptors that were open?

**Comment by justinwalz** [comment] 2017-01-23 18:53
I got to the machine after the nomad process had already died, but I will get a dump next time it occurs live.

**Comment by justinwalz** [comment] 2017-01-26 21:29
See below - truncated output from `lsof -p <nomad pid>`

```
nomad   2449 root *810r      DIR             202,81     4096 2621596 /var/lib/ssi/nomad/alloc/32b3a6a3-7fde-418b-2006-7c65b8ec1660/alloc/logs
nomad   2449 root *811r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *812r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *813r      DIR             202,81     4096 2621596 /var/lib/ssi/nomad/alloc/32b3a6a3-7fde-418b-2006-7c65b8ec1660/alloc/logs
nomad   2449 root *814r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *815r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *816r      DIR             202,81     4096 2621596 /var/lib/ssi/nomad/alloc/32b3a6a3-7fde-418b-2006-7c65b8ec1660/alloc/logs
nomad   2449 root *817r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *818r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *819r      DIR             202,81     4096 2621596 /var/lib/ssi/nomad/alloc/32b3a6a3-7fde-418b-2006-7c65b8ec1660/alloc/logs
nomad   2449 root *820r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *821r      DIR             202,81     4096 2621596 /var/lib/ssi/nomad/alloc/32b3a6a3-7fde-418b-2006-7c65b8ec1660/alloc/logs
nomad   2449 root *822r      DIR             202,81     4096 2621596 /var/lib/ssi/nomad/alloc/32b3a6a3-7fde-418b-2006-7c65b8ec1660/alloc/logs
nomad   2449 root *823r      DIR             202,81     4096 2621596 /var/lib/ssi/nomad/alloc/32b3a6a3-7fde-418b-2006-7c65b8ec1660/alloc/logs
nomad   2449 root *824r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *825r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *826r      DIR             202,81     4096 2621596 /var/lib/ssi/nomad/alloc/32b3a6a3-7fde-418b-2006-7c65b8ec1660/alloc/logs
nomad   2449 root *827r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *828r      DIR             202,81     4096 2621596 /var/lib/ssi/nomad/alloc/32b3a6a3-7fde-418b-2006-7c65b8ec1660/alloc/logs
nomad   2449 root *829r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *830r      DIR             202,81     4096 2621596 /var/lib/ssi/nomad/alloc/32b3a6a3-7fde-418b-2006-7c65b8ec1660/alloc/logs
nomad   2449 root *831r      DIR             202,81     4096 2621596 /var/lib/ssi/nomad/alloc/32b3a6a3-7fde-418b-2006-7c65b8ec1660/alloc/logs
nomad   2449 root *832r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *833r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *834r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *835r      DIR             202,81     4096 2621596 /var/lib/ssi/nomad/alloc/32b3a6a3-7fde-418b-2006-7c65b8ec1660/alloc/logs
nomad   2449 root *836r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *837r      DIR             202,81     4096 2621596 /var/lib/ssi/nomad/alloc/32b3a6a3-7fde-418b-2006-7c65b8ec1660/alloc/logs
nomad   2449 root *838r      DIR             202,81     4096 2621596 /var/lib/ssi/nomad/alloc/32b3a6a3-7fde-418b-2006-7c65b8ec1660/alloc/logs
nomad   2449 root *839r      DIR             202,81     4096 2621596 /var/lib/ssi/nomad/alloc/32b3a6a3-7fde-418b-2006-7c65b8ec1660/alloc/logs
nomad   2449 root *840r      DIR             202,81     4096 2621596 /var/lib/ssi/nomad/alloc/32b3a6a3-7fde-418b-2006-7c65b8ec1660/alloc/logs
nomad   2449 root *841r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *842r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
nomad   2449 root *843r      DIR             202,81     4096 2621588 /var/lib/ssi/nomad/alloc/bd1fa749-7fa1-da62-faf1-8a3187ecc508/alloc/logs
```

**Comment by justinwalz** [comment] 2017-01-26 21:44
To add more context, I've attached the client logs. There are some errors about the logs API and too many open files included.

For what it's worth, nomad healed itself - both memory usage back under control and file descriptors back to normal without needing to restart.

[client-logs.tar.gz](https://github.com/hashicorp/nomad/files/733681/client-logs.tar.gz)

**Comment by dadgar** [comment] 2017-01-28 00:08
@justinwalz Okay re-opening this. Do you have any reproduction steps?

**Comment by sheldonkwok** [comment] 2017-03-14 18:03
We're still running into this issue every week. It makes the server unresponsive and forces reallocations for all of the jobs on it. This issue happens across all of our jobs intermittently when we attempt to fetch logs. It's difficult to reproduce but seems guaranteed to popup with enough logging requests over time on a job. The shared logging config is 

```
      LogConfig: {
        MaxFileSizeMB: 10, 
        MaxFiles: 10, 
      },  
```

**Comment by dadgar** [comment] 2017-03-14 20:51
@sheldonkwok I will make time to play with this soon. I was never able to reproduce however. Are you running both server/client on one machine?

**Comment by sheldonkwok** [comment] 2017-03-14 21:50
Thanks Alex. We are running 5 servers on their own machines and the clients are run separately as well.

**Comment by dadgar** [comment] 2017-04-20 20:57
Hey just tried the following and couldn't reproduce:

Ran this job:
```
job "example" {
  datacenters = ["us-west-2"]
  type = "service"

  group "cache" {
    count = 20

    restart {
      attempts = 60
      interval = "1m"
      delay = "1s"
      mode = "delay"
    }

    ephemeral_disk {
      size = 300
    }

    task "redis" {
      driver = "docker"
      config {
        image = "redis:3.2"
        command = "/bin/bash"
        args = ["-c", "base64 /dev/urandom | head -c 10000000"]
        port_map {
          db = 6379
        }
      }

      resources {
        cpu    = 500 # 500 MHz
        memory = 256 # 256MB
        network {
          mbits = 10
          port "db" {}
        }
      }
    }
  }
}
```

The job produces 10 MB of logs every few seconds and I streamed the logs of all 20 allocations to 3 different machines. I did this for 30+ minutes and transferred many GBs of logs from the client.

@sheldonkwok I did look at your logs and it looks like the streaming connection is held for 50+ minutes  but it is still streaming log stdout.0/stderr.0? Are the apps just not logging much?

I am going to try that as well and will report back.

**Comment by dadgar** [comment] 2017-04-20 21:49
Just tailed logs for over an hour and nothing as well.

@sheldonkwok any more detail on the logging pattern would be great.

**Comment by sheldonkwok** [comment] 2017-04-21 18:15
Hey @dadgar, I really appreciate the efforts you've spent trying to reproduce it! A normal logging pattern that we see is multiple people tailing the logs of multiple services at the same time for many hours. Some of these services may be the same service as well.

**Comment by dadgar** [comment] 2017-04-21 22:36
@sheldonkwok Hm unfortunately I did try that.

So I had 3 nodes each running ~7 allocations. I then was following the logs of all 20 allocations on 3 different machines for over an hour and a half.

I repeated this for two different workloads:

1) Small trickle of logs outputted by each allocation
2) 10 MBs of logs every few seconds.

Neither reproduced. Further when I stopped the logging, not a single extra FD was used (as in there was no leaking that would eventually cause a problem).

**Comment by sheldonkwok** [comment] 2017-04-24 17:06
Unfortunately, we cannot reproduce it effectively either. It generally happens once a week. We have thousands of allocations being created and running daily over hundreds of machines. In addition, users can be tailing thousands of them at once. Thanks again @dadgar

**Comment by dadgar** [comment] 2017-04-24 17:24
@sheldonkwok Do you retain Nomad log files? Would you be willing to run a debug adds some logging that may help get to the bottom of this?

**Comment by sheldonkwok** [comment] 2017-04-24 17:56
Sure, what do we set and how much extra logging does it generate?

**Comment by dadgar** [comment] 2017-04-24 18:38
@sheldonkwok You will set `log_level = "DEBUG"`. I don't know how much extra logging as I need to spend some time building the debug build. I may get to it this week. Will let you know.

**Comment by nickethier** [comment] 2020-04-18 02:37
@sheldonkwok I'm doing some cleanup of old issues and came across this one. The Nomad logging infrastructure has undergone many changes since this was originally opened. If you're still experiencing any problems would you please open a new issue?

Thanks!

**Closed by nickethier** 2020-04-18 02:37 UTC
Labels: api, bug, needs_investigation
