### ISSUE TITLE
Nomad 0.6.2 breaks status for jobs with dash in name

### ISSUE THREAD

**Issue by tino** [hashicorp/nomad#3155] opened 2017-09-03 20:19 UTC
This works in 0.6.0. Also find it strange that it tries to search for an alloc, as that is what `alloc-status` is for right? 

### Nomad version
Nomad v0.6.2

### Operating system and Environment details
Mac OS X Sierra; Ubuntu

### Issue
```
$ nomad status app-production
Error querying search with id: "Unexpected response code: 500 (3 error(s) occurred:\n\n* RPC failed to server 10.0.0.49:4647: rpc error: alloc lookup failed: index error: Input (without hyphens) must be even length\n* RPC failed to server 10.0.0.12:4647: rpc error: alloc lookup failed: index error: Input (without hyphens) must be even length\n* RPC failed to server 10.0.0.19:4647: rpc error: alloc lookup failed: index error: Input (without hyphens) must be even length)"
```

### Job file (if appropriate)
```
job "app-production" {
   ...
```

**Comment by dadgar** [comment] 2017-09-03 20:36
Hey this is a duplicate of https://github.com/hashicorp/nomad/issues/3118. It will be fixed in 0.6.3. Also status is now a general purpose command that can route to the appropriate status of any Nomad object. You can use `nomad job status` instead if you just want jobs.

**Closed by dadgar** 2017-09-03 20:36 UTC
