### ISSUE TITLE
[feature request or bug] Guarantee unique allocation index

### ISSUE THREAD

**Issue by dukeland9** [hashicorp/nomad#3698] opened 2017-12-29 03:37 UTC
This is a feature request or bug report after this issue: https://github.com/hashicorp/nomad/issues/3593
After that issue, there are still duplicate indices for allocations from time to time.

For example, in the following job:
https://github.com/hashicorp/nomad/files/1574186/allocations_0.7.1.txt
Allocation 36, 19 and 25 were scheduled twice.

If we can't guarantee the uniqueness the alloc index, why bother offer such variable interpolation on https://www.nomadproject.io/docs/runtime/interpolation.html? It's very misleading and useless.
![image](https://user-images.githubusercontent.com/4850727/34428882-1fbacfb2-ec8c-11e7-8c6a-6723eaa930c1.png)

**Comment by preetapan** [comment] 2018-01-04 21:02
@dukeland9 we are back after the break and looking at this again. Would like to confirm one thing - in your job specification did you ask for 100 allocs? Would be helpful if you posted the job specification here.

**Comment by preetapan** [comment] 2018-01-04 22:36
@dukeland9 After some more digging into things, we found that there are two different things happening here:

**Reusing the same alloc index on a lost allocation that was replaced** - that is expected behavior. Nomad will use indexes starting from 0 to desired_count -1. When one of those need to be replaced, like 19, 25 and 36 in your example because it lost its connection to the node they were on, the scheduler will reuse that alloc index to create a replacement. 

**Creating the right number of allocations** - We did find a bug in how we count whether a batch job was successfully allocated. This resulted in the scheduler *not* creating allocations with indexes 97, 98 and 99 to make a desired total count of 100. The bug was because it incorrectly counted the replaced allocations (19, 25, 36) against the total number of desired running allocations(100). We have a fix for this, will be commenting shortly with a binary to test this. 

Thanks once again for stress testing this in your environment.

**Comment by dadgar** [comment] 2018-01-04 22:46
[nomad.zip](https://github.com/hashicorp/nomad/files/1604954/nomad.zip)
Hey here is a Linux AMD64 binary that includes the changes from https://github.com/hashicorp/nomad/pull/3717. If you want to give that a test that would be great!

**Comment by dukeland9** [comment] 2018-01-05 06:54
@preetapan Thank you for investigating this issue!

**Comment by dukeland9** [comment] 2018-01-05 06:57
@dadgar I tried to run your binary, but it got "error while loading shared libraries: liblxc.so.1: cannot open shared object file: No such file or directory". I want to confirm that the binary was compiled correctly. I don't think we had lxc dependency before.

**Comment by preetapan** [comment] 2018-01-05 15:11
@dukeland9 can you try [this one](https://s3.amazonaws.com/nomad-test-binary/nomad.zip) ? Tried building one for you on my Linux box. As far as I can tell, this does not depend on liblxc.so (Added some output from ldd below)

```
preetha@preetha-work ~/nomad/bin (master) $ldd nomad
	linux-vdso.so.1 =>  (0x00007fff60bfd000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe9a7b1c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe9a7752000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe9a7d39000)
```

**Comment by dukeland9** [comment] 2018-01-06 14:35
@preetapan I can't access your file from Amazon S3 due to the blocking issue in China. Would you please provide one on github like dadgar? Thanks a lot.

BTW, I only have to update the binaries on the servers right?

**Comment by dukeland9** [comment] 2018-01-07 07:58
@preetapan Never mind. I managed to build one myself. I replaced the binary on the servers and tested running two jobs with node draining situation. It seemed the system worked correctly.
I'll watch the system running a few more days to give more solid feedback then.

**Comment by dukeland9** [comment] 2018-01-10 01:45
The system has been running as expected for several days. Thank @preetapan and @dadgar for fixing this!

**Closed** 2018-01-10 02:16 UTC
Labels: bug, scheduling
