### ISSUE TITLE
taskConfig.NodeName is empty when implementing DriverPlugin

### ISSUE THREAD

**Issue by sjjian** [hashicorp/nomad#10947] opened 2021-07-27 09:51 UTC
### Nomad version
Nomad v1.1.2

### Issue
We using Nomad Plugins to manage our task driver, and now I need to get the NodeName in the our plugin. So, when I implement `DriverPlugin.StartTask`, The TaskConfig already contains field `NodeName`, but the value is empty when our task is started. 

#### Expected Result
I can get NodeName 
#### Actual Result
TaskConfig.NodeName is empty

**Comment by tgross** [comment] 2022-08-22 14:53
Hi @sjjian! I'm doing some issue cleanup and discovered this issue fell thru the cracks somehow. I've checked this with both Nomad 1.1.2 and the current HEAD and I can't reproduce. With the following patch:

```diff
diff --git a/drivers/docker/driver.go b/drivers/docker/driver.go
index 0aa993845..380a6f857 100644
--- a/drivers/docker/driver.go
+++ b/drivers/docker/driver.go
@@ -244,6 +244,9 @@ func (d *Driver) RecoverTask(handle *drivers.TaskHandle) error {
 }

 func (d *Driver) StartTask(cfg *drivers.TaskConfig) (*drivers.TaskHandle, *drivers.DriverNetwork, error) {
+
+       d.logger.Info("StartTask => getting TaskConfig", "NodeID", cfg.NodeID, "NodeName", cfg.NodeName)
+
        if _, ok := d.tasks.Get(cfg.ID); ok {
                return nil, nil, fmt.Errorf("task with ID %q already started", cfg.ID)
        }
```

I get log lines like the following:


```
    2022-08-22T14:43:40.352Z [INFO]  client.driver_mgr.docker: StartTask => getting TaskConfig: driver=docker NodeID=9732adb1-526b-c220-8064-408fc87c8796 NodeName=node01
```

Hopefully you've got this one figured out by now, but I'm going to close this issue out as unreproducible at this point. If you've got new issues that come up, please feel free to open an issue and we'll make sure those will get looked at. Thanks!

**Closed by tgross** 2022-08-22 14:53 UTC
Labels: type/bug, theme/driver
