### ISSUE TITLE
Nomad can't unpack tar.gz artifact archives with directories

### ISSUE THREAD

**Issue by andreynpetrov** [hashicorp/nomad#2514] opened 2017-04-01 10:11 UTC
### Nomad version
Nomad v0.5.2

### Reproduction steps
Prepare  tar.gz artifact archive with directories and use artifact stanza 

artifact {
  source = "https://***/celery/mytest1.tar.gz"
}

### Nomad alloc-status
Recent Events:
Time                   Type                      Description
03/31/17 23:54:00 UTC  Restarting                Task restarting in 10m34.631583511s
03/31/17 23:54:00 UTC  Failed Artifact Download  failed to download artifact "https://***/celery/mytest1.tar.gz": GET error: open /var/lib/nomad/alloc/987838d5-e81d-00d9-8696-03873a846726/stage-celery/local/tmp/test: no such file or directory
03/31/17 23:54:00 UTC  Downloading Artifacts     Client is downloading artifacts
03/31/17 23:54:00 UTC  Received                  Task received by client

**Comment by dadgar** [comment] 2017-04-02 00:08
Hey @andreynpetrov,

I could not reproduce on either 0.5.2 or 0.5.6. Here is what I did.

```
# inside Nomad source code directory
$ tar -czf client.tar.gz client
# Start a web server to pull the image
$ python -m SimpleHTTPServer
```

Then I started nomad: `$ sudo nomad agent -dev`

And ran this job:

```
job "test" {
  datacenters = ["dc1"]
  group "test" {
    task "test" {
      driver = "docker"
      config {
        image = "redis:3.2"
        port_map {
          db = 6379
        }
      }

      artifact {
        source = "http://127.0.0.1:8000/client.tar.gz"
      }

      resources {
        network {
          mbits = 10
          port  "service_port"{}
        }
      }
    }
  }
}
```

Here were the results:

```
$ nomad run example.nomad
==> Monitoring evaluation "afaeb063"
    Evaluation triggered by job "test"
    Allocation "b5a6d0db" created: node "564daec4", group "test"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "afaeb063" finished with status "complete"

$ nomad alloc-status b5
ID                  = b5a6d0db
Eval ID             = afaeb063
Name                = test.test[0]
Node ID             = 564daec4
Job ID              = test
Client Status       = running
Client Description  = <none>
Desired Status      = run
Desired Description = <none>
Created At          = 04/02/17 00:02:32 UTC

Task "test" is "running"
Task Resources
CPU        Memory          Disk     IOPS  Addresses
3/100 MHz  6.3 MiB/10 MiB  300 MiB  0     service_port: 127.0.0.1:21942

Recent Events:
Time                   Type                   Description
04/02/17 00:02:33 UTC  Started                Task started by client
04/02/17 00:02:32 UTC  Downloading Artifacts  Client is downloading artifacts
04/02/17 00:02:32 UTC  Task Setup             Building Task Directory
04/02/17 00:02:32 UTC  Received               Task received by client

$ nomad fs b5 test/local/
Mode        Size     Modified Time          Name
drwxr-xr-x  4.0 KiB  04/02/17 00:02:33 UTC  client/

$ nomad fs b5 test/local/client
Mode        Size     Modified Time          Name
-rw-r--r--  20 KiB   04/02/17 00:02:32 UTC  alloc_runner.go
-rw-r--r--  23 KiB   04/02/17 00:02:32 UTC  alloc_runner_test.go
drwxr-xr-x  4.0 KiB  04/02/17 00:02:32 UTC  allocdir/
-rw-r--r--  70 KiB   04/02/17 00:02:32 UTC  client.go
-rw-r--r--  23 KiB   04/02/17 00:02:32 UTC  client_test.go
drwxr-xr-x  4.0 KiB  04/02/17 00:02:32 UTC  config/
-rw-r--r--  13 KiB   04/02/17 00:02:32 UTC  consul_template.go
-rw-r--r--  24 KiB   04/02/17 00:02:32 UTC  consul_template_test.go
drwxr-xr-x  4.0 KiB  04/02/17 00:02:33 UTC  driver/
drwxr-xr-x  4.0 KiB  04/02/17 00:02:33 UTC  fingerprint/
-rw-r--r--  19 KiB   04/02/17 00:02:33 UTC  fingerprint.tar.gz
-rw-r--r--  9.1 KiB  04/02/17 00:02:33 UTC  gc.go
-rw-r--r--  10 KiB   04/02/17 00:02:33 UTC  gc_test.go
drwxr-xr-x  4.0 KiB  04/02/17 00:02:33 UTC  getter/
-rw-r--r--  6.2 KiB  04/02/17 00:02:33 UTC  restarts.go
-rw-r--r--  5.0 KiB  04/02/17 00:02:33 UTC  restarts_test.go
-rw-r--r--  2.3 KiB  04/02/17 00:02:33 UTC  serverlist.go
-rw-r--r--  3.2 KiB  04/02/17 00:02:33 UTC  serverlist_test.go
drwxr-xr-x  4.0 KiB  04/02/17 00:02:33 UTC  stats/
drwxr-xr-x  4.0 KiB  04/02/17 00:02:33 UTC  structs/
-rw-r--r--  45 KiB   04/02/17 00:02:33 UTC  task_runner.go
-rw-r--r--  43 KiB   04/02/17 00:02:33 UTC  task_runner_test.go
drwxr-xr-x  4.0 KiB  04/02/17 00:02:33 UTC  testutil/
-rw-r--r--  3.2 KiB  04/02/17 00:02:33 UTC  util.go
-rw-r--r--  2.3 KiB  04/02/17 00:02:33 UTC  util_test.go
drwxr-xr-x  4.0 KiB  04/02/17 00:02:33 UTC  vaultclient/
```

Can you provide an example file and tar that produces this error. Until then I am going to close this.

**Closed by dadgar** 2017-04-02 00:08 UTC

**Comment by andreynpetrov** [comment] 2017-04-02 13:06
Please try with this url [http://smartbrood.com/docker/workers.tar.gz](url)

Recent Events:
Time                   Type                      Description
04/02/17 13:01:10 UTC  Restarting                Task restarting in 1m1.16575679s
04/02/17 13:01:10 UTC  Failed Artifact Download  failed to download artifact "http://smartbrood.com/docker/workers.tar.gz": GET error: open /var/lib/nomad/alloc/75b819e4-180a-0b6f-a500-0345e52da345/stage-celery/local/workers/mq/__init__.py: no such file or directory
04/02/17 13:01:10 UTC  Downloading Artifacts     Client is downloading artifacts
04/02/17 13:01:10 UTC  Received                  Task received by client

**Comment by dadgar** [comment] 2017-04-04 00:04
@andreynpetrov How are you creating that tar? It is because the file is listed in the tar before its parent directories.

**Comment by dadgar** [comment] 2017-04-04 01:20
@andreynpetrov I just went ahead and fixed the issue and made a pull request to the underlying library. If that gets merged we will vendor it and the next nomad release should fix this.
