### ISSUE TITLE
Segmentation fault on $ nomad run

### ISSUE THREAD

**Issue by samber** [hashicorp/nomad#2637] opened 2017-05-12 07:56 UTC
In relation with #2635, I ran multiple times ```nomad run example.nomad``` on the same job. I got the following segfault:

(nomad - master branch)

```
    2017/05/12 09:44:37.622288 [DEBUG] http: Request /v1/jobs?region=global (795.455µs)
    2017/05/12 09:44:37.622294 [DEBUG] worker: dequeued evaluation 88cf62ee-b28d-512d-7182-f253aa0c4bd9
    2017/05/12 09:44:37.622407 [DEBUG] sched: <Eval '88cf62ee-b28d-512d-7182-f253aa0c4bd9' JobID: 'example'>: allocs: (place 0) (update 1) (migrate 0) (stop 0) (ignore 0) (lost 0)
    2017/05/12 09:44:37.622963 [DEBUG] sched: <Eval '88cf62ee-b28d-512d-7182-f253aa0c4bd9' JobID: 'example'>: 1 in-place updates of 1
    2017/05/12 09:44:37.623762 [DEBUG] worker: submitted plan for evaluation 88cf62ee-b28d-512d-7182-f253aa0c4bd9
    2017/05/12 09:44:37.623801 [DEBUG] sched: <Eval '88cf62ee-b28d-512d-7182-f253aa0c4bd9' JobID: 'example'>: setting status to complete
    2017/05/12 09:44:37.623814 [DEBUG] client: updated allocations at index 15 (total 1) (pulled 1) (filtered 0)
    2017/05/12 09:44:37.623854 [DEBUG] client: allocs: (added 0) (removed 0) (updated 1) (ignore 0)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x451d1f6]

goroutine 272 [running]:
github.com/hashicorp/nomad/nomad/structs.(*Job).LookupTaskGroup(0x0, 0xc42032402a, 0x5, 0xc4205845d8)
	/Users/samuelberthe/go/src/github.com/hashicorp/nomad/nomad/structs/structs.go:1381 +0x26
github.com/hashicorp/nomad/client.(*TaskRunner).handleUpdate(0xc420584480, 0xc42083c000, 0x0, 0xc420666401)
	/Users/samuelberthe/go/src/github.com/hashicorp/nomad/client/task_runner.go:1519 +0x59
github.com/hashicorp/nomad/client.(*TaskRunner).run(0xc420584480)
	/Users/samuelberthe/go/src/github.com/hashicorp/nomad/client/task_runner.go:1105 +0x663
github.com/hashicorp/nomad/client.(*TaskRunner).Run(0xc420584480)
	/Users/samuelberthe/go/src/github.com/hashicorp/nomad/client/task_runner.go:581 +0x556
created by github.com/hashicorp/nomad/client.(*AllocRunner).Run
	/Users/samuelberthe/go/src/github.com/hashicorp/nomad/client/alloc_runner.go:688 +0x9d9
```

I can reproduce the failure. It always fails after less than 5 ```nomad run example.nomad```.

When agent failure occures, the cli displays the following error:

```
==> No evaluation with id "bbf9c10c-d8a6-a021-1afa-284870ec9299" found
```

**Comment by schmichael** [comment] 2017-05-12 16:21
Thanks for the bug report! I'm pretty sure this is a dupe of #2605, so I'm going to close it for now to keep everything in one place.

**Closed by schmichael** 2017-05-12 16:21 UTC
Labels: bug, crash
