### ISSUE TITLE
Upgrade go-getter

### ISSUE THREAD

**Issue by prologic** [hashicorp/nomad#5445] opened 2019-03-20 03:31 UTC
Need to upgrade the version of [go-getter](https://github.com/hashicorp/go-getter) used to include the fix in hashicorp/go-getter#171

Also somewhat related (*because of dependency management*) #5444

**Comment by ExalDraen** [comment] 2019-05-21 06:12
The new version of go-getter now also supports GCS as a storage backend and contains a number of fixes, e.g. for SCP style URLs when using the git provider.

I'd be happy to help here if needed (though I'm not sure what help would be needed besides bumping the version and testing?)

**Comment by cgbaker** [comment] 2019-05-21 17:13
There's an outstanding PR for updating go-getter: #5446 
I'll talk to the team about getting this in.

**Comment by prologic** [comment] 2019-05-22 01:29
The status on this is "on hold". I haven't had the bandwidth to do the work stated in the comments. Summary of what's needed as follows:

* Rewrite the go-getter patch using securejoin
* Add tests that demonstrate it is impossible to escape the chroot'd path

**Comment by ExalDraen** [comment] 2019-05-22 03:22
Ah, that does seem like a bit more effort than I thought! I'd like to help where I can but it will take some learning to familiarize myself with the Nomad build and tests. It will be easier for me to help change go-getter which #5446 suggests is required. 

@prologic 
When you mention `securejoin` do you mean https://github.com/cyphar/filepath-securejoin? Are you intending to update go-getter to use securejoin instead of `filepath.join`?

**Comment by prologic** [comment] 2019-05-22 03:40
Yes! See [this comment](https://github.com/hashicorp/go-getter/issues/60#issuecomment-480102747) and [this one](https://github.com/hashicorp/go-getter/issues/60#issuecomment-480429214)

**Comment by aclowkey** [comment] 2019-07-19 10:48
Any progress with this?
This is a major blocker for migrating to Nomad, if artifacts are stored in GCS.

**Comment by DrorBuhnik** [comment] 2019-10-22 07:41
It seems that just updating go-getter isn't enough
https://github.com/hashicorp/nomad/blob/ac8fa9fe1dbbdab693e23569e9dde84441cd90fc/client/allocrunner/taskrunner/getter/getter.go#L21
should have 'gcs' in the supported list
```diff
-       supported = []string{"http", "https", "s3", "hg", "git"}
+       supported = []string{"http", "https", "s3", "hg", "git", "gcs"}
```

**Comment by langmartin** [comment] 2019-11-20 17:21
go-getter has been upgraded to support GCS as an artifact source, but still does not support symlinks in tarballs. I'm closing the rest of this issue as duplicate of #2292

**Closed by langmartin** 2019-11-20 17:21 UTC
Labels: vendor-update
