### ISSUE TITLE
raw_exec fails when the "user" is a non-root user (version 0.9.0 beta3)

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#5396] opened 2019-03-06 06:58 UTC
### Nomad version
Nomad v0.9.0-beta3 (2f55f78b21a5e55ab122f2c1e1ed1ec21fde9566)

### Operating system and Environment details
CentOS 7.6 + latest updates
NVIDIA CUDA setup  for GPU related app.

### Issue
My Nomad agent is running as `root`.
When I run the example job, and set the "user" field to a non-root user, it fails with the error:
```
Recent Events:
Time                       Type            Description
2019-03-06T12:15:04+05:30  Not Restarting  Error was unrecoverable
2019-03-06T12:15:04+05:30  Driver Failure  failed to launch command with executor: rpc error: code = Unknown desc = failed to start command path="/bin/sleep" --- args=["/bin/sleep" "600"]: fork/exec /bin/sleep: permission denied
2019-03-06T12:15:04+05:30  Task Setup      Building Task Directory
2019-03-06T12:15:04+05:30  Received        Task received by client
```

### Reproduction steps
Commenting out the `user` directive works (of course), but the process runs as root.
I want to the run the process as `myappuser`, which doesn't work!

### Job file (if appropriate)
I have modified the default example job for `raw_exec`
(this is a minimal example of the real nvidia cuda job)

```hcl
job "example" {
  datacenters = ["dc1"]

  type = "batch"

  constraint {
    attribute = "${node.class}"
    value     = "mymachine-2"
  }

  group "cache" {
    task "redis" {
      driver = "raw_exec"
      user = "myappuser"

      config {
        command = "/bin/sleep"
        args = ["600"]
      }

      resources {
        cpu    = 500
        memory = 256
        network {
          mbits = 10
          port "db" {}
        }
      }
    }
  }
}
```

I haven't tested this with 0.8.7, though it wouldn't be much help as I want to the nvidia gpu related things.

Regards,
Shantanu

**Comment by preetapan** [comment] 2019-03-06 14:26
@shantanugadgil this is expected behavior, by default the raw_exec driver creates a freezer cgroup to allow terminating child tasks spawned from the raw exec job correctly. To disable this, you can use the new `plugin` stanza added in 0.9 and set `no_cgroups` to true. 
https://www.nomadproject.io/docs/drivers/raw_exec.html#no_cgroups. I just tested your jobs with that and it ran fine 

In 0.8.X the same thing can be done via the `options` stanza inside the `client` stanza. See the above docs for details on both ways of doing it.

**Comment by schmichael** [comment] 2019-03-07 14:38
Your example job just worked for with the dev agent running as root on Ubuntu 18.10 (after I commented out the constraint), so I don't think the freezer is involved.

Let us know if you have any more ideas on how to reproduce this!

**Comment by shantanugadgil** [comment] 2019-03-07 16:14
@schmichael  I haven't been able to verify this, I will try with the agent setting and ping back that it works in  the cluster mode.

**Comment by shantanugadgil** [comment] 2019-03-11 13:05
hi @schmichael @preetapan 
This works fine in "-dev" mode when I start nomad as the `root` user and set the "user" field to a non-root user.

This is not working in the clustered mode.

The relevant bits in my client config file looks like the following (I have tried with both the old and the new syntax). Neither works for me.

```hcl
client {
  enabled           = true
...

#  options = {
#    "driver.raw_exec.enable" = "1"
#    "driver.raw_exec.no_cgroups" = "1"
#  }

  reserved {
    cpu            = 500
    memory         = 512
    disk           = 1024
  }
}

plugin "raw_exec" {
  config {
    enabled = true
    no_cgroups = true
  }
}


```

**Comment by schmichael** [comment] 2019-03-11 14:36
I'm still having trouble reproducing this.

**Comment by schmichael** [comment] 2019-03-11 14:39
I'm still having trouble reproducing this. Is there anything helpful in the `${alloc_dir}/${task_name}/executor.out` file?

Does the user have execute permissions on the specified command? Can you try with the `nobody` user and `/bin/sleep`?

Can you try setting `log_level = "TRACE"` on the target client node to see if there's anything useful?

If we can not find the root cause we may be able to at least find a place to add more logging.

**Comment by shantanugadgil** [comment] 2019-03-11 14:58
I switched the username to `nobody`, the `executor.out` has the following:

```
{"@level":"debug","@message":"plugin address","@timestamp":"2019-03-11T20:22:29.089380+05:30","address":"/tmp/plugin192162774","network":"unix"}
{"@level":"debug","@message":"launching command","@module":"executor","@timestamp":"2019-03-11T20:22:29.090167+05:30","args":"600","command":"/bin/sleep"}
{"@level":"debug","@message":"running command as user","@module":"executor","@timestamp":"2019-03-11T20:22:29.090199+05:30","user":"nobody"}
{"@level":"debug","@message":"setting process user","@module":"executor","@timestamp":"2019-03-11T20:22:29.090655+05:30","additional_groups":[0,99],"group":99,"user":99}
```

The status output of the allocation has:
```
Recent Events:
Time                       Type            Description
2019-03-11T20:22:29+05:30  Not Restarting  Error was unrecoverable
2019-03-11T20:22:29+05:30  Driver Failure  failed to launch command with executor: rpc error: code = Unknown desc = failed to start command path="/bin/sleep" --- args=["/bin/sleep" "600"]: fork/exec /bin/sleep: permission denied
2019-03-11T20:22:28+05:30  Task Setup      Building Task Directory
2019-03-11T20:22:28+05:30  Received        Task received by client

```

I will now set `log_level` to `TRACE` and capture the logs.

**Comment by shantanugadgil** [comment] 2019-03-11 15:20
btw, explicitly doing an `su - myappuser` and then executing `/bin/sleep 600` works
also the following works as well `su - myappuser -c "/bin/sleep 600"`

[sleep_trace.log](https://github.com/hashicorp/nomad/files/2952874/sleep_trace.log)

**Comment by preetapan** [comment] 2019-03-13 15:02
@shantanugadgil we reproduced this after starting a raw exec task with the user not having execute permissions on the Nomad client's allocation directory . This was previously reported in #2723 so I am going to close this as a duplicate. 

As a workaround, if you give the user you are trying to run as execute permissions to the data directory on the client you should see this job work again. 

Thanks for providing us a job spec to try, that always helps with reproduction steps.

**Closed by preetapan** 2019-03-13 15:02 UTC

**Comment by shantanugadgil** [comment] 2019-03-14 02:54
Thanks for this. I'll try the above workaround.

As my Nomad is a systemd service, what comes to mind is the following as well:
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#UMask=

Regards,
Shantanu Gadgil
