### ISSUE TITLE
Periodic job config error "unknown time zone" v1.1.3

### ISSUE THREAD

**Issue by daledude** [hashicorp/nomad#10978] opened 2021-07-30 21:28 UTC
### Nomad version
Nomad v1.1.3 (8c0c8140997329136971e66e4c2337dfcf932692)

### Operating system and Environment details
Ubuntu 20.04.2 LTS

### Issue
Periodic config produces error no matter what time_zone value I use.
 
```
Error during plan: Unexpected response code: 500 (rpc error: 1 error occurred:
	* 1 error occurred:
	* Invalid time zone "America/Los_Angeles": unknown time zone America/Los_Angeles
```

```
  periodic {
    cron             = "30 21 * * *"
    prohibit_overlap = true
    time_zone        = "America/Los_Angeles"
  }
```

**Comment by notnoop** [comment] 2021-07-31 00:35
Nomad currently consults the host `tzdata` for looking up time zone info. Ubuntu has the `tzdata` package available: https://packages.ubuntu.com/focal/tzdata . Can you check if it's installed and try again?

**Comment by daledude** [comment] 2021-07-31 02:04
Thanks @notnoop. I have that installed.

```
# dpkg -l tzdata
||/ Name           Version              Architecture Description
+++-==============-====================-============-=======================================
ii  tzdata         2021a-0ubuntu0.20.04 all          time zone and daylight-saving time data
```

```
# ls -l /etc/localtime
lrwxrwxrwx 1 root root 41 May  8 10:05 /etc/localtime -> ../usr/share/zoneinfo/America/Los_Angeles
```

**Comment by tgross** [comment] 2022-08-22 16:34
Apologies that this issue accidentally got dropped @daledude. I was also unable to reproduce. I suspect that the problem here is that TZ data symlink and possibly the permissions to that file if you weren't running Nomad as root (which is required for clients but not servers). 

```
$ ll /etc/localtime
lrwxrwxrwx 1 root root 27 Mar 30 13:59 /etc/localtime -> /usr/share/zoneinfo/Etc/UTC
$ ll /usr/share/zoneinfo/Etc/UTC
-rw-r--r-- 1 root root 118 Mar 21 20:26 /usr/share/zoneinfo/Etc/UTC
```

<details><summary>jobspec</summary>

```hcl
job "example" {
  type        = "batch"
  datacenters = ["dc1"]

  periodic {
    cron             = "30 21 * * *"
    prohibit_overlap = true
    time_zone        = "America/Los_Angeles"
  }

  group "group" {

    task "task" {

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "/bin/sh"
        args    = ["-c", "echo \"running at $(date)\"; sleep 1"]
      }

      resources {
        cpu    = 64
        memory = 64
      }

    }
  }
}
```

</details>

Results in the following successful plan:

```
$ nomad job plan ./jobs/periodic.nomad
+ Job: "example"
+ Task Group: "group" (1 create)
  + Task: "task" (forces create)

Scheduler dry-run:
- All tasks successfully allocated.
- If submitted now, next periodic launch would be at 2022-08-22T21:30:00-07:00 (11h59m3s from now).

Job Modify Index: 0
To submit the job with version verification run:

nomad job run -check-index 0 ./jobs/periodic.nomad

When running the job with the check-index flag, the job will only be run if the
job modify index given matches the server-side version. If the index has
changed, another user has modified the job and the plan's results are
potentially invalid.
```


As this has been open for a while without any additional information or reproduction, I'm going to close it. Apologies again @daledude

**Closed by tgross** 2022-08-22 16:34 UTC
Labels: type/bug, theme/batch
