### ISSUE TITLE
Nomad can allocate port which is already occupied by some outgoing connection

### ISSUE THREAD

**Issue by drscre** [hashicorp/nomad#2500] opened 2017-03-29 16:31 UTC
Nomad v0.5.5

Sometimes services, scheduled by Nomad, refuses to start and complain, that "port is already in use".

Looks like Nomad can allocate a port which is already occupied by outgoing connection.

For example, this is a connection to consul
```
tcp        0      0 127.0.0.1:38151         127.0.0.1:8500          ESTABLISHED 0          11388       1923/nomad
```

And Nomad happened to allocate the same port to a service, so it was not able to start:
```
2017/03/29 16:11:14 [emerg] 22#22: bind() to 0.0.0.0:38151 failed (98: Address already in use)
```

**Comment by schmichael** [comment] 2017-03-29 17:00
Fairly certain this is the same root cause of #2402

**Comment by schmichael** [comment] 2017-03-29 17:48
Going to treat this as a dupe of #2402 and close this one. Thanks for the report!

**Closed by schmichael** 2017-03-29 17:48 UTC
Labels: bug, client, networking
