### ISSUE TITLE
Getting ‘Not Authorized’ when trying to view files via UI - ACL's enabled

### ISSUE THREAD

**Issue by robsonj** [hashicorp/nomad#12217] opened 2022-03-08 14:07 UTC
### Nomad version
1.2.5

### Operating system and Environment details
CentOS 8

### Issue
I have ACL’s enabled and am using a token with the following policy assigned…

`namespace “ABC” {
policy = “read”
capabilities = [“submit-job”, “read-logs”, “read-fs”]
}`

When I click on the 'files button within the allocation for a job in namespace ABC, I am greeted with a not authorized error. This works fine using the master token.

Am I missing a policy capability to allow for thee viewing of the stderr, stdout log files under the allocation files section?

### Reproduction steps
set nomad token to the one generated for the ACL, try to navigate to the files section of the allocation, receive not authorized error.

#### Expected Result
Be able to view the files section of the allocation

#### Actual Result
not authorized error

**Comment by tgross** [comment] 2022-03-08 14:36
Hi @robsonj! The ACLs apply to specific API endpoints. The UI is a richer experience than the CLI, so it has to hit a whole bunch of API endpoints and if just one ACL is missing the whole page ends up getting the "not authorized" error.

You can usually debug which one is the problem by opening the browser dev tools and seeing which API endpoint is returning 403. I took your policy and tried it myself:

```
$ nomad namespace apply ABC
Successfully applied namespace "ABC"!

$ nomad acl policy apply ABC ./test.hcl
Successfully wrote "ABC" ACL policy!

$ nomad acl policy info ABC
Name        = ABC
Description = <none>
Rules       = namespace "ABC" {
  policy       = "read"
  capabilities = ["submit-job", "read-logs", "read-fs"]
}
CreateIndex = 28
ModifyIndex = 28

$ nomad acl token create -name=test -policy=ABC
Accessor ID  = 6e4c571e-20e6-2de5-35e6-663d14fe56b3
Secret ID    = 92440b36-5cb4-3ef4-2e58-4ac19042972e
Name         = test
Type         = client
Global       = false
Policies     = [ABC]
Create Time  = 2022-03-08 14:28:09.596642614 +0000 UTC
Create Index = 42
Modify Index = 42
```

Then I create a job in the `ABC` namespace:



```
$ nomad job run ./job.nomad
==> 2022-03-08T09:25:31-05:00: Monitoring evaluation "712c471f"
    2022-03-08T09:25:31-05:00: Evaluation triggered by job "example"
==> 2022-03-08T09:25:32-05:00: Monitoring evaluation "712c471f"
    2022-03-08T09:25:32-05:00: Evaluation within deployment: "034ac6a7"
    2022-03-08T09:25:32-05:00: Allocation "6faab3d0" created: node "e03fea30", group "web"
...
```

Then checked the UI using the token I created above by visiting http://localhost:4646/ui/allocations/6faab3d0-0975-494a-ff2f-0c91af81ca18/taskname. In my browser's dev tools I'm seeing a 403 for http://localhost:4646/v1/node/e03fea30-374f-459b-a632-6ac02f739f2f

If I add the following policy, the page works just fine:

```hcl
node {
  policy = "read"
}
```

Generally speaking if you want the experience of using the UI to be nice, I'd recommend adding the following to your policy as well:

```hcl
agent {
  policy = "read"
}
```

Hopefully that gets your sorted out @robsonj. This issue is largely a duplicate of https://github.com/hashicorp/nomad/issues/11763 so I'm going to close this out, but please let us know if you run into any related trouble and we'll be happy to help you out.

**Closed by tgross** 2022-03-08 14:36 UTC
Labels: type/bug

**Comment by robsonj** [comment] 2022-03-08 16:09
Thankyou @tgross for the detailed response. I will try adjusting the policy and let you know how it goes. Much appreciated!
