### ISSUE TITLE
CSI: make readiness probe timeout configurable to support faulty plugins

### ISSUE THREAD

**Issue by calvarado2004** [hashicorp/nomad#13179] opened 2022-05-30 22:03 UTC
### Nomad version
Output from `nomad version`
Nomad v1.3.1 (2b054e38e91af964d1235faa98c286ca3f527e56)
### Operating system and Environment details
Ubuntu Linux 20.04
### Issue
CSI Plugin on Nomad 1.3 have a very short timeout. Affects Portworx which can take 15 minutes to be installed.
### Reproduction steps
Try to install Portworx on Nomad as a job following this guide:
https://docs.portworx.com/install-with-other/nomad/installation/install-as-a-nomad-job/

#### Expected Result
Portworx running on Nomad
#### Actual Result
CSI plugin timeout

**Comment by tgross** [comment] 2022-05-31 12:37
Hi @calvarado2004 can you provide the specific log line you're seeing? It sounds like you're saying that after the plugin container starts that it takes 15min for the plugin to successfully respond to probes. But if that's the case, there's almost certainly something broken with your plugin's setup (or possibly the Portworx plugin has a bad bug; it definitely should not be taking 15min to start!). If so, can you please provide the full plugin allocation logs?

**Comment by tgross** [comment] 2022-05-31 20:30
That sounds like a reasonable workaround @RickyGrassmuck. Thanks! 

But we should probably make the plugin supervisor timeout (ref [`plugin_supervisor_hook.go#L254-L256`](https://github.com/hashicorp/nomad/blob/v1.3.1/client/allocrunner/taskrunner/plugin_supervisor_hook.go#L254-L256)) configurable by the end user. This has some unfortunate side-effects in terms of trying to reliably detect when the plugin is broken vs slow, but at least we can give the operator a knob to adjust.

**Comment by ggriffiths** [comment] 2022-06-10 17:52
@RickyGrassmuck Yes that's still accurate, thanks for adding that context here. It normally only takes a few minutes to pull the image/unpack/start PX up depending on network speed. 

@tgross is anyone working on this issue? If not, I can assist here.

Where were you thinking of making the timeout configurable? In the CSI Plugin stanza?

**Comment by tgross** [comment] 2022-06-10 18:08
> @tgross is anyone working on this issue? If not, I can assist here.

It's on our short-term todo list but no one is immediately assigned to it. I'd be happy to review a PR if you're interested. 

> Where were you thinking of making the timeout configurable? In the CSI Plugin stanza?

Yeah, that seems like the right place for it and that struct is available where the readiness probe timeout happens without too much trouble.

**Comment by ggriffiths** [comment] 2022-06-10 18:10
Sounds good, I'll send a PR soon.

**Closed** 2022-06-14 14:04 UTC
Labels: type/enhancement, theme/storage

**Comment by ggriffiths** [comment] 2022-06-14 17:10
Awesome! Can we backport this to 1.1.x and 1.2.x as well? We hit this on Nomad 1.1.14 originally as well.

**Comment by tgross** [comment] 2022-06-14 17:38
We don't generally backport new features. But I get that it makes compatibility with Portworx tricky. Lemme see what it would take to get the backport thru (it's a headache because the code changes out from under us).

**Comment by tgross** [comment] 2022-06-14 18:05
Ah yeah that's right, the timeout was backported, so that makes it a regression to fix.

**Comment by ggriffiths** [comment] 2022-06-14 18:49
Awesome, thank you @tgross!
