### ISSUE TITLE
Update stanza not respected when changing docker image

### ISSUE THREAD

**Issue by BSick7** [hashicorp/nomad#2487] opened 2017-03-27 19:53 UTC
```
CoreOS 1235.12.0
Docker 1.12.6
Nomad v0.5.5
```

### Issue

There are 2 issues:
- 1. The update stanza does not appear to be respected when making a slight change and running.
- 2. Each changed run results in an extra allocation.

This issue can track (1). (2) is already being tracked by #2419.

### Reproduction steps

I took the following steps

- 1. I ran the job file below.
- 2. Ensure 2 containers are running.
- 3. Change the docker image tag to `0.0.2`
- 4. Running a plan reveals in-place updates as expected (see below).
- 5. Run the plan.

I am seeing both allocations stop immediately resulting in 0 containers being alive.
I am also seeing 3 allocations starting.

I have attached the plan diff, first job file, second job file, and intermediate nomad status immediately after running the second job file.

[job-run1.txt](https://github.com/hashicorp/nomad/files/873602/job-run1.txt)
[job-run2.txt](https://github.com/hashicorp/nomad/files/873610/job-run2.txt)
[plan-diff.txt](https://github.com/hashicorp/nomad/files/873605/plan-diff.txt)
[status-run2.txt](https://github.com/hashicorp/nomad/files/873603/status-run2.txt)

### Notes

* Second run was executed at `19:40:10 UTC`.
* The "deploy-blue" task group is meant to serve for blue/green deployment of worker nodes.  It's trying to place 2 because there are no provisioned blue workers

**Comment by dadgar** [comment] 2017-03-28 00:37
@BSick7 Does this always reproduce for you?

Also to clarify, in-place updates do not trigger the update block. The update block is used to control rolling upgrades but in-place updates require no down time so issue 1 is not an issue.

So I diff'ed the job1 and 2 and it appears both task groups are set to count = 2, the only thing changed was the image and that doesn't line up with the plan so I am somewhat confused.

**Comment by BSick7** [comment] 2017-03-28 11:48
@dadgar It always reproduces.

Perhaps you can clarify "rolling upgrades".  If I am "upgrading" my version tag, shouldn't that roll new allocations one at a time?

**Comment by dadgar** [comment] 2017-03-28 18:35
@BSick7 Yes that should trigger a "create/destroy" update which is handled via the update block. That is part of the reason I am confused.

Maybe re-run the test and see if you are seeing the behavior you have documented in the test. Because from the plan and the job files it doesn't really make sense (I wonder if the wrong job files got uploaded to this issue? The create indexes are different between them which suggests the job was stopped in-between those runs as well).

**Comment by BSick7** [comment] 2017-03-29 13:14
I mentioned that I redacted sensitive pieces of the jobspecs.  I will do a file diff to confirm *precisely* what has changed.

**Comment by dadgar** [comment] 2017-08-23 17:20
@BSick7 I am going to close this out. Feel free to open if you still experience it in 0.6.X.

**Closed by dadgar** 2017-08-23 17:20 UTC
Labels: waiting-reply
