### ISSUE TITLE
[Possible bug] Nomad 1.3.0 sysbatch job not getting evaluation done, stuck in pending

### ISSUE THREAD

**Issue by imcom** [hashicorp/nomad#13489] opened 2022-06-27 07:41 UTC
### Nomad version

`Nomad v1.3.0 (52e95d64113e01be05d585d8b4c07f6f19efebbc)`

### Operating system and Environment details

```
root@iZ2zee9g78iybkvt8kx9htZ:~# lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
root@iZ2zee9g78iybkvt8kx9htZ:~# uname -a
Linux iZ2zee9g78iybkvt8kx9htZ 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Issue

A `sysbatch` job stuck with evaluation without completion nor error.

when I force run the periodic job like below
```
==> 2022-06-27T13:53:59+08:00: Monitoring evaluation "6e96ea0a"
2022-06-27T13:53:59+08:00: Evaluation triggered by job "vdproto-log-cleaner/periodic-1656309239"
==> 2022-06-27T13:54:00+08:00: Monitoring evaluation "6e96ea0a"
==> 2022-06-27T13:54:01+08:00: Monitoring evaluation "6e96ea0a"
==> 2022-06-27T13:54:02+08:00: Monitoring evaluation "6e96ea0a"
==> 2022-06-27T13:54:03+08:00: Monitoring evaluation "6e96ea0a"
==> 2022-06-27T13:54:04+08:00: Monitoring evaluation "6e96ea0a"
```

the evaluation itself stuck in pending
I have nomad eval list the output looks like

```
ID Priority Triggered By Job ID Status Placement Failures
88a8cc8a 50 job-register vdproto-log-cleaner/periodic-1656309239 pending false
6e96ea0a 50 periodic-job vdproto-log-cleaner/periodic-1656309239 pending false
and to status a specific eval, it outputs
[root@iZ2zee9g78iybkvt8kx9htZ](mailto:root@iZ2zee9g78iybkvt8kx9htZ):~# nomad eval status 88a8cc8a
ID = 88a8cc8a
Create Time = 41s ago
Modify Time = 41s ago
Status = pending
Status Description = pending
Type = sysbatch
TriggeredBy = job-register
Job ID = vdproto-log-cleaner/periodic-1656309239
Priority = 50
Placement Failures = false
```
no matter the eval is triggered by job-register or periodic , it just stuck in pending

### Reproduction steps

It is simple in my situation, I register a periodic sysbatch job using the below definition

It got stuck when the periodic job fires, but also it got stuck too if I force run the job.

#### Expected Result

The sysbatch job should run on matching nodes.

#### Actual Result

the job stuck in evaluation pending state forever

### Job file (if appropriate)

```
job "vdproto-log-cleaner" {
    datacenters = ["myidc"]
    type = "sysbatch"

    periodic {
        cron = "@daily"
        prohibit_overlap = true
    }

    group "cleaner" {
        constraint {
            attribute = "${meta.gpu_type}"
            value     = "a10"
        }

        count = 1

        task "cleanup" {
            resources {
                cpu = 100
                memory = 128
            }
            driver = "raw_exec"
            config {
                command = "powershell"
                args = ["C:\\cleanup-log.ps1"]
            }
        }
    }
}
```

### Nomad Server logs (if appropriate)

```
root@iZ2zee9g78iybkvt8kx9htZ:~# nomad eval list
ID        Priority  Triggered By    Job ID                                   Status    Placement Failures
88a8cc8a  50        job-register    vdproto-log-cleaner/periodic-1656309239  pending   false
6e96ea0a  50        periodic-job    vdproto-log-cleaner/periodic-1656309239  pending   false
```
```
root@iZ2zee9g78iybkvt8kx9htZ:~# nomad eval status 88a8cc8a
ID                 = 88a8cc8a
Create Time        = 29m38s ago
Modify Time        = 29m38s ago
Status             = pending
Status Description = pending
Type               = sysbatch
TriggeredBy        = job-register
Job ID             = vdproto-log-cleaner/periodic-1656309239
Priority           = 50
Placement Failures = false
```
```
root@iZ2zee9g78iybkvt8kx9htZ:~# nomad eval status --monitor 88a8cc8a
==> 2022-06-27T15:41:05+08:00: Monitoring evaluation "88a8cc8a"
    2022-06-27T15:41:05+08:00: Evaluation triggered by job "vdproto-log-cleaner/periodic-1656309239"
==> 2022-06-27T15:41:06+08:00: Monitoring evaluation "88a8cc8a"
==> 2022-06-27T15:41:07+08:00: Monitoring evaluation "88a8cc8a"
==> 2022-06-27T15:41:08+08:00: Monitoring evaluation "88a8cc8a"
==> 2022-06-27T15:41:09+08:00: Monitoring evaluation "88a8cc8a"
```

**Comment by imcom** [comment] 2022-06-27 10:11
Found a workaround 

found a way to use batch instead. Using spread on attribute unique id to evenly distribute the job to all nodes ...

**Comment by imcom** [comment] 2022-06-27 10:12
creds to https://github.com/liquidinvestigations/cluster/pull/79/files

**Comment by imcom** [comment] 2022-06-27 15:38
Hi @jrasell I did not have the logs by hand. But here's what I saw, 1) the server agent logs to syslog with level INFO, I could find a clue in the syslog. 2) I also tried using `nomad monitor -log-level debug`, when I forced run the job, I could only see a `PUT` request being logged to start an evaluation and that's all I got. Hope this helps. If you have specific instructions for getting more log, I am happy to know and try.

**Comment by Blefish** [comment] 2022-08-08 12:38
Ran into the same problem, sysbatch parameterized job unable to run, just stuck in pending and evaluation is pending as well.

**Comment by OlaSegha** [comment] 2022-11-12 16:03
Ran into this same problem on 1.3.2

**Comment by OlaSegha** [comment] 2022-11-12 16:04
oh and the UI is completely unresponsive when you click on the children jobs ....

**Comment by kevinschoonover** [comment] 2023-10-04 05:15
@jrasell I am also having this issue on nomad 1.6.1, but I am not able to reproduce locally. This is the first time I tried to run sysbatch jobs so not sure what version it started.

Running the following job
```hcl
# nomad run job.hcl
job "update-images-test-8" {
  datacenters = ["dc1"]
  type        = "sysbatch"

  group "update" {
    task "update" {
      driver = "docker"

      config {
        image      = "docker:cli"
        entrypoint = ["sh", "ls"]
      }

      resources {
        cpu    = 256
        memory = 64 # 256MB
      }
    }
  }
}
```

I see what @imcom was mentioning above (all I see is it constantly querying the evaluation constantly0
```sh
> nomad monitor -log-level DEBUG -server-id <leader>
2023-10-04T05:09:09.031Z [DEBUG] http: request complete: method=PUT path=/v1/jobs duration=3.935863ms
2023-10-04T05:09:09.048Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d duration="336.229µs"
2023-10-04T05:09:09.075Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d/allocations duration=1.579828ms
2023-10-04T05:09:09.220Z [DEBUG] http: request complete: method=GET path="/v1/job/XBRtpQC0Xx/allocations?all=true&namespace=default&region=global" duration="312.25µs"
2023-10-04T05:09:09.222Z [DEBUG] http: request complete: method=GET path="/v1/allocation/6b739c1b-c7a2-0391-5ced-ea4feee623d4?namespace=default&region=global" duration="392.642µs"
2023-10-04T05:09:10.121Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d duration="237.199µs"
2023-10-04T05:09:10.151Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d/allocations duration="276.958µs"
2023-10-04T05:09:11.155Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=server duration="328.292µs"
2023-10-04T05:09:11.169Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d duration="375.327µs"
2023-10-04T05:09:11.185Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d/allocations duration="371.228µs"
2023-10-04T05:09:12.203Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d duration="574.178µs"
2023-10-04T05:09:12.221Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d/allocations duration="679.781µs"
2023-10-04T05:09:13.239Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d duration="521.332µs"
2023-10-04T05:09:13.255Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d/allocations duration="518.708µs"
2023-10-04T05:09:13.527Z [DEBUG] nomad: memberlist: Stream connection from=100.83.171.64:33302
2023-10-04T05:09:14.287Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d duration="573.788µs"
2023-10-04T05:09:14.303Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d/allocations duration="561.574µs"
2023-10-04T05:09:15.224Z [DEBUG] http: request complete: method=GET path="/v1/job/XBRtpQC0Xx/allocations?all=true&namespace=default&region=global" duration="651.044µs"
2023-10-04T05:09:15.322Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d duration="538.496µs"
2023-10-04T05:09:15.341Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d/allocations duration="519.949µs"
2023-10-04T05:09:16.393Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d duration="475.83µs"
2023-10-04T05:09:16.409Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d/allocations duration="452.132µs"
2023-10-04T05:09:17.444Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d duration="331.378µs"
2023-10-04T05:09:17.462Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d/allocations duration="496.993µs"
2023-10-04T05:09:18.481Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d duration="272.741µs"
2023-10-04T05:09:18.499Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d/allocations duration="239.113µs"
2023-10-04T05:09:19.518Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d duration="267.61µs"
2023-10-04T05:09:19.536Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d/allocations duration="311.179µs"
2023-10-04T05:09:20.568Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d duration="585.641µs"
2023-10-04T05:09:20.586Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d/allocations duration="518.396µs"
2023-10-04T05:09:21.157Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=server duration="331.469µs"
2023-10-04T05:09:21.222Z [DEBUG] http: request complete: method=GET path="/v1/job/XBRtpQC0Xx/allocations?all=true&namespace=default&region=global" duration="566.113µs"
2023-10-04T05:09:21.224Z [DEBUG] http: request complete: method=GET path="/v1/allocation/6b739c1b-c7a2-0391-5ced-ea4feee623d4?namespace=default&region=global" duration="432.463µs"
2023-10-04T05:09:21.608Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d duration="238.421µs"
2023-10-04T05:09:21.637Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d/allocations duration="251.387µs"
2023-10-04T05:09:21.756Z [DEBUG] nomad: memberlist: Stream connection from=100.91.63.45:42266
2023-10-04T05:09:22.656Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d duration="271.037µs"
2023-10-04T05:09:22.675Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d/allocations duration="240.415µs"
2023-10-04T05:09:23.528Z [DEBUG] nomad: memberlist: Stream connection from=100.83.171.64:55884
2023-10-04T05:09:23.697Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d duration="293.954µs"
2023-10-04T05:09:23.716Z [DEBUG] http: request complete: method=GET path=/v1/evaluation/07edc1b9-ab5b-2970-31d3-cf62458f267d/allocations duration="232.429µs"
```

I tried watching the clients but dont see any logs. Are the any debug logs I can help provide during this time to instrument when its stuck pending?

**Comment by kevinschoonover** [comment] 2023-12-09 07:51
Another interesting observation is that when I run 

```
nomad stop -purge job.hcl
nomad system gc
nomad system reconcile
# edit the job file the be type = "batch"
nomad run job.hcl
```
it is still stuck in pending state, but if I change the name of the job an group name it suddenly works until i change the type back to "sysbatch"

**Comment by jrasell** [comment] 2024-10-31 10:15
Closing as this issue seems to be resolved and looked to be as a result of the sysbatch scheduler not being enabled.

**Closed by jrasell** 2024-10-31 10:15 UTC
Labels: type/bug, stage/waiting-reply
