### ISSUE TITLE
UI does not include client certificate in all ajax requests

### ISSUE THREAD

**Issue by selaux** [hashicorp/nomad#3701] opened 2017-12-29 09:16 UTC
### Nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Issue

It seems like not all ajax requests include the client certificate that was selected. E.g. when visiting the clients page, the request to `/v1/status/leader` returns a `400 Bad Request` error because no client certificate was sent.

Listing nodes through the CLI works fine.

### Reproduction steps
- Enable tls for http
- Visit nomad ui and select valid client certificate
- Visit `/ui/jobs` -> Works as expected
- Visit `/ui/clients` -> shows error page

**Comment by schmichael** [comment] 2018-01-06 01:43
We have an idea what the issue might be, but I've been unable to reproduce this bug in my browser (Google Chrome 63.0.3239.108 (Official Build) (64-bit)).

What browser are you using?

**Comment by selaux** [comment] 2018-01-06 11:33
I'm using Firefox 57.0b3 (64-bit) Developer Edition.

**Comment by selaux** [comment] 2018-01-06 11:33
BTW, same goes for basic auth. It is not sent as well.

**Comment by selaux** [comment] 2018-01-06 11:36
And it indeed works in chrome for me as well...

**Comment by schmichael** [comment] 2018-01-06 22:16
@selaux Thanks for testing! I think we know the fix. Should have a PR up next week for inclusion in the next release. In the meantime I'm afraid you'll have to use Chrome/Chromium. I think Firefox is actually doing the right thing here, so I hope Chrome doesn't "fix" it in the meantime!

**Comment by schmichael** [comment] 2018-01-08 20:12
Tested Firefox 57.0.4 (`57.0.4+build1-0ubuntu0.17.04.1 amd64`) and confirmed it does break against 0.7.1.

Fixed in #3728 but until the fix is in a release you'll have to use Chrome/Chromium I'm afraid.

Thanks for the report!

**Closed** 2018-01-08 22:00 UTC
Labels: bug, tls, ui

**Comment by selaux** [comment] 2018-01-09 07:38
Nice. Thx for the quick fix.
