### ISSUE TITLE
Question: Services on nomad client restart/reallocate when nomad servers are unavailabe

### ISSUE THREAD

**Issue by mnuic** [hashicorp/nomad#4151] opened 2018-04-13 07:53 UTC
### Nomad version
```
# nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)
``` 

### Operating system and Environment details
Ubuntu 16.04LTS

### Issue

We have local datacenter connected to AWS VPC through VPN connection. When VPN goes down, Nomad clients from local dc can not connect to Nomad server that are on AWS and that is fine. Strange thing is that while VPN is down, services on hosts at local dc work like nothing happened, but when VPN is restored (nomad clients connect to nomad servers), all services are migrated to another host. Is this expected behaviour?

Would expect Nomad to start new evaluation of these services and if everything is fine (which is, because services are already working) that they just continue working on the same host?

**Comment by preetapan** [comment] 2018-04-13 15:15
@mnuic when Nomad servers lose connections with their clients they are considered lost allocations and are migrated over to another client node. This happens when the client's node's status is marked as down. 

Could you provide the output of `nomad job status` of the service job and `nomad node status` of the noded that got disconnected the next time this happens?

**Comment by dadgar** [comment] 2018-04-13 23:26
I am going to close this in the mean time because this is expected behavior. The clients heartbeat to the servers so that the servers know the clients are alive. Once the heartbeat is missed, the server will mark the allocations on the client as lost and relocate the allocations on the down host to another machine.

**Closed by dadgar** 2018-04-13 23:26 UTC

**Comment by shantanugadgil** [comment] 2018-04-14 05:09
Hi @mnuic  I think you should have a server in the local datacenter.
The local and AWS servers should then be peered.
Local machine reporting to the local server and AWS machines (if any) reporting in to the AWS server.

HTH,
Regards,
Shantanu
