### ISSUE TITLE
Jobs using CSI volume do not recover from the client failure without human intervention

### ISSUE THREAD

**Issue by PinkLolicorn** [hashicorp/nomad#12118] opened 2022-02-24 01:00 UTC
### Nomad version
```
Nomad v1.2.6 (a6c6b475db5073e33885377b4a5c733e1161020c)
```

### Operating system and Environment details
Ubuntu 20.04.3 LTS running on CPX11 VMs from Hetzner

### Issue
Jobs using CSI volume do not recover from the client failure without human intervention and require volume to be manually detached from the client using provider's web UI. The client's storage controller/node health does not return to normal after the instance is back online. The process of moving the job to the other node works with draining (excluding system jobs) but not on the failure.

### Reproduction steps
- Create cluster with 2 servers and 4 clients (6 VMs, just my testing setup, not sure if matters)
- Run `hetznercloud/hcloud-csi-driver:1.6.0` as system job
- Create/register new volume
- Run job with the said volume
- Shutdown the client with the said job/volume
- Observe failure to alloc job on the new client due to volume being still attached to the previous VM
- Detach the volume manually from the Hetzner Cloud Console (optional)
- Turn the previous VM back on
- Observe the VM back in ready state but plugin dashboard still says "Healthy (3/4)"
- Observe the job working on the other client if volume was manually detached, otherwise still failing
- Observe write allocations for volume, showing failed on the previously turned off client and running on some other

Additional steps
- Shutdown the other client the volume dependent job was moved to
- After some time observe the availability showing 0% with "Controller Health 0% (2/0) Node Health 0% (2/0)"
- Turn on the second VM that is currently running the job
- Observe the availability showing 50% with "Controller Health 50% (2/4) Node Health 50% (2/4)"
- Observe the job failing again
- Detach volume manually again
- Make sure the job allocation is tried again
- Observe the availability still at 50%
- Observe write allocations for volume, showing failed on the previous two clients and running on some other*
- Repeat until zero clients available

*Failed allocations are gone after some time.

#### Expected Result
1. The volume is detached when client failure occurs.
2. Nomad storage support recovers from the client failure.

#### Actual Result
1. The volume is not detached and prevents jobs from running.
2. The previously dead client is no longer a healthy storage controller/node, even after being back online. These seem to have csi job complete but the task is still running**, not sure if that is desirable but these nodes are not considered healthy.

**After night these returned all back to running, but CSI controllers/nodes are still not considered healthy.

![image](https://user-images.githubusercontent.com/44551064/155437393-9897c276-e66c-43b8-a772-b72894b04deb.png)
![image](https://user-images.githubusercontent.com/44551064/155437443-9183b211-c096-4155-8b7c-7b54a2586769.png)
![image](https://user-images.githubusercontent.com/44551064/155435584-6a71f339-0df4-4141-9899-f94e3afd20fd.png)

### Job file (CSI plugin)
```
job "csi" {
  region      = "eu-central"
  datacenters = ["fsn"]
  type        = "system"

  group "node" {
    task "plugin" {
      driver = "docker"

      config {
        image      = "hetznercloud/hcloud-csi-driver:1.6.0"
        privileged = true
      }

      env {
        CSI_ENDPOINT   = "unix:///csi/csi.sock"
        HCLOUD_TOKEN   = "MY_SECRET_TOKEN"
        ENABLE_METRICS = false
      }

      csi_plugin {
        id        = "csi.hetzner.cloud"
        type      = "monolith"
        mount_dir = "/csi"
      }

      resources {
        cpu        = 50
        memory     = 16
        memory_max = 256
      }
    }
  }
}
```

### Job file (MySQL using CSI)
```
job "test" {
  region      = "eu-central"
  datacenters = ["fsn"]

  group "db" {
    count = 1

    restart {
      interval = "1m"
      mode     = "delay"
    }

    volume "storage" {
      type   = "csi"
      source = "volume-1"
      attachment_mode = "file-system"
      access_mode     = "single-node-writer"
    }

    network {
      port "mysql" { to = 3306 }
    }

    task "mysql" {
      driver = "docker"

      # this actually requires the removal of the lost+found
      # manually before mysql can be initialized on the volume
      volume_mount {
        volume      = "storage"
        destination = "/var/lib/mysql"
        read_only   = false
      }

      env {
        MYSQL_ROOT_PASSWORD = "12345"
        MYSQL_DATABASE      = "test"
        MYSQL_USER          = "test"
        MYSQL_PASSWORD      = "1234"
      }

      config {
        image = "mysql:5-debian"
        ports = ["mysql"]
      }

      service {
        port = "mysql"
      }

      resources {
        cpu    = 1000
        memory = 256
      }
    }
  }
}
```

### Job failure message
```
failed to setup alloc: pre-run hook "csi_hook" failed: claim volumes: could not claim volume MY_VOLUME: rpc error: rpc error: controller publish: attach volume: controller attach volume: CSI.ControllerAttachVolume: volume "MY_VOLUME_ID" is already published on another node and does not have MULTI_NODE volume capability: rpc error: code = FailedPrecondition desc = failed to publish volume: volume is attached
```

### CSI plugin logs
```
level=info ts=2022-02-23T23:17:13.563580702Z msg="fetched server" server-name=hashi-fsn-client-4
level=info ts=2022-02-23T23:36:47.371589294Z component=api-volume-service msg="attaching volume" volume-id=MY_VOLUME_ID server-id=client-1
level=info ts=2022-02-23T23:36:47.559393123Z component=api-volume-service msg="volume is already attached to another server" volume-id=MY_VOLUME_ID server-id=client-2
level=error ts=2022-02-23T23:36:47.603606394Z component=grpc-server msg="handler failed" err="rpc error: code = FailedPrecondition desc = failed to publish volume: volume is attached"
level=info ts=2022-02-23T23:38:47.650302102Z component=api-volume-service msg="attaching volume" volume-id=MY_VOLUME_ID server-id=client-3
level=info ts=2022-02-23T23:38:47.884207741Z component=api-volume-service msg="volume is already attached to another server" volume-id=MY_VOLUME_ID server-id=client-2
level=error ts=2022-02-23T23:38:47.925305127Z component=grpc-server msg="handler failed" err="rpc error: code = FailedPrecondition desc = failed to publish volume: volume is attached"
level=info ts=2022-02-23T23:39:20.971902903Z component=api-volume-service msg="detaching volume from server" volume-id=MY_VOLUME_ID server-id=client-2
level=info ts=2022-02-23T23:39:21.07116093Z component=api-volume-service msg="failed to detach volume" volume-id=MY_VOLUME_ID err="cannot perform operation because server is locked (locked)"
level=error ts=2022-02-23T23:39:21.07122513Z component=grpc-server msg="handler failed" err="rpc error: code = Unavailable desc = failed to unpublish volume: server is locked"
level=info ts=2022-02-23T23:42:47.973406664Z component=api-volume-service msg="attaching volume" volume-id=MY_VOLUME_ID server-id=client-4
level=info ts=2022-02-23T23:47:18.516977647Z component=api-volume-service msg="detaching volume from server" volume-id=MY_VOLUME_ID server-id=client-1
level=info ts=2022-02-23T23:47:18.629824577Z component=api-volume-service msg="failed to detach volume" volume-id=MY_VOLUME_ID err="cannot perform operation because server is locked (locked)"
level=error ts=2022-02-23T23:47:18.629904217Z component=grpc-server msg="handler failed" err="rpc error: code = Unavailable desc = failed to unpublish volume: server is locked"
level=info ts=2022-02-23T23:47:21.627957436Z component=api-volume-service msg="detaching volume from server" volume-id=MY_VOLUME_ID server-id=client-1
level=info ts=2022-02-23T23:47:21.669399184Z component=api-volume-service msg="volume not attached to a server" volume-id=MY_VOLUME_ID
level=info ts=2022-02-23T23:48:44.41762282Z component=api-volume-service msg="attaching volume" volume-id=MY_VOLUME_ID server-id=client-4
level=info ts=2022-02-23T23:48:44.64604037Z component=api-volume-service msg="volume is already attached to another server" volume-id=MY_VOLUME_ID server-id=client-2
level=error ts=2022-02-23T23:48:44.67891215Z component=grpc-server msg="handler failed" err="rpc error: code = FailedPrecondition desc = failed to publish volume: volume is attached"
level=info ts=2022-02-23T23:48:45.417872798Z component=api-volume-service msg="detaching volume from server" volume-id=MY_VOLUME_ID server-id=client-2
level=info ts=2022-02-23T23:51:48.163935969Z component=api-volume-service msg="attaching volume" volume-id=MY_VOLUME_ID server-id=client-2
level=info ts=2022-02-23T23:51:48.392417837Z component=api-volume-service msg="volume is already attached to another server" volume-id=MY_VOLUME_ID server-id=client-1
level=error ts=2022-02-23T23:51:48.426822191Z component=grpc-server msg="handler failed" err="rpc error: code = FailedPrecondition desc = failed to publish volume: volume is attached"
```

### Nomad Server logs
```
Feb 23 23:15:56 hashi-fsn-server-1 nomad[1790]:     2022-02-23T23:15:56.847Z [ERROR] nomad.fsm: deregistering job failed: error="DeleteJob failed: deleting job from plugin: plugin missing: csi.hetzner.cloud <nil>" job=csi namespace=default
...
Feb 23 23:47:18 hashi-fsn-server-1 nomad[1790]:     2022-02-23T23:47:18.494Z [ERROR] nomad.volumes_watcher: error releasing volume claims: namespace=default volume_id=MY_VOLUME
Feb 23 23:47:18 hashi-fsn-server-1 nomad[1790]:   error=
Feb 23 23:47:18 hashi-fsn-server-1 nomad[1790]:   | 1 error occurred:
Feb 23 23:47:18 hashi-fsn-server-1 nomad[1790]:   |         * could not detach from controller: controller detach volume: CSI.ControllerDetachVolume: rpc error: code = Unavailable desc = failed to  unpublish volume: server is locked
Feb 23 23:47:18 hashi-fsn-server-1 nomad[1790]:   |
Feb 23 23:47:18 hashi-fsn-server-1 nomad[1790]:
...
Feb 24 00:15:11 hashi-fsn-server-1 nomad[1790]:     2022-02-24T00:15:11.783Z [ERROR] nomad.volumes_watcher: error releasing volume claims: namespace=default volume_id=MY_VOLUME
Feb 24 00:15:11 hashi-fsn-server-1 nomad[1790]:   error=
Feb 24 00:15:11 hashi-fsn-server-1 nomad[1790]:   | 1 error occurred:
Feb 24 00:15:11 hashi-fsn-server-1 nomad[1790]:   |         * could not detach from node: node detach volume: CSI.NodeDetachVolume: context deadline exceeded
Feb 24 00:15:11 hashi-fsn-server-1 nomad[1790]:   |
Feb 24 00:15:11 hashi-fsn-server-1 nomad[1790]:
...
Feb 24 00:30:11 hashi-fsn-server-1 nomad[1790]:     2022-02-24T00:30:11.796Z [ERROR] nomad.volumes_watcher: error releasing volume claims: namespace=default volume_id=MY_VOLUME
Feb 24 00:30:11 hashi-fsn-server-1 nomad[1790]:   error=
Feb 24 00:30:11 hashi-fsn-server-1 nomad[1790]:   | 2 errors occurred:
Feb 24 00:30:11 hashi-fsn-server-1 nomad[1790]:   |         * could not detach from node: node detach volume: CSI.NodeDetachVolume: context deadline exceeded
Feb 24 00:30:11 hashi-fsn-server-1 nomad[1790]:   |         * could not detach from node: No path to node
Feb 24 00:30:11 hashi-fsn-server-1 nomad[1790]:   |
Feb 24 00:30:11 hashi-fsn-server-1 nomad[1790]:
...
Feb 24 00:47:11 hashi-fsn-server-1 nomad[1790]:     2022-02-24T00:47:11.835Z [ERROR] nomad.volumes_watcher: error releasing volume claims: namespace=default volume_id=MY_VOLUME
Feb 24 00:47:11 hashi-fsn-server-1 nomad[1790]:   error=
Feb 24 00:47:11 hashi-fsn-server-1 nomad[1790]:   | 2 errors occurred:
Feb 24 00:47:11 hashi-fsn-server-1 nomad[1790]:   |         * could not detach from node: node detach volume: CSI.NodeDetachVolume: context deadline exceeded
Feb 24 00:47:11 hashi-fsn-server-1 nomad[1790]:   |         * could not detach from node: node detach volume: CSI.NodeDetachVolume: context deadline exceeded
Feb 24 00:47:11 hashi-fsn-server-1 nomad[1790]:   |
Feb 24 00:47:11 hashi-fsn-server-1 nomad[1790]:
```

## Nomad server logs (next day)

Seems like volumes watcher is still trying to detach the volume, even if the volume shows currently only one running allocation on the correct node. The log shows two errors and that would correspond to the two previously turned off clients.

```
Feb 24 11:53:11 hashi-fsn-server-1 nomad[1790]:     2022-02-24T11:53:11.808Z [ERROR] nomad.volumes_watcher: error releasing volume claims: namespace=default volume_id=MY_VOLUME
Feb 24 11:53:11 hashi-fsn-server-1 nomad[1790]:   error=
Feb 24 11:53:11 hashi-fsn-server-1 nomad[1790]:   | 2 errors occurred:
Feb 24 11:53:11 hashi-fsn-server-1 nomad[1790]:   |         * could not detach from node: node detach volume: CSI.NodeDetachVolume: context deadline exceeded
Feb 24 11:53:11 hashi-fsn-server-1 nomad[1790]:   |         * could not detach from node: node detach volume: CSI.NodeDetachVolume: context deadline exceeded
Feb 24 11:53:11 hashi-fsn-server-1 nomad[1790]:   |
Feb 24 11:53:11 hashi-fsn-server-1 nomad[1790]:
Feb 24 11:57:11 hashi-fsn-server-1 nomad[1790]:     2022-02-24T11:57:11.835Z [ERROR] nomad.volumes_watcher: error releasing volume claims: namespace=default volume_id=MY_VOLUME
Feb 24 11:57:11 hashi-fsn-server-1 nomad[1790]:   error=
Feb 24 11:57:11 hashi-fsn-server-1 nomad[1790]:   | 2 errors occurred:
Feb 24 11:57:11 hashi-fsn-server-1 nomad[1790]:   |         * could not detach from node: node detach volume: CSI.NodeDetachVolume: context deadline exceeded
Feb 24 11:57:11 hashi-fsn-server-1 nomad[1790]:   |         * could not detach from node: rpc error: node detach volume: CSI.NodeDetachVolume: context deadline exceeded
Feb 24 11:57:11 hashi-fsn-server-1 nomad[1790]:   |
Feb 24 11:57:11 hashi-fsn-server-1 nomad[1790]:
Feb 24 12:01:11 hashi-fsn-server-1 nomad[1790]:     2022-02-24T12:01:11.848Z [ERROR] nomad.volumes_watcher: error releasing volume claims: namespace=default volume_id=MY_VOLUME
Feb 24 12:01:11 hashi-fsn-server-1 nomad[1790]:   error=
Feb 24 12:01:11 hashi-fsn-server-1 nomad[1790]:   | 2 errors occurred:
Feb 24 12:01:11 hashi-fsn-server-1 nomad[1790]:   |         * could not detach from node: node detach volume: CSI.NodeDetachVolume: context deadline exceeded
Feb 24 12:01:11 hashi-fsn-server-1 nomad[1790]:   |         * could not detach from node: node detach volume: CSI.NodeDetachVolume: context deadline exceeded
Feb 24 12:01:11 hashi-fsn-server-1 nomad[1790]:   |
Feb 24 12:01:11 hashi-fsn-server-1 nomad[1790]:
```

### Related
https://discuss.hashicorp.com/t/csi-plugin-health-after-reboot/24723 - similar issue with 2/3 healthy after reboot and "context deadline exceeded" messages (using [kubernetes-csi/csi-driver-nfs/](https://github.com/kubernetes-csi/csi-driver-nfs/))

**Comment by tgross** [comment] 2022-02-24 13:43
Hi @PinkLolicorn! Thanks for the detailed report on this! As it turns out the initial failure on the client is a known issue https://github.com/hashicorp/nomad/issues/11477, which I've already got a fix in-flight for in https://github.com/hashicorp/nomad/pull/12113. That'll ship in the upcoming Nomad 1.3.0 (and get backported to 1.2.x and 1.1.x).

It looks like on the server you're seeing https://github.com/hashicorp/nomad/issues/11758 which is going to be fixed in https://github.com/hashicorp/nomad/pull/12114.

I'm less sure about the error:

> server is locked

Because that's bubbling up from the Hetzner plugin you're using.

You _might_ be able to recover from the looping volumewatcher errors by ensuring the plugin is running on the old node.

**Comment by tgross** [comment] 2022-02-24 13:44
@PinkLolicorn I'm going to close this as a duplicate because the underlying issue is fixed, but I'm happy to keep chatting about how to fix up the volumewatcher error if possible.

**Closed by tgross** 2022-02-24 13:44 UTC
Labels: type/bug, stage/waiting-reply, stage/duplicate, theme/storage

**Comment by tgross** [comment] 2022-02-25 20:56
> Seems that a moment later the error was gone. I thought it might have been the VM that is turned off, but looks like action on two separate VMs failed with this one. My best guess is this might have been the action of detaching on the Hetzner side, not being cleared yet after the previous attempt.

Ok, the plugin allocation logs you have suggest that Nomad is sending the detach RPCs but they're failing. If you're not seeing the "server is locked" error anymore, are you seeing logs for the detach RPCs?

> This is a bit more confusing, 4 instances but 2 per client with the same ID? There is only a single CSI plugin container running on any of the clients.

Your plugin is of type `monolith`, which means it serves both the controller and node RPCs. This is treated as separate plugin instances because Nomad (or k8s for that matter) has to make decisions about which plugin instance to talk to differently for both. That has a little bit of a goofy side effect in how it gets modeled in the web UI.

> Any schedule for the 1.3.0 release and backports?

I can't give dates for our releases, but I can say it's the currently active line of work across the whole team. In the meantime, feel free to check out the `main` branch and give a build a try!

**Comment by PinkLolicorn** [comment] 2022-02-25 21:48
My previous bugged state was "wiped" due to other experiments on the cluster, but after some digging in the Hetzner's CSI plugin, I was able to figure the meaning of the status:
```
	ErrorCodeLocked                ErrorCode = "locked"                  // Item is locked (Another action is running)
```

Bringing back part of the log, my knowledge about the architecture is limited, but I think we can see: 
1) attach action failing with "volume is attached" (client-1, then client-2, both previously dead - targeting client-2)
2) detach action failing with "server is locked" (client-2 - targeting self previously dead?)
3) detach action failing with "server is locked" (client-4 - targeting client-1 previously dead)
4) ... other actions that I'm not sure what to think of because I might have detached the volume manually at this time ...

```
level=info ts=2022-02-23T23:17:13.563580702Z msg="fetched server" server-name=hashi-fsn-client-4

level=info ts=2022-02-23T23:36:47.371589294Z component=api-volume-service msg="attaching volume" volume-id=MY_VOLUME_ID server-id=client-1
level=info ts=2022-02-23T23:36:47.559393123Z component=api-volume-service msg="volume is already attached to another server" volume-id=MY_VOLUME_ID server-id=client-2
level=error ts=2022-02-23T23:36:47.603606394Z component=grpc-server msg="handler failed" err="rpc error: code = FailedPrecondition desc = failed to publish volume: volume is attached"

level=info ts=2022-02-23T23:38:47.650302102Z component=api-volume-service msg="attaching volume" volume-id=MY_VOLUME_ID server-id=client-3
level=info ts=2022-02-23T23:38:47.884207741Z component=api-volume-service msg="volume is already attached to another server" volume-id=MY_VOLUME_ID server-id=client-2
level=error ts=2022-02-23T23:38:47.925305127Z component=grpc-server msg="handler failed" err="rpc error: code = FailedPrecondition desc = failed to publish volume: volume is attached"

level=info ts=2022-02-23T23:39:20.971902903Z component=api-volume-service msg="detaching volume from server" volume-id=MY_VOLUME_ID server-id=client-2
level=info ts=2022-02-23T23:39:21.07116093Z component=api-volume-service msg="failed to detach volume" volume-id=MY_VOLUME_ID err="cannot perform operation because server is locked (locked)"
level=error ts=2022-02-23T23:39:21.07122513Z component=grpc-server msg="handler failed" err="rpc error: code = Unavailable desc = failed to unpublish volume: server is locked"

level=info ts=2022-02-23T23:42:47.973406664Z component=api-volume-service msg="attaching volume" volume-id=MY_VOLUME_ID server-id=client-4
level=info ts=2022-02-23T23:47:18.516977647Z component=api-volume-service msg="detaching volume from server" volume-id=MY_VOLUME_ID server-id=client-1
level=info ts=2022-02-23T23:47:18.629824577Z component=api-volume-service msg="failed to detach volume" volume-id=MY_VOLUME_ID err="cannot perform operation because server is locked (locked)"
level=error ts=2022-02-23T23:47:18.629904217Z component=grpc-server msg="handler failed" err="rpc error: code = Unavailable desc = failed to unpublish volume: server is locked"

level=info ts=2022-02-23T23:47:21.627957436Z component=api-volume-service msg="detaching volume from server" volume-id=MY_VOLUME_ID server-id=client-1
level=info ts=2022-02-23T23:47:21.669399184Z component=api-volume-service msg="volume not attached to a server" volume-id=MY_VOLUME_ID

level=info ts=2022-02-23T23:48:44.41762282Z component=api-volume-service msg="attaching volume" volume-id=MY_VOLUME_ID server-id=client-4
level=info ts=2022-02-23T23:48:44.64604037Z component=api-volume-service msg="volume is already attached to another server" volume-id=MY_VOLUME_ID server-id=client-2
level=error ts=2022-02-23T23:48:44.67891215Z component=grpc-server msg="handler failed" err="rpc error: code = FailedPrecondition desc = failed to publish volume: volume is attached"

level=info ts=2022-02-23T23:48:45.417872798Z component=api-volume-service msg="detaching volume from server" volume-id=MY_VOLUME_ID server-id=client-2
???

level=info ts=2022-02-23T23:51:48.163935969Z component=api-volume-service msg="attaching volume" volume-id=MY_VOLUME_ID server-id=client-2
level=info ts=2022-02-23T23:51:48.392417837Z component=api-volume-service msg="volume is already attached to another server" volume-id=MY_VOLUME_ID server-id=client-1
level=error ts=2022-02-23T23:51:48.426822191Z component=grpc-server msg="handler failed" err="rpc error: code = FailedPrecondition desc = failed to publish volume: volume is attached"
```

So, to my understanding, it just means that any action in the scope of the specific server that was not yer cleared internally can yield this. A bit weird but would make sense: at first client-1/2 targeted attach to client-2, so considering 1 & 2 temporarily locked seeing then two "server is locked" messages for detach actions targeting these makes sense.

I wonder if this was not the case due to the better handling in the CSI plugin or more delay between attach and detach cycles, the cluster would recover correctly from the failure, or at least partially. That also makes me wonder why this is even possible, we have the answer `volume is attached` so the next action should be free to go. I think I'm going to try to reproduce this without nomad and open the separate issue for the [hetznercloud/csi-driver](https://github.com/hetznercloud/csi-driver) later.

**Comment by PinkLolicorn** [comment] 2022-03-10 14:35
> In the meantime, feel free to check out the `main` branch and give a build a try!

Just tried this, but I have trouble getting my CSI job to run on the dev version. Were there any changes to the environment variables recently? No matter if I set CSI_ENDPOINT or not the plugin does not pick it up correctly. It worked just fine before with the same job file.

```
level=error ts=2022-03-10T14:30:21.717956732Z msg="endpoint must start with unix://"
```

```hcl
job "system-csi-hetzner" {
  region      = "eu-central"
  datacenters = ["fsn"]
  namespace   = "system"
  type        = "system"

  group "node" {
    task "plugin" {
      driver = "docker"

      config {
        image      = "hetznercloud/hcloud-csi-driver:1.6.0"
        privileged = true
      }

      env {
        CSI_ENDPOINT   = "unix:///csi/csi.sock"
        HCLOUD_TOKEN   = "xyz"
        ENABLE_METRICS = false
      }

      csi_plugin {
        id        = "csi.hetzner.cloud"
        type      = "monolith"
        mount_dir = "/csi"
      }

      resources {
        cpu        = 50
        memory     = 16
        memory_max = 256
      }
    }
  }
}
```

**Comment by tgross** [comment] 2022-03-10 21:03
> Just tried this, but I have trouble getting my CSI job to run on the dev version. Were there any changes to the environment variables recently? No matter if I set CSI_ENDPOINT or not, the plugin does not pick it up correctly. It worked just fine before with the same job file.

Yeah, Nomad is setting the `CSI_ENDPOINT` variable now as of https://github.com/hashicorp/nomad/pull/12050 So it looks like the Hetzer plugin is expecting that to have `unix://` but I haven't see it fail on other plugins (I've tested recently on AWS EBS, AWS EFS, GCP, and Democratic NFS). I feel like we probably shouldn't be setting the environment if it's been set by the user though, so I'll fix that for Nomad 1.3.0 and backport.

> Also, is there any complete instruction on installing the required dependencies for the release or dev-ui builds? I was unable to find any, and I'm currently using the binary from the go build.

There's a [contributing guide](https://github.com/hashicorp/nomad/tree/main/contributing#developing-without-vagrant) but mostly what you'll want to do is run `make bootstrap` to bootstrap all the dependencies, and then at that point you can `go build` (or `make dev` to get a reasonable set of build flags).

**Comment by tgross** [comment] 2022-03-10 21:13
I've opened https://github.com/hashicorp/nomad/pull/12257 with a patch for that, but I need to do some testing which I probably won't get to until tomorrow.

**Comment by tgross** [comment] 2022-03-18 15:00
In my tests in https://github.com/hashicorp/nomad/pull/12257 it looks like the `CSI_ENDPOINT` env var isn't being set at all, which is pretty weird. So I still have some work to do to figure out what's going on there.

**Comment by tgross** [comment] 2022-03-21 15:49
Endpoint env var is fixed in #12257

**Comment by rwojsznis** [comment] 2022-05-10 13:36
> My volumes do mount, but I cannot get nomad to reschedule them in case where client goes out, and it is even worse than before, because manual detach from the hetzner UI does not help to recover.

I have pretty much the same same setup (volume & csi plugin) and pretty much the same issue - volume doesn't get rescheduled once client goes down (1.3.0-rc1); I even have a systemd service that tries to to a clean nomad shutdown (drain node) before reboot/shutdown but that seems to have no effect 🤔 

Once I have a little bit more time will try to provide more feedback, but it's good to hear (?) that I'm not the only one with same problem still 😅

**Comment by tgross** [comment] 2022-05-10 13:52
Hey folks! The old node _must_ be live and have a running plugin on it in order for Nomad to cleanly unmount the volume. You should drain a node before shutting it down, so that the tasks are rescheduled and the plugins are left in place until after all the other tasks are rescheduled. If you don't, you need to do [`volume detach`](https://www.nomadproject.io/docs/commands/volume/detach)

**Comment by PinkLolicorn** [comment] 2022-05-10 16:00
> The old node _must_ be live and have a running plugin on it in order for Nomad to cleanly unmount the volume.

@tgross ok, but shouldn't nomad at least recover after the client is back online? This is not the case in my current setup.

**Comment by tgross** [comment] 2022-05-10 17:21
> but shouldn't nomad at least recover after the client is back online?

> I just feel like bringing the client back shouldn't prevent everything from going back to normal without doing deregister manually.

It shouldn't so long as the plugin is alive and healthy. You can't crash-out the client without also making sure the node plugin is live and expect Nomad can clean this situation up; Nomad can't do anything with the volumes without a plugin in place. That's a constraint of the CSI specification.

It doesn't look like the plugin is healthy given the log entry you're showing. I'm happy to revisit this issue but there's not a lot I can do with one liner log snippets. Can you provide specific steps to reproduce and the logs for client, server, and plugins? Allocation status for plugins would also help.

**Comment by PinkLolicorn** [comment] 2022-05-11 11:07
> It shouldn't so long as the plugin is alive and healthy. You can't crash-out the client without also making sure the node plugin is live and expect Nomad can clean this situation up; Nomad can't do anything with the volumes without a plugin in place. That's a constraint of the CSI specification.

@tgross in my current cluster state all clients are online and plugins are too, volume is unmounted in the Hetzner UI, but allocation still can't take place. I noticed that the volume is at 1 allocation, but none is shown, which would make sense considering the displayed error.

**Plugin**

![image](https://user-images.githubusercontent.com/44551064/167835217-b3337e22-faf9-47db-a07a-715940291ee1.png)

**Storage**

![image](https://user-images.githubusercontent.com/44551064/167835326-61a75749-b573-4f8a-8fde-8d55fc17278d.png)

![image](https://user-images.githubusercontent.com/44551064/167835344-f76e6799-8919-4f0b-9559-20d261786d65.png)

**Job**

![image](https://user-images.githubusercontent.com/44551064/167835444-4c90fed3-259e-45aa-9636-187246c400e1.png)

**Comment by PinkLolicorn** [comment] 2022-05-11 11:32
I tried this:
1. registering volume again
2. made a job using it
3. topped the client with the job
4. waited for nomad to notice and try to reschedule
5. turned the client on again

It appears to be stuck for now, with the other previously seen error.

6. ran `nomad system gc`

Apparently this made it work? I think the difference is that the state is `failed` and not `lost`? How long would nomad need to clear this up automatically? Can this be speed up?

**After turning the client off (looks ok?):**

![image](https://user-images.githubusercontent.com/44551064/167838038-fcd80a54-a50f-47d8-9a59-d065b7901412.png)
![image](https://user-images.githubusercontent.com/44551064/167838033-67a37522-5cab-4e89-8d7c-b869d0b972e8.png)

**After turning the client on:**

![image](https://user-images.githubusercontent.com/44551064/167838237-fd73fad4-7d49-463d-ac3f-9818627ceb8e.png)

![image](https://user-images.githubusercontent.com/44551064/167838113-f0a28b49-823e-43de-a572-ea7f7cf07682.png)

**After waiting some time, the job:**

![image](https://user-images.githubusercontent.com/44551064/167838154-0100dbb7-79cf-408d-8b4f-a86e045fbcfe.png)

> failed to setup alloc: pre-run hook "csi_hook" failed: claim volumes: could not claim volume test-mysql: rpc error: rpc error: controller publish: failed to find storage provider info for client "281c57a2-bcfd-97aa-22ab-d92a88c1af76", node plugin "csi.hetzner.cloud" is not running or has not fingerprinted on this client

**After running `nomad system gc`**

![image](https://user-images.githubusercontent.com/44551064/167838594-13b274d1-cfb7-480d-9ebc-aa1ab06982fd.png)
