### ISSUE TITLE
 nomad service info <servicename>, cycles through available services

### ISSUE THREAD

**Issue by bfqrst** [hashicorp/nomad#20264] opened 2024-04-02 18:47 UTC
### Nomad version
Nomad v1.7.6
BuildDate 2024-03-12T07:27:36Z
Revision https://github.com/hashicorp/nomad/commit/594fedbfbc4f0e532b65e8a69b28ff9403eb822e

### Operating system and Environment details
Ubuntu Jammy

### Issue
`nomad service info <specific_service>` doesn't actually show you detailed info about the service you requested.

I noticed this behavior in versions prior, but can't say when I initially saw this...

### Reproduction steps
Execute `nomad service info <specific_service>` on a Nomad client.

#### Expected Result
Detailed output about `<specific_service>`.

#### Actual Result
Output about different services at that time.

```
nomad service info vmagent
Job ID           Address             Tags  Node ID   Alloc ID
victoriametrics  10.194.XX.9:23141  []    de2dfcfe  b2d92d13
``` 
... one second later, same command:

```
nomad service info vmagent
Job ID                     Address        Tags  Node ID   Alloc ID
plugin-aws-ebs-controller  10.193.XX.29  []    8f2f5468  40139007
plugin-aws-ebs-controller  10.193.XX.21   []    545da35d  a1f4318d
```

**Comment by jrasell** [comment] 2024-04-03 06:47
Hi @bfqrst and thanks for raising this issue. I believe it is a duplicate of https://github.com/hashicorp/nomad/issues/19542, so I will close this.

**Closed by jrasell** 2024-04-03 06:47 UTC
Labels: type/bug
