### ISSUE TITLE
Nomad does not register jobs on Consul v0.8.1 

### ISSUE THREAD

**Issue by sheldonkwok** [hashicorp/nomad#2595] opened 2017-04-27 16:27 UTC
### Nomad version
Nomad v0.5.6

### Operating system and Environment details
Linux ip-10-202-1-143 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Issue
We just upgraded to the new consul version and our newly deployed services no longer have http health checks registered to consul. The serf ones are still there. 

### Job file (if appropriate)
```hcl
[
{
Name: "test-app",
PortLabel: "http0",
Tags: [
"dev",
"test-app",
"node",
"b8539b3e10a54e44b913dcd17c34c075319c7827"
],
Checks: [
{
Name: "dev-test-app-alive",
Type: "http",
Command: "",
Args: null,
Path: "/health",
Protocol: "",
PortLabel: "",
Interval: 10000000000,
Timeout: 6000000000,
InitialStatus: ""
}
]
}
]
```

**Comment by sheldonkwok** [comment] 2017-04-27 17:08
Looks like the health checks are a few minutes delayed compared to how it was registered before. Maybe it's a consul issue between 0.8 servers and 0.7 clients.

**Comment by dadgar** [comment] 2017-04-27 20:14
@sheldonkwok Could not reproduce? The check registered the same as a tcp check for me both on 0.5.6 and master

```
"cc1fcba243d4959098ae36b4e325277db849b5e4": {
    "Node": "nomad-server01",
    "CheckID": "cc1fcba243d4959098ae36b4e325277db849b5e4",
    "Name": "what",
    "Status": "critical",
    "Notes": "",
    "Output": "Get http://127.0.0.1:35359/: malformed HTTP status code \"wrong\"",
    "ServiceID": "_nomad-executor-0f012c65-65f8-53de-f5bc-f7c0b3ac5f05-redis-global-redis-check-global-cache",
    "ServiceName": "global-redis-check",
    "CreateIndex": 0,
    "ModifyIndex": 0
  },
```

**Comment by sheldonkwok** [comment] 2017-04-27 20:19
We're in the process of moving the servers over but it's difficult to swap
every machine that we have running Consul at the exact same time. Hopefully
it'll be resolved when we finish moving the servers over. I thought that
the versions were compatible though to allow for a rolling migration. Maybe
this will be better suited for the Consul tracker. Thanks!

**Comment by dadgar** [comment] 2017-04-27 20:21
Makes sense! I thought steady state was like that! Okay I am going to close this issue and if you have issues after migration we can reopen.

**Closed by dadgar** 2017-04-27 20:21 UTC
Labels: waiting-reply
