### ISSUE TITLE
Enabling TLS on nomad removes 'http' tag from consul and does not create 'https' tag.

### ISSUE THREAD

**Issue by xytis** [hashicorp/nomad#2167] opened 2017-01-09 13:45 UTC
### Nomad version
`Nomad v0.5.2`

### Issue
https://github.com/hashicorp/nomad/blob/0f1e5cbea2024b0087cff8da824037ca519a827c/command/agent/agent.go#L466

Once TLS config is enabled, nomad no longer advertises `http` service to consul.
It is reasonable to expect that nomad would advertise `https` tag instead?

### Reproduction steps
Enable TLS config for nomad

**Comment by dadgar** [comment] 2017-01-09 18:00
Duplicate of https://github.com/hashicorp/nomad/issues/2167

**Closed by dadgar** 2017-01-09 18:00 UTC

**Comment by xytis** [comment] 2017-01-10 09:38
Duplicate of self???

**Comment by dadgar** [comment] 2017-01-10 18:41
Haha good catch! Copy paste error: https://github.com/hashicorp/nomad/issues/2144
