### ISSUE TITLE
UI bug when viewing logs of unhealthy task

### ISSUE THREAD

**Issue by Cybernisk** [hashicorp/nomad#8830] opened 2020-09-04 16:03 UTC
### Nomad version
`0.12.0`

### Operating system and Environment details
CentOS 7

### Issue

The logs page of the Nomad UI randomly switched between the tasks of the job's group when one of the tasks is unhealthy/ restating or has any issue.

### Reproduction steps

- You have a job with a single group and a couple of tasks inside that group (for example Postgres, backend, and Nginx)
- Run this job and for example, you have something wrong with one of the tasks (for example backend)
- Go to Nomad UI page something like `http://nomad.local:4646/ui/allocations/<alloc-id>/<backend-task-name>/logs` and after a while (5-10sec), real output of the `stdout` or `stderr` will show you the next task output (Postgres or Nginx), but not the backend. The page was not reloaded, the breadcrumbs didn't change just the output on the black screen changed to another task's output. After a while, it will change to the new task's output. 
That happens only when an allocation has an unhealthy/restarted task. If all tasks are " Started: Task started by a client " status then everything will be with logs output, no random switching to the other task's output.

### Job file (if appropriate)

Tested with a simple job with single group and 3-5 tasks inside that group. Tasks are docker exec.

### Logs

No logs from the client or server cause it is a UI issue. I'm ready to help with finding a bug if I would know how to help.

**Comment by DingoEatingFuzz** [comment] 2020-09-05 02:51
This looks like a duplicate of #8545 which I just spent this evening getting to the bottom of. PR incoming!

**Closed by DingoEatingFuzz** 2020-09-05 02:51 UTC
Labels: stage/duplicate
