### ISSUE TITLE
[UI] Sortable Headers on Variables & Jobs Table Views

### ISSUE THREAD

**Issue by ChefAustin** [hashicorp/nomad#24344] opened 2024-11-01 12:08 UTC
### Proposal
It would be nice if I could sort the 'jobs' and 'variables' table views by any of the column headers (i.e. click 'Name' column's header row and it sorts alphabetically, click it again and it sorts reverse-alphabetically).

Judging by the fact that this already exists on 'servers' and 'clients' table views -- seemingly by way of query string parameters available through the `Sortable` mix-in? -- I'm hoping that this wouldn't require a significant lift (but I've been wrong before [and will be again]). This might also

### Use-cases
Just a small quality-of-life enhancement to allow for more easily finding jobs/variables from the table list without having to filter the displayed items.

### Attempted Solutions
Multiple workarounds exist currently for visually locating a job/var from the table view (filters, search) so, again, this is more of a QoL enhancement and the current lack of this feature is not impairing my use of Nomad very much.

[FWIW: Running Nomad v1.9.1+ent]

**Comment by jrasell** [comment] 2024-11-04 08:49
Hi @ChefAustin and thanks for raising this issue. It sounds like a useful addition, however, I am unsure of how much work would be involved. I'll therefore hand this over to our UI/UX expert.

**Comment by rarrr** [comment] 2024-11-06 12:28
It was exactly like this back in 1.6.1 (might be mistaken on the version), I just today upgraded from that and it's no longer there. Such a weird thing to remove.

**Comment by philrenaud** [comment] 2024-11-06 14:58
Duplicate of https://github.com/hashicorp/nomad/issues/24278

A little context for why we removed this: https://github.com/hashicorp/nomad/issues/24278#issuecomment-2432171621

**Closed by philrenaud** 2024-11-06 14:58 UTC
Labels: type/enhancement, theme/ui, stage/accepted
