### ISSUE TITLE
UI : If alloc-exec is allowed, clicks and web UI are executed, although disabled

### ISSUE THREAD

**Issue by Great-Stone** [hashicorp/nomad#18382] opened 2023-09-04 00:04 UTC
### Nomad version
nomad 1.6.1

### Operating system and Environment details
ubuntu 20.04

### Issue
The alloc-exec was applied, but the button is disabled, which is how it appears. However, clicking it will execute the exec.

### Reproduction steps
```hcl
namespace "*" {
  policy = "write"
  capabilities = [
    "list-jobs",
    "parse-job",
    "read-job",
    "submit-job",
    "dispatch-job",
    "read-logs",
    "read-fs",
    "alloc-exec",
    "alloc-lifecycle",
    "csi-write-volume",
    "csi-mount-volume",
    "list-scaling-policies",
    "read-scaling-policy",
    "read-job-scaling",
    "scale-job"
  ]
  variables {
    path "*" {
      capabilities = ["read"]
    }
  }
}
```

#### Expected Result
If alloc-exec is allowed, the UI will show it as enabled.

#### Actual Result
If alloc-exec is allowed, clicks and web UI are executed, although disabled in the UI

**Comment by jrasell** [comment] 2023-09-05 12:19
Hi @Great-Stone, would you be able to provide more details on your configuration and how to reproduce this? I have been unable to reproduce this locally on either 1.6.1 or 1.6.2-dev.

I ran a local Nomad agent using the dev mode with ACL's enabled and bootstrapped, and ran an example job. I then created an ACL policy using the specification you posted and created an ACL token linked to this policy. I took the created ACL token and used this within the Nomad UI to sign in. When navigating to the job task group page, the exec button is available and works as expected.

**Comment by jrasell** [comment] 2024-09-20 09:51
Closing this as per the resolution comment in #18381 and because there has been no updated comment here. If this is still an issue, please feel free to reopen or create a new issue.

**Closed by jrasell** 2024-09-20 09:51 UTC
Labels: type/bug, stage/waiting-reply
