### ISSUE TITLE
Add ability to specify custom directories in chroot

### ISSUE THREAD

**Issue by dancannon** [hashicorp/nomad#347] opened 2015-10-26 22:13 UTC
Unfortunately we have services that have a dependency on files in an external directory and to get our services to run in Nomad I have had to fork nomad and add out directory to the list of chroot directories manually (https://github.com/dancannon/nomad/commit/8b6a394601784e69237c5aee5bf317d57473f491)

It would be nice to specify a list of environments in the driver config which are mounted when the service starts. I imagine this could also be useful for stateful services but I am interested to hear what other people think.

**Comment by dadgar** [comment] 2015-10-26 22:25
Thanks for filing this! Definitely something we want to expose. I just want to clarify one thing. The way the chroot is created is that it creates hard links to files inside those directories and when that fails it copies that the data. So if you including a folder that was less a NFS mount for your persistent data you would not have the expected behavior (it would just copy everything). We need a separate notion for mounts to accomplish that use case (something we are planning for future versions)

**Comment by dancannon** [comment] 2015-10-26 22:34
Thanks thats great to hear. Ill be honest my version was just a hack to get something working. Our services currently require some config files in a certain directory so having read only (or at least non-permanent) access is not an issue.

Slightly unrelated but I had a quick look into this issue and noticed that driver config has the type `map[string]string`, how would you see setting config for something like this mapping of directories? Would you have the directory mapping in a string, for example `dir:mapping dir2:mapping`and then parse this string when loading the config?

**Comment by cbednarski** [comment] 2015-10-26 23:19
> Slightly unrelated but I had a quick look into this issue and noticed that driver config has the type map[string]string, how would you see setting config for something like this mapping of directories? 

@dancannon This is in design phase for us and is not in the current dev cycle so I don't want to get into specifics that may change, but I think we will pass this into the driver via a specialized data structure, not as key-value pairs.

**Comment by dancannon** [comment] 2015-10-26 23:21
@cbednarski Ok sounds good, I am just trying to understand how the internals work as I am really interested in the project.

**Comment by cbednarski** [comment] 2015-10-26 23:25
@dancannon For some examples:

1. [Network configuration](https://github.com/hashicorp/nomad/blob/master/jobspec/test-fixtures/multi-network.hcl#L11-L21)
2. [How we represent this internally](https://github.com/hashicorp/nomad/blob/master/nomad/structs/structs.go#L614-L623)
3. [How it's used by a driver](https://github.com/hashicorp/nomad/blob/master/client/driver/docker.go#L186-L219)

**Comment by bsoutham** [comment] 2015-10-28 17:15
Another example -- a simple Spring Boot app needs to find a "/tmp" directory in order to startup.  Currently it fails with

```org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to create Tomcat tempdir. java.io.tmpdir is set to /tmp
```

So just the simple ability to specify a directory that is created is useful.

**Comment by dadgar** [comment] 2015-10-29 17:06
@bsoutham: Is it possible to create the temp folder? The directory structure in the chroot is a starting point. The application should be able to create anything it needs

**Comment by bsoutham** [comment] 2015-11-03 22:49
@dadgar With the Spring Boot -- no.  It is starting tomcat to handle connections to the app, which occurs automatically, before the actual app is started.  The app doesn't have a chance to create a directory, because it fails prior to even running any code that I've written.  It fails in the Spring bootstrapping, over which I don't have control.  The directory needs to exist prior to being executed.

**Comment by diptanu** [comment] 2016-08-11 00:08
This was fixed via #1518

**Closed by diptanu** 2016-08-11 00:08 UTC
Labels: driver/exec, enhancement
