### ISSUE TITLE
Feature Request: Add exec option for change_mode

### ISSUE THREAD

**Issue by mr-karan** [hashicorp/nomad#10021] opened 2021-02-12 05:01 UTC
## Feature Request

Currently [`change_mode`](https://www.nomadproject.io/docs/job-specification/template#change_mode) supports `noop`, `restart` and `signal`. 

I propose another option `exec`, which can run arbitrary commands provided by the user.

A simple use case:

An application supports reloading via running `./my-script.sh --reload` but doesn't support signal handling. In this case it might be useful for such an option to exist so the user can give their `command` and `arguments` and Nomad executes them. 

I believe this can be done for `docker` task driver however I'm unsure about other drivers. 

Would like to hear from the community and maintainers if this feature has enough usecases to be considered? :)

Thanks!

**Comment by rkettelerij** [comment] 2021-02-12 12:22
There's already a feature request for this: #2707. I agree this would be very useful. I've encountered the need for this a few times. Would be nice to execute a script or HTTP call when a templates changes.

**Comment by tgross** [comment] 2021-02-12 20:30
Hi folks! There's some interesting technical implications of this because of how we embed consul-template as a library, but it does sound like a cool idea. I'm going to close this as a duplicate of #2707, but please feel free to give 👍 and use cases on that issue -- our product management team uses those to help prioritize what we should be working on!

**Closed by tgross** 2021-02-12 20:30 UTC
