### ISSUE TITLE
server-members doesn't work when some of regions are unreachable

### ISSUE THREAD

**Issue by Ashald** [hashicorp/nomad#2473] opened 2017-03-23 19:40 UTC
If filing a bug please include the following:

### Nomad version
`0.5.4`

### Operating system and Environment details
Centos7

### Issue
We have 2 Nomad regions, each of them a separate subnet: 10.10/16 and 10.40/16. When one of the regions is down, the following command fails:
```
% nomad server-members
Error determining leaders: Unexpected response code: 500 (rpc error: failed to get conn: dial tcp 10.40.1.2:4647: getsockopt: network is unreachable)
```

### Expected Behavior
Command shows information only for available region(s).

**Comment by dadgar** [comment] 2017-03-23 19:53
Duplicate of https://github.com/hashicorp/nomad/issues/1515

**Comment by Ashald** [comment] 2017-03-23 19:54
Ooops, I'm sorry for duplicate. :(

**Closed by dadgar** 2017-03-23 19:53 UTC
