### ISSUE TITLE
worker: failed to dequeue evaluation: error="rpc error: Permission denied" after upgrade to 1.7.1

### ISSUE THREAD

**Issue by kevinschoonover** [hashicorp/nomad#19405] opened 2023-12-09 07:47 UTC
### Nomad version
```
> nomad version
Nomad v1.7.1
BuildDate 2023-12-08T18:11:21Z
Revision 608e719430038cdeb5fe108536d90cf88a8540e3
```

### Operating system and Environment details
```
> uname -a
Linux 6.1.0-9-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux
```

### Issue
After upgrading to 1.7.1, I begin seeing the following with a fresh nomad server cluster with ACL enabled and bootstrapped

`Dec 09 07:40:48 vps-5f87f092 nomad[1273434]: worker: failed to dequeue evaluation: worker_id=124ce3e0-3840-b1b0-6cef-fcf99619d0c9 error="rpc error: Permission denied"`

restarting the nomad server does not fix the issue, but downgrading to 1.6.4 the problem goes away when the leader that is elected is a 1.6.4 node.

In the logs below you can see it affecting the nomad server even when its 1.6.4 until the leader is re-elected to another 1.6.4 node
```
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]: ==> Nomad agent configuration:
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:        Advertise Addrs: HTTP: 100.91.63.45:4646; RPC: 100.91.63.45:4647; Serf: 100.91.63.45:4648
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:             Bind Addrs: HTTP: [100.91.63.45:4646 127.0.0.1:4646]; RPC: 100.91.63.45:4647; Serf: 100.91.63.45:4648
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:                 Client: false
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:              Log Level: INFO
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:                Node Id: 1878ea3d-1a86-bdef-6ff9-e52d31747022
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:                 Region: global (DC: ovh-us-west-or-fed)
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:                 Server: true
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:                Version: 1.6.4
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]: ==> Nomad agent started! Log data will stream in below:
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:40.312Z [INFO]  nomad: setting up raft bolt store: no_freelist_sync=false
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:40.314Z [INFO]  nomad.raft: initial configuration: index=1 servers="[{Suffrage:Voter ID:561a918a-3b47-3fe9-e126-12d24b764dd6 Address:100.83.171.64:4647} {Suffrage:Voter ID:03414442-8500-36f1-1fa5-849e57e4025f Address:100.91.63.45:4647} {Suffrage:Voter ID:1472f6e8-0169-fd84-9e38-be6ee6b81e6e Address:100.90.116.76:4647}]"
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:40.314Z [INFO]  nomad.raft: entering follower state: follower="Node at 100.91.63.45:4647 [Follower]" leader-address= leader-id=
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:40.315Z [INFO]  nomad: serf: EventMemberJoin: vps-5f87f092.global 100.91.63.45
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:40.315Z [INFO]  nomad: starting scheduling worker(s): num_workers=4 schedulers=["_core", "service", "batch", "system"]
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:40.315Z [INFO]  nomad: started scheduling worker(s): num_workers=4 schedulers=["_core", "service", "batch", "system"]
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:40.316Z [INFO]  nomad: serf: Attempting re-join to previously known node: vps-90107b47.global: 100.90.116.76:4648
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:40.316Z [INFO]  nomad: adding server: server="vps-5f87f092.global (Addr: 100.91.63.45:4647) (DC: ovh-us-west-or-fed)"
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:40.319Z [WARN]  nomad: memberlist: Refuting an alive message for 'vps-5f87f092.global' (100.91.63.45:4648) meta:([255 139 166 114 101 103 105 111 110 166 103 108 111 98 97 108 163 118 115 110 161 49 168 114 112 99 95 97 100 100 114 172 49 48 48 46 57 49 46 54 51 46 52 53 164 112 111 114 116 164 52 54 52 55 166 101 120 112 101 99 116 161 51 164 114 111 108 101 165 110 111 109 97 100 162 100 99 178 111 118 104 45 117 115 45 119 101 115 116 45 111 114 45 102 101 100 165 98 117 105 108 100 165 49 46 54 46 52 168 114 101 118 105 115 105 111 110 218 0 40 100 98 100 53 102 51 54 97 50 52 97 57 50 52 101 50 98 97 52 100 100 54 49 57 53 97 102 54 97 52 53 99 57 50 50 97 99 56 99 54 168 114 97 102 116 95 118 115 110 161 51 162 105 100 218 0 36 48 51 52 49 52 52 52 50 45 56 53 48 48 45 51 54 102 49 45 49 102 97 53 45 56 52 57 101 53 55 101 52 48 50 53 102] VS [255 139 164 114 111 108 101 165 110 111 109 97 100 165 98 117 105 108 100 165 49 46 54 46 52 168 114 101 118 105 115 105 111 110 218 0 40 100 98 100 53 102 51 54 97 50 52 97 57 50 52 101 50 98 97 52 100 100 54 49 57 53 97 102 54 97 52 53 99 57 50 50 97 99 56 99 54 168 114 97 102 116 95 118 115 110 161 51 162 105 100 218 0 36 48 51 52 49 52 52 52 50 45 56 53 48 48 45 51 54 102 49 45 49 102 97 53 45 56 52 57 101 53 55 101 52 48 50 53 102 164 112 111 114 116 164 52 54 52 55 166 114 101 103 105 111 110 166 103 108 111 98 97 108 162 100 99 178 111 118 104 45 117 115 45 119 101 115 116 45 111 114 45 102 101 100 163 118 115 110 161 49 168 114 112 99 95 97 100 100 114 172 49 48 48 46 57 49 46 54 51 46 52 53 166 101 120 112 101 99 116 161 51]), vsn:([1 5 2 2 5 4] VS [1 5 2 2 5 4])
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:40.320Z [INFO]  nomad: serf: EventMemberJoin: vps-90107b47.global 100.90.116.76
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:40.320Z [INFO]  nomad: serf: EventMemberJoin: vps-47db81af.global 100.83.171.64
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:  nomad: memberlist: Refuting an alive message for 'vps-5f87f092.global' (100.91.63.45:4648) meta:([255 139 166 114 101 103 105 111 110 166 103 108 111 98 97 108 163 118 115 110 161 49 168 114 112 99 95 97 100 100 114 172 49 48 48 46 57 49 46 54 51 46 52 53 164 112 111 114 116 164 52 54 52 55 166 101 120 112 101 99 116 161 51 164 114 111 108 101 165 110 111 109 97 100 162 100 99 178 111 118 104 45 117 115 45 119 101 115 116 45 111 114 45 102 101 100 165 98 117 105 108 100 165 49 46 54 46 52 168 114 101 118 105 115 105 111 110 218 0 40 100 98 100 53 102 51 54 97 50 52 97 57 50 52 101 50 98 97 52 100 100 54 49 57 53 97 102 54 97 52 53 99 57 50 50 97 99 56 99 54 168 114 97 102 116 95 118 115 110 161 51 162 105 100 218 0 36 48 51 52 49 52 52 52 50 45 56 53 48 48 45 51 54 102 49 45 49 102 97 53 45 56 52 57 101 53 55 101 52 48 50 53 102] VS [255 139 164 114 111 108 101 165 110 111 109 97 100 165 98 117 105 108 100 165 49 46 54 46 52 168 114 101 118 105 115 105 111 110 218 0 40 100 98 100 53 102 51 54 97 50 52 97 57 50 52 101 50 98 97 52 100 100 54 49 57 53 97 102 54 97 52 53 99 57 50 50 97 99 56 99 54 168 114 97 102 116 95 118 115 110 161 51 162 105 100 218 0 36 48 51 52 49 52 52 52 50 45 56 53 48 48 45 51 54 102 49 45 49 102 97 53 45 56 52 57 101 53 55 101 52 48 50 53 102 164 112 111 114 116 164 52 54 52 55 166 114 101 103 105 111 110 166 103 108 111 98 97 108 162 100 99 178 111 118 104 45 117 115 45 119 101 115 116 45 111 114 45 102 101 100 163 118 115 110 161 49 168 114 112 99 95 97 100 100 114 172 49 48 48 46 57 49 46 54 51 46 52 53 166 101 120 112 101 99 116 161 51]), vsn:([1 5 2 2 5 4] VS [1 5 2 2 5 4])
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:  nomad: serf: EventMemberJoin: vps-90107b47.global 100.90.116.76
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:40.320Z [INFO]  nomad: serf: Re-joined to previously known node: vps-90107b47.global: 100.90.116.76:4648
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:40.320Z [INFO]  nomad: adding server: server="vps-90107b47.global (Addr: 100.90.116.76:4647) (DC: ovh-us-west-or-fed)"
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:40.320Z [INFO]  nomad: adding server: server="vps-47db81af.global (Addr: 100.83.171.64:4647) (DC: ovh-us-west-or-fed)"
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:  nomad: serf: EventMemberJoin: vps-47db81af.global 100.83.171.64
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:  nomad: serf: Re-joined to previously known node: vps-90107b47.global: 100.90.116.76:4648
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:  nomad: adding server: server="vps-90107b47.global (Addr: 100.90.116.76:4647) (DC: ovh-us-west-or-fed)"
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:  nomad: adding server: server="vps-47db81af.global (Addr: 100.83.171.64:4647) (DC: ovh-us-west-or-fed)"
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:40.346Z [INFO]  nomad.vault: successfully renewed token: next_renewal=29m59.999972296s
Dec 09 07:43:40 vps-5f87f092 nomad[1273612]:  nomad.vault: successfully renewed token: next_renewal=29m59.999972296s
Dec 09 07:43:49 vps-5f87f092 nomad[1273612]: ==> Newer Nomad version available: 1.7.1 (currently running: 1.6.4)
Dec 09 07:43:50 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:50.575Z [ERROR] worker: failed to dequeue evaluation: worker_id=884707e3-ad43-fafd-eeb8-30ea8e79f71b error="rpc error: Permission denied"
Dec 09 07:43:50 vps-5f87f092 nomad[1273612]: worker: failed to dequeue evaluation: worker_id=884707e3-ad43-fafd-eeb8-30ea8e79f71b error="rpc error: Permission denied"
Dec 09 07:43:50 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:50.665Z [ERROR] worker: failed to dequeue evaluation: worker_id=4166599b-fabb-77a5-60cb-1b69f6c38d67 error="rpc error: Permission denied"
Dec 09 07:43:50 vps-5f87f092 nomad[1273612]: worker: failed to dequeue evaluation: worker_id=4166599b-fabb-77a5-60cb-1b69f6c38d67 error="rpc error: Permission denied"
Dec 09 07:43:50 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:50.799Z [ERROR] worker: failed to dequeue evaluation: worker_id=e1589550-1e91-c6e2-1571-fc2aa0f21eaf error="rpc error: Permission denied"
Dec 09 07:43:50 vps-5f87f092 nomad[1273612]: worker: failed to dequeue evaluation: worker_id=e1589550-1e91-c6e2-1571-fc2aa0f21eaf error="rpc error: Permission denied"
Dec 09 07:43:50 vps-5f87f092 nomad[1273612]:     2023-12-09T07:43:50.854Z [ERROR] worker: failed to dequeue evaluation: worker_id=53af457d-d683-2565-5e24-3cf30f5d24e5 error="rpc error: Permission denied"
Dec 09 07:43:50 vps-5f87f092 nomad[1273612]: worker: failed to dequeue evaluation: worker_id=53af457d-d683-2565-5e24-3cf30f5d24e5 error="rpc error: Permission denied"
Dec 09 07:44:00 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:00.577Z [ERROR] worker: failed to dequeue evaluation: worker_id=884707e3-ad43-fafd-eeb8-30ea8e79f71b error="rpc error: Permission denied"
Dec 09 07:44:00 vps-5f87f092 nomad[1273612]: worker: failed to dequeue evaluation: worker_id=884707e3-ad43-fafd-eeb8-30ea8e79f71b error="rpc error: Permission denied"
Dec 09 07:44:00 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:00.666Z [ERROR] worker: failed to dequeue evaluation: worker_id=4166599b-fabb-77a5-60cb-1b69f6c38d67 error="rpc error: Permission denied"
Dec 09 07:44:00 vps-5f87f092 nomad[1273612]: worker: failed to dequeue evaluation: worker_id=4166599b-fabb-77a5-60cb-1b69f6c38d67 error="rpc error: Permission denied"
Dec 09 07:44:00 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:00.801Z [ERROR] worker: failed to dequeue evaluation: worker_id=e1589550-1e91-c6e2-1571-fc2aa0f21eaf error="rpc error: Permission denied"
Dec 09 07:44:00 vps-5f87f092 nomad[1273612]: worker: failed to dequeue evaluation: worker_id=e1589550-1e91-c6e2-1571-fc2aa0f21eaf error="rpc error: Permission denied"
Dec 09 07:44:00 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:00.855Z [ERROR] worker: failed to dequeue evaluation: worker_id=53af457d-d683-2565-5e24-3cf30f5d24e5 error="rpc error: Permission denied"
Dec 09 07:44:00 vps-5f87f092 nomad[1273612]: worker: failed to dequeue evaluation: worker_id=53af457d-d683-2565-5e24-3cf30f5d24e5 error="rpc error: Permission denied"
Dec 09 07:44:10 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:10.579Z [ERROR] worker: failed to dequeue evaluation: worker_id=884707e3-ad43-fafd-eeb8-30ea8e79f71b error="rpc error: Permission denied"
Dec 09 07:44:10 vps-5f87f092 nomad[1273612]: worker: failed to dequeue evaluation: worker_id=884707e3-ad43-fafd-eeb8-30ea8e79f71b error="rpc error: Permission denied"
Dec 09 07:44:10 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:10.668Z [ERROR] worker: failed to dequeue evaluation: worker_id=4166599b-fabb-77a5-60cb-1b69f6c38d67 error="rpc error: Permission denied"
Dec 09 07:44:10 vps-5f87f092 nomad[1273612]: worker: failed to dequeue evaluation: worker_id=4166599b-fabb-77a5-60cb-1b69f6c38d67 error="rpc error: Permission denied"
Dec 09 07:44:10 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:10.803Z [ERROR] worker: failed to dequeue evaluation: worker_id=e1589550-1e91-c6e2-1571-fc2aa0f21eaf error="rpc error: Permission denied"
Dec 09 07:44:10 vps-5f87f092 nomad[1273612]: worker: failed to dequeue evaluation: worker_id=e1589550-1e91-c6e2-1571-fc2aa0f21eaf error="rpc error: Permission denied"
Dec 09 07:44:10 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:10.857Z [ERROR] worker: failed to dequeue evaluation: worker_id=53af457d-d683-2565-5e24-3cf30f5d24e5 error="rpc error: Permission denied"
Dec 09 07:44:10 vps-5f87f092 nomad[1273612]: worker: failed to dequeue evaluation: worker_id=53af457d-d683-2565-5e24-3cf30f5d24e5 error="rpc error: Permission denied"
Dec 09 07:44:20 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:20.580Z [ERROR] worker: failed to dequeue evaluation: worker_id=884707e3-ad43-fafd-eeb8-30ea8e79f71b error="rpc error: Permission denied"
Dec 09 07:44:20 vps-5f87f092 nomad[1273612]: worker: failed to dequeue evaluation: worker_id=884707e3-ad43-fafd-eeb8-30ea8e79f71b error="rpc error: Permission denied"
Dec 09 07:44:20 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:20.669Z [ERROR] worker: failed to dequeue evaluation: worker_id=4166599b-fabb-77a5-60cb-1b69f6c38d67 error="rpc error: Permission denied"
Dec 09 07:44:20 vps-5f87f092 nomad[1273612]: worker: failed to dequeue evaluation: worker_id=4166599b-fabb-77a5-60cb-1b69f6c38d67 error="rpc error: Permission denied"
Dec 09 07:44:20 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:20.804Z [ERROR] worker: failed to dequeue evaluation: worker_id=e1589550-1e91-c6e2-1571-fc2aa0f21eaf error="rpc error: Permission denied"
Dec 09 07:44:20 vps-5f87f092 nomad[1273612]: worker: failed to dequeue evaluation: worker_id=e1589550-1e91-c6e2-1571-fc2aa0f21eaf error="rpc error: Permission denied"
Dec 09 07:44:20 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:20.859Z [ERROR] worker: failed to dequeue evaluation: worker_id=53af457d-d683-2565-5e24-3cf30f5d24e5 error="rpc error: Permission denied"
Dec 09 07:44:20 vps-5f87f092 nomad[1273612]: worker: failed to dequeue evaluation: worker_id=53af457d-d683-2565-5e24-3cf30f5d24e5 error="rpc error: Permission denied"
Dec 09 07:44:24 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:24.568Z [INFO]  nomad: serf: EventMemberUpdate: vps-47db81af.global
Dec 09 07:44:24 vps-5f87f092 nomad[1273612]:  nomad: serf: EventMemberUpdate: vps-47db81af.global
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:25.003Z [WARN]  nomad.raft: heartbeat timeout reached, starting election: last-leader-addr=100.83.171.64:4647 last-leader-id=561a918a-3b47-3fe9-e126-12d24b764dd6
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:25.003Z [INFO]  nomad.raft: entering candidate state: node="Node at 100.91.63.45:4647 [Candidate]" term=33
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:  nomad.raft: heartbeat timeout reached, starting election: last-leader-addr=100.83.171.64:4647 last-leader-id=561a918a-3b47-3fe9-e126-12d24b764dd6
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:  nomad.raft: entering candidate state: node="Node at 100.91.63.45:4647 [Candidate]" term=33
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:25.011Z [INFO]  nomad.raft: election won: term=33 tally=2
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:25.011Z [INFO]  nomad.raft: entering leader state: leader="Node at 100.91.63.45:4647 [Leader]"
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:  nomad.raft: election won: term=33 tally=2
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:25.011Z [INFO]  nomad.raft: added peer, starting replication: peer=561a918a-3b47-3fe9-e126-12d24b764dd6
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:25.011Z [INFO]  nomad.raft: added peer, starting replication: peer=1472f6e8-0169-fd84-9e38-be6ee6b81e6e
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:  nomad.raft: entering leader state: leader="Node at 100.91.63.45:4647 [Leader]"
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:25.011Z [INFO]  nomad: cluster leadership acquired
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:  nomad.raft: added peer, starting replication: peer=561a918a-3b47-3fe9-e126-12d24b764dd6
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:  nomad.raft: added peer, starting replication: peer=1472f6e8-0169-fd84-9e38-be6ee6b81e6e
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:  nomad: cluster leadership acquired
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:25.013Z [INFO]  nomad.raft: pipelining replication: peer="{Voter 561a918a-3b47-3fe9-e126-12d24b764dd6 100.83.171.64:4647}"
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:  nomad.raft: pipelining replication: peer="{Voter 561a918a-3b47-3fe9-e126-12d24b764dd6 100.83.171.64:4647}"
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:25.017Z [INFO]  nomad.raft: pipelining replication: peer="{Voter 1472f6e8-0169-fd84-9e38-be6ee6b81e6e 100.90.116.76:4647}"
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:  nomad.raft: pipelining replication: peer="{Voter 1472f6e8-0169-fd84-9e38-be6ee6b81e6e 100.90.116.76:4647}"
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:25.023Z [INFO]  nomad: eval broker status modified: paused=false
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:25.023Z [INFO]  nomad: blocked evals status modified: paused=false
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:  nomad: eval broker status modified: paused=false
Dec 09 07:44:25 vps-5f87f092 nomad[1273612]:  nomad: blocked evals status modified: paused=false
Dec 09 07:44:29 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:29.393Z [INFO]  nomad.raft: aborting pipeline replication: peer="{Voter 561a918a-3b47-3fe9-e126-12d24b764dd6 100.83.171.64:4647}"
Dec 09 07:44:29 vps-5f87f092 nomad[1273612]:  nomad.raft: aborting pipeline replication: peer="{Voter 561a918a-3b47-3fe9-e126-12d24b764dd6 100.83.171.64:4647}"
Dec 09 07:44:29 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:29.418Z [ERROR] nomad.raft: failed to heartbeat to: peer=100.83.171.64:4647 backoff time=10ms error=EOF
Dec 09 07:44:29 vps-5f87f092 nomad[1273612]: nomad.raft: failed to heartbeat to: peer=100.83.171.64:4647 backoff time=10ms error=EOF
Dec 09 07:44:29 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:29.453Z [INFO]  nomad.raft: pipelining replication: peer="{Voter 561a918a-3b47-3fe9-e126-12d24b764dd6 100.83.171.64:4647}"
Dec 09 07:44:29 vps-5f87f092 nomad[1273612]:  nomad.raft: pipelining replication: peer="{Voter 561a918a-3b47-3fe9-e126-12d24b764dd6 100.83.171.64:4647}"
Dec 09 07:44:29 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:29.920Z [INFO]  nomad: serf: EventMemberUpdate: vps-47db81af.global
Dec 09 07:44:29 vps-5f87f092 nomad[1273612]:  nomad: serf: EventMemberUpdate: vps-47db81af.global
Dec 09 07:44:31 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:31.024Z [WARN]  nomad.stats_fetcher: error getting server health: server=vps-47db81af.global error="rpc error: stream closed"
Dec 09 07:44:31 vps-5f87f092 nomad[1273612]:  nomad.stats_fetcher: error getting server health: server=vps-47db81af.global error="rpc error: stream closed"
Dec 09 07:44:32 vps-5f87f092 nomad[1273612]:     2023-12-09T07:44:32.025Z [WARN]  nomad.stats_fetcher: failed retrieving server health: server=vps-47db81af.global error="context deadline exceeded"
Dec 09 07:44:32 vps-5f87f092 nomad[1273612]:  nomad.stats_fetcher: failed retrieving server health: server=vps-47db81af.global error="context deadline exceeded"
```

**Comment by roman-vynar** [comment] 2023-12-09 12:38
Actually, I have seen this too. I thought it was only me.
After upgrade 1.3.5 > 1.7.0 with ACL enabled:

Server complains on:
```
    2023-12-08T16:08:54.298Z [ERROR] worker: failed to dequeue evaluation: worker_id=d07d842a-6ab8-6ac5-fb99-84086d803212 error="rpc error: Permission denied"
    2023-12-08T16:08:54.371Z [ERROR] worker: failed to dequeue evaluation: worker_id=103247d7-f401-d4a7-f08c-d46b957296ec error="rpc error: Permission denied"
    2023-12-08T16:09:04.300Z [ERROR] worker: failed to dequeue evaluation: worker_id=d07d842a-6ab8-6ac5-fb99-84086d803212 error="rpc error: Permission denied"
```
Client tries to:
```
    2023-12-08T16:11:20.268Z [ERROR] client.rpc: error performing RPC to server which is not safe to automatically retry: error="rpc error: Permission denied" rpc=Alloc.GetAllocs server=10.0.7.75:4647
    2023-12-08T16:11:20.268Z [ERROR] client: error querying updated allocations: error="rpc error: Permission denied"
```

In my case it was a working cluster which basically got frozen with the above errors after upgrade.

**Comment by tgross** [comment] 2023-12-10 13:51
Hi @kevinschoonover and @roman-vynar! Sorry to hear about this. The authentication code path got a major refactoring in 1.7.0, but it should have been a no-op change for you. We have a nightly E2E cluster that gets tested with mTLS with the strict [`verify_server_hostname=true`](https://github.com/hashicorp/nomad/blob/main/e2e/terraform/etc/nomad.d/tls.hcl#L12). So my first suspicion is that we're incorrectly handling the less-strict configuration where that's `false` (the default, see [here](https://developer.hashicorp.com/nomad/docs/configuration/tls#verify_server_hostname)).

I'll dig into this first thing Monday morning.

**Comment by roman-vynar** [comment] 2023-12-11 08:45
Thanks Tim! We have this config:
```
tls {
  rpc  = true
  ca_file = "/etc/ssl/certs/ca-certificates.crt"
  cert_file = "/xxx.bundle.crt.pem"
  key_file = "/xxx.key.pem"
  tls_prefer_server_cipher_suites = true
}
```
So we don't set `verify_server_hostname` which is `false` by default.

**Comment by tgross** [comment] 2023-12-11 15:28
I've got a patch open for this in #19425.

I've been able to reproduce the failure described in here for servers and test the fix in this patch:
* Start with servers running 1.6.4 with `tls.verify_server_hostname=false`, but with one server using a cert for `client.global.nomad`
* Update to 1.7.0, and find that one server can connect but cannot authenticate, as described in #19405. So it immediately fails to dequeue evals.
* Update to a build with this patch and everything works fine.

The error message shown for clients above I was not able to reproduce exactly, but I know from working on the unit tests for the big auth refactor that the error message can actually vary slightly depending on timing and whether you get the EOF before the "permission denied" error gets written (we had to account for this in the tests). After the patch, everything seems to work fine.

@roman-vynar if you're able to build the patch in #19425 and verify it against the certs you have in your environment, that'd go a long ways towards building confidence that the patch entirely fixes this bug.

**Comment by roman-vynar** [comment] 2023-12-11 16:16
Thanks Tim, I will check the patch and let you know.

**Comment by tgross** [comment] 2023-12-11 19:21
In the meantime I've merged that patch. That's going to close this issue (b/c GitHub automation being what it is), but if please let us know either way.

**Closed** 2023-12-11 19:20 UTC
Labels: type/bug, theme/tls, theme/auth

**Comment by roman-vynar** [comment] 2023-12-12 11:17
Looks like it solves this particular issue.
