### ISSUE TITLE
Not uniq NOMAD_ALLOC_INDEX with same job version

### ISSUE THREAD

**Issue by valodzka** [hashicorp/nomad#12768] opened 2022-04-23 08:58 UTC
### Nomad version
Nomad v1.2.6 (a6c6b475db5073e33885377b4a5c733e1161020c) / Linux 5.10.0-12-amd64

### Issue

I noticed that sometimes during deployment of a job with a large number of groups nomad creates multiple allocations with the same alloc index. Deploy isn't using canaries. This happens infrequently, but if happends it persists - new deploy doesn't correct alloc index, duplication remains. The only way I found to fix the issue is to reset the number of allocations in the task group to one, redeploy, return previous number, redeploy.

Any idea where to look? Are there ways to reset allocation without reset hack?

### Reproduction steps

`nomad job allocs -t '{{ range . }}{{ if and (eq .ClientStatus "running") (eq .TaskGroup "client")  }}{{ print .ID }} {{ print .JobVersion }} {{ print .Name }} {{ println '' }}{{ end }}{{ end }}' bk | sort -k3`

```
a8a12037-c281-bced-1a8c-910a0fea0093 1048 bk.client[0]
8d9c0c57-9cd1-d0c6-be87-74b10e72e500 1048 bk.client[1]
f2fcb07a-a1e2-3353-6caf-096b8a8210a8 1048 bk.client[10]
aa5fea25-1a2a-8733-215e-8b002e0c98c8 1048 bk.client[11]
619aa5e2-3d53-72c1-c2db-c153d76d367a 1048 bk.client[12]
cafb37cb-8615-8d95-31b0-ee5925d56190 1048 bk.client[13]
d6dda228-4845-f7a8-fd34-c864d50b6a4f 1048 bk.client[14]
866dee09-d4e1-225e-737d-929e9e67f30e 1048 bk.client[15]
ca14a748-be3d-28d9-1069-9e0e530550fd 1048 bk.client[16]
8dda4e9e-dbe3-aa11-5063-7b327a089f94 1048 bk.client[17]
a0157881-bad2-237c-ead5-8a1fc8959052 1048 bk.client[18]
5af1d884-6ba3-0aa1-3a42-e1cbfdd784df 1048 bk.client[19]
2f730dbc-bd82-22d3-ac21-cee3b4092047 1048 bk.client[2]
a98d533f-9100-3211-8393-ed47ed97ad76 1048 bk.client[20]
03a6864e-4b62-4e2d-1e6f-b96af0864690 1048 bk.client[21]
b787f6e6-8765-cf67-99d0-ba33601f3667 1048 bk.client[22]
6abc1ffc-a511-cce0-c0d7-8d46350b4432 1048 bk.client[23]
f2468792-0ccd-a79f-4cc1-c322f5c2e3b3 1048 bk.client[23]
4abebb20-1f7b-2346-5e5d-ebeecc19c6d8 1048 bk.client[25]
f19058ca-fe8c-b864-04c3-d0c500fe4c04 1048 bk.client[3]
e4700c5a-f6b7-5b0d-8bd1-7f5b72e2db10 1048 bk.client[4]
319a47ea-4cab-9e60-b77f-28c382001c7c 1048 bk.client[5]
8ce6030d-c07c-a833-fb97-bf3e3a087d85 1048 bk.client[6]
d079fc00-2342-829e-673e-d139e86f601e 1048 bk.client[7]
592a1038-d583-9a9e-6c0f-7b9ac0712e2d 1048 bk.client[8]
c63e42cb-5434-6291-a921-1fae2dd86571 1048 bk.client[9]
```

Notice duplicate **bk.client[23]** and missing 24.

#### Expected Result

NOMAD_ALLOC_INDEX must be unique per job version.

#### Actual Result

NOMAD_ALLOC_INDEX repeated sometimes.

### Nomad Client/Server logs (if appropriate)

I didn't see any errors in log during deploy.

**Comment by lgfa29** [comment] 2022-04-27 15:55
Thanks for report @valodzka. 

I believe this is a duplicate of https://github.com/hashicorp/nomad/issues/10727 so I'm going to close this one since there is a lot of context there already.

Feel free to add more information to that issue, or let me know if you think this is something different and we can re-open this.

**Closed by lgfa29** 2022-04-27 15:55 UTC
Labels: type/bug
