### ISSUE TITLE
Hitting exec on UI task group page results in wrong allocation ID being used for exec

### ISSUE THREAD

**Issue by jwoglom** [hashicorp/nomad#14362] opened 2022-08-28 06:21 UTC
### Nomad version
Output from `nomad version`

```
Nomad v1.3.2 (bf602974112964e9691729f3f0716ff2bcdb3b44)
```

### Operating system and Environment details

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
```

Ubuntu virtual machine running through KVM/Libvirt on a TrueNAS Scale host

### Issue

When navigating to a task group inside a periodic task and clicking on the Exec button, a window with "Select a task to start your session." is shown with a list of tasks inside the task group on the left. When the desired task is selected, the window displays a message which allows the entrypoint command to be modified, and pre-fills in the task ID with the following message:

```
Multiple instances of this task are running. The allocation below was selected by random draw.

Customize your command, then hit ‘return’ to run.

$ nomad alloc exec -i -t -task default 070f2c4c /bin/bash
```

When selecting a task group which is not the first, **the task in the first task group has its allocation ID filled and is connected to in the exec session** instead of the task inside the correct task group.

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/192620/187060395-22bcd644-ef12-40e1-ab32-62c4c3e7a7b5.png">

### Reproduction steps

With job `example-job`, containing three job groups `aaa`, `bbb`, and `ccc`; each with a task named `default`.

#### Expected Result

I launch an invocation of the job via Jobs > example-job > Force Launch.

I navigate to Jobs > example-job > periodic-XXXX and click on the bbb task group, then then Exec button. The exec window shows up:

<img width="975" alt="image" src="https://user-images.githubusercontent.com/192620/187060436-7c505750-8378-4278-ab49-2953e4c0d4fb.png">

The bbb task group is already expanded, so I click on "default" underneath bbb.

The allocation ID which shows up should be the allocation ID of the "default" task within the bbb task group.

#### Actual Result

<img width="976" alt="image" src="https://user-images.githubusercontent.com/192620/187060450-8117b8a2-2e08-47f1-80c8-d3ca45ccc025.png">

The allocation ID is the allocation ID of the "default" task **within the aaa task group**, despite the UI highlighting the default task inside the bbb task group AND the URL containing bbb (`http://nomad-vm:4646/ui/exec/example-job%2Fperiodic-1661667120/bbb/default`)

This is dangerous as all indications in the UI appear to show to the user that they are connected to the task within a different task group than they actually are.

### Job file (if appropriate)

```
job "example-job" {
    datacenters = ["dc1"]

    type = "batch"

    reschedule {
        attempts       = 5
        interval       = "6h"
        delay          = "30s"
        delay_function = "exponential"
        max_delay      = "30m"
        unlimited      = false
    }

    periodic {
        cron = "8,20 0 * * *"
        prohibit_overlap = true
    }

    group "aaa" {
        count = 1
        task "default" {
            driver = "docker"

            config {
                image = "alpine"
                entrypoint = ["sh"]
                args = ["-c", "sleep infinity"]
            }
            
            template {
                destination = "/local/whoami"
                data = "aaa"
            }
        }
    }

    group "bbb" {
        count = 1

        task "default" {
            driver = "docker"

            config {
                image = "alpine"
                entrypoint = ["sh"]
                args = ["-c", "sleep infinity"]
            }
            
            template {
                destination = "/local/whoami"
                data = "bbb"
            }
        }
    }

    group "ccc" {
        count = 1

        task "default" {
            driver = "docker"

            config {
                image = "alpine"
                entrypoint = ["sh"]
                args = ["-c", "sleep infinity"]
            }
            
            template {
                destination = "/local/whoami"
                data = "ccc"
            }
        }
    }
}

```

### Nomad Server logs (if appropriate)

n/a, this is a UI bug

### Nomad Client logs (if appropriate)

n/a

**Comment by jwoglom** [comment] 2022-08-28 06:24
I specifically observed this on a task of type `batch`, but have been able to replicate similarly weird behavior with a job of type `service`. For example, here is an exec to the ccc default task which actually has the bbb default task's task ID.

<img width="975" alt="image" src="https://user-images.githubusercontent.com/192620/187060680-adce855e-50bf-466b-b65e-05a1c47a8f96.png">

**Comment by jwoglom** [comment] 2022-08-28 06:30
I was also able to replicate this bug on the latest v1.3.4, which appears to contain the related bug of saying I don't have permission to run Exec despite the fact I can still click on the button an do so, in a standard setup with no ACL settings specified.

**Comment by lgfa29** [comment] 2022-08-31 17:53
Hi @jwoglom 👋 

Thanks for the report. I believe this is the same issue as described in https://github.com/hashicorp/nomad/issues/10962, so I will close this one as a duplicate of that. 

It's currently set for triaging so I would suggest adding a 👍 to that issue as it helps us gauge priority 🙂

**Closed by lgfa29** 2022-08-31 17:53 UTC
Labels: type/bug
