### ISSUE TITLE
Node API eligibility endpoint does not work as documented

### ISSUE THREAD

**Issue by brydoncheyney-slc** [hashicorp/nomad#6420] opened 2019-10-04 10:21 UTC
### Nomad version

0.9.1 (initially observed)
0.9.5 (upgraded, still impacts)

### Operating system and Environment details

CentOS7/RHEL7

> Reproduction steps below extracted from CentOS7 lxc environment

### Issue

The documented [toggle node eligibility](https://www.nomadproject.io/api/nodes.html#toggle-node-eligibility) API endpoint does not work as expected.

Following the documented process will throw a 500 Server Error with, `missing node ID for setting scheduling eligibility` -

> /v1/node/:node_id/eligibility
```json
{
  "Eligibility": "eligible"
}
```

Instead, you *must* pass a payload that includes (the undocumented) NodeID -

> /v1/node/:node_id/eligibility
```json
{
  "NodeID": "U-U-I-D",
  "Eligibility": "eligible"
}
```

As the `:node_id` is already specified, as part of the path, the `NodeID` parameter should not be necessary. If this is not the case, the documentation is incorrect and should include `NodeID` as a parameter passed in the payload.

### Reproduction steps

```
# initial node state is ineligible
[vagrant@nomad ~]$ curl -ks -XGET -H 'X-Nomad-Token: 5ac74102-258c-e795-25d4-12142666135f' https://nomad.service.consul:4646/v1/node/5a92346f-07f1-5441-fd3e-cdb819b7616d | jq -jr '"ID: ",.ID,"\nEligibility: ",.SchedulingEligibility'
ID: 5a92346f-07f1-5441-fd3e-cdb819b7616d
Eligibility: ineligible

# Use node API - as documented - to toggle eligibility - 500 Server Error
[vagrant@nomad ~]$ curl -ks -XPOST -H 'Content-Type: application/json' -H 'X-Nomad-Token: 5ac74102-258c-e795-25d4-12142666135f' https://nomad.service.consul:4646/v1/node/5a92346f-07f1-5441-fd3e-cdb819b7616d/eligibility -d'{"Eligibility": "eligible"}'
rpc error: missing node ID for setting scheduling eligibility

# Use node API to toggle eligibility, including explicit NodeID in payload
[vagrant@nomad ~]$ curl -ks -XPOST -H 'Content-Type: application/json' -H 'X-Nomad-Token: 5ac74102-258c-e795-25d4-12142666135f' https://nomad.service.consul:4646/v1/node/5a92346f-07f1-5441-fd3e-cdb819b7616d/eligibility -d'{"NodeID": "5a92346f-07f1-5441-fd3e-cdb819b7616d", "Eligibility": "eligible"}'
{"EvalCreateIndex":0,"EvalIDs":null,"Index":8585,"NodeModifyIndex":0}

# node state is eligible
[vagrant@nomad ~]$ curl -ks -XGET -H 'X-Nomad-Token: 5ac74102-258c-e795-25d4-12142666135f' https://nomad.service.consul:4646/v1/node/5a92346f-07f1-5441-fd3e-cdb819b7616d | jq -jr '"ID: ",.ID,"\nEligibility: ",.SchedulingEligibility'
ID: 5a92346f-07f1-5441-fd3e-cdb819b7616d
Eligibility: eligible
```

### Nomad Server logs (if appropriate)

```
Oct  4 09:55:56 packer-lxc-centos-7-x64 nomad[31754]: http: request failed: method=POST path=/v1/node/5a92346f-07f1-5441-fd3e-cdb819b7616d/eligibility error="rpc error: missing node ID for setting scheduling eligibility" code=500
Oct  4 09:55:56 packer-lxc-centos-7-x64 nomad-wrapper: 2019-10-04T09:55:56.145Z [ERROR] http: request failed: method=POST path=/v1/node/5a92346f-07f1-5441-fd3e-cdb819b7616d/eligibility error="rpc error: missing node ID for setting scheduling eligibility" code=500
```

**Comment by endocrimes** [comment] 2019-10-07 09:33
Thanks for reporting this, you shouldn't need to provide this twice. We should update it to only use the UUID from the URI.

**Comment by endocrimes** [comment] 2019-10-07 09:38
interestingly, it looks like we already attempt to handle this in the endpoint code (https://github.com/hashicorp/nomad/blob/550e1b1a1e766bd99f420c183110c1fa9e05fefb/command/agent/node_endpoint.go#L159-L181), I'm not sure on first glance why it's broken, because it also looks like it is covered by the test here https://github.com/hashicorp/nomad/blob/550e1b1a1e766bd99f420c183110c1fa9e05fefb/command/agent/node_endpoint_test.go#L373-L382.

**Comment by jrasell** [comment] 2020-03-02 09:44
Hi @brydoncheyney-slc, I have been trying to reproduce this locally without success and was wondering if you were able to provide any additional context that could help me pin point the problem?

So far I have tested across Nomad 0.9.1, 0.9.5 and 0.10.4 on CentOS 7 with ACLs enabled.

**Comment by brydoncheyney-slc** [comment] 2020-03-03 07:47
We've since upgraded to 0.10.x and, after checking again, I cannot seem to replicate the problem... happy for this to be closed, if unable to replicate.

Many thanks for looking at this!

**Comment by jrasell** [comment] 2020-03-03 08:06
Thanks for updating me @brydoncheyney-slc and I am glad you are no longer seeing the behaviour. I'll go ahead and close this issue. If you do happen to come across this problem again, please feel free to re-open and I can pick it back up.

**Closed by jrasell** 2020-03-03 08:06 UTC
Labels: api, bug, good first issue
