### ISSUE TITLE
[feature request] ui/cli: keep original hcl job spec for inspection

### ISSUE THREAD

**Issue by fredrikhgrelland** [hashicorp/nomad#6778] opened 2019-11-26 14:04 UTC
### Nomad version
v0.10.1

### Operating system and Environment details
Centos 7.7

### Issue
Posting a hcl job spec to nomad parses it leaves a _human_ unreadable json, including all implied default stanzas. I would like to extract the original specification from nomad for inspection. Currently this is not possible?

### Job file (if appropriate)
Using a slightly changed example file from https://www.nomadproject.io/docs/job-specification/index.html

```
# This declares a job named "docs". There can be exactly one
# job declaration per job file.
job "docs" {
  # Specify this job should run in the region named "us". Regions
  # are defined by the Nomad servers' configuration.
  #region = "us"

  # Spread the tasks in this job between us-west-1 and us-east-1.
  datacenters = ["green"]

  # Run this job as a "service" type. Each job type has different
  # properties. See the documentation below for more examples.
  type = "service"

  # Specify this job to have rolling updates, two-at-a-time, with
  # 30 second intervals.
  update {
    stagger      = "30s"
    max_parallel = 2
  }

  # A group defines a series of tasks that should be co-located
  # on the same client (host). All tasks within a group will be
  # placed on the same host.
  group "webs" {
    # Specify the number of these tasks we want.
    count = 5

    # Create an individual task (unit of work). This particular
    # task utilizes a Docker container to front a web application.
    task "frontend" {
      # Specify the driver to be "docker". Nomad supports
      # multiple drivers.
      driver = "docker"

      # Configuration is specific to each driver.
      config {
        image = "hashicorp/web-frontend"
      }

      # The service block tells Nomad how to register this service
      # with Consul for service discovery and monitoring.
      service {
        # This tells Consul to monitor the service on the port
        # labelled "http". Since Nomad allocates high dynamic port
        # numbers, we use labels to refer to them.
        port = "http"

        check {
          type     = "http"
          path     = "/health"
          interval = "10s"
          timeout  = "2s"
        }
      }

      # It is possible to set environment variables which will be
      # available to the task when it runs.
      env {
        "DB_HOST" = "db01.example.com"
        "DB_USER" = "web"
        "DB_PASS" = "loremipsum"
      }

      # Specify the maximum resources required to run the task,
      # include CPU, memory, and bandwidth.
      resources {
        cpu    = 500 # MHz
        memory = 128 # MB

        network {
          mbits = 100

          # This requests a dynamic port named "http". This will
          # be something like "46283", but we refer to it via the
          # label "http".
          port "http" {}

          # This requests a static port on 443 on the host. This
          # will restrict this task to running once per host, since
          # there is only one port 443 on each host.
          port "https" {
            static = 443
          }
        }
      }
    }
  }
}
```
This beautifully annotated job definition is converted to the following json in the Ui tab "definition"
It is not _readable_ anymore and there is no way of understanding the intention of the job spec.
```
{
  "Stop": false,
  "Region": "global",
  "Namespace": "default",
  "ID": "docs",
  "ParentID": "",
  "Name": "docs",
  "Type": "service",
  "Priority": 50,
  "AllAtOnce": false,
  "Datacenters": [
    "green"
  ],
  "Constraints": null,
  "Affinities": null,
  "Spreads": null,
  "TaskGroups": [
    {
      "Name": "webs",
      "Count": 5,
      "Update": {
        "Stagger": 30000000000,
        "MaxParallel": 2,
        "HealthCheck": "checks",
        "MinHealthyTime": 10000000000,
        "HealthyDeadline": 300000000000,
        "ProgressDeadline": 600000000000,
        "AutoRevert": false,
        "AutoPromote": false,
        "Canary": 0
      },
      "Migrate": {
        "MaxParallel": 1,
        "HealthCheck": "checks",
        "MinHealthyTime": 10000000000,
        "HealthyDeadline": 300000000000
      },
      "Constraints": null,
      "RestartPolicy": {
        "Attempts": 2,
        "Interval": 1800000000000,
        "Delay": 15000000000,
        "Mode": "fail"
      },
      "Tasks": [
        {
          "Name": "frontend",
          "Driver": "docker",
          "User": "",
          "Config": {
            "image": "hashicorp/web-frontend"
          },
          "Env": {
            "DB_HOST": "db01.example.com",
            "DB_USER": "web",
            "DB_PASS": "loremipsum"
          },
          "Services": [
            {
              "Name": "docs-webs-frontend",
              "PortLabel": "http",
              "AddressMode": "auto",
              "Tags": null,
              "CanaryTags": null,
              "Checks": [
                {
                  "Name": "service: \"docs-webs-frontend\" check",
                  "Type": "http",
                  "Command": "",
                  "Args": null,
                  "Path": "/health",
                  "Protocol": "",
                  "PortLabel": "",
                  "AddressMode": "",
                  "Interval": 10000000000,
                  "Timeout": 2000000000,
                  "InitialStatus": "",
                  "TLSSkipVerify": false,
                  "Method": "",
                  "Header": null,
                  "CheckRestart": null,
                  "GRPCService": "",
                  "GRPCUseTLS": false,
                  "TaskName": ""
                }
              ],
              "Connect": null,
              "Meta": null
            }
          ],
          "Vault": null,
          "Templates": null,
          "Constraints": null,
          "Affinities": null,
          "Resources": {
            "CPU": 500,
            "MemoryMB": 128,
            "DiskMB": 0,
            "IOPS": 0,
            "Networks": [
              {
                "Mode": "",
                "Device": "",
                "CIDR": "",
                "IP": "",
                "MBits": 100,
                "ReservedPorts": [
                  {
                    "Label": "https",
                    "Value": 443,
                    "To": 0
                  }
                ],
                "DynamicPorts": [
                  {
                    "Label": "http",
                    "Value": 0,
                    "To": 0
                  }
                ]
              }
            ],
            "Devices": null
          },
          "DispatchPayload": null,
          "Meta": null,
          "KillTimeout": 5000000000,
          "LogConfig": {
            "MaxFiles": 10,
            "MaxFileSizeMB": 10
          },
          "Artifacts": null,
          "Leader": false,
          "ShutdownDelay": 0,
          "VolumeMounts": null,
          "KillSignal": "",
          "Kind": ""
        }
      ],
      "EphemeralDisk": {
        "Sticky": false,
        "SizeMB": 300,
        "Migrate": false
      },
      "Meta": null,
      "ReschedulePolicy": {
        "Attempts": 0,
        "Interval": 0,
        "Delay": 30000000000,
        "DelayFunction": "exponential",
        "MaxDelay": 3600000000000,
        "Unlimited": true
      },
      "Affinities": null,
      "Spreads": null,
      "Networks": null,
      "Services": null,
      "Volumes": null
    }
  ],
  "Update": {
    "Stagger": 30000000000,
    "MaxParallel": 2,
    "HealthCheck": "",
    "MinHealthyTime": 0,
    "HealthyDeadline": 0,
    "ProgressDeadline": 0,
    "AutoRevert": false,
    "AutoPromote": false,
    "Canary": 0
  },
  "Periodic": null,
  "ParameterizedJob": null,
  "Dispatched": false,
  "Payload": null,
  "Meta": null,
  "VaultToken": "",
  "Status": "running",
  "StatusDescription": "",
  "Stable": false,
  "Version": 0,
  "SubmitTime": 1574776809704922400,
  "CreateIndex": 35539,
  "ModifyIndex": 35542,
  "JobModifyIndex": 35539
}
```

**Comment by tgross** [comment] 2019-11-26 14:12
Hi @fredrikhgrelland! Thanks for submitting this feature request!

While in some ways this is a duplicate of #681 I'm going to keep it open separately because this issue is more about the operating-facing experience, rather than just tracking specific versions of the jobspec.

**Comment by fredrikhgrelland** [comment] 2019-11-26 16:29
Hi @tgross. Yes my search found #681 before I chose to create this issue. I would like to add some additional context, as this request is very different from #681

This first came up while handcrafting a job spec and copy/pasting it in the ui. After copying a different string and realizing that there was no way to get back to my original HCL spec I got sad. After trying to decipher the json and realizing it was next to impossible to get back to a clean hcl, I gave up and created this issue.

There are a few distinct use cases for this enhancement:

- Inspecting a job posted by a user or a ci job. Preserving comments and layout would allow for visual inspection.
- Manually altering the count of a task in a job. Currently this requires searching in the json ( the ux is not great )

Currently nomad requires you to use a code repository and cli in order to have a sane workflow even for hotfix maintenance tasks. This might not be the direction you are taking nomad, but with the latest ui enhancements, it is quite ok to have an ad hoc workflow in the browser _except_ from this.

Thank you for listening.

**Comment by traceypooh** [comment] 2020-12-25 20:18
I'm running containerization at archive.org
We just switched from kubernetes (k3s cluster setup) to nomad (v1) + consul (v1.9).

As another admin use case,
we just deployed 100 deployments to a nomad/consul cluster of 4 (on-prem) VMs.
But I found w/ the templatized job spec that I made to CI/CD directly from GitLab, that simply setting `memory` limit for our jobs with the default nomad "bin packing" wound up with `OOMkiller` going on utter homicidal sprees after (it seems) file caching in RAM has confused the algorithms somewhere and 2 of our VMs have most of the deployments (bin packing) and they think they're "out of RAM" (they're not even close).

So, after lots of research, added `memory_hard_limit` to 10x the `memory` limit and things are much better.
That's hit ~10 of our ~100 deployments over the course of dev repo updates (and push => CI/CD => nomad deploy)
which is great.

But it _sure would be_ nice to be able to `nomad job inspect -hcl ...` or something, `perl -i -pe s/../../` the 90 jobs/files and then plan/run them in seconds.

`kubectl edit` and `kubectl patch` (esp.) are utterly amazing for this kind of thing.  I suspect more and more folks will migrate, too, to nomad/consul with features like these.  :)

**Comment by jhitt25** [comment] 2021-05-18 19:13
As an additional note on this request, this also makes job tracking quite difficult as well.  We currently have to save all our Nomad jobs in git to be able to easily update deployments (we don't have our builds CI/CD integrated just yet) and to have clean backups of our job specs.  Being able to extract the HCL from Nomad directly would make both of these situations a non-issue.

**Comment by genesis32** [comment] 2022-12-02 17:11
Even if we aren't talking about valid use-cases (which the other posters have many). It seems like a good design principle that for any system where submitting files is a core action that users should be able to get that exact same file out. 

It seems like that would be a relatively straight forward change to just store a copy of what was submitted alongside everything else and have an option to return it. You could then chain these together to create the equivelant of `kubectl edit`

**Comment by mikenomitch** [comment] 2023-03-14 20:55
Hi all, just commenting that this is slated for Nomad 1.6! We plan to have the HCL surfaced in the UI and via an optional flag on the `job inspect` command.

**Comment by genesis32** [comment] 2023-08-23 21:46
I just updated to 1.6.1 and there is no option in the inspect command (that's clearly documented) to show the original hcl.

Running:
```
nomad job inspect [job] -h
```

Just gives me back:
```
Inspect Options:

  -version <job version>
    Display the job at the given job version.

  -json
    Output the job in its JSON format.

  -t
    Format and display job using a Go template.
```

Which is similar to the 1.6.x documentation here.
https://developer.hashicorp.com/nomad/docs/commands/job/inspect

**Comment by lgfa29** [comment] 2023-08-23 22:18
Ah you're right @genesis32, I think we didn't implement a CLI command for the new job submissions API.

I will re-open this to focus on the CLI, but as a workaround you can use the `nomad operator api` example shown in the docs: https://developer.hashicorp.com/nomad/api-docs/jobs#read-job-submission

**Closed** 2024-08-05 19:35 UTC
Labels: type/enhancement, theme/cli, theme/jobspec

**Comment by urusha** [comment] 2024-09-03 08:55
@tgross Should I file new issue?

**Comment by jrasell** [comment] 2024-09-03 09:31
@urusha, yes please file new issues rather than commenting on closed ones.
