### ISSUE TITLE
restarting a docker job deletes the tag and image name

### ISSUE THREAD

**Issue by camerondavison** [hashicorp/nomad#1179] opened 2016-05-17 17:47 UTC
### Nomad version

`nomad version`
Nomad v0.3.2
### Operating system and Environment details

CoreOS stable (899.13.0)
### Issue

the first time that something with docker runs, you can run `docker ps` and see the image name, but I assume some kind of cleanup within nomad is removing the image. If the task is restarted with the same image it shows the name as just the hash instead of the tagged image name.
### Reproduction steps

Run a docker task, then restart it.

**Comment by dadgar** [comment] 2016-05-17 20:43
Can you clarify what you mean by "restart it"

**Comment by diptanu** [comment] 2016-05-18 07:47
@a86c6f7964 Can you please see if there is a stopped container which is referencing the image? Nomad currently removes the container when the task stops and also removes the image of the container. If there is container which is in stopped or running mode that still references that image, then removing the container results into deleting the name and tag of an image.

If you do not want Nomad to clean up the image please set the `docker.cleanup.image` option to false in the Nomad client configuration options.

**Comment by a86c6f7964** [comment] 2016-05-18 23:19
```
nomad agent -dev &
nomad init
# change to point to a new registry location such as username/redis:latest, anything that can change
nomad run example.nomad
docker ps | grep redis
# shows redis:latest tag
# edit example.nomad with something trivial, maybe add env {COOL="1"}, and at the same time push a different image to username/redis:latest
nomad run example.nomad
docker ps | grep redis # now just shows them image hash, instead of the tag
```

Looking through the logs I see that it did not do a docker pull. But if I change a env variable and do not change the tag on the registry then I see 

2016/05/18 23:14:23 [DEBUG] driver.docker: docker pull username/redis:test succeeded
    2016/05/18 23:14:23 [DEBUG] driver.docker: identified image username/redis:test as cb3165112a072ee169c7936a8d78520afd5f81bfc8fbaa2873e0eb24087b7043

It seems like the pull is happening on both, but 1 time it is actually starting up an old version of the container, where the other time it starts up a correct version of the container. The reason I say that the pull is happening on both, is I think that the pull is what is actually deleting the tags.

p.s. I am changing env variables as a way to get the service to restart and pull a new docker image.

**Comment by a86c6f7964** [comment] 2016-05-19 14:31
Okay this looks a lot like there are some assumptions on the fact that a tag is thought to be immutable, where as "latest" is considered mutable. https://github.com/hashicorp/nomad/blob/29be52f7629f7db087eed10ef5326dc03c4581eb/client/driver/docker.go#L529

I guess we could feel free to close this as a wont fix if that is the expected behavior. I think that possibly that this behavior should be documented though.

My expectation is that every single time I run something it would get pulled from the registry.

**Comment by a86c6f7964** [comment] 2016-05-19 15:30
Sorry if this is spammy, and maybe you already knew this but I am pretty sure that I can wrap my head around this now. There is probably a race between shutting down the old container and starting up the new container.

old task shutting down -> at the end it will call `docker rmi IMAGEID`
new task starting up -> figure out the IMAGEID -> startup the container with IMAGEID

If the rmi from the old tasks happens before the new tasks figures out the IMAGEID then everything is fine, because it will pull the latest image from the registry and have the tags. Where as if the rmi occurs after the new task has started up then it will remove the label.

```
core@ip-172-31-31-206 ~ $ docker run -d --name 'test' redis:3.0.7
Unable to find image 'redis:3.0.7' locally
3.0.7: Pulling from library/redis
3059b4820522: Pull complete
ff978d850939: Pull complete
1bc55a3ae3bf: Pull complete
f17e869358e1: Pull complete
2d52a2ee7736: Pull complete
0836ba20239a: Pull complete
35f6c76c07de: Pull complete
1fa84710eada: Pull complete
456367c9d2ab: Pull complete
6c9b4ba7f73e: Pull complete
96545b689cfa: Pull complete
53a668fe2d3d: Pull complete
efcfd74944ee: Pull complete
0d321bf0b655: Pull complete
e329b23362c6: Pull complete
b5cf56c27bbd: Pull complete
f1fa4adc2617: Pull complete
c1420ad4d20a: Pull complete
Digest: sha256:66aa9870b0d21ca78130145434ce2ea6b3caf3d6631ae9bf1f31413d05528d0e
Status: Downloaded newer image for redis:3.0.7
9e26f5b588ae77197236a268c5af0a289b6b8a11bdb2ca18e44c9cf099411316
$ docker ps | grep redis
9e26f5b588ae        redis:3.0.7                        "docker-entrypoint.sh"   9 seconds ago       Up 8 seconds        6379/tcp                                                                                                                     test
$ docker images | grep redis
redis                          3.0.7               c1420ad4d20a        7 days ago          177.5 MB
$ docker rmi c1420ad4d20a
Error response from daemon: conflict: unable to delete c1420ad4d20a (cannot be forced) - image is being used by running container 9e26f5b588ae
Error: failed to remove images: [c1420ad4d20a]
$ docker ps | grep test
9e26f5b588ae        c1420ad4d20a                       "docker-entrypoint.sh"   32 seconds ago      Up 31 seconds       6379/tcp                                                                                                                     test
$ docker version | grep -A1 Server
Server:
 Version:      1.9.1
```

If I do the above with a later version of docker 1.10.3 it does not remove the tag. I think that 1.10 has a lot of improvements for these kinds of things. It would be nice for this to get fixed for older dockers, but it may not need to be a huge priority.

p.s. I am unsure how parallelized all of these commands happen, but I was just noticing that if the rmi occurs after the new tasks gets the IMAGEID and before it starts the container then it will error out. It may be nice to lock docker interactions like this (or just say its okay because nomad will just see the failure and restart the task)

**Comment by a86c6f7964** [comment] 2016-05-23 15:18
Should I open up a new issue, or do you think that as part of this fix there would be some option to require a the latest image (for any tag not just "latest") to be pulled all of the time.

**Comment by a86c6f7964** [comment] 2016-05-23 19:25
It is an issue in my analytics. I am using cAdvisor which is nice because it tells me what image tag name is what.

**Comment by tgross** [comment] 2019-11-20 14:22
Doing some clean up of some old issues. This is safe to close. The [`force_pull`](https://www.nomadproject.io/docs/drivers/docker.html#force_pull) flag for the Docker task driver covers #1197 and at some point the image tags were preserved between versions (so long as the image itself wasn't changed):

```
▶ nomad job run example.nomad
==> Monitoring evaluation "387e7d77"
    Evaluation triggered by job "example"
    Evaluation within deployment: "ee790d24"
    Allocation "41854b80" created: node "c5b3e81f", group "cache"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "387e7d77" finished with status "complete"

▶ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                  NAMES
48a38d983adb        redis:3.2           "docker-entrypoint.s…"   4 seconds ago       Up 2 seconds        127.0.0.1:21893->6379/tcp, 127.0.0.1:21893->6379/udp   redis-41854b80-72f8-092e-f92a-a86d619542eb

▶ emacs example.nomad
# change the job's env stanza, and then...

▶ nomad job run example.nomad
==> Monitoring evaluation "1c267e44"
    Evaluation triggered by job "example"
    Allocation "43f68799" created: node "c5b3e81f", group "cache"
    Evaluation within deployment: "ca69ce4c"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "1c267e44" finished with status "complete"

▶ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                  NAMES
009cb7ff4731        redis:3.2           "docker-entrypoint.s…"   3 seconds ago       Up 2 seconds        127.0.0.1:29007->6379/tcp, 127.0.0.1:29007->6379/udp   redis-43f68799-7352-8f4f-7fab-9bebfe1f34af
```

**Closed by tgross** 2019-11-20 14:22 UTC
Labels: bug, driver/docker
