### ISSUE TITLE
SSO Login returns 500 on /v1/acl/token/self upon login

### ISSUE THREAD

**Issue by ednxzu** [hashicorp/nomad#16333] opened 2023-03-04 16:07 UTC
### Nomad version
Nomad v1.5.0
BuildDate 2023-03-01T10:11:42Z
Revision fc40c491cacec3d8ec3f2f98cd82b9068a50797c

### Operating system and Environment details
3 node cluster on ubuntu 22.04
tls disabled. 
traefik to serve https UI (loadbalancing between the three)

### Issue
I configure SSO login with authelia, but when login in through the UI, I'm getting a 500 code on the `/v1/acl/token/self` endpoint with error: `acl token lookup failed: missing secret id`. It retries and get a 403, then a 200, but permissions don't seem to match the role.
![image](https://user-images.githubusercontent.com/89710239/222919263-15aa8618-f871-4699-8f91-ce38a3c6092d.png)

On the third try: 
![image](https://user-images.githubusercontent.com/89710239/222919286-d035e8f7-6809-4779-b6f7-3568bdc11ad5.png)

The token is created correctly:
![image](https://user-images.githubusercontent.com/89710239/222916115-551b16ba-96ba-404a-854e-dac65912263b.png)

Login in with the root token gets me a 200 and works.

Manually getting the token secret from the CLI and login in using the secret created via authelia returns a 200, but permissions don't seem to match the role

`nomad token self -token=<secret authelia token>` works fine.
![image](https://user-images.githubusercontent.com/89710239/222916277-2ec8b737-2a91-496c-9900-90f35d863655.png)

### Reproduction steps
simple nomad cluster, serve the UI through a reverse-proxy that handles tls.
configure oidc provider and try login in with it on the UI.

#### Expected Result
The self endpoint should return a 200 on login

#### Actual Result
The self endpoint return either 500 `acl token lookup failed: missing secret id`

### Nomad Server logs (if appropriate)
Mar 04 16:51:47 nomad-master-3 nomad[113325]:     2023-03-04T16:51:47.973+0100 [ERROR] http: request failed: method=GET path=/v1/acl/token/self error="rpc error: acl token lookup failed: missing secret id" code=500

**Comment by ednxzu** [comment] 2023-03-04 17:30
complete erratum:
I was using a binding-rule to bind a role to the SSO users. Turns out, either I didn't understand how this work, or the UI isn't working properly with roles. 

This is my test policy:
```
root@nomad-master-1:/etc/nomad_config# nomad acl policy info admins
Name        = admins
Description = policy for administrator users
CreateIndex = 214009
ModifyIndex = 215367

Rules

namespace "*" {
  policy = "write"
}

agent {
  policy = "write"
}

node {
  policy = "write"
}

quota {
  policy = "write"
}

operator {
  policy = "write"
}

Creating the admins roles with the admins policy attached
```
nomad acl role create -name=admins -policy=admins
```

admins role:
```
root@nomad-master-1:/etc/nomad_config# nomad acl role info 58386f07-b2f5-ff9f-c1ce-e32a54af4f41
ID           = 58386f07-b2f5-ff9f-c1ce-e32a54af4f41
Name         = admins
Description  = <none>
Policies     = admins
Create Index = 214011
Modify Index = 214011
```

Creating the binding-rule for the SSO users:
```
nomad acl binding-rule create -auth-method=authelia -bind-type=role -bind-name=admins -selector="admins in list.roles"
```

Creating a token using the role:
```
root@nomad-master-1:/etc/nomad_config# nomad acl token create -name=test -role-name=admins -type=client
Accessor ID  = 6cd415d5-0923-0387-bbd1-efd6e052c7d4
Secret ID    = b6f32167-8e5e-b930-b890-7c1ec248938e
Name         = test
Type         = client
Global       = false
Create Time  = 2023-03-04 17:19:53.358822718 +0000 UTC
Expiry Time  = <none>
Create Index = 215577
Modify Index = 215577
Policies     = []

Roles
ID                                    Name
58386f07-b2f5-ff9f-c1ce-e32a54af4f41  admins
```

Works fine in the CLI, but if you try to log into the UI, no permissions are set, and you will just get read-only everything:
![image](https://user-images.githubusercontent.com/89710239/222920259-6ee926e2-cb91-4118-82ac-12be40c9da41.png)

Solution was to make the binding-rule bind a policy to users instead.

Sorry for the inaccurate issue.

**Comment by Kamilcuk** [comment] 2023-03-07 11:50
`if you try to log into the UI, no permissions are set` I have the same issue! After I create a token with specific role-name, the token does not have roles policies. `Solution was to make the binding-rule bind a policy to users instead`  Could you elaborate?

**Comment by lgfa29** [comment] 2023-03-08 21:38
Hi @ednxzu 👋 

Thanks for the report. I think the core issue here is what @Kamilcuk described in https://github.com/hashicorp/nomad/issues/16361 and what you mentioned in the follow-up comment:
> the UI isn't working properly with roles.

I will leave this one open just in case it's a different problem, but I would suggest keeping an eye on https://github.com/hashicorp/nomad/issues/16361 for updates.

**Comment by lgfa29** [comment] 2023-03-10 21:54
Cool, thank you. I will close this one for now and, once #16361 is fixed, we can reopen it if the problem is not solved.

> Also, the documentation for OIDC auth method makes you create a binding-rule with a role, which is why I ended up doing that in the first place. If this cannot be fixed easily, maybe adding a warning here might be a good idea ?

I think it will depend on quick we expect this issue to be fixed, so I will leave this up to the team. In general we would suggest ACL roles when using SSO.

**Closed by lgfa29** 2023-03-10 21:54 UTC
Labels: type/bug, stage/needs-investigation, theme/ui, theme/auth
