### ISSUE TITLE
cpu resource allocation documentation is unclear for docker containers

### ISSUE THREAD

**Issue by josh-m-sharpe** [hashicorp/nomad#18154] opened 2023-08-04 12:37 UTC
### Nomad version
1.5.8

So I gather from [this](https://developer.hashicorp.com/nomad/docs/drivers/docker#resource-isolation) doc that `cpu` in the resources block for a docker task is more like a ratio.  So... example time (at least the way I understand it):

Host has 10000mhz available.
task1 has cpu = 4000
task2 has cpu = 2000
Nomad will schedule them because 4000+2000=6000 is < 10000. Great.
And if everything is going full-tilt, then task2 will get half the cpu cycles that task1 gets.

Is this roughly correct so far?

But if task 1 is completely idle and task2 is pegged, it will consume (almost) all 10000mhz.

So 'cpu' is not a limit. 

But wait!  Example 2 time!

Same host (10000 Mhz)
task1 cpu = 6000
task2 cpu = 6000
Nomad won't schedule this because 6000+6000=12000 is > 10000

This is confusing. Now there's a cpu limit?  Effectively I want the allocations to have an equal weight and there is no real cpu limit, but it fails? (And yea, I could set them both to 5000, or 4000, or leave them default - but this is all arbitrary. Arbitrary is no good.)

[This doc](https://developer.hashicorp.com/nomad/docs/runtime/environment#job-related-variables) also refers to NOMAD_CPU_LIMIT as a limit: `CPU limit in MHz for the task` but this is also seemingly not true.

Not exactly sure what I'm looking for.  If I'm even partly correct with the above assessment, then maybe a documentation refresh would be helpful?

But maybe there's a feature request here too.  If `cpu` for docker is truly a ratio, maybe I should be able to set an attribute like `cpu_ratio` for docker tasks?  Maybe?

**Comment by schmichael** [comment] 2023-08-07 21:11
Hi Josh!

Nomad measures CPU resources in mhz and cores. Linux containerization (cgroups) allows limiting cpu usage based on shares or cores. Shares are relative soft limits as you've discovered. So for Docker (and exec/java) tasks we treat 1 share as 1 mhz which makes the math and proportions work fine as long as nothing else on your systems is setting shares with a different methodology. Even then the soft limit nature of shares should let things muddle along even if suboptimally.

If you would like hard limits then there's a Docker specific option: https://developer.hashicorp.com/nomad/docs/drivers/docker#cpu_hard_limit

I'd love feedback on how we could make the docs more clear on these points. I see that it's surprising, but unfortunately our high priority on backward compatibility limits our ability to change the code or names around this.

The *intent* behind this design is for job authors to be able to assign their tasks the amount of cpu time they need to meet their service-level objectives or intended performance requirements. In other words Nomad tries to guarantee at least a _baseline_ of cpu resources are available for your workloads to perform as intended. The default soft limit is more about not enforcing limits when there's no "need" too (because the cpu would otherwise be idle).

Ratios or proportional measures of CPU would require job authors to know what every other job in the cluster was set to in order to appropriately set their workload's relative requirements. Even then differences between nodes could cause wildly different performance characteristics.

I'm going to close this for now, but if there are specific things we should clarify in the docs feel free to reopen!

**Closed by schmichael** 2023-08-07 21:11 UTC
Labels: type/bug
