### ISSUE TITLE
Nomad logmon extremely high memory usage.

### ISSUE THREAD

**Issue by bubejur** [hashicorp/nomad#10629] opened 2021-05-20 13:00 UTC
Hi there,

### Nomad version
Nomad v1.1.0 (2678c3604bc9530014208bc167415e167fd440fc)

### Operating system and Environment details
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"

### Issue
Extremely high memory usage by nomad logmon.

### Reproduction steps
Upgrade nomad cluster and client to 1.0.0+ version. After all you will see errors:
[ERROR] client.driver_mgr.raw_exec: error receiving stream from Stats executor RPC, closing stream: alloc_id=2eba8886-94a2-0afc-8e2b-24e6af270728 driver=raw_exec task_name=Group-1-worker-0 error="rpc error: code = Unavailable desc = transport is closing" in syslog.
And some time ago (about 8h) logmon process takes >5% memory usage. And after 1 day I really need to restart nomad process to free up node memory.
I hoped a lot about fix it at 1.1.0, but still have this issue...

  PID USER     %MEM COMMAND
25543 root      5.7 /usr/local/bin/nomad agent -config=/etc/nomad
32075 root      0.9 /opt/puppet-archive/nomad-1.1.0/nomad logmon
31148 root      0.9 /opt/puppet-archive/nomad-1.1.0/nomad logmon
31142 root      0.9 /opt/puppet-archive/nomad-1.1.0/nomad logmon
31132 root      0.9 /opt/puppet-archive/nomad-1.1.0/nomad logmon
31116 root      0.9 /opt/puppet-archive/nomad-1.1.0/nomad logmon
31101 root      0.9 /opt/puppet-archive/nomad-1.1.0/nomad logmon
31094 root      0.9 /opt/puppet-archive/nomad-1.1.0/nomad logmon
31087 root      0.9 /opt/puppet-archive/nomad-1.1.0/nomad logmon
31074 root      0.9 /opt/puppet-archive/nomad-1.1.0/nomad logmon
31067 root      0.8 /opt/puppet-archive/nomad-1.1.0/nomad logmon
31066 root      0.8 /opt/puppet-archive/nomad-1.1.0/nomad logmon

#### Expected Result
No memory leak by nomad logmon.

#### Actual Result
Huge memory usage.

**Comment by tgross** [comment] 2021-05-20 13:04
Sorry @bubejur I probably wasn't clear. If your problem is high memory usage, this is indeed a dupe of #9858. It seemed like you were having some _other_ issue from your message in https://github.com/hashicorp/nomad/issues/9858#issuecomment-845063999. Closing as a dupe.

**Closed by tgross** 2021-05-20 13:04 UTC
Labels: type/bug
