### ISSUE TITLE
Allow Canary to stop existing allocation 

### ISSUE THREAD

**Issue by Juberstine** [hashicorp/nomad#12339] opened 2022-03-21 20:40 UTC
In our scenario, to use a canary, we have to dedicate an extra hot-spare server to be able to use canaries. We would like to be able to have a canary stop an existing allocation and use that client for the new canary. Our workload in this case required dedicated hosts and having an extra spare just sitting there in case we need to do a canary deploy is a waste of hardware.

Is it possible to allow an override of the default behavior and have a canary deploy stop an existing allocation if there is not another suitable location to land the allocation?

**Comment by lgfa29** [comment] 2022-03-23 21:06
Hi @Juberstine 👋 

I think this feels like the same scenario as described in https://github.com/hashicorp/nomad/issues/12339? Which is a way to do a rolling upgrade but stop at the first replacement batch?

**Comment by tgross** [comment] 2022-08-22 14:10
Doing a bit of issue cleanup and I'm going to close this one out as a dupe of #12339.

**Closed by tgross** 2022-08-22 14:10 UTC
Labels: type/enhancement, stage/waiting-reply, stage/duplicate, theme/deployments

**Comment by dynamix** [comment] 2022-09-13 15:57
Is this maybe the wrong issue link? Otherwise it would mean #12339 it is a duplicate of itself?  @tgross @lgfa29

**Comment by tgross** [comment] 2022-09-13 16:23
Whoops, good catch! Looks like that dupe is https://github.com/hashicorp/nomad/issues/9745
