### ISSUE TITLE
Task leader not submitted via HTTP API

### ISSUE THREAD

**Issue by jzvelc** [hashicorp/nomad#2463] opened 2017-03-21 10:21 UTC
### Nomad version
0.5.5

### Operating system and Environment details
Ubuntu 16.04.2 LTS
4.8.0-41-generic #44~16.04.1-Ubuntu SMP Fri Mar 3 17:11:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Issue
When submitting a job via JSON api task's `leader` key is ignored.

### Reproduction steps
Submit a job via HTTP API with a task which has a `leader` key set to true.
Task is placed within task group which has at least two tasks.
When inspecting a job leader is not present.

**Comment by dadgar** [comment] 2017-03-21 16:13
Hey @jzvelc,

I could not reproduce.

HCL version:
```
job "leader" {
  datacenters = ["dc1"]
  type = "batch"
  group "cache" {
    count = 1

    task "sleep short" {
      driver = "raw_exec"
      leader = true
      config {
        command = "sleep"
        args = ["10"]
      }
    }

    task "sleep long" {
      driver = "raw_exec"
      config {
        command = "sleep"
        args = ["100"]
      }
    }
  }
}
```

Submitted JSON: 
```
{
    "Job": {
        "AllAtOnce": false,
        "Constraints": null,
        "CreateIndex": 8,
        "Datacenters": [
            "dc1"
        ],
        "ID": "leader-test",
        "JobModifyIndex": 8,
        "Meta": null,
        "ModifyIndex": 10,
        "Name": "leader",
        "ParameterizedJob": null,
        "ParentID": "",
        "Payload": null,
        "Periodic": null,
        "Priority": 50,
        "Region": "global",
        "Status": "running",
        "StatusDescription": "",
        "TaskGroups": [
            {
                "Constraints": null,
                "Count": 1,
                "EphemeralDisk": {
                    "Migrate": false,
                    "SizeMB": 300,
                    "Sticky": false
                },
                "Meta": null,
                "Name": "cache",
                "RestartPolicy": {
                    "Attempts": 15,
                    "Delay": 15000000000,
                    "Interval": 604800000000000,
                    "Mode": "delay"
                },
                "Tasks": [
                    {
                        "Artifacts": [],
                        "Config": {
                            "args": [
                                "10"
                            ],
                            "command": "sleep"
                        },
                        "Constraints": null,
                        "DispatchPayload": null,
                        "Driver": "raw_exec",
                        "Env": null,
                        "KillTimeout": 5000000000,
                        "Leader": true,
                        "LogConfig": {
                            "MaxFileSizeMB": 10,
                            "MaxFiles": 10
                        },
                        "Meta": null,
                        "Name": "sleep short",
                        "Resources": {
                            "CPU": 100,
                            "DiskMB": 0,
                            "IOPS": 0,
                            "MemoryMB": 10,
                            "Networks": null
                        },
                        "Services": [],
                        "Templates": [],
                        "User": "",
                        "Vault": null
                    },
                    {
                        "Artifacts": [],
                        "Config": {
                            "args": [
                                "100"
                            ],
                            "command": "sleep"
                        },
                        "Constraints": null,
                        "DispatchPayload": null,
                        "Driver": "raw_exec",
                        "Env": null,
                        "KillTimeout": 5000000000,
                        "Leader": false,
                        "LogConfig": {
                            "MaxFileSizeMB": 10,
                            "MaxFiles": 10
                        },
                        "Meta": null,
                        "Name": "sleep long",
                        "Resources": {
                            "CPU": 100,
                            "DiskMB": 0,
                            "IOPS": 0,
                            "MemoryMB": 10,
                            "Networks": null
                        },
                        "Services": [],
                        "Templates": [],
                        "User": "",
                        "Vault": null
                    }
                ]
            }
        ],
        "Type": "batch",
        "Update": {
            "MaxParallel": 0,
            "Stagger": 0
        },
        "VaultToken": ""
    }
}
```

Nomad inspect:
```
{
    "Job": {
        "AllAtOnce": false,
        "Constraints": null,
        "CreateIndex": 23,
        "Datacenters": [
            "dc1"
        ],
        "ID": "leader-test",
        "JobModifyIndex": 23,
        "Meta": null,
        "ModifyIndex": 29,
        "Name": "leader",
        "ParameterizedJob": null,
        "ParentID": "",
        "Payload": null,
        "Periodic": null,
        "Priority": 50,
        "Region": "global",
        "Status": "dead",
        "StatusDescription": "",
        "TaskGroups": [
            {
                "Constraints": null,
                "Count": 1,
                "EphemeralDisk": {
                    "Migrate": false,
                    "SizeMB": 300,
                    "Sticky": false
                },
                "Meta": null,
                "Name": "cache",
                "RestartPolicy": {
                    "Attempts": 15,
                    "Delay": 15000000000,
                    "Interval": 604800000000000,
                    "Mode": "delay"
                },
                "Tasks": [
                    {
                        "Artifacts": [],
                        "Config": {
                            "args": [
                                "10"
                            ],
                            "command": "sleep"
                        },
                        "Constraints": null,
                        "DispatchPayload": null,
                        "Driver": "raw_exec",
                        "Env": null,
                        "KillTimeout": 5000000000,
                        "Leader": true,
                        "LogConfig": {
                            "MaxFileSizeMB": 10,
                            "MaxFiles": 10
                        },
                        "Meta": null,
                        "Name": "sleep short",
                        "Resources": {
                            "CPU": 100,
                            "DiskMB": 0,
                            "IOPS": 0,
                            "MemoryMB": 10,
                            "Networks": null
                        },
                        "Services": [],
                        "Templates": [],
                        "User": "",
                        "Vault": null
                    },
                    {
                        "Artifacts": [],
                        "Config": {
                            "args": [
                                "100"
                            ],
                            "command": "sleep"
                        },
                        "Constraints": null,
                        "DispatchPayload": null,
                        "Driver": "raw_exec",
                        "Env": null,
                        "KillTimeout": 5000000000,
                        "Leader": false,
                        "LogConfig": {
                            "MaxFileSizeMB": 10,
                            "MaxFiles": 10
                        },
                        "Meta": null,
                        "Name": "sleep long",
                        "Resources": {
                            "CPU": 100,
                            "DiskMB": 0,
                            "IOPS": 0,
                            "MemoryMB": 10,
                            "Networks": null
                        },
                        "Services": [],
                        "Templates": [],
                        "User": "",
                        "Vault": null
                    }
                ]
            }
        ],
        "Type": "batch",
        "Update": {
            "MaxParallel": 0,
            "Stagger": 0
        },
        "VaultToken": ""
    }
}
```

Alloc-Status:
```
ID                  = da8beab3
Eval ID             = bd892564
Name                = leader.cache[0]
Node ID             = 564daec4
Job ID              = leader-test
Client Status       = complete
Client Description  = <none>
Desired Status      = run
Desired Description = <none>
Created At          = 03/21/17 16:08:57 UTC

Task "sleep long" is "dead"
Task Resources
CPU      Memory  Disk     IOPS  Addresses
100 MHz  10 MiB  300 MiB  0

Recent Events:
Time                   Type              Description
03/21/17 16:09:07 UTC  Killed            Task successfully killed
03/21/17 16:09:07 UTC  Killing           Sent interrupt. Waiting 5s before force killing
03/21/17 16:09:07 UTC  Leader Task Dead  Leader Task in Group dead
03/21/17 16:08:57 UTC  Started           Task started by client
03/21/17 16:08:57 UTC  Task Setup        Building Task Directory
03/21/17 16:08:57 UTC  Received          Task received by client

Task "sleep short" is "dead"
Task Resources
CPU      Memory  Disk     IOPS  Addresses
100 MHz  10 MiB  300 MiB  0

Recent Events:
Time                   Type        Description
03/21/17 16:09:07 UTC  Terminated  Exit Code: 0
03/21/17 16:08:57 UTC  Started     Task started by client
03/21/17 16:08:57 UTC  Task Setup  Building Task Directory
03/21/17 16:08:57 UTC  Received    Task received by client
```

I am going to close this but we can re-open if you post more details showing it not working. Thanks!

**Closed by dadgar** 2017-03-21 16:13 UTC

**Comment by jzvelc** [comment] 2017-03-21 20:53
@dadgar You are using type batch. Can you try this with service?

**Comment by dadgar** [comment] 2017-03-21 21:01
@jzvelc Sure. Same behavior:
```
{
    "Job": {
        "AllAtOnce": false,
        "Constraints": null,
        "CreateIndex": 8,
        "Datacenters": [
            "dc1"
        ],
        "ID": "leader",
        "JobModifyIndex": 8,
        "Meta": null,
        "ModifyIndex": 10,
        "Name": "leader",
        "ParameterizedJob": null,
        "ParentID": "",
        "Payload": null,
        "Periodic": null,
        "Priority": 50,
        "Region": "global",
        "Status": "running",
        "StatusDescription": "",
        "TaskGroups": [
            {
                "Constraints": null,
                "Count": 1,
                "EphemeralDisk": {
                    "Migrate": false,
                    "SizeMB": 300,
                    "Sticky": false
                },
                "Meta": null,
                "Name": "cache",
                "RestartPolicy": {
                    "Attempts": 2,
                    "Delay": 15000000000,
                    "Interval": 60000000000,
                    "Mode": "delay"
                },
                "Tasks": [
                    {
                        "Artifacts": [],
                        "Config": {
                            "args": [
                                "10"
                            ],
                            "command": "sleep"
                        },
                        "Constraints": null,
                        "DispatchPayload": null,
                        "Driver": "raw_exec",
                        "Env": null,
                        "KillTimeout": 5000000000,
                        "Leader": true,
                        "LogConfig": {
                            "MaxFileSizeMB": 10,
                            "MaxFiles": 10
                        },
                        "Meta": null,
                        "Name": "sleep long",
                        "Resources": {
                            "CPU": 100,
                            "DiskMB": 0,
                            "IOPS": 0,
                            "MemoryMB": 10,
                            "Networks": null
                        },
                        "Services": [],
                        "Templates": [],
                        "User": "",
                        "Vault": null
                    },
                    {
                        "Artifacts": [],
                        "Config": {
                            "command": "/bin/bash",
                            "args": [
                                "-c",
                                "sleep 1 && exit 1"
                            ]
                        },
                        "Constraints": null,
                        "DispatchPayload": null,
                        "Driver": "raw_exec",
                        "Env": null,
                        "KillTimeout": 5000000000,
                        "Leader": false,
                        "LogConfig": {
                            "MaxFileSizeMB": 10,
                            "MaxFiles": 10
                        },
                        "Meta": null,
                        "Name": "sleep short",
                        "Resources": {
                            "CPU": 100,
                            "DiskMB": 0,
                            "IOPS": 0,
                            "MemoryMB": 10,
                            "Networks": null
                        },
                        "Services": [],
                        "Templates": [],
                        "User": "",
                        "Vault": null
                    }
                ]
            }
        ],
        "Type": "service",
        "Update": {
            "MaxParallel": 0,
            "Stagger": 0
        },
        "VaultToken": ""
    }
}
```
