### ISSUE TITLE
support streaming logs from all allocations for a job on the CLI

### ISSUE THREAD

**Issue by tcrayford** [hashicorp/nomad#10379] opened 2021-04-14 14:14 UTC
### Proposal

I'd like to be able to (for local development/debugging) stream logs from all allocations from a job via the CLI (and possibly the UI as well, but that seems like a stretch).

### Use-cases

Currently, to find logs from my application, I have to drill down to the allocation level, like this:

- `nomad job status myjob`

because `nomad job status` doesn't support any kind of `json` or machine readable output, I have to grab all the allocation ids myself and copy/paste them somewhere.

Then in `tmux` I open a split per allocation, and run `nomad alloc logs -f ALLOCID`.

This is a lot of steps to get access to logs for my application, which is what I was trying to do.

I talked to @schmichael about this and he suggested this could be implemented as a CLI only solution, so the maintenance wouldn't be too much. It'd save me maybe 15-20 minutes per day (I need to look at logs a lot!).

### Attempted Solutions

See above.

**Comment by mikenomitch** [comment] 2022-04-26 20:48
Hey @tcrayford closing as a dupe of https://github.com/hashicorp/nomad/issues/10308! Thanks! :)

**Closed by mikenomitch** 2022-04-26 20:48 UTC
Labels: type/enhancement, theme/cli, theme/logging, stage/accepted
