### ISSUE TITLE
Job Logs

### ISSUE THREAD

**Issue by ChrisMcKenzie** [hashicorp/nomad#475] opened 2015-11-20 02:46 UTC
Currently it seems there is no way to view the out put of a job other than using `docker logs` (if you are scheduling docker) on a individual container. it would be awesome if the logs were made available via a stream or something, this would also make for a useful ui feature in that you can see your jobs get allocated and see there output, perhaps even see the logs of all of the instances of a task in the same stream just tag for each instance.

**Comment by cbednarski** [comment] 2015-11-20 06:33
Thanks for the suggestion. This is a duplicate of https://github.com/hashicorp/nomad/issues/277 so I'm going to close this issue. If you have any additional feedback please add it to 277. Thanks!

**Closed by cbednarski** 2015-11-20 06:33 UTC
