### ISSUE TITLE
nomad UI "couldn't connect to client" when evaluating CPU and Memory for a job

### ISSUE THREAD

**Issue by Justin-DynamicD** [hashicorp/nomad#3545] opened 2017-11-13 22:55 UTC
When browsing the new UI in Nomad 0.7.0, if I browse a client and look at the allocation table,  both the CPU and Memory report a yellow "!" instead of a value.  Hovering over these warnings with the mouse reports "couldn't connect to client".

It's possible I'm missing a setting somewhere but wasn't able to find it.  As an FYI nomad alloc-status -stats returns information just fine.

**Comment by dadgar** [comment] 2017-11-13 23:47
@Justin-DynamicD Is the UI being accessed within the same network as when alloc-status works? A requirement is that you can contact the client node directly to access stats.

**Comment by DingoEatingFuzz** [comment] 2017-11-13 23:49
This is a duplicate of either #3497 or #3527.

**Comment by Justin-DynamicD** [comment] 2017-11-13 23:51
"same network" is a bit ambiguous so Ill clarify:  all networks in question are route-able, but not necessarily the same subnet.

The Nomad cluster is on 3 separate subnets, all rout-able to the node in question (which shares one of the subnets).  I can successfully test from a _4th_ rout-able subnet in another physical datacenter.

So there is lots of routing involved, but no ACLs, firewall, or otherwise.

**Comment by dadgar** [comment] 2017-11-13 23:52
@Justin-DynamicD Thanks for clarifying. Closing as @DingoEatingFuzz points out this has been fixed  by https://github.com/hashicorp/nomad/pull/3530 and will be part of 0.7.1! Thanks for reporting!

**Closed by dadgar** 2017-11-13 23:52 UTC
Labels: bug, ui, waiting-reply
