### ISSUE TITLE
unhealthy deployment with poststart lifecycle

### ISSUE THREAD

**Issue by tcdev0** [hashicorp/nomad#10058] opened 2021-02-22 15:25 UTC
### Nomad version
Nomad v1.0.3 (08741d9f2003ec26e44c72a2c0e27cdf0eadb6ee)

### Operating system and Environment details
Ubuntu 18.04.5 LTS

### Issue
Deployement with poststart task is immediately marked as unhealthy and still running as an active deployment until deadline hits.
The Service is registered healthy in Consul and reachable via traefik. 

![nomad_poststart_1](https://user-images.githubusercontent.com/822498/108725144-5af2ca00-7526-11eb-9086-e9cc7102e097.png)

![nomad_poststart_2](https://user-images.githubusercontent.com/822498/108725258-7d84e300-7526-11eb-8e62-a19710d70aff.png)

Removing the poststart job and the deployment is running fine.

I guess the poststart job is exiting too fast (under 10s) und therefore hits the min_healthy_time of 10s(default).

### Job file

```
job "nginx" {

  datacenters = ["prod"]
  namespace   = "default"
  type        = "service"

  group "nginx" {
    count = 1
    service {
      name = "${BASE}"
      tags = [
        "traefik.enable=true",
        "traefik.http.routers.nginx.entrypoints=websecure",
        "traefik.http.routers.nginx.rule=Host(`nginx.domain`)",
        "traefik.http.routers.nginx.tls=true"
      ]
      port = "http"
      check {
        name     = "alive"
        type     = "tcp"
        interval = "2s"
        timeout  = "2s"
      }
    }

    network {
      port "http" {
        to = 80
      }
    }

    update {
      min_healthy_time  = "10s"
      healthy_deadline  = "5m"
      progress_deadline = "10m"
    }

    task "nginx-web" {
      driver = "docker"
      config {
        image = "nginx:latest"
        ports = ["http"]
      }
    }

    task "nginx-poststart" {
      driver = "docker"
      config {
        image   = "alpine:latest"
        command = "sh"
        args    = ["-c", "sleep 5 && echo 'running....' && exit 0;"]

      }
      lifecycle {
        hook    = "poststart"
        sidecar = false
      }
    }
  }
}
```

Enforcing the poststart job to wait for the min_healthy_time from the web service and exiting after, fixed the issue. 
So i set the sleep timer slightly above the **min_healthy_time = "10s"** and it works.

```
    task "nginx-poststart" {
      driver = "docker"
      config {
        image   = "alpine:latest"
        command = "sh"
        args    = ["-c", "sleep 12 && echo 'running....' && exit 0;"]

      }
      lifecycle {
        hook    = "poststart"
        sidecar = false
      }
    }
```
![nomad_poststart_3](https://user-images.githubusercontent.com/822498/108728340-c8542a00-7529-11eb-91b9-53815b4e80ee.png)

Seen in [9361](https://github.com/hashicorp/nomad/issues/9361)

Is it a bug or working as expected ? 

Thanks.

**Comment by tgross** [comment] 2021-02-22 16:13
HI @tcdev0. Looks like the fix for #9361 shipped in Nomad 1.0.2. This problem is slightly different, and looks like a bug emerging from the interaction of three things:
* A post start task
* That's not a sidecar (and so should be expected to exit)
* With a minimum healthy time in the `update` block

To make this work without your workaround (which looks sensible), we'd have to update the allocation health status to verify that the exit code is successful for post-stop tasks if we find they aren't "healthy" by the minimum healthy time.

**Comment by tommyalatalo** [comment] 2021-04-20 13:54
We also observed this behavior today, having a task with a post start hook (not sidecar) and a min_healthy_time set in the update stanza. Will be following this, definitiely in need of a fix.

**Comment by maxless** [comment] 2021-09-03 12:27
+1
Moreover, it feels weird that stuff in the update stanza is used to control prestart/poststart/poststop tasks. One of their intended uses as is shown in the documentation for lifecycle stanza is to just send HTTP requests to chat channels and exit. Which is precisely what it fails to do in the current implementation, marking allocation as unhealthy. I guess either there needs to be some flag in lifecycle, like "ignore_update", or separate task update block that overrides the group update block.

**Comment by Vadim-Che** [comment] 2021-09-24 14:14
Have Nomad v1.1.0 but faced the same issue. My jobs have Poststart and Poststop tasks. Poststop task is marked with "Task not running by deadline":
![image](https://user-images.githubusercontent.com/51299600/134688590-4a5847b2-7b35-4263-8020-7bfbd349a8ec.png)

But the strangest thing is that there are other services, that are deployed by the same scheme and those are Ok (are not marked as failed):
![image](https://user-images.githubusercontent.com/51299600/134689017-7eaa73b4-a373-468d-b5d2-b48a27e5027e.png)

Will this be fixed in recent future?

**Comment by Oloremo** [comment] 2021-10-05 22:29
Hit that too on Nomad 1.1.5

**Comment by havenith** [comment] 2021-11-04 01:12
+1
I have the same problem. The above sample fails on Nomad 1.1.6. And in our case we have a long running Java process and a short running(sub ten second), non-sidecar poststart task. 
The deployment always fails with 'Task not running for min_healthy_time of 10s by deadline' even though the long running Java task is healthy in both Nomad and Consul. 
Padding out the length of the poststart task doesn't seem to help though, so we don't have a workaround currently.

Is there a way to track this issue? Is it still being worked on?

**Comment by beautifulentropy** [comment] 2021-11-13 03:53
Experiencing this too. As a new Nomad user I burned a ton of cycles on this before realizing this was just a bug.

**Comment by axsuul** [comment] 2021-12-28 16:28
Still getting this issue on Nomad 1.2.0

**Comment by SunSparc** [comment] 2022-01-04 22:10
Same. Nomad 1.2.0. I changed my `poststart` task to use the `exec` driver and handed it a bash script so I could use the `sleep` kludge that the OP used. This also got me past the problem, for now.

**Comment by ksklareski** [comment] 2022-01-20 16:00
FYI issue persists in 1.2.4. Sleeping workaround still works.

**Comment by beautifulentropy** [comment] 2022-01-24 23:33
A note for others who attempt to fix this with the a sleep of `>=min_healthy_time`. This workaround will result in a successful initial deployment. However, any subsequent update deployment where only new allocations are created `forces create` (not `forces create/destroy update`) will result in all previously healthy nodes becoming unhealthy; new allocations will be healthy though. The only real workaround I could find that truly avoids the issue is just making your existing post-start ephemeral hooks long-running sidecars instead.

**Closed** 2022-02-02 21:29 UTC
Labels: type/bug, theme/task lifecycle, stage/accepted

**Comment by edudobay** [comment] 2022-02-03 02:52
Should the same changes be applied to `prestart` tasks? The PR above only changed the behaviour for `poststart` tasks, but it seems like `prestart` should have been included as well.

**Comment by tgross** [comment] 2022-02-03 13:38
@edudobay the code touched by #11945 already had a special case for `prestart`, and there wasn't any other discussion of `prestart` in this issue. If you're encountering something similar there, can you open a new issue for it? Thanks!

**Comment by shantanugadgil** [comment] 2022-04-27 09:18
Is there a v1.2.7 anticipated? or should we just wait for v1.3.0 GA ?
