### ISSUE TITLE
Different Job ID and Name

### ISSUE THREAD

**Issue by Regenhardt** [hashicorp/nomad#10946] opened 2021-07-27 07:52 UTC
### Proposal

Allow Job name to be different from ID.

### Use-cases

This makes the job list look way more friendly.

### Attempted Solutions

A year ago I started my journey with nomad. Pushed a job with ID "comp-imageconverter" and name "ImageConverter". So it has an id I can see in the job-url "/ui/jobs/comp-imageconverter", but in the big job list on the nomad homepage I can see the name "ImageConverter".

Now I tried to make another job like that, and I get the "Job ID not matching" error, probably because of this part:

```
if jobName != "" && *args.Job.ID != jobName {
		return nil, CodedError(400, "Job ID does not match")
	}
```

which is strange, because ID and name feel like things that should be able to be set independently.

**Comment by tgross** [comment] 2022-08-22 14:56
Sorry about the delay on replying to this one @Regenhardt. Turns out this is mostly a duplicate of a long-open issue https://github.com/hashicorp/nomad/issues/2248 that goes through some of the challenges. At this point it's going to be very challenging to do this kind of thing without breaking backwards compatibility in the API, so I'm going to be honest and say this isn't likely to be done.

Going to close this issue as a dupe, but thanks for opening the issue!

**Closed by tgross** 2022-08-22 14:56 UTC
Labels: type/enhancement
