### ISSUE TITLE
UI job editor puts list variables into quotes which causes invalid `input.hcl` file structure

### ISSUE THREAD

**Issue by Davasny** [hashicorp/nomad#23732] opened 2024-08-04 10:20 UTC
### Nomad version
Output from `nomad version`

```
Nomad v1.8.2
BuildDate 2024-07-16T08:50:09Z
Revision 7f0822c1e4f25907d9f60e2d595411950dd1bd28
```

### Operating system and Environment details

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

### Issue

UI job editor puts list variables into quotes which causes invalid `input.hcl` file structure

### Reproduction steps

1. Run provided jobspec using cli

```bash
nomad job run -var='tags=["aa"]' test-redis.nomad
```

2. Go to deployed service via nomad ui

3. Go to definition, edit, try to plan without any change

4. You will see exception

```
Failed to parse job: unable to parse var content: input.hcl:1,9-11: Missing newline after argument; An argument definition must end with a newline.
```

![image](https://github.com/user-attachments/assets/47f23775-8da1-4a47-977e-c7109d780e9c)

#### Expected Result

Job should be planned without exception

UI should not put list variable value into quotes. Changing value by hand will result in accepted plan

```diff
- tags="["aa"]"
+ tags=["aa"]
```

#### Actual Result

```
Failed to parse job: unable to parse var content: input.hcl:1,9-11: Missing newline after argument; An argument definition must end with a newline.
```

### Job file (if appropriate)

```
variable "tags" {
  type = list(string)
}

job "test-redis" {
  datacenters = [
    "*"
  ]
  type = "service"

  group "redis" {
    count = 1

    task "redis" {
      driver = "docker"

      config {
        image = "redis"
        ports = ["redis"]
      }
    }

    network {
      port "redis" {
        to = 6379
      }
    }

    service {
      name = "test-redis"
      port = "redis"
      tags = var.tags
    }
  }
}

```

**Comment by tgross** [comment] 2024-08-05 12:42
Hi @Davasny! I don't think the UI does any parsing of the HCL which is maybe why it's not identifying the variables type correctly. I'll mark this for further investigation.

**Comment by the-nando** [comment] 2024-08-07 18:23
@tgross I think this is a duplicate of the issue we've discussed here: https://github.com/hashicorp/nomad/issues/23462

**Comment by tgross** [comment] 2024-08-07 18:29
Good catch, thanks @the-nando! I'm going to close this as a duplicate, but ping @philrenaud so he sees the additional context here.

**Closed by tgross** 2024-08-07 18:29 UTC
Labels: type/bug, theme/ui, theme/hcl
