### ISSUE TITLE
Growing allocations

### ISSUE THREAD

**Issue by BSick7** [hashicorp/nomad#904] opened 2016-03-10 23:00 UTC
I am noticing a quirky issue where nomad is "growing" the number of allocations per evaluation by 1 on every `nomad run`.  In other words, my job specification has a count of 1 and after issuing 8 times, I get 8 allocations.

It may be helpful to know that these jobs are failing.

### Allocations
```
$ nomad eval-monitor 62fde126
==> Monitoring evaluation "62fde126"
    Evaluation triggered by job "bravos-api-migrate"
    Allocation "8db0b439" created: node "0778cec7", group "setup"
    Allocation "a6a487ec" created: node "0778cec7", group "setup"
    Allocation "a756cdd6" created: node "59f6e93e", group "setup"
    Allocation "b40a3857" created: node "e989118e", group "setup"
    Allocation "d2b7c891" created: node "59f6e93e", group "setup"
    Allocation "df0b86d2" created: node "0778cec7", group "setup"
    Allocation "fae6ec3c" created: node "59f6e93e", group "setup"
    Allocation "7a9a2244" created: node "e989118e", group "setup"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "62fde126" finished with status "complete"
```

### Job Spec
```
$ curl http://nomad:4646/v1/job/<scrubbed-jobid>
{
  "Region": "us-east",
  "ID": "<scrubbed-jobid>",
  "ParentID": "",
  "Name": "<scrubbed-jobid>",
  "Type": "batch",
  "Priority": 50,
  "AllAtOnce": false,
  "Datacenters": [
    "us-east-1d",
    "us-east-1a",
    "us-east-1c"
  ],
  "Constraints": null,
  "TaskGroups": [
    {
      "Name": "setup",
      "Count": 1,
      "Constraints": null,
      "RestartPolicy": {
        "Attempts": 3,
        "Interval": 6.048e+14,
        "Delay": 15000000000,
        "Mode": "fail"
      },
      "Tasks": [
        {
          "Name": "migrate",
          "Driver": "docker",
          "Config": {
            "args": [
              "db:migrate",
              "db:seed"
            ],
            "auth": <scrubbed>,
            "command": "rake",
            "image": "<scrubbed>"
          },
          "Env": {
            "VAULT_ADDR": "<scrubbed>",
            "VAULT_TOKEN": "<scrubbed>"
          },
          "Services": [
            {
              "Name": "<scrubbed-jobid>",
              "Tags": null,
              "PortLabel": "",
              "Checks": null
            }
          ],
          "Constraints": null,
          "Resources": {
            "CPU": 500,
            "MemoryMB": 128,
            "DiskMB": 300,
            "IOPS": 0,
            "Networks": [
              
            ]
          },
          "Meta": null,
          "KillTimeout": 5000000000,
          "LogConfig": {
            "MaxFiles": 10,
            "MaxFileSizeMB": 10
          }
        }
      ],
      "Meta": null
    }
  ],
  "Update": {
    "Stagger": 0,
    "MaxParallel": 0
  },
  "Periodic": null,
  "GC": true,
  "Meta": null,
  "Status": "running",
  "StatusDescription": "",
  "CreateIndex": 40993,
  "ModifyIndex": 40995,
  "JobModifyIndex": 40993
}
```

**Comment by dadgar** [comment] 2016-03-10 23:20
Hey,

Would you mind sharing reproduction steps? Wasn't able to reproduce.

**Comment by BSick7** [comment] 2016-03-10 23:38
I was afraid you were going to ask that.
I'll tell you what I did and then maybe we can figure out the right steps to reproduce.
I'm assuming foo.hcl is the hcl version of above job spec.
I'm also assuming the task I'm running fails; a typical allocation looks like this
```
$ nomad alloc-status d2b7c891
ID              = d2b7c891
Eval ID         = 62fde126
Name            = foo.setup[0]
Node ID         = 59f6e93e
Job ID          = foo
Client Status   = dead
Evaluated Nodes = 2
Filtered Nodes  = 0
Exhausted Nodes = 0
Allocation Time = 34.09µs
Failures        = 0

==> Task "migrate" is "dead"
Recent Events:
Time                   Type        Description
10/03/16 17:51:56 EST  Terminated  Exit Code: 1, Exit Message: "Docker container exited with non-zero exit code: 1"
10/03/16 17:49:54 EST  Started     <none>
10/03/16 17:49:36 EST  Terminated  Exit Code: 1, Exit Message: "Docker container exited with non-zero exit code: 1"
10/03/16 17:47:34 EST  Started     <none>
10/03/16 17:47:15 EST  Terminated  Exit Code: 1, Exit Message: "Docker container exited with non-zero exit code: 1"
10/03/16 17:45:13 EST  Started     <none>
10/03/16 17:44:56 EST  Terminated  Exit Code: 1, Exit Message: "Docker container exited with non-zero exit code: 1"
10/03/16 17:42:54 EST  Started     <none>
10/03/16 17:42:53 EST  Received    <none>

==> Status
Allocation "d2b7c891" status "dead" (0/2 nodes filtered)
  * Score "59f6e93e-91be-9ba0-2fc3-1e77be884aa4.binpack" = 6.178288
  * Score "59f6e93e-91be-9ba0-2fc3-1e77be884aa4.job-anti-affinity" = -10.000000
  * Score "e989118e-6472-c09a-f01c-264c421c9684.binpack" = 6.178288
  * Score "e989118e-6472-c09a-f01c-264c421c9684.job-anti-affinity" = -10.000000
```

```
$ nomad run foo.hcl
# wait until status is dead
$ nomad status foo
# output of this will be 1 evaluation with 1 dead alloc

$ nomad run foo.hcl
# wait until status is dead
$ nomad status foo
# output will be 2 evaluations and 3 allocations
# alloc-1 is associated to eval-1
# alloc-2 and alloc-3 are associated with eval-2
```

Every consecutive run will add an extra allocation per evaluation.

**Comment by BSick7** [comment] 2016-03-10 23:40
After 8 runs, here is an example status dump:
```
$ nomad status foo
ID          = foo
Name        = foo
Type        = batch
Priority    = 50
Datacenters = us-east-1d,us-east-1a,us-east-1c
Status      = dead
Periodic    = false

==> Evaluations
ID        Priority  Triggered By    Status
62fde126  50        job-register    complete
c226ca13  50        job-deregister  complete
c47b0898  50        job-register    complete
db96e00d  50        job-register    complete
a3016137  50        job-register    complete
945a9020  50        job-register    complete

==> Allocations
ID        Eval ID   Node ID   Task Group  Desired  Status
d2b7c891  62fde126  59f6e93e  setup       run      dead
a756cdd6  62fde126  59f6e93e  setup       run      dead
df0b86d2  62fde126  0778cec7  setup       run      dead
7a9a2244  62fde126  e989118e  setup       run      dead
8db0b439  62fde126  0778cec7  setup       run      dead
a6a487ec  62fde126  0778cec7  setup       run      dead
fae6ec3c  62fde126  59f6e93e  setup       run      dead
b40a3857  62fde126  e989118e  setup       run      dead
7b0dc394  c47b0898  0778cec7  setup       stop     dead
e7679c0c  c47b0898  59f6e93e  setup       stop     dead
bf07e9fd  c47b0898  e989118e  setup       stop     dead
cfe24a15  c47b0898  59f6e93e  setup       stop     dead
aa60e3f3  db96e00d  0778cec7  setup       stop     dead
277c5028  db96e00d  e989118e  setup       stop     dead
2f80e2ba  a3016137  0778cec7  setup       stop     dead
755706cc  945a9020  0778cec7  setup       stop     dead
```

**Comment by dadgar** [comment] 2016-03-10 23:44
Is the job type batch or service?

**Comment by BSick7** [comment] 2016-03-10 23:46
batch

**Comment by dadgar** [comment] 2016-03-11 00:34
And last question hopefully: Is this Nomad 0.3 or you are on head?

**Comment by BSick7** [comment] 2016-03-11 03:00
Client:
```
$ nomad -v
Nomad v0.3.0
```

Servers
```
$ nomad server-members
Name               Address         Port  Status  Protocol  Build  Datacenter  Region
manager-0.us-east  172.24.200.4    4648  alive   2         0.3.0  us-east-1a  us-east
manager-1.us-east  172.24.200.68   4648  alive   2         0.3.0  us-east-1c  us-east
manager-2.us-east  172.24.200.132  4648  alive   2         0.3.0  us-east-1d  us-east
```

**Comment by dadgar** [comment] 2016-03-21 20:53
@BSick7 could you try again with Nomad 0.3.1. I believe this may be fixed. I couldn't reproduce it on either 0.3.0 or 0.3.1. However the state of the allocation now enters the failed state instead of dead which makes me believe it may be fixed in the newer version

**Comment by BSick7** [comment] 2016-03-23 00:42
I would love to give it a shot, but it may take until the end of week for me to clear some time for it.
Stay tuned.

**Comment by dadgar** [comment] 2016-03-23 01:10
I would still love if you could provide a job spec to make this reproducible on Nomad 0.3.0 as well so I could add a unit test to make sure we don't regress

**Comment by dadgar** [comment] 2016-04-11 21:25
@BSick7 I am going to close and will reopen when you try again if the same results are there.

**Closed by dadgar** 2016-04-11 21:25 UTC
Labels: bug, scheduling
