### ISSUE TITLE
prometheus exporter: `nomad_driver_docker_oom` is not actually a counter

### ISSUE THREAD

**Issue by pznamensky** [hashicorp/nomad#4449] opened 2018-06-25 11:46 UTC
### Nomad version
 ~ $ nomad version
Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)

### Issue
`nomad_driver_docker_oom` counter resets after some time.
Because of this it's hard to understand "OOM-killer speed"

### Reproduction steps

1. start container which is being killed by OOM-killer and then being restarted by nomad
2. get value of `nomad_driver_docker_oom` from https://nomad-client:4646/v1/metrics?format=prometheus
3. wait 10 minutes
4. get value of `nomad_driver_docker_oom` again

### Expected behavior
counter should increase over time

At the screenshot you can see values of `nomad_driver_docker_oom`, but it's not the `rate(nomad_driver_docker_oom)` as you could think.
![screenshot_20180625_150034](https://user-images.githubusercontent.com/14976219/41849151-9a5899ba-7888-11e8-8a12-3d7b479fe539.png)

**Comment by ncabatoff** [comment] 2019-01-31 15:35
If you're using rate(), any counter resets should be hidden from you.  That's the whole point of a counter in Prometheus.

**Comment by pznamensky** [comment] 2019-04-08 09:49
@ncabatoff Yes, you're right.
But it works well in cases when there is any value of a counter.
```
0   0   1   0
0s  30s 60s 90s
```
^^ This works fine
```
-   -   1   -
0s  30s 60s 90s
```
^^ And this doesn't
When a counter is absent, you can't rely on a rate() result.

**Comment by ncabatoff** [comment] 2019-04-08 13:31
Ah, you're right.  What about using an OR, e.g. `delta(nomad_driver_docker_oom[interval]) OR nomad_driver_docker_oom`?  That way if it increases over your interval, you'll see by how much, and if there's only a single sample in a given interval you'll see its value.

The real problem I think is that [go-metrics](https://github.com/armon/go-metrics) expires Prometheus metrics after some time.  [Vault Prometheus telemetry](https://www.vaultproject.io/docs/configuration/telemetry.html) uses a config key `prometheus_retention_time` to configure this, maybe Nomad could get the same?

**Comment by pznamensky** [comment] 2019-04-09 08:40
> What about using an OR, e.g. `delta(nomad_driver_docker_oom[interval]) OR nomad_driver_docker_oom`?

This workaround works not perfectly, unfortunately. Another possible solution could be found here:
https://www.robustperception.io/existential-issues-with-metrics
But the best solution as for me is initialising `nomad_driver_docker_oom = 0` for each task at the start.

>The real problem I think is that go-metrics expires Prometheus metrics after some time

Yes, I think it would be great to have something like `prometheus_retention_time` for Nomad

**Comment by tgross** [comment] 2021-04-13 13:12
Going to close this as a dupe of https://github.com/hashicorp/nomad/issues/10155 even though that issue is newer; it's verified on a current version of Nomad and has the specific fix we need to implement called out.

**Closed by tgross** 2021-04-13 13:12 UTC
Labels: stage/needs-verification, theme/metrics, type/enhancement
