### ISSUE TITLE
NOMAD_IP_<label> Variables not Exposed In Bridge Mode is Serious Limitation

### ISSUE THREAD

**Issue by adawalli** [hashicorp/nomad#8264] opened 2020-06-24 14:22 UTC
### Nomad version
Nomad v0.11.3 (8918fc804a0c6758b6e3e9960e4eb2e605e38552)

### Operating system and Environment details
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

### Issue
The bridge IP address (that gets registered with consul) does not get exposed as an environment variable in the task container. This seems to be described here: https://www.nomadproject.io/docs/job-specification/network#limitations

This can end up being a serious limitation though. In the case where a service communicates only via IP address (e.g., Traefik->Consul integration), the inability to request a certificate from VAULT with the actual IP SANS renders secure communication between Traefik and Nomad containers impossible when using TLS termination.

Are there plans to provide the IP address to the environment?

**Comment by tgross** [comment] 2020-06-24 16:04
Agreed @adawalli! I'll add this to our project board! Thanks!

**Comment by tgross** [comment] 2021-01-26 14:46
This is a dupe of https://github.com/hashicorp/nomad/issues/9781 and that has a bit more information, so I'm going to close this one in lieu of #9781 (the `hcc/cst` tag is already applied there and that issue is what's being tracked in the internal ticket anyways).

**Closed by tgross** 2021-01-26 14:46 UTC
Labels: hcc/cst, stage/accepted, theme/networking, type/enhancement
