### ISSUE TITLE
Nomad clients running out of memory

### ISSUE THREAD

**Issue by robsonj** [hashicorp/nomad#13935] opened 2022-07-29 00:31 UTC
### Nomad version
1.2.5

### Operating system and Environment details
CentOS 8.5, 3 server nodes, 8cores, 16gb of memory each
3 client nodes, 112 cores, 128gb memory each

### Issue
We are seeing our server nodes constantly running out of memory and becoming unresponsive. To the point that we have to reset the whole nomad server infra - remove the server data directory and restart everything, re-setup ACL's etc.

this occurs when we have 30k-40k batch jobs pending, so it could be that the server nodes are undersized now for our workload. If this is the case what is the recommended server hardware size in order to handle 40,000 - 1,000,000 queued jobs please?

Note our job workload has increased a lot in the last few days, w which is when we started seeing this issue.

**Comment by tgross** [comment] 2022-08-02 12:35
@robsonj I'm going to close this issue as a duplicate of https://github.com/hashicorp/nomad/issues/13933

**Closed by tgross** 2022-08-02 12:35 UTC
Labels: type/bug
