### ISSUE TITLE
unclear how to assign ip address for docker container

### ISSUE THREAD

**Issue by macb** [hashicorp/nomad#209] opened 2015-10-03 18:36 UTC
I'd like to launch containers and have docker forward all interfaces to the container for the dynamic port. It doesn't seem like that is currently supported as `ip` isn't exposed in the network config and whatever is configuring it is defaulting to the `10.20.x.x` network which is reachable from the host but no where else.

I could easily be missing something though.

> Nomad uses port binding to expose services running in containers using the port space on the host's interface. For example, Nomad host running on 1.2.3.4 may allocate port 22333 to a task, so you would access that service via 1.2.3.4:22333.

```
root@nomad-client-tor1-0:~# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                         NAMES
a9a8f68d8fd1        macb/repeater       "/bin/sh -c 'socat -v"   11 hours ago        Up 11 hours         10.20.0.166:21470->9000/tcp   drunk_mahavira
8ba64f31bd7f        macb/repeater       "/bin/sh -c 'socat -v"   11 hours ago        Up 11 hours         10.20.0.166:59453->9000/tcp   jolly_franklin
```

**Comment by achanda** [comment] 2015-10-04 03:17
`docker` selects a IP range to be used on `docker0` (in bridge mode). All containers are allocated IPs from that range. Nomad does not provide a way to configure that. You can try to:
1. Assign a IP to `docker0`. This can be done by starting the daemon with a `--bip` parameter as described in https://docs.docker.com/articles/networking/#docker0 This is independent of nomad.
2. Use host networking mode. This can be done by passing `network_mode=host` in the configuration for a nomad task.

Please let me know if I misunderstood.

**Comment by rvm2015** [comment] 2015-10-04 05:05
You can also start docker in non-masquerading mode, turn on routing in the kernel, and then route traffic through the host IP. You'll run into problems if you have more than one docker host however as you'll have to configure the bridge interface to have it's own private subnet on each host. It's doable but ugly to scale.

**Comment by macb** [comment] 2015-10-04 20:57
Hmm, I'm not sure if we're all talking about the same thing. In `bridged` mode if you start a container like:

```
root@nomad-client-tor1-4:~# docker run -d -p 1234:9000 macb/repeater
b3506717030c8fa92d4a31ce3c6bd21a3193d80cddb0f7cc4a29ff882bfc14ce
root@nomad-client-tor1-4:~# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                         NAMES
b3506717030c        macb/repeater       "/bin/sh -c 'socat -v"   4 seconds ago       Up 3 seconds        0.0.0.0:1234->9000/tcp        naughty_galileo
6bbdf4988653        macb/repeater       "/bin/sh -c 'socat -v"   26 hours ago        Up 26 hours         10.20.0.167:32755->9000/tcp   naughty_curie
00ca858b6b03        macb/repeater       "/bin/sh -c 'socat -v"   38 hours ago        Up 38 hours         10.20.0.167:50897->9000/tcp   distracted_kalam
66a4abe62b1f        macb/repeater       "/bin/sh -c 'socat -v"   38 hours ago        Up 38 hours         10.20.0.167:46592->9000/tcp   adoring_engelbart
```

Then it's available both on localhost as well as via the server's IP:
```
root@nomad-client-tor1-4:~# nc 127.0.0.1 1234
hi
hi
```

It appears that when nomad starts the container it finds an IP to apply to it and sets the `-p` flag as `ip:port:port`. This is seen in nomad's logs if `log_level="DEBUG"` mode is enabled [here](https://github.com/hashicorp/nomad/blob/master/client/driver/docker.go#L163).

**Comment by rvm2015** [comment] 2015-10-05 19:48
My understanding is you would have to assign dynamic_ports = ["9000"], this will pass a NOMAD_PORT_9000 environment variable through to the container when it's started. This port will be a random port in the service ports range, nomad is expecting the container to register this port in service discovery somewhere (consul or etcd). You can see which one it is by doing docker ps or docker inspect on the container.

As far as I can tell there is no way to set a 1:1 mapping of, "I want docker to expose this container port as this docker host port," through nomad.

**Comment by macb** [comment] 2015-10-05 19:56
[This](https://github.com/macb/nomad-bootstrap/blob/master/work/repeater.nomad) is the job that's being run which has worked well for starting the container and having it map a dynamic port to the port in the container. However it also applies and IP address when I'd rather it use `0.0.0.0` so it's only reachable from the host. `nc 10.20.0.167 32755` instead of `nc 127.0.0.1 32755` in the `docker ps` from https://github.com/hashicorp/nomad/issues/209#issuecomment-145387262.

**Comment by cbednarski** [comment] 2015-10-09 08:00
@macb Thanks for the report. We are working out the kinks in networking (some bug fixes have landed in master already), and binding to 127.0.0.1 is not intended.

To clarify the design, we bind a task to one interface (ip address), potentially with multiple ports on that IP. The scheduler allows you some control over this so you can select a private or public subnet. The design does not currently support binding to 0.0.0.0.

**Comment by skozin** [comment] 2015-11-27 22:43
@cbednarski, could you please tell me how I can select private or public subnet for a specific Docker task? I was unable to find this in the docs and thought it is not possible yet.

**Comment by diptanu** [comment] 2015-11-28 07:08
@skozin We don't support selecting one of many interfaces in Nomad yet. Support for doing that is going to come fairly soon.

**Comment by skozin** [comment] 2015-11-28 14:26
@diptanu Thanks for the info. That's the only thing that really prevents us from using Nomad.

We have cluster of machines, and some of these machines have both public and private interfaces. These two-nic machines run infrastructure services, that need to listen only on private interface, as well as public services, which should listen on public interface.

I really hope that it will be available soon. Currently we're upgrading our infrastructure and we'd really like to give Nomad a try, because it looks very promising.

The ability to listen on all interfaces is also a desirable feature, although not as critical for us as the ability to select one specific interface.

**Comment by dontrebootme** [comment] 2015-12-09 01:11
I think the point of this thread that @macb is trying to bring up is that Nomad is incorrectly passing an IP with the dynamic port association to Docker and that IP in some cases is wrong (eth0 vs eth1). You can see that Nomad is passing not only the dynamic port, but also an IP when you do a `docker inspect`.

**Comment by dontrebootme** [comment] 2015-12-09 04:15
For example, even when bind and advertise are set to a specific IP, the command sent to docker for the port mapping is using another IP.
```
vagrant@docker1:~$ cat /etc/nomad/nomad.json
{
  "advertise_addr": "10.7.0.21",
  "bind_addr": "10.7.0.21",
  "data_dir": "/var/lib/nomad",
  "datacenter": "nomad-intro",
  "enable_syslog": true,
  "syslog_facility": "LOCAL0",
  "log_level": "INFO",
  "client": {
    "enabled": true,
    "servers": [ "10.7.0.10:4647" ]
  }
}
```
vagrant@docker1:~$ docker ps -a
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                              NAMES
7099eebb018f        dontrebootme/microbot:v1   "/bin/sh -c /start_ng"   15 seconds ago      Up 14 seconds       10.0.2.15:50793->80/tcp, 10.0.2.15:50793->80/udp   microbot-4361f96b-fb84-4d25-41d9-d29f2c88d12f
ded4fb62469d        dontrebootme/microbot:v1   "/bin/sh -c /start_ng"   15 seconds ago      Up 14 seconds       10.0.2.15:25027->80/tcp, 10.0.2.15:25027->80/udp   microbot-6fc76072-6be1-587b-f83e-fb701e22e0f0
9415b6d4fa95        dontrebootme/microbot:v1   "/bin/sh -c /start_ng"   15 seconds ago      Up 15 seconds       10.0.2.15:56609->80/tcp, 10.0.2.15:56609->80/udp   microbot-65306089-b2e3-105f-4155-d42b904a379a
```

`docker inspect` shows me that a HostIp is being passed that differs from the configuration above.
```
        "Ports": {
            "80/tcp": [
                {
                    "HostIp": "10.0.2.15",
                    "HostPort": "50793"
                }
            ],
            "80/udp": [
                {
                    "HostIp": "10.0.2.15",
                    "HostPort": "50793"
                }
            ]
        },
```

**Comment by diptanu** [comment] 2015-12-09 08:00
@dontrebootme Did you try setting the ```network_interface``` option? This is a client specific option which forces Nomad client to fingerprint a specific network interface and not look at anything else on the host on which the Agent is running. This would make Nomad to always choose this interface. The option takes an interface name.

The bind addr can be different than the network interface that Nomad fingerprints and allocates ports to Tasks.

Let me know if that works?

**Comment by dontrebootme** [comment] 2015-12-09 18:51
I can confirm that setting network_interface in my nomad client configuration did it for me.

Snippet from my config:
```
  "client": {
    "enabled": true,
    "network_interface": "eth1",
    "servers": [ "10.7.0.10:4647" ]
  }
```

**Comment by skozin** [comment] 2015-12-24 19:30
> @skozin We don't support selecting one of many interfaces in Nomad yet. Support for doing that is going to come fairly soon.

@diptanu Do you have any updates on this (and #264, which is closely related)? Can I assume that by "fairly soon" you mean 0.3? Should I open separate issue for that use case (selecting specific interface for specific Docker job)?

**Comment by skozin** [comment] 2016-01-05 18:34
@diptanu, @cbednarski, I've opened a separate issue #646 for my request; but the proposed solution covers listening on all interfaces as well.

**Comment by safanaj** [comment] 2016-06-07 17:33
Hi, the IP od dockers services registered in consul shouldn't not select dynamically, inspecting the started docker?
[here](https://github.com/hashicorp/nomad/blob/master/nomad/structs/structs.go#L1735) I think nomad should inspect the task (atleast for docker driver) instead just to use NetworkResources

**Comment by dadgar** [comment] 2017-01-03 18:50
Going to close this since the original was a config bug and there is a subsequent issue for multiple networks #646

**Closed by dadgar** 2017-01-03 18:50 UTC
Labels: bug, networking
