### ISSUE TITLE
update stanza in API output wrong

### ISSUE THREAD

**Issue by hsmade** [hashicorp/nomad#3032] opened 2017-08-16 07:36 UTC
Nomad version: 0.6.0

job HCL:

    job "wim-test-update" {
      type = "service"
      datacenters = ["dc1"]
    
      update {
        max_parallel     = 1
        health_check     = "checks"
        min_healthy_time = "3s"
        healthy_deadline = "10m" 
        auto_revert      = true
      }
    
      group "frontend" {
        count = 5
        task "webserver" {
          driver = "docker"
          config {
            image = "abiosoft/caddy"
            args = ["log stdout"]
            port_map { web = 2015 }
          }
          resources {
            network {
              port "web" {}
            }
            memory = 10
          }
          service {
            name = "simple-service"
            port = "web"
            tags = ["urlprefix-/"]
            check {
              type = "http"
              path = "/"
              port = "web"
              timeout = "1s"
              interval = "2s"
            }
          }
        }
      }
    }

After I run this, query the API:

curl -s localhost:4646/v1/job/wim-test-update|jq .Update

    {
      "Stagger": 30000000000,
      "MaxParallel": 1,
      "HealthCheck": "",
      "MinHealthyTime": 0,
      "HealthyDeadline": 0,
      "AutoRevert": false,
      "Canary": 0
    }

My update settings do seem to be honored, so it's probably just the rendering of the API that's wrong.

**Comment by schmichael** [comment] 2017-08-16 17:13
The update stanza on the task group _is_ correct and will take precedence, so I believe this is just a bug or deficiency in how we translate the hcl to json... looking into it.

**Comment by dadgar** [comment] 2017-08-16 17:25
Hey @hsmade,

This is actually by design. As the HCL and JSON job gets translated into the internal job structure the job level update stanza is merged with the task groups so the original submitted version is lost in a way as we translate back out.

**Closed by dadgar** 2017-08-16 17:25 UTC
Labels: api, bug, jobspec
