### ISSUE TITLE
[question] Nomad retrying failed job forever

### ISSUE THREAD

**Issue by kimh** [hashicorp/nomad#3257] opened 2017-09-21 00:12 UTC
### Nomad version
0.6.3

### Operating system and Environment details
OSX 10.11.6 and Linux

### Issue
When I run the following job that never succeeds (because of ping noexist command), Nomad keeps retrying the job forever even though I set "attempts = 3".

It's worth to note that if I increase `internal` to say `20s`, then the job failed after 3 attempts properly.

What am I missing?

Thanks!

### Reproduction steps
Run Nomad server with `nomad agent -dev` and submit a job with `nomad run example.nomad`.

### Nomad Server logs (if appropriate)
N/A

### Nomad Client logs (if appropriate)

```
➜  nomad run /opt/nomad/example.nomad
==> Monitoring evaluation "2c3bb70e"
    Evaluation triggered by job "test"
    Allocation "c533af3d" created: node "2d949299", group "test-1"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "2c3bb70e" finished with status "complete"

➜  nomad status test
ID            = test
Name          = test
Submit Date   = 09/20/17 12:43:49 JST
Type          = batch
Priority      = 50
Datacenters   = dc1
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
test-1      0       1         0        0       0         0

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created At
c533af3d  2d949299  test-1      0        run      pending  09/20/17 12:43:49 JST

➜ nomad alloc-status c533af3d | grep "Total Restarts"
Total Restarts = 14
```

### Job file (if appropriate)

```
job "test" {
  datacenters = ["dc1"]
  type = "batch"

  group "test-1" {
    count = 1
    restart {
      attempts = 3
      interval = "5s"
      delay = "1s"
      mode = "fail"
    }

    task "test-1" {
      driver = "raw_exec"
      config {
        command = "bash"
        args = ["-c", "sleep 2; ping noexist"]
      }
    }
  }
}
```

**Comment by dadgar** [comment] 2017-09-25 18:12
@kimh The restart stanza you have provided tells Nomad that if the task fails 3 times within a five second window to fail the task. But the conditions make it so that it is impossible to hit 3 in that window. It looks like this:

0: Start and sleep 2 seconds, then fail
2: Apply 1 second restart delay
3: Start and sleep 2 seconds, then fail
5: repeat...

So you only get 1 failure per window.

Hope that helps. I am going to close this since it is not a bug but feel free to leave a comment if it didn't make sense!

Thanks,
Alex

**Closed by dadgar** 2017-09-25 18:12 UTC

**Comment by kimh** [comment] 2017-09-26 00:40
Thanks for the explanation!

> But the conditions make it so that it is impossible to hit 3 in that window. 

It seems to me that this doesn't justify Nomad can keep running builds forever, though. It's less confusing if Nomad retries less than or equal to max retry count. Thoughts?

**Comment by dadgar** [comment] 2017-09-27 17:33
@kimh It is following the user specified restart policy. I think it would be more confusing if it deviated from that. Further the example policy in your issue is not realistic. The interval should always be much longer.
