### ISSUE TITLE
Exec should kill spawned process if reattaching fails

### ISSUE THREAD

**Issue by tugbabodrumlu** [hashicorp/nomad#632] opened 2015-12-24 19:30 UTC
I upgraded Nomad from Version 0.2.1 to 0.2.3 in the morning. With the previous version if I kill Nomad after I run a job, and then restart Nomad again, I was able to see the previously registered services from Consul UI. But with the new version this is not the case, although I could still list the processes listed when I run ps aux command.

**Comment by diptanu** [comment] 2015-12-24 19:55
@tugbabodrumlu By restarting Nomad, do you mean restarting the Nomad client?

**Comment by diptanu** [comment] 2015-12-24 20:00
So I tried reproducing the issue by running a task and restarting the Nomad client agent, and when the agent was restarted the client re-registered the service and the check and this is how it is supposed to behave. Can you provide some more details please?

**Comment by tugbabodrumlu** [comment] 2015-12-25 07:10
* First, I start a nomad server and client by using the config files listed [here](https://github.com/hashicorp/nomad/tree/master/demo/vagrant) , then I run a sample job. When I run `nomad status job` I can see it is complete and services and health check can be seen from Consul UI.
* Then I kill nomad by running `killall nomad` (so both client and server are down) When I check Consul UI, I can still see the services and health checks.
* After that, I start nomad server and client again just like before. Then I check from Consul UI and services and health checks are gone. However I can still list the processes listed when I run ps aux command.

This was definitely not like that when I was using the 0.2.1.

**Comment by diptanu** [comment] 2015-12-25 07:41
@tugbabodrumlu I am sorry I still can't reproduce the issue 

I used the vagrant demo box and the configurations that you linked to - 

Here are the steps that I followed -

* Started the nomad server using server.hcl from the demo

* Started one nomad client using the client2.hcl from the demo

* Used nomad init to generate the example.nomad job file, and ran it.

* Killed nomad via ```killall nomad``` and restarted the nomad server first and then the client. 

* Queried consul using the api ```curl http://127.0.0.1:8500/v1/agent/services``` and ```curl http://127.0.0.1/v1/agent/checks``` and still could see the service and the check for the redis container.

However, on running both client1 and client2 on the same machine one of the client tries to remove the service and checks the other client registers because the services implementation assumes that only one Nomad agent will be running on a node in the client mode.

**Comment by tugbabodrumlu** [comment] 2015-12-25 08:25
@diptanu  I checked it again. My client configuration is slightly different
```
# Increase log verbosity
log_level = "DEBUG"

# Setup data dir
data_dir = "/tmp/client1"

enable_syslog = true
syslog_facility = "LOCAL0"

# Enable the client
client {
    options = {
        "driver.raw_exec.enable" = "1"
    }
    enabled = true

    # For demo assume we are talking to server1. For production,
    # this should be like "nomad.service.consul:4647" and a system
    # like Consul used for service discovery.
     servers = ["127.0.0.1:4647"]
}

# Modify our port to avoid a collision with server1
ports {
    http = 5656
}
```

This is the error message I got from nomad client after I restart nomad client. Maybe it helps?

```
    2015/12/25 08:18:34 [INFO] client: using state directory /tmp/client1/client
    2015/12/25 08:18:34 [INFO] client: using alloc directory /tmp/client1/alloc
    2015/12/25 08:18:34 [INFO] fingerprint.consul: consul agent is available
    2015/12/25 08:18:34 [DEBUG] client: periodically fingerprinting consul at duration 15s
    2015/12/25 08:18:34 [DEBUG] fingerprint.network: Detected interface eth0  with IP 10.97.170.19 during fingerprinting
    2015/12/25 08:18:34 [DEBUG] client: applied fingerprints [arch consul cpu host memory network storage]
    2015/12/25 08:18:34 [DEBUG] driver.java: must run as root user on linux, disabling
    2015/12/25 08:18:34 [DEBUG] driver.rkt: must run as root user, disabling
    2015/12/25 08:18:34 [DEBUG] driver.docker: using client connection initialized from environment
    2015/12/25 08:18:34 [DEBUG] driver.docker: privileged containers are disabled
    2015/12/25 08:18:34 [DEBUG] driver.docker: could not connect to docker daemon at unix:///var/run/docker.sock: Get http://unix.sock/version: dial unix /var/run/docker.sock: connect: no such file or directory
    2015/12/25 08:18:34 [DEBUG] driver.exec: must run as root user, disabling
    2015/12/25 08:18:34 [WARN] driver.raw_exec: raw exec is enabled. Only enable if needed
    2015/12/25 08:18:34 [DEBUG] client: available drivers [raw_exec]
    2015/12/25 08:18:34 [ERR] client: failed to open handle to task 'server' for alloc '7a4b0af4-718f-753a-a17b-11a401972b3f': failed to open ID {"SpawnPid":48134,"SpawnPpid":48107,"StateFile":"/tmp/client1/alloc/7a4b0af4-718f-753a-a17b-11a401972b3f/server_exit_status","UserPid":48140,"UserCmd":{"Path”:”XXX”,”Args”:[“XXX”,”-p57951"],"Env":["NOMAD_MEMORY_LIMIT=100","NOMAD_CPU_LIMIT=100","NOMAD_IP=10.97.170.19","NOMAD_PORT_srvport=57951","NOMAD_ALLOC_DIR=/tmp/client1/alloc/7a4b0af4-718f-753a-a17b-11a401972b3f/alloc","NOMAD_TASK_DIR=/tmp/client1/alloc/7a4b0af4-718f-753a-a17b-11a401972b3f/server/local"],"Dir":"/tmp/client1/alloc/7a4b0af4-718f-753a-a17b-11a401972b3f/server","Stdin":null,"Stdout":null,"Stderr":null,"ExtraFiles":null,"SysProcAttr":null,"Process":null,"ProcessState":null},"Logs":{"Stdin":"/dev/null","Stdout":"/tmp/client1/alloc/7a4b0af4-718f-753a-a17b-11a401972b3f/server/local/server.stdout","Stderr":"/tmp/client1/alloc/7a4b0af4-718f-753a-a17b-11a401972b3f/server/local/server.stderr"},"Chroot":""}
: Spawner not alive and exit code not written
    2015/12/25 08:18:34 [DEBUG] client: starting runner for alloc '7a4b0af4-718f-753a-a17b-11a401972b3f'
    2015/12/25 08:18:34 [DEBUG] client: starting task context for 'server' (alloc '7a4b0af4-718f-753a-a17b-11a401972b3f')
    2015/12/25 08:18:34 [INFO] consul: registering service server-bind-port with consul.
    2015/12/25 08:18:34 [ERR] client: failed to update allocation: rpc error: No cluster leader
    2015/12/25 08:18:34 [ERR] client: failed to update alloc '7a4b0af4-718f-753a-a17b-11a401972b3f' status to running: rpc error: No cluster leader
    2015/12/25 08:18:34 [INFO] consul: registering check with ID: 794f1f28921114530ae7bdcb7c6f55389a7b0c32 for service: nomad-registered-service-9184577c-089b-c005-cd4d-dd5560e69e84
    2015/12/25 08:18:34 [INFO] consul: deregistering service server-bind-port with consul
    2015/12/25 08:18:34 [ERR] client: failed to complete task 'server' for alloc '7a4b0af4-718f-753a-a17b-11a401972b3f': Wait returned exit code 255, signal 0, and error <nil>
    2015/12/25 08:18:34 [INFO] client: Restarting Task: server
    2015/12/25 08:18:34 [DEBUG] client: Sleeping for 10s before restarting Task server
    2015/12/25 08:18:44 [INFO] consul: registering service server-bind-port with consul.
    2015/12/25 08:18:44 [INFO] consul: registering check with ID: 794f1f28921114530ae7bdcb7c6f55389a7b0c32 for service: nomad-registered-service-9184577c-089b-c005-cd4d-dd5560e69e84
    2015/12/25 08:18:44 [INFO] consul: deregistering service server-bind-port with consul
    2015/12/25 08:18:44 [ERR] client: failed to complete task 'server' for alloc '7a4b0af4-718f-753a-a17b-11a401972b3f': Wait returned exit code 255, signal 0, and error <nil>
    2015/12/25 08:18:44 [INFO] client: Restarting Task: server
    2015/12/25 08:18:44 [DEBUG] client: Sleeping for 10s before restarting Task server
2015/12/25 08:18:44 [INFO] consul: registering service server-bind-port with consul.
    2015/12/25 08:18:44 [INFO] consul: registering check with ID: 794f1f28921114530ae7bdcb7c6f55389a7b0c32 for service: nomad-registered-service-9184577c-089b-c005-cd4d-dd5560e69e84
    2015/12/25 08:18:44 [INFO] consul: deregistering service server-bind-port with consul
    2015/12/25 08:18:44 [ERR] client: failed to complete task 'server' for alloc '7a4b0af4-718f-753a-a17b-11a401972b3f': Wait returned exit code 255, signal 0, and error <nil>
    2015/12/25 08:18:44 [INFO] client: Restarting Task: server
    2015/12/25 08:18:44 [DEBUG] client: Sleeping for 10s before restarting Task server

```

**Comment by diptanu** [comment] 2015-12-25 08:55
@tugbabodrumlu Thanks for posting the logs. Looks like the reason why the service and checks are not visible in Consul after restart is because the Nomad client thinks that the ```server``` task is actually crashing and hence the Nomad client is restarting the ```server``` task after sleeping for 10s every time before it restarts. The reason why you could see this working in 0.2.1 was - we were not de-registering services from Consul while restarting a task which was not a proper behavior and has been fixed in 0.2.3.

Also the log shows that the nomad client after restarting is not able to find the state of the spawner process which keeps track of the task that is being run by the raw_exec driver.

@dadgar Can you please take a look at this? I think the spawner process is getting killed along with the client but the task that the spawner was tracking doesn't get killed and when the client is trying to restart the task, the spawner is probably not able to restart the task since the original task was not killed (and if the process is a server process, most likely it is still bound to a port which the new process is trying to bind to and is crashing). Just my hunch.

**Comment by kaskavalci** [comment] 2015-12-25 09:34
It is true that spawner process gets killed with nomad because of ```killall nomad```. It's nice that server task doesn't get killed alongside with spawner but I think spawner should recognize the previously spawned task and attach to it. Is that not the expected behavior?

**Comment by tugbabodrumlu** [comment] 2015-12-25 09:49
@diptanu @dadgar Another thing I might add: After I kill process of server task by running `kill` command, spawn is able to restart it successfully.

**Comment by diptanu** [comment] 2015-12-25 10:19
@tugbabodrumlu Yeah I expected that to happen, like I commented earlier spawner was probably not able to restart the process because the old server process was being boud to the port.

So we will have to think about this a little bit. I don't think it is possible for the child process's life to be bound to spawner's life transparently on even Linux. 

If we controlled the child process too, we could have used the syscall ```prctl``` and asked the kernel to send a signal to the child process when it's parent died but that's not possible since we don't own the binary of the child processes. There are other hacks like redirecting the child's input stream to the parent and check for it's existence, etc but like I said they are not transparent.

@dadgar any thoughts?

**Comment by tugbabodrumlu** [comment] 2016-01-09 16:34
@diptanu @dadgar  Are there any updates regarding this bug?

**Comment by dadgar** [comment] 2016-01-11 17:52
@tugbabodrumlu: Hey, this isn't quite a bug with registering services into consul. The bug is actually that when the Nomad client restarts and can't rebind to a running process, it should kill the process. No work has been started on this but hopefully it will be in 0.3

**Comment by diptanu** [comment] 2016-02-12 21:51
@tugbabodrumlu The fix for this has landed on master. Please let us know if this fixes the problem.

**Closed by diptanu** 2016-02-12 21:51 UTC
Labels: bug, driver/exec, driver/raw_exec
