### ISSUE TITLE
v1/job/invalid_job_id/allocations (and others) return 200 and value rather than 404

### ISSUE THREAD

**Issue by nugend** [hashicorp/nomad#3215] opened 2017-09-14 18:24 UTC
### Nomad version
Nomad v0.6.0

### Operating system and Environment details
 3.10.0-327.36.3.el7.x86_64

### Issue
The nomad HTTP API at `v1/job/any-invalid-job-id/allocations` returns an empty JSON list and a 200 response code. The `v1/job/any-invalid-job-id` endpoint returns a 404 response code.

I don't know what assumptions are made about what this endpoint *should* be returning, but my feeling is that for an invalid or otherwise no-longer valid job id, the current behavior is not correct.

I've also tested the other job sub-apis:

**Returns a 200 code and empty list**

- `v1/job/any-invalid-job-id/allocations`
- `v1/job/any-invalid-job-id/evaluations`
- `v1/job/any-invalid-job-id/deployments`

**Returns a 200 code and empty null**
- `v1/job/any-invalid-job-id/deployment`

**Returns a 404**

- `v1/job/any-invalid-job-id/summary`
- `v1/job/any-invalid-job-id/versions`

### Reproduction steps

GET any of the mentioned endpoints

**Comment by dadgar** [comment] 2017-09-14 18:26
Hey I am closing as a duplicate of: https://github.com/hashicorp/nomad/issues/2994

**Closed by dadgar** 2017-09-14 18:26 UTC

**Comment by nugend** [comment] 2017-09-14 18:28
Sorry. Looked for it, but didn't find it.
