### ISSUE TITLE
[Bug] auto_advertise does not work when nomad in both client and server mode

### ISSUE THREAD

**Issue by capone212** [hashicorp/nomad#1547] opened 2016-08-09 08:55 UTC
### Nomad version
Nomad v0.4.1-dev

### Operating system and Environment details
OS Windows

### Issue
I have built nomad with the last master revision, new nomad does not register itself in consul when it in both client and master mode. This was broken recently, because several weeks earlier it worked. I have tried to explicitly enable auto_advertise setting in config, but it has no effect.

### Reproduction steps
consul.exe agent --bootstrap -server -data-dir data
wait 30 seconds
nomad.exe agent -server -client -data-dir C:\temp\nomad

### Nomad Server logs (if appropriate)

`
    No configuration files loaded
==> Starting Nomad agent...
==> Nomad agent configuration:

                 Atlas: <disabled>
                Client: true
             Log Level: INFO
                Region: global (DC: dc1)
                Server: true

==> Nomad agent started! Log data will stream in below:

    2016/08/09 11:51:01 [INFO] raft: Node at 127.0.0.1:4647 [Follower] entering Follower state (Leader: "")
    2016/08/09 11:51:01 [INFO] serf: Ignoring previous leave in snapshot
    2016/08/09 11:51:01 [INFO] serf: Ignoring previous leave in snapshot
    2016/08/09 11:51:01 [INFO] serf: Ignoring previous leave in snapshot
    2016/08/09 11:51:01 [INFO] serf: EventMemberJoin: a-apshev.global 127.0.0.1
    2016/08/09 11:51:01.673581 [INFO] nomad: starting 8 scheduling worker(s) for [service batch system _core]
    2016/08/09 11:51:01 [WARN] serf: Failed to re-join any previously known node
    2016/08/09 11:51:01.674082 [INFO] nomad: adding server a-apshev.global (Addr: 127.0.0.1:4647) (DC: dc1)
    2016/08/09 11:51:01.676250 [INFO] client: using state directory C:\temp\nomad\client
    2016/08/09 11:51:01.676250 [INFO] client: using alloc directory C:\temp\nomad\alloc
    2016/08/09 11:51:03 [WARN] raft: EnableSingleNode disabled, and no known peers. Aborting election.
    2016/08/09 11:51:12.250924 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:12.287522 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:12.300424 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:12.322406 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:12.345313 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:12.354360 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:12.398743 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:12.629913 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:14.197089 [ERR] client: failed to register node: No cluster leader
    2016/08/09 11:51:19.337570 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:19.341996 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:19.354955 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:19.361599 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:19.392087 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:19.428262 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:19.552474 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:19.906441 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:32.430623 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:32.456546 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:32.467901 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:32.486420 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:32.540593 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:32.574183 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:32.610666 [ERR] worker: failed to dequeue evaluation: No cluster leader
    2016/08/09 11:51:33.003465 [ERR] worker: failed to dequeue evaluation: No cluster leader

`

**Comment by dadgar** [comment] 2016-08-09 17:10
Thanks for reporting. I think what is happening is that the client is deregistering the server services since it has a reconcile loop. Should be an easy enough fix

**Comment by dadgar** [comment] 2016-08-09 19:26
This commit makes it slightly better: 08628fea9058aeff80f9320cd350453a048f6153

But this is actually not a bug but a configuration problem. You need to set the bootstrap expect since the server is looking for more peers and is not finding any.

**Comment by kaskavalci** [comment] 2016-10-04 11:31
We experienced the same issue on AWS cluster after restart where we run nomad clients and servers as separate processes on each node. Nomad v0.4.0 and Nomad v0.4.1 has this problem.

Server Config:
```
{
  "consul":{
    "address":"localhost:8500"
  },
  "leave_on_terminate":true,
  "bind_addr":"0.0.0.0",
  "advertise":{
    "serf":"10.0.0.169:4648",
    "rpc":"10.0.0.169:4647",
    "http":"10.0.0.169:4646"
  },
  "server":{
    "retry_interval":"5s",
    "enabled":true,
    "bootstrap_expect":2
  },
  "name":"manager.cluster",
  "data_dir":"/tmp/server",
  "leave_on_interrupt":true,
  "ports":{
    "serf":4648,
    "rpc":4647,
    "http":4646
  },
  "disable_update_check":true,
  "enable_syslog":true
}
```

Client config:
```
{
  "enable_syslog":true,
  "leave_on_terminate":true,
  "bind_addr":"0.0.0.0",
  "advertise":{
    "http":"10.0.0.126:5646"
  },
  "leave_on_interrupt":true,
  "data_dir":"/tpm/client",
  "name":"master.cluster",
  "ports":{
    "http":5646
  },
  "client":{
    "enabled":true,
    "options":{
      "driver.raw_exec.enable":"1"
    }
  },
  "disable_update_check":true,
  "consul":{
    "address":"localhost:8500"
  }
}
```

Server 1 log:
```
Oct  4 05:01:54 manager nomad[29273]: raft: Node at 10.0.0.169:4647 [Follower] entering Follower state (Leader: "")
Oct  4 05:01:54 manager nomad[29273]: serf: Ignoring previous leave in snapshot
Oct  4 05:01:54 manager nomad[29273]: serf: EventMemberJoin: manager.cluster.global 10.0.0.169
Oct  4 05:01:54 manager nomad[29273]: nomad: starting 8 scheduling worker(s) for [service batch system _core]
Oct  4 05:01:54 manager nomad[29273]: serf: Attempting re-join to previously known node: master.cluster.global: 10.0.0.126:4648
Oct  4 05:01:54 manager nomad[29273]: nomad: adding server manager.cluster.global (Addr: 10.0.0.169:4647) (DC: dc1)
Oct  4 05:01:54 manager nomad[29273]: serf: Failed to re-join any previously known node
Oct  4 05:01:55 manager nomad[29273]: serf: EventMemberJoin: master.cluster.global 10.0.0.126
Oct  4 05:01:55 manager nomad[29273]: nomad: adding server master.cluster.global (Addr: 10.0.0.126:4647) (DC: dc1)
Oct  4 05:01:56 manager nomad[29273]: raft: EnableSingleNode disabled, and no known peers. Aborting election.
Oct  4 05:01:57 manager nomad[29273]: http: Request /v1/status/peers, error: No cluster leader
```

Server 2 log:
```
Oct  4 05:01:55 master nomad[17165]: raft: Node at 10.0.0.126:4647 [Follower] entering Follower state (Leader: "")
Oct  4 05:01:55 master nomad[17165]: serf: Ignoring previous leave in snapshot
Oct  4 05:01:55 master nomad[17165]: serf: EventMemberJoin: master.cluster.global 10.0.0.126
Oct  4 05:01:55 master nomad[17165]: nomad: starting 8 scheduling worker(s) for [service batch system _core]
Oct  4 05:01:55 master nomad[17165]: serf: Failed to re-join any previously known node
Oct  4 05:01:55 master nomad[17165]: nomad: adding server master.cluster.global (Addr: 10.0.0.126:4647) (DC: dc1)
Oct  4 05:01:55 master nomad[17165]: serf: EventMemberJoin: manager.cluster.global 10.0.0.169
Oct  4 05:01:55 master nomad[17165]: server.consul: successfully contacted 1 Nomad Servers
Oct  4 05:01:55 master nomad[17165]: nomad: adding server manager.cluster.global (Addr: 10.0.0.169:4647) (DC: dc1)
Oct  4 05:01:56 master nomad[17165]: raft: EnableSingleNode disabled, and no known peers. Aborting election.
Oct  4 05:02:00 master nomad[17165]: server.consul: successfully contacted 1 Nomad Servers
Oct  4 05:02:01 master nomad[17165]: http: Request /v1/status/peers, error: No cluster leader
```

**Comment by dadgar** [comment] 2016-10-04 17:40
@kaskavalci What do you mean after restart? Took down the whole cluster and brought it back up?

**Comment by kaskavalci** [comment] 2016-10-04 18:09
@dadgar yes after full restart. Is it not supported?

**Comment by kaskavalci** [comment] 2016-10-05 18:01
I noticed `peers.json` in each server only contain their own IP address. After talk with @dadgar it is because of setting `"leave_on_terminate":true`. However when servers are up, they cannot perform leader election because of incomplete `peers.json`.

**Comment by dadgar** [comment] 2016-10-06 16:47
@kaskavalci Leave on terminate is useful if you are rolling the server machines, if your normal behavior is to restart Nomad then it may be better to unset that.

Are you using Consul as well for discovery of servers?

**Comment by dadgar** [comment] 2016-10-06 16:52
@kaskavalci rejoin_after_leave may also help

**Comment by kaskavalci** [comment] 2016-10-06 17:56
@dadgar Yes we use Consul for server discovery as well. The reason we set this is to have clean node list when a nomad agent goes down. But apparently it does more harm than good :) We unset it right now and since peers.json is not modified, leader selection is performed without an issue. 

However I missed `rejoin_after_leave` parameter. I guess it makes sense, since servers leave the cluster before terminating, they will not join again if that is not provided. Maybe it's a good idea to set this at all times to ensure cluster availability?

**Comment by dadgar** [comment] 2016-10-06 18:01
@kaskavalci It really depends on how you are managing Nomad. If you don't have leave_on_terminate set you get that behavior by default.

I am going to close this as the original issue is fixed and this was a config problem.

**Closed by dadgar** 2016-10-06 18:01 UTC
Labels: bug, discovery, needs_investigation
