### ISSUE TITLE
nil pointer crash due to template change_mode script processing (1.8.3+)

### ISSUE THREAD

**Issue by ygersie** [hashicorp/nomad#24051] opened 2024-09-24 07:48 UTC
We've just upgraded from Nomad 1.8.2 to 1.8.4 and a lot of our nodes are now in a crash loop due to the following nil pointer:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c8c1b7]

goroutine 9215 [running]:
github.com/hashicorp/nomad/client/allocrunner/taskrunner.(*DriverHandle).Exec(0x0, 0xdf8475800, {0xc001545240, 0x1d}, {0xc001553f50, 0x1, 0xc0048a8480?})
	github.com/hashicorp/nomad/client/allocrunner/taskrunner/driver_handle.go:70 +0xf7
github.com/hashicorp/nomad/client/allocrunner/taskrunner/template.(*TaskTemplateManager).processScript(0xc002a65950, 0xc0013eb300, 0xc0026dca20?)
	github.com/hashicorp/nomad/client/allocrunner/taskrunner/template/template.go:597 +0x104
created by github.com/hashicorp/nomad/client/allocrunner/taskrunner/template.(*TaskTemplateManager).handleChangeModeScript in goroutine 3975
	github.com/hashicorp/nomad/client/allocrunner/taskrunner/template/template.go:563 +0x47
```

**Comment by ygersie** [comment] 2024-09-24 07:53
This looks to be related to the triggering of change_mode=script templates on client restarts that was introduced in 1.8.3 here: https://github.com/hashicorp/nomad/issues/24051

**Comment by jrasell** [comment] 2024-09-24 10:06
Hi @ygersie and thanks for raising this issue and finding a probable change which is associated to this. I'll mark this for roadmapping and get this looked into.

**Comment by tgross** [comment] 2024-09-24 13:07
Hi @ygersie! This was supposed to have been fixed in Nomad 1.8.4 by https://github.com/hashicorp/nomad/pull/23917 (which is missing from the changelog :facepalm: but I can see it's in the release tag here: https://github.com/hashicorp/nomad/commit/529b3d0d85b34dc9be280b75918f05e4e0464e36).


But I'm looking at the stack trace you have and it looks to me like it's from Nomad 1.8.3 and not Nomad 1.8.4. Compare the [`template.go#L595` from 1.8.3](https://github.com/hashicorp/nomad/blob/release/1.8.3/client/allocrunner/taskrunner/template/template.go#L595) to [`template.go#L595` from 1.8.4](https://github.com/hashicorp/nomad/blob/release/1.8.4/client/allocrunner/taskrunner/template/template.go#L595). That line in 1.8.4 is two lines above where the crash should be occurring. Are you sure you've upgraded completely to 1.8.4?

**Comment by ygersie** [comment] 2024-09-24 13:19
Hey @tgross thanks for the quick response. Yeah I'm positive this is from the 1.8.4 release binary we have. It's the 1.8.4 enterprise musl build as reported by nomad itself. The lines in the trace point to the following code in 1.8.4: https://github.com/hashicorp/nomad/blob/release/1.8.4/client/allocrunner/taskrunner/template/template.go#L597 Not line **595**

**Comment by tgross** [comment] 2024-09-24 13:23
> Hey @tgross thanks for the quick response. 

Apparently too quick, as you're right I got the wrong line number there. I'll dig in further and follow-up once I know more.

**Comment by tgross** [comment] 2024-09-24 14:34
Ok, I've got a reliable and minimal reproduction at this point.

While running a client and server separately, create a Nomad Variable:

```sh
nomad var put -force nomad/jobs/example name=Tim
```

Run a job that consumes that Variable:

<details><summary>jobspec</summary>

```hcl
job "example" {

  group "web" {

    task "http" {

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-vv", "-f", "-p", "8001", "-h", "/local"]
      }

      template {
        data        = <<EOT
{{- with nomadVar "nomad/jobs/example" -}}
FOO = {{ .name }}
{{ end -}}

        EOT

        destination = "local/test.txt"
        change_mode = "script"
        change_script {
          command = "/bin/sh"
          args = ["-c", "echo ok"]
        }
      }

      resources {
        cpu    = 100
        memory = 100
      }
    }
  }

}
```

</details>

Stop the client with the allocation still running. Then update the Variable:

```sh
$ nomad var put -force nomad/jobs/example name=Yorick
```

Restart the client:

```
    2024-09-24T10:28:20.087-0400 [DEBUG] agent: (runner) receiving dependency nomad.var.block(nomad/jobs/example@default.global)
    2024-09-24T10:28:20.087-0400 [DEBUG] agent: (runner) initiating run
    2024-09-24T10:28:20.087-0400 [DEBUG] agent: (runner) checking template 99264c04aea457a2a707ad264732193f
    2024-09-24T10:28:20.087-0400 [DEBUG] agent: (runner) rendering "(dynamic)" => "/run/nomad/client/data/alloc/e5b1ce00-1c9a-39f8-7f98-a513aa745253/http/local/test.txt"
    2024-09-24T10:28:20.096-0400 [INFO]  agent: (runner) rendered "(dynamic)" => "/run/nomad/client/data/alloc/e5b1ce00-1c9a-39f8-7f98-a513aa745253/http/local/test.txt"
    2024-09-24T10:28:20.096-0400 [DEBUG] agent: (runner) diffing and updating dependencies
    2024-09-24T10:28:20.096-0400 [DEBUG] agent: (runner) nomad.var.block(nomad/jobs/example@default.global) is still needed
    2024-09-24T10:28:20.096-0400 [DEBUG] agent: (runner) watching 1 dependencies
    2024-09-24T10:28:20.096-0400 [DEBUG] agent: (runner) all templates rendered
    2024-09-24T10:28:20.096-0400 [DEBUG] agent: (runner) enabling global quiescence for "99264c04aea457a2a707ad264732193f"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17a6f57]

goroutine 632 [running]:
github.com/hashicorp/nomad/client/allocrunner/taskrunner.(*DriverHandle).Exec(0x0, 0x12a05f200, {0xc0005f19c9, 0x7}, {0xc000d23020, 0x2, 0x2de9301?})
        github.com/hashicorp/nomad/client/allocrunner/taskrunner/driver_handle.go:70 +0xf7
github.com/hashicorp/nomad/client/allocrunner/taskrunner/template.(*TaskTemplateManager).processScript(0xc0009f4aa0, 0xc001316c80, 0xc001280b60?)
        github.com/hashicorp/nomad/client/allocrunner/taskrunner/template/template.go:597 +0xf8
created by github.com/hashicorp/nomad/client/allocrunner/taskrunner/template.(*TaskTemplateManager).handleChangeModeScript in goroutine 626
        github.com/hashicorp/nomad/client/allocrunner/taskrunner/template/template.go:563 +0x47
```

That'll make this a lot easier to track down what we missed in #23917.

**Comment by tgross** [comment] 2024-09-24 15:27
My draft PR is here https://github.com/hashicorp/nomad/pull/24057 but I think this causes a regression in https://github.com/hashicorp/nomad/pull/23663 so I'm trying to debug that now.

**Comment by ygersie** [comment] 2024-09-24 15:56
Really appreciate you jumping on this @tgross! Yes, that is really an unfortunate and subtle bug. Not sure if it would be better to handle this in the `SetDriverHandle` method though? Also uncertain if this warrants some doc update or advisory regarding this version to prevent others from running into the same problem.

**Comment by tgross** [comment] 2024-09-24 16:19
> Not sure if it would be better to handle this in the `SetDriverHandle` method though? 

Yeah the whole approach we have here for injecting the "script executor" into the template manager needs a bit of rework, as it turns out, because we're doing these nil checks in several places and it's wrong to do that everywhere. _Plus_ the change script is now not firing on client restart at all. What we should be doing is queueing-up the change script so that it waits until the task handle has been restored. Working thru that now.

> Also uncertain if this warrants some doc update or advisory regarding this version to prevent others from running into the same problem.

Good call. I'm going to pin this issue for now and we'll get this added to upgrade guide notes.

**Comment by tgross** [comment] 2024-09-24 19:55
Ok, PR is up for review. After a mess of debugging I realized we already had this class of problem prior to introducing `change_mode = "script"` and it was solved with existing infra we'd neglected to use when we implemented the new feature. So we'll now be using that existing battled-hardened infra and that should finally put this one to bed. I've tested end-to-end and it's looking good.

**Closed** 2024-09-25 12:59 UTC
Labels: type/bug, theme/client, theme/template, stage/accepted, hcc/jira

**Comment by tgross** [comment] 2024-09-25 14:33
This will ship in the real-soon-now Nomad 1.9.0-beta, with backports to Nomad Enterprise shipping soon thereafter.
