### ISSUE TITLE
`verbose_oidc_logging` for Nomad

### ISSUE THREAD

**Issue by alexiri** [hashicorp/nomad#24332] opened 2024-10-30 09:31 UTC
### Proposal

Implement an `verbose_oidc_logging` option for Nomad, similar to the one in Vault.

### Use-cases

While trying to configure OIDC SSO access to Nomad, I got several different errors, such as:

```
[ERROR] http: request failed: method=GET path=/v1/acl/token/self error="rpc error: acl token lookup failed: missing secret id" code=500
```
or
```
no role or policy bindings matched
```

However, there's no way to figure out what the problem is because there are no clues in the logs. It would be great to be able to enable extra debug logging to be able to figure out how to configure this correctly.

**Comment by jrasell** [comment] 2024-10-30 09:39
Hi @alexiri and thanks for raising this issue. I believe this is a duplicate of https://github.com/hashicorp/nomad/issues/16360, therefore I will close this issue in favour of that with the linking. Please feel free to reopen this issue if you do not believe that to be correct.

**Closed by jrasell** 2024-10-30 09:39 UTC
Labels: type/enhancement, stage/duplicate
