### ISSUE TITLE
Topology hostname label disappear

### ISSUE THREAD

**Issue by k0wl0n** [hashicorp/nomad#14330] opened 2022-08-26 04:27 UTC
### Nomad version
Output from `v1.2.0`

### Operating system and Environment details
amazon-linux

### Issue
Topology hostname label disappear

#### Expected Result
the topology hostname label is showing
![alt text](https://i.imgur.com/0hbjS1N.png)

#### Actual Result
Topology hostname label disappear
![alt text](https://i.imgur.com/rp1taX4.png)

**Comment by tgross** [comment] 2022-08-26 13:46
@k0wl0n it looks from your screenshot that you've narrowed the window quite a bit, and when the window narrows past a certain point the name is no longer visible? Is that correct?

If so, I can't reproduce that behavior on Chrome 104.0.5112.101. Which browser are you using? In any case, I'll flag this for the web UI folks.

**Comment by philrenaud** [comment] 2022-12-14 16:54
We've been unable to reproduce this; closing the ticket with this in mind.

**Closed by philrenaud** 2022-12-14 16:54 UTC
Labels: type/bug, theme/ui
