### ISSUE TITLE
restore "datacenter" dropdown filter to jobs page

### ISSUE THREAD

**Issue by thetoothpick** [hashicorp/nomad#23500] opened 2024-07-03 19:00 UTC
Hello!

### Proposal

With the Nomad 1.8 release, the "datacenter" dropdown filter was removed from the Jobs page.  Can that be added back?  We used this filter quite heavily, most of our jobs are logically segmented by datacenter.

### Use-cases

Quickly filter by datacenter instead of typing a filter each time.

### Attempted Solutions

Can use the `"name" in Datacenters` filter in the new search box, but this is far less convenient.

Thanks!
Kevin

**Comment by tgross** [comment] 2024-07-03 19:32
Duplicate of https://github.com/hashicorp/nomad/issues/23446. We've decided not to do this.

**Closed by tgross** 2024-07-03 19:32 UTC
Labels: type/enhancement
