### ISSUE TITLE
Fingerprinting with remote Docker endpoint reports local resources

### ISSUE THREAD

**Issue by rchrd** [hashicorp/nomad#566] opened 2015-12-11 13:04 UTC
### Use Case
I would like to use Nomad on Triton; connecting Nomad to the remote Docker endpoint of Triton would make the entire datacenter available in Nomad.

### Issue
Nomad reports resources of the instance where Nomad is running.

### How to reproduce
This issue can be reproduced with Docker Machine (Boot2Docker) on OSX.

1. Create a VM with Docker Machine
2. Set the Docker environment variables (DOCKER_HOST, DOCKER_TLS_VERIFY, DOCKER_CERT_PATH)
3. Start Nomad in Dev mode
4. Query the node info via the Nomad HTTP API (http://127.0.0.1:4646/v1/node/<node id>)

The resources of the OSX host are reported instead of the remote Docker host.

**Comment by cbednarski** [comment] 2015-12-11 20:50
Thanks for the report. This is currently expected behavior.

In order to accommodate this you need a custom fingerprinter which can query the Titan API to get stats for the remote host. We'd like to support a plugin system that would allow you to replace the built-in fingerprint's default behavior to query the API instead of using the local system's resource.

In the mean time if you want this to work you will need to make a custom build which replaces behavior found in the following files with Titan API calls:

- https://github.com/hashicorp/nomad/blob/master/client/fingerprint/cpu.go
- https://github.com/hashicorp/nomad/blob/master/client/fingerprint/host.go
- https://github.com/hashicorp/nomad/blob/master/client/fingerprint/memory.go
- https://github.com/hashicorp/nomad/blob/master/client/fingerprint/network.go
- https://github.com/hashicorp/nomad/blob/master/client/fingerprint/storage.go

You should be able to write one fingerprinter to do this and by adding it to https://github.com/hashicorp/nomad/blob/master/client/fingerprint/fingerprint.go#L31-L41 you can get it to run and replace the information reported by the other built-in fingerprinters.

**Comment by arminc** [comment] 2015-12-13 11:55
Maybe I am wrong but currently you are supposed to run the nomad client on the machine you want to use as a node. You can cheat when using Docker because you can specify a remote Docker host, basically what @rchrd is doing.

By doing this you will need to ‘restrict’ nomad node to just accept docker jobs? Because if you want to run a different job that is not a docker one, it could get scheduled to the Triton machine while it will end up where ever the nomad node is running.

**Comment by dadgar** [comment] 2015-12-22 18:25
Going to close this as it is desired behavior for Nomad to fingerprint the host.

**Closed by dadgar** 2015-12-22 18:25 UTC
Labels: core, enhancement
