### ISSUE TITLE
Unhealthy Task restarted endlessly when restart_policy set to "fail"

### ISSUE THREAD

**Issue by djenriquez** [hashicorp/nomad#19875] opened 2024-02-05 20:40 UTC
### Nomad version
Nomad v1.6.1
BuildDate 2023-07-21T13:49:42Z
Revision 515895c7690cdc72278018dc5dc58aca41204ccc

### Operating system and Environment details
Amazon Linux 2

### Issue
We have a job running a task where the Nomad UI reports that it is sending a restart signal because of a failed health check, but the health check is configured with `"RestartPolicy.Mode": "fail"`. Not sure why, but it has been trying to constantly send a restart signal when it should be rescheduling the allocation.
<img width="602" alt="Screenshot 2024-02-05 at 12 29 02 PM" src="https://github.com/hashicorp/nomad/assets/4636740/f7e12fa6-4852-423a-b18f-c05d76a03826">

We do render secrets from Vault, which are configured for `"Mode": "restart"`, but the health check is whats sending the restart. So wondering if there is some bug between the restart from the Vault template re-render and the health check?

### Reproduction steps
Not quite sure how to reproduce, thousands of jobs running and this is the first time we've seen this.

#### Expected Result
When healthcheck fails for a job spec configured with `"RestartPolicy.Mode": "fail"`, reschedule the allocation.

#### Actual Result
When healthcheck failing for a task and a "restart signal" is sent over and over.

### Job file (if appropriate)
Can send over if needed, contains somewhat sensitive information pertaining to our org, but fundamentally, 1 taskgroup with 3 tasks, each task is configured with:
`RestartPolicy`:
```json
      "RestartPolicy": {
        "Attempts": 0,
        "Interval": 180000000000,
        "Delay": 1000000000,
        "Mode": "fail",
        "RenderTemplates": false
      }
```
and task group:
`ReschedulePolicy`:
```json
"ReschedulePolicy": {
        "Attempts": 0,
        "Interval": 0,
        "Delay": 15000000000,
        "DelayFunction": "exponential",
        "MaxDelay": 300000000000,
        "Unlimited": true
      }
```

Finally a Vault template config that looks like:
```json
          "Vault": {
            "Policies": [
              "<REDACTED>"
            ],
            "Namespace": "",
            "Env": true,
            "DisableFile": false,
            "ChangeMode": "restart",
            "ChangeSignal": "SIGHUP"
          },
          "Templates": [
            {
              "SourcePath": "",
              "DestPath": "secrets/rendered.env",
              "EmbeddedTmpl": "<REDACTED>",
              "ChangeMode": "restart",
              "ChangeSignal": "",
              "ChangeScript": null,
              "Splay": 5000000000,
              "Perms": "0644",
              "Uid": null,
              "Gid": null,
              "LeftDelim": "{{",
              "RightDelim": "}}",
              "Envvars": true,
              "VaultGrace": 0,
              "Wait": null,
              "ErrMissingKey": false
            },
```

**Comment by djenriquez** [comment] 2024-02-05 20:44
Just found this bug on another job where the task started to fail at the same time as the original job in the post. Same situation, same configuration, should have rescheduled, but proceeded to endlessly send restart signals.

**Comment by lgfa29** [comment] 2024-02-07 02:02
Hi @djenriquez 👋 

The `restart` block is only applied when the task fails. From the [docs](https://developer.hashicorp.com/nomad/docs/job-specification/restart):
> The `restart` block configures a task's behavior on task failure. Restarts happen on the client that is running the task.

So, in this case, it doesn't seem like the task technically failed because it didn't exit, but it did fail its health check, which causes Nomad to restart it:

https://github.com/hashicorp/nomad/blob/1e04fc461394d96bd4aab0e50cfa80048e1b5fd0/client/serviceregistration/watcher.go#L88-L98

Thinking through this, it may be a confusing behaviour. Were you expecting the task to be marked as `failed` (and therefore rescheduled) as soon as a health check failed?

**Comment by djenriquez** [comment] 2024-02-21 00:06
Hi @lgfa29, sorry for the late reply -- yes, thats actually what we were expecting. Since the healthcheck failed, that should trigger the restart policy right? And since the restart policy is set to `fail`, we were expecting the reschedule policy to take over.

**Comment by tgross** [comment] 2024-06-24 18:32
Hi folks! Doing a little bit of issue cleanup here. I was unable to reproduce this behavior on the current tip of `main`. I used the following job spec with a `check` and `check_restart` block, with a `restart` block that disables restarts.

<details><summary>jobspec</summary>

```hcl
job "example" {

  group "group" {

    restart {
      attempts = 0
      mode     = "fail"
    }

    network {
      mode = "bridge"
      port "www" {
        to = 8001
      }
    }

    service {
      name     = "httpd-web"
      provider = "nomad"
      port     = "www"

      check {
        type     = "http"
        path     = "/health"
        interval = "3s"
        timeout  = "1s"

        check_restart {
          limit           = 3
          grace           = "10s"
          ignore_warnings = false
        }
      }
    }

    task "task" {

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-vv", "-f", "-p", "8001", "-h", "/local"]
        ports   = ["www"]
      }

      template {
        data        = "<html>hello, world</html>"
        destination = "${NOMAD_TASK_DIR}/index.html"
      }

      resources {
        cpu    = 100
        memory = 100
      }

    }
  }

}
```

</details>

I get the expected set of task events. The restart is signaled but then the taskrunner rejects that restart because of the policy in the `restart` block:

```
Recent Events:
Time                       Type              Description
2024-06-24T14:28:22-04:00  Not Restarting    Policy allows no restarts
2024-06-24T14:28:22-04:00  Terminated        Exit Code: 137, Exit Message: "Docker container exited with non-zero exit code: 137"
2024-06-24T14:28:17-04:00  Restart Signaled  healthcheck: check "service: \"httpd-web\" check" unhealthy
2024-06-24T14:28:01-04:00  Started           Task started by client
2024-06-24T14:28:01-04:00  Task Setup        Building Task Directory
2024-06-24T14:28:01-04:00  Received          Task received by client
```

I'm going to close this out for now. If folks can reproduce with a specific jobspec, we'd be happy to revisit.

**Closed by tgross** 2024-06-24 18:32 UTC
Labels: type/bug, stage/needs-investigation, theme/service-discovery
