### ISSUE TITLE
Nomad unable to parse CLI args in a Dispatched Job

### ISSUE THREAD

**Issue by ptarpan** [hashicorp/nomad#2784] opened 2017-07-06 18:14 UTC
### Nomad version
v0.5.5

### Operating system and Environment details
Server: AWS RHEL AMI 
Worker: Windows (running internal tool) 
Client: OS X 

### Issue
Nomad unable to parse CLI args 

### Reproduction steps
- Use an existing Nomad cluster 
- Deploy a dispatched job using the job file below 

### Nomad Server logs (if appropriate)
N/A 
### Nomad Client logs (if appropriate)
- Failed to parse command line arguments.
### Job file (if appropriate)
```hcl
job "batch-test" {
    region = "us-west-2"
    datacenters = ["us-west-2"]
    type = "batch"

    constraint {
        attribute   = "${node.class}"
        value       = ""
    }

    meta {
        INPUT_PATH  = ""
        ARGS        = ""
    }

    parameterized {
        payload       = "forbidden"
        meta_required = ["INPUT_PATH"]
        # An output path where results should be written
        meta_required = ["ARGS"]
    }

    # Define a task to run
    task "t1" {
        # Run the task without resource isolation
        driver = "raw_exec"

        # Configure the task to use key/value pairs
        config {
            # System path to internally developed binary 
            command = "path_to_binary" 
            # Arguments that the binary takes 
            args    = []
        }

        # We must specify the resources required for this task to ensure it runs on a machine with
        # enough capacity
        resources {
            cpu         = 500   # 500 MHz
            memory      = 256 # 256 MB
            network {
                mbits   = 10
            }
        }
    } // END task
}
```

Note: The issue occurs when passing multiple args. A single argument works as expected. See below. 

### Request (same for both): 
```shell
curl -XPOST --data @dispatch.json http://nomad.service.dev:4646/v1/job/batch-test/dispatch
```

### Successful JSON file
```json
{
    "Meta":
    {
        "INPUT_PATH": "<path_to_file>",
        "ARGS": "-a"
    }
}
```
### Successful log: 
```
machine: .
log    : Application Log
source : <internal_tool_name>

Version: 0.6.58.1
Working on package <file_name>
Verification start time 10:11:39 AM
Running schema validation on <file_name> finished
Verification end time 10:11:41 AM. Duration 0.02 minutes.
Report saved to: <binary_output_path_arg>
Completed
```
### Failed JSON file
```json
{
    "Meta":
    {
        "INPUT_PATH": "<path_to_file>",
        "ARGS": "-a -b"
    }
}
```
### Failed log: 
```
machine: .
log    : Application Log
source : <internal_tool_name>
Failed to parse command line arguments.
```

**Comment by schmichael** [comment] 2017-07-06 21:32
The log output seems to be from the internal tool you're running. I'm not sure if this is a Nomad issue from the details you posted. Are you sure the issue isn't in how your binary is parsing `$ARGS`?

When you pass multiple arguments in a single string like that they may be treated as a single argument (`-a -b`) instead of two distinct arguments (`-a`, `-b-`). It depends on exactly what your code is doing with `$ARGS`.

I'm going to close this for now but will definitely reopen if you can provide more details.

**Closed by schmichael** 2017-07-06 21:32 UTC

**Comment by ptarpan** [comment] 2017-07-06 21:44
Just got this working. Yes @schmichael, this might be an issue with the internal tool itself. Still testing but will keep you posted.
