### ISSUE TITLE
Question client: error fetching host resource usage stats: permission denied

### ISSUE THREAD

**Issue by sigil66** [hashicorp/nomad#1680] opened 2016-09-02 08:28 UTC
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:
### Nomad version

Nomad v0.4.1
### Operating system and Environment details

Ubuntu 16.04 amd64
### Issue

While running nomad as a non root user:
client: error fetching host resource usage stats: permission denied

Looking at:
https://github.com/hashicorp/nomad/blob/97a717356aa253eda894afe81afc5c270ce2c827/client/stats/host.go#L73

I don't think any (could be wrong) of these collection actions should require root. I am guessing scheduling will not work correctly without proper host stats?
### Reproduction steps

Run nomad as non root user
### Nomad Client logs (if appropriate)

error fetching host resource usage stats: permission denied

**Comment by diptanu** [comment] 2016-09-02 17:48
Can you go through the client logs and share with us the `WARN` messages related to this?
If the client can't collect stats it writes the following log line - 
`[WARN] client: error fetching host resource usage stats` It would help me understand which file the stats collector is not able to read.

**Comment by dadgar** [comment] 2016-11-10 20:05
@sigil66 Are you still running into this?

**Comment by sigil66** [comment] 2016-11-10 20:13
@dadgar we switched to running nomad as root on worker nodes, to deal with the issue. If the issue should be fixed I can test as an unprivileged user.

**Comment by dadgar** [comment] 2016-11-10 20:52
@sigil66 I don't think we were ever able to reproduce it. I mainly wanted to see if it was still reproducible for you. If you do test would you mind trying on 0.5.0-rc2? https://releases.hashicorp.com/nomad/0.5.0-rc2/

**Comment by sigil66** [comment] 2016-11-10 20:53
@dadgar sure thing I will do so when I get a few spare cycles and will update accordingly.

**Comment by christoe** [comment] 2016-12-08 06:18
We've now started seeing this on some(!) of our hosts:

`nomad: 2016/12/08 07:16:05.780502 [WARN] client: error fetching host resource usage stats: permission denied
nomad[12155]: client: error fetching host resource usage stats: permission denied`

In our case it seems as if this started appearing after upgrading to 0.5.0. I'm currently trying to chase down what differences there might be between the hosts that may be causing this.

**Comment by christoe** [comment] 2016-12-08 07:05
After some digging, strace gave me the answer (at least to my cause):

`28666 statfs("/var/lib/<mounted_partition>", 0xc4205b0af8) = -1 EACCES (Permission denied)`

Turns out the disk library used by Nomad to determine disk usage gets all mounted filesystems from /etc/mtab. However, not all of those filesystems are allowed to be stat:ed by a non-root user - which causes the permission denied error.

**Comment by diptanu** [comment] 2016-12-08 22:30
@sigil66 I am of the opinion that we close this ticket since reading `/etc/mtab` is the most reliable way to get the disk information out, which is what tools like `df` use as well. Do you have any opinions/thoughts?

**Comment by christoe** [comment] 2016-12-09 12:06
@diptanu However (correct me if I'm wrong) after looking at the code it seems as if Collect() returns as soon as Usage() returns an error. Shouldn't the code be more resilient - i.e. continue to warn about the failed stat, but collect data from the partitions the user actually have permission to read?

**Comment by dadgar** [comment] 2016-12-12 17:50
@christoe I agree, could you file an issue with that project and cross link the issues?

**Comment by christoe** [comment] 2016-12-13 11:33
@dadgar: I think this should be fixed in Nomad. See reference PR #2090.

**Comment by dadgar** [comment] 2016-12-13 23:19
Closed via #2090

**Comment by dadgar** [comment] 2016-12-13 23:19
Thanks!

**Closed by dadgar** 2016-12-13 23:19 UTC
Labels: needs_investigation, waiting-reply
