### ISSUE TITLE
Add volumes for docker driver

### ISSUE THREAD

**Issue by farcaller** [hashicorp/nomad#630] opened 2015-12-24 10:52 UTC
Based on https://github.com/hashicorp/nomad/issues/62, I have an actual use case for proper volumes support, specifically I want to run nomad jobs that are backed by docker ceph volume plugin. I'm not sure if nomad should actually manage those in some way (as k8s does), for my use case it would be enough if I just was able to utilize docker's volume infrastructure in jobs.

**Comment by dadgar** [comment] 2016-01-04 18:02
Closing as this is a duplicate of #150

**Closed by dadgar** 2016-01-04 18:02 UTC
