### ISSUE TITLE
[template] temporary Consul cluster leader loss caused permanent job failure

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#2788] opened 2017-07-06 20:29 UTC
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `v0.5.6`

### Issue

`consul-template: health.service(seatgeek|passing): Unexpected response code: 500 (No cluster leader)`

I would have expected nomad to continue to start the job until Consul was back in a good available state, rather than giving up permanently on the job.

### Reproduction steps

Start job with template depending on Consul services, temporary kill the cluster leaders

**Comment by dadgar** [comment] 2017-07-06 20:30
Duplicate of https://github.com/hashicorp/nomad/issues/2623

**Comment by jippi** [comment] 2017-07-06 20:31
ha, thanks @dadgar - i looked for that issue and couldn't find it - thought I had dreamt it up

**Closed by dadgar** 2017-07-06 20:30 UTC
