### ISSUE TITLE
Functions are skipped for meta inputs of parameterized jobs

### ISSUE THREAD

**Issue by bew** [hashicorp/nomad#14613] opened 2022-09-16 21:50 UTC
### Nomad version
Output from `Nomad v1.3.5`

### Operating system and Environment details

OS: ArchLinux

Nomad installed through Nix package manager.

### Reproduction steps

1. Run `nomad agent -dev`
2. Submit job (see job file at end of issue), job registration is successful
3. Run `nomad job dispatch   -meta input=foo/bar.txt   bug-function-param-job`
4. Check the logs of the dispatched job execution

#### Expected Result

Logs should show: `foo/bar.txt --- bar.txt`

#### Actual Result

Job dispatch shows:
```
Dispatched Job ID = bug-function-param-job/dispatch-1663363793-8fce4cc8
Evaluation ID     = f88bba62

==> 2022-09-16T23:29:53+02:00: Monitoring evaluation "f88bba62"
    2022-09-16T23:29:53+02:00: Evaluation triggered by job "bug-function-param-job/dispatch-1663363793-8fce4cc8"
    2022-09-16T23:29:53+02:00: Allocation "fcbacc8a" created: node "a0887f7c", group "main"
    2022-09-16T23:29:54+02:00: Allocation "fcbacc8a" status changed: "pending" -> "complete" (All tasks have completed)
    2022-09-16T23:29:54+02:00: Evaluation status changed: "pending" -> "complete"
==> 2022-09-16T23:29:54+02:00: Evaluation "f88bba62" finished with status "complete"
```

And final dispatched job logs show: `foo/bar.txt --- foo/bar.txt`
And no error / warning on dispatch.

#### Speculation

I see in the functions doc, it says:
> HCL functions are executed on job submission

Which seems fine to me as I'm thinking that the function would be evaluated on the dispatch job submission (not on the parent job submission, which I assume is happening here).
When the dispatch job is submitted, we have all input variables fully known AFAIK, calling a function should be possible.

If this is absolutely not possible, it should at least give a warning on evaluation, saying that a function was skipped or something like that.

### Job file
```hcl
job "bug-function-param-job" {
  datacenters = ["dc1"] # required
  type = "batch" # required for parameterized jobs

  parameterized {
    meta_required = ["input"]
  }

  task "main" {
    driver = "raw_exec"

    config {
      command = "sh"
      args = ["-c", "echo ${NOMAD_META_input} --- ${basename(NOMAD_META_input)}"]
    }
  }
}
```

**Comment by lgfa29** [comment] 2022-09-19 20:37
Hi @bew 👋 

This is actually the expected result. As you pointed out HCL functions are evaluated at job submission, which happens when you run `nomad job run`. After this, the job is stored as JSON and HCL is not involved anymore.

When you run `nomad job dispatch`, Nomad will use the stored JSON representation to create the child job, so it doesn't have any HCL function to run. You can see this when you pull the job definition either from API or the UI:
<img width="917" alt="image" src="https://user-images.githubusercontent.com/775380/191111342-aca450c3-9796-4008-a601-4fdd961c3245.png">

In addition to this, `NOMAD_META_*` are environment variables, so they are only available at runtime. You will need to call a system-level function to process that variable when the task runs, like [`basename`](https://man7.org/linux/man-pages/man3/basename.3.html) on Linux.

I hope this helps clarify the difference. I'm going to close this since it's working as intended, but feel free to ask more questions if it's not clear 🙂

**Closed by lgfa29** 2022-09-19 20:37 UTC
Labels: type/bug

**Comment by bew** [comment] 2022-09-19 21:15
For me, in the case of `basename` at least, it can usually be implemented as a pure function, just looking at the input, returning `.` for a path given without parents.

What happens on the call to the basename hcl function then?
If it's just bypassed, would it be possible to have a warning on job submission? (as I don't think there is a reasonable case where this is an ok thing)

**Comment by lgfa29** [comment] 2022-09-19 21:54
> Also, what happens on the call to the basename hcl function then?

It returns just `NOMAD_META_input` since there's no path to break into `dirname` and `basename`. That's why the final JSON has `--- ${NOMAD_META_input}` 🙂

**Comment by bew** [comment] 2022-09-19 22:18
Did you already considered adding a warning when passing a `NOMAD_META_` to an hcl function? or more generally when giving any reference to a thing that is currently unknown / that cannot be resolved to a value?

Or has this been discussed already?

**Comment by lgfa29** [comment] 2022-09-22 20:49
When the job registration happen Nomad needs to be completely agnostic as to which values are passed to functions. `NOMAD_META_` is not correct in your case, but it could in others, so we can't make that kind of validation.
