### ISSUE TITLE
Pending allocations in nomad 0.11, unable to process periodic tasks

### ISSUE THREAD

**Issue by gerardstanczak** [hashicorp/nomad#7787] opened 2020-04-23 10:27 UTC
### Nomad version
Nomad v0.11.0 (5f8fe0afc894d254e4d3baaeaee1c7a70a44fdc6)

### Operating system and Environment details
Centos 7 AWS
Linux 3.10.0-1062.el7.x86_64
glibc-2.17-292.el7.x86_64

### Issue
Some nomad clients randomly stop processing new allocations and mark them all as Pending. The agent is unable to process any new jobs and tasks, basically the processing stops completely for any new periodic tasks. Allocations stay in pending forever, while resource usage is low and there is plenty of CPU/memory to allocate on the host. No errors or warnings visible in nomad agent log. 

Only restarting the nomad agent process helps and allocations start to run and tasks are executed

```
[10:16:31] [root@batch.165181.dev5 ~]# nomad node status adc015a | grep pending
5d0e5bf4  adc015ad  callbacks                                 0        run      pending  1h30m ago   1h30m ago
[tens of other pending jobs, all with approximatelly the same timestamp of creation/modificaiton]
```

Whats strange is nomad alloc status returns 404 on this one, but returns other data correctly
```
ID                  = 5d0e5bf4-862c-76cc-5741-36c58c5ef2eb
Eval ID             = 525f64fe
Name                = callbacks_hour/periodic-1587600000.callbacks[0]
Node ID             = adc015ad
Node Name           = myhost.mydomain.com
Job ID              = callbacks_hour/periodic-1587600000
Job Version         = 0
Client Status       = pending
Client Description  = <none>
Desired Status      = run
Desired Description = <none>
Created             = 1h33m ago
Modified            = 1h33m ago

Couldn't retrieve stats: Unexpected response code: 404 (rpc error: Unknown allocation "5d0e5bf4-862c-76cc-5741-36c58c5ef2eb")
```

Restarting or signaling also fails 

```
[10:24:57] [root@batch.165181.dev5 ~]# nomad alloc restart 5d0e5bf4
Failed to restart allocation:
Unexpected response code: 404 (rpc error: Unknown allocation "5d0e5bf4-862c-76cc-5741-36c58c5ef2eb")

[10:28:00] [root@batch.165181.dev5 ~]# nomad alloc signal 5d0e5bf4
Error signalling allocation: Unexpected response code: 500 (rpc error: No path to region)
```

Stopping seems to run fine but running status later shows its still in pending state
```

[10:28:16] [root@batch.165181.dev5 ~]# nomad alloc stop 5d0e5bf4
==> Monitoring evaluation "56d8b7da"
    Evaluation triggered by job "callbacks_hour/periodic-1587600000"
    Allocation "34a2ce58" created: node "adc015ad", group "callbacks"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "56d8b7da" finished with status "complete"
[10:28:23] [root@batch.165181.dev5 ~]# nomad alloc status 5d0e5bf4
ID                   = 5d0e5bf4-862c-76cc-5741-36c58c5ef2eb
Eval ID              = 525f64fe
Name                 = callbacks_hour/periodic-1587600000.callbacks[0]
Node ID              = adc015ad
Node Name            = myhost.mydomain.com
Job ID               = callbacks_hour/periodic-1587600000
Job Version          = 0
Client Status        = pending
Client Description   = <none>
Desired Status       = stop
Desired Description  = alloc is being migrated
Created              = 1h37m ago
Modified             = 10s ago
Replacement Alloc ID = 34a2ce58

Couldn't retrieve stats: Unexpected response code: 404 (rpc error: Unknown allocation "5d0e5bf4-862c-76cc-5741-36c58c5ef2eb")
```

### Reproduction steps
Issue seems random, with no pattern or predictable behaviour. Works stable on most of the clusters, only on some it randomly disables one client from functioning. We have 80+ periodic and 30+ service raw_exec jobs loaded into nomad cluster and from 2 to 8 nomad agents executing them. Happens on production (3 nodes in cluster) and dev clusters (1 node)

**Comment by notnoop** [comment] 2020-04-25 19:05
Thanks @gdsjerry for raising it.  This is very concerning indeed. I would love more info so I can reproduce and investigate this.

Can you share the job files that trigger this condition?  How long does it take to hit the condition?  I'm having a hard time reproducing this with my simple sleep periodic jobs.

Also, would you be able to submit the goroutine stacks while the allocation is pending?  When running as dev, you can see it through http://localhost:4646/debug/pprof/goroutine?debug=1 .  If running as a non-dev agent, you can also get it by running `kill -ABRT <nomad-pid>`.

Having the goroutine stack while the allocation is pending should significantly speed up the fix.  Thank you!

**Comment by gdsjerry** [comment] 2020-04-27 15:12
@notnoop its difficult to say which job specifically triggers this condition, as we have many (all raw_exec) very simmilar to each other + few docker services. The symptom is that all new allocations get stuck, no matter what periodic/service it is, and also it occurs very randomly. On ~20 clusters we have one random fails every few days, at different parts of the day.

If that helps, our logs are also full of those errors https://github.com/hashicorp/nomad/issues/7776 
We also observe memory leaking from the nomad agent - after some time the nomad process occupies all memory and is killed by OOM.  The memory usage inceases linearly over time. https://dl.dropboxusercontent.com/s/kbbklckubsxl1f0/r8Z5Eb6yJ6.png

We upgraded to recently released 0.11.1 and there is still same problem.

I will wait for next node to stop processing allocations and submit the debug info you requested

**Comment by gdsjerry** [comment] 2020-05-05 19:56
Ok, we got same issue few more times, I collected processlist, nomad statuses, logs from messages and sent kill ABRT signal afterwards

Nomad continues to get stuck in pending state for all new allocaitons and continues to leak /tmp/plugin files, spam with grpc errors and consumes memory until OOM killer stops it. We downgraded to 0.10.5 and there is same problem, although not as much errors "/tmp/plugin<number> not found", but the files are still there, uncleaned

Attached logs from /var/log/messages are filtered out from most of the trash by following regexp (exclusions), to save space
- Unavailable desc = transport is closing
- Canceled desc = grpc: the client connection is closing
- batch su: 
- batch consul:
- batch kernel: docker0
- batch kernel: IPv6


[messages.log](https://github.com/hashicorp/nomad/files/4583293/messages.log)
[nomad_node_status.log](https://github.com/hashicorp/nomad/files/4583314/nomad_node_status.log)
[nomad_node_status_self.log](https://github.com/hashicorp/nomad/files/4583317/nomad_node_status_self.log)
[nomad_status.log](https://github.com/hashicorp/nomad/files/4583319/nomad_status.log)
[process_list_tree.log](https://github.com/hashicorp/nomad/files/4583321/process_list_tree.log)

**Comment by notnoop** [comment] 2020-05-06 18:51
Thank you @gdsjerry for the info.  That definitely helps point to few problems!

Also, can you double check the ulimit on the hosts?  I wonder if you are hitting the problems related to resources mentioned in https://github.com/hashicorp/nomad/issues/6557 .  In particular, I would check ulimit/pids_max/threads-max.  I suspect logmon is crashing while it's spinning up threads before it gets a chance to delete the files.  If you can scan how close you are to the limits and increase them, that'd be great.

here are my observations from the log:
* The `process_list_tree.log` file lists 6 executor processes but no logmon ones!  Interestingly none of them have any child processes!  That's very unexpected.
* 2 goroutines with runDriver activity - this means that at most two of the above processes are tracked by nomad and the rest probably leaked!
* 6 goroutines that are attempting to kill tasks but hanging:
```
goroutine 14078187 [select, 618 minutes]:
github.com/hashicorp/nomad/client/allocrunner/taskrunner.(*TaskRunner).Kill(0xc043c6a780, 0x3785e20, 0xc00003e040, 0xc01b348b40, 0xc01c5c0e08, 0x1)
  /opt/gopath/src/github.com/hashicorp/nomad/client/allocrunner/taskrunner/lifecycle.go:81 +0x229
github.com/hashicorp/nomad/client/allocrunner.(*allocRunner).killTasks.func1(0xc017707590, 0xc00cc8c4e0, 0xc017707560, 0xc0acf9ae70, 0xc0445e79a0, 0x20, 0xc043c6a780)
  /opt/gopath/src/github.com/hashicorp/nomad/client/allocrunner/alloc_runner.go:542 +0x13f
created by github.com/hashicorp/nomad/client/allocrunner.(*allocRunner).killTasks
  /opt/gopath/src/github.com/hashicorp/nomad/client/allocrunner/alloc_runner.go:538 +0x53c
```

* 3 goroutines are stuck waiting for the allocs to be destroyed - i wonder if each alloc has two tasks?!  Not sure how these goroutines correspond to the ones above.  Here is a sample goroutine:

```
goroutine 324 [semacquire, 618 minutes]:
sync.runtime_Semacquire(0xc06c4162b8)
  /usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc06c4162b0)
  /usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/hashicorp/nomad/client/allocrunner.(*allocRunner).killTasks(0xc000301a00, 0xc0c4555500)
  /opt/gopath/src/github.com/hashicorp/nomad/client/allocrunner/alloc_runner.go:553 +0x552
github.com/hashicorp/nomad/client/allocrunner.(*allocRunner).handleAllocUpdate(0xc000301a00, 0xc0c4555500)
  /opt/gopath/src/github.com/hashicorp/nomad/client/allocrunner/alloc_runner.go:754 +0x184
github.com/hashicorp/nomad/client/allocrunner.(*allocRunner).handleAllocUpdates(0xc000301a00)
  /opt/gopath/src/github.com/hashicorp/nomad/client/allocrunner/alloc_runner.go:722 +0x4c
created by github.com/hashicorp/nomad/client/allocrunner.(*allocRunner).Run
  /opt/gopath/src/github.com/hashicorp/nomad/client/allocrunner/alloc_runner.go:251 +0xad
```

* 1 goroutine is GCing an alloc and is stuck waiting for the alloc runner to be destroyed in

```
goroutine 14210045 [select, 552 minutes]:
github.com/hashicorp/nomad/client.(*AllocGarbageCollector).destroyAllocRunner(0xc00007fc80, 0xc026e882a0, 0x24, 0x37cf7c0, 0xc01f469a00, 0x2ffb17b, 0x11)
  /opt/gopath/src/github.com/hashicorp/nomad/client/gc.go:185 +0x29d
github.com/hashicorp/nomad/client.(*AllocGarbageCollector).Collect(0xc00007fc80, 0xc026e882a0, 0x24, 0xc075249c01)
  /opt/gopath/src/github.com/hashicorp/nomad/client/gc.go:209 +0x190
created by github.com/hashicorp/nomad/client.(*Client).removeAlloc
  /opt/gopath/src/github.com/hashicorp/nomad/client/client.go:2238 +0x36e
```

* This above goroutine is holding a GC destruction lock for a very long time (9 hours!) and blocking 15 other GC jobs from running.  Sadly, one of them is being blocked in `runAllocs()`:

```
Blocking running new allocations
goroutine 239 [select, 552 minutes]:
github.com/hashicorp/nomad/client.(*AllocGarbageCollector).destroyAllocRunner(0xc00007fc80, 0xc0704b1bc0, 0x24, 0x37cf7c0, 0xc01fb301a0, 0xc090499d40, 0x21)
  /opt/gopath/src/github.com/hashicorp/nomad/client/gc.go:177 +0x1dc
github.com/hashicorp/nomad/client.(*AllocGarbageCollector).MakeRoomFor(0xc00007fc80, 0xc04c598010, 0x1, 0x1, 0x4, 0x4)
  /opt/gopath/src/github.com/hashicorp/nomad/client/gc.go:257 +0x116
github.com/hashicorp/nomad/client.(*Client).runAllocs(0xc0002aef00, 0xc05a1ddb00)
  /opt/gopath/src/github.com/hashicorp/nomad/client/client.go:2133 +0x689
github.com/hashicorp/nomad/client.(*Client).run(0xc0002aef00)
  /opt/gopath/src/github.com/hashicorp/nomad/client/client.go:1581 +0x91
created by github.com/hashicorp/nomad/client.NewClient
  /opt/gopath/src/github.com/hashicorp/nomad/client/client.go:494 +0x1c1e
```

While `runAllocs` is blocked for the GC - the client cannot process a new allocations.

So there are few steps for us to investigate:
* Make `runAllocs` not dependant on GC or cope with long running GC periods
* Add time out to GC handling such that a single bad alloc GC doesn't halt entire alloc GC activity
* Figure out the cause of the stuck destruction goroutines and fix it!
* Figure out how a node get into this state and ensure we always cope well :( - this is going to be the hardest one

**Comment by gdsjerry** [comment] 2020-05-07 12:53
I checked the limits on the affected hosts (the client with biggest amount of allocations from all others - around 3000) and here is how they look like: 
```
[12:47:44] [root@batch.5106.prod ~]# cat /proc/sys/kernel/threads-max 
58152
[12:47:58] [root@batch.5106.prod ~]#  find /proc/*/task/ -maxdepth 1 -mindepth 1 -type d | wc -l
1665
[12:48:03] [root@batch.5106.prod ~]# ps -eLf | wc -l
1654

[12:52:02] [root@batch.5106.prod ~]# cat /proc/sys/kernel/pid_max 
32768
[12:52:22] [root@batch.5106.prod ~]# find /proc/ -maxdepth 1 -mindepth 1 -type d | wc -l
310
[12:52:36] [root@batch.5106.prod ~]# ps aux | wc -l
304
```

So if I'm counting that correctly, then it seems we are far away from that limit

Anything else we can collect or check to help investigate this issue? We need to soon rollback this version and downgrade back to 0.8.6 which was the last stable version we used, because of those stability problems.

**Comment by notnoop** [comment] 2020-05-08 10:19
@gdsjerry Thanks.  I think we have everything we can think of at this moment.  I'll implement the fix.

I'm very sorry that you are experiencing this.  I'll implement fixes for the issues I raised above and keep digging into how we can reproduce this issue.  Will keep you posted through this issue.  Thanks for your patiences.

**Comment by ultra-baba** [comment] 2020-05-18 02:40
I just encountered the same problem ...

Couldn't retrieve stats: Unexpected response code: 404 (rpc error: Unknown allocation "xxxxxxxx")

**Comment by a-zagaevskiy** [comment] 2022-05-06 13:08
Hi! Any news on that? Is it still relevant for the newest versions?

**Comment by nakabonne** [comment] 2022-10-19 06:03
Hello, any updates?

**Comment by jhyx2022** [comment] 2023-08-07 00:17
Recently we encounter this problem since upgrading to 1.6.0, and upgrading to 1.6.1 didn't resolve this issue. We started from 1.5.3 and didn't have such problem.

Is anyone from the team looking into this?

Thanks!

**Comment by aneustroev** [comment] 2024-02-21 12:03
Same issue on 1.7.4 https://github.com/hashicorp/nomad/issues/19917

**Comment by cl-bvl** [comment] 2024-02-27 16:31
Hello.
[MakeRoomFor](https://github.com/hashicorp/nomad/blob/main/client/gc.go#L237) func is called synchronous during creation new allocation.
When new allocations creating fastest, than GC is removing it's new jobs are stuck at synchronous GC

**Comment by tgross** [comment] 2024-06-24 15:44
Going to mark this issue as a duplicate of https://github.com/hashicorp/nomad/issues/19917 just to make it a little easier to keep track of the work to fix it. But I'll leave a back-reference to hear because there's been some good debugging in this issue already.

**Closed by tgross** 2024-06-24 15:44 UTC
Labels: type/bug, stage/duplicate, theme/resiliency
