### ISSUE TITLE
it seems that nomad restart tasks when server leadership changed

### ISSUE THREAD

**Issue by tantra35** [hashicorp/nomad#2453] opened 2017-03-16 16:37 UTC
### Nomad version
Nomad v0.5.4

### Issue
We had stuck server where was placed nomad-server agent. Server respond time to time, but it fully hung, so we have made reset it. And at this moment I noticed that most of the task has restarted

We have follow logs, at moment when leadeship was changed(`192.168.30.6` - is stuck server)

```
    2017/03/16 18:03:11 [WARN] raft: Rejecting vote request from 192.168.30.6:4647 since we have a leader: 192.168.30.4:4647
    2017/03/16 18:03:13.419195 [ERR] worker: failed to dequeue evaluation: rpc error: eval broker disabled
    2017/03/16 18:03:13.419274 [ERR] worker: failed to dequeue evaluation: rpc error: eval broker disabled
    2017/03/16 18:03:14 [WARN] raft: Rejecting vote request from 192.168.30.1:4647 since we have a leader: 192.168.30.4:4647
    2017/03/16 18:03:15 [WARN] raft: Heartbeat timeout from "192.168.30.4:4647" reached, starting election
    2017/03/16 18:03:18 [WARN] raft: Rejecting vote request from 192.168.30.6:4647 since we have a leader: 192.168.30.1:4647
    2017/03/16 18:04:01 [ERR] memberlist: Failed TCP fallback ping: read tcp 192.168.31.220:50796->192.168.30.6:4648: i/o timeout
    2017/03/16 18:06:16 [ERR] memberlist: Failed TCP fallback ping: read tcp 192.168.31.220:53056->192.168.30.6:4648: i/o timeout
```

For example we have fllow state of zabbixmysql task

```
root@social:/home/ruslan# nomad status zabbixmysql
ID            = zabbixmysql
Name          = zabbixmysql
Type          = service
Priority      = 70
Datacenters   = test
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group   Queued  Starting  Running  Failed  Complete  Lost
zabbixmysql  0       0         1        0       1         0

Allocations
ID        Eval ID   Node ID   Task Group   Desired  Status   Created At
420974b1  964cd154  e96e5b23  zabbixmysql  run      running  03/16/17 18:04:20 MSK

```

We can make conclusion that nomad doens't simple restart task, it loses perviouse state(we doens't see allocation with Desired: `stop` and  Status: `complete`, but not so much time that nomad GC completed alloaction)

**Comment by dadgar** [comment] 2017-03-16 20:47
@tantra35 I am having a hard time following what the issue is?

**Comment by tantra35** [comment] 2017-03-16 21:09
I think yes, problem is that not all jobs was restarted, in our case, i may say that tasks was restarted only on some nodes, but this nodes was absolutely health, and linked with other throw single network switch. Perhaps this happens when leader begin work unstable, like this happened at this time, but in previous situations we doesn't saw any abnormal behavior of leader or servers

**Comment by dadgar** [comment] 2017-03-16 21:30
@tantra35 Can you show the restarting tasks you are mentioning? On a leader transition there should be no restarts. All allocations are committed to a quorum of servers, so even if that leader failed, the other servers should know about the allocation.

Are you by chance running servers/clients on the same machine?

**Comment by tantra35** [comment] 2017-03-16 21:32
And question, suppose leader election happens in 2 sec interval, so as i understand nomad can't update alloc state at this period and can make decision that allocs are lost?

**Comment by dadgar** [comment] 2017-03-16 21:34
@tantra35 That is correct. You need a leader to make scheduling decisions. The client will resend its updates however so they are not lost.

**Comment by tantra35** [comment] 2017-03-16 21:37
Yes, here

```
root@social:/home/ruslan# nomad status zabbixfrontend
ID            = zabbixfrontend
Name          = zabbixfrontend
Type          = service
Priority      = 70
Datacenters   = test
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group      Queued  Starting  Running  Failed  Complete  Lost
zabbixfrontend  0       0         1        0       1         0

Allocations
ID        Eval ID   Node ID   Task Group      Desired  Status   Created At
01e3cbfa  8c9fbbb4  e96e5b23  zabbixfrontend  run      running  03/16/17 18:04:20 MSK
```

```
root@social:/home/ruslan# nomad status zabbixmysql
ID            = zabbixmysql
Name          = zabbixmysql
Type          = service
Priority      = 70
Datacenters   = test
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group   Queued  Starting  Running  Failed  Complete  Lost
zabbixmysql  0       0         1        0       1         0

Allocations
ID        Eval ID   Node ID   Task Group   Desired  Status   Created At
420974b1  964cd154  e96e5b23  zabbixmysql  run      running  03/16/17 18:04:20 MSK
```
```
root@social:/home/ruslan# nomad status carbon
ID            = carbon
Name          = carbon
Type          = service
Priority      = 70
Datacenters   = test
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
carbon-a    0       0         1        0       2         0

Allocations
ID        Eval ID   Node ID   Task Group  Desired  Status    Created At
be6a3ce2  be46ee05  439a2f5a  carbon-a    run      running   03/16/17 20:12:33 MSK
bf2e12a2  99b10653  439a2f5a  carbon-a    stop     complete  03/16/17 18:04:29 MSK
```

This task was restarted by myself at `20:12:33 MSK`, but you can see that it was previously restarted  by nomad at `20:12:33 MSK` with no any reason for this

**Comment by tantra35** [comment] 2017-03-16 21:39
All this task was restarted at the same time(roughly) 18:04 MSK when leader migrations happens

**Comment by dadgar** [comment] 2017-03-17 18:28
@tantra35 Can you create a gist with all the server logs. Are you sure the allocations were not just garbage collected?

**Comment by tantra35** [comment] 2017-03-20 09:34
https://gist.github.com/tantra35/4cca03f070f34bbae8837d44a30ab89d

Yes you right, this allocs was garbage collected(probably I incorrectly expressed), but GC for killed allocs happened too early(within few minutes), so when i saw 'nomad status <bla bla bla>' after 10 minutes  i doesn't saw anything except allocs in run(runnning) state, but must also saw additional allocs in stop(complete) state.  In prev post i try to demonstrate this for all task that i mention

**Comment by dadgar** [comment] 2017-03-20 16:51
@tantra35 You are running clients and servers together? I do not think there is a bug here. You lost leadership and the allocations on the client were likely marked as lost. When you regained quorum the allocations were replaced and the old ones were garbage collected because they were marked as failed and old. The threshold is 4 hours and you didn't have a leader for 13+ hours..

**Comment by dadgar** [comment] 2017-03-20 16:52
Is there a reason you are running 7 servers?

**Closed by dadgar** 2017-03-20 16:51 UTC
Labels: waiting-reply

**Comment by tantra35** [comment] 2017-03-20 17:13
>>>The threshold is 4 hours and you didn't have a leader for 13+ hours..

How this can be? Sorry but for me this looks like a bug. Yes in our environment leader node was hang, but there was another 6 healthy server nodes, why they doesn't got leadership, from hang node?  If i understend logs right, part of nodes thinked that leader(server6 192.168.30.6) is health, and reject leadership requests:

```
    2017/03/16 12:40:56 [WARN] raft: Rejecting vote request from 192.168.30.1:4647 since we have a leader: 192.168.30.6:4647
    2017/03/16 12:40:56 [WARN] raft: Rejecting vote request from 192.168.30.1:4647 since we have a leader: 192.168.30.6:4647
    2017/03/16 12:40:57 [WARN] raft: Rejecting vote request from 192.168.31.220:4647 since we have a leader: 192.168.30.6:4647
    2017/03/16 12:40:57 [WARN] raft: Rejecting vote request from 192.168.30.2:4647 since we have a leader: 192.168.30.6:4647
```

This is our test enviroemnt. and there no any reason to launch so many servers, the reason only one - it's easier to configure

**Comment by dadgar** [comment] 2017-03-20 17:28
@tantra35 Sorry you are right, looking at your logs more you had lost leadership once but look to be re-electing.

```
 2017/03/16 18:04:11.531554 [WARN] nomad.heartbeat: node 'e96e5b23-ec85-27a5-7efb-2e6e7d44de19' TTL expired
    2017/03/16 18:04:18.561359 [WARN] nomad.heartbeat: node '439a2f5a-5090-c526-ce8d-82539b715a56' TTL expired
    2017/03/16 18:04:26.384561 [WARN] nomad.heartbeat: node '41b521c8-d666-ce6d-b2b4-1e937f11e37f' TTL expired
```

Either way what I told appears to be what is happening. You lost those nodes and replacements were created and the allocations were garbage collected.
