### ISSUE TITLE
Ephemeral disk migration fails when ACL is enabled

### ISSUE THREAD

**Issue by burdandrei** [hashicorp/nomad#4525] opened 2018-07-23 08:24 UTC
### Nomad version
Output from `nomad version`
Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)

### Operating system and Environment details
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"

### Issue
Ephemeral disk migration fails when ACL is enabled
Here is the Anonymous policy:
```hcl
$ nomad acl policy info anonymous

Name        = anonymous
Description = Allow read-only access for anonymous requests
Rules       = namespace "default" {
  policy = "read"
}
agent {
    policy = "read"
}
node {
    policy = "write"
}
CreateIndex = 6841952
ModifyIndex = 6842341
```

We tried to use ```ephemeral_disk {
      migrate = true
      size    = "500"
      sticky  = true
    }
  }```

Looks like because Nomad client doesn't know to run with the agent token, like consul and our anonymous token can't read the fs of the allocation, call that tries to migrate the data receives 403.

### Nomad Client logs (if appropriate)
2018/07/22 14:30:17.560315 [WARN] client: alloc "b8b35f2e-9e29-1866-cf87-22858f81f0f4" error while migrating data from previous alloc: error getting snapshot from previous alloc "441b2bd9-0f31-9e95-88f2-5868211d51b0": Unexpected response code: 403 (Permission denied)

**Comment by schmichael** [comment] 2018-07-23 13:21
Nodes use an ephemeral "migration" token when using ACLs and migrating ephemeral disks. I'll investigate to see if there was a regression in 0.8.4

**Comment by schmichael** [comment] 2018-07-23 13:39
Unfortunately I was unable to reproduce this using a 2 node cluster with ACLs enabled. I see the data migrated from one node to the other and a successful HTTP snapshot request (the request used to migrate):

```
2018/07/23 06:34:38.329342 [DEBUG] http: Request GET /v1/client/allocation/3d83e85d-6431-1507-f728-0a3d02505a39/snapshot (3.210632ms)
```

I tried it a few times without error. Does this happen every time for you? Is every node in the cluster on 0.8.4? Can you post any logs associated with either of those alloc IDs on either client node or the servers?

**Comment by burdandrei** [comment] 2018-07-23 19:42
Happened every time for me.
I triggered the migration by draining the node running the allocation.
Every node is 0.8.4.
I'll reproduce it and gather both server and client logs and will update.
Thanks for quick answer!

**Comment by burdandrei** [comment] 2018-07-29 14:16
Hi @schmichael 
here is what we have:
Job description:
```hcl
job "migrate" {
  datacenters = ["staging-us-east-1"]
  type = "service"

  constraint {
    attribute = "${node.class}"
    value     = "bandrei"
  }

  update {
    max_parallel = 1
    min_healthy_time = "10s"
    healthy_deadline = "3m"
    progress_deadline = "10m"
    auto_revert = false
    canary = 0
  }

  migrate {
    max_parallel = 1
    health_check = "checks"
    min_healthy_time = "10s"
    healthy_deadline = "5m"
  }

  group "cache" {
    count = 1
    restart {
      attempts = 2
      interval = "30m"
      delay = "15s"
      mode = "fail"
    }

    ephemeral_disk {
      migrate = true
      size = 300
    }

    task "redis" {
      driver = "docker"
      config {
        image = "redis:alpine"
          volumes = [
            "local/redis/data:/data"
          ]
        port_map {
          db = 6379
        }
      }
      
      resources {
        cpu    = 500 # 500 MHz
        memory = 256 # 256MB
        network {
          mbits = 10
          port "db" {}
        }
      }

      service {
        name = "bandrei"
        tags = ["global", "cache"]
        port = "db"
        check {
          name     = "alive"
          type     = "tcp"
          interval = "10s"
          timeout  = "2s"
        }
      }
    }
  }
}
```

here are the logs from node A:
```
root@ip-10-101-5-117:/var/lib/nomad/alloc/4c539f64-bd89-77d6-10bb-f533c417a015/redis/local/redis/data# ll
total 12
drwxr-xr-x 2 systemd-timesync root            4096 Jul 29 13:58 ./
drwxr-xr-x 3 root             root            4096 Jul 29 13:57 ../
-rw-r--r-- 1 systemd-timesync systemd-journal  109 Jul 29 13:58 dump.rdb
root@ip-10-101-5-117:/var/lib/nomad/alloc/4c539f64-bd89-77d6-10bb-f533c417a015/redis/local/redis/data# nomad node drain -self -enable
2018-07-29T14:01:37Z: Ctrl-C to stop monitoring: will not cancel the node drain
2018-07-29T14:01:37Z: Node "cc8c10d5-7cd1-3324-5309-749c88513722" drain strategy set
2018-07-29T14:01:38Z: Alloc "4c539f64-bd89-77d6-10bb-f533c417a015" marked for migration
2018-07-29T14:01:38Z: Alloc "4c539f64-bd89-77d6-10bb-f533c417a015" draining
2018-07-29T14:01:38Z: No drain strategy set for node cc8c10d5-7cd1-3324-5309-749c88513722
root@ip-10-101-5-117:/var/lib/nomad/alloc/4c539f64-bd89-77d6-10bb-f533c417a015/redis/local/redis/data# Jul 29 14:01:38 ip-10-101-5-117 nomad[4733]: 2018-07-29T14:01:38.606Z [DEBUG] plugin.nomad: 2018/07/29 14:01:38 [ERR] plugin: plugin server: accept unix /tmp/plugin103563321: use of closed network connection
Jul 29 14:01:38 ip-10-101-5-117 nomad[4733]: 2018-07-29T14:01:38.608Z [DEBUG] plugin: plugin process exited: path=/usr/local/bin/nomad
Jul 29 14:01:38 ip-10-101-5-117 nomad[4733]:     2018/07/29 14:01:38.609228 [INFO] (runner) stopping
Jul 29 14:01:38 ip-10-101-5-117 nomad[4733]:     2018/07/29 14:01:38.609310 [INFO] client.gc: marking allocation 3e8ef463-8c32-e91d-c9b8-24b24ea2fb7a for GC
Jul 29 14:01:38 ip-10-101-5-117 nomad[4733]:     2018/07/29 14:01:38.609606 [INFO] (runner) received finish
Jul 29 14:01:38 ip-10-101-5-117 nomad[4733]:     2018/07/29 14:01:38.873049 [INFO] driver.docker: stopped container 8ef476a0c63c2cd0f7c2928ba25f4f6d208e9f4589dae81acb9642711c4432c1
Jul 29 14:01:42 ip-10-101-5-117 nomad[4733]: 2018-07-29T14:01:42.878Z [DEBUG] plugin.nomad: 2018/07/29 14:01:42 [ERR] plugin: plugin server: accept unix /tmp/plugin641633217: use of closed network connection
Jul 29 14:01:42 ip-10-101-5-117 nomad[4733]: 2018-07-29T14:01:42.878Z [DEBUG] plugin: plugin process exited: path=/usr/local/bin/nomad
Jul 29 14:01:42 ip-10-101-5-117 nomad[4733]:     2018/07/29 14:01:42.888854 [INFO] client.gc: marking allocation 4c539f64-bd89-77d6-10bb-f533c417a015 for GC
Jul 29 14:01:43 ip-10-101-5-117 nomad[4733]:     2018/07/29 14:01:43.097830 [ERR] http: Request /v1/client/allocation/4c539f64-bd89-77d6-10bb-f533c417a015/snapshot, error: Permission denied
```

Here are the logs from node B:
```
root@ip-10-101-5-208:~# Jul 29 14:01:43 ip-10-101-5-208 nomad[6545]:     2018/07/29 14:01:43.096091 [WARN] client: alloc "35ee2f0d-96df-3c44-bd22-017c3bba8f27" error while migrating data from previous alloc: error getting snapshot from previous alloc "4c539f64-bd89-77d6-10bb-f533c417a015": Unexpected response code: 403 (Permission denied)
Jul 29 14:01:44 ip-10-101-5-208 nomad[6545]: 2018-07-29T14:01:44.220Z [DEBUG] plugin: starting plugin: path=/usr/local/bin/nomad args="[/usr/local/bin/nomad executor {"LogFile":"/var/lib/nomad/alloc/35ee2f0d-96df-3c44-bd22-017c3bba8f27/redis/executor.out","LogLevel":"INFO"}]"
Jul 29 14:01:44 ip-10-101-5-208 nomad[6545]: 2018-07-29T14:01:44.221Z [DEBUG] plugin: waiting for RPC address: path=/usr/local/bin/nomad
Jul 29 14:01:44 ip-10-101-5-208 nomad[6545]: 2018-07-29T14:01:44.250Z [DEBUG] plugin.nomad: plugin address: timestamp=2018-07-29T14:01:44.249Z address=/tmp/plugin514408554 network=unix
Jul 29 14:01:44 ip-10-101-5-208 nomad[6545]:     2018/07/29 14:01:44.298569 [INFO] driver.docker: created container 6be69b2ef4b0f2cc1c8dc903043f0f1de42055ecf487cfd66ce0adc7f6be5743
Jul 29 14:01:44 ip-10-101-5-208 nomad[6545]:     2018/07/29 14:01:44.627857 [INFO] driver.docker: started container 6be69b2ef4b0f2cc1c8dc903043f0f1de42055ecf487cfd66ce0adc7f6be5743
```
Couldn't ding anything on the server side(Leader).
Anything else i can do to debug this?

**Comment by tgross** [comment] 2020-08-24 15:08
I'm doing some issue clean-up and this one dates from before the big 0.9 refactoring. Without a reproduction from our side I think the best course of action for this issue is to close it out at this point.

**Closed by tgross** 2020-08-24 15:08 UTC
Labels: theme/client, type/bug
