### ISSUE TITLE
 Killing a job and re-running the job does not start the job again

### ISSUE THREAD

**Issue by olvesh** [hashicorp/nomad#230] opened 2015-10-07 11:03 UTC
Ref discussion at: 
https://groups.google.com/forum/#!topic/nomad-tool/U63kPAQ1uMo

I have been messing around with the steps in the getting started guide, and tried to check what happens when I kill a running job (Allocation).

Armon Dadgar suggested I file a bug for the case. I follow the same steps with one server and two client. A simpler example might be possible, but I haven't got the time to simplify, hope it os ok.

I simply started the job with  ``` nomad run example.nomad``` restarted docker and ran the nomad run command again.

Uploading text files to github just doesn't work atm.. Check gist
https://gist.github.com/olvesh/1b5434fe27ffd537f64b

**Comment by cbednarski** [comment] 2015-10-15 01:58
Thanks for the report! I think this is a duplicate of https://github.com/hashicorp/nomad/issues/176

I'm going to close this as a duplicate issue but if this is not the same please reopen and/or ping me.

**Closed by cbednarski** 2015-10-15 01:58 UTC
Labels: bug, core
