### ISSUE TITLE
Log cluster events 

### ISSUE THREAD

**Issue by diptanu** [hashicorp/nomad#3478] opened 2017-10-31 20:32 UTC
One of the challenges we face with Nomad is that job owners can't debug their services when they are GCed. We need cluster events to be logged to storage so that job owners can look into the cluster events and debug problems, this would be useful for scheduler developers too. 

I think there are two options here, either we log events that are applied to the state store from the FSM into a log or we write objects to the log before they are being GCed. You could do even more fancy things in the future to it and build SQL like interfaces to the datastore for users to query.

Background - Folks are using the Nomad API to launch dynamic jobs and scale them out and is based on workload, and they have been asking the people operating Nomad what happened to their allocations which are GCed.

@dadgar any opinions on this? I am happy to work on this as well.

**Comment by dadgar** [comment] 2017-10-31 20:34
@diptanu Is this a dupe of https://github.com/hashicorp/nomad/issues/1137

**Comment by diptanu** [comment] 2017-10-31 20:57
Yes, please feel free to close either of them.

**Closed** 2017-10-31 23:38 UTC
Labels: core, enhancement
