### ISSUE TITLE
for driver=docker the force_pull=true is not honored

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23681] opened 2024-07-24 16:26 UTC
### Nomad version
```
Nomad v1.8.2
BuildDate 2024-07-16T08:50:09Z
Revision 7f0822c1e4f25907d9f60e2d595411950dd1bd28
```

### Issue
We released the new version of docker images (the `latest` tag is used) and replanned Nomad task, but noting is happened

```
kes@Eugens-MacBook-Pro nomad $ nomad job plan -var="project_name=$PRTL_PROJECT_NAME" -var="base_domain=$PRTL_BASE_DOMAIN" derived-src/services/portal.hcl
Job: "portal"
Task Group: "wi-api" (1 in-place update)
  Task: "wi-api-task"

Task Group: "wi-knecht" (1 in-place update)
  Task: "wi-knecht-task"

Task Group: "wi-nginx" (1 in-place update)
  Task: "wi-nginx-task"

Task Group: "wi-webshot" (1 in-place update)
  Task: "wi-webshot-task"

Scheduler dry-run:
- All tasks successfully allocated.

Job Modify Index: 1915
To submit the job with version verification run:

nomad job run -check-index 1915 -var="project_name=nomad" -var="base_domain=XXX" derived-src/services/portal.hcl

When running the job with the check-index flag, the job will only be run if the
job modify index given matches the server-side version. If the index has
changed, another user has modified the job and the plan's results are
potentially invalid.
kes@Eugens-MacBook-Pro nomad $ nomad job run -check-index 1915 -var="project_name=nomad" -var="base_domain=XXX" derived-src/services/portal.hcl
==> 2024-07-24T12:21:03-04:00: Monitoring evaluation "36b36fb2"
    2024-07-24T12:21:04-04:00: Evaluation triggered by job "portal"
    2024-07-24T12:21:04-04:00: Evaluation within deployment: "1f9e46e9"
    2024-07-24T12:21:04-04:00: Evaluation status changed: "pending" -> "complete"
==> 2024-07-24T12:21:04-04:00: Evaluation "36b36fb2" finished with status "complete"
==> 2024-07-24T12:21:04-04:00: Monitoring deployment "1f9e46e9"
  ✓ Deployment "1f9e46e9" successful

    2024-07-24T12:21:04-04:00
    ID          = 1f9e46e9
    Job ID      = portal
    Job Version = 8
    Status      = successful
    Description = Deployment completed successfully

    Deployed
    Task Group  Desired  Placed  Healthy  Unhealthy  Progress Deadline
    wi-api      1        1       1        0          2024-07-24T16:13:03Z
    wi-knecht   1        1       1        0          2024-07-24T16:12:57Z
    wi-nginx    1        1       1        0          2024-07-24T16:13:04Z
    wi-webshot  1        1       1        0          2024-07-24T16:12:52Z
```

### Reproduction steps
1. Deploy task
2. Build new version of application
3. Replan job

#### Expected Result
Nomad should check and pull newer version of docker image

#### Actual Result
Nothing is happened.

### Job file (if appropriate)
```
     ...
      driver = "docker"

      config {
        force_pull = true
        image = "planitar/wi-webshot:latest"
        ports = ["wi-webshot-srv"]
      }
```

As a temporary workaround I stop job/plan/run job.

**Comment by tgross** [comment] 2024-07-24 16:28
Duplicate of https://github.com/hashicorp/nomad/issues/23627. What I told you there:

> @EugenKon that's not what the [`force_pull`](https://developer.hashicorp.com/nomad/docs/drivers/docker#force_pull) flag is for. Here's the docs:

> force_pull - (Optional) true or false (default). Always pull most recent image instead of using existing local image. Should be set to true if repository tags are mutable. If image's tag is latest or omitted, the image will always be pulled regardless of this setting.

> Note that this doesn't say anything about forcing tasks to be replaced. The Nomad schedulers, which are running on completely separate machines, have no way of talking to Docker to figure out if the image has been changed. Nor would we want to have evaluation processing change depending on external APIs.

**Closed by tgross** 2024-07-24 16:28 UTC
Labels: type/bug

**Comment by tgross** [comment] 2024-07-25 15:29
You'd need to update the jobspec. Either use explicit tags for your Docker image, or update a field that forces a reschedule (ex. you could have a [`meta`](https://developer.hashicorp.com/nomad/docs/job-specification/meta) field that gets bumped each time you update the image.
