### ISSUE TITLE
Deploying a CSI plugin container that is neither a controller or a node

### ISSUE THREAD

**Issue by gregory112** [hashicorp/nomad#11903] opened 2022-01-22 08:45 UTC
### Nomad version
Nomad v1.2.3 (a79efc8422082c4790046c3f5ad92c542592a54f)

### Operating system and Environment details
Ubuntu, Linux 5.4.0-96-generic

### Issue
I am trying to follow ceph-csi documentation about ceph-csi plugin deployment in Kubernetes, so I can deploy ceph-csi in Nomad. So far I have been doing it fine, but the plugin seems to does not survive reboot, for example, if Nomad and Ceph both reside in the same host and the host is rebooted, the plugin starts before Ceph starts and the plugin fails forever.

The ceph-csi support --type=liveness mode apart from controller or node. It exposes Prometheus metrics too. This way, I think, I can use it to setup Consul health check and so the job can be rescheduled should it fail to start. Following the Kubernetes deployment [here](https://github.com/ceph/ceph-csi/blob/devel/deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml), it seems to deploy a separate pod with `--type=liveness` flag set, but it does require mounting the `/csi` directory. Now for controller and nodes, `/csi` directory where the CSI socket file lives seems to be mounted with `csi_plugin` stanza, like so:

```
      csi_plugin {
        id = "ceph-csi"
        type = "node"
        mount_dir = "/csi"
      }
```

I wonder if I can create another task in ceph-csi node to run the CSI node as liveness (not controller, not node) together in the node job (which is a system job), but still also mount the `/csi` directory? If I want to mount it using `volume_mount`, I don't know from which volume it is mounted from. If I were to use `csi_plugin`, does that mean I have to set the type to "node" or something else? If it's set to node, I assume it will be detected as CSI nodes and be used to mount volumes while in fact it is not a node and so unable to serve mount requests.

### Job file (if appropriate)

```
job "ceph-csi-node" {
  datacenters = ["my-datacenter"]
  type = "system"

  update {
    health_check      = "checks"
    min_healthy_time  = "10s"
    healthy_deadline  = "25m"
    progress_deadline = "30m"
  }

  group "nodes" {
    task "plugin" {
      driver = "docker"

      template {
        destination = "local/config.json"
        data = <<EOF
[{
    "clusterID": "[[ .ceph_fsid ]]",
    "monitors": [[ mustToJson .ceph_monitor ]]
}]
EOF
        change_mode = "restart"
      }

      config {
        image = "[[ .ceph_image ]]"
        image_pull_timeout = "20m"
        volumes = [
          "./local/config.json:/etc/ceph-csi-config/config.json",
          "/lib/modules:/lib/modules"
        ]
        mounts = [
          {
            type     = "tmpfs"
            target   = "/tmp/csi/keys"
            readonly = false
            tmpfs_options = {
              size = 1000000 # size in bytes
            }
          }
        ]
        args = [
          "--type=cephfs",
          "--drivername=[[ .ceph_drivername ]]",
          "--nodeserver=true",
          "--endpoint=unix://csi/csi.sock",
          "--nodeid=${node.unique.name}",
          "--instanceid=${node.unique.name}-nodes",
          "--pidlimit=0",
          "-logtostderr=true",
          "-v=4",
          "-alsologtostderr=true"
        ]
        privileged = true
      }

      csi_plugin {
        id = "ceph-csi"
        type = "node"
        mount_dir = "/csi"
      }
    }
  }
  task "liveness" {
    template {
      data = <<EOF
[{
    "clusterID": "[[ .ceph_fsid ]]",
    "monitors": [[ mustToJson .ceph_monitor ]]
}]
EOF
      destination = "local/config.json"
      change_mode = "restart"
    }

    driver = "docker"

    config {
      image = "[[ .ceph_image ]]"
      image_pull_timeout = "30m"
      volumes = [
        "./local/config.json:/etc/ceph-csi-config/config.json"
      ]
      mounts = [
        {
          type     = "tmpfs"
          target   = "/tmp/csi/keys"
          readonly = false
          tmpfs_options = {
            size = 1000000 # size in bytes
          }
        }
      ]
      args = [
        "--endpoint=unix://csi/csi.sock",
        "--metricsport=8681",
        "--metricspath=/metrics",
        "--type=liveness",
        "--polltime=60s",
        "--timeout=3s",
        "-logtostderr=true",
        "-alsologtostderr=true"
      ]
    }

    csi_plugin {
      id = "ceph-csi"
      type = "node" # What to put here?
      mount_dir = "/csi"
    }
  }
}
```

**Comment by tgross** [comment] 2022-01-24 14:17
Hi @gregory112! It seems like you have two different issues here.

The first issue is:

> I am trying to follow ceph-csi documentation about ceph-csi plugin deployment in Kubernetes, so I can deploy ceph-csi in Nomad. So far I have been doing it fine, but the plugin seems to does not survive reboot, for example, if Nomad and Ceph both reside in the same host and the host is rebooted, the plugin starts before Ceph starts and the plugin fails forever.

This issue is a duplicate of https://github.com/hashicorp/nomad/issues/11784

---

The second issue is:

> The ceph-csi support --type=liveness mode apart from controller or node. It exposes Prometheus metrics too. This way, I think, I can use it to setup Consul health check and so the job can be rescheduled should it fail to start. Following the Kubernetes deployment here, it seems to deploy a separate pod with --type=liveness flag set, but it does require mounting the /csi directory.

Hm... that's a very unfortunate choice on the part of the Ceph CSI plugin authors, as they're relying on implementation details that aren't in the CSI spec and probably aren't guaranteed even by Kubernetes. That being said, I recognize you didn't write the plugin, so let's see what we can do here. 😀 

The first thing I would try is to run the `--type=liveness` without the `/csi` mount at all and see whether that can work. It might be worth digging into the plugin's source code to try to figure out what it's supposed to be doing with the CSI RPCs.

> I wonder if I can create another task in ceph-csi node to run the CSI node as liveness (not controller, not node) together in the node job (which is a system job), but still also mount the `/csi` directory? If I want to mount it using `volume_mount`, I don't know from which volume it is mounted from. 

That's the approach that seems most promising. But the [plugin supervisor hook](https://github.com/hashicorp/nomad/blob/main/client/allocrunner/taskrunner/plugin_supervisor_hook.go) that defines the `/csi` mount runs at the task level, not the allocation level. The directory is written at `$nomad_data_dir/client/csi/node/$plugin_id` on the host. You won't be able to mount that via `volume_mount` but instead will need to use [`task.config.mount`](https://www.nomadproject.io/docs/drivers/docker#mount) and make sure you've set [`docker.volumes.enabled = true`](https://www.nomadproject.io/docs/drivers/docker#docker-volumes-enabled) in the client configuration.

(ref [`plugin_supervisor_hook.go#L64-L75`](https://github.com/hashicorp/nomad/blob/v1.2.4/client/allocrunner/taskrunner/plugin_supervisor_hook.go#L64-L75))

> If I were to use `csi_plugin`, does that mean I have to set the type to "node" or something else? If it's set to node, I assume it will be detected as CSI nodes and be used to mount volumes while in fact it is not a node and so unable to serve mount requests.

Correct, if you use the `csi_plugin` block for this task Nomad will try to send it CSI plugin RPCs, which will fail. So that's not a path that'll work for us.

**Comment by gregory112** [comment] 2022-02-15 04:36
Hi @tgross, sorry for the late reply. Thank you so much for the investigation.

Yes, so I guess there is no CSI node type other than controller or node per spec. However, eventually I did find a way to run node/controller with metrics enabled by setting more flags in it after digging ceph-csi codes.

It does not help though with the root cause of the issue, as the containers are all healthy, with metrics available, while not being reported as a healthy CSI plugin, so this can be closed as a duplicate of https://github.com/hashicorp/nomad/issues/11784?

**Comment by tgross** [comment] 2022-02-15 13:44
> It does not help though with the root cause of the issue, as the containers are all healthy, with metrics available, while not being reported as a healthy CSI plugin, so this can be closed as a duplicate of https://github.com/hashicorp/nomad/issues/11784?

Agreed. Thanks!

**Closed by tgross** 2022-02-15 13:44 UTC
Labels: stage/waiting-reply, type/question, theme/storage
