### ISSUE TITLE
[feature request] Support interpolation from command line flags

### ISSUE THREAD

**Issue by dukeland9** [hashicorp/nomad#3366] opened 2017-10-12 07:47 UTC
https://www.nomadproject.io/docs/runtime/interpolation.html states that "Nomad supports interpreting two classes of variables, node attributes and runtime environment variables.".

Aside from that, sometimes it would be convenient to specify attributes of the job configuration from command line flags. It works like:

job conf:
<pre>
vars {
  region = "global"
}
job "a_job" {
  region = "${args.region}"
  #...
}
</pre>

Command line:
nomad run job.nomad -vars=region=some_other_region

I guess it would be more convenient if we have this feature.

**Comment by dadgar** [comment] 2017-10-12 16:58
Hey! This is definitely a feature we'd like. However closing as a duplicate of: https://github.com/hashicorp/nomad/issues/2422

**Closed by dadgar** 2017-10-12 16:58 UTC
