### ISSUE TITLE
Allow setting graceful termination timeout for each task

### ISSUE THREAD

**Issue by F21** [hashicorp/nomad#522] opened 2015-12-01 04:31 UTC
It would be nice if we could set a custom timeout for terminating tasks.

For example, I might have a task (running in docker) that provides an api for other services and takes a while to clean up on termination. I would like to be able to do the following:

1. On termination, it is deregistered from consul so that no more new requests flow to it.
2. It continues working to complete current requests and sends a response.
3. If it does not terminate in the duration of the timeout set for graceful termination, nomad kills it forcefully (to prevent tasks from hanging around for ever).
4. If it does terminate gracefully, all is well.

**Comment by dadgar** [comment] 2015-12-01 17:06
Yeah that is a possibility. Nomad already does this. It first does a SIGTERM and then a SIGKILL but the period is not user specifiable currently. Do you need it to be configurable or you just want the soft kill then hard kill behavior?

**Comment by F21** [comment] 2015-12-01 21:21
I would love to be able to configure the timeout, because some tasks might take a bit longer to clean up (hence a longer timeout).

**Comment by cbednarski** [comment] 2015-12-02 18:24
This is a duplicate of https://github.com/hashicorp/nomad/issues/17

**Comment by dadgar** [comment] 2016-01-04 19:44
Fixed by #624

**Closed by dadgar** 2016-01-04 19:44 UTC
Labels: config, duplicate, enhancement
