### ISSUE TITLE
Use HIL for interpolation

### ISSUE THREAD

**Issue by clinta** [hashicorp/nomad#3020] opened 2017-08-14 13:13 UTC
Is there any ongoing work to replace nomad's interpolation with https://github.com/hashicorp/hil. We need the ability to do some basic math in the interpolation, and I'm willing to try to start the work to replace nomad's basic regex replacement with HIL, but I wanted to open this issue to make sure this is something that would be appreciated or if you're intending to do something different with the interpolation in nomad.

**Comment by schmichael** [comment] 2017-08-14 18:11
We absolutely want to use HIL for interpolation in Nomad. You can see a few more details on #1185.

Unfortunately I still don't have a firm timeline, although I can say that prerequisite work is in progress. We really want to release it as a holistic interpolation system instead of slowly migrating support over as Nomad's interpolation is quite complex. There are 3 or more different times that interpolation needs to progressively occur with different validation at each stage. We're excited to do the work, but it's still a little ways out.

Closing as a duplicate of #1185.

**Closed by schmichael** 2017-08-14 18:11 UTC
