### ISSUE TITLE
Add ability to read environment variables from a local file

### ISSUE THREAD

**Issue by mildred** [hashicorp/nomad#2669] opened 2017-05-24 09:18 UTC
Currently, I have a nomad job running a docker container where some of the environment variables are generated using a nomad template. This is very useful to generate some of the environment variables from consul keys.

Currently, I'm overriding the run command with a `sh -c` command running a oneliner script. This works for this particular use case but it won't work for every docker image.

What would be nice is to have a possibility to define a list of files containing environment variables that would be read before running the task.

My current job looks like:

    task "web" {
      driver = "docker"
      config {
        command = "sh"
        args = [
          "-c",
          "exec 2>&1; . /local/env; env | sort; exec bundle exec rails server -b 0.0.0.0"
        ]
        ...
      }

      ...

      template {
        destination = "local/env"
        data = <<TEMPLATE
    export PROJECT_SERVER_URL=http://local-{{key_or_default "squarescale-web/forward-address" ""}}
    TEMPLATE
      }
    }

I'd prefer something like:

    task "web" {
      driver = "docker"

      ...

      environment_files = [ "local/env" ]

      template {
        destination = "local/env"
        data = <<TEMPLATE
    PROJECT_SERVER_URL=http://local-{{key_or_default "squarescale-web/forward-address" ""}}
    TEMPLATE
      }
    }

**Comment by schmichael** [comment] 2017-05-24 16:00
Great minds think alike! #2654 is almost ready and adds almost exactly the behavior you're asking for. The one difference is that instead of the `environment_files=[...]` key there's an `env=true` flag on each template you want to read in as an environment variable.

It will be in master soon and released in 0.6.

Closing this as a dupe of #1765 as that's the original inspiration for this feature.

**Closed by schmichael** 2017-05-24 16:00 UTC
