### ISSUE TITLE
Validation error when registering a volume

### ISSUE THREAD

**Issue by eightseventhreethree** [hashicorp/nomad#11115] opened 2021-09-01 16:27 UTC
### Nomad version
```
root@nomad-server-shared-001:/etc/nomad.d# nomad -version
Nomad v1.1.3 (8c0c8140997329136971e66e4c2337dfcf932692)
```

### Operating system and Environment details
```
root@nomad-server-shared-001:/etc/nomad.d# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
### Issue
Attempting to register a volume to a running CSI plugin.

### Reproduction steps
1. Deploy CSI plugin and nodes.
2. Verify that plugin nodes and controller count is expected.
```
root@nomad-server-shared-001:/etc/nomad.d# nomad plugin status -verbose | grep us-east-1b
aws-ebs-us-east-1b                    ebs.csi.aws.com  1/1                           1/1
```
3. Run volume register w/ definition.

client error:
```
root@nomad-server-shared-001:/etc/nomad.d# nomad volume register plan-stateful-example-aws-qa-stateful-volume-vol.nomad
Error registering volume: Unexpected response code: 500 (validation: missing access mode, missing attachment mode)
```
server logs:
```
2021-09-01T16:26:27.830Z [DEBUG] http: request complete: method=GET path=/v1/deployment/7a6d55f4-fe51-704c-2f97-1120875eb859?index=47672&region=shared&stale=&wait=2000ms duration=2.005005264s
2021-09-01T16:26:28.917Z [ERROR] http: request failed: method=PUT path=/v1/volume/csi/stateful-volume error="validation: missing access mode, missing attachment mode" code=500
2021-09-01T16:26:28.917Z [DEBUG] http: request complete: method=PUT path=/v1/volume/csi/stateful-volume duration=285.345µs
```

### Job file (if appropriate)
Controller:
```
job "service-aws-ebs-controller-us-east-1b-aws-qa" {

  datacenters   = ["aws"]
  type          = "service"
  region        = "shared"

  constraint {
    operator   = "="
    attribute   = "${attr.platform.aws.placement.availability-zone}"
    value   = "us-east-1b"
  }


  group "controllers" {

    count = 1

  
    task "plugin" {
      driver = "docker"

      config {
        image = "aws-ebs-csi-driver:release-1.2"

        args = [
            "controller", "--endpoint=unix://csi/csi.sock", "--logtostderr", "--v=5",
        ]


      }
      
      csi_plugin  {
          id = "aws-ebs-us-east-1b"
          type = "controller"
          mount_dir = "/csi"
        }
    
      resources {
        cpu    = 500
        memory = 256
      }
    }
    }
}

```

Nodes:
```
job "system-aws-ebs-nodes-us-east-1b-aws-qa" {

  datacenters   = ["aws"]
  type          = "system"
  region        = "shared"

  constraint {
    operator   = "="
    attribute   = "${attr.platform.aws.placement.availability-zone}"
    value   = "us-east-1b"
  }


  group "nodes" {


  
    task "plugin" {
      driver = "docker"

      config {
        image = "aws-ebs-csi-driver:release-1.2"

        args = [
            "node", "--endpoint=unix://csi/csi.sock", "--logtostderr", "--v=5",
        ]

      privileged = true

      }
      
      csi_plugin  {
          id = "aws-ebs-us-east-1b"
          type = "node"
          mount_dir = "/csi"
        }
    
      resources {
        cpu    = 500
        memory = 256
      }
    }
    }
}
```

Volume registration:
```
# volume registration
id = "stateful-volume"
name = "stateful-volume"
type = "csi"
external_id = "vol-035d8274ccec3e051"
plugin_id = "aws-ebs-us-east-1b"

capability {
  access_mode     = "single-node-writer"
  attachment_mode = "file-system"
}
capability {
  access_mode     = "single-node-writer"
  attachment_mode = "file-system"
}

mount_options {
  fs_type     = "ext4"
}

```

**Comment by lgfa29** [comment] 2021-09-02 20:42
Hi @eightseventhreethree 👋 

I'm not being able to reproduce this issue 🤔 

Could you check if your servers and clients are all running the same Nomad version? You can use the `nomad server members` and `nomad node status -verbose` commands.

Also, do you see anything in the plugin logs?

**Comment by tgross** [comment] 2022-02-03 19:06
Just wanted to follow up on this: the error message received here only exists Nomad 1.0.x and was removed in Nomad 1.1.0. So it looks like there were mixed versions of Nomad among the servers here. Going to close this issue out.

**Closed by tgross** 2022-02-03 19:06 UTC
Labels: type/bug, theme/storage, stage/needs-verification
