### ISSUE TITLE
segfault while verifying Vault role

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#2644] opened 2017-05-15 13:57 UTC
### Nomad version

`v0.5.6`

### Operating system and Environment details

```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

### Issue

Segfault while trying to validate Vault role

I'm largely following the guide at https://www.nomadproject.io/docs/vault-integration/index.html - with the exception that my initial token is created using `aws-ec2` from vault 

Vault is running 0.7.0 

### Nomad Server logs (if appropriate)

```
==> Starting Nomad agent...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xd11ae0]

goroutine 29 [running]:
github.com/hashicorp/nomad/nomad.(*vaultClient).validateRole(0xc420376d00, 0xc4203f6203, 0xc, 0xc420440400, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/nomad/vault.go:793 +0x290
github.com/hashicorp/nomad/nomad.(*vaultClient).parseSelfToken(0xc420376d00, 0xc420494201, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/nomad/vault.go:680 +0x291
github.com/hashicorp/nomad/nomad.(*vaultClient).establishConnection(0xc420376d00)
	/opt/gopath/src/github.com/hashicorp/nomad/nomad/vault.go:437 +0x293
github.com/hashicorp/nomad/nomad.(*vaultClient).(github.com/hashicorp/nomad/nomad.establishConnection)-fm()
	/opt/gopath/src/github.com/hashicorp/nomad/nomad/vault.go:259 +0x2a
github.com/hashicorp/nomad/nomad.wrapNilError.func1(0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/nomad/vault.go:1178 +0x24
github.com/hashicorp/nomad/vendor/gopkg.in/tomb%2ev2.(*Tomb).run(0xc420422630, 0xc42040c210)
	/opt/gopath/src/github.com/hashicorp/nomad/vendor/gopkg.in/tomb.v2/tomb.go:153 +0x2b
created by github.com/hashicorp/nomad/vendor/gopkg.in/tomb%2ev2.(*Tomb).Go
	/opt/gopath/src/github.com/hashicorp/nomad/vendor/gopkg.in/tomb.v2/tomb.go:149 +0xd2
```

### Vault Config (json)

```
  "vault": {
      "enabled": true,
      "address": "http://active.vault.service.consul:8200",
      "create_from_role": "nomad-server"
  }
```

**Comment by dadgar** [comment] 2017-05-16 16:20
Hey,

Thanks for reporting. It is a know issue that will be fixed in 0.6.0. The root cause is that the role doesn't exist in Vault. Closing as it is a duplicate of: https://github.com/hashicorp/nomad/issues/2451

**Closed by dadgar** 2017-05-16 16:20 UTC
