### ISSUE TITLE
change CLI to use wildcard namespace instead of "default"

### ISSUE THREAD

**Issue by yitbarek123** [hashicorp/nomad#11487] opened 2021-11-09 22:28 UTC
Nomad version
1.1.6

Issue
When ACLs are enabled and a token has permissions to namespaces individually but no permissions for default, requesting `nomad status` results in a 403 Forbidden.

I expected to get all allocations across all namespaces I have permissions for.

Reproduction steps
Create some namespaces
Create policies that grant read access to namespaces individually
Create a token using those policies
Export the nomad token
Run `nomad status` or similar 

policy

```
namespace "docs" {
  policy = "read"
}

agent {
  policy = "read"
}

node {
  policy = "read"
}

quota {
  policy = "read"
}
```

**Comment by tgross** [comment] 2021-11-10 14:26
Hi @yitbarek123! If I'm understanding the scenario you've described correctly, then right now that's working as designed. See the [`job status` docs](https://www.nomadproject.io/docs/commands/job/status#namespace):

> If set to `'*'`, job and alloc subcommands query all namespaces authorized to user. Defaults to the "default" namespace.

The default for the command is the `default` namespace, which isn't the same thing as `"*"` ("all namespaces I have access to"). When we make API calls with the `"*"`, Nomad has to query each namespace separately, and for users with large clusters this can make common operations very expensive. Not to mention that the name `"default"` ends up being kind of weird in that case, as you'd have to specifically pass it in to filter down to that namespace.

That being said, if we were designing Nomad from scratch today we might have made a different trade off and made `"*"` the default, but when we introduced multi-namespace queries I think we were trying to avoid breaking folks existing workflows with the CLI. I definitely think it's worth revisiting that decision though.

**Comment by yitbarek123** [comment] 2021-11-10 23:30
Thanks @tgross . Now, I'm able to access the docs namespace with the generated token  after adding 

```
namespace "*" {
  policy = "read"
}
```

I think this should be modified https://learn.hashicorp.com/tutorials/nomad/access-control-policies?in=nomad/access-control#acl-policy-specification .

**Comment by tgross** [comment] 2021-11-11 13:52
Good call about the docs. I've opened a PR on the internal repo for Learn with the following diff:

```diff
diff --git a/content/tutorials/nomad/access-control-policies.mdx b/content/tutorials/nomad/access-control-policies.mdx
index 59c3fc89a..1486de6d4 100644
--- a/content/tutorials/nomad/access-control-policies.mdx
+++ b/content/tutorials/nomad/access-control-policies.mdx
@@ -115,7 +115,8 @@ namespace "sensitive" {
 Namespace rules are keyed by the namespace name they apply to. When no namespace
 is specified, the "default" namespace is the one used. For example, the above
 policy grants write access to the default namespace, and read access to the
-sensitive namespace. In addition to the coarse-grained `policy` disposition,
+sensitive namespace. To grant access to all namespaces, you can use the wildcard
+namespace (`"*"`). In addition to the coarse-grained `policy` disposition,
 the `namespace` stanza allows setting a more fine grained list of
 `capabilities`. This includes:
```

**Comment by tgross** [comment] 2021-12-07 21:32
Learn Guide has been updated (it may take a few moments to get deployed).

**Comment by yitbarek123** [comment] 2021-12-08 11:03
Thanks, @tgross.

**Comment by lgfa29** [comment] 2023-02-03 21:38
After some internal discussion we decided to close this one as using the wildcard namespace by default could lead to some undesired accidental actions. Larger clusters with several jobs across multiple namespaces could also suffer from unnecessarily long outputs. 

For those that desire to have wildcard namespace as default can consider setting `export NOMAD_NAMESPACE="*"` as a default shell export. Just be careful to make sure you're performing actions in the intended namespace 😅 

Thank you for the suggestion @yitbarek123 🙂

**Closed by lgfa29** 2023-02-03 21:38 UTC
Labels: type/enhancement, theme/cli, stage/needs-discussion
