### ISSUE TITLE
Duplicated index in allocation name

### ISSUE THREAD

**Issue by pznamensky** [hashicorp/nomad#6829] opened 2019-12-10 13:10 UTC
### Nomad version
Nomad v0.9.4 (a81aa846a45fb8248551b12616287cb57c418cd6)

### Operating system and Environment details
CentOS Linux release 7.7.1908 (Core)
docker-ce-18.03.1

### Issue
Similar to https://github.com/hashicorp/nomad/issues/3698
After updating a nomad job some allocations got the same name.
```
nomad-bm alloc -json | jq '.[] | .Name + " - " + .TaskStates[].State' | grep app | sort | uniq -c
      1 "app.app[0] - running"
      1 "app.app[10] - running"
      1 "app.app[11] - running"
      2 "app.app[1] - running" // duplicate name
      1 "app.app[2] - running"
      2 "app.app[3] - running" // duplicate name
      1 "app.app[4] - running"
      2 "app.app[5] - running" // duplicate name
      1 "app.app[6] - running"
      2 "app.app[7] - running" // duplicate name
      1 "app.app[8] - running"
      1 "app.app[9] - running"
```

### Reproduction steps
1. create a job
2. make changes in nomad file
3. run `nomad run` with that changes
4. check allocation names

### Job file (if appropriate)
```
job "app" {
  datacenters = ["dc1"]
  type = "service"

  update {
    max_parallel = 2
    min_healthy_time = "10s"
    healthy_deadline = "3m"
    canary = 12
    auto_promote = true
  }
  group "app" {
    count = 16
    restart {
      attempts = 10
      interval = "5m"
      delay = "20s"
      mode = "delay"
    }
    task "app" {
      driver = "docker"
      config {
        image = "app:master"
      }
      resources {
        network {
          port "http" {}
        }
      }
      service {
        name = "app"
        port = "http"
        check {
          type     = "tcp"
          interval = "10s"
          timeout  = "5s"
        }
      }
    }
  }
}
```

**Comment by tgross** [comment] 2019-12-10 13:38
Hi @pznamensky! The allocation IDs aren't guaranteed to be unique. The servers make a best-effort attempt to make this value unique from 0 to count-1 but when you have canaries on the task group, there are reused indexes since you have multiple job versions running at the same time.

If you need a unique number for interpolating a value in your application, you can get this by combining the job version and the alloc index (which together should be unique).

**Comment by tgross** [comment] 2019-12-10 13:39
I'm going to close this issue as a duplicate of https://github.com/hashicorp/nomad/issues/5879.

**Closed by tgross** 2019-12-10 13:39 UTC

**Comment by pznamensky** [comment] 2019-12-10 13:51
@tgross thanks for the explanation!

**Comment by pznamensky** [comment] 2019-12-10 16:56
@tgross, sorry for coming back to it, but what is the purpose of ALLOC INDEX? Since there is no guarantees it is unique, probably it would be reasonable to delete it at all. What do you think?
