### ISSUE TITLE
System jobs show degraded and never show stable

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/nomad#13122] opened 2022-05-25 18:23 UTC
### Nomad version
Nomad v1.2.6 (a6c6b475db5073e33885377b4a5c733e1161020c)

### Operating system and Environment details
PhotonOS3

### Issue
We have noticed that the UI provides some confusing data around system jobs. We see our system jobs showing "degraded" even when properly allocated and placed.

When we use the CLI we do see that the job is showing as running though - which is what we would expect.

Also we notice that, unless we explicitly call these steps https://www.nomadproject.io/api-docs/jobs#set-job-stability the system job is never set as stable

### Reproduction steps
1. Create a nomad cluster running at least 1 windows node and 1 linux node2. 
2. Deploy a system job. 

#### Expected Result
Job is marked as stable when all nodes in the cluster have it deployed

Job status in UI is "Running"
Screenshots:
<details>
<img width="1176" alt="Screen Shot 2022-05-25 at 2 09 51 PM" src="https://user-images.githubusercontent.com/46198537/170339005-d4749bf8-312c-416e-9571-21d4232fd676.png">
<img width="1163" alt="Screen Shot 2022-05-25 at 2 09 58 PM" src="https://user-images.githubusercontent.com/46198537/170339004-7fc7a464-d87b-4128-92e1-8859d29d2f5b.png">
<img width="1252" alt="Screen Shot 2022-05-25 at 2 11 58 PM" src="https://user-images.githubusercontent.com/46198537/170339000-77d938c6-032b-42e3-89e7-3320b5cdb42a.png">
</details>

#### Actual Result
CLI Output:
<details>nomad job status --tls-skip-verify fabio
ID            = fabio
Name          = fabio
Submit Date   = 2022-05-25T14:06:12-04:00
Type          = system
Priority      = 50
Datacenters   = dev-setup
Namespace     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group                               Queued  Starting  Running  Failed  Complete  Lost
client-side-load-balancer-linux-group    0       0         4        0       0         0
client-side-load-balancer-windows-group  0       0         1        0       0         0

Allocations
ID        Node ID   Task Group                               Version  Desired  Status   Created    Modified
06dd0645  4ed0e2e9  client-side-load-balancer-windows-group  0        run      running  3m14s ago  9s ago
7cc86935  c16d15dd  client-side-load-balancer-linux-group    0        run      running  3m14s ago  44s ago
9f43f360  31eefc68  client-side-load-balancer-linux-group    0        run      running  3m14s ago  2s ago
c7e5e8a7  8548ece7  client-side-load-balancer-linux-group    0        run      running  3m14s ago  52s ago
df370bb2  1e52bf84  client-side-load-balancer-linux-group    0        run      running  3m14s ago  33s ago`
</details>

### Job file
Redacted/Simplified Job
<details>
job "fabio" {
  region      = "[[ .job_region ]]"
  datacenters = ["[[ .cluster_name ]]"]
  type        = "system"

  update {
    stagger      = "10s"
    max_parallel = 1
  }

  group "client-side-load-balancer-windows-group" {

    constraint {
      attribute = "${attr.kernel.name}"
      value     = "windows"
    }

    network {
      port "ui" {
        static = 29998
      }

      port "lb" {
        static = 29999
      }
    }

    service {
      name = "traefik"

      check {
        name     = "alive"
        type     = "tcp"
        port     = "ui"
        interval = "5s"
        timeout  = "2s"
      }
    }

    task "cleanup-previous-clb" {
      lifecycle {
        hook    = "prestart"
        sidecar = false
      }

      driver = "raw_exec"
      config {
        command = "powershell"
        args    = ["Get-Process | Where-Object { $_.Name -Like \"traefik*\" } | Stop-Process -Force"]
      }
    }

    task "client-side-load-balancer-windows" {
      driver = "raw_exec"

      artifact {
        source = "[[ .default_binary_registry ]]/traefik-[[ .traefik_version ]].exe"
      }

      config {
        command = "traefik-[[ .traefik_version ]].exe"
        args    = ["--configfile", "config/traefik.yaml"]
      }

      resources {
        cpu    = "[[ .traefik.resources.windows.cpu ]]" # Mhz
        memory = "[[ .traefik.resources.windows.memory ]]" # MB
      }
    }

  }

  group "client-side-load-balancer-linux-group" {

    constraint {
      attribute = "${attr.kernel.name}"
      value     = "linux"
    }

    network {
      mode = "bridge"

      port "ui" {
        static = 29998
      }

      port "lb" {
        static = 29999
      }
    }

    service {
      name = "traefik"

      check {
        name     = "alive"
        type     = "tcp"
        port     = "ui"
        interval = "5s"
        timeout  = "2s"
      }
    }

    task "client-side-load-balancer-linux" {

      driver = "docker"

      

      config {
        image = "[[ .default_docker_registry ]]/[[ .traefik_image ]]"
        args  = ["--configfile", "/local/traefik.yaml"]
        mount {
          type     = "bind"
          target   = "/etc/pki/tls/certs/"
          source   = "/etc/pki/tls/certs/"
          readonly = true
        }
      }

      resources {
        cpu    = "[[ .traefik.resources.linux.cpu ]]" # Mhz
        memory = "[[ .traefik.resources.linux.memory ]]" # MB
      }
    }
  }
}
</details>

**Comment by lgfa29** [comment] 2022-06-01 00:25
Hi @idrennanvmware 👋 

Unfortunately that UI element is quite misleading and confusing. What it represents is that some clients didn't receive an allocation for this `system` job, which could mean that there may be something wrong with them (like a misconfiguration, or the task driver being used is not healthy etc.).

In your case I suspect that the clients didn't receive an allocation due to your `constraint`, which is the expected behaviour. So feel free to ignore this if you don't see anything wrong with your clients.

I will leave this issue open for us to improve this element.

**Comment by philrenaud** [comment] 2023-12-13 14:44
Closing — we launched a new job status UI in 1.6.0 that generally handles this better.

**Closed by philrenaud** 2023-12-13 14:44 UTC
Labels: type/enhancement, theme/ui, theme/system-scheduler, stage/accepted
