### ISSUE TITLE
[Question] Wouldn't it make sense to allow vault tokens without  renewal

### ISSUE THREAD

**Issue by dwimberger** [hashicorp/nomad#5353] opened 2019-02-21 20:19 UTC
I could not figure out a way to configure nomad, so that it generates a vault token, without handling the renewal for the token. Is there a way to achieve this through configuration?

The use case I have is a container that expects a short TTL one-time token and handles the token renewal itself (i.e. running consul-template with specific reloading actions for certificate updates and consul value changes).

**Comment by cgbaker** [comment] 2019-03-12 16:00
Makes sense to me. I've filed an issue for this in our internal tracker; I'll bring it up with the team and we can decide whether there's any impediment to doing this. Thanks for the suggestion, @dwimberger .

**Comment by tgross** [comment] 2023-11-01 19:06
Making a note here that starting in [Nomad 1.7.0-beta.1](https://github.com/hashicorp/nomad/releases/tag/v1.7.0-beta.1) we've got a new workflow where Nomad will use workload identities to sign into Vault for purposes of getting Vault tokens for those workloads. 

But we didn't implement a feature to disable renewal, which is something we can probably implement now either based on the `vault` block or the Vault auth configuration itself (ex. if the auth config uses batch tokens). This is a duplicate of the more recent https://github.com/hashicorp/nomad/issues/8690 which has some additional context, so I'm going to close this issue as a dupe.

**Closed by tgross** 2023-11-01 19:06 UTC
Labels: theme/client, theme/vault, stage/needs-discussion
