### ISSUE TITLE
Wrong port advertised to consul

### ISSUE THREAD

**Issue by bondido** [hashicorp/nomad#9347] opened 2020-11-12 23:42 UTC
### Nomad version
v1.0.0-beta2

### Operating system and Environment details
Ubuntu 18.04

### Issue
If I try to run task (docker) with mapped 'to' port and register it to consul, the service (every task instance) is advertised with port from inside the container, not the port dynamically assigned and exposed externally by the docker driver.

### Reproduction steps

- Run below 'simplest of the simplests' job file with nomad v1.0.0-beta2

- Check the task port exposed in nomad UI (28750):

![image](https://user-images.githubusercontent.com/19214089/99009310-25fad280-2548-11eb-9d47-abc30c96842a.png)

- Check the port advertised in consul UI (should be 28750, but it's 80):

![image](https://user-images.githubusercontent.com/19214089/99009377-44f96480-2548-11eb-90f7-7d25888624c5.png)

If I switch to nomad v0.12.7 with exact same job file, expected (dynamic) port is advertised in consul.

### Job file (if appropriate)
```
job "nginx" {
  datacenters = ["dc1"]
  type = "service"
  group "nginx" {

    service {
      name = "nginx"
      port = "nginxport"
      check {
        type     = "http"
        path     = "/"
        interval = "5s"
        timeout  = "5s"
      }
    }

    network {
      port "nginxport" { to = 80 }
    }

    count = 1

    task "nginx-container" {
      driver = "docker"

      config {
        image = "nginx"
        ports = ["nginxport"]
      }

      resources {
        cpu = 200
        memory = 32
      }
    }
  }
}
```

**Comment by nickethier** [comment] 2020-11-13 02:45
Hey 👋 this looks like a duplicate of #9221 and has been fixed in beta3. Thanks for trying out the beta!

**Closed by nickethier** 2020-11-13 02:45 UTC
