### ISSUE TITLE
failed to decode state: unexpected end of JSON input

### ISSUE THREAD

**Issue by lettrung99** [hashicorp/nomad#1170] opened 2016-05-12 07:24 UTC
Hi,

we keep getting the: failed to decode state: unexpected end of JSON input. after restart nomad agent on one of our client node.

### Nomad version
0.30

### Operating system and Environment details
Ubuntu 14.04

### Issue
service nomad restart failed to bring up client agent.  Log indicates:
failed to decode state: unexpected end of JSON input
    Loaded configuration from /var/tmp/nomad/nomad.hcl

Here is our nomad.hcl:

bind_addr = "10.9.23.217"
client_addr = "10.9.23.217"
datacenter =  "dc1"
enable_syslog = true
syslog_facility = "LOCAL0"
log_level = "DEBUG"
data_dir = "/var/nomad"
leave_on_terminate = true
disable_update_check = true

addresses {
    rpc = "10.9.23.217:4647"
}

advertise {
  rpc = "10.9.23.217:4647"
}

client {
    options = {
      "driver.raw_exec.enable" = "1"
      "docker.privileged.enabled" = "true"
    }
    enabled = true
    network_interface = "eth0"
}

### Nomad Client logs (if appropriate)
* failed to decode state: unexpected end of JSON input
    Loaded configuration from /var/tmp/nomad/nomad.hcl
==> Starting Nomad agent...
==> Error starting agent: client setup failed: failed to restore state: 1 error(s) occurred:

**Comment by dadgar** [comment] 2016-05-12 17:10
Hey would you mind posting the full logs? Also if it is possible can you upgrade to Nomad 0.3.2 and see if it is still a problem?

**Comment by c4milo** [comment] 2016-05-31 22:07
I'm running into this as well. It started happening when I:

1. scheduled a system job with multiple tasks, all of which failed. 
2. Modified job definition to remove some tasks
3. Tried to stop current scheduled job. It blocked for a while.
4. At this point the leader got lost due to a crash
5. Attempting to restart Nomad yield a `failed to decode state: unexpected end of JSON input` 

Logs: 

```
May 31 21:39:36 brain2 nomad[2096]: 2016/05/31 21:39:36 [DEBUG] plugin: waiting for RPC address for: /hooklift/bin/nomad
May 31 21:39:36 brain2 nomad[2096]: 2016/05/31 21:39:36 [DEBUG] memberlist: TCP connection from=10.0.54.248:47622
May 31 21:39:36 brain2 nomad[2096]: 2016/05/31 21:39:36 [DEBUG] plugin: nomad: 2016/05/31 21:39:36 [DEBUG] plugin: plugin address: unix /tmp/plugin841586549
May 31 21:39:36 brain2 nomad[2096]: 2016/05/31 21:39:36 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 6)
May 31 21:39:36 brain2 nomad[2096]: 2016/05/31 21:39:36 [INFO] serf: EventMemberUpdate: brain1.us-east-1a.aws.us
May 31 21:39:36 brain2 nomad[2096]: 2016/05/31 21:39:36 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 6)
May 31 21:39:36 brain2 nomad[2096]: 2016/05/31 21:39:36 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 6)
May 31 21:39:36 brain2 nomad[2096]: 2016/05/31 21:39:36 [DEBUG] serf: messageJoinType: brain2.us-east-1e.aws.us
May 31 21:39:36 brain2 nomad[2096]: 2016/05/31 21:39:36 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 6)
May 31 21:39:36 brain2 nomad[2096]: 2016/05/31 21:39:36 [DEBUG] serf: messageJoinType: brain1.us-east-1a.aws.us
May 31 21:39:36 brain2 nomad[2096]: 2016/05/31 21:39:36 [DEBUG] client: allocs: (added 0) (removed 0) (updated 2) (ignore 4)
May 31 21:39:36 brain2 nomad[2096]: 2016/05/31 21:39:36 [DEBUG] client: Not restarting task: dnsmasq because it's destroyed by user
May 31 21:39:36 brain2 nomad[2096]: 2016/05/31 21:39:36 [DEBUG] client: Not restarting task: statsite because it's destroyed by user
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] client: allocs: (added 1) (removed 0) (updated 0) (ignore 6)
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] client: starting task runners for alloc 'beaa276f-e4a5-e153-ef1d-0e4e7def8eb6'
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] client: starting task context for 'statsite' (alloc 'beaa276f-e4a5-e153-ef1d-0e4e7def8eb6')
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] client: allocs: (added 2) (removed 0) (updated 2) (ignore 5)
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] client: starting task runners for alloc '0827c22a-fa7c-dc1c-eb20-70cdce351be7'
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] client: starting task context for 'statsite' (alloc '0827c22a-fa7c-dc1c-eb20-70cdce351be7')
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] client: starting task runners for alloc '1efdfc4c-d9fe-b859-4c9c-807059c294b9'
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] client: starting task context for 'dnsmasq' (alloc '1efdfc4c-d9fe-b859-4c9c-807059c294b9')
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] serf: messageJoinType: brain1.us-east-1a.aws.us
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] plugin: starting plugin: /hooklift/bin/nomad []string{"/hooklift/bin/nomad", "executor", "/hooklift/var/lib/nomad/alloc/beaa276f-e4a5-e153-ef1d-0e4e7def8eb6/statsi
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] plugin: waiting for RPC address for: /hooklift/bin/nomad
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] plugin: nomad: 2016/05/31 21:39:37 [DEBUG] plugin: plugin address: unix /tmp/plugin985478754
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] serf: messageJoinType: brain1.us-east-1a.aws.us
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [WARN] raft: Rejecting vote request from 10.0.180.201:4647 since we have a leader: 10.0.54.248:4647
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] plugin: starting plugin: /hooklift/bin/nomad []string{"/hooklift/bin/nomad", "executor", "/hooklift/var/lib/nomad/alloc/0827c22a-fa7c-dc1c-eb20-70cdce351be7/statsi
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] plugin: waiting for RPC address for: /hooklift/bin/nomad
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] plugin: nomad: 2016/05/31 21:39:37 [DEBUG] plugin: plugin address: unix /tmp/plugin780550864
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] plugin: starting plugin: /hooklift/bin/nomad []string{"/hooklift/bin/nomad", "executor", "/hooklift/var/lib/nomad/alloc/1efdfc4c-d9fe-b859-4c9c-807059c294b9/dnsmas
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] serf: messageJoinType: brain1.us-east-1a.aws.us
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] plugin: waiting for RPC address for: /hooklift/bin/nomad
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] plugin: nomad: 2016/05/31 21:39:37 [DEBUG] plugin: plugin address: unix /tmp/plugin426998696
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [DEBUG] plugin: /hooklift/bin/nomad: plugin process exited
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [ERR] client: failed to start task 'dnsmasq' for alloc '1efdfc4c-d9fe-b859-4c9c-807059c294b9': Failed to mount shared directory for task dnsmasq: no such file or directory
May 31 21:39:37 brain2 nomad[2096]: 2016/05/31 21:39:37 [INFO] client: Not restarting task: dnsmasq for alloc: 1efdfc4c-d9fe-b859-4c9c-807059c294b9
May 31 21:39:38 brain2 nomad[2096]: 2016/05/31 21:39:38 [ERR] client: failed to destroy context for alloc '417a162d-49e7-4049-0b27-458948030eb8': 1 error(s) occurred:
May 31 21:39:38 brain2 nomad[2096]: * remove /hooklift/var/lib/nomad/alloc/417a162d-49e7-4049-0b27-458948030eb8/statsite/usr: directory not empty
May 31 21:39:38 brain2 nomad[2096]: 2016/05/31 21:39:38 [DEBUG] client: terminating runner for alloc '417a162d-49e7-4049-0b27-458948030eb8'
May 31 21:39:38 brain2 nomad[2096]: 2016/05/31 21:39:38 [ERR] client: failed to destroy context for alloc 'bb04eea5-8b21-eb82-a956-28ce70599edc': 1 error(s) occurred:
May 31 21:39:38 brain2 nomad[2096]: * remove /hooklift/var/lib/nomad/alloc/bb04eea5-8b21-eb82-a956-28ce70599edc/dnsmasq/usr: directory not empty
May 31 21:39:38 brain2 nomad[2096]: 2016/05/31 21:39:38 [DEBUG] client: terminating runner for alloc 'bb04eea5-8b21-eb82-a956-28ce70599edc'
May 31 21:39:38 brain2 nomad[2096]: 2016/05/31 21:39:38 [DEBUG] raft-net: 10.0.115.245:4647 accepted connection from: 10.0.180.201:35562
May 31 21:39:38 brain2 nomad[2096]: 2016/05/31 21:39:38 [DEBUG] raft: Node 10.0.115.245:4647 updated peer set (2): [10.0.180.201:4647 10.0.115.245:4647 10.0.54.248:4647]
May 31 21:39:38 brain2 nomad[2096]: 2016/05/31 21:39:38 [DEBUG] client: updated allocations at index 442 (pulled 0) (filtered 9)
May 31 21:39:39 brain2 nomad[2096]: 2016/05/31 21:39:39 [ERR] client: failed to destroy context for alloc '1efdfc4c-d9fe-b859-4c9c-807059c294b9': 2 error(s) occurred:
May 31 21:39:39 brain2 nomad[2096]: * 1 error(s) occurred:
May 31 21:39:39 brain2 nomad[2096]: * failed to delete shared alloc dir "/hooklift/var/lib/nomad/alloc/1efdfc4c-d9fe-b859-4c9c-807059c294b9/dnsmasq/alloc": remove /hooklift/var/lib/nomad/alloc/1efdfc4c-d9fe-b859-4c9c-807059c294
May 31 21:39:39 brain2 nomad[2096]: * readdirent: no such file or directory
May 31 21:39:39 brain2 nomad[2096]: 2016/05/31 21:39:39 [DEBUG] client: terminating runner for alloc '1efdfc4c-d9fe-b859-4c9c-807059c294b9'
May 31 21:39:40 brain2 nomad[2096]: 2016/05/31 21:39:40 [ERR] Error connecting to statsite! Err: dial tcp 127.0.0.1:8125: getsockopt: connection refused
May 31 21:39:45 brain2 nomad[2096]: 2016/05/31 21:39:45 [ERR] Error connecting to statsite! Err: dial tcp 127.0.0.1:8125: getsockopt: connection refused
May 31 21:39:45 brain2 nomad[2096]: 2016/05/31 21:39:45 [DEBUG] client: updated allocations at index 449 (pulled 0) (filtered 9)
May 31 21:39:50 brain2 nomad[2096]: 2016/05/31 21:39:50 [ERR] Error connecting to statsite! Err: dial tcp 127.0.0.1:8125: getsockopt: connection refused
May 31 21:39:55 brain2 nomad[2096]: 2016/05/31 21:39:55 [ERR] Error connecting to statsite! Err: dial tcp 127.0.0.1:8125: getsockopt: connection refused
May 31 21:39:55 brain2 nomad[2096]: 2016/05/31 21:39:55 [DEBUG] driver.exec: started process via plugin with pid: 2199
May 31 21:39:55 brain2 nomad[2096]: 2016/05/31 21:39:55 [DEBUG] driver.exec: started process via plugin with pid: 2200
May 31 21:39:55 brain2 nomad[2096]: panic: nil wait
May 31 21:39:55 brain2 nomad[2096]: goroutine 291 [running]:
May 31 21:39:55 brain2 nomad[2096]: panic(0xf53520, 0xc8201b66c0)
May 31 21:39:55 brain2 nomad[2096]: /usr/local/go/src/runtime/panic.go:481 +0x3e6
May 31 21:39:55 brain2 nomad[2096]: github.com/hashicorp/nomad/client.(*TaskRunner).run(0xc820a7ed20)
May 31 21:39:55 brain2 nomad[2096]: /work/src/github.com/hashicorp/nomad/client/task_runner.go:360 +0xcaa
May 31 21:39:55 brain2 nomad[2096]: github.com/hashicorp/nomad/client.(*TaskRunner).Run(0xc820a7ed20)
May 31 21:39:55 brain2 nomad[2096]: /work/src/github.com/hashicorp/nomad/client/task_runner.go:271 +0x304
May 31 21:39:55 brain2 nomad[2096]: created by github.com/hashicorp/nomad/client.(*AllocRunner).Run
May 31 21:39:55 brain2 nomad[2096]: /work/src/github.com/hashicorp/nomad/client/alloc_runner.go:402 +0x14f9
May 31 21:39:55 brain2 systemd[1]: nomad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 31 21:39:55 brain2 systemd[1]: nomad.service: Unit entered failed state.
May 31 21:39:55 brain2 systemd[1]: nomad.service: Failed with result 'exit-code'.
May 31 21:39:55 brain2 systemd[1]: nomad.service: Service hold-off time over, scheduling restart.
May 31 21:39:55 brain2 systemd[1]: Stopped Nomad Server Service.
May 31 21:39:55 brain2 systemd[1]: Started Nomad Server Service.
May 31 21:39:55 brain2 nomad[2205]: Loaded configuration from /hooklift/etc/nomad.d/nomad.hcl
May 31 21:39:55 brain2 nomad[2205]: ==> Starting Nomad agent...
May 31 21:39:55 brain2 nomad[2205]: ==> Error starting agent: client setup failed: failed to restore state: 1 error(s) occurred:
May 31 21:39:55 brain2 nomad[2205]: * 1 error(s) occurred:
May 31 21:39:55 brain2 nomad[2205]: * failed to decode state: unexpected end of JSON input
```

**Comment by dadgar** [comment] 2016-06-01 00:47
@c4milo Can you paste the state file?

**Comment by c4milo** [comment] 2016-06-01 15:07
oh, my destroyed my cluster but I will test again.

**Comment by a86c6f7964** [comment] 2016-06-27 16:49
I ran into this when I killed a machine through the aws ec2 console instead of draining it first. For me my task state file was EMPTY. I deleted it and got 
```
Jun 27 16:35:38 ip-172-31-1-40.us-west-2.compute.internal nomad[4011]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 27 16:35:38 ip-172-31-1-40.us-west-2.compute.internal nomad[4011]: [signal 0xb code=0x1 addr=0x78 pc=0x564478]
Jun 27 16:35:38 ip-172-31-1-40.us-west-2.compute.internal nomad[4011]: goroutine 1 [running]:
Jun 27 16:35:38 ip-172-31-1-40.us-west-2.compute.internal nomad[4011]: panic(0x1124da0, 0xc82000c070)
Jun 27 16:35:38 ip-172-31-1-40.us-west-2.compute.internal nomad[4011]: /opt/go/src/runtime/panic.go:464 +0x3e6
Jun 27 16:35:38 ip-172-31-1-40.us-west-2.compute.internal nomad[4011]: github.com/hashicorp/nomad/client/driver.GetTaskEnv(0xc8203d8a50, 0xc82014af00, 0x0, 0xc820375a40, 0x0, 0x0, 0x0)
```

So then I deleted the ALLOCATION state file and got
```
Jun 27 16:36:58 ip-172-31-1-40.us-west-2.compute.internal nomad[4376]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 27 16:36:58 ip-172-31-1-40.us-west-2.compute.internal nomad[4376]: [signal 0xb code=0x1 addr=0x50 pc=0x534e4b]
Jun 27 16:36:58 ip-172-31-1-40.us-west-2.compute.internal nomad[4376]: goroutine 108 [running]:
Jun 27 16:36:58 ip-172-31-1-40.us-west-2.compute.internal nomad[4376]: panic(0x1124da0, 0xc82000c070)
Jun 27 16:36:58 ip-172-31-1-40.us-west-2.compute.internal nomad[4376]: /opt/go/src/runtime/panic.go:464 +0x3e6
Jun 27 16:36:58 ip-172-31-1-40.us-west-2.compute.internal nomad[4376]: github.com/hashicorp/nomad/client.(*AllocRunner).Run(0xc8203cf110)
Jun 27 16:36:58 ip-172-31-1-40.us-west-2.compute.internal nomad[4376]: /opt/gopath/src/github.com/hashicorp/nomad/client/alloc_runner.go:354 +0x9b
```
So then I `rm -rf`'d the whole alloc directory, and everything recovered. I think that #1314 should help with some of the Null references getting caught, but not the JSON parsing problem.

It would probably be a good idea to put the path being read https://github.com/hashicorp/nomad/blob/7db2eb03c40ecb4dea100ffb1c60d019ff70dfb1/client/util.go#L104 in the error message. I had to run JQ over all the state files in order to try and find which one was having the problem. Or even just logging which task ID or alloc ID is having errors when the client fails to startup

**Comment by a86c6f7964** [comment] 2016-06-27 20:33
In nomad 0.3.2 if I start nomad with
```
nomad agent -client -data-dir /tmp/nomad-data -server -bootstrap-expect=1
```
Then nomad run the following job
```
job "example-docker" {
  datacenters = ["dc1"]
  group "group" {
    task "redis" {
      driver = "docker"
      config {
        image = "redis:alpine"
      }
      resources {
        cpu = 20
        memory = 200
      }
    }
  }
}
```
Then kill -9 nomad, and truncate the task state json.
```
echo > /tmp/nomad-data/client/alloc/d980e679-9bf6-0f21-9f77-21f0de36dde0/task-86a1b907d54bf7010394bf316e183e67/state.json
```
Then I get
```
==> Error starting agent: client setup failed: failed to restore state: 1 error(s) occurred:

* 1 error(s) occurred:

* failed to decode state: unexpected end of JSON input
```
which as far as I can tell is there error that is happening here. My guess would be because of https://github.com/hashicorp/nomad/issues/1357 having truncated/corrupted the json file.

Keeping the same corrupted state, if I upgrade to nomad `0.4.0-rc2` it continues to give me the same error. If I remove the state json above instead of truncating in then I get.

```
==> Error starting agent: client setup failed: failed to restore state: 1 error(s) occurred:

* 1 error(s) occurred:

* task runner snapshot include nil Task
```
If I remove the alloc state json
```
rm /tmp/nomad-data/client/alloc/d980e679-9bf6-0f21-9f77-21f0de36dde0/state.json
```
then I get
```
==> Error starting agent: client setup failed: failed to restore state: 1 error(s) occurred:

* 2 error(s) occurred:

* alloc_runner snapshot includes a nil allocation
* alloc_runner snapshot includes a nil context
```

I am leaving this ticket open because I have no idea what y'all want the expected behavior to be? I feel like if things get into a corrupted state like this then there should be some kind of operator message to say "please remove alloc <ID>" in order to get started.

Also, personally I feel like nomad should be able to start with corrupted allocs and then delete them garbage collect them, and let the scheduler schedule them on a new machine.

**Comment by dadgar** [comment] 2016-06-28 16:56
@a86c6f7964 Can you create a new issue for gracefully handling corrupt state by cleaning up state with better operator messages. Going to close this one since your atomic swap should fix this issue.

**Closed by dadgar** 2016-06-28 16:56 UTC
Labels: bug, waiting-reply

**Comment by a86c6f7964** [comment] 2016-06-28 20:57
I made the issue #1367
