### ISSUE TITLE
UI: Expired ACL tokens cached and presented when no longer applicable

### ISSUE THREAD

**Issue by michael-strigo** [hashicorp/nomad#17308] opened 2023-05-25 02:20 UTC
### Nomad version
```
Nomad v1.5.6
BuildDate 2023-05-19T18:26:13Z
Revision 8af70885c02ab921dedbdf6bc406a1e886866f80
```

### Issue
When using a ACL token in the UI, once the token is expired, the user stars getting Not Authorised error page instead of falling back to anonymous policy. It seems like the token stays in cookies and kept being presented with every request even though it is expired and/or no longer valid.

![CleanShot_20230525T021230Z@2x](https://github.com/hashicorp/nomad/assets/113865820/0e73d428-7072-4cf8-bbae-c047f04a3094)

The behaviour in the CLI is similar to this (returns 403 error). However, I would argue that with CLIs it is not a big problem  since envars usually are not present in a new terminal session or it's just a manner of `unset NOMAD_TOKEN`. 
In the browser case, the only way out is having to click on that ACL link and re-login or clear cookies in the browser to get back to anonymous policy state.

It would be nice to have a better UX here, since users who are unfamiliar with issue this will escalate to the admins.

### Reproduction steps

0. Have an anonymous ACL policy that allows to list jobs:
  ```hcl
namespace "*" {
  policy = "read"
}
```
1. Create a test token and bind whatever policy you want for it (something that allows you to `list-jobs` for example)
2. Sign in with the token in the UI
3. Delete the token
4. Point browser to the Nomad UI root (https://your_nomad_endpoint/ui)
5. Get the error

#### Expected Result
I expect that access to UI with expired tokens would seamlessly move to being anonymous again.

#### Actual Result
Getting the error page above. Note that clicking the "Jobs" button just loops back to this error page while clicking the "Clients" button takes you to the normal UI console but with auth error message. This is another confusing inconsistency.

**Comment by lgfa29** [comment] 2023-05-29 19:02
Hi @michael-strigo 👋 

Thanks for the report. I believe this is the same problem as reported in https://github.com/hashicorp/nomad/issues/11125, which also relates to https://github.com/hashicorp/nomad/issues/16803.

I think falling back to the anonymous policy would be even more confusing, as it results in a transparent sudden loss of permission, so, like the CLI, an error message is the best the UI can do, but we can improve this error message.

I will close this as a duplicate of https://github.com/hashicorp/nomad/issues/11125, feel free to add any additional context there 🙂

**Closed by lgfa29** 2023-05-29 19:02 UTC
Labels: type/bug, stage/duplicate, theme/ui
