### ISSUE TITLE
memory limit is incorrectly calculated when setting docker shm_size

### ISSUE THREAD

**Issue by aep** [hashicorp/nomad#17425] opened 2023-06-05 13:49 UTC
when specifying shm_size in tasks docker config, the task will be killed immediately after opening shm even when shm is well within the resource limit. nomad log does not indicate anything and kernel OOM is  triggered.

### Nomad version

```
Nomad v1.5.6
BuildDate 2023-05-19T18:26:13Z
Revision 8af70885c02ab921dedbdf6bc406a1e886866f80
```

### Operating system and Environment details

```
docker --version
Docker version 24.0.2, build cb74dfc
```

### Job file (if appropriate)

```
            resources {
                 cpu    = 4000
                 memory = 4000
            }
            driver = "docker"
            config {
                network_mode = "host"
                privileged = true
                shm_size = "2097152000"

```

### Nomad Client logs (if appropriate)

```

Jun 05 13:30:46 uca1h nomad[4044207]:     2023-06-05T13:30:46.239Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=beecb07e-15fb-15fb-575f-bb384e3c8743 task=c-5b122e2b-c32a-47cd-9155-78bcc496a3c4 type=Started msg="Task started by client" failed=false
Jun 05 13:31:25 uca1h nomad[4044207]:     2023-06-05T13:31:25.477Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=beecb07e-15fb-15fb-575f-bb384e3c8743 task=c-5b122e2b-c32a-47cd-9155-78bcc496a3c4 type=Killing msg="Sent interrupt. Waiting 1m0s before force killing" failed=false
```

## dmesg

```
[511805.939244] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=docker-f8548728aaf7cd16c4c1c8146b341f2590ae6bac740246ce5eeff807bd7c7883.scope,mems_allowed=0-1,oom_memcg=/nomad.slice/docker-f8548728aaf7cd16c4c1c8146b341f2590ae6bac740246ce5eeff807bd7c7883.scope,task_memcg=/nomad.slice/docker-f8548728aaf7cd16c4c1c8146b341f2590ae6bac740246ce5eeff807bd7c7883.scope,task=qemu-system-x86,pid=1963061,uid=0
[511805.940173] Memory cgroup out of memory: Killed process 1963061 (qemu-system-x86) total-vm:2178680kB, anon-rss:25160kB, file-rss:56kB, shmem-rss:185076kB, UID:0 pgtables:864kB oom_score_adj:0

```

**Comment by shoenig** [comment] 2023-06-09 15:16
Hi @aep, I haven't been able to reproduce what you're seeing. If I run a simple docker container with `memory` resources large enough to contain the `shm` and the container itself, it works as expected. And I can verify the cgroup is created with `memory.max` set to the expected value.

Are you sure your `shm` and the memory consumed by your container are within the 4000 megabytes of your resources block?

**Comment by tgross** [comment] 2024-11-08 16:38
Doing a little bit of issue cleanup. Looks like we never heard back on this one so I'm going to close it out.

**Closed by tgross** 2024-11-08 16:38 UTC
Labels: type/bug, theme/driver/docker, stage/waiting-reply
