### ISSUE TITLE
Batch jobs fail to update periodic stanza

### ISSUE THREAD

**Issue by volym3ad** [hashicorp/nomad#4526] opened 2018-07-23 14:51 UTC
### Nomad version
Nomad v0.8.3 (c85483da3471f4bd3a7c3de112e95f551071769f)

### Operating system and Environment details
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch

### Issue
When adding `periodic` stanza to batch job I'll get the following error:
```
Error submitting job: Unexpected response code: 500 (rpc error: cannot update non-periodic job to being periodic)
```
Even if I stop batch job and try to run it once more, the error remains.

The only way to make it work is to force GC. Looks like a bug.

### Reproduction steps
Create simple batch job first. Then try to add `periodic` stanza and update job.

**Comment by angrycub** [comment] 2018-07-23 14:59
@volym3ad 

If you run `nomad stop -purge «job name»` you should be able to resubmit the non-periodic job as a periodic job.  This is expected behavior and is to ensure that this change has been intentionally made by an operator.   I will look into improving the documentation around this state.

Please let me know if this resolves this issue for you.  Regards!

**Comment by dadgar** [comment] 2018-07-26 23:43
Closing out since it’s expected and docs have been updated.

**Comment by dadgar** [comment] 2018-07-26 23:43
Closing out since it’s expected and docs have been updated.

**Closed by dadgar** 2018-07-26 23:43 UTC
