### ISSUE TITLE
Binding ports to 0.0.0.0

### ISSUE THREAD

**Issue by wusikijeronii** [hashicorp/nomad#12106] opened 2022-02-23 09:54 UTC
### Proposal
Hello. I want to bind nomad job binding IP binds to 0.0.0.0.

### Use-cases
I have a vrrp interface and I want to reach deployed apps via vrrp but the nomad binds ports to local IP. By default, nomad binds service to an eth interface address. For example, if I have an IP 172.16.0.1 on the eth0 and service with output port 1111 a job will be bound as 172.16.0.1:1111. It will not work even if I tried to connect to 1111 via localhost. 
Default behavior:
Job:
```
job "nginx" {
  datacenters = ["dc1"]
  type = "service"
  group "nginx" {
    count = 3
    task "nginx" {
      driver = "docker"
      config {
        image = "nginx"
        port_map {
          http = 80
        }
        port_map {
          https = 443
        }
      }
      resources {
        cpu    = 100 # 100 MHz
        memory = 128 # 128 MB
        network {
          mbits = 10
          port "http" {
              static = 4444
          }
          port "https" {
              static= 4445
          }
        }
      }
      service {
        name = "nginx"
        tags = [ "nginx", "web", "urlprefix-/nginx" ]
        port = "http"
        check {
          type     = "tcp"
          interval = "10s"
          timeout  = "2s"
        }
      }
    }
  }
}
```
Interface IP:
```shell
curl 172.18.0.3:4444
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to nginx!</title>
    <style>
    html { color-scheme: light dark; }
    body { width: 35em; margin: 0 auto;
    font-family: Tahoma, Verdana, Arial, sans-serif; }
    </style>
    </head>
    <body>
    <h1>Welcome to nginx!</h1>
    <p>If you see this page, the nginx web server is successfully installed and
    working. Further configuration is required.</p>
    
    <p>For online documentation and support please refer to
    <a href="http://nginx.org/">nginx.org</a>.<br/>
    Commercial support is available at
    <a href="http://nginx.com/">nginx.com</a>.</p>
    
    <p><em>Thank you for using nginx.</em></p>
    </body>
    </html>
```
localhost:
```shell
curl localhost:4444
curl: (7) Failed to connect to localhost port 4444: Connection refused
```
vrrp:
```shell
curl vrrp.router:4444
curl: (7) Failed to connect to vrrp.router port 4444: Connection refused
```
### Attempted Solutions
I have tried:
```json
"Networks": [
              {
                "Mode": "",
                "Device": "",
                "CIDR": "",
                "IP": "0.0.0.0",
                "Hostname": "",
                "MBits": 0,
                "DNS": null,
                "ReservedPorts": [
                  {
                    "Label": "http",
                    "Value": 80,
                    "To": 0,
                    "HostNetwork": "0.0.0.0"
                  },
                  {
                    "Label": "https",
                    "Value": 443,
                    "To": 0,
                    "HostNetwork": "0.0.0.0"
                  }
                ],
                "DynamicPorts": null
              }
            ],
```
I also tried to create a new topic on the https://discuss.hashicorp.com/
https://discuss.hashicorp.com/t/how-to-transfer-ports-to-0-0-0-0/33340
https://discuss.hashicorp.com/t/nomad-with-keepalived-controlled-interfaces/16014
Looks like this problem has been around for over 2 years.

**Comment by tgross** [comment] 2022-03-07 19:50
Hi @wusikijeronii! This does appear to be a duplicate of #8577, which isn't currently on the roadmap. The best way to encourage it to get on the roadmap is to give it some 👍 on that issue and, if you have new use cases that aren't being discussed there, bring them up.

(As an aside, the `network` block that you're using on the `task.resources` is long-deprecated. You'll need to move that to `group.network` no matter what you try to do next.)

I'm going to close this issue as a duplicate.

**Closed by tgross** 2022-03-07 19:50 UTC
Labels: type/enhancement

**Comment by alshdavid** [comment] 2022-03-21 13:38
So if I want to use nomad with my workflow, I need to have a reverse proxy exposing services from the cluster to the world?

**Comment by valodzka** [comment] 2022-05-15 10:52
@alshdavid and anyone looking for solution: it is possible to achieve effect similar to bind 0.0.0.0 via using network mode bridge (requires cni plugins installation):

```
  network {
    mode = "bridge"
    ...
  } 
```
