### ISSUE TITLE
Nomad client acl token permission denied

### ISSUE THREAD

**Issue by artyomturkin** [hashicorp/nomad#10603] opened 2021-05-17 15:13 UTC
### Nomad version
Nomad v1.0.5 (0b870631cfa0c8e52cf698d7a7cc7989fbaec576)

### Operating system and Environment details
Ubuntu 20.04

### Issue
Client tokens fail to submit a job, while plan works fine. When deploying with management token everything works fine/

### Reproduction steps
policy.hcl
```hcl
namespace "*" {
  policy = "write"
}

node {
  policy = "write"
}

agent {
  policy = "write"
}

operator {
  policy = "write"
}

plugin {
  policy = "list"
}
```

#### Expected Result
Job is deployed

#### Actual Result
Error submitting job: Unexpected response code: 403 (Permission denied)

### Nomad Server logs (if appropriate)

```
2021-05-17T15:05:40.739Z [DEBUG] http: request failed: method=PUT path=/v1/jobs?namespace=experiments®ion=almaty error="Permission denied" code=403
```

**Comment by jsosulska** [comment] 2021-05-22 19:06
Hi @artyomturkin !

I attempted to replicate this using the dev mode configuration, but I was unable to reproduce your issue.

I attempted to replicate this locally by:

1. Set up a region via launching with the CLI with sudo power, and make sure docker was running. Here I'm using the management token.
`sudo nomad agent -dev -acl-enabled -region 'dev.local'`
2. Manually applied the namespace "dev", but kept the default DC, `"DC1.`
`nomad namespace dev`
4. Used `nomad job init -short` to create a job, and adjusted the job file to include region, datacenter, and namespace.
4. Created a new policy using the file above 
```
nomad acl policy apply 10306 10306_repro_policy.hcl
nomad acl token create -name 10306 -policy 10306
```
5. Switched the token in my environment variable, and planned the job. No issues on plan or submit.
I verified this worked as of the most recent release.

Could you also provide your job file?
Can you include the commands used to submit the job?
Can you let me know if I missed any steps needed for reproducing the issue? 
Hope this helps!

**Comment by ignasbernotas** [comment] 2021-06-06 22:37
I'm getting the same issue when deploying with Levant and Nomad v1.1.0 (2678c3604bc9530014208bc167415e167fd440fc). Unless I use a management token, it fails.
```
docker run -e "NOMAD_CACERT=/certs/nomad-ca.pem" \
  -e "NOMAD_CLIENT_CERT=/certs/nomad-ci.pem" \
  -e "NOMAD_CLIENT_KEY=/certs/nomad-ci-key.pem" \
  -e "NOMAD_ADDR=https://xxx:4646" \
  -e "NOMAD_TOKEN=xxx" \
  -v /var/lib/nomad/certs:/certs \
  -v /var/lib/nomad/jobs:/jobs \
  --rm --name levant \
  hashicorp/levant:latest \
  levant deploy -log-level=DEBUG -ignore-no-changes=true /jobs/api.nomad
```

```
2021-06-06T22:19:35Z |DEBU| levant/plan: triggering Nomad plan
2021-06-06T22:19:35Z |DEBU| levant/deploy: running dynamic job count updater job_id=api
2021-06-06T22:19:35Z |INFO| levant/deploy: using dynamic count 2 for group api job_id=api
2021-06-06T22:19:35Z |INFO| levant/deploy: triggering a deployment job_id=api
2021-06-06T22:19:35Z |ERRO| levant/deploy: unable to register job with Nomad error="Unexpected response code: 403 (Permission denied)" job_id=api
2021-06-06T22:19:35Z |ERRO| levant/deploy: job deployment failed job_id=api
```

`ci.policy`
```
namespace "default" {
  policy = "read"
  capabilities = ["submit-job","dispatch-job","read-logs", "read-job"]
}
```

P.S. Maybe someone could tell me what would be a good bare minimum ACL policy configuration for CI deployment with Levant? I could not find anything in Google or Nomad/Levant docs regarding this. Thanks!

**Comment by artyomturkin** [comment] 2021-07-22 09:19
I've been using host volumes in the job. Forgot that they needed explicit permissions in the policy. After adding them? everything works as expected.

```hcl
host_volume "ca-certificates" {
  policy = "read"
}
```

**Comment by tgross** [comment] 2021-11-08 21:38
Doing some issue cleanup and it looks like this is resolved as of https://github.com/hashicorp/nomad/issues/10603#issuecomment-884771044. Going to close it out.

**Closed by tgross** 2021-11-08 21:38 UTC
Labels: type/bug, stage/waiting-reply, theme/auth
