### ISSUE TITLE
Registering Jobs Takes about 0.2s

### ISSUE THREAD

**Issue by ethankhall** [hashicorp/nomad#3252] opened 2017-09-19 17:54 UTC
## Use case that we're testing
We are trying to see how well our build jobs can be scheduled onto nomad. We have an average of 2 QPS, but will burst to 5000 QPS from time to time. Currently we're creating independant jobs each with a single task (we're not parameterizing). We may be able to pull out templates from the job and break them into several parameterized jobs, but that's not how we're testing it at the moment.

There are 3 nomad masters, and 97 nomad workers.
### Nomad version
Output from `nomad version`
`Nomad v0.6.3`

### Operating system and Environment details
RHEL 7.3

### Issue
Registering a job takes about 0.2s, so we're seeing a serial QPS of 5 job creations a second. Comparing this to some of the other schedulers we're testing with it seems relatively slow.

### Reproduction steps
Source code for example in: https://gist.github.com/ethankhall/2d81c63d6fe568602da26b1bebf5b00f

This should need the JDK, logback, and the nomad java api's.

Please let us know if this is expected or if you need more info.

**Comment by schmichael** [comment] 2017-09-25 17:40
Thanks for the detailed bug report! 5 QPS is pretty unacceptable, so we'll definitely investigate.

I did a quick test locally using the root Vagrantfile, 1 server, 1 client, and submitting 100 *raw* exec echo jobs. That hit ~40 QPS (2.5 seconds for the full run), but the difference between our test runs is obviously too substantial to draw any conclusions. I was just hoping to find an easy repro. :)

If you're able to run some more tests before I get a chance to, here are some things to watch or try:

1. Can you use a threadpool to submit jobs in parallel? That should help mitigate latency between the host you're submitting from and the server as well as allow each server to create evaluations in parallel.
2. Do you have any CPU stats from the Nomad nodes? I'm curious if we're CPU bound anywhere.
3. Submitting jobs directly to servers (instead of clients/workers) cuts at least one network roundtrip out of the equation.

**Comment by dadgar** [comment] 2017-09-25 17:43
@schmichael @ethankhall Just to update everyone involved, we had a chance to talk about this at HashiConf. One of the larger issues seems to be using spinning disk for the servers. All of the above suggestions are valid as well.

Would love to hear an update when the test config is updated.

**Comment by ethankhall** [comment] 2017-10-04 23:25
Sorry for the delay on responding. We moved the work dir into a ram disk and we moved from 5 to 6 QPS.

@schmichael Responding to your comments:
1) In a real world situation, we would submit then in a thread pool and submit the work, but that would just mask the issue.
2) I don't ATM, but all the machines were idle when we started.
3) We were submitting to servers for the requests.

I believe it's a configuration thing, based on what I understand about Nomad it seems like that's the only thing that makes since.

**Comment by dadgar** [comment] 2017-10-05 19:02
@ethankhall I tested just locally using a dev agent and got the following results: https://gist.github.com/dadgar/6ef7868469aced2865079999417b618d
Roughly: 272.5 QPS

When testing running the server as follow `nomad agent -server -bind 192.168.74.149 -data-dir /tmp/nomad -bootstrap-expect 1` in a VM with slow filesystem I still saw 150+ QPS. 

This does point to a configuration issue. I would try to see if you are network or IO bound during your tests. I would also double check that you configured that `data-dir` to be on the RAM disk

**Comment by dadgar** [comment] 2017-11-17 00:37
@ethankhall Should we go ahead and close this one? None of us were able to reproduce and I believe I heard you all had got the performance up

**Closed** 2017-11-17 16:39 UTC
Labels: needs_investigation, performance
