### ISSUE TITLE
[enhancement] job_timeout in batch jobs

### ISSUE THREAD

**Issue by MorphBonehunter** [hashicorp/nomad#3145] opened 2017-08-31 10:27 UTC
It would be a good extension for the batch job system to define an max running time for the job.
For example if i define an periodic job which runs */15 i would like to have the ability to define an `job_timeout` (with no default) of "5m" after which the job gets killed and marked failed.
This prevents "hanging" scripts and in case of prohibit_overlap that the job isn't executed on the next schedule.

**Comment by jippi** [comment] 2017-08-31 10:34
As mentioned in Gitter chat, the `timeout` binary in `coreutils` can do this inside the container if yoi need a fix right now.

`timeout 5 /path/to/slow/command with options`

**Comment by MorphBonehunter** [comment] 2017-08-31 11:24
@jippi thanks for your suggestion ( i doesn't realize in gitter because the mention is to someone else :smile: ) and i will check this.
However i think this could be an usefull addition to nomad, so i've decide to open this issue.

**Comment by jippi** [comment] 2017-08-31 11:54
I agree having it native to Nomad would be nice :)

**Comment by dadgar** [comment] 2017-08-31 16:45
Hey closing this as a duplicate of https://github.com/hashicorp/nomad/issues/1782

**Closed by dadgar** 2017-08-31 16:45 UTC

**Comment by MorphBonehunter** [comment] 2017-08-31 16:59
sorry again, another issue i could not find that there is already an open one :scream:
