### ISSUE TITLE
goroutine leaks when making nomad api cals

### ISSUE THREAD

**Issue by tantra35** [hashicorp/nomad#6620] opened 2019-11-05 13:39 UTC
### Nomad version
0.8.x - latest nomad version

### Issue
We making nomad api calls to collect telemetry for jobs and time to time see that goroutine leaks appear on control plane(we remove them by restartting nomad with leaked goroutines)

![img-2019-11-05-16-32-43](https://user-images.githubusercontent.com/1377084/68212295-4cf3ff80-ffea-11e9-90e8-24a0423bbff9.png)

This happens in yamux code, look on our goroutines which we took with delve debugger
[glist.txt](https://github.com/hashicorp/nomad/files/3809187/glist.txt)

also we get some backtrace of some goroutines with most typical behavior
[bt-1119376.txt](https://github.com/hashicorp/nomad/files/3809198/bt-1119376.txt)
[bt-821359.txt](https://github.com/hashicorp/nomad/files/3809199/bt-821359.txt)
[bt-886686.txt](https://github.com/hashicorp/nomad/files/3809200/bt-886686.txt)

Backtraces was collected on nomad-0.9.6

**Comment by tgross** [comment] 2019-11-05 13:54
Thanks for reporting this, @tantra35! I'm going to take a look through the logs you've provided and see if I can replicate this.

**Comment by tantra35** [comment] 2019-11-05 14:08
@tgross Its very hard to reproduce, for example we cant simulate this on test stand only on production system  :-(

**Comment by tgross** [comment] 2019-11-05 14:14
Understood... but we'll figure it out! 😀

Just so that I understand the scenario you have here: you're hitting the [`/client/allocation/:alloc_id/stats`](https://www.nomadproject.io/api/client.html#read-allocation-statistics) HTTP API on the server?

**Comment by tantra35** [comment] 2019-11-05 15:39
@tgross yes

**Comment by tantra35** [comment] 2019-11-05 19:56
@tgross yes the situation is the same 

![изображение](https://user-images.githubusercontent.com/1377084/68241185-49c73680-001f-11ea-9bea-5195f95b8e98.png)

**Comment by tgross** [comment] 2019-11-05 21:16
In #4604 you reported that these were mostly sockets in `CLOSE_WAIT`, and that the problem was mostly occurring when a server was talking cross-region to the client. Our clients initiate the connection to the servers so if the server has sockets in `CLOSE_WAIT` that suggests the client is sending `FIN` back to the server but the server isn't wrapping up the connection from its end.

I'm trying to see if I can reproduce the behavior but haven't yet done so successfully. Right now that environment looks like the following:
- I've stood up a Nomad cluster using the Terraform configs we use for e2e testing, with the change that there's only 1 client node.
- I'm running one job (the Connect demo).
- I'm periodically checking the goroutine `http://$NOMAD_ADDR/debug/pprof/` and `http://$NOMAD_ADDR/debug/pprof/goroutine?debug=1`
- I'm running a script from my laptop to hit the allocation stats endpoint repeatedly:

```sh
#!/bin/bash
while true
do 
  curl -so /dev/null "$NOMAD_ADDR/v1/client/allocation/$ALLOC_ID/stats"
  echo -n "."
  sleep 1
done
```

Then on the client I'm using [`tc`](http://manpages.ubuntu.com/manpages/xenial/man8/tc.8.html) to disrupt the network traffic by inducing packet loss or delay. So far I haven't come up with a scenario that's causing it, but I've got a few more I want to try out tomorrow before I give up on this avenue.

---

I also think that the suggestion you had in the earlier issue to add the RPC timeout is probably right (but maybe not enough, as you noted), but I want to have a reproduction before I go changing things in Nomad. There's a deadline configuration in yamux we're not using.

**Comment by tgross** [comment] 2019-11-06 16:52
One of the complicating factors for my tests yesterday was that if the Nomad client loses connectivity with a server, it'll establish a connection with another server. I've corrected this with a new test setup where I'm running the following script on the client:

```bash
#!/bin/bash
# must be run as root

SERVER_IPS=($(curl -s localhost:4646/v1/status/peers | jq -r '.[] | split(":") | .[0]'))

echo "dropping traffic from ${SERVER_IPS[0]} ${SERVER_IPS[1]}"
echo "shaping traffic from ${SERVER_IPS[2]}"

iptables -I INPUT -s ${SERVER_IPS[0]} -j DROP
iptables -I INPUT -s ${SERVER_IPS[1]} -j DROP

# create 3 queue-discipline classes
tc qdisc add dev eth0 root handle 1: prio

# configure these classes, with the low-priority band being set to drop 25% of
# packets with 25% correlation. this should be enough to cause TCP connections
# that we send thru that queue to break and force the Nomad client to try to 
# reconnect
tc qdisc add dev eth0 parent 1:1 handle 10: sfq
tc qdisc add dev eth0 parent 1:2 handle 20: sfq
tc qdisc add dev eth0 parent 1:3 handle 30: netem loss 25% 25%

# filter traffic from server 3
tc filter add dev eth0 protocol ip parent 1:0 prio 3 u32 \
     match ip dst ${SERVER_IPS[2]}/32 flowid 1:3

```

After verifying that we're seeing roughly 25% packet loss from the last server and that this is the only server the client can connect to, I set my `NOMAD_ADDR` to the same server (and in a second attempt, a different server so that we exercise the forwarding code paths) and tried my `curl` loop again. The HTTP calls to the stats endpoint do slow down and sometimes timeout in that situation. But the number of goroutines remains steady.

I've even ramped up to 50% and 75% packet loss to see if that could recreate the situation, but at higher packet loss levels the Nomad servers just mark the node as down and we get "no path to node". I eventually start getting lingering `FIN_WAIT1` and `FIN_WAIT2` at that level of degradation but not very many.

I'm going to leave this to soak for a couple hours to see if anything changes, but at this point I think my hypothesis that this has to do with simple network degradation is incorrect -- or at least more complex than that.

@tantra35 it might help if you can answer a few questions:
* Is there anything unusual about the network topology in your production environment that I might be missing here?
* Which OS are you deploying onto? Maybe there's a network tunable I'm not considering.
* When you see sockets in `CLOSE_WAIT`, are they sockets that were opened with the

**Comment by tantra35** [comment] 2019-11-07 21:13
@tgross we placed inside aws cloud and does't see any network problems most time and use ubuntu 16.04lts as our main distro, with minimal turning of network parameters

**Comment by tgross** [comment] 2019-11-08 14:28
I agree that the lack of timeouts is one issue. The blocked goroutines should all continue once we have some timeouts in place but I want to have a clear mechanism of the bug so that we're not just pushing the problem to some other place in the stack.

When you're talking about a patched version, you're referring to the patch from #4604, or is there some other patch you're using here?:

```go
sc.stream.SetDeadline(time.Now().Add(10 * time.Second))
```

---

For the file `2.txt` you've sent, is this a particular client node that's been demonstrating this problem? Does this happen with any other client node? That EC2 instance has impressive uptime!

In #4604 you mentioned there was another region involved and that you weren't seeing the problem with same-region metrics collection. So the problem may be part of how we're handling RPC fowarding. If the diagram below describes this topology correctly, are you seeing the goroutine increase on Server A or Server B?

```
┌────────────────────────┐     ┌───────────────────────┐ 
│        region A        │     │       region B        │
│                        │     │                       │
│  metrics ──> server A ─┼─────┼─> server B ──> client │
│  scraper               │     │                       │
└────────────────────────┘     └───────────────────────┘ 
```

**Comment by tantra35** [comment] 2019-11-11 09:10
@tgross Oh, it's been a long time since, and we abandoned such a scheme. So for now we doesn't do any cross region queries for statistic, and have a collecting daemon in each region. That's why we removed patch with timeouts we hoped that exactly cross region queries was a real reason of hung connections, but we were wrong, as practic shows

As for the patch with timeouts in #4604  you absolutely right, but we were extended this timeout to 5 minutes

As for the `2.txt` file in my prevoiuse post I posted it for the company(its my mistake), and it is irrelevant, and demonstrates other strange behavior in nomad 0.8.6, which is now on 0.9.6 is not reproduced

**Comment by tgross** [comment] 2019-11-18 16:17
@tantra35 I'd still like to see if I can reproduce this. One of the avenues I'm investigating is whether the number of allocations involved is very high and that's exposing some kind of deadlocking condition we'd normally never hit in development environments. You mentioned this only happens in production -- roughly how many allocations per node is this? Is the HTTP client you're using to hit the API querying all the allocations as once, or sequentially?

**Comment by tantra35** [comment] 2019-11-20 10:22
@tgross Hm, and doesn't think that this is key of problem, due in our case on node launches 5-10 allocations average. Also i must said that this happens very strange in time, i mean that can be month and we doesn't see any problems, but some times this can be fews days continusly

**Comment by tantra35** [comment] 2019-12-21 15:51
@tgross hello we think that the real problem in our case is exactly leader switch, and the goruntine increase is consequence. look  at follow screenshorts

![изображение](https://user-images.githubusercontent.com/1377084/71310170-1b13ec80-2422-11ea-9667-636be5f54b45.png)

as you can see at 15:44 nomad switch leader, and at this point something went wrog and `ip-172-27-5-61` which begins leader for small time that quickly lost leadership

![изображение](https://user-images.githubusercontent.com/1377084/71310241-d50b5880-2422-11ea-8e13-e64bd8adf681.png)
 
and doesn't return to raft follower state

**Comment by tantra35** [comment] 2019-12-22 07:44
just reproduced this again and we got sockets stats(`ss -nt`) and found 

```
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:38246
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:51068
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:36990
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:43642
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:33904
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:41554
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:51460
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:55616
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:55814
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:37494
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:35766
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:47904
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:39322
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:34362
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:36104
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:49902
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:53078
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:43852
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:59284
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:47666
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:54228
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:41550
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:60240
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:47136
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:40756
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:51652
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:49424
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:49698
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:50358
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:41432
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:39566
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:58876
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:53524
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:38688
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:50508
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:48870
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:43610
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:35488
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:52040
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:52048
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:59254
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:36682
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:34342
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:60586
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:48054
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:59092
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:55362
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:53350
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:49828
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:50510
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:42262
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:46204
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:49416
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:53282
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:53546
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:58590
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:54466
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:53510
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:53962
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:56566
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:51554
ESTAB      0      0                    ::ffff:172.27.5.61:8300                            ::ffff:172.27.0.113:38434
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:35716
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:56240
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:38084
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:46098
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:60176
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:39866
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:53924
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:39558
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:34628
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:36428
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:56468
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:55304
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:53460
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:37754
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:40960
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:51934
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:44364
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:41006
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:47722
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:59832
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:55414
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:49160
ESTAB      0      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:38386
ESTAB      0      0                    ::ffff:172.27.5.61:4647                            ::ffff:172.27.0.212:38798
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:50972
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:53728
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:38264
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:52760
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:34454
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:52726
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:50460
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:41218
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:43300
ESTAB      0      0                    ::ffff:172.27.5.61:8300                              ::ffff:172.27.0.6:30932
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:45744
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:53640
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:35020
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:51466
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:55266
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:49838
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:43630
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:51916
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:58798
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:45956
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:55448
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:41762
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:36604
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:57096
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:55940
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:34530
CLOSE-WAIT 1      0                    ::ffff:172.27.5.61:4647                             ::ffff:172.27.3.86:47538
```

**Comment by tgross** [comment] 2020-01-06 13:54
> 1. presenting 2 leaders at the same time(with this we fight in 0.8.6 with patch described in #4749, and it appear again for us as in 0.9.x we doesn't apply this modifications)

That's a pretty serious correctness issue; I'm going to re-open #4749 so we can follow up on that one. Looks like stalebot got overzealous.

> 2. hung yamux connections(reasons of this we cant find yet)

I don't see an obvious way this would be related to multiple leaders, but if we can get into that state there's a whole mess of problems that'll fall out of that because having exactly one leader is one of our core assertions. If there's a way we could replicate the leader issue it might give us more insight.

> 3. absolutely ignoring of hashicorp team of reports from community. The only reason why this happens i can imagine to myself is that nomad not very priority product

I definitely understand your frustration with this. For what it's worth, the Nomad engineering team has been staffed up quite a bit in the last year (especially in the last 6 months). And my particular focus has been around reliability and stability issues. Thanks so much for how much you've been willing to contribute back in extensive bug reports! We'll get there!

**Comment by tgross** [comment] 2020-01-06 20:30
Unfortunately it looks like we're missing the original election failover for node 172.27.5.61 in the logs you've provided -- we can see that the node is already in a flapping state and trying to execute leader operations (and failing to do so because it's not the raft leader). It probably doesn't matter how we got into the flapping state in the first place; there's plenty of networking or other reasons why a node might flap and we need to account for that. Like in #4749 we can also see that the node has lost connectivity or has intermittent connectivity to the other two server nodes. It manages to win an election but then times out on heartbeats ~500ms later.

From the output of `ss` we can see that the buggy node 172.27.5.61 has a bunch of connections in `CLOSE_WAIT` and all of them are from 172.27.3.86, the new leader. So the pile-up of goroutines isn't because of connections w/ dead nodes (clients make inbound connections with servers anyways, not the other way around, so even if the server somehow had stale data that wouldn't cause a bunch of outbound connections).

That narrows down the places to look quite a bit in terms of trying to reproduce. While I work on that, if you can reproduce while running with debug mode on, could you dump the output of `curl`ing `/debug/pprof/goroutine?debug=2` to a file?

**Comment by tgross** [comment] 2020-01-07 21:16
I've been able to get similar log outputs from a test cluster of 3 servers by running the script below on one of the machines. I've also tried adding extra load (by running CPU stress tests on AWS `t2` class machines, to trigger CPU throttling). I'm then polling `/debug/pprof/goroutine?debug=1` to get the count of goroutines. Leadership flaps and forward progress is slow, but unfortunately this hasn't resulted in a runaway number of goroutines and network connections in `CLOSE_WAIT`

@tantra35 you've mentioned a couple times both 0.8.x and 0.9.x -- is this happening similarly on both clusters? If not, what's the exact version of the cluster involved? And is there any chance I can get debug-level logs? The raft system does some logging there that might be helpful to us.

```bash
#!/bin/bash
set -e

trap cleanup err exit

cleanup() {
    echo
    echo "removing queue disciplines!"
    sudo tc qdisc del dev eth0 root
}

MY_IP=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/')
SERVER_IPS=($(curl -s localhost:4646/v1/status/peers | jq -r '.[] | split(":") | .[0]'))

# clear any old queue disciplines, if any
sudo tc qdisc del dev eth0 root > /dev/null 2>&1 || true

echo "Hit Ctrl-C to exit..."

while :
do
    # configure queue discipline classes
    sudo tc qdisc add dev eth0 root handle 1: prio
    sudo tc qdisc add dev eth0 parent 1:1 handle 10: sfq
    sudo tc qdisc add dev eth0 parent 1:2 handle 20: sfq
    sudo tc qdisc add dev eth0 parent 1:3 handle 30: netem loss 75% 75%

    # attach the filter to the peers
    for SERVER_IP in ${SERVER_IPS[@]}; do
        if [[ "$SERVER_IP" != "$MY_IP" ]]; then
            sudo tc filter add dev eth0 protocol ip parent 1:0 prio 3 u32 \
               match ip dst "${SERVER_IP}/32" flowid 1:3
        fi
    done
    echo -n '.'
    sleep 2

    sudo tc qdisc del dev eth0 root
    sleep 5

done
```

**Comment by tantra35** [comment] 2020-01-10 09:52
@tgross 

1. our t2 instances never was overloaded, so they never been throttled(despite this we set on them Unlimited (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-performance-instances-unlimited-mode.html))

2. If you have similar logs, that means that you must doesnt see pairs of messages: 
```
nomad: cluster leadership lost
nomad: cluster leadership acquired"
```
As you doesn't see any leaked sockets, I am 100%  sure, that in your logs you can see this pair, and this is mean that it is not our case. At some moment we doesn't see `cluster leadership lost` despite wee see in logs that raft leadership is lost

3. I think that your miss fact that raft leadership detecting by nomad by reading buffered channel  leaderCh (https://github.com/hashicorp/nomad/blob/master/nomad/server.go#L1237), with buffer count 1, and when we overload this buffer we have that all raft stuff code will block, so there must happens multiple flapping in that buffer to overlap it. So may be the key to reporduce is to disable this buffering(i doesn't check this idea), also from this can may follow a solution - increase this buffer tho something  more bigger

4. We Apply patch described in #4749, and now doesn't see any problems about 19 days(since 22.12.2019, and graph you can see that before we have issues more often, ofcouce this is not mean that we solve issue fully - need more time to check):
![изображение](https://user-images.githubusercontent.com/1377084/72143209-56f9fc00-33a7-11ea-8e68-0bb9469e86a0.png). So fo now not possible to provide profiling or debug logs

**Comment by tgross** [comment] 2020-01-10 14:02
> If you have similar logs, that means that you must doesnt see pairs of messages:
> ```
> nomad: cluster leadership lost
> nomad: cluster leadership acquired"
> ```
> As you doesn't see any leaked sockets, I am 100% sure, that in your logs you can see this pair, and this is mean that it is not our case. At some moment we doesn't see cluster leadership lost despite wee see in logs that raft leadership is lost


I just want to make sure I understand very clearly:
* In my test, I do see both those log messages and do not see goroutine leaks.
* You do see `nomad: cluster leadership acquired` but you never see the `nomad: cluster leadership lost` log on any of the servers?

**Comment by tantra35** [comment] 2020-01-10 20:50
We doesn't see `nomad: cluster leadership lost` on nomad server with leaked sockets, other servers behave as expected

**Comment by filip-vt** [comment] 2020-01-13 12:09
Just wanted to add that we are experiencing the same issue. We're making calls to `/v1/client/allocation/<alloc-id>/stats` and once in a while the call just hangs (does not timeout or return any other error). Besides the fact that the Java SDK does not have any timeout implemented (a problem on its own), the only solution is to do a rolling restart of the nomad servers. For us it happens about once every few days, but thanks to @tantra35's debugging info, I now understand a little bit more why. Not sure if I can provide more info. For now, I was unable to reproduce it.

**Comment by tantra35** [comment] 2020-01-16 12:43
@filip-vt if you full enough brave jeday, you can try our binary https://yadi.sk/d/QnKOvsBaY4fSog
linux only

**Comment by tgross** [comment] 2020-03-03 19:04
@tantra35 I just wanted to follow up with you on this issue. On Feb 19 we shipped [0.10.4](
https://github.com/hashicorp/nomad/blob/master/CHANGELOG.md#0104-february-19-2020). My colleague @notnoop landed a fix to leadership flapping (https://github.com/hashicorp/nomad/pull/6977), which combined with the RPC fix we shipped in 0.10.3 we believe should fix the problems in this issue and in #4749

**Comment by tantra35** [comment] 2020-03-05 14:47
@tgross We saw all changes that was maded by hashicop team. Good work, but at now we still use 0.9.7(with our custom patch) version due we not actually believe that 0.10.4 is ready for production(we must backport https://github.com/hashicorp/nomad/pull/6324 to 0.10.4), also problem with leaked goroutines solved only partial (we eliminate raft problems, but not eliminate https://github.com/hashicorp/nomad/issues/4604, in that issue i provided more info that we found)

**Comment by tgross** [comment] 2020-03-05 16:06
Thanks @tantra35. I'm going to close this issue and we can follow up on any remaining issues in #4606.

**Closed by tgross** 2020-03-05 16:06 UTC
Labels: bug, raft
