### ISSUE TITLE
Tooltip is covered by left navbar in the web UI

### ISSUE THREAD

**Issue by TheRevenantStar** [hashicorp/nomad#5796] opened 2019-06-10 00:10 UTC
### Nomad version
Nomad v0.9.1 (4b2bdbd9ab68a27b10c2ee781cceaaf62e114399)
### Operating system and Environment details
Ubuntu Server 18.04.2 LTS
### Issue
When hovering over the "Rescheduled" icon in the web UI, the left navbar covers it.
See [Image](https://imgur.com/bho8lNC).
### Reproduction steps
Submit any job that will be rescheduled (due to failure) and hover over the rescheduled icon in the "Recent Allocations" box.
### Job file (if appropriate)
N/A
### Nomad Client logs (if appropriate)
If possible please post relevant logs in the issue.
N/A

**Comment by DingoEatingFuzz** [comment] 2019-06-10 00:21
Hi @TheRevenantStar, thank you for the bug report!

This appears to be a duplicate of #5705 and is fixed in 0.9.2.

**Closed by DingoEatingFuzz** 2019-06-10 00:21 UTC
