### ISSUE TITLE
nil pointer dereference when merging resources when recovering a task on startup

### ISSUE THREAD

**Issue by dbresson** [hashicorp/nomad#2320] opened 2017-02-15 19:29 UTC
### Nomad version
Nomad v0.5.4

### Issue
nil pointer dereference when merging resources when recovering a task on startup

```
Feb 15 17:33:56 ip-10-0-0-11 nomad[76588]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 15 17:33:56 ip-10-0-0-11 nomad[76588]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5ebe54]
Feb 15 17:33:56 ip-10-0-0-11 nomad[76588]: goroutine 111 [running]:
Feb 15 17:33:56 ip-10-0-0-11 nomad[76588]: panic(0x1000940, 0xc42000e050)
Feb 15 17:33:56 ip-10-0-0-11 nomad[76588]:         /opt/go/src/runtime/panic.go:500 +0x1a1
Feb 15 17:33:56 ip-10-0-0-11 nomad[76588]: github.com/hashicorp/nomad/client/driver.(*CreatedResources).Merge(0x0, 0xc4204ea050)
Feb 15 17:33:56 ip-10-0-0-11 nomad[76588]:         /opt/gopath/src/github.com/hashicorp/nomad/client/driver/driver.go:131 +0xe4
Feb 15 17:33:56 ip-10-0-0-11 nomad[76588]: github.com/hashicorp/nomad/client.(*TaskRunner).startTask(0xc4200b34a0, 0xc42015ed80, 0x0)
Feb 15 17:33:56 ip-10-0-0-11 nomad[76588]:         /opt/gopath/src/github.com/hashicorp/nomad/client/task_runner.go:1169 +0x2e3
Feb 15 17:33:56 ip-10-0-0-11 nomad[76588]: github.com/hashicorp/nomad/client.(*TaskRunner).run(0xc4200b34a0)
Feb 15 17:33:56 ip-10-0-0-11 nomad[76588]:         /opt/gopath/src/github.com/hashicorp/nomad/client/task_runner.go:902 +0x38a
Feb 15 17:33:56 ip-10-0-0-11 nomad[76588]: github.com/hashicorp/nomad/client.(*TaskRunner).Run(0xc4200b34a0)
Feb 15 17:33:56 ip-10-0-0-11 nomad[76588]:         /opt/gopath/src/github.com/hashicorp/nomad/client/task_runner.go:444 +0x6a1
Feb 15 17:33:56 ip-10-0-0-11 nomad[76588]: created by github.com/hashicorp/nomad/client.(*AllocRunner).RestoreState
Feb 15 17:33:56 ip-10-0-0-11 nomad[76588]:         /opt/gopath/src/github.com/hashicorp/nomad/client/alloc_runner.go:190 +0x89
```

**Comment by schmichael** [comment] 2017-02-15 19:34
This is a dupe of #2295 and fixed in #2301. 0.5.5 should be out shortly.

Sorry for the hassle!

**Closed by schmichael** 2017-02-15 19:34 UTC
Labels: bug, client
