### ISSUE TITLE
batch job does not respect disabling restart

### ISSUE THREAD

**Issue by EtienneBruines** [hashicorp/nomad#12930] opened 2022-05-10 09:35 UTC
### Nomad version
1.2.6

### Operating system and Environment details
Ubuntu 20.04.4 LTS on `amd64`

### Issue
My `batch` job keeps restarting.

### Reproduction steps
Use the sample job file and `nomad job run` it.

#### Expected Result
The allocation should `fail` after 5 seconds (no restart attempts!) and at most one other allocation should be attempted (which should fail after 5 seconds), ending in a `failed` status for the job overall. 

#### Actual Result
The allocation keeps restarting, over and over again. No new allocations are attempted, because the original allocation isn't deemed dead/failed. 

The allocation keeps switching between `pending` (when it is waiting 5 seconds to restart, which it isn't even supposed to do) and `running` (during the `sleep` of the task to simulate doing actual work before crashing).

### Job file (if appropriate)

```hcl
job "crash-test" {
	datacenters = ["dc1"]
	type = "batch"

	group "crash-group" {
		restart {
			attempts = 0
			mode = "fail"
		}

		reschedule {
			attempts = 1
			interval = "15s"
			delay = "5s"
			unlimited = false
		}

		task "crash-task" {
			driver = "docker"

			config {
				image = "alpine:latest"
				command = "/bin/ash"
				args = ["-c", "sleep 5 && exit 1"]
			}
		}
	}
}

```

### Nomad Server logs (if appropriate)

Logs were monitored (`TRACE`), but nothing was found on the `leader` that was related to restart attempts. 

Logs were monitored (`TRACE`), but nothing was found on the node that received the job either.

### Nomad Client logs (if appropriate)

Logs were monitored (`TRACE`), but the restart attempts / events of this job/allocation did not show up in the client logs. Other services were present, but are not related. Mostly idle. 

![Screenshot_20220510_113101](https://user-images.githubusercontent.com/3962174/167597324-5b91574d-f917-419a-81d3-fb198aa94eba.png)

**Comment by bsftshantanu** [comment] 2022-05-13 10:46
I assume you want the `reschedule` deliberately instead of just a total of `two` attempts?

```
    reschedule {
      attempts  = 0
      unlimited = false
    }

    restart {
      attempts = 1
      mode     = "fail"
    }
```

**Comment by shantanugadgil** [comment] 2022-05-13 10:47
I assume you want the `reschedule` deliberately instead of just a total of `two` attempts?

```
    reschedule {
      attempts  = 0
      unlimited = false
    }

    restart {
      attempts = 1
      mode     = "fail"
    }
```

**Comment by EtienneBruines** [comment] 2022-05-13 12:23
@shantanugadgil If it doesn't work out on one node, I'd want it to immediately retry on another node. But even that is optional, I want it to never restart and potentially never reschedule on another node. Fail=fail and then I can debug myself. 

Use-case: I'm trying to reliably do database migrations via nomad batch jobs - but without a reliable way for them to fail, detecting failure now usually does not work (because the job keeps restarting in-place indefinitely).

**Comment by shantanugadgil** [comment] 2022-05-13 12:55
For me, the following does one-and-only-one attempt and immediately fail.

```
    reschedule {
      attempts  = 0
      unlimited = false
    }

    restart {
      attempts = 0
      mode     = "fail"
    }
```

But I understand the use case of "if fails on one node, try ONLY one on a different node"

**Comment by tgross** [comment] 2022-06-06 20:17
Hi @EtienneBruines! I took the jobspec you provided and unfortunately wasn't able to reproduce this behavior on Nomad 1.2.6 or the current head. I end up with a status like the following instead, just as I'd expect:

```
$ nomad alloc status 0a7
ID                     = 0a703e0e-f375-3dc8-6e6b-cbae00beaf15
Eval ID                = 1d89cb63
Name                   = crash-test.crash-group[0]
Node ID                = 8b05eb07
Node Name              = proxy
Job ID                 = crash-test
Job Version            = 0
Client Status          = failed
Client Description     = Failed tasks
Desired Status         = run
Desired Description    = <none>
Created                = 10s ago
Modified               = 4s ago
Reschedule Eligibility = 1s from now

Task "crash-task" is "dead"
Task Resources
CPU        Memory          Disk     Addresses
0/100 MHz  56 KiB/300 MiB  300 MiB

Task Events:
Started At     = 2022-06-06T20:08:16Z
Finished At    = 2022-06-06T20:08:21Z
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                       Type            Description
2022-06-06T16:08:21-04:00  Not Restarting  Policy allows no restarts
2022-06-06T16:08:21-04:00  Terminated      Exit Code: 1, Exit Message: "Docker container exited with non-zero exit code: 1"
2022-06-06T16:08:16-04:00  Started         Task started by client
2022-06-06T16:08:15-04:00  Driver          Downloading image
2022-06-06T16:08:15-04:00  Task Setup      Building Task Directory
2022-06-06T16:08:15-04:00  Received        Task received by client
```

A point of clarity because the discussion about rescheduling might confuse things otherwise: the `restart` block is _entirely_ controlled by the Nomad client. It's tracked on the client, and the client sends task events that show up in the `alloc status`, but the decision making is all client-side. The `reschedule` block is _entirely_ controlled by the Nomad scheduler. Once the client has run out of restarts, it lets the server know it's done and all decision making is done on the server.

From the symptoms you've reported, it looks like all other components are behaving as we'd expect. So `restart` is the only thing we need to care about here.

I know you said you didn't find anything in the trace logs on the client, but it might help if you can provide them anyways. Maybe there's something subtle there that we'd pick up that wouldn't be so obvious.

**Comment by tgross** [comment] 2022-07-05 14:53
I'm going to close this issue for now as we don't have the requested information that we'd need to debug. If you do get that info, please feel free to post here and we can re-open the issue. Thanks!

**Closed by tgross** 2022-07-05 14:53 UTC
Labels: type/bug, stage/waiting-reply, theme/restart/reschedule
