### ISSUE TITLE
flakey test TestOperator_TransferLeadershipToServerAddress_ACL

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#19718] opened 2024-01-11 19:20 UTC
I've noticed this test fail a few times, and just now failed 3 times in a row causing a build failure.

```
 === RUN   TestOperator_TransferLeadershipToServerAddress_ACL/good-token
    assert.go:14: 
        operator_endpoint_test.go:516: expected nil error
        ↪ error: Permission denied
--- FAIL: TestOperator_TransferLeadershipToServerAddress_ACL/good-token (0.00s)
FAIL nomad.TestOperator_TransferLeadershipToServerAddress_ACL/good-token (re-run 1) (0.00s)
=== RUN   TestOperator_TransferLeadershipToServerAddress_ACL
    operator_endpoint_test.go:433: bootstrap token: {ea59fd08-c7f2-bf20-f8f5-96e70e3984fe ec80755e-5092-17d1-fe18-b3cc737d6441 management 87b00b9c-f7e7-416f-f25b-1012634d7dcc management [] [] true [] 2024-01-11 19:15:49.532296339 +0000 UTC <nil> 0s 1 1}
Error: 1 2024-01-11T19:15:50.032Z [ERROR] raft-net: failed to decode incoming command: error="transport shutdown"
Error: 1 2024-01-11T19:15:50.117Z [ERROR] raft-net: failed to decode incoming command: error="transport shutdown"
--- FAIL: TestOperator_TransferLeadershipToServerAddress_ACL (0.75s)
FAIL nomad.TestOperator_TransferLeadershipToServerAddress_ACL (re-run 1) (0.75s)
coverage: 10.4% of statements
FAIL nomad (coverage: 10.4% of statements)
```

**Comment by tgross** [comment] 2024-01-11 19:22
I'll close the dupe of this over here: https://github.com/hashicorp/nomad/issues/18993

**Comment by shoenig** [comment] 2024-01-11 19:24
Oh whoops, should have checked first :goat:

**Closed** 2024-03-18 22:03 UTC
Labels: theme/flaky-tests
