### ISSUE TITLE
[document] warn users about the name limitation in template

### ISSUE THREAD

**Issue by liujingchen** [hashicorp/nomad#6099] opened 2019-08-09 11:07 UTC
I'm new to Nomad and Vault. I was trying to integrate nomad and vault. After reading [this document](https://www.vaultproject.io/docs/secrets/kv/kv-v2.html), I created my first secret in Vault with the name "api-key" because all the examples in that document are using hyphen in the names. Then I start to try to render a template in my Nomad job, and it kept failing. After hours of troubleshooting, it turned out the reason was just I should've named my secret as "api_key" instead of "api-key". And apparently I'm not the only person confused by this: https://groups.google.com/forum/#!topic/consul-tool/xCjJG10vIjQ
Please write a warning message on [this page](https://www.nomadproject.io/docs/job-specification/template.html#vault-integration) to stop this tragedy...

**Comment by langmartin** [comment] 2019-08-09 19:49
@liujingchen thanks for pointing this out!

**Comment by tgross** [comment] 2020-11-19 20:08
I opened a PR to update the docs in #9394 but after some internal discussion I wasn't able to confirm this behavior at all. Unfortunately this issue has been open and unloved for too long to expect a reply to help debug it. But I think this is safe to close.

```sh
# enable and populate KV v1 secrets engine
vault secrets enable -path=secrets-kv1 kv
vault kv put secrets-kv1/my_app key=SEEKRIT
vault kv put secrets-kv1/my-app key=SEEKRIT
vault kv put secrets-kv1/myapp key=SEEKRIT

# enable and populate KV v2 secrets engine
vault secrets enable -path=secrets-kv2 kv-v2
vault kv put secrets-kv2/my-app key=SEEKRIT
vault kv put secrets-kv2/my_app key=SEEKRIT
vault kv put secrets-kv2/myapp key=SEEKRIT

# enable and populate PKI secrets engine
vault secrets enable -path=pki-test1 pki
vault write pki-test1/root/generate/internal \
    common_name=service-one.consul ttl=1h
vault write pki-test1/roles/nomad \
    allowed_domains=service-one.consul \
    allow_subdomains=true \
    generate_lease=true max_ttl=10m

# write a policy for Nomad
vault policy write mypolicy ./policy.hcl
```

Policy file:

 ```hcl
path "secrets-kv1/myapp" {
  capabilities = ["read"]
}

path "secrets-kv1/my_app" {
  capabilities = ["read"]
}

path "secrets-kv1/my-app" {
  capabilities = ["read"]
}

path "secrets-kv2/data/myapp" {
  capabilities = ["read"]
}

path "secrets-kv2/data/my_app" {
  capabilities = ["read"]
}

path "secrets-kv2/data/my-app" {
  capabilities = ["read"]
}

path "pki-test1/issue/nomad" {
  capabilities = ["create", "update", "read"]
}
```

Jobspec:

```hcl
job "secrets" {
  datacenters = ["dc1"]

  group "group" {

    task "task" {

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "/bin/sh"
        args    = ["-c", "sleep 300"]
      }

      vault {
        policies = ["mypolicy"]
      }

      template {
        data = <<EOT
{{ with secret "pki-test1/issue/nomad" "common_name=nomad.service-one.consul" "ip_sans=127.0.0.1" }}
{{- .Data.certificate -}}
{{ end }}
EOT

        destination = "${NOMAD_SECRETS_DIR}/certificate.crt"
        change_mode = "noop"
      }

      template {
        data = <<EOT
SOME_SECRET={{ with secret "secrets-kv1/myapp" }}{{- .Data.key -}}{{end}}
EOT

        destination = "${NOMAD_SECRETS_DIR}/myapp-test0"
      }

      template {
        data = <<EOT
SOME_SECRET={{ with secret "secrets-kv1/my_app" }}{{- .Data.key -}}{{end}}
EOT

        destination = "${NOMAD_SECRETS_DIR}/my_app-test0"
      }

      template {
        data = <<EOT
SOME_SECRET={{ with secret "secrets-kv1/my-app" }}{{- .Data.key -}}{{end}}
EOT

        destination = "${NOMAD_SECRETS_DIR}/my-app-test0"
      }


      template {
        data = <<EOT
SOME_SECRET={{ with secret "secrets-kv2/data/myapp" }}{{- .Data.data.key -}}{{end}}
EOT

        destination = "${NOMAD_SECRETS_DIR}/myapp-test1"
      }

      template {
        data = <<EOT
SOME_SECRET={{ with secret "secrets-kv2/data/my_app" }}{{- .Data.data.key -}}{{end}}
EOT

        destination = "${NOMAD_SECRETS_DIR}/my_app-test1"
      }

      template {
        data = <<EOT
SOME_SECRET={{ with secret "secrets-kv2/data/my-app" }}{{- .Data.data.key -}}{{end}}
EOT

        destination = "${NOMAD_SECRETS_DIR}/my-app-test1"
      }


      resources {
        cpu    = 128
        memory = 64
      }
    }

  }
}
```

**Comment by tgross** [comment] 2020-11-19 20:26
@angrycub has straighted me out on this one: the issue is if the name of the secret has a `-`, not the path. Will fix in that PR.

**Comment by tgross** [comment] 2020-11-19 21:17
Fixed in https://github.com/hashicorp/nomad/pull/9394 and will ship with the next website push.

**Closed by tgross** 2020-11-19 21:17 UTC
Labels: theme/docs, type/enhancement
