### ISSUE TITLE
Error while fetching allocation logs using nomad 0.3

### ISSUE THREAD

**Issue by bithavoc** [hashicorp/nomad#889] opened 2016-03-06 16:09 UTC
using nomad `0.3`, trying to fetch the logs for an allocation is resulting in an error:

```bash
nomad fs ls e719a28a alloc/logs/
```
**Error:**
```go
    2016/03/06 16:06:39 [ERR] http: Request /v1/allocation/e719a28a, error: alloc lookup failed: index error: UUID must be 36 characters
    2016/03/06 16:06:39 http: panic serving 127.0.0.1:42589: runtime error: invalid memory address or nil pointer dereference
goroutine 4225 [running]:
net/http.(*conn).serve.func1(0xc820452f00)
	/opt/go/src/net/http/server.go:1389 +0xc1
panic(0x1083040, 0xc82000e070)
	/opt/go/src/runtime/panic.go:426 +0x4e9
github.com/hashicorp/nomad/client.(*Client).GetAllocFS(0x0, 0xc820637db5, 0x24, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/client/client.go:418 +0x4f
github.com/hashicorp/nomad/command/agent.(*HTTPServer).DirectoryListRequest(0xc820226cc0, 0x7eff0520dac8, 0xc8205148f0, 0xc8205f67e0, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/fs_endpoint.go:25 +0x276
github.com/hashicorp/nomad/command/agent.(*HTTPServer).DirectoryListRequest-fm(0x7eff0520dac8, 0xc8205148f0, 0xc8205f67e0, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/http.go:106 +0x5a
github.com/hashicorp/nomad/command/agent.(*HTTPServer).wrap.func1(0x7eff0520dac8, 0xc8205148f0, 0xc8205f67e0)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/http.go:164 +0x139
net/http.HandlerFunc.ServeHTTP(0xc82022b020, 0x7eff0520dac8, 0xc8205148f0, 0xc8205f67e0)
	/opt/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820225f20, 0x7eff0520dac8, 0xc8205148f0, 0xc8205f67e0)
	/opt/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc8201f9000, 0x7eff0520dac8, 0xc8205148f0, 0xc8205f67e0)
	/opt/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820452f00)
	/opt/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/opt/go/src/net/http/server.go:2137 +0x44e

```
Any ideas why this is failing?

**Comment by dadgar** [comment] 2016-03-07 18:25
Hey,

Thanks for reporting, there is a bug!

**Comment by dadgar** [comment] 2016-03-07 21:02
Also if you can build off master, #890 may have fixed this issue! We were not able to reproduce the panic

**Comment by dadgar** [comment] 2016-03-10 02:27
We could not reproduce and we are fairly confident #890 guards the only way this panic could happen. Closing until another report comes in.

**Closed by dadgar** 2016-03-10 02:27 UTC
Labels: bug, client

**Comment by blalor** [comment] 2016-06-16 13:57
I just had the same problem as the submitter.  Turns out I was doing `nomad fs ls <alloc_id> …` instead of `nomad fs <alloc_id> ls …`
