### ISSUE TITLE
Allow disabling hcl2 interpolation for string literals

### ISSUE THREAD

**Issue by notnoop** [hashicorp/nomad#10777] opened 2021-06-17 13:39 UTC
HCLv2 added more comprehensive support for expression interpolation within strings. Users can insert variable references (e.g. `${var.user_field}`) or expressions in here-doc style syntax:

```
template = <<EOT
%{ for ip in var.ips }
server ${ip}
%{ endfor }
EOT
```

This interpolation though comes with downsides. Nomad templates frequently embed shell/perl scripts or embedded nijna-like templates that can conflict with the use of `${` or `%{`. Users must escape references of `${` and `%{`, a tedious task, specially for users upgrading from pre-1.0.0 nomad versions.

We should consider adding a mechanism to disable HCLv2 interpolation processing; e.g. adopt the bash heredoc mechanism to disable variables, by using `'`, e.g. `<<'EOF'`.

The change needs to be coordinated with the hcl library.

This issue was raised in https://github.com/hashicorp/nomad/pull/10743 and https://github.com/hashicorp/nomad/issues/9838#issuecomment-845878713 .

**Comment by idrennanvmware** [comment] 2022-04-05 23:30
@notnoop - just wanted to follow up if there had been any further movement on this? We're still stuck on HCL1 jobs and getting deeper and deeper in to having a hard time switching to HCL2 without this kind of feature

Thanks!

**Comment by tgross** [comment] 2024-08-16 16:15
I'm going to close this issue as a duplicate of https://github.com/hashicorp/nomad/issues/9838. I've left some notes there recently on the challenge involved in implementing this, which will likely require upstream changes to HCL syntax.

**Closed by tgross** 2024-08-16 16:15 UTC
Labels: type/enhancement, theme/hcl, stage/accepted
