### ISSUE TITLE
Job created through CLI has improperly quoted HCL list/map variables in UI

### ISSUE THREAD

**Issue by jhitt25** [hashicorp/nomad#23679] opened 2024-07-24 14:48 UTC
### Nomad version
v1.8.0

### Operating system and Environment details
Oracle Linux 7.9, Kernel 5.4.17

### Issue
Our internal deployments are controlled by Gitlab CI workflows.  As the final step, we build a Nomad job as HCL, validate, plan, then run it.  All our variables are passed as `NOMAD_VAR_` environment variables.  When we then inspect the job in the UI, the job HCL looks fine, but the HCL variables are improperly quoted when they are anything other than simple strings.  If we want to edit the job in the UI, we also have to remove extra quotes in the variables or the job pass the 'plan' call.

### Reproduction steps

Create a simple Nomad job that uses a list or map variable.
```
variable "TEXT" {
    type = list(string)
    default = [ "-text", "Hello World" ]
}

job "http-echo" {
  datacenters = ["centralus"]

  group "echo" {
    task "server" {
      driver = "docker"

      config {
        image = "hashicorp/http-echo:latest"
        args  = var.TEXT
      }
    }
  }
}
```

Export an appropriate environment variable: `export NOMAD_VAR_TEXT="[\"-text\", \"Goodbye World\"]"`

Run the job: `nomad job run http-echo.nomad`

#### Expected Result
The HCL variable in the UI should look like this: `TEXT=["-text", "Goodbye World"]`

#### Actual Result
The HCL variable in the UI looks like this: `TEXT="["-text", "Goodbye World"]"`

**Comment by jrasell** [comment] 2024-07-24 14:57
Hi @jhitt25 and thanks for raising this issue. I have been able to reproduce this locally using latest main, therefore will move this to our backlog for roadmapping.

**Comment by the-nando** [comment] 2024-08-07 18:25
@jrasell I believe this is a duplicate of the issue discussed here: https://github.com/hashicorp/nomad/issues/23462

**Comment by tgross** [comment] 2024-08-07 18:29
Good catch, thanks @the-nando! I'm going to close this as a duplicate, but ping @philrenaud so he sees the additional context here.

**Closed by tgross** 2024-08-07 18:29 UTC
Labels: type/bug, theme/jobspec, theme/hcl, stage/accepted
