### ISSUE TITLE
dimension "disk" exhausted

### ISSUE THREAD

**Issue by shakor0** [hashicorp/nomad#15016] opened 2022-10-24 12:04 UTC
> with Nomad 1.2.4, on Ubuntu 20.04 the issue is still there. @sirkjohannsen do you mind re-opening this ticket?

@maxadamo I can not :) I think its best to file a new Bug report and reference this issue.

_Originally posted by @sirkjohannsen in https://github.com/hashicorp/nomad/issues/4563#issuecomment-1027088307_

**Comment by tgross** [comment] 2022-10-24 12:47
Hi @shakor0! You've hit upon why we set up the lock bot recently: posts on long-closed issues get missed. Unfortunately that post was many months ago, so I'm not sure we're going to get details for a reproduction. If you or the original poster can provide enough details for a reproduction, we'll be happy to look at it thoughh.

**Comment by tgross** [comment] 2022-11-30 21:55
Didn't hear back on this one, but it's pretty clear this is a duplicate of https://github.com/hashicorp/nomad/issues/6172 (and the more recent https://github.com/hashicorp/nomad/issues/14871). I'm going to close this issue and ask that further discussion move over to #6172

**Closed by tgross** 2022-11-30 21:55 UTC
Labels: type/bug, stage/waiting-reply, theme/scheduling, stage/needs-verification
