### ISSUE TITLE
Need a way to cleanly shut down nodes

### ISSUE THREAD

**Issue by blalor** [hashicorp/nomad#2052] opened 2016-12-01 22:55 UTC
Nomad v0.5.0

There doesn't appear to be a way to cleanly shut down a client node in a way that allows allocations to be moved to other nodes and also accounts for the data in sticky ephemeral disks to be migrated.  I wrote a script to help my systemd service delay stopping the service until allocations have been moved, but there doesn't appear to be a way to monitor for the status of the migrated data.  If the data's not moved quickly, it could be lost when the node shuts down.

Something like `nomad shutdown` that blocks until the agent is completely idle would be ideal.

**Comment by groggemans** [comment] 2018-06-03 20:38
Consul has the `leave` command. Would be nice to have a similar command in nomad, which would trigger a node drain, wait for it to complete, and then gracefully leave the cluster.

**Comment by preetapan** [comment] 2018-06-04 03:44
@groggemans Nomad 0.8 added advanced node draining features. Some useful links:

[Node drain command](https://www.hashicorp.com/blog/advanced-node-draining-in-hashicorp-nomad)
[Blog post that explains node draining features](https://www.hashicorp.com/blog/advanced-node-draining-in-hashicorp-nomad)

**Comment by groggemans** [comment] 2018-06-04 06:56
I know, and it solves/implements te draining part, but then the node should still gracefully leave the cluster. And I think the only way to do this now is by stopping/interrupting the service (with `leave_on_terminate = true` or `leave_on_interrupt = true`).

Setting `leave_on_interrupt` or `leave_on_terminate` to `true` isn't always desirable, but it should still be possible to do a graceful leave from the cli even when both options are `false` (default).

For servers there's the `force-leave` option, but for clients there's no command to do a graceful leave. A universal `leave` that would work for both servers and clients which also triggers a node drain seems to be missing.

**Comment by onlyjob** [comment] 2018-08-15 01:08
A relevant discussion happened in #4305. @insanejudge, @schmichael.

Indeed draining node on shutdown is the best and service file could be adjusted to do that. However graceful restart can not be implemented in systemd service because it can not distinguish shut down from restart. Regardless, `KillMode=control-group` (default) is better than `KillMode=process` because the latter does not guarantee cleanup. It is important to leave no unmanaged processes behind.

**Comment by dcparker88** [comment] 2018-09-12 16:29
Not sure if this is relevant or related - but even when I have `leave_on_terminate` set in my config - it doesn't seem to fully leave. I've been doing some testing with the stuff above, and I can see in my logs the node is cleanly shutting down:

```
nomad: ==> Caught signal: terminated
nomad: ==> Gracefully shutting down agent...
nomad[2525]: agent: requesting shutdown
nomad: 2018/09/12 16:11:52.306399 [INFO] agent: requesting shutdown
nomad: 2018/09/12 16:11:52.306468 [INFO] client: shutting down
nomad[2525]: client: shutting down
nomad: 2018/09/12 16:11:52.320998 [INFO] agent: shutdown complete
nomad[2525]: agent: shutdown complete
```

but when I check `nomad node status` it still shows down:
```
$ nomad node status
ID        DC                 Name   Class   Drain  Eligibility  Status
4995dacd  east     agent1     <none>  false  ineligible   down
```

is that expected behavior? I would expect once the node leaves the cluster it doesn't appear in the status anymore.

**Comment by schmichael** [comment] 2018-09-12 17:03
@onlyjob Does systemd allow configuring different signals for reloads, restarts, and shutdowns? If so we could use SIGHUP, SIGINT, and SIGTERM respectively to separate the shutdown behaviors. Adding APIs+CLI commands would also be useful. This is definitely something we're hoping to do, but I don't know if it will make it into 0.9.0.

@dcparker88 Unfortunately `leave_on_terminate` is not implemented for clients, so yes, that is expected.

**Comment by onlyjob** [comment] 2018-09-12 22:34
No it doesn't... There is `ExecStop` but not `ExecRestart`... Anyway IMHO it is _wrong_ to distinguish. Node should be drained on restart as well because it is the only safe approach. If updated executable fail to start then system will end up with dangled unaccounted services.

**Comment by onlyjob** [comment] 2018-09-13 08:04
It is OK if you are committed to support restart without draining. However this is unsafe and therefore should be configurable. Moreover draining node on restart must be default behaviour. It is not OK to leave dangling VMs because they are not cheap to restart.

Betting on perfect stability of the Nomad client is a strategy for the perfect world, like saying that defects in your code (will) never happen.
One day something unforeseen will happen on architecture that your CI does not cover and client will fail to start for whatever reason - could be low memory condition for example - how do you know if there will be enough memory available to start Nomad if it doesn't terminate its jobs?

http://thecodelesscode.com/case/96

**Comment by dcparker88** [comment] 2018-09-13 14:57
@schmichael ah thanks - that makes sense then. Do you know if that's a planned feature, or should I just continue to use GC to clean out down nodes?

**Comment by schmichael** [comment] 2018-09-14 17:08
> @dcparker88: Do you know if that's a planned feature, or should I just continue to use GC to clean out down nodes?

We hoped shutdown improvements would land in 0.9.0, but some larger features (eg plugins) take priority so you may want to continue using GC for the time being. If they don't make it in 0.9.0, hopefully we'll get them out in a patch release.

> @onlyjob: ...therefore should be configurable. Moreover draining node on restart must be default behaviour.

This is the plan!

> @onlyjob: Betting on perfect stability of the Nomad client is a strategy for the perfect world, like saying that defects in your code (will) never happen.

This is precisely reason 2 I gave above for supporting inplace upgrades. A guiding principle in Nomad's design is in the face of errors: do not stop user services! Nomad downtime should prevent further scheduling, but it should avoid causing service downtime as much as possible.

**Comment by onlyjob** [comment] 2018-09-15 04:06
Thanks. :) I think there is a flaw in this reasoning... We need to separate two issues: avoiding stopping services during normal operations and a case when Nomad client itself is restarting.
It violate principles of integrity and common sense to leave scheduled jobs running when nomad client exited...
Service downtime is _necessary_ when manager/dispatcher is restarting because it is the only safe mode of operations.

What if updated Nomad disagrees with running Docker on version of API?

**Comment by rmlsun** [comment] 2020-07-13 23:54
Basically what we want is, if nomad itself is running into unexpected issues, leave the task runtime alone and confined nomad issue to be just nomad issue as much as possible (smallest blast radius possible). On the other hand, if it's an intentional shutdown of nomad client, provides a way to trigger a clean shutdown of task runtimes

I think there might be a fine line here @schmichael

Ideally, if nomad client itself crashes or shutdown b/c not operator initiated reasons, it should not trigger task shutdown. Only if it's an operator initiated shutdown, it triggers (and waits for the finish of) clean shutdown of all tasks.

So would a signal be a good way to indicate it's an intentional shutdown? Like, instead of having client.drain_shutdown = true, how about client.drain_shutdown_signal = SIGINT something along that line.

>Would a client.drain_shutdown = true agent configuration parameter fit your use case? The idea being that when the nomad client received the signal to shutdown it would block exiting until it had drained all running allocations?

**Comment by mwild1** [comment] 2021-04-20 11:57
I understand the reasoning for many people in this thread wanting this feature. It is surely a safer option in many environments. However a few comments implied that the current behaviour is *always* undesirable, which is not the case.

There are some workloads where it absolutely makes sense to keep allocations running during a restart (or crash) of the nomad client. Assuming of course that those allocations can be re-adopted by a new nomad process.

In-place upgrades and the general ease of upgrades with zero or minimal disruption in Nomad are one of the big features over Kubernetes for me.

So yes, by all means a way to combine drain+shutdown/restart would be great, but not because it's the only way that makes sense.

**Comment by ketzacoatl** [comment] 2021-04-22 11:54
@tgross what discussion is needed to figure out next steps here? I would love to help move this along!

**Comment by ketzacoatl** [comment] 2021-09-15 14:46
@tgross ping

**Comment by tgross** [comment] 2021-09-16 00:00
Hey @ketzacoatl given that you already cross-linked this somewhere the Nomad team was asking for inputs, I'm sure they'll have some thoughts for you at some point. But I'm not at HashiCorp for a while now and there aren't any non-HashiCorp maintainers so pinging me probably won't help move things along. :grin:

That being said, if it were up to me (and it's not!), I'd say there's not much to this issue:
* If you're already shutting down a client intentionally, scripting a drain doesn't seem like a huge additional effort.
* If a node is shutting down unintentionally (i.e. it crashes), the node can't participate in telling the server to drain it. So you need to rely on something like [`stop_after_client_disconnect`](https://www.nomadproject.io/heartyeet) anyways.

I'm sure the Nomad team would be open to a patch that provides client configuration that causes the node to drain on graceful shutdown.

**Comment by ketzacoatl** [comment] 2021-09-16 15:10
@tgross apologies for the ping!

**Comment by mikenomitch** [comment] 2021-11-12 19:23
There was a suggestion to use [systemd inhibitor locks](https://trstringer.com/systemd-inhibitor-locks/) to achieve this. Noting here in case it is helpful if this gets picked up.

**Comment by tgross** [comment] 2023-04-14 19:36
Implemented (finally!) in https://github.com/hashicorp/nomhttps://github.com/hashicorp/nomad/pull/16827ad/pull/16827, which will ship in the next release of Nomad.

**Closed** 2023-04-14 19:35 UTC
Labels: type/enhancement, theme/client, stage/needs-discussion, theme/drain
