### ISSUE TITLE
Consul tags can't be defined for just nomad http service

### ISSUE THREAD

**Issue by spuder** [hashicorp/nomad#8081] opened 2020-05-31 00:23 UTC
Nomad = 0.11.2

The nomad server configuration includes a `consul.tags` stanza that allows you to add consul tags to the nomad service

https://www.nomadproject.io/docs/configuration/consul/#tags

```
consul {
  address = "127.0.0.1:8500"
  tags = ["urlprefix-nomad.owen/"]
}
```

This however applies to _all_ nomad services exposed to consul. Suppose you wanted to tag the nomad http service so you could add it to a load balancer like fabio. 

Doing so will put ports 4646,4647 and 4648 in the loadbalancer which is undesirable since they aren't http ports. 

<img width="932" alt="Screenshot 2020-05-30 18 12 17" src="https://user-images.githubusercontent.com/242382/83341580-f7db4c00-a2a1-11ea-866e-e1a8c41dc4e1.png">

There is no way to tag _just_ the http service. 

<img width="806" alt="Screenshot 2020-05-30 18 13 38" src="https://user-images.githubusercontent.com/242382/83341590-235e3680-a2a2-11ea-827e-f91c3dd43899.png">

## Solution

1. Is it possible to define a custom service tag that _only_ applies to the http service? 
2. If not, a feature request to add this functionality would be desired. 

Purposed solution

```
consul {
  address = "127.0.0.1:8500"
  service {
    "http": {
       tags = ["urlprefix-nomad.owen/"]
     }
  } 
}
```

**Comment by tgross** [comment] 2020-06-22 17:07
I'm going to close this as a duplicate of https://github.com/hashicorp/nomad/issues/7941 but rest-assured it's on our radar.

**Closed by tgross** 2020-06-22 17:07 UTC
Labels: consul, duplicate, enhancement
