### ISSUE TITLE
Many UI bugs in v1.3.4

### ISSUE THREAD

**Issue by iluminae** [hashicorp/nomad#14359] opened 2022-08-27 02:26 UTC
### Nomad version
Nomad v1.3.4 (a267b2b000ae72ba05fa571eaafe170a7b9c4d1b)

### Operating system and Environment details
Linux [arm,arm64,amd64]
ACLs are not enabled

### Issue
I will try to enumerate all the issues here, but the UI is very broken in v1.3.4.
* _Any_ graph is blank and spams the browser console with errors. They all seem to be like this error: `Uncaught Error: TypeError: Cannot read properties of null (reading 'then')`
* going to the `Files` tab of any allocation or task will completely crash the page with `UNRECOVERABLE ERROR: TypeError: Cannot read properties of null (reading 'then')`
* going to the `Logs` tab of any task results in a blank log box and this error: `Uncaught TypeError: Cannot read properties of null (reading 'body')`
* going to a client, the `eligible` and `drain` options are greyed out. This cluster has no ACLs enabled, so these should be available.

### Reproduction steps
I am not sure if it is environment or browser specific at all, but I am using Chrome 105.0.5195.42

#### Expected Result
the graphs, logs, files features of the ui to... work.

#### Actual Result
the graphs, logs, files features of the ui do not.... work.

### Job file (if appropriate)
n/a

**Comment by philrenaud** [comment] 2022-08-27 03:02
Hi @iluminae, thanks for raising this. Digging into it now. To help me isolate the problem more quickly, do you happen to know the most recent version of Nomad you were using without the aforementioned UI errors?

**Comment by iluminae** [comment] 2022-08-27 03:18
v1.3.3 - and I kept one client back at that version so I can use it's UI. (all of the features work fine on there, including clients -> eligible toggle and draining options)

**Comment by philrenaud** [comment] 2022-08-27 03:51
Thanks for the info and great find. We've been able to find the cause and will fix this asap.

As a (temporary) workaround, in your chrome dev console, try doing the following:

```
localStorage.setItem('nomadTokenSecret', 'foo')
```

If you try to load your charts/logs/files after that, they should be fine.

Look for an upcoming fix for this soon, and my apologies for the bugs.

**Comment by iluminae** [comment] 2022-08-27 04:06
@philrenaud workaround looks like it is working for me, thanks!

**Comment by heikkilamarko** [comment] 2022-08-27 05:46
I can confirm that the workaround fixes this one too: #14331

**Comment by ednxzu** [comment] 2022-08-27 21:17
If I can add to this, it seems like the UI does not allow you to run job if ACL aren't setup anymore. 
I went from 1.3.3 to 1.3.4 on a test cluster that doesnt have ACLs setup, and the UI will not work unless you setup ACLs (grayed out buttons with "you do not have the permissions to run job" message).

**Comment by iluminae** [comment] 2022-08-28 03:39
@philrenaud when using the workaround above, I still get an error when using the UI to change the job definition of a thing:```
Plan Error
acl token lookup failed: index error: UUID must be 36 characters
```
so the workaround would have to be: ```localStorage.setItem('nomadTokenSecret', 'thisisathirtysixcharacterlongstring!');```

**Comment by philrenaud** [comment] 2022-08-28 03:41
Ah thank you! That'll teach me for using arbitrary metasyntactic variables.

**Comment by rismoney** [comment] 2022-08-30 19:42
will we get a rather quick release when fixed, like a 1.3.5?  A bunch of bug fixes in 1.3.4 are super helpful , but the ui bugs don't allow troubleshooting the alloc fs which kills a lot of inspectability ?  TYVM!!!

**Comment by shantanugadgil** [comment] 2022-08-31 07:53
same question from me too ... would/could there be a 1.3.5 soonish? (UI fixes only)

I could deploy and report back if the various UI bugs are fixed/solved or still present.

**Comment by benvanstaveren** [comment] 2022-08-31 09:35
As requested, adding the following: in a multi-cluster setup, UI no longer allows me to select the cluster I want to operate on. This after an upgrade from 1.2.5 to 1.3.4, on a 4 cluster setup with ACL disabled.

**Comment by lgfa29** [comment] 2022-08-31 17:55
Hi everyone 👋 

Yes, we're planning to have a quick 1.3.5 release out today, so keep an eye out for the announcement, and apologies for the troubles in 1.3.4.

**Comment by shantanugadgil** [comment] 2022-08-31 18:06
Awaiting eagerly for 1.3.5 ...👍🏻🙏🏻

**Comment by lgfa29** [comment] 2022-08-31 22:23
1.3.5 is now available: https://releases.hashicorp.com/nomad/1.3.5/

I'm going to close this issue for now, but let us know if the problem persists.

Thank you for the patience and understanding everyone!

**Closed by lgfa29** 2022-08-31 22:23 UTC
Labels: type/bug, theme/ui

**Comment by shantanugadgil** [comment] 2022-09-01 03:12
Deployed the servers with version 1.3.5 in the staging environment. The UI issues seem resolved. I shall try to deploy to production in a few hours and reconfirm here if it works as expected.

**Comment by shantanugadgil** [comment] 2022-09-01 12:38
I have deployed this to PROD as well and this works fine for now. The UI issues of the `Exec` button are no longer there.

**Comment by lgfa29** [comment] 2022-09-01 14:00
> I have deployed this to PROD as well and this works fine for now. The UI issues of the `Exec` button are no longer there.

Great! Thank you for the confirmation 🙂

**Comment by benvanstaveren** [comment] 2022-09-01 14:09
I've just deployed to prod as well and it seems the UI issues are now resolved. 

Just to throw in my 2 cents as well :)
