### ISSUE TITLE
Unable to interpolate NOMAD_ALLOC_INDEX in group volume stanza

### ISSUE THREAD

**Issue by ryanmickler** [hashicorp/nomad#8540] opened 2020-07-27 07:14 UTC
### Nomad version
11.3

### Operating system and Environment details
ubuntu bionic

### Issue
In order to deploy a (scalable) cluster of tasks, each with their own persistent volume, I need to be able to interpolate the group allocation index in the `volume` stanza at the group level. Each allocation group needs to have its own persistent volume.

In the Nomad UI, i see that the following error, indicating that no interpolation has happened. 
`Constraint missing CSI Volume csi-test-${NOMAD_ALLOC_INDEX} filtered 4 nodes`

### Job file
```
...

    group "group" {

        volume "group_csi_volume" {
            type = "csi"
            read_only = false
            source = "csi-test-${NOMAD_ALLOC_INDEX}"
        }

        ...
```

**Comment by tgross** [comment] 2020-07-27 12:22
Hi @ryanmickler! Thanks for opening this issue. It looks like this is a duplicate of https://github.com/hashicorp/nomad/issues/7877, so I'm going to close it. But it's definitely on our radar!

**Closed by tgross** 2020-07-27 12:22 UTC
