### ISSUE TITLE
Don't URL encode dispatched job IDs

### ISSUE THREAD

**Issue by evandam** [hashicorp/nomad#7962] opened 2020-05-14 18:38 UTC
I'm looking to print links to Nomad jobs in our CI/CD pipeline while dispatching jobs, but it's tricky to format the link correctly since the `/` in a dispatched job ID is encoded to `%2F`.

For example: `https://my.nomad.com/ui/jobs/my-job%2Fdispatch-1589480934-1d1a8e63`

Most tools (ex: Ruby's `URI.encode`) won't encode the `/` because it looks like a valid part of the URL so it has to be handled manually.

Is there a reason this is encoded, or would it be possible to handle a URL like `https://my.nomad.com/ui/jobs/my-job/dispatch-1589480934-1d1a8e63`?

**Comment by DingoEatingFuzz** [comment] 2020-05-14 19:01
This is a duplicate of #7664 

I understand the inconvenience of this, but since (as you mention) `/` is URL segment delimiter, the UI router doesn't take kindly to this type of routing.

In the meantime, in ruby you can use [`URI.encode_www_form_component`](https://docs.ruby-lang.org/en/2.1.0/URI.html#method-c-encode_www_form_component) to also encode the `/`.

**Closed by DingoEatingFuzz** 2020-05-14 19:01 UTC

**Comment by evandam** [comment] 2020-05-14 19:19
Thanks! Understood the technical reasons for it, would just be nice to see 😄
