### ISSUE TITLE
nomad does not restart a failed container

### ISSUE THREAD

**Issue by dockerciworkshop** [hashicorp/nomad#198] opened 2015-10-02 13:44 UTC
Description:
https://www.nomadproject.io/intro/ states `Nomad will handle placement and recover from failures automatically.`
However when killing a docker container Nomad does not restart it.

Repeat by: 
```
nomad init
nomad run example.nomad
docker ps | grep redis 
docker kill <REDIS-CONTAINER-ID>
```

**Comment by bastiaanb** [comment] 2015-10-02 13:51
Nomad, does log the failure, just doesn't act on it:
```
    2015/10/02 13:04:18 [ERR] client: failed to complete task 'redis' for alloc 'b37c8d45-e69c-6d1e-e856-efa279837c7c': Docker container exited with non-zero exit code: 137
```

**Comment by joshua** [comment] 2015-10-02 15:47
I'm experiencing the same issue If I attached to the docker container and kill the service. Nomad does log the failure and change the allocation's state to 'dead' but doesn't attempt to restart or reevaluate.

May be related to #134.

**Comment by dadgar** [comment] 2015-10-02 16:24
Going to close as it is a duplicate of #134

**Closed by dadgar** 2015-10-02 16:24 UTC
