### ISSUE TITLE
Nomad on AWS: Servers not able to discover each other.

### ISSUE THREAD

**Issue by aashayshahh** [hashicorp/nomad#7183] opened 2020-02-19 05:17 UTC
I followed this deployment guide:
https://aws-quickstart.s3.amazonaws.com/quickstart-hashicorp-nomad/doc/hashicorp-nomad-on-the-aws-cloud.pdf

To launch Nomad into a new VPC on my AWS.
After that I ssh into the bastion host. From there I ssh into the nomad server. Once I am on nomad server, I run this command:
```
nomad server members
```
This is what is displays to me:
![Screen Shot 2020-02-18 at 3 17 53 PM](https://user-images.githubusercontent.com/43300957/74786561-e1186880-5261-11ea-9e57-dfda9cd5b036.jpg)

I would expect it to display all 3 server members and not just one. Basically what this is doing is, instead of displaying 3 server members, it just displaying itself. And the Leader=false. I would expect it to display all 3 members with one of them being Leader=True. In a nutshell, it seems like all 3 nomad server members are not able to find/communicate with each other. Please note that my 3 nomad server members are in one region but 3 different AZs. Kindly help me out if I am missing some permissions or configurations.

**Comment by tgross** [comment] 2020-02-19 13:09
Closing as dupe of https://github.com/hashicorp/nomad/issues/7173#issuecomment-587954129

**Closed by tgross** 2020-02-19 13:09 UTC
