### ISSUE TITLE
-dev-connect is only supported on linux

### ISSUE THREAD

**Issue by spuder** [hashicorp/nomad#7184] opened 2020-02-19 05:33 UTC
On OSX, if you attempt to start nomad as shown in the documentation, you get this error

```
brew upgrade nomad
==> Upgrading 1 outdated package:
nomad 0.9.6 -> 0.10.3
```
```
sudo nomad agent -dev-connect
==> -dev-connect is only supported on linux.
```

Up until version 0.10.x OSX has been a first class citizen. Is there a technical reason that `-dev-connect` can't be used on OSX anymore?

**Comment by tgross** [comment] 2020-02-19 13:13
Hi @spuder! The Connect integration depends on Linux network namespaces, which isn't available on macOS. We do try to keep feature parity with macOS but there are a few other features like the `exec` driver that don't work outside of Linux.

**Comment by schmichael** [comment] 2020-02-19 15:57
I'm going to close this as a duplicate of #6501 which describes the root cause: Windows and macOS will be supported using host networking.

In the mean time `nomad agent -dev` works as before v0.10.0. Only the new `-dev-connect` variation is Linux-only. Feel free to reopen if you have further questions or issues!

**Closed by schmichael** 2020-02-19 15:57 UTC
Labels: question, waiting-reply
