### ISSUE TITLE
[feature] Scheduling type: datacenter (& region)

### ISSUE THREAD

**Issue by momania** [hashicorp/nomad#2307] opened 2017-02-13 11:18 UTC
We have a couple of jobs which we run on a datacenter basis. i.e. Consul-replicate, and git2consul.
Consul-replicate should run in each datacenter where git2consul doesn't run. Even though I know adding a new datacenter is not usually something you do every day, it would be nice to be able to specify these jobs with datacenter awareness. This way, I just have to add consul-replicate as a single task in the job description, with a constraint not run in the main datacenter, and then I don't have to copy/paste the task per datacenter I add.

Something like this:
```
 job "consul-tools" {

  datacenters = ["main, site-b, site-c, site-N"]

  type = "datacenter"

  group "git2consul" {
    count = 1

    constraint {
      attribute = "${node.datacenter}"
      operator  = "="
      value     = "main"
    }

    task "git2consul" {

    }
  }

  group "consul-replicate" {
    count = 1

    constraint {
      attribute = "${node.datacenter}"
      operator  = "!="
      value     = "main"
    }

    task "consul-replicate" {

    }
  }
}
```

I would assume that something like Netflix's chaos monkey would also be a very nice contenter for running as datacenter job.

Any thoughts?

**Comment by dadgar** [comment] 2017-02-14 19:50
@momania Hey I am a bit confused what your request is. If you change the type of that job to "service" and kept those constraints it would do what you asked.

**Comment by momania** [comment] 2017-02-14 20:15
@dadgar When changing to 'service' in my example, the 'consul-replicate' task will only run once in either 'site-b' or 'site-c' or 'site-N'.
What I'd like is that it runs one instance in each datacenter.

**Comment by dadgar** [comment] 2017-02-14 22:39
I see. I believe this is a duplicate of #517 which is being implemented by https://github.com/hashicorp/nomad/pull/2168. If you agree lets close this! Thanks!

**Comment by momania** [comment] 2017-02-15 05:54
I'm not sure if it's 100% the same.
Doesn't the `balance_datacenter` constraint mean that if I have a group count of 2, it will try to just distribute those 2 jobs across the datacenters that I have, and even if I have for instance 5 datacenters it will still only run 2, randomly picking 2 unique datacenters from the 5?

What I'm looking for is exactly the same behaviour as the `system` scheduler type, so I don't have to know the number of Nomad clients I have, but each time I add one I know it gets all system jobs scheduled. This, but then on a datacenter level.

**Comment by dadgar** [comment] 2017-02-27 19:32
@momania I understand now.

**Comment by lgierth** [comment] 2017-04-03 20:45
I have a similar need for running a job exactly 1x or 2x per datacenter.

**Comment by lgfausak** [comment] 2017-11-14 14:04
I do as well.  I would like to be able to run a set of jobs on all datacenters.  just now looking in to how i am going to do that.

**Comment by jippi** [comment] 2017-11-14 14:08
would [distinct_property](https://www.nomadproject.io/docs/job-specification/constraint.html#quot-distinct_property-quot-) not do the trick today? if you but `value=2` and unique property to be the DC?

**Comment by lgfausak** [comment] 2017-11-14 14:19
i think so. wow, haven't seen that before.  so something like:
```
constraint {
  operator  = "distinct_property"
  attribute = "${node.datacenter}"
  value     = "1"
}
```
I'll give it a try. Lots of interesting things there. Thanks!

**Closed** 2019-06-09 16:06 UTC
Labels: core, scheduling, waiting-reply
