### ISSUE TITLE
job_gc_interval not found

### ISSUE THREAD

**Issue by jonatasfreitasv** [hashicorp/nomad#6353] opened 2019-09-20 04:21 UTC
### Nomad version
0.9.5

### Operating system and Environment details
CentOS

### Issue
Error loading configuration from /etc/nomad.d: Error loading /etc/nomad.d/server.hcl: server unexpected keys job_gc_interval

### Reproduction steps
```
      server {
        enabled = true
        bootstrap_expect = 3


        job_gc_interval = "30s"
        job_gc_threshold = "1h"
        eval_gc_threshold = "30m"
        num_schedulers = 6
        rejoin_after_leave = true
      }
```

**Comment by preetapan** [comment] 2019-10-09 13:16
Duplicate of #6437

**Closed** 2019-10-09 13:16 UTC
