### ISSUE TITLE
Variables are allowed to be written to non-existing namespaces

### ISSUE THREAD

**Issue by lgfa29** [hashicorp/nomad#18254] opened 2023-08-17 19:49 UTC
### Nomad version

1.6.1

### Operating system and Environment details

MacOS

### Issue

The Nomad variables API allows a variable to be written to a namespace that does not exist.

### Reproduction steps

1. Start a Nomad dev agent
2. Write a variable to a namesapce that doesn't exist.
    ```console
    $ nomad var put -namespace=new test a=b
    Created variable "test" with modify index 1326
    ```

#### Expected Result

Variable write fails because namespace doesn't exist.

#### Actual Result

Variable is written successfully.

**Comment by tgross** [comment] 2023-12-01 18:49
Doing some issue cleanup after that poststop bug for Variables. Looks like this is a dupe of https://github.com/hashicorp/nomad/issues/15379

**Closed by tgross** 2023-12-01 18:49 UTC
Labels: type/bug, stage/accepted, theme/variables
