### ISSUE TITLE
scheduler: incorrect resource calculation when using the prestart hook

### ISSUE THREAD

**Issue by agarfer1** [hashicorp/nomad#24459] opened 2024-11-13 20:15 UTC
### Nomad version
Nomad v1.9.3
BuildDate 2024-11-11T16:35:41Z
Revision d92bf1014886c0ff9f882f4a2691d5ae8ad8131c

### Operating system and Environment details
Ubuntu 24.04 x64

### Issue

When using a task of hook type prestart, both the cpu and the memory resource calculation get stuck on that value, if it's higher than the next/main task.

This would still carry over if there is a poststop task.

Noticed this because my prestart task uses 20 times the memory of the main task, and if the scheduler believes the resource usage is that high while the main task is running, I can barely fit any other tasks in the same client.

### Reproduction steps

Create the job file and let it run in a client with no other running tasks. Visit the v1 metrics endpoint.

#### Expected Result

(While the allocation is the main task)

```
curl -s http://localhost:4646/v1/metrics | jq '.Gauges[] | select(.Name | test("\\.allocated\\.(cpu|memory)")) | .Name, .Value'
"nomad.client.allocated.cpu"
64.0
"nomad.client.unallocated.cpu"
64.0
```

#### Actual Result

(While the allocation is the main task)

```
curl -s http://localhost:4646/v1/metrics | jq '.Gauges[] | select(.Name | test("\\.allocated\\.(cpu|memory)")) | .Name, .Value'
"nomad.client.allocated.cpu"
96.0
"nomad.client.unallocated.cpu"
96.0
```

### Job file

```
job "redis2nd" {
  type = "service"
  group "cache" {
    count = 1

    task "redis-prestart" {
      lifecycle {
        hook    = "prestart"
        sidecar = false
      }
      driver = "docker"
      config {
        image = "hello-world:latest"
      }
      resources {
        cpu = 96
        memory = 96
      }
    }

    task "redis" {
      driver = "docker"
      config {
        image = "redis:3.2"
      }
      resources {
        cpu = 64
        memory = 64
      }
    }
  }
}
```

**Comment by tgross** [comment] 2024-11-13 20:35
Hi @agarfer1! This is working as intended, although I can see how it might be surprising. This happens for two reasons:
* The Nomad scheduler makes placements at the level of a whole allocation. So it allocates the maximum amount of memory the allocation could need at one time.
* The Nomad scheduler can't know when prestart tasks will end, because that's controlled by the workload. So it has to assume the worst case scenario.

For example, suppose we had two different jobs. One has a prestart with memory=100 and a main task with memory=200. The other has a prestart with memory=200 and a main task with memory=100. In an optimistic concurrent placement of these two allocations where both stop their prestart tasks simultaneously, we would need a maximum of 300MB of memory at one time: 

![example-1](https://github.com/user-attachments/assets/95d89513-05be-4013-b28d-978679c5da1c)


But the scheduler can't assume that the prestart tasks from different workloads will stop independently, so we need to account for their overlap. A pessimistic interleaving would require 400MB on that same host:

![example-2](https://github.com/user-attachments/assets/91207469-3679-46fd-a3c2-518d21f17af9)


So in order to ensure we can safely place the workloads, we need to reserve 200MB for each. The actual limits on the tasks (implemented via the task driver, so `docker` in your case) will still be what you've specified.

**Comment by agarfer1** [comment] 2024-11-13 21:07
Thank you for the very detailed explanation.

I sort of get it but I think that assumption makes more sense when the main task (or the poststop task) uses more resources than the previous task that has already finished.

![image](https://github.com/user-attachments/assets/7360a83f-8a02-4141-acc4-644ba89d95a5)

What I'm proposing is that in this image, both allocations would reserve 200MB when they start (since that's the maximum amount of memory they need at any point in time), but after prestart of allocation 2 has finished, why does that allocation still reserve 200MB when it only requires 100MB to complete?

In my use case, my prestart needs 512MB to complete, for less than a minute, but afterwards the main task which will run for hours only requires 16MB. In a 2GB machine I was expecting to fit 96 tasks of 16MB while there are still 512MB available for new jobs to run (they jobs are dispatched). If this doesn't get fixed, I can only run 4 allocations at once in 2GB, which are actually going to be using 64MB out the 2GB.

Thank you for your time, I know that this is not something that can easily fit every situation, but for me this issue is a complete disaster if it doesn't get "fixed".

**Comment by agarfer1** [comment] 2024-11-13 21:23
For example, let's image the following task/resource usage:

prestart, 512MB,
main task, 128MB,
poststop, 192MB

When the task is allocated, it checks the resources demands and reserves the highest concurrent memory that is still necessary.

512MB while the prestart is running

After prestart finishes, it check the remaining tasks, and reserves the highest concurrent memory that is still necessary.

In this case, even though it's about to run the main task, it still keeps 192MB, or else it won't be able to allocate the poststop.

And after the main task finishes, it still keeps the 192MB that poststop itself requires.

-----

I get the feeling that with the current logic is like on allocation is "worrying" about leaving resources for another. And if in the image, allocation 1, and allocation 2 both reserve 200MB from the get go, and release resources as they are no longer required, there won't be any resource exhaustion.

**Comment by tgross** [comment] 2024-11-13 21:51
> why does that allocation still reserve 200MB when it only requires 100MB to complete?

Yeah, I understand where you're coming from on that. But we can't actually assert the allocation can complete with only that 100MB. 

For example, consider the case where a user runs [`alloc restart`](https://developer.hashicorp.com/nomad/docs/commands/alloc/restart) and we need to re-run that prestart task. If the scheduler "took back" resources from tasks that can reappear, then you potentially not have enough on the host left even though the allocation has already been placed. Every command that currently is just a RPC call would now have to pass through the scheduler in order to determine if it were viable. (Or we'd just try it and error-out, but that'd end up with partial restarts.)

> In my use case, my prestart needs 512MB to complete, for less than a minute, but afterwards the main task which will run for hours only requires 16MB.

You're definitely hitting an unfortunate corner case here. Is it possible to run the prestart as a separate allocation?

**Comment by agarfer1** [comment] 2024-11-13 22:31
Just throwing in ideas, maybe there could be a different behavior for batch type of jobs? Since those can always either be re-scheduled or go back to the queue (at least the parameterized batch type). Meaning, those are not types of jobs that generally would be restarted manually by a user.

> You're definitely hitting an unfortunate corner case here. Is it possible to run the prestart as a separate allocation?

In my use case I need both tasks/jobs to be run in the same host, and with parameterized batch type I don't think that can be achieved, maybe I can create the pretask as a system job, but then I would need to create some type of queue or exponential backoff to avoid that when 10 tasks of 16MB are scheduled they crash the "pretask job".

This just makes my project much more difficult.

**Comment by agarfer1** [comment] 2024-11-14 18:16
Thank you for your explanations and your patience. I understand this can not be modified since it's working correctly for most use cases, and I understand that it would open up new sets of problems.

Also, thank you for the ideas, I really appreciate your effort.

And finally thank you and the whole team for the great product(s) :smile:

**Comment by tgross** [comment] 2024-11-15 18:28
Ok, I'm going to close this issue out, but if there's any more help we can give to guide your project I'd be happy to do so here or in a new issue on a different topic.

**Closed by tgross** 2024-11-15 18:28 UTC
Labels: type/bug, theme/scheduling, theme/task lifecycle
