### ISSUE TITLE
System jobs are not rescheduled when resources become available

### ISSUE THREAD

**Issue by maihde** [hashicorp/nomad#4072] opened 2018-03-29 02:45 UTC
### Nomad version
0.7.1

### Operating system and Environment details
Linux

### Issue
When a system job is evaluated, if a node has no free resources the task is queued.  Later, if resources on the node become available the system task should be allocated.  

### Reproduction steps
1. Start a Nomad cluster
2. Run jobs to consume all of the CPU resources
3. Run a system job
4. Notice that the system jobs are Queued
5. Stop the job started at step 2
6. Notice the the system jobs remain Queued

Expected behaviour:
System jobs are removed from the Queued state and go into the Running state

Observed behaviour:
System jobs remain in the Queued state.

**Comment by maihde** [comment] 2018-03-29 03:50
By porting the blocked evaluation logic from `generic_scheduler.go` into `system_scheduler.go` I'm able to get things to work as expected.

https://github.com/maihde/nomad/tree/issue-4072

**Comment by dadgar** [comment] 2018-03-29 23:43
@maihde I think you identified the problem correctly. We do want to bring a lot of the improvements from the generic scheduler to the system scheduler. Hopefully we can use some of your work!

**Comment by maihde** [comment] 2018-03-30 01:16
@dadgar thanks for the feedback.  If you would like a pull-request for my patch, let me know.

**Comment by jippi** [comment] 2018-05-17 17:32
@maihde would be nice to get that PR up

**Comment by maihde** [comment] 2018-05-17 19:43
@jippi just opened up.  Thanks.

**Comment by mwalters-workmarket** [comment] 2019-07-29 13:03
Is there a timeline for the system scheduler rework that will include the fix for this?

**Comment by maihde** [comment] 2019-08-01 13:02
@jippi @mwalters-workmarket my original pull request was closed because there was a major refactor planned to the schedulers and it was deemed easier to start afresh.  If this feature is still on your roadmap I'd be happy to implement the feature against the current `master` and provide a new pull request.

**Comment by burdandrei** [comment] 2020-02-23 10:14
would be cool to revive this

**Comment by notnoop** [comment] 2020-07-09 13:35
Following up here late, sorry.  Is this still a relevant issue?  I believe Nomad 0.9.4 fixed this issue with  https://github.com/hashicorp/nomad/pull/5900 .  Can someone confirm?

**Comment by notnoop** [comment] 2020-07-16 17:39
Closing this ticket, as it seems fixed and I'm unable to reproduce it now.  Please re-open or open a new one if you believe this to be an error.  Thanks!

**Closed by notnoop** 2020-07-16 17:39 UTC
Labels: enhancement, fixed-waiting-confirmation, system-scheduler
