### ISSUE TITLE
address_mode with ingress bound to localhost

### ISSUE THREAD

**Issue by ahjohannessen** [hashicorp/nomad#12203] opened 2022-03-07 12:27 UTC
Hi, I think I am experiencing a "bug" with `host_network` and `address_mode`.

### Nomad version
Nomad v1.2.6 (a6c6b475db5073e33885377b4a5c733e1161020c)

### Operating system and Environment details
Fedora Linux 35.20220213.3.0 (CoreOS)

### Issue

When I use this on my nomad client:

```
client {
    host_network "localhost" {
        interface = "lo"
    }
}
```

and use this job:

```
job "xroad-ingress" {

  datacenters = ["dc1"]

  group "xroad-ingress" {

    network {
      mode = "bridge"
      port "inbound" {
        static       = 8888
        to           = 8888
        host_network = "localhost"
      }
    }

    service {

      name = "xroad-ingress"
      port = "8888"

      address_mode = "host"

      connect {
        gateway {
          ingress {
            listener {
              port     = 8888
              protocol = "tcp"
              service {
                name = "count-api"
              }
            }
          }
        }
        sidecar_task { 
          config { 
           security_opt = ["label=disable"] 
          } 
        }        
      }
    }
  }
}
```

When I do:
```
dig count-api.ingress.consul
...
count-api.ingress.consul. 0	IN	A	192.168.81.103
```

Should I not get 127.0.0.1?

When I use `address_mode = "alloc"` I get this (which is fine):

```
dig count-api.ingress.consul
...
count-api.ingress.consul. 0	IN	A	172.26.64.9
```

**Comment by tgross** [comment] 2022-03-07 20:55
Hi @ahjohannessen! I was able to reproduce this behavior. tl;dr This is a duplicate of https://github.com/hashicorp/nomad/issues/10001 and we need to figure out a way to fix this that doesn't break backwards compatibility. I'm going to close this issue as a duplicate.

In the meantime, I do have to ask why try to use Connect if you're binding to localhost in the first place? There might be a better way to try to do what you're doing. I'd be happy to continue the conversation here to see if there's a viable workaround.

---

Reproduction:


<details><summary>jobspec</summary>

```hcl
job "xroad-ingress" {
  datacenters = ["dc1"]

  group "xroad-ingress" {

    network {
      mode = "bridge"
      port "inbound" {
        static       = 8888
        to           = 8888
        host_network = "localhost"
      }
    }

    service {

      name = "xroad-ingress"
      port = "8888"

      address_mode = "host"

      connect {
        gateway {
          ingress {
            listener {
              port     = 8888
              protocol = "tcp"
              service {
                name = "count-api"
              }
            }
          }
        }
      }
    }

    task "http" {

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-v", "-f", "-p", "8888", "-h", "/local"]
        ports   = ["inbound"]
      }

      template {
        data        = "<html>hello, world</html>"
        destination = "local/index.html"
      }

      resources {
        cpu    = 256
        memory = 512
      }

    }
  }
}

```

</details>

My clients all have have two IP address, one on 192.168.56.0/24 and one on 10.0.2.0/24, and the relevant portion of the client configuration is as follows:

```hcl
bind_addr  = "0.0.0.0"

advertise {
  http = "192.168.56.2"
  rpc  = "192.168.56.2"
  serf = "192.168.56.2"
}

client {
  host_network "localhost" {
    interface = "lo"
  }
}
```

When I run the job, I get the following allocation:

```
$ nomad alloc status 0b3
...

Allocation Addresses (mode = "bridge")
Label     Dynamic  Address
*inbound  yes      127.0.0.1:8888 -> 8888
```

And if I query Consul for the service, I get the 192.168.56.0/24 address, just as you've seen:

```
$ dig @127.0.0.1 -p 8600 xroad-ingress.service.consul
...
xroad-ingress.service.consul. 0 IN      A       192.168.56.2
...
```

If I remove the "localhost" from the `network` block and redeploy, and we get the same `host` address but a different allocation IP address:

```
Allocation Addresses (mode = "bridge")
Label     Dynamic  Address
*inbound  yes      10.0.2.15:8888 -> 8888
```

```
$ dig @127.0.0.1 -p 8600 xroad-ingress.service.consul
...
xroad-ingress.service.consul. 0 IN      A       192.168.56.2
...
```

Remove `address_mode = "host"` and we get the default behavior for Docker, which is unchanged from `host`. If instead we swap out to `address_mode = "alloc"` we get the 10.0.2.0/24 address advertised.

**Closed by tgross** 2022-03-07 20:55 UTC
Labels: type/bug, theme/networking

**Comment by ahjohannessen** [comment] 2022-03-07 21:24
> In the meantime, I do have to ask why try to use Connect if you're binding to localhost in the first place? There might be a better way to try to do what you're doing. I'd be happy to continue the conversation here to see if there's a viable workaround

I have a couple of X-Road servers that are exposed to the internet, these servers get traffic from other X-Road servers using their own mTLS system. My local X-Road servers then gatekeep  subsystems and need to talk to various internal systems that are on the consul service mesh. So in order to allow traffic into the mesh I setup a ingress gateway on the machines that have xroad + consul + nomad, only on localhost.

**Comment by ahjohannessen** [comment] 2022-03-07 21:34
@tgross My ingress gateway solution works fine, I can set intentions up between internal services in connect and xroad-ingress. I just noticed that localhost network resolved to bind_address.

**Comment by tgross** [comment] 2022-03-08 14:47
> Anyway, if I can accomplish the same without using the gateway approach above I am happy to learn about it :)

Probably not without X-Road also being on the Consul mesh to act as the gateway. I wasn't familiar with X-Road so I just did a little dive into the docs and it looks like one could describe X-Road as a service mesh itself?

**Comment by ahjohannessen** [comment] 2022-03-08 16:39
I think you could describe it as such, perhaps like consul mesh gateways :)
