### ISSUE TITLE
env as an empty array fails ""json: cannot unmarshal array into Go value of type map[string]string""

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#1769] opened 2016-09-29 08:40 UTC
Hi,

I'm using PHP to construct a JSON jobspec to submit over HTTP

If `Env` is en empty array (in php = `[]`) I get `"json: cannot unmarshal array into Go value of type map[string]string"`

Would be nice if it was possible for Nomad to handle dynamic language quirks like this and treat `[]` as `NULL` in this case

I've worked around it for now by simply just forcing it to `NULL` if its empty, though it took a while to debug it, so maybe other developers in the future will also spend time on this :)

**Comment by dadgar** [comment] 2016-11-09 23:46
Ah I misread this when I first labelled the issue. The problem is that is invalid json representation of a map so the json parser will throw an error. Nomad can't do much about that. I am going to close the issue but feel free to comment if there is a way forward or something I missed :)

**Closed by dadgar** 2016-11-09 23:46 UTC
Labels: api, bug
