### ISSUE TITLE
Memory metrics not being exposed correctly

### ISSUE THREAD

**Issue by mr-karan** [hashicorp/nomad#19604] opened 2024-01-04 09:06 UTC
### Nomad version

```
Nomad v1.6.1
BuildDate 2023-07-21T13:49:42Z
Revision 515895c7690cdc72278018dc5dc58aca41204ccc
```

### Operating system and Environment details

Ubuntu 22.04

### Issue

I am running Kafka on Nomad using `docker` driver. The memory usage is controlled with the following options in env as documented [here](https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md#configuration).

The `nomad_client_allocs_memory_usage` metric seems to be including cached memory, causing it to report higher memory usage than what is actually being consumed by the processes of the job.

```
KAFKA_HEAP_OPTS=-Xms8g -Xmx8g
```

On the underlying EC2 Instance I can see the actual memory used is just 6GB and rest of it is cached/buffers.

```
$ free -m        
               total        used        free      shared  buff/cache   available
Mem:           15630        6015         315           0        9299        9269
Swap:              0           0           0
```

![image](https://github.com/hashicorp/nomad/assets/5689132/c0d72718-08d2-451d-8f2d-4b2b24f2e668)

However, Nomad reports 14GB of _used_ memory:

```
nomad_client_allocs_memory_usage{alloc_id="e40c0d22-xxx",job="kafka-broker",namespace="kafka",task="kafka",task_group="kafka-broker"} 1.467961344e+10
```

![image](https://github.com/hashicorp/nomad/assets/5689132/3401a6d9-ac8f-43ab-bba8-b7d16a1cbd4e)

Now, the issue is, if I want to alert on 95% memory usage of the allocated, I am unable to with this PromQL query:

```
(nomad_client_allocs_memory_usage / nomad_client_allocs_memory_allocated)
```

I decided to excluded the `nomad_client_allocs_memory_usage` from cache/swap but that metric is `0` for this alloc. In addition, the `nomad_client_allocs_memory_rss` is also 0. I've observed that `nomad_client_allocs_memory_rss` is non zero only for allocs running with `raw_exec` driver.

This makes it really hard/non trivial to report the actual underlying memory used by the alloc.

Any suggestions or help would be great!

**Comment by tgross** [comment] 2024-01-04 13:29
Hi @mr-karan! RSS isn't available to us from the Docker API under cgroups v2, and the reason for that is that the _kernel_ no longer returns an explicit RSS field in cgroups v2. 

This looks like a duplicate of https://github.com/hashicorp/nomad/issues/19185, but this extra context is helpful so I'll link back to this issue from over there.

**Closed by tgross** 2024-01-04 13:29 UTC
Labels: type/bug

**Comment by tgross** [comment] 2025-04-24 16:49
Fixed in https://github.com/hashicorp/nomad/pull/25751
