### ISSUE TITLE
Nomad CLI: allow bypassing of parsing -h/--help argument when running exec

### ISSUE THREAD

**Issue by qubidt** [hashicorp/nomad#15859] opened 2023-01-24 14:44 UTC
### Proposal

Currently, the nomad CLI always interprets any `-h`/`-help`/`--help` flag passed as an argument. No matter where it is passed in the argument list. This makes it very difficult to `exec` a command w/  one of those arguments. For example:

```
$ nomad alloc exec <ALLOC_ID> df -h
```

results in:

```
Usage: nomad alloc exec [options] <allocation> <command>

  Run command inside the environment of the given allocation and task.
...
```

Ideas:

* Only parse the `-h`/`--help` flag when it precedes the command. i.e. *only* if it is in the  `[options]` part of the usage example, not when it follows `<command>`
* Allow the user to pass a `--` argument indicating the end of all arguments that should be parsed by nomad CLI. e.g.:

```
Usage: nomad alloc exec [options] <allocation> [--] <command>
```

### Use-cases

This allows passing `--help` to the command in the nomad allocation, which is a usability improvement. More importantly, `-h` is sometimes *not* an alias for `--help` (e.g. `df`).

### Attempted Solutions

Passing a command line to a shell within the container, bypassing `nomad alloc exec`'s argument parsing. e.g.:

```
nomad alloc exec <ALLOC_ID> /bin/sh -c 'df -h'
```

Sometimes this is not possible. e.g. Containers built off of `scratch` that don't have a useful userspace; they contain only a single binary.

Apologies if this issue has already been documented, I couldn't find any existing issues or threads

**Comment by tgross** [comment] 2023-01-24 16:11
Hi @qubidt! This is indeed a duplicate of the bug https://github.com/hashicorp/nomad/issues/12922. I'm going to close this issue, but you can keep an eye on that one instead.

**Closed by tgross** 2023-01-24 16:11 UTC
Labels: type/enhancement
