### ISSUE TITLE
Globbing in datacenters list

### ISSUE THREAD

**Issue by the-maldridge** [hashicorp/nomad#8269] opened 2020-06-24 17:34 UTC
I'd like to suggest a feature where the datacenters list could use common globbing rules.  In my environments each region is broken up into a set of datacenters based on broad areas of function.  Think things like "edge", "proxy", and "control".  For system jobs that run everywhere, it means that we need an ever growing list of datacenters to run in.

I'd like to suggest that the datacenters field be "globbable".  In this way it would be possible to submit jobs with specifications that request datacenters by partial match.  For system tasks this is fairly straightforward, run in all that match.  For other job types, perhaps the datacenter that's selected should just be randomly selected from the match.  In an ideal world, it would be based on running the scheduler on the job everywhere and picking the best match, but that is likely not practical in a first implementation.

**Comment by mikenomitch** [comment] 2022-04-05 20:32
Hey @the-maldridge, agreed that this is a good idea. Looks like a dupe of this one: https://github.com/hashicorp/nomad/issues/9024 so I'll close this out.

Some notes. This will have to make it into a major release because it is technically a breaking change (If you already had datacenter "foo-*"). Won't be able to make it into 1.3 though, as it's coming very soon.

**Closed by mikenomitch** 2022-04-05 20:32 UTC
Labels: type/enhancement, theme/jobspec, stage/needs-discussion, help-wanted
