### ISSUE TITLE
[BUG] Periodic Scheduler stuck on March 8th 2AM EST, while servers clock was set to UTC

### ISSUE THREAD

**Issue by burdandrei** [hashicorp/nomad#7289] opened 2020-03-08 09:56 UTC
### Nomad version
Nomad v0.10.3 (65af1b9ecff5b55a1dd6e10b8c3224f896d6c9fa)

### Operating system and Environment details
```bash
# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

# cat /etc/timezone 
Etc/UTC
```

### Issue
Periodic jobs stopped firing exactly on DST change

### Reproduction steps
Save daylight time :roll_eyes: 

Here's 24-hour logs pattern from nomad server leader. The obvious spike at 2 AM UTC (8AM local browser time) and decrease after nomad leader was restarted and migrated to another server 

![image](https://user-images.githubusercontent.com/2526486/76160614-50cc9580-6134-11ea-87ee-687fad4970b1.png)

Will post logs after sanitizing

**Comment by burdandrei** [comment] 2020-03-08 10:24
Found the exact message nomad was shouting:
`skipping launch of periodic job because job prohibits`
![image](https://user-images.githubusercontent.com/2526486/76160980-88890c80-6137-11ea-84bb-64133b0e220b.png)


Please guide me what other logs/info can be helpfull

**Comment by jippi** [comment] 2020-03-08 10:33
Note: This has been a multi-year issue hitting us _every_ year - see https://github.com/hashicorp/nomad/issues/5410 and https://github.com/hashicorp/nomad/issues/3392

**Comment by burdandrei** [comment] 2020-03-08 12:45
According to @jippi's assumption, the scheduler is going nuts even if there's one Periodic job that is not in UTC timezone. 
I checked this, and in affected cluster couple of jobs indeed had `America/New_York` time zone configured.
Other clusters, that have only `UTC` time zone crons survived this night well.

**Comment by the-maldridge** [comment] 2020-03-09 07:24
I just got paged into a "fun" outage where a single task running in a localized timezone caused hundreds of other batch tasks to not be dispatched.  What can be done to making sure this bug doesn't go the way of the others referenced above?

**Comment by burdandrei** [comment] 2020-03-09 07:44
Similar to us @the-maldridge =)
We added a force check of the Periodic jobs timezone for now. 
But obviously, when you're running with multi DC, distributed team of developers environment use of timezone is very handy from the developer's perspective

**Comment by jrasell** [comment] 2020-03-09 11:42
Hi @burdandrei, @jippi and @the-maldridge. Thanks a lot for the detail in this issue and apologies this has both caused impact and been in existence for a while. The team started some discussions yesterday on how best to resolve this and we will again talk about this today. I'll likely close this issue as a duplicate of the already linked #5410, however, I think its worth leaving this open for at least today so that anyone else encountering this problem can quickly and easily find the conversation.

**Comment by burdandrei** [comment] 2020-03-09 13:12
Thanks for update @jrasell

**Comment by Dirrk** [comment] 2020-03-09 17:43
We also had this happen in our dev/prod clusters running 0.9.6 on Ubuntu 16.04.  Unfortunately fluentd dropped our logs that would have ended up in Kibana and we shutdown the node once it alerted for 0% disk space which replaced it in the autoscaling group. So I don't have much to add for debugging info but I do know that it used up a ton of memory + disk space on the box.  Hopefully at least this will help others next year.

![image](https://user-images.githubusercontent.com/431645/76241220-a2435600-6202-11ea-9a3f-33a7106bc347.png)

![image](https://user-images.githubusercontent.com/431645/76241327-c737c900-6202-11ea-8ca0-578c2d988fa7.png)

**Comment by jdebbink** [comment] 2020-03-09 20:24
We got hit by this issue as well, what did you do to get things back in a working state?

**Comment by the-maldridge** [comment] 2020-03-09 20:25
@jdebbink We had great luck with removing anything that wasn't running in UTC timezone.  After that we did a stop/start on all jobs in batch/periodic mode and ran a monitoring query to figure out what needed an on-demand launch.

**Comment by jippi** [comment] 2020-03-09 21:14
also just restarting the nomad leader made everything work without any job changes :)

**Closed** 2020-05-12 20:36 UTC
Labels: batch, bug, scheduling
