### ISSUE TITLE
Allocation resources usage showing zero for rootless raw_exec driver in v1.8.0 in Linux

### ISSUE THREAD

**Issue by Settler** [hashicorp/nomad#23425] opened 2024-06-24 10:45 UTC
### Nomad version
Nomad v1.8.0
BuildDate 2024-05-28T17:38:17Z
Revision 28b82e4b2259fae5a62e2ed47395334bea5a24c4

### Operating system and Environment details
Debian 11, raw_exec, cgroupV2

### Issue
This issue possible related to #20285, but we think this problem is different.
We use nomad with `raw_exec` module without root (yes, we know that this is unrecommended setup). We use `raw_exec` because `exec` module has too high overhead with fs isolation. For example, if Nvidia CUDA is installed `exec` module copies over 10Gb of CUDA library into every task. On the other side use `raw_exec` with root access isn't secure enough.

So... `raw_exec` module can use cgroupV2 and create group for every task. We modified Nomad systemd service in this way:
```
[Service]
User=nomad
Group=nomad
Slice=nomad.slice
EnvironmentFile=-/etc/nomad.d/nomad.env
ExecReload=/bin/kill -HUP $MAINPID
ExecStartPre=+chown -R nomad:nomad /sys/fs/cgroup/nomad.slice
ExecStart=/usr/bin/nomad agent -config /etc/nomad.d
Delegate=yes
```
With that setup Nomad process under nomad user has full rights to `nomad.slice`, can manage resources and read stats.
In Nomad 1.7.7 everything is working perfectly. But Nomad 1.8.0 reports zero values for allocation resource usage.

### Reproduction steps
Start nomad in Linux environment without root access with example systemd setup. Start any job with `raw_exec` driver.

#### Expected Result
Reported actual allocation resource usage.

#### Actual Result
Reported zeros for allocation resource usage.

**Comment by tgross** [comment] 2024-06-24 16:02
Hi @Settler! This is a known issue, so I'm going to close this issue as a duplicate of https://github.com/hashicorp/nomad/issues/19828.

**Closed by tgross** 2024-06-24 16:02 UTC
Labels: type/bug
