### ISSUE TITLE
[question] Secrets management for Docker registries

### ISSUE THREAD

**Issue by nferch** [hashicorp/nomad#7687] opened 2020-04-10 15:51 UTC
On https://nomadproject.io/docs/drivers/docker/ it states:

> Be Careful! At this time these credentials are stored in Nomad in plain text. Secrets management will be added in a later release.

Is there tracking or a design for this integration?

At the moment I'm using a credential helper shim that separately authenticates and retrieves a temporary credential from Vault to authenticate with Google Container Registry, but it'd be nice if we got this functionality out of the box, using the existing Vault integration, (hopefully) obviating the need to put Vault credentials on clients.

### Nomad version
Nomad v0.10.2

### Operating system and Environment details
Ubuntu xenial
Vault v1.2.4

**Comment by adeleglise** [comment] 2021-09-14 07:11
Hi, 
Is this feature now available?

**Comment by tgross** [comment] 2024-07-09 12:57
Closing as dupe of https://github.com/hashicorp/nomad/issues/9740

**Closed by tgross** 2024-07-09 12:57 UTC
Labels: type/enhancement, theme/driver/docker
