### ISSUE TITLE
nomad restart dead batch job didn't run

### ISSUE THREAD

**Issue by thatsk** [hashicorp/nomad#10655] opened 2021-05-25 12:29 UTC
### Nomad version
Nomad v1.1.0 (2678c3604bc9530014208bc167415e167fd440fc)

### Operating system and Environment details
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

### Issue
nomad run batchjob.nomad
it did not restart dead job
### Reproduction steps
nomad plan batchjob.nomad
nomad run batchjob.nomad
nomad run batchjob.nomad didn't work

#### Expected Result
it should again run the batch jobs
#### Actual Result
the job keeps in dead state until we modiy anything in nomad job.

### Job file (if appropriate)
```HCL
job "small" {
  datacenters = ["dc1"]

  type = "batch"
  constraint {
    attribute = "${attr.kernel.name}"
    value     = "linux"
  }

  group "worker" {
    count = 1


    task "worker" {
      config {
        image   = "busybox:1"
        command = "/bin/sh"
        args    = ["-c", "echo 'this looks like small jobs' done;  sleep 100" ]
      }

      resources {
        cpu    = 128
        memory = 64
      }
    }
  }
}
```

**Comment by thatsk** [comment] 2021-05-25 13:33
is there a way we can add a date as a meta parameter so that when we run nomad it will take latest timestamp

**Comment by notnoop** [comment] 2021-05-27 14:50
Hi @thatsk ! I'm afraid that this is the expected behavior by design; though I agree it's not intuitive.

I'd suggest checking out the [parameterized/dispatch jobs Learn guide](https://learn.hashicorp.com/tutorials/nomad/job-spec-parameterized?in=nomad/job-specifications). They are designed for dynamic batch jobs that need to be re-run as-is, or with the option of parameterized arguments that are specific to each run.

Alternatively, you can also roll out batch dispatch features using [input variables](https://www.nomadproject.io/docs/job-specification/hcl2/variables), so you can set the timestamp in your example as an input variable and set it with `nomad job run -var timestamp=$(date +%s) ...`  cli invocation.

Does this address your use case?

**Comment by thatsk** [comment] 2021-05-27 14:53
cant we use some meta parameter to dynamically fetch in nomad plan itself
rather than passing an -var

**Comment by thatsk** [comment] 2021-05-27 14:55
as you said timestamp. so can i add something like this 
meta {
  cur_date = $date
}
is $date work in nomad job when we are planning it will take current time date ?

**Comment by notnoop** [comment] 2021-05-27 17:05
Not quite; though Parameterized/dispatch jobs add `SubmitTime` attribute:

```sh
$ nomad job run ./example.nomad
Job registration successful
mars:a notnoop$ nomad job dispatch example
Dispatched Job ID = example/dispatch-1622134856-db81b920
Evaluation ID     = 26940512

==> Monitoring evaluation "26940512"
    Evaluation triggered by job "example/dispatch-1622134856-db81b920"
    Allocation "25202f83" created: node "50cc54ca", group "cache"
==> Monitoring evaluation "26940512"
    Allocation "25202f83" status changed: "pending" -> "running" (Tasks are running)
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "26940512" finished with status "complete"
$ curl -sSL 'http://localhost:4646/v1/job/example%2Fdispatch-1622134856-db81b920' | jq .SubmitTime
1622134856973180000
```

If you are hitting a limitation with the parameterized/dispatch job approach that prevents it from addressing your use case, let us know.

**Comment by thatsk** [comment] 2021-05-28 12:38
can we pass -var via api because i don't find anything how to pass var via HTTP api . I like if we can pass -var to get date timestamp and we can get current time so that it will be going to run everytime whenever we want.

**Comment by thatsk** [comment] 2021-05-28 12:48
parameterized job does not show the status of group task when you run the job and you did not get any visibility for status of job.

**Comment by notnoop** [comment] 2021-05-28 13:39
The HTP job run API endpoint  accepts fully rendered job json rendition - and you have the flexibility of using your preferred json generation or templating technique.  The HCL and `-var` processing occurs in the CLI for `job run` invocation.

> parameterized job does not show the status of group task when you run the job and you did not get any visibility for status of job

Not sure I understand.  You should be able to use `nomad job status` or `nomad alloc status:

```bash
$ # submit job
$ nomad job run billing-nightly.nomad
Job registration successful
$ nomad job dispatch billing-nightly
Dispatched Job ID = billing-nightly/dispatch-1622209014-7bfac19f
Evaluation ID     = 923a80fb

==> Monitoring evaluation "923a80fb"
    Evaluation triggered by job "billing-nightly/dispatch-1622209014-7bfac19f"
    Allocation "c06e6b27" created: node "990346e5", group "processor"
==> Monitoring evaluation "923a80fb"
    Allocation "c06e6b27" status changed: "pending" -> "running" (Tasks are running)
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "923a80fb" finished with status "complete"


$ # check status
$ nomad job status billing-nightly/dispatch-1622209014-7bfac19f
ID            = billing-nightly/dispatch-1622209014-7bfac19f
Name          = billing-nightly/dispatch-1622209014-7bfac19f
Submit Date   = 2021-05-28T09:36:54-04:00
Type          = batch
Priority      = 50
Datacenters   = dc1
Namespace     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
processor   0       0         1        0       0         0

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created  Modified
c06e6b27  990346e5  processor   0        run      running  6s ago   5s ago



$ # check status after it completes
$ nomad job status billing-nightly/dispatch-1622209014-7bfac19f
ID            = billing-nightly/dispatch-1622209014-7bfac19f
Name          = billing-nightly/dispatch-1622209014-7bfac19f
Submit Date   = 2021-05-28T09:36:54-04:00
Type          = batch
Priority      = 50
Datacenters   = dc1
Namespace     = default
Status        = dead
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
processor   0       0         0        0       1         0

Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created  Modified
c06e6b27  990346e5  processor   0        run      complete  19s ago  12s ago
 
 $ # you can check the alloc status too
$ nomad alloc status c06e6b27
ID                  = c06e6b27-9f02-840f-73c3-995a023b740b
Eval ID             = 923a80fb
Name                = billing-nightly/dispatch-1622209014-7bfac19f.processor[0]
Node ID             = 990346e5
Node Name           = mars
Job ID              = billing-nightly/dispatch-1622209014-7bfac19f
Job Version         = 0
Client Status       = complete
Client Description  = All tasks have completed
Desired Status      = run
Desired Description = <none>
Created             = 26s ago
Modified            = 19s ago

Task "processor" is "dead"
Task Resources
CPU        Memory          Disk     Addresses
0/500 MHz  32 KiB/256 MiB  300 MiB

Task Events:
Started At     = 2021-05-28T13:36:54Z
Finished At    = 2021-05-28T13:37:01Z
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                       Type        Description
2021-05-28T09:37:01-04:00  Terminated  Exit Code: 0
2021-05-28T09:36:54-04:00  Started     Task started by client
2021-05-28T09:36:54-04:00  Task Setup  Building Task Directory
2021-05-28T09:36:54-04:00  Received    Task received by client
```

**Comment by tgross** [comment] 2021-06-07 13:54
> Can we pass the -var in curl API ? To submit the job with new timestamp

The `-var` is interpolated entirely client-side in the Nomad CLI, so if you were using the HTTP API directly via curl, you'd need to handle that yourself.

**Comment by thatsk** [comment] 2021-06-15 16:19
k thanks for the info. I think we can do same like https://github.com/jippi/hashi-ui for restarting job. when we hit on restart job it just add meta stanza with date time stamp to restart the job . can we have something in nomad file.

**Comment by tgross** [comment] 2021-11-08 21:34
I'm going to close this issue as resolved. @thatsk if you want to open a feature request explaining what you're asking about for adding a meta stanza, let's open that in a new issue. Thanks!

**Closed by tgross** 2021-11-08 21:34 UTC
Labels: type/question, theme/batch
