### ISSUE TITLE
Artifacts not downloading correctly in 1.5.0+ent

### ISSUE THREAD

**Issue by mocofound** [hashicorp/nomad#16344] opened 2023-03-06 16:18 UTC
### Nomad version
```
Nomad v1.5.0+ent
BuildDate 2023-03-01T11:17:01Z
Revision 2b69add77bbc569b6fffa1ce6663a60f62bbbb6f
```

### Operating system and Environment details
```
Ubuntu 16.04
```

### Issue
After upgrading from 1.4.4+ent to 1.5.0+ent, nomad jobs with artifacts are no longer working correctly.  

### Reproduction steps
Run the job file specified below from the UI
#### Expected Result
task starts successfully
#### Actual Result

```
Mar 06, '23 10:08:46 -0600 | Failed Artifact Download | failed to download artifact "git::https://github.com/fhemberger/nomad-demo.git//nomad_jobs/artifacts/hello-world-java/": getter subprocess failed: exit status 1
Mar 06, '23 10:08:46 -0600 | Downloading Artifacts | Client is downloading artifacts
Mar 06, '23 10:08:30 -0600 | Restarting | Task restarting in 16.474615748s
```

### Job file
```
job "hello-world-java" {
  datacenters = ["dc1"]
  type        = "service"

  # Specify this job to have rolling updates, with 30 second intervals.
  update {
    stagger      = "30s"
    max_parallel = 1
  }

  # A group defines a series of tasks that should be co-located
  # on the same client (host). All tasks within a group will be
  # placed on the same host.
  group "web" {
    # Specify the number of these tasks we want.
    count = 1

    restart {
      attempts = 3
      interval = "2m"
      delay    = "15s"
      mode     = "fail"
    }

    network {
      port "http" {
        static = "9292"
        #to = "9292"
      }
    }

    task "frontend" {
      driver = "java"

      artifact {
        source = "git::https://github.com/fhemberger/nomad-demo.git//nomad_jobs/artifacts/hello-world-java/"
      }

      config {
        jar_path    = "local/HelloWorld.jar"
        jvm_options = ["-Dhelloworld.port=${NOMAD_PORT_http}"]
      }

      resources {
        cpu    = 100
        memory = 50
      }

      service {
        name = "hello-java"
        tags = ["http"]
        port = "http"

        check {
          type     = "http"
          path     = "/"
          interval = "10s"
          timeout  = "2s"
          #port = "http"
        }
      }
    }
  }
}
```
### Nomad Server logs (if appropriate)
N/A
### Nomad Client logs 

```
Mar 06, '23 10:08:46 -0600 | Failed Artifact Download | failed to download artifact "git::https://github.com/fhemberger/nomad-demo.git//nomad_jobs/artifacts/hello-world-java/": getter subprocess failed: exit status 1
Mar 06, '23 10:08:46 -0600 | Downloading Artifacts | Client is downloading artifacts
Mar 06, '23 10:08:30 -0600 | Restarting | Task restarting in 16.474615748s
```

**Comment by dani** [comment] 2023-03-06 17:12
I think I can reproduce something similar with Nomad OSS 1.5.0

Sample job
```
job "downloader" {
  datacenters = ["dc1"]

  group "downloader" {
    task "downloadder" {
      driver = "docker"
      config {
        image = "busybox:latest"
        command = "/bin/true"
      }
      artifact {
        source = "https://letsencrypt.org/certs/isrgrootx1.pem"
      }
      resources {
        cpu = 20
        memory = 30
      }
    }
  }
}
```

Running this job fails with
```
failed to download artifact "https://letsencrypt.org/certs/isrgrootx1.pem": getter subprocess failed: exit status 1
```

In nomad client's log, I get
```
mars 06 18:07:29 ct-wn-1 nomad[2223599]:     2023-03-06T18:07:29.432+0100 [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=ac6d762f-aadf-f395-3933-ad3e9e76b37f task=downloadder type="Downloading Artifacts" msg="Client is downloading artifacts" failed=false
mars 06 18:07:29 ct-wn-1 nomad[2223599]:     2023-03-06T18:07:29.844+0100 [ERROR] client.artifact: sub-process: OUTPUT="failed to download artifact: mkdir /opt/nomad/data/alloc: permission denied"
mars 06 18:07:29 ct-wn-1 nomad[2223599]:     2023-03-06T18:07:29.844+0100 [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=ac6d762f-aadf-f395-3933-ad3e9e76b37f task=downloadder type="Failed Artifact Download" msg="failed to download artifact \"https://letsencrypt.org/certs/isrgrootx1.pem\": getter subprocess failed: exit status 1" failed=false
mars 06 18:07:29 ct-wn-1 nomad[2223599]:     2023-03-06T18:07:29.847+0100 [ERROR] client.alloc_runner.task_runner: prestart failed: alloc_id=ac6d762f-aadf-f395-3933-ad3e9e76b37f task=downloadder error="prestart hook \"artifacts\" failed: failed to download artifact \"https://letsencrypt.org/certs/isrgrootx1.pem\": getter subprocess failed: exit status 1"
mars 06 18:07:29 ct-wn-1 nomad[2223599]:     2023-03-06T18:07:29.847+0100 [INFO]  client.alloc_runner.task_runner: restarting task: alloc_id=ac6d762f-aadf-f395-3933-ad3e9e76b37f task=downloadder reason="Restart within policy" delay=16.372240597s
```

/opt/nomad/data/alloc is my Nomad data_dir. It's root.root and 700 for obvious security reason (and Nomad client is running as root)

**Comment by lgfa29** [comment] 2023-03-06 20:14
Hi @dani 👋 

Thanks for the extra info. So in your configuration you have something like `data_dir = "/opt/nomad/data"`? Could you check the ownership and permission for this directory as well?

And which OS and version are you using?

**Comment by avfuturist** [comment] 2023-03-06 23:28
Downgraded for now to Nomad 1.4.5. Downloads seem to be working now.

**Comment by chenjpu** [comment] 2023-03-07 00:26
Check the permission setting of the directory (/opt/nomad/data) ,and includes the parent's.
nobody account need to have access to these directories

**Comment by lgfa29** [comment] 2023-03-07 01:13
After some more investigation this seems to be caused by the change introduced in https://github.com/hashicorp/nomad/pull/15328 were `go-getter` runs in a forked process under the `nobody` user. 

As @chenjpu noted, this change had the unintended consequence that artifacts download now require the `nobody` user to have access to Nomad's data directory, but this conflicts with our [Nomad hardening guidelines](https://developer.hashicorp.com/nomad/docs/install/production/requirements#hardening-nomad) where we recommend Nomad's data directory to have `0700` permission.

@avfuturist thank your for checking with a previous version of Nomad and confirming that it fixes the problem, but just as a reminder to anyone else having this problem downgrading Nomad versions is not a supported operation.

For now, a workaround for those facing this is issue would be to set the permission of the Nomad client data directory to `0711`, but please make sure you assess potential security impacts on your environment.

We will be working on a fix for this. Thank you all for the help!

**Comment by SunSparc** [comment] 2023-03-09 01:26
This is not making sense. I am hitting the same bug after upgrading to `1.5.0`. However, when I run a job that has an artifact, the artifact is actually downloaded and put where I expect it. Yet the job still fails with:
```
failed to download artifact "https://some.host.com/path/file.tar.gz": getter subprocess failed: exit status 1
```
I go look for it in the `alloc` directory and there it is.

**Comment by tgross** [comment] 2023-03-09 20:15
> Which probably means my situation is unrelated. 

Hi @SunSparc! Yeah that's the new artifact decompression limits. See https://developer.hashicorp.com/nomad/docs/upgrade/upgrade-specific#artifact-decompression-limits for the details the configuration knobs to tweak to get that working.


This issue is closed by https://github.com/hashicorp/nomad/pull/16375 which will ship shortly in Nomad 1.5.1

**Closed by tgross** 2023-03-09 20:15 UTC
Labels: type/bug, theme/client-restart, theme/artifact, stage/accepted
