### ISSUE TITLE
Panic when restarting agent after installing dmidecode

### ISSUE THREAD

**Issue by Mongey** [hashicorp/nomad#19417] opened 2023-12-11 10:44 UTC
### Nomad version
`v1.7.0`

### Operating system and Environment details
`Debian GNU/Linux 11 (bullseye)`

### Issue
After running into dmidecode. I stopped nomad, and installed dmidecode, upon restarting nomad, it panicked 

### Reproduction steps

Start an agent on Debian without `dmidecode` installed. Stop the agent. `apt-get install dmidecode`. Start the agent.
#### Expected Result
Nomad does not crash and can fingerprint the cpu
#### Actual Result
The nomad agent crashes 

### Nomad Client logs
```
2023-12-11T10:22:40.347Z [ERROR] worker: error invoking scheduler: worker_id=77ce465e-c757-72f6-bd31-8c56d02a25b4 error="failed to process evaluation: failed to process eval: runtime error: invalid memory address or nil pointer dereference"
2023-12-11T10:22:40.751Z [ERROR] worker.sysbatch_sched: processing eval panicked scheduler - please report this as a bug!: eval_id=f70460f3-3815-0f11-3db7-ecbee150260c job_id=clamav/periodic-1702287900 namespace=default worker_id=77ce465e-c757-72f6-bd31-8c56d02a25b4 eval_id=f70460f3-3815-0f11-3db7-ecbee150260c error="runtime error: invalid memory address or nil pointer dereference"
  stack_trace=
  | goroutine 74 [running]:
  | runtime/debug.Stack()
  | \truntime/debug/stack.go:24 +0x64
  | github.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process.func1()
  | \tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:83 +0x50
  | panic({0x27a08c0?, 0x4be8a40?})
  | \truntime/panic.go:914 +0x218
  | github.com/hashicorp/nomad/client/lib/numalib.(*Topology).UsableCores(...)
  | \tgithub.com/hashicorp/nomad/client/lib/numalib/topology.go:252
  | github.com/hashicorp/nomad/nomad/structs.(*NodeResources).Comparable(0x4002205a40)
  | \tgithub.com/hashicorp/nomad/nomad/structs/structs.go:3177 +0x80
  | github.com/hashicorp/nomad/scheduler.(*Preemptor).SetNode(0x400198b008, 0x40021bdc80)
  | \tgithub.com/hashicorp/nomad/scheduler/preemption.go:139 +0x30
  | github.com/hashicorp/nomad/scheduler.(*BinPackIterator).Next(0x40044f8930)
  | \tgithub.com/hashicorp/nomad/scheduler/rank.go:274 +0x5b8
  | github.com/hashicorp/nomad/scheduler.(*ScoreNormalizationIterator).Next(0x40021006c0)
  | \tgithub.com/hashicorp/nomad/scheduler/rank.go:808 +0x30
  | github.com/hashicorp/nomad/scheduler.(*SystemStack).Select(0x40025b4600, 0x4002a02120, 0x400198b770)
  | \tgithub.com/hashicorp/nomad/scheduler/stack.go:362 +0x720
  | github.com/hashicorp/nomad/scheduler.(*SystemScheduler).computePlacements(0x4003242840, {0x4000f65700, 0x5, 0x6?})
  | \tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:374 +0x274
  | github.com/hashicorp/nomad/scheduler.(*SystemScheduler).computeJobAllocs(0x4003242840)
  | \tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:322 +0x95c
  | github.com/hashicorp/nomad/scheduler.(*SystemScheduler).process(0x4003242840)
  | \tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:163 +0x428
  | github.com/hashicorp/nomad/scheduler.retryMax(0x2, 0x400198bd70, 0x400198bd60)
  | \tgithub.com/hashicorp/nomad/scheduler/util.go:96 +0x54
  | github.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process(0x4003242840, 0x40044e7680)
  | \tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:108 +0x55c
  | github.com/hashicorp/nomad/nomad.(*Worker).invokeScheduler(0x40008407e0, 0x4001965680, 0x40044e7680, {0x4001d929f0, 0x24})
  | \tgithub.com/hashicorp/nomad/nomad/worker.go:629 +0x2b8
  | github.com/hashicorp/nomad/nomad.(*Worker).run(0x40008407e0, 0x12a05f200)
  | \tgithub.com/hashicorp/nomad/nomad/worker.go:458 +0x4bc
  | created by github.com/hashicorp/nomad/nomad.(*Worker).Start in goroutine 1
  | \tgithub.com/hashicorp/nomad/nomad/worker.go:158 +0x64
  
2023-12-11T10:22:
```

**Comment by tgross** [comment] 2023-12-11 21:18
@Mongey this looks to be a duplicate of https://github.com/hashicorp/nomad/issues/19407 so I'm going to close it just so it's easier to keep track of things. I'll note over in #19407 that the `dmidecode` helped trigger the problem though.

**Closed by tgross** 2023-12-11 21:18 UTC
Labels: type/bug, theme/crash
