### ISSUE TITLE
build: bootstrap target fails due to invalid cert

### ISSUE THREAD

**Issue by desmana** [hashicorp/nomad#14785] opened 2022-10-03 20:27 UTC
### Nomad version

Not applicable.

### Operating system and Environment details

Fedora Linux 5.19.11-200.fc36.x86_64

### Issue

An error occures when trying to compile nomad from source.

`deps` target contains reference to gophers.dev which is currently returning certificate mismatch error.

### Reproduction steps

Run this snippet from official documentation using a clean system (no installed Go packages):

```sh
git clone https://github.com/hashicorp/nomad.git
cd nomad
make bootstrap
```

#### Expected Result

Bootstrap completes without error.

#### Actual Result

```
go: gophers.dev/cmds/hc-install/cmd/hc-install@v1.0.2: unrecognized import path "gophers.dev/cmds/hc-install/cmd/hc-install": https fetch: Get "https://gophers.dev/cmds/hc-install/cmd/hc-install?go-get=1": x509: certificate is valid for cpanel.ctzsupport.duckdns.org, cpcalendars.ctzsupport.duckdns.org, cpcontacts.ctzsupport.duckdns.org, ctzsupport.duckdns.org, mail.ctzsupport.duckdns.org, webdisk.ctzsupport.duckdns.org, webmail.ctzsupport.duckdns.org, www.ctzsupport.duckdns.org, not gophers.dev
```

**Comment by tgross** [comment] 2022-10-03 20:33
Hi @desmana it looks like this is a known issue for hc-install: https://github.com/hashicorp/hc-install/issues/70 But I'm not sure why that gophers.dev URL is in use in the first place except that the CLI hasn't actually been stabilized. We got that version in https://github.com/hashicorp/nomad/pull/12937 so that we were using my colleague @shoenig's fork at the time. But that's all been merged at this point.

`go install github.com/hashicorp/hc-install/cmd/hc-install@4487b02cbcbb92204e3416cef9852b6ad44487b21` should get the job done, and I'm going to add that to our makefile.

**Comment by tgross** [comment] 2022-10-03 20:38
I've opened https://github.com/hashicorp/nomad/pull/14786 with what should fix it.

**Comment by desmana** [comment] 2022-10-03 21:14
Hi,

thanks for your prompt response. The revision in your comment seems to be invalid, but it looks like simply using HEAD is not going to be complete fix anyway.

FYI `tools/go.mod` also refers to a package from this currently problematic source: `gophers.dev/pkgs/ignore`. This should not impact installation, but `make tidy` is currently failing with the same error:

```sh
$ make tidy
==> Tidy up submodules
go: downloading gophers.dev/pkgs/ignore v0.3.1
github.com/hashicorp/nomad/tools/missing imports
	gophers.dev/pkgs/ignore: unrecognized import path "gophers.dev/pkgs/ignore": https fetch: Get "https://gophers.dev/pkgs/ignore?go-get=1": x509: certificate is valid for cpanel.ctzsupport.duckdns.org, cpcalendars.ctzsupport.duckdns.org, cpcontacts.ctzsupport.duckdns.org, ctzsupport.duckdns.org, mail.ctzsupport.duckdns.org, webdisk.ctzsupport.duckdns.org, webmail.ctzsupport.duckdns.org, www.ctzsupport.duckdns.org, not gophers.dev
```

Might be worth looking into this as well.

**Comment by kmoe** [comment] 2022-10-04 09:01
hc-install does not use gophers.dev. I think the issue is likely to be more along the lines of @desmana's comment.

**Comment by tgross** [comment] 2022-10-04 12:31
The build we had for `hc-install` was from a fork because we had a bug fix that wasn't yet in `main` (IIRC it was something around the releases API), so the install we had _was_ from gophers.dev because that's how @shoenig published his fork. You can't publish a fork without changing the source URL. #14786 removes the fork. 

That still leaves the `tools` install being broken because of gophers.dev's cert issue. That `ignore` package looks to also be another @shoenig fork but we can switch that out for https://pkg.go.dev/github.com/shoenig/ignore

**Comment by tgross** [comment] 2022-10-04 13:08
Go modules are really the worst:

```
$ go mod tidy
go: downloading github.com/shoenig/ignore v0.3.1
go: github.com/shoenig/ignore@v0.3.1: parsing go.mod:
        module declares its path as: gophers.dev/pkgs/ignore
                but was required as: github.com/shoenig/ignore
```

**Comment by tgross** [comment] 2022-10-04 13:20
Removed the remaining dependency in https://github.com/hashicorp/nomad/pull/14789

**Closed** 2022-10-04 13:49 UTC
Labels: type/bug, theme/build-infrastructure
