### ISSUE TITLE
job didn't run and can't be restarted

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#18543] opened 2023-09-20 18:23 UTC
### Issue

I ran the task. But this event is not visible via UI
![image](https://github.com/hashicorp/nomad/assets/139780495/feeb5fe3-516e-40f8-b158-ee92ce131b9e)

### Reproduction steps
See picture above

#### Expected Result
I expect to see in UI that job was planned and ran.

#### Actual Result
No messages in UI

**Comment by EugenKon** [comment] 2023-09-20 18:26
And this is not visible too:
![image](https://github.com/hashicorp/nomad/assets/139780495/8c3318d2-4608-4da2-b8a9-27cb2c9e413f)

**Comment by philrenaud** [comment] 2023-09-20 18:28
Hi @EugenKon — I believe what you're looking for here may be on the Task page of a given allocation/task. If you click into your `postgres-task` task from the screenshot above, do you see an events table with these within it?

Follow-up questions in case they're not there: If you go to the Evaluations page (keyboard: `g e`), do you see the evaluations mentioned in your first screenshot in that table?

**Comment by EugenKon** [comment] 2023-09-20 18:33
![image](https://github.com/hashicorp/nomad/assets/139780495/80cb142d-8202-4876-865f-269961bce40e)

![image](https://github.com/hashicorp/nomad/assets/139780495/a4e278dc-a333-4d92-9204-10185a298624)

I can see for `nomad job run -check-index 8046 upgrade-db.hcl` but not for `restart`:
![image](https://github.com/hashicorp/nomad/assets/139780495/217eba26-3e4b-4f06-9f78-629b17feb152)

Still do not know how to find detailed info about `response code: 500`

**Comment by tgross** [comment] 2023-09-20 18:44
@EugenKon this doesn't look to be a UI issue. The initial `nomad job run` command you posted doesn't include the allocation actually having started, but I can't tell because you've cropped the image (it would be much better if you posted terminal output as text instead of screenshots, by the way).

So it looks like you've got two different problems here:
* You started a job and no allocations are running for that version. You should produce the output of `nomad job status` for that version and probably the result of the evaluation from the `job run` as well so that we can see what the current status of the allocations are.
* The "restart of an alloc that should not be running" is what I'd expect to see if you ran a job, the allocation entered the `dead` state because it was a batch job that completed, and then you tried to restart it (which isn't allowed).

My guess here is that your jobspec hasn't changed or the scheduler has determined that the change doesn't result in a new allocation to create. And then when you try to `job restart`, the only allocations are the ones for the previous version of the job which can't restart.

What you should do to get more help here is:
* Post the output of `nomad job status` on the job
* Post the output of `nomad eval status c9ea92ce`
* Post any server logs for that evaluation
* Post the jobspec

**Comment by tgross** [comment] 2023-09-20 19:01
@EugenKon please post the items requested.

**Comment by tgross** [comment] 2023-09-26 15:17
Looks like this is effectively a dupe of https://github.com/hashicorp/nomad/issues/18558

**Closed by tgross** 2023-09-26 15:17 UTC
Labels: stage/waiting-reply, type/question
