### ISSUE TITLE
cores = 2 in resources not working on VM on Ubuntu 21.10

### ISSUE THREAD

**Issue by joshuataylor** [hashicorp/nomad#11773] opened 2022-01-04 11:58 UTC
### Nomad version
Nomad v1.2.3 (a79efc8422082c4790046c3f5ad92c542592a54f)

### Operating system and Environment details
Ubuntu 21.10

On 20.04 it seems to work.

### Issue
On Ubuntu 21.10, even though the number of cores shows as 8 in the UI, it won't let me provision that many cores. Setting the full amount of hz that shows ( 0 MHz / 22,400 MHz Total )

### Reproduction steps

Ubuntu 21.10

#### Expected Result

It works?

#### Actual Result

It says that no enough cores, only 1 works.

### Job file (if appropriate)

```
      resources {
        cores = 2
        memory = 3255
      }
```

Sorry for the lack of information, I couldn't see anything else in the logs, htop and other tools I tried all showed 8 cores on both 20.04 and 21.10.

**Comment by tgross** [comment] 2022-03-18 15:16
I'm going to close this out as a dupe of https://github.com/hashicorp/nomad/issues/11289

**Closed by tgross** 2022-03-18 15:16 UTC
Labels: type/bug, stage/waiting-reply, theme/cgroupv2
