### ISSUE TITLE
You don't have permission to exec in UI while using Vauld OIDC authorization

### ISSUE THREAD

**Issue by beninghton** [hashicorp/nomad#18576] opened 2023-09-26 05:58 UTC
### Nomad version
Nomad v1.6.0
BuildDate 2023-07-18T18:51:11Z
Revision 87d411f4e3a6a744d328c95708c60c12bae0fb18

### Operating system and Environment details
Fedora release 35 (Thirty Five)

### Issue
We use Vault as OIDC provider and if we authorize via Vault we can't perform allocation exec via UI.
![image](https://github.com/hashicorp/nomad/assets/20965960/a2ddfcd6-f4f4-4a86-b89b-01309142709f)

However, If we use the same token that we got from Vault during authorization and use it in nomad cli we successfuly perform exec:
`nomad alloc exec -i -t -task test-task 406f41aa-49fc-1bea-6abb-e4b9ba634cd8 /bin/sh
`
### Reproduction steps
Connect Vault as OIDC provider.

#### Expected Result
Alloc exec is performed

**Comment by tgross** [comment] 2023-09-26 13:01
Dupe of https://github.com/hashicorp/nomad/issues/18577

**Closed by tgross** 2023-09-26 13:01 UTC
Labels: type/bug
