### ISSUE TITLE
Unable to normally stop and purge system job with csi plugin

### ISSUE THREAD

**Issue by ygersie** [hashicorp/nomad#11758] opened 2022-01-03 08:48 UTC
### Nomad version
v1.2.3

### Operating system and Environment details
MacOS nomad agent -dev setup

### Issue
Unable to stop and purge a `failed` system job which has a csi_plugin stanza and unexpected start of the job when `-purge` is passed.
### Reproduction steps
Run below example job.
```hcl
job "example" {
  datacenters = ["dc1"]
  type        = "system"

  group "example" {
    task "example" {
      driver = "docker"
      config {
        image = "alpine"
        args  = ["/bin/sh", "-c", "exit 1"]
      }

      restart {
        attempts = 1
        interval = "10s"
        delay    = "5s"
        mode     = "fail"
      }

      csi_plugin {
        id        = "example"
        type      = "node"
        mount_dir = "/csi"
      }

      resources {
        cpu    = 100
        memory = 64
      }
    }
  }
}
```
Now wait until the job transitions to the failed state, then stop + purge the job.
```sh
nomad job stop -purge example
```
Now check the status of the job:
```sh
$ nomad job status example
ID            = example
Name          = example
Submit Date   = 2022-01-03T09:33:10+01:00
Type          = system
Priority      = 50
Datacenters   = dc1
Namespace     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
example     0       0         0        1       0         0

Allocations
ID        Node ID   Task Group  Version  Desired  Status  Created    Modified
86f91d4c  73681f8d  example     0        run      failed  2m52s ago  2m42s ago
```
This should've returned a not found error but it's still there and the `Desired` column states **run**. Re-running `nomad job stop -purge example` doesn't change the outcome until a GC has been run. Now trigger a GC with `nomad system gc` and rerun the stop -purge again, the result becomes:
```sh
$ nomad job stop -purge example
==> 2022-01-03T09:44:23+01:00: Monitoring evaluation "ed1f4546"
    2022-01-03T09:44:23+01:00: Evaluation triggered by job "example"
    2022-01-03T09:44:23+01:00: Allocation "c8c61822" created: node "73681f8d", group "example"
==> 2022-01-03T09:44:24+01:00: Monitoring evaluation "ed1f4546"
    2022-01-03T09:44:24+01:00: Evaluation status changed: "pending" -> "complete"
==> 2022-01-03T09:44:24+01:00: Evaluation "ed1f4546" finished with status "complete"
```
Instead of stopping it actually recreates the allocation again..

**Comment by jrasell** [comment] 2022-01-03 10:25
Hi @ygersie and thanks for providing such a detailed reproduction. I ran through this locally and got the same results as you detailed. These results are very unexpected.

**Comment by tgross** [comment] 2022-01-03 13:49
I suspect this is related to another CSI plugin counts issue; I'm taking a pass through our open CSI issues over the next few weeks and will look at this as part of that work.

**Comment by tgross** [comment] 2022-02-03 17:12
Noting here that I've marked https://github.com/hashicorp/nomad/issues/11114 as a duplicate of this one. https://github.com/hashicorp/nomad/issues/10073 may also ultimately be a duplicate but I'll leave that open for the time being as the cause is subtly different.

It looks like there are two parts to this:
* The plugin counts don't accurately match the state of allocations. I'm working up a patch the resolves plugin counts in a similar fashion to what we did for volume claims in https://github.com/hashicorp/nomad/pull/11890
* There may also be a race between how we trigger allocation stops from a job purge, which in turn triggers the plugin GC, and how we purge the job. We can't GC the plugin until the allocation is terminal, but perhaps (incorrectly) can't GC the job until the plugin is GC'd. I'll be looking into this as well.

**Comment by tgross** [comment] 2022-02-08 20:03
I've opened https://github.com/hashicorp/nomad/pull/12027 which is targeting https://github.com/hashicorp/nomad/issues/9810 and https://github.com/hashicorp/nomad/issues/10073 but may be a partial fix for this issue. Once I've got that merged I'll be digging into this.

**Comment by tgross** [comment] 2022-02-23 20:55
Ok, so following #12027, #10073, and #12078 we've _almost_ got this one resolved. There's just one bug left, which is that we can't deregister the job because it's looking to delete the plugin that doesn't exist:

> 2022-02-23T20:51:35.777Z [ERROR] nomad.fsm: deregistering job failed: error="DeleteJob failed: deleting job from plugin: plugin missing: example <nil>" job=badplugin namespace=default

**Comment by tgross** [comment] 2022-02-23 21:07
Fixed in https://github.com/hashicorp/nomad/pull/12114!

**Closed** 2022-02-24 13:53 UTC
Labels: type/bug, theme/storage, stage/accepted
