### ISSUE TITLE
Nomad creates two allocations for task group with count = 1

### ISSUE THREAD

**Issue by grobinson-blockchain** [hashicorp/nomad#1269] opened 2016-06-13 12:25 UTC
I've just experienced a situation where Nomad has created two allocations for the same evaluation despite the count in the taskGroup being 1:

	==> Allocations
	ID        Eval ID   Node ID   Task Group  Desired  Status
	b65f79cc  2c63d234  8a571766  deploy-api  run      running
	fc46efca  2c63d234  8a571766  deploy-api  run      running
	5db8dcf2  79b0f77e  8a571766  deploy-api  stop     complete
	2330b4e8  79b0f77e  8a571766  deploy-api  stop     complete

The evaluation monitor:

	==> Monitoring evaluation "2c63d234"
	    Evaluation triggered by job "deploy-api"
	    Allocation "b65f79cc" modified: node "8a571766", group "deploy-api"
	    Allocation "fc46efca" modified: node "8a571766", group "deploy-api"
	    Evaluation status changed: "pending" -> "complete"
	==> Evaluation "2c63d234" finished with status "complete"

I waited but Nomad never de-registered the second allocation. I was able to get back to a single allocation with `nomad stop` followed with `nomad run`:

        ==> Allocations
	ID        Eval ID   Node ID   Task Group  Desired  Status
	e7423589  39803708  8a571766  deploy-api  run      pending
	b65f79cc  2c63d234  8a571766  deploy-api  stop     complete
	fc46efca  2c63d234  8a571766  deploy-api  stop     complete
	5db8dcf2  79b0f77e  8a571766  deploy-api  stop     complete
	2330b4e8  79b0f77e  8a571766  deploy-api  stop     complete

### Nomad version
Nomad v0.3.2

### Job file (if appropriate)
    job "deploy-api" {
        type = "service"
        region = "global"
        datacenters = ["dc1"]

        group "deploy-api" {
            count = 1

            task "deploy-api" {
                driver = "docker"

                config {
                    image = "docker-registry.service.consul:5000/deploy-api:e4dd57d"
                    dns_servers = [
                        "172.17.0.1"
                    ]
                    port_map = {
                        http = 8080
                    }
                }

                constraint {
                    attribute = "${attr.hostname}"
                    regexp = "deploy-api*"
                }

                service {
                    name = "deploy-api"
                    port = "http"
                    check {
                        type = "http"
                        path = "/healthz"
                        interval = "10s"
                        timeout = "2s"
                    }
                }

                env {
                    DEPLOY_API_REGISTRY="docker-registry.service.consul:5000"
                    CONSUL_HTTP_ADDR="172.17.0.1:8500"
                    NOMAD_ADDR="http://172.17.0.1:4646"
                }

                resources {
                    cpu = 512
                    memory = 512
                    network {
                        mbits = 100
                        port "http" {}
                    }
                }
            }
        }
    }

# Client logs

	Jun 13 12:17:15 deploy-api-ylm1 docker[19925]: time="2016-06-13T12:17:15.410627032Z" level=error msg="restartmanager canceled"
	Jun 13 12:17:15 deploy-api-ylm1 docker[19925]: time="2016-06-13T12:17:15.420239375Z" level=error msg="restartmanager canceled"
	Jun 13 12:17:15 deploy-api-ylm1 kernel: [86788.673128] docker0: port 2(veth9fb9d61) entered disabled state
	Jun 13 12:17:15 deploy-api-ylm1 kernel: [86788.686367] docker0: port 2(veth9fb9d61) entered disabled state
	Jun 13 12:17:15 deploy-api-ylm1 kernel: [86788.694173] device veth9fb9d61 left promiscuous mode
	Jun 13 12:17:15 deploy-api-ylm1 kernel: [86788.699911] docker0: port 2(veth9fb9d61) entered disabled state
	Jun 13 12:17:15 deploy-api-ylm1 kernel: [86788.735701] docker0: port 1(vetha201098) entered disabled state
	Jun 13 12:17:15 deploy-api-ylm1 kernel: [86788.745220] device vetha201098 left promiscuous mode
	Jun 13 12:17:15 deploy-api-ylm1 kernel: [86788.751734] docker0: port 1(vetha201098) entered disabled state
	Jun 13 12:17:15 deploy-api-ylm1 nomad[4049]: 2016/06/13 12:17:15 [INFO] driver.docker: stopped container 751e7bfb907c3a6d9594ea83ed7c924818f3853e8dc7053ce1ef2eeda1082742
	Jun 13 12:17:15 deploy-api-ylm1 consul[2111]: 2016/06/13 12:17:15 [INFO] agent: Deregistered service 'nomad-registered-service-fc46efca-172b-edb0-f90d-8545a14ad172-deploy-api-885e3c077ed2e1dbadfe5caa48f348c72c1fac4b'
	Jun 13 12:17:15 deploy-api-ylm1 consul[2111]: 2016/06/13 12:17:15 [INFO] agent: Deregistered check 'cd212cff4fd565a416fcfd73a6bd88fdc24818c1'
	Jun 13 12:17:15 deploy-api-ylm1 docker[19925]: time="2016-06-13T12:17:15.549975696Z" level=error msg="Handler for POST /containers/751e7bfb907c3a6d9594ea83ed7c924818f3853e8dc7053ce1ef2eeda1082742/stop returned error: Container 751e7bfb907c3a6d9594ea83ed7c924818f3853e8dc7053ce1ef2eeda1082742 is already stopped"
	Jun 13 12:17:15 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:17:15 [INFO] (view) "service(deploy-api)" received data
	Jun 13 12:17:15 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:17:15 [INFO] (runner) running
	Jun 13 12:17:15 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:17:15 [INFO] (runner) diffing and updating dependencies
	Jun 13 12:17:15 deploy-api-ylm1 systemd[1]: Reloading The NGINX HTTP and reverse proxy server.
	Jun 13 12:17:15 deploy-api-ylm1 nomad[4049]: 2016/06/13 12:17:15 [INFO] driver.docker: stopped container 20b6da96289b421ab874d74b6df6dc011732965da9db9638d33672820ecf1832
	Jun 13 12:17:15 deploy-api-ylm1 docker[19925]: time="2016-06-13T12:17:15.567092221Z" level=error msg="Handler for DELETE /images/sha256:cc8ee4365056af6fc235afde03047521d9f21782432927e260a97579978eedc1 returned error: conflict: unable to delete cc8ee4365056 (must be forced) - image is being used by stopped container 20b6da96289b"
	Jun 13 12:17:15 deploy-api-ylm1 systemd[1]: Reloaded The NGINX HTTP and reverse proxy server.
	Jun 13 12:17:15 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:17:15 [INFO] (runner) watching 1 dependencies
	Jun 13 12:17:15 deploy-api-ylm1 consul[2111]: 2016/06/13 12:17:15 [INFO] agent: Deregistered service 'nomad-registered-service-b65f79cc-077b-1e3a-74f8-d31cff97dce6-deploy-api-885e3c077ed2e1dbadfe5caa48f348c72c1fac4b'
	Jun 13 12:17:15 deploy-api-ylm1 consul[2111]: 2016/06/13 12:17:15 [INFO] agent: Deregistered check '5fb222c8452aa079672e8d750fac074b101cc497'
	Jun 13 12:17:15 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:17:15 [INFO] (view) "service(deploy-api)" received data
	Jun 13 12:17:15 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:17:15 [INFO] (runner) running
	Jun 13 12:17:15 deploy-api-ylm1 docker[19925]: time="2016-06-13T12:17:15.588812551Z" level=error msg="Handler for POST /containers/20b6da96289b421ab874d74b6df6dc011732965da9db9638d33672820ecf1832/stop returned error: Container 20b6da96289b421ab874d74b6df6dc011732965da9db9638d33672820ecf1832 is already stopped"
	Jun 13 12:17:15 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:17:15 [INFO] (runner) diffing and updating dependencies
	Jun 13 12:17:15 deploy-api-ylm1 systemd[1]: Reloading The NGINX HTTP and reverse proxy server.
	Jun 13 12:17:15 deploy-api-ylm1 systemd[1]: Reloaded The NGINX HTTP and reverse proxy server.
	Jun 13 12:17:15 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:17:15 [INFO] (runner) watching 1 dependencies
	Jun 13 12:17:25 deploy-api-ylm1 docker[19925]: time="2016-06-13T12:17:25.476493072Z" level=error msg="Handler for GET /images/docker-registry.service.consul:5000/deploy-api:e4dd57d/json returned error: No such image: docker-registry.service.consul:5000/deploy-api:e4dd57d"
	Jun 13 12:17:25 deploy-api-ylm1 docker[19925]: time="2016-06-13T12:17:25.484400081Z" level=warning msg="Error getting v2 registry: Get https://docker-registry.service.consul:5000/v2/: tls: oversized record received with length 20527"
	Jun 13 12:17:25 deploy-api-ylm1 docker[19925]: time="2016-06-13T12:17:25.484943583Z" level=error msg="Attempting next endpoint for pull after error: Get https://docker-registry.service.consul:5000/v2/: tls: oversized record received with length 20527"
	Jun 13 12:18:13 deploy-api-ylm1 kernel: [86846.906573] aufs au_opts_verify:1570:docker[20845]: dirperm1 breaks the protection by the permission bits on the lower branch
	Jun 13 12:18:13 deploy-api-ylm1 docker[19925]: time="2016-06-13T12:18:13.667569342Z" level=warning msg="Your kernel does not support memory limit capabilities. Limitation discarded."
	Jun 13 12:18:13 deploy-api-ylm1 kernel: [86846.933262] aufs au_opts_verify:1570:docker[20845]: dirperm1 breaks the protection by the permission bits on the lower branch
	Jun 13 12:18:13 deploy-api-ylm1 kernel: [86846.954092] aufs au_opts_verify:1570:docker[20796]: dirperm1 breaks the protection by the permission bits on the lower branch
	Jun 13 12:18:13 deploy-api-ylm1 nomad[4049]: 2016/06/13 12:18:13 [INFO] driver.docker: created container e122bf48b757a919e8f606cb6ca57b1056cfe6d662c6d354527dac424c24c70f
	Jun 13 12:18:13 deploy-api-ylm1 kernel: [86846.970543] device vethff38dcb entered promiscuous mode
	Jun 13 12:18:13 deploy-api-ylm1 kernel: [86846.978984] IPv6: ADDRCONF(NETDEV_UP): vethff38dcb: link is not ready
	Jun 13 12:18:13 deploy-api-ylm1 systemd-sysctl[13287]: Overwriting earlier assignment of net/ipv4/ip_forward in file '/etc/sysctl.d/99-salt.conf'.
	Jun 13 12:18:13 deploy-api-ylm1 systemd-sysctl[13289]: Overwriting earlier assignment of net/ipv4/ip_forward in file '/etc/sysctl.d/99-salt.conf'.
	Jun 13 12:18:13 deploy-api-ylm1 kernel: [86847.061629] IPv6: ADDRCONF(NETDEV_CHANGE): vethff38dcb: link becomes ready
	Jun 13 12:18:13 deploy-api-ylm1 kernel: [86847.070191] docker0: port 1(vethff38dcb) entered forwarding state
	Jun 13 12:18:13 deploy-api-ylm1 kernel: [86847.077970] docker0: port 1(vethff38dcb) entered forwarding state
	Jun 13 12:18:13 deploy-api-ylm1 kernel: [86847.099066] IPv4: martian source 172.17.0.1 from 172.17.0.2, on dev eth0
	Jun 13 12:18:13 deploy-api-ylm1 kernel: [86847.106749] ll header: 00000000: ff ff ff ff ff ff 02 42 ac 11 00 02 08 06        .......B......
	Jun 13 12:18:13 deploy-api-ylm1 nomad[4049]: 2016/06/13 12:18:13 [INFO] driver.docker: started container e122bf48b757a919e8f606cb6ca57b1056cfe6d662c6d354527dac424c24c70f
	Jun 13 12:18:13 deploy-api-ylm1 docker[19925]: time="2016-06-13T12:18:13Z" level=error msg="containerd: notify OOM events" error="open memory.oom_control: no such file or directory"
	Jun 13 12:18:13 deploy-api-ylm1 consul[2111]: 2016/06/13 12:18:13 [INFO] agent: Synced service 'nomad-registered-service-e7423589-c2d6-6cf7-d8cd-c02345843457-deploy-api-885e3c077ed2e1dbadfe5caa48f348c72c1fac4b'
	Jun 13 12:18:13 deploy-api-ylm1 consul[2111]: 2016/06/13 12:18:13 [INFO] agent: Synced check '1fed7953ce2ce3bd4d5902401816ec44c8291965'
	Jun 13 12:18:13 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:18:13 [INFO] (view) "service(deploy-api)" received data
	Jun 13 12:18:13 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:18:13 [INFO] (runner) running
	Jun 13 12:18:13 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:18:13 [INFO] (runner) diffing and updating dependencies
	Jun 13 12:18:13 deploy-api-ylm1 systemd[1]: Reloading The NGINX HTTP and reverse proxy server.
	Jun 13 12:18:13 deploy-api-ylm1 systemd[1]: Reloaded The NGINX HTTP and reverse proxy server.
	Jun 13 12:18:13 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:18:13 [INFO] (runner) watching 1 dependencies
	Jun 13 12:18:13 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:18:13 [INFO] (view) "service(deploy-api)" received data
	Jun 13 12:18:13 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:18:13 [INFO] (runner) running
	Jun 13 12:18:13 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:18:13 [INFO] (runner) diffing and updating dependencies
	Jun 13 12:18:13 deploy-api-ylm1 systemd[1]: Reloading The NGINX HTTP and reverse proxy server.
	Jun 13 12:18:13 deploy-api-ylm1 systemd[1]: Reloaded The NGINX HTTP and reverse proxy server.
	Jun 13 12:18:13 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:18:13 [INFO] (runner) watching 1 dependencies
	Jun 13 12:18:14 deploy-api-ylm1 kernel: [86847.400156] IPv6: eth0: IPv6 duplicate address fe80::42:acff:fe11:2 detected!
	Jun 13 12:18:16 deploy-api-ylm1 consul[2111]: 2016/06/13 12:18:16 [INFO] agent: Synced check '1fed7953ce2ce3bd4d5902401816ec44c8291965'
	Jun 13 12:18:16 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:18:16 [INFO] (view) "service(deploy-api)" received data
	Jun 13 12:18:16 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:18:16 [INFO] (runner) running
	Jun 13 12:18:16 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:18:16 [INFO] (runner) diffing and updating dependencies
	Jun 13 12:18:16 deploy-api-ylm1 systemd[1]: Reloading The NGINX HTTP and reverse proxy server.
	Jun 13 12:18:16 deploy-api-ylm1 systemd[1]: Reloaded The NGINX HTTP and reverse proxy server.
	Jun 13 12:18:16 deploy-api-ylm1 consul-template[2224]: 2016/06/13 12:18:16 [INFO] (runner) watching 1 dependencies
	Jun 13 12:18:28 deploy-api-ylm1 kernel: [86862.112033] docker0: port 1(vethff38dcb) entered forwarding state
	Jun 13 12:24:32 deploy-api-ylm1 consul[2111]: 2016/06/13 12:24:32 [INFO] serf: EventMemberReap: deploy-api-2jq8
	Jun 13 12:26:18 deploy-api-ylm1 systemd[1]: Starting Cleanup of Temporary Directories...
	Jun 13 12:26:18 deploy-api-ylm1 systemd[1]: Started Cleanup of Temporary Directories.
	Killed by signal 1.
	Locals-MBP:~ grobinson$

**Comment by dadgar** [comment] 2016-06-13 14:23
Can you post the server logs. Is this reproducible for you?

**Comment by grobinson-blockchain** [comment] 2016-06-13 14:43
@dadgar I'm not sure quite how to reproduce it again, but it just happened for another, separate job. This is the output from the Nomad cluster (will enable "debug" output to provide more in-depth logs when it happens next).

	Jun 13 14:34:33 consul-master-eu-west-1 consul-template[3236]: ==> Monitoring evaluation "b80229a4"
	Jun 13 14:34:33 consul-master-eu-west-1 consul-template[3236]: Evaluation triggered by job "charts-worker"
	Jun 13 14:34:34 consul-master-eu-west-1 consul-template[3236]: Allocation "2e59e7d8" created: node "e327664b", group "charts-worker"
	Jun 13 14:34:34 consul-master-eu-west-1 consul-template[3236]: Allocation "016f43dd" modified: node "e327664b", group "charts-worker"
	Jun 13 14:34:34 consul-master-eu-west-1 consul-template[3236]: Evaluation status changed: "pending" -> "complete"
	Jun 13 14:34:34 consul-master-eu-west-1 consul-template[3236]: ==> Evaluation "b80229a4" finished with status "complete"

**Comment by capone212** [comment] 2016-07-27 15:00
Hi, reproducing it in Nomad v0.4.1-dev.
I have a 3 servers with task running. I have pinned that task to specific server srv1, so it can't be moved to other servers on crash.

`job.Constrain(apiNomad.NewConstraint("${node.unique.name}", "=", "srv1"))`

To reproduce problem I have to just  switch off network cable from srv1. Wait several minutes and reconcile network. When nomad agent returned to cluster it allocates second instance of task, despite "count" in the task group set to 1. This reproduces 100%

**Comment by dadgar** [comment] 2016-07-27 17:15
@capone212 That is expected behavior. Nomad detected that the node was down, stopped the old allocation and when the node came back online it created a new one. If you didn't pin it to a specific machine it would have chosen a different machine when the node was detected as down

**Comment by capone212** [comment] 2016-07-27 17:43
yes. But it didn't stopped old allocation. In fact i see two conquer process for one task. they have conflicting resources so both does not work correctly.

Here is my allocations list

[allocations.txt](https://github.com/hashicorp/nomad/files/386724/allocations.txt)

**Comment by dadgar** [comment] 2016-07-27 18:06
@capone212 Ah interesting! Could you post the job, the client and server logs and any more detailed reproduction steps you think would help! Also can you reproduce this 100% reliably?

**Comment by capone212** [comment] 2016-07-27 18:29
@dadgar To reproduce I just follow instructions:
- 3  windows machines. each nomad is a server and client
- Combine them to cluster
- run one job (see json job spec in attachments) raw_exec driver
- wait a minute
- partition nomad agent with the pinned job
- wait a while.
- observe that http://127.0.01:4646/v1/allocations?pretty returns one allocation  with "ClientStatus": "lost",
- reconcile network. Wait a while.
- observe that http://127.0.01:4646/v1/allocations?pretty returns two allocation  with "ClientStatus": "running"

I reproduces that one more time to collect logs. Then I did one more partition/reconcile loop. In result I have two allocations in "dead" state and task does not run anymore.  
Logs are in "INFO" can connect "DEBUG" on request

[info.zip](https://github.com/hashicorp/nomad/files/386844/info.zip)

**Comment by capone212** [comment] 2016-07-27 18:51
[debug.zip](https://github.com/hashicorp/nomad/files/386890/debug.zip)

Debug logs

**Comment by diptanu** [comment] 2016-07-28 00:55
@capone212 The fix landed on master, can you please test?

**Comment by capone212** [comment] 2016-07-28 17:53
Hi @diptanu 
Updated to last commit. Something is broken... Can't stop running task with "nomad stop". Job is gone but allocation is still running.

**Comment by capone212** [comment] 2016-07-28 17:54
http://127.0.01:4646/v1/jobs?pretty
[jobs.txt](https://github.com/hashicorp/nomad/files/389052/jobs.txt)
http://127.0.01:4646/v1/allocations?pretty
[allocations.txt](https://github.com/hashicorp/nomad/files/389054/allocations.txt)

**Comment by capone212** [comment] 2016-07-28 17:57
This is reproducing during normal operation. Just created new job and tried to stop it

**Comment by capone212** [comment] 2016-07-28 18:08
C:\work\golang.workspace\bin>nomad stop ngprunner.Node1
==> Monitoring evaluation "58334e09"
    Evaluation triggered by job "ngprunner.Node1"
    Evaluation status changed: "pending" -> "failed"
==> Evaluation "58334e09" finished with status "failed"

**Comment by capone212** [comment] 2016-07-28 18:09
2016/07/28 18:48:41.387782 [ERR] worker: failed to submit plan for evaluation 59e5f143-2037-1448-d285-56e9b6358e25: rpc error: error updating job summary: job summary for job "pgrunner.nydl2XDBUT.A-APSHEV2" is not present
    2016/07/28 18:48:41.467780 [ERR] worker: failed to submit plan for evaluation 59e5f143-2037-1448-d285-56e9b6358e25: rpc error: error updating job summary: job summary for job "pgrunner.nydl2XDBUT.A-APSHEV2" is not present
    2016/07/28 18:48:41 [ERR] nomad.fsm: UpsertAllocs failed: error updating job summary: job summary for job "pgrunner.nydl2XDBUT.A-APSHEV2" is not present
    2016/07/28 18:48:41 [ERR] nomad.fsm: UpsertAllocs failed: error updating job summary: job summary for job "pgrunner.nydl2XDBUT.A-APSHEV2" is not present
    2016/07/28 18:48:41 [ERR] nomad.fsm: UpsertAllocs failed: error updating job summary: job summary for job "pgrunner.nydl2XDBUT.A-APSHEV2" is not present
true v1:4068678362174278309
true v1:2998871670322494015
true v1:6049178613256509988
    2016/07/28 19:02:23.013405 [ERR] client: failed to save state for alloc cf86fd90-f951-c61f-5ae8-58be2785ce2f: failed to rename tmp to path: rename C:\work\cluster\nomad\data\client\alloc\cf86fd90-f951-c61f-5ae8-58be2785ce2f\state.json.tmp C:\work\cluster\nomad\data\client\alloc\cf86fd90-f951-c61f-5ae8-58be2785ce2f\state.json: The process cannot access the file because it is being used by another process.
    2016/07/28 19:02:23.013405 [ERR] client: failed to save state: 1 error(s) occurred:

* failed to rename tmp to path: rename C:\work\cluster\nomad\data\client\alloc\cf86fd90-f951-c61f-5ae8-58be2785ce2f\state.json.tmp C:\work\cluster\nomad\data\client\alloc\cf86fd90-f951-c61f-5ae8-58be2785ce2f\state.json: The process cannot access the file because it is being used by another process.
    2016/07/28 19:04:29.717910 [ERR] worker: failed to submit plan for evaluation 58334e09-9c93-5293-c2e4-84ccbb7b4195: rpc error: error updating job summary: job summary for job "ngprunner.Node1" is not present
    2016/07/28 19:04:29 [ERR] nomad.fsm: UpsertAllocs failed: error updating job summary: job summary for job "ngprunner.Node1" is not present
    2016/07/28 19:04:29 [ERR] nomad.fsm: UpsertAllocs failed: error updating job summary: job summary for job "ngprunner.Node1" is not present
    2016/07/28 19:04:29 [ERR] nomad.fsm: UpsertAllocs failed: error updating job summary: job summary for job "ngprunner.Node1" is not present

**Comment by capone212** [comment] 2016-08-08 11:25
Hi @dadgar @diptanu I have checked once again with latest sources. it seems that problem does not appear any more. Thanks for fix. This issue can be closed, I think.

**Comment by dadgar** [comment] 2016-08-08 22:42
Thanks for testing @capone212

**Closed** 2016-08-08 22:49 UTC
Labels: bug, scheduling

**Comment by grobinson-blockchain** [comment] 2016-10-11 11:46
Did this fix make it into Nomad 0.4.1? We still see this issue with that latest release.

**Comment by grobinson-blockchain** [comment] 2016-10-11 12:44
@dadgar Did this fix make it into Nomad 0.4.1? We still see this issue with that latest release.

**Comment by grobinson-blockchain** [comment] 2016-10-11 13:03
Demo job file:

    job "demo" {
        type = "service"
        region = "europe"
        datacenters = ["europe-west1"]

        group "demo" {
            count = 1

            task "demo" {
                driver = "docker"

                config {
                    image = "docker-registry.service.consul:5000/demo:latest"
                    dns_servers = [
                        "172.17.0.1"
                    ]
                    port_map = {
                        http = 8080
                    }
                    labels = {
                      service_name = "demo"
                    }
                }


Output from Nomad plan:

    ~$ nomad plan /etc/nomad/jobs/demo.hcl
    Job: "demo"
    Task Group: "demo" (2 in-place update)
      Task: "demo"

    Scheduler dry-run:
    - All tasks successfully allocated.

    Job Modify Index: 165903

Output from Nomad run:

    ~$ nomad run /etc/nomad/jobs/demo.hcl
    ==> Monitoring evaluation "916772a6"
        Evaluation triggered by job "demo"
        Allocation "39291375" modified: node "e6e55433", group "demo"
        Allocation "86b4c7c1" modified: node "e6e55433", group "demo"
        Evaluation status changed: "pending" -> "complete"
    ==> Evaluation "916772a6" finished with status "complete"

but if I stop the job first:

    nomad plan /etc/nomad/jobs/demo.hcl
    + Job: "demo"
    + Task Group: "demo" (1 create)
      + Task: "demo" (forces create)

    Scheduler dry-run:
    - All tasks successfully allocated.

    Job Modify Index: 0

**Comment by dadgar** [comment] 2016-10-13 00:26
@grobinson-blockchain Is this reproducible for you? The change did go in 0.4.1
