### ISSUE TITLE
Feature request: make 'datacenter' optional or allow for a wildcard

### ISSUE THREAD

**Issue by benvanstaveren** [hashicorp/nomad#9024] opened 2020-10-05 10:47 UTC
Quick use case: we run 3 nomad clusters, each region is comprised of about 4 to 5 datacenters in said region, but our workload doesn't honestly care which datacenter within a region it runs on, as long as a job runs in a particular region. In order to make our developers' lives a bit easier, it'd be great if they can just omit the datacenter entry from the job file, or use something like 

`datacenter = "*"`

Both of these would have the same effect, namely that when datacenter is blank or "*" that any datacenter is acceptable, this perhaps ties into the scheduler code where it could do something smart like give preference to nodes (matching all constraints, of course) in the "least loaded" datacenter. This would partner very well with the new spread scheduler, I feel. 

We're still on Nomad 0.10 so I'm not sure if this has been added/changed already.

**Comment by tgross** [comment] 2020-10-05 12:39
Hi @benvanstaveren! Thanks for opening this issue.

Allowing wildcards seems pretty reasonable to me. From a first-pass implementation standpoint, it looks like we'd need to change the scheduler's [`readyNodesInDCs`](https://github.com/hashicorp/nomad/blob/v0.12.5/scheduler/util.go#L233) function as well as jobspec validation for the datacenter name. I'd also want parity with the [`multiregion.region[*].datacenters`](https://www.nomadproject.io/docs/job-specification/multiregion#datacenters) fields so those get interpolated correctly.

Automatically balancing across datacenters gets a little more computationally tricky. We already allow you to opt-in to that by using a [`spread`](https://www.nomadproject.io/docs/job-specification/spread) stanza against the datacenter attribute, so having some kind of implicit balancing behavior seems to me like it would be a source of unexpected behavior.

**Comment by benvanstaveren** [comment] 2020-10-08 09:42
Could swear I replied to this by email but it didn't show, so to recap the email reply: if the wildcard thing is possible (and doable) then that would be the main thing, scheduling across datacenters, you are right, I forgot all about the spread stanza! 

So basically, being able to wildcard/make optional the 'datacenter' attribute would, in our case, be the cherry on top of our nomad adventure :)

**Comment by jmwilkinson** [comment] 2021-03-19 17:15
To add a use case to this: there is a need to have system jobs that execute once per datacenter. This can in part be accomplished via the "constraint" stanza, but the job still needs to include all the data-centers, and needs to be updated as more are added. It would be really nice to have semantics to do this for us.

**Comment by benvanstaveren** [comment] 2021-03-19 17:18
> 
> 
> To add a use case to this: there is a need to have system jobs that execute once per datacenter. This can in part be accomplished via the "constraint" stanza, but the job still needs to include all the data-centers, and needs to be updated as more are added. It would be really nice to have semantics to do this for us.

Doesn't a service job fit that bill better? System jobs run on every node (matching the constraints given), but if you want a single-job-per-dc then I'd imagine either a single service job with multiple groups (each group constrained to a DC) would do the trick as well. Not automatically, though. Or a system job with a constraint on a meta field that you set on a single node in every DC.

**Comment by jmwilkinson** [comment] 2021-03-19 17:49
The following constraint seems to work ok:

```
constraint {
    operator  = "distinct_property"
    attribute = "${node.datacenter}"
    value     = "1"
}
```
The only problem is that if the allocation is stopped on one DC, I still don't know how to specify that a system job must _always_ be running, so it's not clear to me how to start it again.

But from a deployment perspective, this would work very nicely if there were wildcard dcs, or an "all dcs" option. Without that, the job needs to be updated every time a DC is added/replaced.

**Comment by benvanstaveren** [comment] 2021-03-19 18:20
You shouldn't have to specify it - it should spin up a new allocation if you kill the existing one.

**Comment by jmwilkinson** [comment] 2021-03-19 19:21
Interesting, I have a discussion thread asking a question about that [here](https://discuss.hashicorp.com/t/starting-an-allocation-after-stopping-it/22216). That's not the behavior I'm currently seeing, though. A stopped allocation remains stopped, and a new one is not started.

**Comment by josegonzalez** [comment] 2021-06-02 15:28
+1 Being able to specify a wildcard datacenter would be great. We'd like to change our current rollout mechanism (replace all nodes and let allocs land) to spinning up a new datacenter within a region, marking all existing nodes as ineligible and draining them one-by-one. This assumes the datacenters are joined of course.

Enabling wildcard datacenters would allow us to slowly move workloads over to the new datacenter, but also give us the flexibility of migrating back if there are issues. This would additionally harden our infrastructure against clustering or acl issues, as we can preemptively check the cluster's state to ensure everything is as we expect before moving workloads onto the new cluster.

The alternative is to modify jobs - either in code (untenable when jobs are in their respective repositories), or through some transparent proxy (we're working on such a thing) - and resubmit, but that dance seems less than ideal, and probably annoying to do for system jobs.

**Comment by luckymike** [comment] 2021-06-02 15:35
+1. I think it would make sense for this to also be possible for `region`

**Comment by tgross** [comment] 2023-02-02 14:58
Closed by https://github.com/hashicorp/nomad/pull/11170, which will ship in the upcoming Nomad 1.5.0

**Closed by tgross** 2023-02-02 14:58 UTC
Labels: type/enhancement, theme/scheduling, theme/jobspec, stage/accepted
