### ISSUE TITLE
Change nomad ui base URL when in iframe

### ISSUE THREAD

**Issue by ebarriosjr** [hashicorp/nomad#18651] opened 2023-10-04 08:41 UTC
I am currently trying to show the nomad UI via an embedded iframe in a webpage. Sadly it does not work because of all the href, scripts and js redirects. Is there any way to change the base url to include a path prefix?

### Proposal
My proposal would be to have a variable in the nomad config inside the ui stanza that would let you configure this on a UI wide level.

### Use-cases

This would be beneficial from when the nomad ui is embedded in another page. 

### Attempted Solutions
I tried using nginx to rewrite all the links to include the prefix. It is easily done for the hrefs and scripts but for the js files is a lot more complicated.

**Comment by ebarriosjr** [comment] 2023-10-04 08:43
I saw there is a baseURL already in the code but it seems to be only used for the testing environments. Maybe this could be exposed via the nomad config file.

**Comment by tgross** [comment] 2023-10-04 12:32
I think this is ultimately a duplicate of https://github.com/hashicorp/nomad/issues/6413 ?

**Comment by lgfa29** [comment] 2023-10-04 18:49
> I think this is ultimately a duplicate of #6413 ?

Yup, I think we can consider this a duplicate of #6413, so I'm going to close this one.

@ebarriosjr feel free to reach out if you think they're different. 

Thanks for the report!

**Closed by lgfa29** 2023-10-04 18:49 UTC
Labels: theme/ui
