### ISSUE TITLE
Cinder-CSI Plugin reports 0 healthy nodes/controllers after node decommissioning

### ISSUE THREAD

**Issue by ksitnik-tc** [hashicorp/nomad#10073] opened 2021-02-23 16:19 UTC
### Nomad version
Nomad v1.0.2

### Issue
We run our client nodes with the cinder-csi plugin for persistent storage.

When we decommission client nodes, Nomad reports plugin health status of 0.

For example, prior to stopping the clients,
```
nomad plugin status
Container Storage Interface
ID        Provider                  Controllers Healthy/Expected  Nodes Healthy/Expected
dev  cinder.csi.openstack.org  6/6                           6/6
```

After removing the old clients,
```
nomad plugin status
Container Storage Interface
ID        Provider                  Controllers Healthy/Expected  Nodes Healthy/Expected
dev  cinder.csi.openstack.org  4/0                           4/0
```

Re-applying the cinder-csi plugin job does not remedy this issue.

**Comment by apollo13** [comment] 2021-02-23 20:13
Probably related/similar cause to #9810

**Comment by tgross** [comment] 2022-02-03 17:16
In https://github.com/hashicorp/nomad/issues/11758#issuecomment-1029211330 I've noted what's probably the cause of and fix for this issue:

> The plugin counts don't accurately match the state of allocations. I'm working up a patch the resolves plugin counts in a similar fashion to what we did for volume claims in https://github.com/hashicorp/nomad/pull/11890

**Comment by tgross** [comment] 2022-02-08 20:05
I've just opened https://github.com/hashicorp/nomad/pull/12027 which should close out this issue.

**Closed** 2022-02-09 16:53 UTC
Labels: type/bug, theme/storage, stage/accepted
