### ISSUE TITLE
Dynamic ports with consul-connect integration

### ISSUE THREAD

**Issue by commarla** [hashicorp/nomad#7229] opened 2020-02-26 10:07 UTC
### Nomad version
Nomad v0.10.4-rc1 (eef3009aff5f20e320e00f09952d0f33a324e8b0)

### Operating system and Environment details
Debian 9 on EC2

### Issue
Basic client server app with consul-connect.
It's working well without exposing server port on the host (like in the example provided by `nomad init -connect`)
But if I add a port map on the server to expose the port on the host it's only working if I chose a static port equals the service port.

With a dynamic port I have 
```
Allocation Addresses (mode = "bridge")
Label                            Dynamic  Address
app                              yes      10.72.135.26:23256 -> 5672
connect-proxy-main-rabbitmq-app  yes      10.72.135.26:20497 -> 20497
```

On the server, within the shared namespace, I can see with tcpdump that Envoy is sending packets to the dynamic port allocated by nomad (23256) instead of the local port.
```
root@164b1f9d1be4:/# tcpdump -ni lo 
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes
09:16:55.012899 IP 127.0.0.1.40112 > 127.0.0.1.23256: Flags [S], seq 4123591517, win 43690, options [mss 65495,sackOK,TS val 4035444004 ecr 0,nop,wscale 9], length 0
09:16:55.012905 IP 127.0.0.1.23256 > 127.0.0.1.40112: Flags [R.], seq 0, ack 4123591518, win 0, length 0
```
Envoy should send packets to 5672, the 23256 is only visible on the host in the DNAT iptables rules.

### Job file (if appropriate)
Non working jobspec https://gist.github.com/commarla/519c768042c69eca6257c2c7ea4a6205
Working jobspec https://gist.github.com/commarla/7bf8d40c04990ba4684ddd892cc2e395

Not really sure but it may be related with #6956

**Comment by kamijin-fanta** [comment] 2020-06-23 08:12
This issue does not seem to be fixed in v0.11.

**Comment by kamijin-fanta** [comment] 2020-06-25 09:24
I found a way to work without using static ports. If you specify local_service_port, it works without problems.

But, this behavior difficult. I think that it is better to specify local_service_port by default.

```
// example config
sidecar_service {
  proxy {
    local_service_port = 5672
  }
}
```

**Comment by commarla** [comment] 2021-02-22 10:04
I can't reproduce this issue with nomad 1.0.1 and consul 1.9.1 without changing anything to the jobspec provided in the initial post.

**Comment by zdevwu** [comment] 2021-07-23 11:00
Still having the same problem in v1.1.2.
Modified the example from https://www.nomadproject.io/docs/job-specification/sidecar_service, you will ***have to*** specify the `local_service_port` for the dynamic port to work. Ideally the `local_service_port` should probably take the `to` of the labelled port.
```
    network {
      mode = "bridge"
      port "api" {
        to = 9001
      }
    }

    service {
      name = "count-api"
      port = "api"
      connect {
        sidecar_service {
          proxy {
            local_service_port = 9001
          }
        }
      }
    }
```

**Comment by kirooshu** [comment] 2022-10-05 20:57
We also had similar problem with a job spec which should have worked just find if the default logic of Nomad was taking the `to` part of the port definition as clearly that is where the service is listening. Is there a reason why this was just closed?

Nomad 1.2.8 and Consul 1.11.8 in our infra.

**Comment by tgross** [comment] 2022-10-05 21:06
Hi @kirooshu it was closed over a year ago because it was originally reported against a version 4 major versions before the one you're using and the original reporter reported it as resolved on the version 2 versions before the one you're running. 

At this point it's better to open a new issue describing in detail what symptoms you're seeing today. Thanks!

**Comment by mikenomitch** [comment] 2023-11-17 17:31
I'm reopening this as I think making local_service_port take the "to" value of the service's port automatically makes sense.

**Comment by tgross** [comment] 2024-01-05 14:30
@mikenomitch the service doesn't have a `to` port, it just has a `port` value. And that's what the `local_service_port` is set to by default. In any case, I've just verified this behavior is working as intended. Changing the default behavior of the `local_service_port` at this point would break many existing jobs.

To reproduce, I'm using this jobspec, which is identical to the output of `nomad job init -short -connect` except with the `static = 9002` port of the dashboard group commented out.

<details><summary>jobspec</summary>

```hcl
job "countdash" {

  group "api" {
    network {
      mode = "bridge"
    }

    service {
      name = "count-api"
      port = "9001"

      connect {
        sidecar_service {}
      }
    }

    task "web" {
      driver = "docker"

      config {
        image          = "hashicorpdev/counter-api:v3"
        auth_soft_fail = true
      }
    }
  }

  group "dashboard" {
    network {
      mode = "bridge"

      port "http" {
        # NOTE: commented out from nomad job init -short -connect
        # static = 9002
        to = 9002
      }
    }

    service {
      name = "count-dashboard"
      port = "9002"

      connect {

        sidecar_service {
          proxy {
            upstreams {
              destination_name = "count-api"
              local_bind_port  = 8080
            }
          }
        }
      }
    }

    task "dashboard" {
      driver = "docker"

      template {
        data = <<EOT
{{- range service "count-api" }}
API_ADDR=http://{{ .Address }}:{{ .Port }}{{- end }}
EOT

        destination = "local/count-api.txt"
      }

      env {
        COUNTING_SERVICE_URL = "http://${NOMAD_UPSTREAM_ADDR_count_api}"
      }

      config {
        image          = "hashicorpdev/counter-dashboard:v3"
        auth_soft_fail = true
      }
    }
  }
}
```

</details>

Run the job, and look at the allocation status for the dashboard task:

```
$ nomad alloc status b8b
...
Allocation Addresses (mode = "bridge"):
Label                           Dynamic  Address
*http                           yes      192.168.1.77:30566 -> 9002
*connect-proxy-count-dashboard  yes      192.168.1.77:26430 -> 26430
...
```

If I hit `192.168.1.77:30566` in my browser, it works which is what I'd expect. If I wanted to hit 9002 instead, I'd need to use the `static` port, which is exactly what I'd expect.

I'm going to close this issue as working as intended. If there's a concern otherwise, we should open a new issue with the appropriate context and reproduction.

**Closed by tgross** 2024-01-05 14:30 UTC
Labels: theme/networking, theme/consul/connect

**Comment by blake** [comment] 2024-01-10 02:44
@tgross, the problem is that port registered in Consul for the `count-dashboard` service is not correct. This configuration registers port 9002 as the application's service port. However, that port is not directly reachable in this configuration. External clients would need to use port dynamically allocated port of 30566 in order to access the dashboard service outside of the service mesh.

If the port field in the `service {} ` block is changed to use the named port (i.e., `port = "http"`), the dynamically allocated port is correctly published in Consul, but then that breaks service mesh traffic as Envoy is also trying to forward traffic to the local application at the dynamically allocated port, not port 9002.

The solution is to specify to `local_service_port` in the proxy configuration so that Envoy is correctly configured to forward traffic to the local application, and the application is still reachable by downstream that are not in the mesh via communicating with the service over the dynamically allocated port.

**Comment by tgross** [comment] 2024-01-10 13:39
This issue is going to remain closed and we can open a new issue if there's still anything real to this.
