### ISSUE TITLE
services with nomad SD do not support `script` type checks?

### ISSUE THREAD

**Issue by geekodour** [hashicorp/nomad#23833] opened 2024-08-15 20:28 UTC
I was trying to add a `script` type healthcheck. and I am using nomad SD.
I thought this was straightforward from https://developer.hashicorp.com/nomad/docs/v1.7.x/job-specification/check but it seems like `script` type is not allowed in non-consul services.

Is there any limitations to this? If this is a oversight. would like to send in a patch otherwise can we know why is this the case for services with normal SD?

https://github.com/hashicorp/nomad/blob/0bc9796d3b892b0f0c86fb37c5644f41a4a5c076/nomad/structs/services.go#L350

cc: @tgross 

related issue: https://github.com/hashicorp/nomad/issues/8952

**Comment by tgross** [comment] 2024-08-15 20:31
Right. From the [check.type](https://developer.hashicorp.com/nomad/docs/job-specification/check#type) docs:
> [type](https://developer.hashicorp.com/nomad/docs/job-specification/check#type) (string: <required>) - This indicates the check types supported by Nomad. For Consul service checks, valid options are grpc, http, script, and tcp. For Nomad service checks, valid options are http and tcp.

I'm going to close this issue as a duplicate of https://github.com/hashicorp/nomad/issues/23783. If you're interested in submitting a patch we'd love to have one!

**Closed by tgross** 2024-08-15 20:31 UTC
