### ISSUE TITLE
[Improvement] Allow user to pass his own variables when submitting jobspec

### ISSUE THREAD

**Issue by amelnikov-mylivn** [hashicorp/nomad#2821] opened 2017-07-11 10:18 UTC
### Proposal
Support passing variables for interpolation using `nomad run`.

### Use case
Sometimes you cannot specify all environment variable values in your jobspec file:
- you do not want to commit jobspec with sensitive data, but you can get it when you run it
- you do not know exact values when you create jobspec (i.e. commit ref that CI provides you)
- you want your jobspec to be parametrized from command line

#### Capture client env vars
`nomad run` can just capture all client environment variables and pass them alongside with jobspec to server. On server you can treat them as low priority values, meaning that same vars defined on server will override those from client.

#### Pass vars explicitly from command line
`nomad run --address=<SERVER_ADDRESS> -e USER_VAR_1=<USER_VALUE_1> -e USER_VAR_2=<USER_VALUE_2>` example.service

### Usage in jobspec
The goal of this proposal to be able to do like
```
...
env {
    SETTING_1="${USER_VAR_1}"
    SETTING_2="${USER_VAR_2}"
}
...
or
...
meta {
   meta-key-1="${USER_VAR_1}"
   meta-key-2="${USER_VAR_2}"
}
...
```

**Comment by dadgar** [comment] 2017-07-11 16:42
Hey thanks for the issue. I am going to close as it is a duplicate of:
https://github.com/hashicorp/nomad/issues/1185
https://github.com/hashicorp/nomad/issues/2422

**Closed by dadgar** 2017-07-11 16:42 UTC
