### ISSUE TITLE
Error initializing client: invalid address. No closing '. Not clear error message

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#20023] opened 2024-02-21 23:11 UTC
### Nomad version
```
Nomad v1.6.1
BuildDate 2023-07-21T13:49:42Z
Revision 515895c7690cdc72278018dc5dc58aca41204ccc
```

### Operating system and Environment details
```
uname -a
Darwin Eugens-MacBook-Pro.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:27 PDT 2023; root:xnu-10002.41.9~6/RELEASE_X86_64 x86_64 i386 Darwin
```

### Issue
![image](https://github.com/hashicorp/nomad/assets/139780495/d55b5b0b-9962-4fe3-9e2d-54b287154dd2)

```
Error initializing client: invalid address '╷
│ Warning: No outputs found
│
│ The state file either has no outputs defined, or all the defined outputs are empty. Please define an output in
│ your configuration with the `output` keyword and run `terraform refresh` for it to become available. If you are
│ using interpolation, please verify the interpolated value is not empty. You can use the `terraform console`
│ command to assist.
╵:4646': parse "\x1b[33m╷\x1b[0m\x1b[0m\n\x1b[33m│\x1b[0m \x1b[0m\x1b[1m\x1b[33mWarning: \x1b[0m\x1b[0m\x1b[1mNo outputs found\x1b[0m\n\x1b[33m│\x1b[0m \x1b[0m\n\x1b[33m│\x1b[0m \x1b[0m\x1b[0mThe state file either has no outputs defined, or all the defined outputs are empty. Please define an output in\n\x1b[33m│\x1b[0m \x1b[0myour configuration with the `output` keyword and run `terraform refresh` for it to become available. If you are\n\x1b[33m│\x1b[0m \x1b[0musing interpolation, please verify the interpolated value is not empty. You can use the `terraform console`\n\x1b[33m│\x1b[0m \x1b[0mcommand to assist.\n\x1b[33m╵\x1b[0m\x1b[0m:4646": net/url: invalid control character in URL
```

### Reproduction steps
```
$ env | grep NOM
NOMAD_TOKEN=
NOMAD_ADDR=╷
```

#### Expected Result
Error initializing client: invalid address `https://╷:4646`

Here you should use actual normalized result. 

#### Actual Result
Not clear error message

### Job file (if appropriate)

Not relevant

**Comment by EugenKon** [comment] 2024-02-21 23:13
Hm... ok. This is not error, this is output from the next command:
```
terraform output -raw lb_address_consul_nomad
╷
│ Warning: No outputs found
│
│ The state file either has no outputs defined, or all the defined outputs are empty. Please define an output in
│ your configuration with the `output` keyword and run `terraform refresh` for it to become available. If you are
│ using interpolation, please verify the interpolated value is not empty. You can use the `terraform console`
│ command to assist.
╵
```

**Comment by jrasell** [comment] 2024-02-22 08:39
Hi @EugenKon and thanks for raising this issue. I tried to reproduce this locally, but I saw different results to those you got and the error returns look useful enough to figure out what is happening.

```
$ env |grep NOMAD_ADDR
NOMAD_ADDR=╷
```

```
$ nomad job plan example.nomad.hcl
Error during plan: Put "/v1/job/example/plan": unsupported protocol scheme ""
```

I tested adding a protocol on the Nomad address variable as well as just adding the protocol (without the comma) and again the errors seem OK.

```
$ nomad job plan example.nomad.hcl
Error during plan: Put "http:///v1/job/example/plan": http: no Host in request URL

$ nomad job plan example.nomad.hcl
Error during plan: Put "http://%E2%95%B7/v1/job/example/plan": dial tcp: lookup xn--nzh: no such host
```

The error we do get comes from the [url.Parse](https://github.com/hashicorp/nomad/blob/e4e70b086a304e4e80496d95f514a4de6e926b3b/api/api.go#L513) stdlib function, so if we did want to change any output, it would need to be how the string is formatted. Please let me know your thoughts.

**Comment by EugenKon** [comment] 2024-02-22 13:48
I am understand now better what is going on. Try next steps instead:
1. Go to empty directory and run commands
2. Change directory with `.hcl` file and plan
![image](https://github.com/hashicorp/nomad/assets/139780495/5a2f7989-5127-4950-aff9-9db027f5ba9e)

**Comment by tgross** [comment] 2024-02-22 21:55
@EugenKon it looks like you're getting Terraform error messages from that `nomad job plan` call at (2) in your screenshot. Is your Nomad CLI an alias to something else?

**Comment by EugenKon** [comment] 2024-06-06 13:28
No, `nomad` is not aliased:
![image](https://github.com/hashicorp/nomad/assets/139780495/894891ea-9217-4741-aaff-e85f5a17a4a3)

I think the problem was with this command:

![image](https://github.com/hashicorp/nomad/assets/139780495/5fcd01ac-2f0d-4079-8a6e-bdd3626b6e62)

**Comment by jrasell** [comment] 2024-10-31 10:12
Closing as the error seems to be coming from an erroneous Terraform command call which states no outputs are available.

**Closed by jrasell** 2024-10-31 10:12 UTC
Labels: type/bug, stage/waiting-reply

**Comment by EugenKon** [comment] 2024-10-31 13:03
@jrasell Still it would be nice to see correct error message if `NOMAD_ADDR` does not have correct format instead of a bunch of something.
eg. `Error initializing client: NOMAD_ADDR is invalid`
