### ISSUE TITLE
Allow for dynamically configuring dispatch job resources

### ISSUE THREAD

**Issue by jelmersnoeck** [hashicorp/nomad#12228] opened 2022-03-08 16:05 UTC
### Proposal

Currently, it's possible to set up resource constraints for batch jobs when defining the job itself:

```hcl
# example.nomad
job "workflow" {
  type = "batch"

  group "workflow" {
    task "workflow" {
      // …
      resources {
        memory = 256
        cpu = 500
      }
    }
  }
}
```

This is however limited to the global batch job specification, and is not changeable on a per batch-job run basis. If we try to parameterize this, we get an error that the value is not an integer:

```hcl
# example.nomad
job "workflow" {
  type = "batch"

  parameterized {
    payload = "optional"
    meta_required = ["memory"]
  }

  group "workflow" {
    task "workflow" {
      // …
      resources {
        memory = "${NOMAD_META_MEMORY}"
      }
    }
  }
}
```

```
nomad run example.nomad
> Unsuitable value type; Unsuitable value: a number is required
```

(*Note:* when using just `${NOMAD_META_MEMORY}` instead of `"${NOMAD_META_MEMORY}"` we get the error `Unsuitable value type; Unsuitable value: value must be known`)

### Use-cases

We are using dispatch jobs to dynamically run one of jobs with different configuration. Based on the configuration, the resource constraints can differ (from 50MB to 500MB, for example). To optimize resource utilization, we want to be able to set this dynamically per job so that we don't have to request 500MB for all jobs.

### Attempted Solutions

We currently set the value to the highest observed resource utilization, meaning that all other batch jobs are over provisioned.

**Comment by tgross** [comment] 2022-03-08 16:34
Hi @jelmersnoeck! This is something we've been asked for before, so I'm going to close this as a duplicate of  https://github.com/hashicorp/nomad/issues/8259. If you give that issue a :+1: and/or add more use cases, that'll help surface the issue when we're doing roadmapping. Thanks!

**Closed by tgross** 2022-03-08 16:34 UTC
Labels: type/enhancement
