### ISSUE TITLE
[Improvement] Source environment variables from consul-template

### ISSUE THREAD

**Issue by samber** [hashicorp/nomad#2217] opened 2017-01-19 15:16 UTC
Hi guys,

I wonder how do you manage environment variables from consul k/v ?
We would like to use your implementation of consul-template with the template stanza, but there is no way to “source” the generated file.

What do you think about developing an env_file stanza in config or task ? Like the following:

```
task “redis” {
   driver = "docker"
   config {
        image = “redis:3.2”
   }

    env_file {
        source = “local/.env”
    }
    env {
        other_key = "other_value"
    }

    template {
	source = “local/.env.dist”
        destination = “local/.env”
    }
}
```

or

```
task “redis” {
   driver = "docker"
   config {
        image = “redis:3.2”
        dot_env = “local/.env”
   }

    env {
        other_key = "other_value"
    }

    template {
	source = “local/.env.dist”
        destination = “local/.env”
    }
}
```

**Comment by dadgar** [comment] 2017-01-23 02:20
Hey,

This is a duplicate of this issue: https://github.com/hashicorp/nomad/issues/1765

Hopefully be able to have this functionality soon 👍

**Closed by dadgar** 2017-01-23 02:20 UTC

**Comment by nanoz** [comment] 2017-01-25 09:40
Hi @dadgar,

I think there is still a usage to include the env_file option, at least for the Docker driver. You might want to download this env file from an artefact, or use advanced consul-template options in order to generate your env file.

Would you refuse a PR implementing that change ?
If so, where do you think the env_file parameter should be placed ? In the Docker driver config {} or in something more generic ?

**Comment by dadgar** [comment] 2017-01-31 17:32
@nanoz Can you explain a case where you would need an env_file given that the job file allows you to specify environment variables and env_consul support?

Generally avoid having many ways to do one thing.

**Comment by rokka-n** [comment] 2017-02-04 19:30
@dadgar This a general problem with development workflow: when nomad is ready to fire - there is already the whole bunch of settings for an application:
in docker compose
in .env files
exports for a shell
terraform outputs
and the list can go on and on

All that should be stored in consul, but nomad can't read yer from consul kv yet. This creates quite a large gap in your definition of the application lifecycle: build, test, package, provision, secure and then suddenly deploy step is on its own.

Nomad should get a first class support of making deploy step as easy as possible.

Amazon provided an elegant solution for lambda for a very similar problem.
http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html

**Comment by dadgar** [comment] 2017-02-06 18:43
@rokka-n Reading from Consul would happen at the clients not on the machine that submits the job so the CI example wouldn't be a problem. Further we support adding environment variables natively: https://www.nomadproject.io/docs/job-specification/env.html.
