### ISSUE TITLE
Cannot get any of the drivers to work on arm64

### ISSUE THREAD

**Issue by l1x** [hashicorp/nomad#10259] opened 2021-03-30 12:21 UTC
### Nomad version

```
/opt/nomad/bin/nomad -version
Nomad v1.0.4 (149b150fb2d87766b8462346d68b72831f622047+CHANGES)
```

### Operating system and Environment details

arm64 / Debian 11

### Issue

I was trying to get the following driver to work:

- java
- lxc
- docker
- containerd

### Reproduction steps

Install Nomad on arm64 / Debian 11 and try to do the same

#### Expected Result

Working Nomad cluster

#### Actual Result

```
2021-03-30T12:13:57.770Z [DEBUG] client.driver_mgr.docker: cancelling removal of container image: driver=docker image_name=alpine:3.13.3
    2021-03-30T12:13:57.770Z [DEBUG] client.driver_mgr.docker: image reference count incremented: driver=docker image_name=alpine:3.13.3 image_id=sha256:831773d30abfa7dba154735633cb68bc02d97a48e1214c31a749b23f4fad6d7e references=1
    2021-03-30T12:13:57.771Z [DEBUG] client.driver_mgr.docker: configured resources: driver=docker task_name=test-task memory=268435456 memory_reservation=0 cpu_shares=500 cpu_quota=0 cpu_period=0
    2021-03-30T12:13:57.771Z [DEBUG] client.driver_mgr.docker: binding directories: driver=docker task_name=test-task binds="[]string{"/opt/nomad/data/alloc/4d95f8db-6961-bcd0-1cd6-7f9921ce4e07/alloc:/alloc", "/opt/nomad/data/alloc/4d95f8db-6961-bcd0-1cd6-7f9921ce4e07/test-task/local:/local", "/opt/nomad/data/alloc/4d95f8db-6961-bcd0-1cd6-7f9921ce4e07/test-task/secrets:/secrets"}"
    2021-03-30T12:13:57.771Z [DEBUG] client.driver_mgr.docker: networking mode not specified; using default: driver=docker task_name=test-task
    2021-03-30T12:13:57.771Z [DEBUG] client.driver_mgr.docker: applied labels on the container: driver=docker task_name=test-task labels=map[com.hashicorp.nomad.alloc_id:4d95f8db-6961-bcd0-1cd6-7f9921ce4e07]
    2021-03-30T12:13:57.771Z [DEBUG] client.driver_mgr.docker: setting container name: driver=docker task_name=test-task container_name=test-task-4d95f8db-6961-bcd0-1cd6-7f9921ce4e07
    2021-03-30T12:13:58.066Z [INFO]  client.driver_mgr.docker: created container: driver=docker container_id=dd3625722d74bebece82819d606d83c4531cad90308abbfa1d38d87044969828
    2021-03-30T12:13:59.426Z [INFO]  client.driver_mgr.docker: started container: driver=docker container_id=dd3625722d74bebece82819d606d83c4531cad90308abbfa1d38d87044969828
    2021-03-30T12:13:59.426Z [DEBUG] client.driver_mgr.docker.docker_logger: starting plugin: driver=docker path=/opt/nomad/bin/nomad args=[/opt/nomad/bin/nomad, docker_logger]
    2021-03-30T12:13:59.428Z [DEBUG] client.driver_mgr.docker.docker_logger: plugin started: driver=docker path=/opt/nomad/bin/nomad pid=2891
    2021-03-30T12:13:59.428Z [DEBUG] client.driver_mgr.docker.docker_logger: waiting for RPC address: driver=docker path=/opt/nomad/bin/nomad
    2021-03-30T12:13:59.450Z [DEBUG] client.driver_mgr.docker.docker_logger.nomad: plugin address: driver=docker address=/tmp/plugin132400096 network=unix @module=docker_logger timestamp=2021-03-30T12:13:59.450Z
    2021-03-30T12:13:59.450Z [DEBUG] client.driver_mgr.docker.docker_logger: using plugin: driver=docker version=2
    2021-03-30T12:13:59.453Z [DEBUG] client.driver_mgr.docker.docker_logger.nomad: using client connection initialized from environment: driver=docker @module=docker_logger timestamp=2021-03-30T12:13:59.453Z
    2021-03-30T12:13:59.466Z [DEBUG] client.driver_mgr.docker.docker_logger: plugin process exited: driver=docker path=/opt/nomad/bin/nomad pid=2891
    2021-03-30T12:13:59.466Z [DEBUG] client.driver_mgr.docker.docker_logger: plugin exited: driver=docker
    2021-03-30T12:13:59.478Z [DEBUG] client.alloc_runner.task_runner.task_hook.stats_hook: failed to start stats collection for task with unrecoverable error: alloc_id=4d95f8db-6961-bcd0-1cd6-7f9921ce4e07 task=test-task error="container stopped"
    2021-03-30T12:13:59.508Z [DEBUG] client.driver_mgr.docker: image id reference count decremented: driver=docker image_id=sha256:831773d30abfa7dba154735633cb68bc02d97a48e1214c31a749b23f4fad6d7e references=0
```

### Job file (if appropriate)

```
job "test-job" {
  datacenters = ["dc1"]

  group "test-group" {
    task "test-task" {
      driver = "docker"

      config {
        image = "alpine:3.13.3"
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

### Nomad Server logs (if appropriate)

```
    2021-03-30T12:18:27.151Z [DEBUG] client.driver_mgr.docker: setting container name: driver=docker task_name=test-task container_name=test-task-7630311b-b40e-9c9e-1354-e8142363a59f
    2021-03-30T12:18:41.317Z [INFO]  client.driver_mgr.docker: created container: driver=docker container_id=d83fde5d7665f0ce031422cc3b79578d0dc3b81fed0b425c0404018ae56eb89c
    2021-03-30T12:18:48.292Z [INFO]  client.driver_mgr.docker: started container: driver=docker container_id=d83fde5d7665f0ce031422cc3b79578d0dc3b81fed0b425c0404018ae56eb89c
    2021-03-30T12:18:48.292Z [DEBUG] client.driver_mgr.docker.docker_logger: starting plugin: driver=docker path=/opt/nomad/bin/nomad args=[/opt/nomad/bin/nomad, docker_logger]
    2021-03-30T12:18:48.294Z [DEBUG] client.driver_mgr.docker.docker_logger: plugin started: driver=docker path=/opt/nomad/bin/nomad pid=3104
    2021-03-30T12:18:48.295Z [DEBUG] client.driver_mgr.docker.docker_logger: waiting for RPC address: driver=docker path=/opt/nomad/bin/nomad
    2021-03-30T12:18:48.339Z [DEBUG] client.driver_mgr.docker.docker_logger.nomad: plugin address: driver=docker @module=docker_logger address=/tmp/plugin130102293 network=unix timestamp=2021-03-30T12:18:48.338Z
    2021-03-30T12:18:48.339Z [DEBUG] client.driver_mgr.docker.docker_logger: using plugin: driver=docker version=2
    2021-03-30T12:18:48.352Z [DEBUG] client.driver_mgr.docker.docker_logger.nomad: using client connection initialized from environment: driver=docker @module=docker_logger timestamp=2021-03-30T12:18:48.351Z
    2021-03-30T12:18:48.381Z [DEBUG] client.driver_mgr.docker.docker_logger: plugin process exited: driver=docker path=/opt/nomad/bin/nomad pid=3104
    2021-03-30T12:18:48.382Z [DEBUG] client.driver_mgr.docker.docker_logger: plugin exited: driver=docker
    2021-03-30T12:18:49.852Z [DEBUG] client.alloc_runner.task_runner.task_hook.stats_hook: failed to start stats collection for task with unrecoverable error: alloc_id=7630311b-b40e-9c9e-1354-e8142363a59f task=test-task error="container stopped"
    2021-03-30T12:18:49.955Z [DEBUG] client.driver_mgr.docker: image id reference count decremented: driver=docker image_id=sha256:831773d30abfa7dba154735633cb68bc02d97a48e1214c31a749b23f4fad6d7e references=0
    2021-03-30T12:18:49.955Z [INFO]  client.alloc_runner.task_runner: not restarting task: alloc_id=7630311b-b40e-9c9e-1354-e8142363a59f task=test-task reason="Exceeded allowed attempts 2 in interval 30m0s and mode is "fail""

```

Focusing on docker:

```
 docker run -ti --rm alpine:3.13.3 date
Tue Mar 30 12:19:59 UTC 2021
```

```
uname -a
Linux rpi4-2.lan 5.10.0-5-arm64 #1 SMP Debian 5.10.24-1 (2021-03-19) aarch64 GNU/Linux
cat /etc/issue.net
Debian GNU/Linux bullseye/sid
```

**Comment by drewbailey** [comment] 2021-03-30 17:03
@l1x sorry you are running into issues. Could you please provide some additional details to help figure out what may be going on?

- output of `nomad node status -verbose <node_id>`
- docker logs from failed container

**Comment by l1x** [comment] 2021-03-30 17:50
> @l1x sorry you are running into issues. Could you please provide some additional details to help figure out what may be going on?
> 
> * output of `nomad node status -verbose <node_id>`
> * docker logs from failed container

```
nomad@rpi4-2:/opt/nomad$ ./bin/nomad node status -verbose cedfd833
ID              = cedfd833-cdd7-fbfb-2c5e-e46f80df8bc4
Name            = rpi3-1.lan
Class           = <none>
DC              = dc1
Drain           = false
Eligibility     = eligible
Status          = ready
CSI Controllers = <none>
CSI Drivers     = <none>
Uptime          = 6h13m46s

Drivers
Driver       Detected  Healthy  Message   Time
docker       true      true     Healthy   2021-03-30T17:38:41Z
exec         true      true     Healthy   2021-03-30T17:38:41Z
java         true      true     Healthy   2021-03-30T17:38:42Z
mock_driver  true      true     Healthy   2021-03-30T17:38:42Z
qemu         false     false    <none>    2021-03-30T17:38:41Z
raw_exec     false     false    disabled  2021-03-30T17:38:41Z

Node Events
Time                  Subsystem  Message          Details
2021-03-30T11:59:08Z  Cluster    Node registered  <none>

Allocated Resources
CPU         Memory       Disk
0/4800 MHz  0 B/906 MiB  0 B/22 GiB
Allocations
ID                                    Eval ID                               Node ID                               Task Group  Version  Desired  Status  Created               Modified
7630311b-b40e-9c9e-1354-e8142363a59f  f9a1243c-48c8-94f8-e287-c6d6b1fda6cb  cedfd833-cdd7-fbfb-2c5e-e46f80df8bc4  test-group  1        run      failed  2021-03-30T12:16:16Z  2021-03-30T17:38:42Z
805518ab-d7f4-73c8-1cf0-67d642e33d75  82a36258-4bd4-33f8-cff5-5e253cb8f0db  cedfd833-cdd7-fbfb-2c5e-e46f80df8bc4  test-group  1        stop     failed  2021-03-30T12:09:08Z  2021-03-30T17:38:42Z

Attributes
cpu.arch                  = arm64
cpu.frequency             = 1200
cpu.numcores              = 4
cpu.totalcompute          = 4800
driver.docker             = 1
driver.docker.bridge_ip   = 172.17.0.1
driver.docker.os_type     = linux
driver.docker.runtimes    = io.containerd.runc.v2,io.containerd.runtime.v1.linux,runc
driver.docker.version     = 20.10.5
driver.exec               = 1
driver.java               = 1
driver.java.runtime       = OpenJDK Runtime Environment (build 11.0.11-ea+4-post-Debian-1)
driver.java.version       = 11.0.11-ea
driver.java.vm            = OpenJDK 64-Bit Server VM (build 11.0.11-ea+4-post-Debian-1, mixed mode)
driver.mock               = true
driver.mock_driver        = 1
kernel.name               = linux
kernel.version            = 5.10.0-5-arm64
memory.totalbytes         = 950878208
nomad.advertise.address   = 10.10.10.101:4646
nomad.revision            = 149b150fb2d87766b8462346d68b72831f622047+CHANGES
nomad.version             = 1.0.4
os.name                   = debian
os.signals                = SIGALRM,SIGBUS,SIGCONT,SIGTSTP,SIGXFSZ,SIGIOT,SIGTERM,SIGXCPU,SIGABRT,SIGSYS,SIGFPE,SIGPROF,SIGTRAP,SIGUSR1,SIGKILL,SIGSEGV,SIGQUIT,SIGTTIN,SIGTTOU,SIGUSR2,SIGCHLD,SIGHUP,SIGILL,SIGINT,SIGIO,SIGPIPE,SIGSTOP,SIGURG,SIGWINCH
os.version                = bullseye/sid
unique.cgroup.mountpoint  = /sys/fs/cgroup
unique.hostname           = rpi3-1.lan
unique.network.ip-address = 10.10.10.101
unique.storage.bytesfree  = 23817605120
unique.storage.bytestotal = 30302523392
unique.storage.volume     = /dev/mmcblk0p2
Meta
connect.gateway_image     = envoyproxy/envoy:v${NOMAD_envoy_version}
connect.log_level         = info
connect.proxy_concurrency = 1
connect.sidecar_image     = envoyproxy/envoy:v${NOMAD_envoy_version}
```

**Comment by l1x** [comment] 2021-03-30 17:53
I do not know how to correlate Nomad errors to Docker errors.

```
Mar 30 16:03:23 rpi4-2.lan containerd[475]: time="2021-03-30T16:03:23.533152809Z" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/7c462dec>
Mar 30 16:03:24 rpi4-2.lan containerd[475]: time="2021-03-30T16:03:24.251308947Z" level=info msg="shim disconnected" id=7c462dec63c6ce509b524d2ff662f8c4947c5fa38931254507fc6a5718274d27
Mar 30 16:03:24 rpi4-2.lan containerd[475]: time="2021-03-30T16:03:24.251494595Z" level=error msg="copy shim log" error="read /proc/self/fd/9: file already closed"
Mar 30 16:03:25 rpi4-2.lan containerd[475]: time="2021-03-30T16:03:25.344304563Z" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/0a9b14b9>
Mar 30 16:03:26 rpi4-2.lan containerd[475]: time="2021-03-30T16:03:26.018777297Z" level=info msg="shim disconnected" id=0a9b14b9d3931c4286c731ec8ae1514b49365606f78801075f505814b269dd39
Mar 30 16:03:26 rpi4-2.lan containerd[475]: time="2021-03-30T16:03:26.018954538Z" level=error msg="copy shim log" error="read /proc/self/fd/9: file already closed"
Mar 30 16:03:27 rpi4-2.lan containerd[475]: time="2021-03-30T16:03:27.174089271Z" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/7bcd0815>
Mar 30 16:03:27 rpi4-2.lan containerd[475]: time="2021-03-30T16:03:27.854154931Z" level=info msg="shim disconnected" id=7bcd0815c2db81c22c59479df2e184df825bc453f7d8acaea71dc8fcc4e2b1ad
Mar 30 16:03:27 rpi4-2.lan containerd[475]: time="2021-03-30T16:03:27.854340541Z" level=error msg="copy shim log" error="read /proc/self/fd/9: file already closed"
```

It is quite surprising to me that even with DEBUG loglevel I could not gather an information what Nomad is actually doing. All the logs are 0 bytes in /alloc. I ended up running Nomad in foreground mode but still. I see all the HTTP calls but nothing about what Nomad is actually trying to do. Is there a way to investigate why Nomad is unable to do basic workflows?

**Comment by drewbailey** [comment] 2021-03-30 18:47
@l1x thanks for the additional information, could you please provide the output of some of the failed allocations
`nomad alloc status <failed_alloc_id>`

**Comment by drewbailey** [comment] 2021-03-30 21:32
@l1x the job file you posted also will just exit right away, so this seems to be the expected behavior. Could you try something like redis?

```
job "test-job" {
  datacenters = ["dc1"]

  group "test-group" {
    task "test-task" {
      driver = "docker"

      config {
        image = "redis:latest"
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

**Comment by drewbailey** [comment] 2021-03-31 13:18
@l1x you'll want to look at the output of `nomad status <alloc_id>` 

```
ID                  = e3629608-4020-03fd-8d8e-ebac4e7cfd78
Eval ID             = ee927489
Name                = test-java.test-group[0]
Node ID             = bfaaf389
Node Name           = ip-172-31-16-89
Job ID              = test-java
Job Version         = 2
Client Status       = pending
Client Description  = No tasks have started
Desired Status      = run
Desired Description = <none>
Created             = 13s ago
Modified            = 6s ago
Deployment ID       = cea18305
Deployment Health   = unset

Task "test-task" is "pending"
Task Resources
CPU        Memory           Disk     Addresses
0/500 MHz  8.8 MiB/256 MiB  300 MiB

Task Events:
Started At     = 2021-03-31T13:12:18Z
Finished At    = N/A
Total Restarts = 1
Last Restart   = 2021-03-31T13:12:23Z

Recent Events:
Time                  Type                   Description
2021-03-31T13:12:23Z  Restarting             Task restarting in 17.712437673s
2021-03-31T13:12:23Z  Terminated             Exit Code: 0
2021-03-31T13:12:18Z  Started                Task started by client
2021-03-31T13:12:18Z  Downloading Artifacts  Client is downloading artifacts
2021-03-31T13:12:16Z  Task Setup             Building Task Directory
2021-03-31T13:12:16Z  Received               Task received by client
```

This job just prints a message and exits so Exit Code 0 is expected. The client logs should also have some information about starting the allocation

```
Mar 31 13:12:41 ip-172-31-16-89 nomad[7149]:     2021-03-31T13:12:41.506Z [INFO]  client.driver_mgr.java: starting java task: driver=java driver_cfg="{Class:Hello ClassPath:/local JarPath: JvmOpts:[] Args:[] ModeP
Mar 31 13:12:41 ip-172-31-16-89 nomad[7149]:     2021-03-31T13:12:41.506Z [DEBUG] client.driver_mgr.java.executor: starting plugin: alloc_id=e3629608-4020-03fd-8d8e-ebac4e7cfd78 driver=java task_name=test-task pat
Mar 31 13:12:41 ip-172-31-16-89 nomad[7149]:     2021-03-31T13:12:41.506Z [DEBUG] client.driver_mgr.java.executor: plugin started: alloc_id=e3629608-4020-03fd-8d8e-ebac4e7cfd78 driver=java task_name=test-task path
Mar 31 13:12:41 ip-172-31-16-89 nomad[7149]:     2021-03-31T13:12:41.506Z [DEBUG] client.driver_mgr.java.executor: waiting for RPC address: alloc_id=e3629608-4020-03fd-8d8e-ebac4e7cfd78 driver=java task_name=test-
Mar 31 13:12:41 ip-172-31-16-89 nomad[7149]:     2021-03-31T13:12:41.515Z [DEBUG] client.driver_mgr.java.executor: using plugin: alloc_id=e3629608-4020-03fd-8d8e-ebac4e7cfd78 driver=java task_name=test-task versio
```

Here is the nomad file I used

```
job "test-java" {
  datacenters = ["dc1"]

  group "test-group" {
    task "test-task" {
      driver = "java"

      config {
        class = "Hello"
        class_path = "${NOMAD_TASK_DIR}"
      }

      artifact {
        source = "https://github.com/hashicorp/nomad/blob/main/drivers/java/test-resources/Hello.class?raw=true"
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

I don't think there is a bug here so I am going to close the issue for now. Please feel free to post on discuss.hashicorp.com about any of the other drivers you are working with.

**Closed by drewbailey** 2021-03-31 13:18 UTC
Labels: stage/needs-investigation, stage/waiting-reply, theme/platform-arm, type/bug

**Comment by l1x** [comment] 2021-03-31 15:04
Thanks @drewbailey
