### ISSUE TITLE
Disk Resources in Task

### ISSUE THREAD

**Issue by Miserlou** [hashicorp/nomad#4694] opened 2018-09-18 21:24 UTC
Here was a typical task death for us:

```
nomad status 9d5a915d
ID                  = 9d5a915d
Eval ID             = cc292bdf
Name                = DOWNLOADER/dispatch-1537291949-5b0a71df.jobs[0]
Node ID             = d1f48c42
Job ID              = DOWNLOADER/dispatch-1537291949-5b0a71df
Job Version         = 0
Client Status       = failed
Client Description  = <none>
Desired Status      = run
Desired Description = <none>
Created             = 3h25m ago
Modified            = 2h59m ago

Task "downloader" is "dead"
Task Resources
CPU      Memory   Disk     IOPS  Addresses
256 MHz  512 MiB  300 MiB  0     

Task Events:
Started At     = 2018-09-18T17:34:32Z
Finished At    = 2018-09-18T17:58:43Z
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                  Type            Description
2018-09-18T17:58:43Z  Not Restarting  Policy allows no restarts
2018-09-18T17:58:43Z  Terminated      Exit Code: 0, Exit Message: "OOM Killed"
2018-09-18T17:34:32Z  Started         Task started by client
2018-09-18T17:32:29Z  Driver          Downloading image wkurt/dr_downloaders:latest
2018-09-18T17:32:29Z  Task Setup      Building Task Directory
2018-09-18T17:32:29Z  Received        Task received by client
```

Where is the `Disk: 300MiB` coming from? We're not defining that ourselves, there is nothing mentioning disk in the `resources` stanza documentation, and this value will ultimately limit our ability to pack jobs if it's set to this 300MiB value, since we do all of our actual disk operations on a mounted disk, not the root HDD.

Similarly, in a `nomad status <node>`, I see:

```
Allocated Resources
CPU                Memory           Disk           IOPS
165084/198400 MHz  956 GiB/961 GiB  95 GiB/95 GiB  0/0
```

Even though the disk is actually only 20% used. Is this the culmination of all of those 300MiBs? What's going on here? Why isn't any of this documented?

**Comment by angrycub** [comment] 2018-09-18 21:31
You can find information about the ephemeral disk settings here: https://www.nomadproject.io/docs/job-specification/ephemeral_disk.html#size

**Comment by dadgar** [comment] 2018-09-18 21:59
@Miserlou Hey the link @angrycub gave you is the where you can define the disk resources. These are shared with all tasks in a group.

 The kill reason appears to be due to the task running out of memory rather than disk (just so that you are aware). I am going to close this issue since it is working as intended.

**Closed by dadgar** 2018-09-18 21:59 UTC

**Comment by Miserlou** [comment] 2018-09-19 15:27
Yeah, I know that's why it got killed, that's not what this ticket was about. Thanks though.

Why is it listed under Task Resources in the output if it isn't defined under Task Resources?

Besides being confusingly placed, the documentation/feature set also seems incomplete. For instance, there is no way to disable this, there is no way to set the volume path (we use small local file systems and very large mounts), and there is an undocumented minimum, so if you try to disable it by putting a value of 1 you'll get:
```
* minimum DiskMB value is 10; got 1
```
There is also no mention the interaction with the logging subsystem, which also cannot be disabled, so you may also end up with errors like:
```
* log storage (1 MB) must be less than requested disk capacity (1 MB))
```
