### ISSUE TITLE
Zombie service registered if Service name is changed

### ISSUE THREAD

**Issue by cleung2010** [hashicorp/nomad#658] opened 2016-01-07 20:56 UTC
I encountered an issue where a Task was registered to Consul as service under a specific name, but after changing the name the old task name was still registered, in addition to the new one.

Initially I had this JSON Service object in the job spec:
```
...
"Services": [
  {
    "Name": "helloworld",
    "PortLabel": "http"
  }
],
...
```
Running this job registered the `helloworld.service.dc1.consul` service. I then changed the service name to be the following:

```
...
"Services": [
  {
    "Name": "nomad-helloworld",
    "PortLabel": "http"
  }
],
...
```
This registered `nomad-helloworld.service.dc1.consul`, but `helloworld.service.dc1.consul` was also still registered.

**Comment by diptanu** [comment] 2016-01-07 21:51
@cleung2010 This will be fixed in 0.3

**Comment by diptanu** [comment] 2016-01-07 21:52
I see we keep registering the service once it's name changes infinitely but we do remove the old service. So not sure why you are seeing a zombie service, we know the problem but taking some time to handle updates to allocations in a nicer way.

**Comment by cleung2010** [comment] 2016-01-07 22:22
It seems that when I delete a job, the services on that job does not get deregistered. Don't know if this should be a separate issue.

**Comment by diptanu** [comment] 2016-01-07 22:27
@cleung2010 Can you post your job description for that? I can't reproduce.

**Comment by cleung2010** [comment] 2016-01-07 22:28
@diptanu regarding the job deletion? That's a mistake on my part, it's working as intended.

**Comment by diptanu** [comment] 2016-01-07 22:54
@cleung2010 Yeah I was asking about the job deletion. We know what's happening when the service name changes, a fix will land soon. Taking some time to handle updates properly.

**Comment by cleung2010** [comment] 2016-01-12 20:11
@diptanu by zombie service I meant the state of the service registration and not the actual service (that service does get removed/replaced).

**Closed** 2016-02-07 01:10 UTC
Labels: bug, discovery
