### ISSUE TITLE
Datacenter being starved of work

### ISSUE THREAD

**Issue by robsonj** [hashicorp/nomad#13933] opened 2022-07-28 17:30 UTC
### Nomad version
1.3.2

### Operating system and Environment details
CentOS 8.5

### Issue
We have 2 datacenter configured within nomad - call them A & B for the purpose of this issue. We have 4 namespaces, call then n1, n2,n3,n4 for the purpose of this issue. namespace n1 is always directed to datacenter A, and n2,n3,n4 are always directed to datacenter B.

These are all batch jobs, everything has the same job priority of 50.

If we submit enough batch jobs from n2,n3,n4 so that the resources are exhausted at datacenter B, they begin queuing up, as expected. Datacenter A remains idle, as expected.

if we then submit jobs from n1, for processing at datacenter A (which is idle), we'd expect them to be scheduled and begin processing.

However they seem to get stuck behind the jobs queued from n2,n3,n4, which once cleared, the n1 jobs eventually schedule to datacenter A - which has sat idle in the meantime.

### Reproduction steps
1. Create 2 datacenters, assign 1 client machine to each.
2. Create 2 namespaces.
3. submit jobs for the first namespace to go to the first datacenter, enough jobs for them to begin queueing due to lack of resources at that first datacenter. 
4. Submit jobs from the second namespace to go to the second datacenter (which is sat idle).
5. Watch the jobs for the second namespace queue, even though there are resources available at the datacenter that they are targeting.

 Expected Result
Evaluate the target datacenter when the job is evalutated, and schedule it due to there being available resources at the datacenter it is targeting

#### Actual Result
The jobs queue, even though there are available resources in the datacenter being targeted.

**Comment by tgross** [comment] 2022-07-28 18:32
Hi @robsonj! I wasn't able to reproduce the behavior you're seeing on either Nomad 1.2.5 or Nomad 1.3.2, so I suspect there's some clue we're missing for the behavior here. The observed behavior doesn't align very well with the internal model for how Nomad processes evaluations, either, so that suggests to me there's something else at play.

When a job gets dispatched, Nomad writes an Evaluation to the state store. That evaluation is enqueued immediately in the leader's eval broker for scheduling. If a sheduler can't create a plan that places all allocations in the job, it create a new "blocked" Evaluation that goes into a separate queue awaiting changes from the nodes (ex. new capacity comes on or an allocation exits). So there's no mechanism I can think of for evaluations to be "stuck" behind blocked evaluations. The exception would be if there are a _lot_ of evaluations in the eval broker, such that the schedulers aren't keeping up with all the work to be done. But that wouldn't be because of the client capacity, just a lot of evals.

A few things to look at to debug this:
* Take a look at the `nomad eval list` command, filtered by the namespaces you're interested in. You should see information about the evaluation status that'll help us figure out what's going on together. 
* It would also be helpful to look at `nomad eval status -namespace=X $eval_id` for the evaluations of the "stuck" dispatch.
* Take a look at the scheduler metrics described in [Monitoring Nomad - Scheduling](https://www.nomadproject.io/docs/operations/monitoring-nomad#scheduling) to see if the scheduler itself is making progress as expected.

---

Here's my failed reproduction...

I've got 2 small client nodes, one in each datacenter:

```
$ nomad node status
ID        DC     Name           Class    Drain  Eligibility  Status
3be0d5b9  dc1    nomad-client1  vagrant  false  eligible     ready
82470c43  dc2    nomad-client2  vagrant  false  eligible     ready

$ nomad node status 82470c43
Allocated Resources
CPU         Memory       Disk
0/2712 MHz  0 B/676 MiB  0 B/28 GiB

$ nomad node status 3be0d5b9
Allocated Resources
CPU         Memory       Disk
0/2712 MHz  0 B/676 MiB  0 B/30 GiB
```

I've also got 4 namespaces:

```
$ nomad namespace list
Name        Description
default     Default shared namespace
namespaceA  <none>
namespaceB  <none>
namespaceC  <none>
namespaceD  <none>
```

My job for the first datacenter looks like the following. The idea here is that when dispatched, it'll eat up 256MB of memory on the node and sit there for 15 minutes. We should be able to saturate `dc2` with just 3 of these.

```hcl
job "batchA" {
  type        = "batch"
  namespace = "namespaceA"
  datacenters = ["dc1"]

  parameterized {
    payload = "required"
  }

  group "group" {
    task "task" {

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "/bin/sh"
        args    = ["-c", "cat local/payload.txt; sleep 900"]
      }

      dispatch_payload {
        file = "payload.txt"
      }

      resources {
        cpu    = 256
        memory = 256
      }

    }
  }
}
```

My jobs for the second datacenter are identical except for `namespace` and `datacenters` field:

```hcl
job "batchB" {
  type        = "batch"
  namespace   = "namespaceB"
  datacenters = ["dc2"]
  ...
```

```hcl
job "batchC" {
  type        = "batch"
  namespace   = "namespaceC"
  datacenters = ["dc2"]
  ...
```

```hcl
job "batchD" {
  type        = "batch"
  namespace   = "namespaceD"
  datacenters = ["dc2"]
  ...
```

I register all four jobs successfully, as expected:

```
$ nomad job run ./batchA.nomad
Job registration successful
$ nomad job run ./batchB.nomad
Job registration successful
$ nomad job run ./batchC.nomad
Job registration successful
$ nomad job run ./batchD.nomad
Job registration successful

$ nomad job status -namespace='*'
ID      Namespace   Type                 Priority  Status   Submit Date
batchA  namespaceA  batch/parameterized  50        running  2022-07-28T14:12:38-04:00
batchB  namespaceB  batch/parameterized  50        running  2022-07-28T14:12:41-04:00
batchC  namespaceC  batch/parameterized  50        running  2022-07-28T14:12:43-04:00
batchD  namespaceD  batch/parameterized  50        running  2022-07-28T14:12:45-04:00
```

Then I'll dispatch one each of jobs `batchB`, `batchC`, and `batchD`, which will be intended for dc2 which is node `82470c43`. We should see that the `batchD` job doesn't get to run because it runs out of resources on the host.

```
# write a dispatch payload file
$ echo 'hello' > world.txt

$ nomad job dispatch -detach -namespace namespaceB batchB ./world.txt
Dispatched Job ID = batchB/dispatch-1659031986-255233ce
Evaluation ID     = 9049c46b

$ nomad job dispatch -detach -namespace namespaceC batchC ./world.txt
Dispatched Job ID = batchC/dispatch-1659031990-48ae87df
Evaluation ID     = 9a727b8f

$ nomad job dispatch -detach -namespace namespaceD batchD ./world.txt
Dispatched Job ID = batchD/dispatch-1659031994-5c6da220
Evaluation ID     = fe31163e

$ nomad job status -namespace='*'
ID                                   Namespace   Type                 Priority  Status   Submit Date
batchA                               namespaceA  batch/parameterized  50        running  2022-07-28T14:12:38-04:00
batchB                               namespaceB  batch/parameterized  50        running  2022-07-28T14:12:41-04:00
batchB/dispatch-1659031986-255233ce  namespaceB  batch                50        running  2022-07-28T14:13:06-04:00
batchC                               namespaceC  batch/parameterized  50        running  2022-07-28T14:12:43-04:00
batchC/dispatch-1659031990-48ae87df  namespaceC  batch                50        running  2022-07-28T14:13:10-04:00
batchD                               namespaceD  batch/parameterized  50        running  2022-07-28T14:12:45-04:00
batchD/dispatch-1659031994-5c6da220  namespaceD  batch                50        pending  2022-07-28T14:13:14-04:00

$ nomad eval status -namespace namespaceD fe31163e
ID                 = fe31163e
Create Time        = 40s ago
Modify Time        = 38s ago
Status             = complete
Status Description = complete
Type               = batch
TriggeredBy        = job-register
Job ID             = batchD/dispatch-1659031994-5c6da220
Namespace          = namespaceD
Priority           = 50
Placement Failures = true

Failed Placements
Task Group "group" (failed to place 1 allocation):
  * Resources exhausted on 1 nodes
  * Class "vagrant" exhausted on 1 nodes
  * Dimension "memory" exhausted on 1 nodes

Evaluation "9d1d2543" waiting for additional capacity to place remainder
```

And then at that point we'll dispatch `batchA`.

```
$ nomad job dispatch -detach -namespace namespaceA batchA ./world.txt
Dispatched Job ID = batchA/dispatch-1659032052-a1b3fe2a
Evaluation ID     = 5c4ea396
```

If we look at the job list, we can see the dispatch for `batchA` is running:

```
$ nomad job status -namespace='*'
ID                                   Namespace   Type                 Priority  Status   Submit Date
batchA                               namespaceA  batch/parameterized  50        running  2022-07-28T14:12:38-04:00
batchA/dispatch-1659032052-a1b3fe2a  namespaceA  batch                50        running  2022-07-28T14:14:12-04:00
batchB                               namespaceB  batch/parameterized  50        running  2022-07-28T14:12:41-04:00
batchB/dispatch-1659031986-255233ce  namespaceB  batch                50        running  2022-07-28T14:13:06-04:00
batchC                               namespaceC  batch/parameterized  50        running  2022-07-28T14:12:43-04:00
batchC/dispatch-1659031990-48ae87df  namespaceC  batch                50        running  2022-07-28T14:13:10-04:00
batchD                               namespaceD  batch/parameterized  50        running  2022-07-28T14:12:45-04:00
batchD/dispatch-1659031994-5c6da220  namespaceD  batch                50        pending  2022-07-28T14:13:14-04:00
```

We can also look at the eval list to see that we've got one evaluation for the queued-up alloc that's still in a blocked state. That's the one that's waiting for more resources in dc2.

```
$ nomad eval list -namespace='*'
ID        Priority  Triggered By    Job ID                               Namespace   Node ID  Status    Placement Failures
5c4ea396  50        job-register    batchA/dispatch-1659032052-a1b3fe2a  namespaceA  <none>   complete  false
9d1d2543  50        queued-allocs   batchD/dispatch-1659031994-5c6da220  namespaceD  <none>   blocked   N/A - In Progress
fe31163e  50        job-register    batchD/dispatch-1659031994-5c6da220  namespaceD  <none>   complete  true
9a727b8f  50        job-register    batchC/dispatch-1659031990-48ae87df  namespaceC  <none>   complete  false
9049c46b  50        job-register    batchB/dispatch-1659031986-255233ce  namespaceB  <none>   complete  false
04471fb8  50        job-deregister  batchB/dispatch-1659031790-2aa09685  namespaceB  <none>   complete  false
47174da5  50        job-register    batchB/dispatch-1659031790-2aa09685  namespaceB  <none>   complete  false
```

**Comment by robsonj** [comment] 2022-07-28 18:37
Hmmm, thank you for taking the time to look at this so quickly. I am wondering if its related to how the jobs were submitted. We had a lot of one task jobs which was overwhelming nomad (180,000ish), so I'm wondering if it was taking a long time to even eval the jobs. 

generally we try to submit jobs with multiple tasks to drastically lower the job counts, but we're in the process of onboarding an internal group

**Comment by robsonj** [comment] 2022-07-28 18:43
correction, I think it was in the order of 15,000 pending jobs at the time we saw this. I will see if I can recreate the scenario on a VM as maybe there is some missing facet here

**Comment by Fuco1** [comment] 2022-08-02 11:49
@robsonj this is maybe not really related, but the difference between 10k jobs with count = 1 and one job with count = 10k is **EXTREME**.  Our pipelines were constantly crashing and freezing and killing the entire nomad environment, even on very high-end leader machines (which honestly didn't make a difference at all, going from 2 core to even 64 core).

We used to run 40k jobs with count = 1, now we run 5 jobs with count 10-20k, the difference in stability is massive and everything in Nomad happens instantly.  We've been fighting the migration to this new scheduling system but finally bit the bullet and regret not doing it a year earlier.  So I can definitely recommend this approach. (when using count = X, you can use nomad allocation index to differentiate the tasks, if needed using some external dispatch table).

**Comment by robsonj** [comment] 2022-08-02 12:11
> @robsonj this is maybe not really related, but the difference between 10k jobs with count = 1 and one job with count = 10k is **EXTREME**. Our pipelines were constantly crashing and freezing and killing the entire nomad environment, even on very high-end leader machines (which honestly didn't make a difference at all, going from 2 core to even 64 core).
> 
> We used to run 40k jobs with count = 1, now we run 5 jobs with count 10-20k, the difference in stability is massive and everything in Nomad happens instantly. We've been fighting the migration to this new scheduling system but finally bit the bullet and regret not doing it a year earlier. So I can definitely recommend this approach. (when using count = X, you can use nomad allocation index to differentiate the tasks, if needed using some external dispatch table).

Your comment is extremely useful! I’ve hunted around for this kind of job sizing info and haven’t been able to find much at all. We swapped out our VMs for high powered server  nodes with 32cores and 64gb (moving to 128gb) today. We then tried 10,000 jobs with 50 tasks, it ran out of memory. Today I’m gonna look to reduce the job count and increase the tasks per jobs, see if that helps

**Comment by tgross** [comment] 2022-08-02 12:42
As noted in #13935, the workload pattern you've got here is going to push hard on memory requirements. Something to keep in mind is that Nomad's state store is kept entirely in-memory. The raft logs that are replicated to all nodes to create that state are persisted to disk and those are rehydrated into the in-memory state store on start. 

From @Fuco1's example of 40k jobs with count=1, that means 40k `Job` structs + 40k `Evaluation` structs had to be persisted for a single deployment of all those jobs, and the schedulers had to process 40k computationally expensive evaluations. Whereas 5 jobs with count=10k means only _5_ `Job` and `Evaluation` structs in memory, and only 5 computationally expensive evaluations.

Nomad can be sized to handle the scale you're talking about, but you'll need to invest some time in making sure you've got a handle on the [scheduler internals](https://www.nomadproject.io/docs/concepts/scheduling/scheduling) and figuring out where the bottlenecks are for your particular workload (see [Key Performance Indiciators](https://www.nomadproject.io/docs/operations/monitoring-nomad#key-performance-indicators). If you're willing to share some data here we may be able to provide more specific guidance. You may also want to take a look at the [2M Container Challenge](https://www.hashicorp.com/resources/nomad-the-2-million-container-challenge) project that we did a while back to demonstrate this sort of thing.

**Comment by robsonj** [comment] 2022-08-02 13:19
> As noted in #13935, the workload pattern you've got here is going to push hard on memory requirements. Something to keep in mind is that Nomad's state store is kept entirely in-memory. The raft logs that are replicated to all nodes to create that state are persisted to disk and those are rehydrated into the in-memory state store on start.
> 
> From @Fuco1's example of 40k jobs with count=1, that means 40k `Job` structs + 40k `Evaluation` structs had to be persisted for a single deployment of all those jobs, and the schedulers had to process 40k computationally expensive evaluations. Whereas 5 jobs with count=10k means only _5_ `Job` and `Evaluation` structs in memory, and only 5 computationally expensive evaluations.
> 
> Nomad can be sized to handle the scale you're talking about, but you'll need to invest some time in making sure you've got a handle on the [scheduler internals](https://www.nomadproject.io/docs/concepts/scheduling/scheduling) and figuring out where the bottlenecks are for your particular workload (see [Key Performance Indiciators](https://www.nomadproject.io/docs/operations/monitoring-nomad#key-performance-indicators). If you're willing to share some data here we may be able to provide more specific guidance. You may also want to take a look at the [2M Container Challenge](https://www.hashicorp.com/resources/nomad-the-2-million-container-challenge) project that we did a while back to demonstrate this sort of thing.

Hi Tim. Thanks for this, I'll follow up on the articles, I am more than happy to share data if you have a email I can correspond on.

This has been extremely useful, everything points to less jobs, more tasks, which is what I'm starting to trail now.

**Comment by robsonj** [comment] 2022-08-03 01:59
So I tried turning this on its head. We added 3 32core 128gb servers - so those make up our nomad servers, and I moved from having a lot of jobs with a few tasks to having 20 jobs each with 10,000 task groups (each group has 3 tasks inside it). We pretty quickly exhausted the 128gb on the 3 server nodes.

I must be doing something wrong, at the minute I'm concluding that nomad can't really handle anything much about 5,000-10,000 queued tasks for scheduling, which doesn't feel like its the correct conclusion.

The UI certainly falls apart with jobs consisting of that many tasks (DoS's the browser when trying to view the individual 10,000 task group job), but I was prepared for that fact before trying based on previous observations of the UI.

Our tasks are all batch tasks, they are quick in nature, some only run for 60-90 seconds, maybe that is overwhelming the scheduler in some way. 

I was wondering if turning off all of the schedulers but the batch scheduler would help. Also would running more than the default 1 scheduler per core help, or maybe run less?

**Comment by robsonj** [comment] 2022-08-03 02:15
Another detail which may be critical, is we have a lot of task groups in the queued state (by design on our part) as our clients are capable of running about 300-400 parallel tasks at any one time. So maybe the high number of failed allocation placements is causing the excessive memory growth?

My final thought is to just off load that queue of pending work to a home grown webapp and implement some sort of queue on demand to take the load off of nomad, which I’d rather not do.

**Comment by dvusboy** [comment] 2022-08-03 02:25
The change from lots of jobs to big jobs with lots of distinct task-groups is not going to help with the memory consumption problem. A big job with a single task-group but large `count`, that'd help. Almost like you need to have a separate service to tell each of your batch task what the task details are. What Nomad needs to keep track in memory is tremendous.

**Comment by tgross** [comment] 2022-08-03 13:19
> We pretty quickly exhausted the 128gb on the 3 server nodes.

RSS? Servers under these conditions are also going to be hitting disk a _lot_ so I'd want to know more detailed memory metrics here. That will also show up indirectly in the key performance indicator metrics I linked above.

> The UI certainly falls apart with jobs consisting of that many tasks (DoS's the browser when trying to view the individual 10,000 task group job), but I was prepared for that fact before trying based on previous observations of the UI.

Yeah, we don't have pagination everywhere yet. That's coming and we have open issues for it.

> Our tasks are all batch tasks, they are quick in nature, some only run for 60-90 seconds, maybe that is overwhelming the scheduler in some way.
> 
> I was wondering if turning off all of the schedulers but the batch scheduler would help. Also would running more than the default 1 scheduler per core help, or maybe run less?

Maybe, but what does "overwhelm" mean here? The metrics that I've pointed out previously will tell you whether the scheduler is stalled on raft, on the eval broker, etc. Nomad will tell you where it hurts! 😀 That'll let us make more specific recommendations.

>  So maybe the high number of failed allocation placements is causing the excessive memory growth?

It certainly won't help (but again, what do the metrics say? how many evaluations are in each state?). Each incomplete placement will spawn a new Evaluation in the blocked state. That evaluation will get enqueued in the eval broker and need to be dequeued and evaluated again once there's a change in cluster state.

> The change from lots of jobs to big jobs with lots of distinct task-groups is not going to help with the memory consumption problem.

It might help _some_, because there won't be as many Evaluations initially created. But each task group creates `count` Allocations. But because the cluster doesn't actually have enough room, each Evaluation will spawn another Evaluation. The Evaluation will create a few Allocations and then spawn another Evaluation, and so on and so on until eventually the job's work is complete. What's worse, is that the processed Evaluations will be marked complete, but are still sitting around in memory_ so that you can check their status via `nomad eval status`.

So without you sharing more specific metrics from the cluster or the jobspec you're using, @robsonj, I can't make more specific recommendations. There's an internal-facing mailing list nomad-oss-debug@hashicorp.com where you can submit jobspecs and debug logs that you don't want to share publicly, but that's one-way so it'd probably be easier if you can post here with data masked as needed. (Plus you'll be helping out the rest of the OSS community who might face similar issues.)

A couple of suggestions I can make from what you have shared:
* Drop the [`eval_gc_threshold`](https://www.nomadproject.io/docs/configuration/server#eval_gc_threshold) to something very short (as low as the 5 min GC interval or whatever you're willing to tolerate in terms of observability loss). That'll make it so that the completed Evaluations described above are getting reaped every 5 min, which will help reduce memory pressure.
* Take a heap profile (from `/debug/pprof/heap?debug=1` with [`enable_debug = true`](https://www.nomadproject.io/docs/configuration#enable_debug)). That'll tell us which specific objects are eating all the memory.

**Comment by robsonj** [comment] 2022-08-03 16:50
Thanks again @tgross . While I haven't got you the stats yet, we had already reduced the `eval_gc_threshold` to 30seconds. 

This morning I grouped 18 of our tasks into each task group, so should effectively reduce the evals 18times. Its looking much better, I have 500,000+ tasks queued across 50 jobs with 556 groups of 18 tasks in each. Server memory at about 36gb, so its def. the evals that are causing the issue.

The drawback of course, is that if we happen to group a longer running task with a bunch of quick ones, the machine resources will not be considered available, until the long task has completed, but I'll cross that bridge once we can get to 1,000,000 queued tasks without melting things.

**Comment by Fuco1** [comment] 2022-08-05 13:32
Just as @dvusboy said, the `count` is a property on the task group which schedules (allocates) *the same* task group multiple times.  We also tried having one job with thousands of task groups, but that's not good either.

What we have now is an external mapper (in form of files) from allocation id to the input data.  We run time series forecasting so each allocation of the task group computes some hundred forecasts.  The allocation index is used to derive a path to blob storage with more detailed task description .csv file.

Since you run batch jobs I'd assume they are only of a few general kinds.  For each kind, run a new job with count = X and then use allocation id to get the correct inputs for that "chunk" of the overall computation.  This is the only way we found over the three years of using nomad how to really scale it up to thousands of CPUs/agents.

This is our actual code (typescript) from production, omiting some details: we first fetch an existing parameterized job deployed on nomad, which only serves as a template (notice you can't dispatch jobs with count, so we have to "clone" them).

```typescript
	const job = await nomad.getJob(environment, {
		namespace: FORECAST_JOB_NAMESPACE,
	});
```

Then we create a new job:

```typescript
const newJob: NomadJob = {
		...job,    // copy all the old properties, except...
		TaskGroups: [
			{
				...job.TaskGroups[0],
				Count: inputs.length,     // set count here to the number of chunks you are computing
				Tasks: [
					{
						...job.TaskGroups[0].Tasks[0],
						Templates: [
							...job.TaskGroups[0].Tasks[0].Templates,
							{
								EmbeddedTmpl: JSON.stringify(config) + "\n",   /// here we generate some config template.
								DestPath: "local/config.yaml",
							},
						],
					},
				],
			},
		],
		Priority: Math.min(Math.max(minPriority - 10, 0), 100),
		ParameterizedJob: null,     /// set parameterized to null so it becomes regular batch job.
		Name: newName,   // give the job some new name + id
		ID: newName,
		Meta: {
			...job.Meta,
			FORECAST_UUID: uuid,
			SQL_HOST: config.db.host,
			INPUT_FORECAST_UUID: sourceContainer,
		},
	}
```

and finally we submit this new job

```typescript
	await nomad.createJob(newJob).catch((e) => {
		console.error(e);
	});
```

**Comment by robsonj** [comment] 2022-08-05 13:42
Thanks @Fuco1 , this is similar to what we are doing. I had some more success by increasing the number of tasks in a task group (1 initially, now 18, trying 72 (the max I can go before we don't have a server large enough to schedule the task group)), but due to the number of pending task groups we have queued, it still eventually eats up memory it seems. It really is the tasks that are pending that cause the issue, the longer they pend, the more memory is used due to failed evals.

We're trying to queue 180k allocations against 336 CPU's, hence we likely have much longer time in pending state, which is the issue.

**Comment by tgross** [comment] 2022-08-05 14:37
> I had some more success by increasing the number of tasks in a task group (1 initially, now 18, trying 72 (the max I can go before we don't have a server large enough to schedule the task group))

Remember that all the tasks in a single task group have to be scheduled _together_ in the allocation. So having a bunch of tasks in the same task group actually makes it harder for the scheduler to find space for them. Ex.
* If you have 1 job with count=10 with 10 tasks each with 1000MB memory, the scheduler gets 1 Evaluation of 10 Allocations, and needs to find 10 blocks of 10000MB.
* If you have 1 job with count=100 with 1 task each with 1000MB, the scheduler gets 1 Evaluation of 100 Allocations, and needs to find 100 blocks of 1000MB.
* If you have 10 jobs with with count=10 with 1 task each 1000MB memory, the scheduler gets 10 Evaluations of 10 Allocations, and each evaluation needs to find 10 blocks of 1000MB.

> , but due to the number of pending task groups we have queued, it still eventually eats up memory it seems. It really is the tasks that are pending that cause the issue, the longer they pend, the more memory is used due to failed evals.

Yeah you're kind of working against the scheduler here by giving it a lot of work it can't place. When I ran ML batch workloads on Nomad (back before I was on the team), I solved this similar to how @Fuco1 did; our pipeline would submit jobs into a queue that a worker would submit to the scheduler and not ACK the dequeue if there wasn't any room on the cluster. The nice thing about this was that I could autoscale my set of client nodes by monitoring the queue depth.

**Comment by robsonj** [comment] 2022-08-05 15:14
Yep @tgross I sized the task group to 72 which means one task group fits on one of our servers exactly. My problem is the client wants to queue up a bunch of work that can spend days in the pending state. An early thought of mine was to implement some just in time queuing outside of nomad. I think that maybe the only approach available to me at this point.

**Comment by robsonj** [comment] 2022-08-09 15:48
Moved to having 500 taskgroups per job each with 1 task, the task runs a bash script with 72 of our command line processes in it (so 36,000 commands (500*72) per job in total), running sequentially. This solves the issue of the taskgroup size as it goes from being a breadth first to a depth first kinda approach. So now we have 5 jobs each with the 500 taskgroups, which does keep the UI stable. Each task group of course takes longer to run, but we can run many of them in parallel, though there are still gonna be many placement failures, as we're essentially queuing up alot more work than we have CPUs for, which is what we wanna do.

Still the memory grows over night. I have enable debug and will send over a heap dump. Do you need the heap dump for each of the server @tgross  or just the lead server?

Cheers
Jonathan

**Comment by tgross** [comment] 2022-08-15 18:49
Hi @robsonj! I was on vacation last week and didn't get a chance to look at this until today. But tl;dr I analyzed the heap dump and almost the entirety of the heap consists of encoding what looks like large `template` blocks.

With a go toolchain, you can examine the heapdump you provided as follows:

```
$ go tool pprof ./path/to/nomad_1.3.2/nomad ./heapdump.txt
File: nomad
Type: inuse_space
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) web
```

This opens your browser with a handy SVG file, which I've uploaded as a gist [here (ref pprof001.svg)](https://gist.githubusercontent.com/tgross/9c3e8edf8ee2e3977683d1d4937e6160/raw/df78fadb956cee19c5412762f82e7a7773099210/pprof001.svg). The heap here is ~36.4GiB. You can trace "branches" of the heap tree from top to bottom. On the left hand side there's a branch starting at the Nomad HTTP server, with a leaf of ~28.7GiB (77%) where we're allocating large bytes slices in the JSON encoder. If you trace up from that leaf you can find it forks at `structs.(*Template).CodecEncodeSelf` and that fork represents fully 55% of the heap!


<img width="455" alt="Screen Shot 2022-08-15 at 2 26 57 PM" src="https://user-images.githubusercontent.com/1409219/184695814-00e78fef-a160-4a96-a50b-9d4b4e49a58f.png">


Likewise, on the right-hand side of the graph we can see a similar large leaf representing ~12% of the heap, and that has the template encoding in its path as well.

Keep in mind this is only the heap memory. Anything that gets written to disk (i.e. the raft logs) will show up in the disk cache for the process, and there'll be plenty of memory on the stack as well associated with this encoding process. And if this server isn't the leader note that the leader will have a similar heap profile on the RPC handlers instead.

So you've got huge jobs with 500 task groups per job, each of which contains some (chunky?) template. And that's getting encoded every single time a particular HTTP API is getting hit, to the tune of 11MiB per task group in JSON encoding alone. That suggests this API is getting hit quite a lot. Unfortunately because of the way the HTTP server is constructed we can't tell which API is getting hit from this heap dump.

Here's where you'll need to look at your metrics. The `nomad.nomad.job.*` metrics will show the timing of the RPC calls that the HTTP server ends up making, but if you don't already know what's being hit you'll need to check your Nomad logs for the job endpoints to get the counts. My _guess_ is that it's most likely the [Read Job API](https://www.nomadproject.io/api-docs/jobs#read-job) but you should definitely verify that yourself.

And as noted above, you almost certainly have lots of evaluations in the `blocked` state. But without you querying that information from your metrics I can't verify that for you. 

You want to avoid trying to use Nomad as queue if you can, but honestly from the heap dump the biggest recommendation I can give you right now is to find out what's hitting the HTTP API so much and dial it back by using [blocking queries](https://www.nomadproject.io/api-docs#blocking-queries) and rate limiting yourself at the client.

**Comment by tgross** [comment] 2022-08-16 12:51
> but honestly from the heap dump the biggest recommendation I can give you right now is to find out what's hitting the HTTP API so much and dial it back by using [blocking queries](https://www.nomadproject.io/api-docs#blocking-queries) and rate limiting yourself at the client.

It occurs to me that you may still be trying to use the UI even though it simply isn't going to work without pagination. Are you just sitting on the jobs page looking to refresh job status? At the scale you're operating at I would strongly recommend using the HTTP API (thoughtfully, as noted above), rather than expecting the UI to work for you when there's a known flaw in pagination.

**Comment by tgross** [comment] 2022-09-29 20:49
Doing some issue cleanup and it looks like we have a solid idea at this point of where all the memory went. I'm going to close this out but if you have more context to add, we can certainly continue the conversation (and reopen if necessary). Thanks!

**Closed by tgross** 2022-09-29 20:49 UTC
Labels: type/bug, stage/waiting-reply, theme/scheduling
