### ISSUE TITLE
nomad client fails to submit job on a windows 10

### ISSUE THREAD

**Issue by harkamals** [hashicorp/nomad#4389] opened 2018-06-07 06:20 UTC
### Nomad version
Nomad v0.8.3

### Operating system and Environment details
Windows 10

### Issue
nomad client fails to submit job
Error getting job struct: Error getting jobfile from "example.nomad": symlink C:\ws\example.nomad C:\temp\jobfile697008935: A required privilege is not held by the client.

### Reproduction steps
nomad job run example.nomad

### Job file (if appropriate)
example.nomad

**Comment by angrycub** [comment] 2018-06-07 13:10
This appears to be a duplicate of #3491.  I'm going to go ahead and close it in favor of the older issue.

**Closed by angrycub** 2018-06-07 13:10 UTC
