### ISSUE TITLE
Nomad re-renders templates every few minutes despite much higher secret TTL

### ISSUE THREAD

**Issue by karelorigin** [hashicorp/nomad#17398] opened 2023-06-02 14:25 UTC
### Nomad version
Output from `nomad version`

```
Nomad v1.5.6
BuildDate 2023-05-19T18:26:13Z
Revision 8af70885c02ab921dedbdf6bc406a1e886866f80
```

#### Nomad Server

```
Nomad v1.5.6
BuildDate 2023-05-19T18:26:13Z
Revision 8af70885c02ab921dedbdf6bc406a1e886866f80
```

```
Vault v1.13.0-dev1 ('ac5997ef1dd9e7bd2e89f64ed1f8b721e60ce641+CHANGES'), built 2023-02-06T14:28:16Z
```

```
Consul v1.14.3
Revision bd257019
Build Date 2022-12-13T17:13:55Z
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

#### Nomad Client

```
Nomad v1.5.6
BuildDate 2023-05-19T18:26:13Z
Revision 8af70885c02ab921dedbdf6bc406a1e886866f80
```

```
Vault v1.13.0-dev1 ('ac5997ef1dd9e7bd2e89f64ed1f8b721e60ce641+CHANGES'), built 2023-02-06T14:28:16Z
```

```
Consul v1.14.3
Revision bd257019
Build Date 2022-12-13T17:13:55Z
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

### Issue

Nomad keeps re-rendering templates every ~2 minutes or so, which forces the allocation to restart. 

I checked Vault's active leases to make sure that they were indeed still valid, and this is what I got:

| issued_at                      | expires_at                     | id                                             |
|--------------------------------|--------------------------------|------------------------------------------------|
| 2023-06-02T13:42:47.392765095Z | 2023-06-03T13:42:47.531957624Z | postgres/creds/master/rHjTV3hn6PU3sNpyWyTN3JCN |
| 2023-06-02T13:44:47.465583446Z | 2023-06-03T13:44:47.548960263Z | postgres/creds/master/SVZ4IbtmIYhB3b4jRlHYlyVZ |
| 2023-06-02T13:44:47.517964824Z | 2023-06-03T13:44:47.639492123Z | postgres/creds/master/i5anY6USygU3qMHGcFW3mz9W |
| 2023-06-02T13:46:47.668052185Z | 2023-06-03T13:46:47.76473802Z  | postgres/creds/master/YgjtAlimVvaUYa02v9jLIqbL |
| 2023-06-02T13:46:47.724985922Z | 2023-06-03T13:46:47.824646623Z | postgres/creds/master/DrviOj2dLgiiLezO8tifSf7L |
| 2023-06-02T13:48:47.849705356Z | 2023-06-03T13:48:47.074941793Z | postgres/creds/master/jvE8j7gkHoSVfND1WxxEF3Eq |
| 2023-06-02T13:48:47.917406152Z | 2023-06-03T13:48:47.092322846Z | postgres/creds/master/cPaSB7LyU2AtVu6xVAP0LTZm |
| 2023-06-02T13:50:47.975874635Z | 2023-06-03T13:50:47.127023078Z | postgres/creds/master/w6H6RieuoJWPI1AQ7zZYsnX3 |
| 2023-06-02T13:50:48.036771929Z | 2023-06-03T13:50:48.163245115Z | postgres/creds/master/8OLl6vWxJNg6Ecfxx2CK5o4Z |
| 2023-06-02T13:52:48.156546964Z | 2023-06-03T13:52:48.256558224Z | postgres/creds/master/gqAeIKBl2e7aD2viVb8ijKDc |
| 2023-06-02T13:52:48.207491713Z | 2023-06-03T13:52:48.315285478Z | postgres/creds/master/DJoCgHUNnfWGK2yz9lZhZ7fw |
| 2023-06-02T13:54:48.166340475Z | 2023-06-03T13:54:48.248564036Z | postgres/creds/master/3M8Ny9rSQXXWobnjOezgIjAj |
| 2023-06-02T13:54:48.225739957Z | 2023-06-03T13:54:48.370442382Z | postgres/creds/master/JyHgRgnGkWQBnMiCyrdr18x1 |
| 2023-06-02T13:56:48.660700681Z | 2023-06-03T13:56:48.769047036Z | postgres/creds/master/PCpKNZHesoEH2P7elZJys2SR |
| 2023-06-02T13:56:48.746860939Z | 2023-06-03T13:56:48.8385467Z   | postgres/creds/master/IXAEMx08hKqNTvLBKklHtrWL |

The secrets are valid for at least another day.

#### Expected Result

Nomad should respect the generated secret's lease and re-render when appropriate, not on an unrelated interval.

#### Actual Result

Template re-renders every few minutes regardless of the secret's TTL.

### Job file (if appropriate)

```hcl
# Dynamically retrieve postgres address and generate credentials
template {
  destination = "secrets/postgres.env"
  env         = true
  change_mode = "restart"
  data        = <<-EOH
  {{- with service "postgres@dc1" -}}
  {{- with index . 0 -}}
  DB_HOST={{ .Address }}
  DB_PORT={{ .Port }}
  {{ end }}
  {{ end }}
  {{- with secret "postgres/creds/master" -}}
  DB_USER={{ .Data.username }}
  DB_PASSWORD={{ .Data.password }}
  {{- end }}
  DB_NAME=foo
  EOH
}

# Dynamically set RabbitMQ address and generate credentials
template {
  destination = "secrets/rabbitmq.env"
  env         = true
  change_mode = "restart"
  data        = <<-EOH
  {{- with service "rabbitmq@dc1" -}}
  {{- with index . 0 -}}
  RABBITMQ_HOST={{.Address}}
  RABBITMQ_PORT={{.Port}}
  {{ end }}
  {{ end }}
  {{- with secret "rabbitmq/creds/nomad" -}}
  RABBITMQ_USER={{ .Data.username }}
  RABBITMQ_PASSWORD={{ .Data.password }}
  {{- end }}
  EOH
}
```

**Note: I did consider that perhaps the service address could be the issue, but this seems to be constant across re-renders, so we should be able to safely rule out that it could be responsible.**

**Comment by tgross** [comment] 2023-06-20 17:25
Hi @karelorigin I agree that this sounds like a dupe of https://github.com/hashicorp/nomad/issues/16846. I'm going to close this issue and link to it from #16846 for more context once we get some more eyes on that investigation.

**Closed by tgross** 2023-06-20 17:25 UTC
Labels: type/bug
