### ISSUE TITLE
nomad agent should use the bind addr

### ISSUE THREAD

**Issue by i0rek** [hashicorp/nomad#359] opened 2015-10-29 10:44 UTC
I am starting nomad in AWS with the `-bind` flag:

```
exec nomad agent -config /opt/nomad.d/ -bind 10.127.130.175:4646
```

When I run `$ nomad agent-info` it fails with: `Error querying agent info: failed querying self endpoint: Get http://127.0.0.1:4646/v1/agent/self: dial tcp 127.0.0.1:4646: getsockopt: connection refused`. But running `$ NOMAD_ADDR=http://10.127.130.175:4646" nomad agent-info` fixes it.

I think the agent should use the `bind` address instead of the loopback.

**Comment by dadgar** [comment] 2015-10-30 00:05
Hey,

The Nomad CLI commands are calling APIs exposed by the local Nomad Agent which can bind to any interface. The implication of this is that when you run Nomad CLI commands, it does not know the bind address of the Nomad Agent so it tries to resolve the address by looking in the environment variable $NOMAD_ADDR, trying a default address or by using the address passed to the command with the flag `-address`.

You can see this by running help on any of the CLI commands. I am going to close this ticket because it is working as intended. Feel free to let me know if you have any questions.

**Closed by dadgar** 2015-10-30 00:05 UTC

**Comment by i0rek** [comment] 2015-10-30 08:57
I understand your reasoning. I was thinking that there is no way that the local agent can be reached if it is binded to something else. and since the client ships with the agent, I did expect it to know about the bind. 

Thank you for your help and your work!
