### ISSUE TITLE
subprocess of task is not shutdown when stop job on Windows

### ISSUE THREAD

**Issue by Bingqiang-Jing** [hashicorp/nomad#7722] opened 2020-04-15 08:47 UTC
### Nomad version
v0.10.4

### Operating system and Environment details
Windows 10

### Issue
I start a task, it create a few of subprocess. when stop job, only parent process is shutdown, the child process is still alive.

Do you have any suggestions about this? 
Thanks.

**Comment by tgross** [comment] 2020-04-15 12:16
Hi @Bingqiang-Jing! Which executor are you running here? It might be helpful to know a bit more about the subprocesses that are getting forked -- are they being daemonized so that the task's first process is no longer their parent?

**Comment by Bingqiang-Jing** [comment] 2020-04-16 02:22
thanks for your reply @tgross 
below is my job snippet
```
task "rtspserver-dongta-03-exe" { 
            driver = "raw_exec"
            config {
                command = "C:\\Program Files (x86)\\iseetech\\stitch\\WatchDogRTSPService.exe"
                args = ["-p", "C:\\Program Files (x86)\\iseetech\\stitch\\setting\\dongta-03"]
            }
        }
````

`WatchDogRTSPService.exe`  is Python script  compiling with Pyinstaller,  it creates subprocess with Python interface `subprocess.Popen(cmd)`,  then subprocess run a `rtsp_server.exe` written in C++.

**Comment by tgross** [comment] 2020-04-17 18:30
The `rtsp_server.exe`'s parent PID is the watchdog process? It's not being re-parented to PID4? And the watchdog isn't passing `shell=true` into `subprocess.Popen`?

Does the watchdog process mask signals sent? On Windows [we send `SIGTERM` for graceful shutdown](https://github.com/hashicorp/nomad/blob/095c2a9890ef4f26f2fd238d38276fe7a8134fd2/drivers/docker/driver.go#L1241-L1247), followed by `SIGKILL` after the timeout.

**Comment by tgross** [comment] 2020-06-22 13:18
Going to close this as a duplicate of https://github.com/hashicorp/nomad/issues/7747

**Closed by tgross** 2020-06-22 13:18 UTC
Labels: platform-windows, question
